### ISSUE TITLE
Winget is missing in system user context

### ISSUE THREAD

**Issue by sokatra** [microsoft/winget-cli#1000]
# Brief description of your issue
if i run winget as system user .. it does not find the program
'winget' is not recognized as an internal or external command

Please use this section to describe your issue.   This could be a repeat of the title, or maybe you have more to say.
-->
# Steps to reproduce

run a system user cmd with
psexec64.exe -sid cmd.exe

# Expected behavior

winget should also run as system user .so i can use deployment software which is using that account

# Actual behavior

winget does not run(not found) in system context ..only in normal user accounts

# Environment
Windows 10 20H2
```none
[winget --info] Windows Package Manager v1.0.11451
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version
this version 
https://github.com/microsoft/winget-cli/releases/download/v1.0.11451/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle
Any other software? no
```

**Comment by denelon** [comment]
@sokatra I believe this is related to a few other issues that have already been submitted. We might end up closing this one as a duplicate for one of those. We seem to have narrowed the issue down to the fact that the MSIX doesn't get registered for the System context.

Take a look at https://github.com/microsoft/winget-cli/discussions/962 Usage with System Account

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/discussions/962#discussioncomment-736278
