### ISSUE TITLE
Query guid in packagecache directory to determin whether some packages needs upgrade

### ISSUE THREAD

**Issue by lychichem** [microsoft/winget-cli#1001]
# Description of the new feature/enhancement
There are some packages, for example, all versions of Microsoft.VC++xxxx-xxx, are distributed as a bundle. They report their GUID in packagecache directory in `winget list` as productcode. Now `winget upgrade` is unable to list Microsoft.VC++2015-2019-xxx as upgradable when there is an updated version in winget source. So, a new feature for querying this key is needed.

# Proposed technical implementation details (optional)
Winget should also query GUID in BundleCachePath in registry when `winget upgrade` is execuated, and a bundled exe package like Microsoft.VC++xxxx-xxx need to provide it as product code, either manually or by automated process.

**Comment by lychichem** [comment]
The GUID can be checked at HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{bundle guid}\BundleCachePath
![image](https://user-images.githubusercontent.com/9316590/119840028-33e9d100-bf37-11eb-9c45-6343fa18a7c6.png)

**Comment by Trenly** [comment]
[Policy] Command-Upgrade
[Policy] Area-Matching
