### ISSUE TITLE
Hebrew shows up as gibberish on CMD / PowerShell

### ISSUE THREAD

**Issue by MichaelYochpaz** [microsoft/winget-cli#1015]
# Brief description of your issue
When using the `winget` command on CMD / PowerShell, it prints the description in my computer's default language - Hebrew,
but it seems like both CMD & PowerShell can't print in Hebrew (I assume both use ASCII encoding and not Unicode?).

On Windows Terminal it does work (both on CMD and PS tabs), but has some RTL (Right-To-Left) issues.
For example, the first line says:
תוכנית השירות של שורת הפקודה WinGet מאפשרת להתקין יישומים וחבילות אחרות משורת הפקודה.

Instead of:
‫תוכנית השירות של שורת הפקודה WinGet מאפשרת להתקין יישומים וחבילות אחרות משורת הפקודה.

Can be fixed by adding [Unicode's RLM mark](https://en.wikipedia.org/wiki/Right-to-left_mark) - "\u200F" at the start of all RTL languages strings.

# Steps to reproduce
Use the `winget` command on CMD or PowerShell.

# Screenshots
CMD:
<img src="https://user-images.githubusercontent.com/8832013/120062935-5120bb80-c06d-11eb-9684-7526e0690937.png" width="400"  />

PowerShell:
<img src="https://user-images.githubusercontent.com/8832013/120062937-5251e880-c06d-11eb-99c2-756b411611e9.png" width="400"  />

Windows Terminal:
<img src="https://user-images.githubusercontent.com/8832013/120062940-53831580-c06d-11eb-8f0f-a7277a5e480e.png" width="400"  />

# Environment

```
[winget --info]
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19043.1023
Microsoft.DesktopAppInstaller v1.11.11451.0

Other Software:
Windows Terminal v1.8.1444.0
```

**Comment by denelon** [comment]
By Microsoft policy, we have reduced the number of locales supported by the Windows Package Manager.
