### ISSUE TITLE
source option does not work on list

### ISSUE THREAD

**Issue by AdilHindistan** [microsoft/winget-cli#1019]
# Brief description of your issue

When I use --source or -s to filter installed packages by source, result does not get filtered, I get the full list of installed apps instead.

# Steps to reproduce

1. winget list --source winget

2. winget list --name visual --source winget

```
PS C:\Users\adil> winget list --name visual --source winget
Name                                                               Id                                     Version        Available Source
-----------------------------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2010  x64 Redistributable - 10.0.40219        {1D8E6291-B0D5-35EC-8441-6616F567A0F7} 10.0.40219
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161     {5FCE6D76-F5DC-37AB-B2B8-22AB8CEDB1D4} 9.0.30729.6161
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.17       {8220EEFE-38CD-377E-8595-13398D740ACE} 9.0.30729
Visual Studio Code                                                 Microsoft.VisualStudioCode             1.47.3         1.56.2    winget
... (shortened)

```

# Expected behavior

1. Get the list of all installed apps where source is winget
2. Get the list of packages that have 'visual' in name and source is winget

# Actual behavior

1. I get the list of all apps regardless of the source. I.e. source is ignored
2. I get the list of all apps with 'visual' in the name regardless of the source. Source is ignored.

# Environment

```
> winget --info
Windows Package Manager v1.0.11451
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.985
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

```

**Comment by denelon** [comment]
@AdilHindistan are you looking for packages that have an upgrade available from a given source, or are you looking for any packages installed with a corresponding manifest is a given source?

`winget upgrade -s <source>` would provide the list of packages with upgrades available from a given source.

**Comment by AdilHindistan** [comment]
@denelon That command is quite useful, thank you. In my case, I simply wanted to see what was installed by winget vs other means. Maybe the "source" is a bit misleading. I am pretty sure I did not use winget to install some of the packages listed. I guess it just means winget has a version for the installed package? 
I thought I can use -s to filter installed packages list by source but I guess not?

**Comment by denelon** [comment]
@AdilHindistan you are correct. The source column in the list output just shows a package from an available source that "should" be an upgrade. We don't record what was installed by the Windows Package Manager vs. another install method yet.

**Comment by denelon** [comment]
I'm going to close this bug since it appears the client is behaving as expected.

**Comment by KaranKad** [comment]
I think `winget list -s winget` should show what apps are installed on my system, available from given source and should filter out apps that have no/different source. Currently `winget list -s winget` is similar to `winget list` command, just outputting list of all the applications installed on system instead just showing apps from given source. This command will be helpful to know exactly which installed apps winget can recognize/know if available in winget-pkgs or any custom source. Output could be similar to `winget export` command where apps with unknown sources are removed from the list.

**Comment by denelon** [comment]
@KaranKad https://github.com/microsoft/winget-cli/issues/1155 looks like what you're suggesting.

**Comment by KaranKad** [comment]
Yeah that's exactly it 😅.
