### ISSUE TITLE
Bug with upgrading malware bytes

### ISSUE THREAD

**Issue by a-a3458** [microsoft/winget-cli#1021]
# Brief description of your issue

# Steps to reproduce

type winget upgrade malwarebytes and it makes to bars

# Expected behavior

 for it to upgrade malware bytes

# Actual behavior

 it created two downlaod bars both at 0% each then saying a unknown error occured error code --> 0x80d02002
[failed upgrade attempt.txt](https://github.com/microsoft/winget-cli/files/6565491/failed.upgrade.attempt.txt)

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
```

**Comment by denelon** [comment]
@a-a3458

We've published the v1.1 [release candidate](https://github.com/microsoft/winget-cli/releases/tag/v1.1.12653) and updated our [troubleshooting guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting).

Can you confirm if this is still happening?
