### ISSUE TITLE
Additional option for list command

### ISSUE THREAD

**Issue by pjaj** [microsoft/winget-cli#1030]
Add an additional "--upgradeable / --updateable" option to the list command so that it only shows those packages that are both out of date and known to winget.
I may be just me , but it seems rather pointless showing dozens of programs that winget knows nothing about and/or can't update. Particularly as a list of all installed packages is already available via Settings > Apps & features.

An additional filter that only displays a package for which

- Winget has a record and therefore _could_  upgrade it.
- The installed package either has a down-level version or an unknown version 

This new feature would have the additional benefit of showing which packages would likely be affected should the user issue the "upgrade --all" command. For example a program that would move from freeware to paid for if updated.

**Comment by denelon** [comment]
@pjaj I believe `winget upgrade` does exactly what you are looking for.

We are looking at other improvements with `winget list` as well.
https://github.com/microsoft/winget-cli/issues/977
https://github.com/microsoft/winget-cli/issues/964

**Comment by pjaj** [comment]
@denelon Maybe I'm mistaken, but I thought that _winget upgrade_ actually performs an upgrade on as many packages as it could. What I'm suggesting is a way of listing those packages, but without actually doing anything to them. That is a list of the packages that would be upgraded by _winget upgrade_. One  advantage of this is that upgrading some packages changes them from freeware to paid for and a user might not want to do that. Or there may be compatibility problems between newer versions and other legacy programs.

**Comment by denelon** [comment]
`winget upgrade` lists all packages with possible upgrades.
`winget upgrade -all` executes the upgrades for all possible packages with upgrades.

**Comment by pjaj** [comment]
Mea culpa, I'm new to winget. I'll close this suggestion as already implemented.

**Comment by denelon** [comment]
@pjaj, no worries. Thanks for making the suggestion 😊

I know how hard it is to find duplicate issues.
