### ISSUE TITLE
Not a package manager.

### ISSUE THREAD

**Issue by VelocityDesign** [microsoft/winget-cli#1031]
As an avid Linux user I must tell you the truth. Winget is not a package manager. A true package manager should come preinstalled on the system, manage dependancies, and (most importantly) provide a single backbone for all packages on a system. However, winget is basically a cli for the Microsoft store. Winget is not a package manager and I highly recommend Microsoft to stop pushing it as such. Until winget becomes the backbone of the system and Microsoft store becomes the GUI, winget is not a package manager, but a CLI.

**Comment by josh-65** [comment]
Winget will be preinstalled with app installer for version 1809 and above eventually.

**Comment by VelocityDesign** [comment]
Ok, but if Microsoft wants to take this seriously, they need to make this the backbone for all package management

**Comment by denelon** [comment]
@VelocityDesign thanks for the feedback. We still have plenty of work to do with the current set of features and experiences. We also have a fairly deep backlog of new feature requests. 

We are listening. 

Building a package manager on Windows is a huge undertaking, and it will require community support as well. There are plenty of publishers and ISVs who are still going through their own sets of challenges with installers, and we're trying to meet them where they are so we can all improve together.

The main reason this didn't get pushed as an update to the "stable" App Installer is to give our enterprise customers enough time to implement and roll out Group Policy. Once that has happened, we will make this the "default" App Installer and push to all Windows 10 version 1809 and newer builds.

**Comment by nonetrix** [comment]
I am kinda confused with winget as well, why couldn't repo support and other "package manager" like features be added to Windows Store, then make winget a CLI version of Windows Store.

My guess is that supporting stuff like purchases and etc would be hard if they open sourced windows store, but this has already been done in open source take Cydia for example.

**Comment by denelon** [comment]
@nonetrix the Windows Package Manager has a different set of goals from the Microsoft Store. Some of the goals are similar, but there are subtle differences. We are working to make store Apps available as packages, but we still have plenty of work to do. That's the reason the store is an *experimental* feature currently. We will continue working to address all of the store specific concerns to make sure we can deliver the best customer experiences from a commnd-line point of view.
