### ISSUE TITLE
By name alphabetical order searches

### ISSUE THREAD

**Issue by josh-65** [microsoft/winget-cli#1036]
# Description of the new feature/enhancement
When doing a `winget search` it will display all of the available programs but not in alphabetical order by Name witch makes it harder for me to look through.

# Proposed technical implementation details
It should order it by Name not ID from 0-9 AAA-ZZZ

**Comment by denelon** [comment]
@josh-65 the search return order has more to do with what "matched" with a particular field in the manifest. I like the idea of adding some additional arguments for sorting results. This could be arguments, and/or settings.

**Comment by chausner** [comment]
This seems to be a duplicate of #142.

**Comment by denelon** [comment]
Duplicate of #142
