### ISSUE TITLE
I wanna ask can Winget get files like wget/apt install on linux?

### ISSUE THREAD

**Issue by WinkeyCheng** [microsoft/winget-cli#1040]
I wanna ask can this kind of 'Command Prompt' get the files like: sudo apt install mono-devel
![image](https://user-images.githubusercontent.com/73391218/120135269-7bf04880-c202-11eb-8da0-85e990b39267.png)

**Comment by KaranKad** [comment]
If you are talking about this application [monodevelop](https://www.monodevelop.com/developers/building-monodevelop/). Then probably yes. I'll try adding manifest for it to see if it works.

**Comment by WinkeyCheng** [comment]
I wanna know can I apply for develop this application? 
I am not an employee of Microsoft

**Comment by WinkeyCheng** [comment]
I hope this application can also work for
wget/mono getting files
And also can connection to windows server and work like ftp/ssh client

**Comment by WinkeyCheng** [comment]
I hope this application can also work for
wget/mono getting files
And also can connection to windows server and work like ftp/ssh client

**Comment by KaranKad** [comment]
> I wanna know can I apply for develop this application?

I mean winget-cli is open to contribution.

**Comment by denelon** [comment]
@WinkeyCheng if you have the Windows Package Manager installed on your system, it should work via CMD.
