### ISSUE TITLE
Malwarebytes doesn't progress download.

### ISSUE THREAD

**Issue by goopy13** [microsoft/winget-cli#1050]
# Brief description of your issue
Malwarebytes will get stuck at 0.00B/192MB.

# Steps to reproduce
`winget install malwarebytes`
# Expected behavior
The download will progress at normal speed.
# Actual behavior
```
winget install malwarebytes
Found Malwarebytes [Malwarebytes.Malwarebytes]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://downloads.malwarebytes.com/file/mb4_offline
  ██████████████████████████████  0.00 B /  192 MB
  ██████████████████████████████  0.00 B /  192 MB
An unexpected error occurred while executing the command:
0x80d02002 : unknown error
```
# Environment

```
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19041.985
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
```

My internet is working. I can ping downloads.malwarebytes.com. The file winget is attempting to download can be downloaded with wget in wsl or just entering the url into chrome.

**Comment by denelon** [comment]
I'm marking this as "Area-External" as the Delivery Optimization has an exceptionally long timeout. We've got some work with that team to have more of a "fast fail" so we can fall back to wininet.

**Comment by cryptic-code** [comment]
I faced the same issue today and adding `"network": {"downloader": "wininet"},` solved it.

I am just wondering if there are any downsides to this configuration? And when it is indeed fixed, would it need manual intervention to remove this?

**Comment by denelon** [comment]
@cryptic-code. The one downside would be losing the potential benefit of Delivery Optimization in the enterprise if it is supported by the enterprise. You would need to either remove that line in settings, or change it to "default", or "do".

**Comment by cryptic-code** [comment]
@denelon shouldn't this issue be marked as close? As this was fixed in the latest [release](https://github.com/microsoft/winget-cli/tree/v1.0.11692)?

**Comment by denelon** [comment]
@cryptic-code thanks for pointing that out 👍 

I'm playing a bit of catch up.
