### ISSUE TITLE
Manifests - Switches

### ISSUE THREAD

**Issue by iDolmatov** [microsoft/winget-cli#1057]
Hello.

I can't find Switches for update mode. 
Winget support "upgrade" command, 
[AIMP](https://github.com/microsoft/winget-pkgs/tree/master/manifests/a/AIMP/AIMP) support "/UPDATE" Switch. 
https://www.aimp.ru/forum/index.php?topic=259.msg135976#msg135976

Can't find how use "-l,--location" switcher in Manifests (winget install -?). 

Can't find help tip about use 
```
    InstallerSwitches:
      Custom
```
in "winget install -?". Only "--override", without get switches from manifest.

**Comment by denelon** [comment]
@iDolmatov ,

There is a key in the manifest syntax for "Upgrade" in the ""InstallerSwitches".

```JSON
"Upgrade": {
          "type": [ "string", "null" ],
          "minLength": 1,
          "maxLength": 512,
          "description": "Upgrade is the value that should be passed to the installer when user chooses an upgrade"        },
```

The `--location` argument depends on the installer supporting passing that argument.

**Comment by iDolmatov** [comment]
What about use Custom in winget?

**Comment by iDolmatov** [comment]
I create question, because it's look as separate command.
https://github.com/microsoft/winget-cli/discussions/1067

Need documentation about this switch.
