### ISSUE TITLE
Fails to update program, error 0x801901a0

### ISSUE THREAD

**Issue by Masamune3210** [microsoft/winget-cli#1060]
# Brief description of your issue

Just got winget installed after joining the package manager beta, tried upgrade --all and it keeps dying trying to upgrade QuickPar with a Requested range not satisfiable (416) error

# Steps to reproduce

Attempt to upgrade QuickPar, would assume the same issue occurs if you try to install it from scratch but I haven't tried it
# Expected behavior

For it to download the setup and the upgrade to complete
# Actual behavior

Error on setup download

# Environment

```none
[winget --info]
Windows Package Manager version v1.0.11451
Windows: Windows.Desktop version v10.0.19043.985
Package: Microsoft.DesktopAppInstaller version v1.11.11451.0

Any other software?
```
Was running it in a PowerShell instance inside of the new Terminal, don't know if that would change anything or not

**Comment by denelon** [comment]
@Masamune3210 I'm not sure, but this might have something to do with Delivery Optimization attempting to download the file with "range" requests. You might try to change your settings to `"network: "wininet"` and see if that helps.

**Comment by Masamune3210** [comment]
Im sorry, I am unfamiliar with how to do that, I'm probably just misunderstanding how to use the config file

**Comment by denelon** [comment]
`winget settings` will launch the settings file with your default editor. If you have something like Visual Studio Code configured to handle JSON files, it also supports JSON schemas. That means you would get intellisense and tooltips.

From there, you would add the line above (probably ending in a comma if you have other settings).

**Comment by Masamune3210** [comment]
tried but not sure if I added the config right, result was the same 

`{
    "$schema": "https://aka.ms/winget-settings.schema.json",

    // For documentation on these settings, see: https://aka.ms/winget-settings
    // "source": {
    //    "autoUpdateIntervalInMinutes": 5
    // },
}	"Network": "wininet"`

**Comment by denelon** [comment]
You put it past the end. Here is an example:

```
{
    "$schema": "https://aka.ms/winget-settings.schema.json",

    // For documentation on these settings, see: https://aka.ms/winget-settings
    // "source": {
    //    "autoUpdateIntervalInMinutes": 5
    // },

    "network": {"downloader": "wininet"}
}
```

**Comment by Masamune3210** [comment]
Ok, yeah now that the config file is fixed the file is correctly downloaded and the upgrade works correctly
