### ISSUE TITLE
Installing a package from a local manifest (generated with wingetcreate) fails.

### ISSUE THREAD

**Issue by TechWatching** [microsoft/winget-cli#1064]
# Brief description of your issue
Error `0x8a150004 : Opening manifest failed` when trying to install a local manifest created with winget create package.
# Steps to reproduce

Create a manifest from a msi hosted in github using wingetcreate tool and store the manifest locally : for instance ` wingetcreate new https://github.com/nushell/nushell/releases/download/0.32.0/nu_0_32_0_windows.msi -o .`
Try to install to generated manifest using winget install command: `winget install -m .\Nushell.Nushell.yaml`

Nushell.Nushell.yaml
```json
# Created using wingetcreate

PackageIdentifier: Nushell.Nushell
PackageVersion: 0.32.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0
```

Nushell.Nushell.installer.yaml
```json
# Created using wingetcreate

PackageIdentifier: Nushell.Nushell
PackageVersion: 0.32.0
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  InstallerUrl: https://github.com/nushell/nushell/releases/download/0.32.0/nu_0_32_0_windows.msi
  InstallerSha256: 2ACA5A30A3AC39DE2A48EFDB94AACE618A60523097AB5001CFFB4B33F7408B4E
  ProductCode: '{6296CFD4-3DA4-49E8-BF3F-76FF3B2CBF29}'
ManifestType: installer
ManifestVersion: 1.0.0

```
Nushell.Nushell.locale.en-US.yaml
```json
# Created using wingetcreate

PackageIdentifier: Nushell.Nushell
PackageVersion: 0.32.0
PackageLocale: en-US
Publisher: The Nu Project Contributors
PackageName: nu
License: MIT License
ShortDescription: A new type of shell.
ManifestType: defaultLocale
ManifestVersion: 1.0.0

```

# Expected behavior

winget installs the package.

# Actual behavior

winget install fails with the following error : `0x8a150004 : Opening manifest failed`

# Environment

```none
[winget --info]
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19042.985
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

Any other software?
```

**Comment by denelon** [comment]
When you are validating a "multi-file" YAML manifest, you should pass the directory into the tool rather than one of the .yaml files. We will consider an approach that might work if you specify one of the .yaml files.

**Comment by TechWatching** [comment]
Thanks indeed, works better with the directory.

**Comment by Trenly** [comment]
@TechWatching - Is this issue resolved?

**Comment by Trenly** [comment]
[Policy] Needs-Author-Feedback
