### ISSUE TITLE
Error with Microsoft.WingetCreate

### ISSUE THREAD

**Issue by Jesper15** [microsoft/winget-cli#1072]
# Brief description of your issue

Microsoft.WingetCreate does not install

# Steps to reproduce

Microsoft.WingetCreate gives an error while installing with winget.  I get the following error:

**Found Windows Package Manager Manifest Creator [Microsoft.WingetCreate]
An unexpected error occurred while executing the command:
Unsupported ManifestVersion: 1.0.0
0x8a150007 : Cannot process manifest. The manifest version is higher than supported. Please update the client.**

Microsoft WingetCreate should be installed. There are no updates available.

I get an error which I described above.

# Environment

```none
Windows Package Manager v0.2.2941 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.985
Package: Microsoft.DesktopAppInstaller v1.11.2941.0

Any other software?

I use windows terminal with powershell to download this.
```

**Comment by jedieaston** [comment]
You're on a old version of the Windows Package Manager. No big deal, it's easy to update. Download the latest version from here:

https://aka.ms/installwinget

**Comment by Jesper15** [comment]
Thanks for your answer. I updated the Windows Package Manager and now I can install the create manager. 

One question. Can I use this link always to update the package manager or gets every update a seperate download link?

**Comment by jedieaston** [comment]
This link should always be up to date, but eventually, updates will be served via the Microsoft Store.

**Comment by Jesper15** [comment]
Ah ok. Thanks for your help. I will close the issue since the problem is solved!
