### ISSUE TITLE
winget install results in 0x80d03002 : unknown error

### ISSUE THREAD

**Issue by vaughan-naidoo** [microsoft/winget-cli#1076]
# Brief description of your issue
winget install results in 0x80d03002 : unknown error

# Steps to reproduce
In Powershell issue the following command:
> winget install 'Visual Studio Code'

# Expected behavior

Installation of visual studio code should begin.

# Actual behavior

Found Visual Studio Code [Microsoft.VisualStudioCode]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://az764295.vo.msecnd.net/stable/054a9295330880ed74ceaedda236253b4f39a335/VSCodeUserSetup-x64-1.56.2.exe
An unexpected error occurred while executing the command:
0x80d03002 : unknown error

# Environment
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19043.985
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

Any other software?
```

**Comment by denelon** [comment]
@vaughan-naidoo we've seen this error on a few different machines. We believe it is related to Delivery Optimization and possibly enterprise managed settings. You can try to change your `winget settings` to specify "wininet" for the download mechanism.

Example from settings.json:

```
{
    "$schema": "https://aka.ms/winget-settings.schema.json",

    // For documentation on these settings, see: https://aka.ms/winget-settings
    // "source": {
    //    "autoUpdateIntervalInMinutes": 5
    // },

    "network": {"downloader": "wininet"}
    }
}
```

**Comment by vaughan-naidoo** [comment]
Thank you @denelon that fixed it.

**Comment by EJacobowitz** [comment]
Thank you @denelon this fixed the issue for me too.

for others with the same issue, I didn't have a settings.jason. I had to type winget.exe settings and this created the file in the following path $env:LOCALAPPDATA\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState

then I updated based on denelon's post above and I am loving winget.exe now.
