### ISSUE TITLE
Multiple installed packaged found

### ISSUE THREAD

**Issue by AdilHindistan** [microsoft/winget-cli#1083]
# Brief description of your issue

Cannot upgrade Visual Studio Code as winget fails to properly use the provided criteria

# Steps to reproduce

All of the following commands fail:
```
PS C:\Users\adil> winget upgrade --id Microsoft.VisualStudioCode
Multiple installed packages found matching input criteria. Please refine the input.
Name                                Id
------------------------------------------------------------------------------
Visual Studio Code                  Microsoft.VisualStudioCode
Microsoft Visual Studio Code (User) {771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1

PS C:\Users\adil> winget upgrade --id Microsoft.VisualStudioCode -e
Multiple installed packages found matching input criteria. Please refine the input.
Name                                Id
------------------------------------------------------------------------------
Visual Studio Code                  Microsoft.VisualStudioCode
Microsoft Visual Studio Code (User) {771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1

PS C:\Users\adil> winget upgrade -e Microsoft.VisualStudioCode
Multiple installed packages found matching input criteria. Please refine the input.
Name                                Id
------------------------------------------------------------------------------
Visual Studio Code                  Microsoft.VisualStudioCode
Microsoft Visual Studio Code (User) {771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1

PS C:\Users\adil> winget upgrade -e --id Microsoft.VisualStudioCode
Multiple installed packages found matching input criteria. Please refine the input.
Name                                Id
------------------------------------------------------------------------------
Visual Studio Code                  Microsoft.VisualStudioCode
Microsoft Visual Studio Code (User) {771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1
```

# Expected behavior

It should match just the top one:

```
Name                                Id
------------------------------------------------------------------------------
Visual Studio Code                  Microsoft.VisualStudioCode
```

# Actual behavior

Matches another install that actually does not have the id I typed.

# Environment

```none
PS C:\Users\adil> winget --info
Windows Package Manager v1.0.11451
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.985
Package: Microsoft.DesktopAppInstaller v1.11.11451.0


```

**Comment by denelon** [comment]
@AdilHindistan can you share the output for `winget list visual`?

We've run into some challenges with packages that have a different version number than what shows up in "Add / Remove Programs". The Visual Studio Code manifests have a four part version number, and only the first three appear to be registered in Windows.

**Comment by denelon** [comment]
I'm also wondering if you have the "stable" release and a daily build installed on your machine. I've seen some interesting interactions with packages that have side by side install support.

**Comment by AdilHindistan** [comment]
> I'm also wondering if you have the "stable" release and a daily build installed on your machine. I've seen some interesting interactions with packages that have side by side install support.

How do I check @denelon ?

**Comment by denelon** [comment]
Run `winget list visual` and share the output if you don't mind. Visual Studio Code supports "side by side" install for stable and "daily" builds. I believe we would see more than one entry for "Visual Studio Code".

**Comment by AdilHindistan** [comment]
I think you are onto something here @denelon 

```
PS C:\Users\adil> winget list visual
Name                                             Id                                     Version        Available Source
-----------------------------------------------------------------------------------------------------------------------
Visual Studio Code                               Microsoft.VisualStudioCode             1.47.3         1.56.2    winget
Microsoft Visual C++ 2010  x64 Redistributable … {1D8E6291-B0D5-35EC-8441-6616F567A0F7} 10.0.40219
Microsoft Visual C++ 2008 Redistributable - x64… {5FCE6D76-F5DC-37AB-B2B8-22AB8CEDB1D4} 9.0.30729.6161
Microsoft Visual C++ 2008 Redistributable - x64… {8220EEFE-38CD-377E-8595-13398D740ACE} 9.0.30729
Microsoft Visual C++ 2013 Redistributable (x64)… {050d4fc8-5d48-4b8f-8972-47c82c46020f} 12.0.30501.0
Microsoft Visual C++ 2012 Redistributable (x86)… {33d1fd90-4274-48a1-9bc1-97e33d9c2d6f} 11.0.61030.0
Microsoft Visual C++ 2005 Redistributable        {710f4c1c-cc18-4c49-8cbf-51240c89a1a2} 8.0.61001
Microsoft Visual C++ 2005 Redistributable        {7299052b-02a4-4627-81f2-1818da5d550d} 8.0.56336
Microsoft Visual C++ 2008 Redistributable - x86… {9BE518E6-ECC6-35A9-88E4-87755C07200F} 9.0.30729.6161
Microsoft Visual C++ 2015-2019 Redistributable … {a9cfe9c7-e54f-46cd-9c5c-542ff8e3e8c4} 14.28.29334.0
Microsoft Visual C++ 2015-2019 Redistributable … {b2d0f752-adc5-496e-8f70-8669de01f746} 14.28.29334.0
Microsoft Visual C++ 2012 Redistributable (x64)… {ca67548a-5ebe-413a-b50c-4b9ceb6d66c6} 11.0.61030.0
Microsoft Visual C++ 2010  x86 Redistributable … {F0C3E5D1-1ADE-321E-8167-68EF0DE699A5} 10.0.40219
Microsoft Visual C++ 2013 Redistributable (x86)… {f65db027-aff3-4070-886a-0d87064aabb1} 12.0.30501.0
Visual Studio Code                               Microsoft.VisualStudioCode             1.56.2
```

**Comment by denelon** [comment]
The Windows Package Manager has "settings" and an argument to specify "User" vs. "Machine". The default is "User" when not specified (assuming the manifest is configured correctly). Depending on when and how the first version was installed, this could have been the result of the Windows Package Manager not being able to map to the version or scope on your machine. We will need to perform some additional testing to see if the behavior is correct in the client, or if we need to make some additional changes in the code paths to see if it is possible to detect which one a user has installed, and at least provide a warning to avoid this scenario. We have a feature to look at "UpgradeCode" in MSI packages, and I'm hoping that will properly address at least this scenario. 

Thank you so much for the detailed analysis!

**It really helps when we have sufficient data to be able to troubleshoot and reproduce errors**

**Comment by denelon** [comment]
I believe we have narrowed down what has happened in this case. The previous version was installed as "machine" and the installer in the manifest currently defaults to "user". We see the earlier version, but when we install we install the new version as "user". This shows up as a second entry. I'm not sure what we could do in cases like this to help improve experience. If you can think of a better behavior, let us know. I'd be happy to have a new "Feature" request additional behavior or user control.
