### ISSUE TITLE
wget wont install

### ISSUE THREAD

**Issue by redimongo** [microsoft/winget-cli#1086]
So I have ran winget install wget and i get that it cant find package.

yet when i search winget search wget i get 

Wget for Windows GnuWin32.Wget 1.11.4  Tag: wget

So wondering why can I not install this?

**Comment by KaranKad** [comment]
Can you tell me what happens when you run `winget install GnuWin32.Wget`

**Comment by denelon** [comment]
@redimongo

We've published the v1.1 [release candidate](https://github.com/microsoft/winget-cli/releases/tag/v1.1.12653) and updated our [troubleshooting guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting).

Can you confirm if this is still happening?
