### ISSUE TITLE
Issues & suggestions

### ISSUE THREAD

**Issue by DePhoegon** [microsoft/winget-cli#1087]
1. Issue -- Programs like 'Intelj' error out in the installer if installed in place like the way is being done (something is already in that folder)
2. Suggestion --  Allow for custom install locations.  
--- while this isn't an issue for tools & utility programs for the most part...   not being able to install in another location & not know which location it is without digging can become an issue fast.
3. Suggestion -- Blacklist an app from being 'upgraded'.
-- Again,  Programs like Intelj, have a competent upgrader built into the program, or may have issues with being upgraded with it's installer and will cause it to try & download the program... 'AGAIN'  which cause cause other issues around data usage & storage.
4. Suggestion -- Allow Input of 'sources' that are CMD line inputs to another program.
-- Current example CMD Line Steam, where it can be triggered and told to update / validate a program.

**Comment by Masamune3210** [comment]
definitely +1 on the blacklist part as I had a bunch of apps freak out because of them not expecting to be updated through installer

**Comment by denelon** [comment]
@DePhoegon
1) We are aware, I believe there is another Issue for this
2) Custom locations are supported
3) This is the "pin" feature in the backlog
4) This is most likely not something we could implement. Steam has it's own mechanisms for repairing/restoring their packages. I'm not aware of any API we could leverage in this case, and we likely wouldn't try to keep parity with third party programs with this kind of behavior.

**Comment by denelon** [comment]
I believe the key features have been implemented.

Pinning is an experimental feature in our latest release.

If any one of these is still an issue, please create a separate Issue. It's best to have an individual Issue so we can better track progress.
