### ISSUE TITLE
search and list output

### ISSUE THREAD

**Issue by MJPhelan** [microsoft/winget-cli#1096]
Any chance we can get this in a format that can be used more easily in powershell.

Ideally I'd like to be able to do something like 

```
$AppsList = Winget List
foreach ($App in $AppsList)
{
	$AppVersion = (winget show $App.ID).Version
	if ($AppVersion -gt $App.Version) { Winget Upgrade $App.ID }
}
```

But as it stands I'll have to process the output of Winget List myself...

**Comment by denelon** [comment]
Duplicate of #221
