### ISSUE TITLE
Update prompted more than once

### ISSUE THREAD

**Issue by albertopasqualetto** [microsoft/winget-cli#1104]
# Brief description of your issue

I have just installed appget and it suggests me updates I already have done without using it.

# Environment

```none
[winget --info]
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19043.1023
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

**Comment by jedieaston** [comment]
Can you post the output of `winget upgrade`?

**Comment by albertopasqualetto** [comment]
[https://user-images.githubusercontent.com/39854348/120823283-935b6880-c557-11eb-9d22-5f3db6ecd64b.png]
This is basically the image.

I don't think it is useful for this issue.

For example I updated manually OBS to version 27, but winget proposed to update it again. The same with Todoist.
When I did the updates trough winget it didn't reprompt me about them (the image is from after the updates).

**Comment by denelon** [comment]
@albertopasqualetto 

We've published the v1.1 [release candidate](https://github.com/microsoft/winget-cli/releases/tag/v1.1.12653) and updated our [troubleshooting guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting).

Can you confirm if this is still happening?

**Comment by albertopasqualetto** [comment]
Yes, an example is Discord
<details>
  <summary>Proof</summary>

![image](https://user-images.githubusercontent.com/39854348/135904063-97eaf335-cd8c-4e3c-b711-e58d50c2beaf.png)
![image](https://user-images.githubusercontent.com/39854348/135904161-808eaacb-0018-4c05-aa24-9e2575a54e37.png)

</details>

**Comment by jedieaston** [comment]
What version number shows in Add and Remove Programs?

**Comment by denelon** [comment]
@albertopasqualetto Discord may not upgrade if it's running. We've also seen cases where packages install newer versions as a separate application. We have other issues tracking those scenarios.

**Comment by albertopasqualetto** [comment]
> What version number shows in Add and Remove Programs?

1.0.9002 (the old one)

**Comment by albertopasqualetto** [comment]
> @albertopasqualetto Discord may not upgrade if it's running. We've also seen cases where packages install newer versions as a separate application. We have other issues tracking those scenarios.

I understand.
I'll wait for improvements!
