### ISSUE TITLE
Publish Winget to winget-pkgs

### ISSUE THREAD

**Issue by felipecrs** [microsoft/winget-cli#1110]
It would be cool, so we could do `winget upgrade winget`. I'm creating this issue in this repo because a CI/CD integration would be desirable, so every new version would end up in the winget-pkgs.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-pkgs/pull/332

**Comment by felipecrs** [comment]
Oh sorry, while my issue talks specifically about automatic creation of manifests for winget using wingetcreate, it would probably be covered by https://github.com/microsoft/winget-cli/issues/505 and https://github.com/microsoft/winget-pkgs/pull/332.

**Comment by denelon** [comment]
@felipecrs no worries. As soon as we have the code changes in the client to allow the client to "upgrade" itself, we will use [wingetcreate](https://github.com/microsoft/winget-create) to publish our own manifests. We also need to get "channels" support done correctly as well. Only one instance of "App Installer" can be on a machine at a time, so we need to be able to separate the "DEV" channel from the "stable" channel somehow.
