### ISSUE TITLE
Winget not working after install 

### ISSUE THREAD

**Issue by AnubisOfMalware** [microsoft/winget-cli#1120]
# Winget not working after install #

After install of "App Installer" Winget and im about to test it out no commands seming to work have tried in both Admin and non Admin & Uninstalling and installing again I only get the * 'winget'  is not recognized as an internal or external command, operable program or batch file. *

winget info
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

**Comment by iDolmatov** [comment]
Is there anything displayed in the control panel (settings window)?
Example:
![image](https://user-images.githubusercontent.com/19782385/120902370-7ad37700-c659-11eb-9471-d963ee95eaee.png)

What does the system offer when the [appxbundle](https://github.com/microsoft/winget-cli/releases) is opened?

Is there anything in the folder?
`%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir`

Write a complete version of the system (command prompt or `winver` command).

Check this is issue related to https://github.com/microsoft/winget-cli/issues/210

**Comment by AnubisOfMalware** [comment]
Uninstalled restarted and downloaded Appxbundle again and everything working fine now thanks. 👯
