### ISSUE TITLE
new program executed winget list wait indefinitely

### ISSUE THREAD

**Issue by 582197490** [microsoft/winget-cli#1121]
hello there:

today when i install winget.
first i executed winget, it lists the list of commands.
i executed winget list.
windows terminal entered an infinite loop state.
i don't know this is my network problem or this is a bug.

**Comment by iDolmatov** [comment]
run `winget --info` and copy-paste output here.

Open log dir (winget --info show the path like as `%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir` and attach a files (or a files in archive).

**Comment by denelon** [comment]
@582197490 

We've published the v1.1 [release candidate](https://github.com/microsoft/winget-cli/releases/tag/v1.1.12653) and updated our [troubleshooting guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting).

Can you confirm if this is still happening?
