### ISSUE TITLE
Issue when trying to create a manifest

### ISSUE THREAD

**Issue by sanikdah** [microsoft/winget-cli#1124]
# Brief description of your issue

When trying to install the local manifest of the software: KeyFinder by MagicalJellyBean, winget will give me an unexpected error.

# Steps to reproduce

wingetcreate new https://www.magicaljellybean.com/downloads/KeyFinderInstaller.exe
fill out the manifest
winget validate (manifest path)
winget install --manifest (manifest path)

# Expected behavior

wingetcreate should download and parse the installer, then continue with the creation process.
Then once that is done and the validation is done, it should work when you run winget install --manifest (manifest path)

# Actual behavior

Everything works fine until the local manifest install, where this happens.
![image](https://user-images.githubusercontent.com/72118300/120938586-42b74d00-c6c8-11eb-867b-9bdc00201b38.png)

# Environment
![image](https://user-images.githubusercontent.com/72118300/120938605-67abc000-c6c8-11eb-9a4c-e83647ea7782.png)

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
Not sure exactly what this means but if it means does the error occur with any other software as far as I know it does not.

**Comment by ItzLevvie** [comment]
I'm seeing the same issue here but with a PR (i.e. https://github.com/microsoft/winget-pkgs/pull/16358):
![image](https://user-images.githubusercontent.com/11600822/120944102-965a8280-c72a-11eb-9f02-094446b4206a.png)

**Comment by sanikdah** [comment]
huh, weird.

**Comment by mddtest** [comment]
When going to that site Megabytes is blocking it.  could the CLI think its malicious?

**Comment by sanikdah** [comment]
> When going to that site Megabytes is blocking it. could the CLI think its malicious?

Do you mean Malwarebytes?  And if so I don't think so but it's possible.

**Comment by mddtest** [comment]
> 
> 
> > When going to that site Megabytes is blocking it. could the CLI think its malicious?
> 
> Do you mean Malwarebytes? And if so I don't think so but it's possible.

I am getting a security warning from Malwarebytes and SSL error when going to magicaljellybean.com

**Comment by sanikdah** [comment]
huh.. idk, maybe a mod or a dev would know if that might be affecting it.

**Comment by mddtest** [comment]
ItzLevvie would look in to it as hes a mod here.

**Comment by sanikdah** [comment]
yep

**Comment by denelon** [comment]
@sanikdah can you share logs or submit a [Feedback](https://aka.ms/winget-feedback) report and share the link?

The log path is visible from `winget --info`.

**Comment by denelon** [comment]
@ItzLevvie I took a look at the logs. It looks like this is related to Delivery Optimization.  You can change the "network" setting.

```
 "network": {"downloader":"wininet"}
```

Will force "wininet" rather than "do" (the default).

**Comment by sanikdah** [comment]
my current settings.json file looks like this, not seeing anywhere to put that line.
{
    "$schema": "https://aka.ms/winget-settings.schema.json",

    // For documentation on these settings, see: https://aka.ms/winget-settings
    // "source": {
    //    "autoUpdateIntervalInMinutes": 5
    // },
}

**Comment by sanikdah** [comment]
If you want I could disable DO from windows settings, I know where it's at.

**Comment by denelon** [comment]
@sanikdah, the settings.json file accepts JSON syntax. Here is an example:

```
{
    "$schema": "https://aka.ms/winget-settings.schema.json",

    // For documentation on these settings, see: https://aka.ms/winget-settings
    // "source": {
    //    "autoUpdateIntervalInMinutes": 5
    // },

    "network": {"downloader":"wininet"},

    "visual": {"progressBar": "rainbow"},

    "experimentalFeatures": {
        "experimentalMSStore": true
    }
}
```

**Comment by sanikdah** [comment]
Alright that worked!
