### ISSUE TITLE
ResourceUnavailable: (:) [], ApplicationFailedException

### ISSUE THREAD

**Issue by Ixogamer** [microsoft/winget-cli#1125]
# Brief description of your issue
I installed winget and can't use it, I get an error.
# Steps to reproduce

1 - Install Winget
2 - It doesn't work anymore after updating

# Expected behavior

Winget gets called with "winget" and "winget.exe"

# Actual behavior

```
PS C:\Users\Usuario> winget
Error al ejecutar el programa 'winget.exe': El sistema no tiene acceso al archivoEn línea: 1
Carácter: 1
+ winget
+ ~~~~~~.
En línea: 1 Carácter: 1
+ winget
+ ~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```
![image](https://user-images.githubusercontent.com/68835899/120947085-ee9b7f80-c73e-11eb-9fbc-c16e01bca236.png)

# Environment

```none
[winget --info]
Windows Package Manager version - Latest
Windows: 19043.1023
Package: Latest release

Any other software?
Windows terminal, but it's not needed for the bug.
```

**Comment by denelon** [comment]
@Ixogamer which method from the instructions in the link below did you use to install the Windows Package Manager?

https://github.com/microsoft/winget-cli#installing-the-client

**Comment by Ixogamer** [comment]
@denelon I've tried all of them, even removing the package manager via powershell and installing manually the .appxbundle from the releases tab.

It worked when I just downloaded the Insider version from the Microsoft Store, but it doesn't work anymore.

And My %appdata%/local/microsoft folder doesn't exist. Could it be that?

**Comment by denelon** [comment]
@Ixogamer do you get the option to "repair" the App Installer in the Microsoft Store?

Are you on a Windows Insider build or a stable release?

**Comment by Ixogamer** [comment]
I don't have the option to "repair" the app installed. I'm on a Windows Insider build

**Comment by denelon** [comment]
Do you have the App Execution Alias enabled for "winget"?

**Comment by Ixogamer** [comment]
![image](https://user-images.githubusercontent.com/68835899/121107766-d3954200-c808-11eb-8f43-3c98ea9f3872.png)
It should be.
![image](https://user-images.githubusercontent.com/68835899/121107812-e90a6c00-c808-11eb-8b1e-e604857c8d95.png)
the error on an elevated powershell window

**Comment by denelon** [comment]
OK, my next best guess at this point is the path. Take a look at #210.

**Comment by Ixogamer** [comment]
Yeah, I think so. I don't have the "Microsoft" directory on Appdata\Local, though. Is that normal?

**Comment by denelon** [comment]
I don't think that is "normal" or correct. I'm not sure if that might be all or part of the problem or not.

**Comment by Ixogamer** [comment]
After reinstalling Windows with the ISO, everything is the same. Thought I would point that out.

**Comment by Ixogamer** [comment]
Nevermind. After re-joining Windows Insiders and trying to install the Package Manager, i get this error: 
![image](https://user-images.githubusercontent.com/68835899/121920145-0aeb7d80-cd38-11eb-86cd-ca2e96d27f59.png)

**Comment by Ixogamer** [comment]
This is becoming even weirder... after running `Add-AppxPackage -Path "D:\Usuario\Downloads\Winget.appxbundle"` on a elevated Powershell, i get this unnamed app:
![image](https://user-images.githubusercontent.com/68835899/121920664-8cdba680-cd38-11eb-9927-a1997a82b5da.png)

Installing packages with it (By double clicking an appxbundle) doesn't work, and gives me this error: 
![image](https://user-images.githubusercontent.com/68835899/121920770-a54bc100-cd38-11eb-8b22-aed231172ca2.png)

**Comment by Ixogamer** [comment]
Forget the last things, winget corrupted completely my Windows installation. After clean installing windows, updating to the latest Insider version (Beta Channel) and updating Package Manager on the Microsoft Store, winget worked perfectly. I just had to open up a powershell and type winget.
