### ISSUE TITLE
winget list command not working

### ISSUE THREAD

**Issue by charudatta10** [microsoft/winget-cli#1129]
# Brief description of your issue

Failed to open the predefined source; please report to winget maintainers.
An unexpected error occurred while executing the command:
0x80070459 : No mapping for the Unicode character exists in the target multi-byte code page.

# Steps to reproduce

winget list

# Expected behavior

Name                                     Id                                                     Version
-------------------------------------------------------------------------------------------------------------------
IPFS Desktop 0.14.0                      033dffdc-028b-55d6-9442-9e386fe5b76e                   0.14.0
Notebook 1.2.9                           07e74316-82bc-58bb-a564-e9fc8e1a4b1c                   1.2.9

# Actual behavior

Failed to open the predefined source; please report to winget maintainers.
An unexpected error occurred while executing the command:
0x80070459 : No mapping for the Unicode character exists in the target multi-byte code page.

# Environment

Windows Package Manager v0.2.10191 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18363.1556
Package: Microsoft.DesktopAppInstaller v1.11.10191.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
Licence Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget

**Comment by denelon** [comment]
@charudatta10 can you upgrade to the latest version of the client?

https://github.com/microsoft/winget-cli#installing-the-client

**Comment by charudatta10** [comment]
It worked with upgrade
