### ISSUE TITLE
Winget install/show without arguments should not produce a list of all packages 

### ISSUE THREAD

**Issue by theking465** [microsoft/winget-cli#1131]
# Description of the new feature/enhancement
When typing `winget install` or  `winget show` the CLI currently outputs a list of all packages with a mention there have been too many packages found. This floods the terminal and is not user-friendly. When no arguments are given it should default to the help message or simply a warning the user has to provide a package name. 

# Proposed technical implementation details (optional)
If `install`or `show` have no arguments, the terminal should respond with: `Please provide a package name` or refer to the help message of the command.

**Comment by Jaifroid** [comment]
Have to agree. Now that there are so many packages, it takes forever to show a list that is usually truncated in the terminal in any case, so useless. It would be better to show help if someone writes `winget install`.

**Comment by denelon** [comment]
@theking465 great suggestion.

**Comment by j-mclain** [comment]
I found it handy to dump an exhaustive list to a text file so I could browse through the gazillions of things out there. That's how I found a bunch of applications I hadn't considered before. Will that be an option somehow in the future now that it's been removed from "winget search" as a default?

**Comment by Trenly** [comment]
`winget search --query="" --source=winget` allows for dumping the entire list
