### ISSUE TITLE
Auto Upgrade Tag

### ISSUE THREAD

**Issue by mddtest** [microsoft/winget-cli#1137]
# Description of the new feature/enhancement

Add a Tag to any program that forces the latest version at launch IE. Spotify, Steam, Battle.net, other launcher or self managed programs.

> it's late just think out side the box too much.

# Proposed technical implementation details (optional)

would clean up the manifest and provide a way for the user to know that winget wont run an update but when a program is launched.

Most of these apps allow you to download a beta version of the program with in the program it self.  This may cause a issue when running winget upgrade --all

**Comment by denelon** [comment]
Duplicate of #1163
