### ISSUE TITLE
Is there any winget source available?

### ISSUE THREAD

**Issue by nssiwi** [microsoft/winget-cli#1151]
the default source is `https://winget.azureedge.net/cache` ， but The specified resource does not exist. RequestId:682ecae6-101e-0001-3a72-5e9aec000000 Time:2021-06-11T03:33:13.4035588Z

**Comment by denelon** [comment]
@nssiwi can you share the ouput from `winget --info`?

**Comment by nssiwi** [comment]
> @nssiwi can you share the ouput from `winget --info`?

`
Windows: Windows.Desktop v10.0.19042.1052
程序包: Microsoft.DesktopAppInstaller v1.11.11451.0
`

**Comment by denelon** [comment]
@nssiwi have you tried `winget source reset`?

This may be a network issue related to fetching the PreIndexed source package.

**Comment by bdbch** [comment]
Same here

```
Windows Package Manager v1.0.11451
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1052
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
```

https://downforeveryoneorjustme.com/ also tells me that the resource is not available / down.

**Comment by ItzLevvie** [comment]
cc @bdbch @nssiwi: Are you sure that your internet isn't blocking the `winget.azureedge.net` subdomain? What happens when you go to https://winget.azureedge.net/cache?

**Comment by bdbch** [comment]
@ItzLevvie it works fine now. I guess for me it was just a downage for that time? As I said I also tried using external sources to determine if the url was throwing 404s.

But it's okay now

**Comment by denelon** [comment]
@nssiwi 

We've published the v1.1 [release candidate](https://github.com/microsoft/winget-cli/releases/tag/v1.1.12653) and updated our [troubleshooting guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting).

Can you confirm if this is still happening?

**Comment by orifjonmelibayev** [comment]
This is happening to me. I can download `https://winget.azureedge.net/cache/source.msix`, but getting ResourceNotFound for https://winget.azureedge.net/cache

**Comment by bogdanrbucur** [comment]
Same here. No idea...

```PowerShell
PS C:\Users\bogda> winget --info
Windows Package Manager v1.2.10691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3737
Package: Microsoft.DesktopAppInstaller v1.17.10691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
PS C:\Users\bogda> winget source update
Updating all sources...
Updating source: msstore...
Done
Updating source: winget...
Cancelled
PS C:\Users\bogda> winget source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://winget.azureedge.net/cache
```
