### ISSUE TITLE
list command throws segment fault

### ISSUE THREAD

**Issue by ZnqbuZ** [microsoft/winget-cli#1152]
# Brief description of your issue
![image](https://user-images.githubusercontent.com/40349250/121629432-b46b0e80-caad-11eb-8e52-cb8130d9e811.png)

# Environment
Windows Package Manager v1.0.11451

Windows: Windows.Desktop v10.0.19043.1052
Microsoft.DesktopAppInstaller v1.11.11451.0

%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

```
Log file: [WinGet-2021-06-11-12-08-02.250.log](https://github.com/microsoft/winget-cli/files/6635752/WinGet-2021-06-11-12-08-02.250.log)
```

Have tried:
    reinstall Microsoft.DesktopAppInstaller
    reset winget source

**Comment by denelon** [comment]
@ZnqbuZ can you reproduce this?

If you can, would you submit a [Feedback](https://aka.ms/winget-feedback) report and share the link to the feedback here?

**Comment by jpl-mac** [comment]
I've hit this right after installing Python.Python.3.  I've only started using winget a couple days ago and now this.  winget throws segfaults for every command.  

How can I get it back to a working state?  I thought it was pretty useful but now it's totally useless with no indication of how to fix it.

**Comment by denelon** [comment]
Have you tried to reinstall it? You can just open the .msixbundle in [releases](https://github.com/microsoft/winget-cli/releases). It would also help if you could share logs. The path is visible via `winget --info`. I'd also like to see the output from there to see which version you are running, and which OS version. 

I'm also not sure if there are any unintended interactions with Git bash.

**Comment by jpl-mac** [comment]
[Update2]: uninstalling python from cmd got winget to work again in git bash.  I reinstalled python from cmd and winget still works.  Now only python hangs in git bash but looks fine in cmd.

--

$ winget --info
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1706
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

**Comment by denelon** [comment]
Does anyone have good instructions for reproducing this error?

In particular, I would like to see if this happens in [Windows Package Manager 1.3 Release Candidate](https://github.com/microsoft/winget-cli/releases/tag/v1.3.1681)

I'd like to see if there is something we can do in Windows Package Manager or isolate it to an installer that might be causing this problem so we can try to track it down, or notify the publisher of what's happening.
