### ISSUE TITLE
Copy settings on export

### ISSUE THREAD

**Issue by SonOfDiablo** [microsoft/winget-cli#1154]
# Description of the new feature/enhancement

It would be amazing if a list of files could be included in the manifest, these files would then be copied on export/import such that you don't have to manually copy over settings files if you were to reinstall windows or other such things.

I know this isn't possible for all applications, but at least having the option would be great and hopefully devs would notice this and adapt their applications to be able to benefit from this feature.

# Proposed technical implementation details (optional)

**Comment by denelon** [comment]
I think this particular scenario is better handled via WinGet configuration:
* https://github.com/microsoft/winget-cli/issues/3274

I'm going to close this issue in favor of that one. Please add your 👍 on the other issue.

The mechanism would be part of a PowerShell DSC resource with support for getting the application settings for a particular package.
