### ISSUE TITLE
Enhancements to upgrade (Apps that upgrade themselves)

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#1163]
# Description of the new feature/enhancement

Several packages manage upgrades themselves. One example is Visual Studio Code.

# Proposed technical implementation details (optional)

Add a key to the manifest to identify packages with this capability.
>Placeholder value: "PackageAutoUpgrades" (optional boolean key)

When the user executes `winget upgrade` this package would either not be displayed (as having an upgrade available), or it would be displayed in a manner that indicates this behavior.

When the user executes `winget upgrade --all` this package would not be upgraded.
To be in line with `--include-unknown` we should add `--include-automatic`.
We may also want to consider `--force` to apply all `--include-<*>` options.

>Note: Schema changes have a large surface area: (Client, Validation Pipelines, Publishing Pipelines, REST API, Manifest Creator). This key may be added to the schema ahead of implementing the behavior in the client.

**Comment by Skgland** [comment]
Isn't this the same as #1137 but targeting a superset of packages as the other issue is only concerned with forced upgrades on launch where this is for all packages that will upgrade themselves, but not necessarily force an upgrade?

**Comment by denelon** [comment]
@Skgland, yes this is a "more generic" case so the publisher could essentially use this for a package that doesn't force an upgrade, but may support the option in their application. 

@mddtest would you agree this covers the scenario in #1137 as well?

**Comment by mddtest** [comment]
I think it's best to only have it not show updates for ones that force update on launch.

If the app can be updated thought the program at any time it should still fit under the update --all parameter

Update on launch of program. Should be blocked.

Update with in program. Should still show up.

**Comment by denelon** [comment]
We're thinking about these, and we have looked a bit into the future regarding our plans to support package pinning #476. This would align with pinned packages don't automatically get upgraded with `winget upgrade --all`.

How about:

```YAML
Installers:
  - InstallerType: exe
    InstallerArchitecture: x64
    InstallerSHA256: 12341234123412341234123412341234123412341234
    InstallerURL: https://www.contoso.com/awesomeapp/1.0.0/awesomeapp.x64.exe
    AutoPin: true
```

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/blob/5a97e26ba3efb6b1f0d5997ec9de7d16b8fa52b9/schemas/JSON/manifests/v1.1.0/manifest.installer.1.1.0.json#L367-L370

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/pull/1427
