### ISSUE TITLE
Packages that do not upgrade o report incorrect package version 

### ISSUE THREAD

**Issue by musm** [microsoft/winget-cli#1192]
The following packages
```
Cisco Webex Meetings              Cisco.CiscoWebexMeetings 41.5.4       41.5.6.9    winget
Geekbench 5                       PrimateLabs.Geekbench.5  Unknown      5.4.1       winget
Mozilla Firefox                   Mozilla.Firefox          89.0         89.0.1      winget
WhatsApp                          WhatsApp.WhatsApp        2.2121.6     2.2123.7    winget
Microsoft Windows Desktop Runtime Microsoft.dotnetRuntime  3.1.16.30112 5.0.7.30113 winget
```

Prepetually state that they are upgradable, despite upgrading them multiple times. I suspect there is an issue somewhere with the packages reporitng their version numbers.

**Comment by KaranKad** [comment]
Might be related to this https://github.com/microsoft/winget-cli/issues/1191#issuecomment-865210093

**Comment by musm** [comment]
@KaranKad That does indeed seem to fix the Mozilla and WhatsApp issues. Hopefully when those packages get an update, I won't have the same problem.

**Comment by musm** [comment]
So geekbench doesn't report the correct version, it seems like it would make sense for winget-cli to then fallback gracefuly to the verison recorded in the Manifest? That should be doable if winget records the installed version for packages through winget-kgs.

**Comment by Spyromaniac31** [comment]
Some way to hide packages from `winget upgrade` would be useful for dealing with packages that report the incorrect version or none at all.

**Comment by denelon** [comment]
I think we've captured the scenarios here in [Windows Package Manager 1.3 Release Candidate](https://github.com/microsoft/winget-cli/releases/tag/v1.3.1681).

The exclusion of "Unknown" packages by default in `winget upgrade --all` gets some of them and I believe the rest are captured by:

* #1543

Can you confirm?
