### ISSUE TITLE
Warning for different InstallerType

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#1196]
# Description of the new feature/enhancement

When a user attempts to upgrade a package, and the installer type doesn't match. The user should be informed.

# Proposed technical implementation details (optional)

Instead of the message `No applicable update found.` the user should be informed the upgrade is a different installer type. 
>Note: We need to test a couple of known packages like:
PowerToys - MSI installer inside of a .exe installer
[Python](https://github.com/microsoft/winget-cli/issues/1191#issuecomment-865214306) - may have been installed with a different installer type.
Optionally the user should be able to force the upgrade if this isn't a breaking scenario

**Comment by Trenly** [comment]
@denelon - Is this resolved in the 1.3 preview client with #1649 ?
