### ISSUE TITLE
Microsoft.OneDrive update gets stuck at Starting package install

### ISSUE THREAD

**Issue by ageekhere** [microsoft/winget-cli#1197]
# Brief description of your issue

When I tried to update Microsoft.OneDrive to 21.109.0530.0001 it gets stuck on Starting package install...
# Steps to reproduce

Upgrade Microsoft.OneDrive
# Expected behavior

Microsoft.OneDrive updates
# Actual behavior

Install gets stuck at Starting package install...

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
```

**Comment by denelon** [comment]
@ageekhere can you share the output from `winget --info`?

What version of OneDrive do you have installed on your machine?
Can you share the output from `winget list onedrive`?

Do you know how you originally installed OneDrive on the machine?

**Comment by ageekhere** [comment]
Microsoft OneDrive Microsoft.OneDrive 21.099.0516.0003 21.109.0530.0001 winget
PS C:\WINDOWS\system32> winget --info
Windows Package Manager v1.0.11451
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1055
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget

OneDrive originally default install by windows (came with windows 10).

**Comment by 2br-2b** [comment]
This has also just happened for me for either Marktext or Joplin (I forget which). It could have just been taking a while - I encountered a long wait time this while updating Logitech Gaming Software [Logitech.LGS], but eventually it worked.

For Marktext/Joplin, the line wasn't spinning, but when I pressed ^C to kill the app, it said it was successfully installed. I haven't found any problems with the installed software yet.

I had installed both using the installers from their websites, but uninstalled them and used winget once I saw I could use it to update all my software at once.

winget --info:

```
Windows Package Manager v1.0.11692

Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1165
Package: Microsoft.DesktopAppInstaller v1.12.11692.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
```
