### ISSUE TITLE
0x80070003 : The system cannot find the path specified.

### ISSUE THREAD

**Issue by JJussi** [microsoft/winget-cli#1203]
# Brief description of your issue
winget install <x> produces error

# Steps to reproduce

Unknow - even reinstall of winget didn't fix problem. Command has never worked

# Expected behavior

Install requested package

# Actual behavior

Error!
Here is an example, but the result is same with all packages what are not present yet.

>winget install "Bicep CLI"
Found Bicep CLI [Microsoft.Bicep]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://github.com/Azure/bicep/releases/download/v0.4.63/bicep-setup-win-x64.exe
An unexpected error occurred while executing the command:
0x80070003 : The system cannot find the path specified.

Problem "could" be my user name, because it have non-US characters.

# Environment

Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.21390.2025
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

Logs: [WinGet-2021-06-22-20-12-40.835.log](https://github.com/microsoft/winget-cli/files/6696254/WinGet-2021-06-22-20-12-40.835.log)

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
Licence Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget

```

**Comment by rbarbrow** [comment]
I tried from my prompt (with only us char) and it worked fine.

**Comment by JJussi** [comment]
I created a second user with the name jjussi and winget worked fine.  
With user name (the full name comes from AAD) Jussi Jääskeläinen, winget has problems with user directory path.

**Comment by denelon** [comment]
@JJussi

We've published the v1.1 [release candidate](https://github.com/microsoft/winget-cli/releases/tag/v1.1.12653) and updated our [troubleshooting guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting).

Can you confirm if this is still happening?

**Comment by JJussi** [comment]
Yes, I can confirm. Now I can install with winget even the user name is 'Jääskeläinen'

**Comment by GiulianoSpaghetti** [comment]
please verify the packageversion tag on the .install.yml file.
In my files there is a whitespace: PackageVersion: '2.4.0.5 ', when it should be '2.4.0.5'.
Solving this it works on my personal rewinged server.
