### ISSUE TITLE
Failed Discord upgrade uninstalls the old version

### ISSUE THREAD

**Issue by DejanRibnikar** [microsoft/winget-cli#1214]
I tried to upgrade my Discord app with winget. It downloaded and confirmed installed hash, then showed an unknown error and aborted the install. I then wanted to open my previously installed Discord app, which was no longer available on my PC. It just left blank shortcuts in taskbar and start menu.

**Comment by denelon** [comment]
We've got a new release coming shortly. I think the issue with Discord may already be resolved.

**Comment by denelon** [comment]
@DejanRibnikar 

We've published the v1.1 [release candidate](https://github.com/microsoft/winget-cli/releases/tag/v1.1.12653) and updated our [troubleshooting guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting).

Can you confirm if this is still happening?
