### ISSUE TITLE
Better winget validate error message

### ISSUE THREAD

**Issue by cub525** [microsoft/winget-cli#1222]
# Description of the new feature/enhancement
A Slightly more useful error message would be extremely helpful; I ran the validate step and I got the following message:
```
[YAML:Reader] control characters are not allowed [3] at 2
```
nota bene: I used wingetcreate to create this manifest.
[OpenStenoProject.Plover.manifests.zip](https://github.com/microsoft/winget-cli/files/6719315/OpenStenoProject.Plover.manifests.zip)

**Comment by denelon** [comment]
https://github.com/microsoft/winget-create/issues/96

**Comment by johnwhitington** [comment]
I just had this issue - one of my manifest files was open in Vim, and so the vim backup file 
was in the directory in addition to the manifest files. I got:

```
PS C:\Users\John> winget install -m "$($env:USERPROFILE)\manifests\c\CoherentGraphics\Cpdf\2.8.1"
An unexpected error occurred while executing the command:
[YAML:Reader] control characters are not allowed [0] at 9
0x8a150004 : Opening manifest failed
```

This is WinGet v1.10.340.

Can we at least have it print the name of the file it is trying to read when the error occurs?
