### ISSUE TITLE
Manifest Schema v1.1

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#1243]
# Description of the new feature/enhancement

We will be adding multiple new nodes to the schema to support future features. The schema suggestions are in the following features:

* #200
* #713
* #873
* #967
* #970
* #993
* #1073
* #1145
* #1163
* #1227
* #1241
* #1242
* #1278
* #1284

# Proposed technical implementation details (optional)

These schema values will be added, but the features may not be implemented in the next release. This will help consolidate the complex efforts related to schema changes across the Windows Package Manager client, the Windows Package Manager Manifest Creator, the validation pipelines, the publishing pipelines, and our periodic validation services.

**Comment by Karl-WE** [comment]
Are the new schemas reflected in the YAML store app UI?
source: https://www.microsoft.com/en-us/p/yaml-generator-for-windows-package-manager/9p3n60fs22k5?activetab=pivot:overviewtab

**Comment by ItzLevvie** [comment]
You'll have to contact the application developer to allow creation of 1.0 and above manifests.

**Comment by denelon** [comment]
I contacted the author to let them know about the schema changes.

**Comment by ptorr-msft** [comment]
Thanks - I have been on leave for most of the year so wasn't keeping up. I have temporarily hidden the app and will work with @denelon to see if it's worth updating or not.

**Comment by denelon** [comment]
> Are the new schemas reflected in the YAML store app UI?
> source: https://www.microsoft.com/en-us/p/yaml-generator-for-windows-package-manager/9p3n60fs22k5?activetab=pivot:overviewtab

I don't believe anything other than the Windows Package Manager client and the reference implementation for the REST API have the new schema at this time.

**Comment by Karl-WE** [comment]
@denelon the project of YAML generator seems not to be active atm
https://github.com/ptorr-msft/WinGetYamlGenerator/graphs/code-frequency
@ptorr-msft

**Comment by denelon** [comment]
It was removed now that we have [wingetcrate](https://github.com/microsoft/winget-create). Be sure to 👍 microsoft/winget-create/issues/159 if you want a GUI.

**Comment by ptorr-msft** [comment]
Right, I de-listed it from the Store. I'll update the GitHub readme as well.
