### ISSUE TITLE
Disallow empty query on search

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#1249]
# Description of the new feature/enhancement
When a user runs `winget search` with no parameters, no switches, or an empty search string, they receive a list of many, many packages. Running a search with no query is a very rare and infrequent use case for a package manager. This would help a user understand when the search is not going to give meaningful results

# Proposed technical implementation details (optional)
- If there are no switches used and no query string, show the command usage (alias of `winget search -?`)
- If the query string is `""` throw an invalid argument error and show the command usage
- Treat a combination of a switch and parameter as a valid query

Require searches to have a query that will return meaningful results
```powershell
# Expected Results:
winget search  # Returns the command usage
winget search ""  # Returns an invalid argument error and shows the command usage
winget search Test # Returns all packages matching the query "Test"
winget search --moniker Test # Returns all packages matching the moniker "Test"
winget search Test --tag system # Returns all packages matching the query "Test" with a tag of "system"
winget search --moniker "" # Returns an invalid argument error and shows the command usage
winget search --moniker # Returns argument value required error
winget search -n 5 # Returns an invalid argument error - query string is required
```

**Comment by rdeforest** [comment]
I disagree. This proposal assumes it can read the user's mind and that they didn't do what they meant to do. Here's a use-case for an empty search:

```console
PS C:\Users\Robert de Forest> $i=0; winget search | foreach-object { $i++ }; echo $i
2699
PS C:\Users\Robert de Forest>
```

You could add a switch to search to request a count of all packages, but that feature already exists using the construction above. This proposal solves a problem which does not exist.
