### ISSUE TITLE
Microsoft 365 (Office) cannot be installed due to installer hash being different.

### ISSUE THREAD

**Issue by ShinraCorpMixer** [microsoft/winget-cli#1252]
# Brief description of your issue

Microsoft 365 cannot be installed intermittently via Winget due to installer hash being different. I'm testing a Powershell script to automate the installation of various applications via Winget, sometimes Office installs correctly, sometimes it doesn't...

# Steps to reproduce

Run Powershell as Admin.
winget install Microsoft.Office

# Expected behavior

A blank command prompt window to appear and Microsoft 365 being installed.

# Actual behavior

An error message saying that the installer hash does not match.
![image](https://user-images.githubusercontent.com/55590236/124291792-ef97b500-db22-11eb-9056-ffb4b7aad582.png)

# Environment

Windows Package Manager v1.0.11692
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.1052
Package: Microsoft.DesktopAppInstaller v1.12.11692.0

Any other software?
```

**Comment by jedieaston** [comment]
A PR was opened in the other repo that fixed the hash. Has your problem been fixed?

**Comment by ShinraCorpMixer** [comment]
> A PR was merged in the other repo that fixed the hash. Has your problem been fixed?

Yes, I've tested it out and it works again! Thank you! 👍
