### ISSUE TITLE
Add logos to packages

### ISSUE THREAD

**Issue by SlimRG** [microsoft/winget-cli#1253]
Today I develop my program WingetGUI
So... I'd like to show logos of apps.
In my opinion, it will be a good idea to have URL on logo of package
New windows terminal also support images in title, so you can use this logo in installation progress too.
What do you think about it?

**Comment by rbarbrow** [comment]
how would you show a logo via a command-line interface?

**Comment by SlimRG** [comment]
Something like that?
![image](https://user-images.githubusercontent.com/39348033/124379822-ebee6480-dcc1-11eb-869e-31dd4e4a7df1.png)

**Comment by jantari** [comment]
> how would you show a logo via a command-line interface?

It would just be ignored by the command-line `winget`. I think it's a good idea to have an OPTIONAL logo url in the manifest for GUI wrappers to consume.

**Comment by SlimRG** [comment]
Yes, of course
Logo URL should be only OPTIONAL parameter of manifest

**Comment by khaffner** [comment]
I had the same idea, but did not find this issue before i posted here: https://github.com/microsoft/winget-pkgs/issues/22577 

I support this :+1:

**Comment by drewid** [comment]
Definitely should be supported as the repo could/should definitely be resourced other than command line to be more useful and holistic.

**Comment by drewid** [comment]
Should be a simple manifest addition

**Comment by khaffner** [comment]
> Should be a simple manifest addition

Yes, I see two options:

1. Encode the image in base64. Takes huge amount of space, but the maintainers have full control over the content of the image. Inelegant.
2. A link to an image. This opens up to third parties modifying the image to something awful without winget knowing, except if we also have a field in the manifest for the hash of the image. The same way installer files are secured in the manifest. GUI implementations can then get the image, verify hash, and only show image if hashes match.

**Comment by denelon** [comment]
We're tracking this work in:
* https://github.com/microsoft/winget-cli/issues/3026

The schema support has been added to the 1.5 schema. The WinGet community repository will not accept manifests with the icon fields included (by policy), but we will be fetching them during validation, and exposing them via the COM API so other GUI based solutions can display them. Once the back-end work is completed, all 1.5 manifests will be used as the signal to capture the icon and make it available via a URL, and the SHA256 for the image and the image type will be automatically included in the manifests served by WinGet even though this metadata will not be in the winget-pkgs repository.

Note: The [Dev Home](https://github.com/microsoft/devhome) experience will provide an example of how to implement this once it's all wired up.

https://github.com/microsoft/winget-cli/blob/83cd0dcaddd31cc64570422b081f7743a79dc10d/schemas/JSON/manifests/v1.5.0/manifest.defaultLocale.1.5.0.json#L54-L112
