### ISSUE TITLE
Multiple separate version reports upon `winget upgrade`

### ISSUE THREAD

**Issue by cilerler** [microsoft/winget-cli#1258]
# Steps to reproduce

The following command will install the package that I identified with the issue.

```
winget install Microsoft.dotnet;
```

# Expected behavior

`winget upgrade` should not report two separate versions for the same package.

# Actual behavior

It shows the same package with different versions.

![image](https://user-images.githubusercontent.com/385958/124595453-07c34900-de2f-11eb-98a2-fbe43724f253.png)

# Environment

```none
Windows Package Manager v1.0.11692
Windows: Windows.Desktop v10.0.19043.1052
Package: Microsoft.DesktopAppInstaller v1.12.11692.0
```

**Comment by denelon** [comment]
The .net SDK does get treated as different "packages". They run side by side so other packages with version specific dependencies don't break. There are several other issues discussing this topic.

**Comment by cilerler** [comment]
Thanks, @denelon, and that is precisely my point.  It should treat them as separate packages since you may want to have **5.1.200** and **5.2.100** side by side, and that doesn't mean that it should suggest upgrading all to **5.3.0**

If you don't mind, can you give me a reference issue that covers the problem here to close this one.  Thank you so much for your attention and participation.

**Comment by denelon** [comment]
@cilerler, this is the latest comment:

https://github.com/microsoft/winget-pkgs/issues/17985#issuecomment-874321711

**Comment by cilerler** [comment]
Perfect, thank you!  Closing this issue since it is a duplicate.
