### ISSUE TITLE
Winget List is very slow in Windows 11

### ISSUE THREAD

**Issue by MathiasDevelopes** [microsoft/winget-cli#1259]
# Brief description of your issue
Winget List is slow

# Steps to reproduce
Use winget list on windows 11

# Expected behavior
Winget List returns all the packages and all the new versions fast

# Actual behavior
Winget List is slower than before

# Environment

```none
[winget --info]
Windows Package Manager version v1.0.11694
Windows: Windows.Desktop version v10.0.22000.51
Package: Microsoft.DesktopAppInstaller version v1.15.11694.0

Any other software? No
```

**Comment by rbarbrow** [comment]
is it fair to test the speed on a beta?

**Comment by MathiasDevelopes** [comment]
> is it fair to test the speed on a beta?

I wanted to let the developers know. I have also found a similar question on feedback hub. I don't know if it is my beta build or winget itself.

**Comment by denelon** [comment]
Duplicate of #855
