### ISSUE TITLE
Install downloads 2 byte file and fails hash verification

### ISSUE THREAD

**Issue by MasterPackager** [microsoft/winget-cli#1261]
# Brief description of your issue
Our package fails to install due to hash verification failure since the manifests were updated to 1.0 schema.
winget seems to be downloading a 2 byte file instead of the actual 15 MB .MSI file. All of our previous versions have the same problem.
![image](https://user-images.githubusercontent.com/51095201/124665221-20764200-deb5-11eb-9e40-5d701d796959.png)

# Steps to reproduce

winget install MasterPackager

# Expected behavior

The package is downloaded, hash is verified and package is installed.

# Actual behavior

We receive the following error - "Installer hash does not match; this cannot be overridden when running as admin" and it  seems to be downloading a 2 byte file instead of the actual 15 MB .MSI file.

# Environment
Clean Windows 10 20H2 VM with no other software.
Windows Package Manager v1.0.11692
Windows: Windows.Desktop v10.0.19042.746
Package: Microsoft.DesktopAppInstaller v1.12.11692.0

**Comment by ItzLevvie** [comment]
For me, the solution to this was to switch to wininet rather than do.

**Comment by MasterPackager** [comment]
@ItzLevvie  Is this something we should fix on our website where the file is stored?

**Comment by denelon** [comment]
We've see this issue occur most frequently when the URL for the download has a redirect to an http:// URL rather than an https:// URL. The Delivery Optimization (DO) downloader doesn't support HTTP redirects. DO attempts to use range requests to pull the file down in smaller pieces via parallel download for optimization. Changing the settings to use wininet is a temporary workaround until we either make a hard policy decision about https:// or we find a better way to detect when this occurs and we can fall back to wininet "faster".

**Comment by MasterPackager** [comment]
@denelon but in this case the URL is https?

**Comment by ItzLevvie** [comment]
> @ItzLevvie Is this something we should fix on our website where the file is stored?

I think so. It might be that Delivery Optimization doesn't support some of the features on your server that WinINet supports.

I think the only way to tell is to make a program that exports headers with Delivery Optimization and WinINet and then compare both of them to see the differences.

Delivery Optimization (DO):
![image](https://user-images.githubusercontent.com/11600822/124745846-26e9d580-df18-11eb-8208-d4f56fcbf008.png)

WinINet:
![image](https://user-images.githubusercontent.com/11600822/124745920-3a953c00-df18-11eb-8f01-d33396d6ecc1.png)

You can take a look at the comments from https://github.com/microsoft/winget-pkgs/pull/15665 to see what may be happening.

**Comment by denelon** [comment]
@MasterPackager

We've published the v1.1 [release candidate](https://github.com/microsoft/winget-cli/releases/tag/v1.1.12653) and updated our [troubleshooting guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting).

Can you confirm if this is still happening?

**Comment by MasterPackager** [comment]
@denelon we can confirm we still have this problem
![image](https://user-images.githubusercontent.com/51095201/135970324-1211200a-ddd2-4add-be14-543528c328d2.png)

**Comment by MasterPackager** [comment]
@denelon any idea what we need change on our website to not get this error anymore?

**Comment by denelon** [comment]
@MasterPackager I don't know what is causing this yet. We're heads down on bugs, so I'm hoping we get to this in the coming weeks and can have someone from the engineering team share more details on exactly how the validation service is attempting to verify packages, and what differences if any may be impacting the client. There are a few possibilities like interaction with Delivery Optimization and whether the server supports HTTP range requests on the top of my mind currently.

**Comment by MasterPackager** [comment]
@denelon we managed to finally fix it by changing the url to this one - https://www.masterpackager.com/installer/professional/masterpackager_21.2.7837.0.msi
Should we close the issue? Or do you want to keep it open until you figure out why the other url doesn't work?

**Comment by vedantmgoyal2009** [comment]
I think it should be closed treating it as an edge case.

**Comment by denelon** [comment]
@MasterPackager thanks for following up. Yes, go ahead and close the issue if you have a resolution. Until we have enough other instances to see what's common, I don't think we have enough to go on. I'm pretty sure one of us will remember the issue well enough if it pops up again, and we can check the history for context and other possible URLs.

**Comment by denelon** [comment]
For some additional context, we do have an ask for the Delivery Optimization service to support https -> http redirects.
