### ISSUE TITLE
Default to Silent Install and Show Progress

### ISSUE THREAD

**Issue by Trance-Paradox** [microsoft/winget-cli#1263]
# Description of the new feature/enhancement

Winget doesn't install any software silently by default. We have to add -h or --silent to make silent installation.
Feature silent install as default and also adding progress bar in terminal to show the progress of the install

**Comment by denelon** [comment]
@Trance-Paradox we're doing some work with MSI installers to support silent and get the progress reported. MSIX already behaves correctly. It's mostly .exe installers that don't consistently emit progress. Let's see if others have a strong opinion about silent as the default.

**Comment by Fayyaadh** [comment]
If silent install means having the installation being done in the background, then yeah, that most definitely needs to be the default.

**Comment by Trance-Paradox** [comment]
@denelon can you enable the progress bar for msix installer for now? And when msi and exe installer are implemented (if implemented) then enable those in the future

**Comment by denelon** [comment]
We have some other improvements coming with how we install MSIX packages (deferred registration). I expect we'll look at the progress bar when we tackle that.

**Comment by KaranKad** [comment]
Would definitely prefer silent install instead of silent with progress as default option.

**Comment by denelon** [comment]
Closed in favor of:
* #1942
