### ISSUE TITLE
i get a error

### ISSUE THREAD

**Issue by TekSoup** [microsoft/winget-cli#1266]
I try to install, and i get this. 
![fail](https://user-images.githubusercontent.com/39171003/125000710-d81a6980-e005-11eb-8485-1113a52454c9.png)

**Comment by rbarbrow** [comment]
you need to update the windows store

**Comment by denelon** [comment]
@TekSoup

We've published the v1.1 [release candidate](https://github.com/microsoft/winget-cli/releases/tag/v1.1.12653) and updated our [troubleshooting guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting).

Can you confirm if this is still happening?
