### ISSUE TITLE
winget install -h lists all packages

### ISSUE THREAD

**Issue by Bilal-io** [microsoft/winget-cli#1267]
# Brief description of your issue
winget install -h lists all packages instead of listing help information

# Steps to reproduce
Run `winget install -h`

# Expected behavior
List of possible options, helpful tips of how to use the `winget install` command

# Actual behavior
Lists all the possible package that can be installed with winget

# Environment

```none
[winget --info]
Windows Package Manager version 1.0.11694
Windows: Windows.Desktop version 10.0.22000.65 (Windows 11 latest build)
Package: Microsoft.DesktopAppInstaller version 1.15.11694.0

Any other software?
```
None

**Comment by Bilal-io** [comment]
I'd like to clarify, the expectation described above is not necessarily based on the winget CLI documentation, but rather a general expectation I have when using any CLI, and I thought winget should behave the same way.

If the team does not consider this a bug, then please take it as feedback.

**Comment by denelon** [comment]
@Bilal-io the current "short" help argument is `-?` the long form argument is `--help`.

The client currently has `-h` for `--silent` ("hush") as a synonym.
The `-s` was already taken for `--source`.

We do have a feature to switch to silent as the default install behavior. If that gets implemented we can use `-p` for `--silent-with-progress` which would free up `-h` for `--help`.

**Comment by denelon** [comment]
Adding the link to help track this for implementation purposes: https://github.com/microsoft/winget-cli/issues/1263

**Comment by Bilal-io** [comment]
@denelon I believe this issue is not directly related to the `-h` argument.
If I type `winget install` without a query I still get a list of all packages, which feels wrong. That's 2916 items all listed at once (as of today).
Does the winget team have a strong reason for why query is optional? The same question applies to `winget search`

**Comment by denelon** [comment]
@Bilal-io this is an ongoing usability discussion. One might have a valid command without passing a value for the query. If the name, moniker, etc. is specified the results are narrowed down. We are considering changes for this as potentially breaking. It may wait until we decide to take other breaking changes into a 2.0 release.

**Comment by Trenly** [comment]
@denelon - I believe this has been resolved; Running `winget install -h`  currently provides the error message `No package selection argument was provided; see the help for details about finding a package.` as well as shows the help dialogue.
