### ISSUE TITLE
IntelliJ IDEA Community 211.7628.21 installs in `C:\Program Files (x86)` instead of `C:\Program Files`

### ISSUE THREAD

**Issue by hrishikesh-kadam** [microsoft/winget-cli#1288]
# Brief description of your issue

IntelliJ IDEA Community 211.7628.21 installs in `C:\Program Files (x86)` instead of `C:\Program Files`

The issue is that the `bin` folder needs to be kept in `PATH` to invoke it from the terminal.
Is the issue on the IntelliJ IDEA side or this can be solved by tweaking [manifest][1].

# Steps to reproduce

`winget install intellij-idea-community`

# Expected behavior

Installation should be done in `C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.3`

# Actual behavior

Installation happened in `C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2021.1.3`

# Environment
```none
> winget --info
Windows Package Manager v1.0.11692
Windows: Windows.Desktop v10.0.19043.1110
Package: Microsoft.DesktopAppInstaller v1.12.11692.0
```

[1]: https://github.com/microsoft/winget-pkgs/tree/master/manifests/j/JetBrains/IntelliJIDEA/Community/211.7628.21

**Comment by hrishikesh-kadam** [comment]
For Android Studio, `winget install android-studio` does install correctly in `C:\Program Files`.
I couldn't find the difference between [Android Studio][1] and [IntelliJ IDEA Community][2] manifests.

[1]: https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/Google/AndroidStudio/4.2
[2]: https://github.com/microsoft/winget-pkgs/tree/master/manifests/j/JetBrains/IntelliJIDEA/Community/211.7628.21

**Comment by ItzLevvie** [comment]
What happens when you download it from the URL using a browser and then installing it manually rather than from WinGet? It might be an issue with JetBrains' installers.

You can use `--location` with `winget install` to install it where you want.

**Comment by hrishikesh-kadam** [comment]
> What happens when you download it from the URL using a browser and then installing it manually rather than from WinGet? It might be an issue with JetBrains' installers not placing the files where it needs to be.

It asks for the Destination Folder to install and prefills with "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.3"

![image](https://user-images.githubusercontent.com/8739924/125816797-57137b91-218d-4a45-97f5-65ce17c0ea70.png)

> You can use --location "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.3" (winget-cli will run it with /D=[DIRECTORY]) with winget install to install it in the location where you would like it to install.

I was aware of `--location` but thought of asking for help.
I preferred to drop the version from the location path as below.

`> winget install intellij-idea-community --location "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition"`

This is working as expected.
Thanks for the help.

**Comment by hrishikesh-kadam** [comment]
Opened an issue on JetBrains side - https://youtrack.jetbrains.com/issue/IDEA-273824

**Comment by denelon** [comment]
@hrishikesh-kadam thanks for creating the issue for JetBrains to evaluate. I put a 👍 on it. Feel free to create an issue at winget-pkgs. I'll mark it as "Area-External", and we can keep it open to have a link to the JetBrains Issue, and others might be willing to upvote. Once it gets resolved, we can close the issue over at winget-pkgs.
