### ISSUE TITLE
When will winget be part of the non-insider windows experience?

### ISSUE THREAD

**Issue by vinczemarton** [microsoft/winget-cli#1297]
I'm not the biggest fan of beta software. When winget was announced I kept an eye on it and waited for it to become part of the stable windows ecosystem.

Since the software got to 1.0 I thought that this will be the time when it starts to be available outside the insiders program, but it is still just for insiders.

Plans for the stable rollout are unclear for me as I cannot find any statement regarding when will it happen or will it ever happen.

**Comment by jedieaston** [comment]
This has been covered in other places, but the current plan is September.

Related discussion message: https://github.com/microsoft/winget-cli/discussions/988#discussioncomment-793667
