### ISSUE TITLE
Package Version is not sorted correctly for versions of type vXX.X

### ISSUE THREAD

**Issue by Timber1900** [microsoft/winget-cli#1298]
# Brief description of your issue

Packages whose version are written like `vXX.x` (eg. v10.1) aren't sorted correctly
![image](https://user-images.githubusercontent.com/9287896/126064522-20f173de-903d-482b-ac2a-960969d9450c.png)
![image](https://user-images.githubusercontent.com/9287896/126064576-5c30df11-3785-4e36-a0b9-7aae3f81cc5c.png)

# Steps to reproduce

Look at the Timber1900.WebDL package, the latest version is v10.2, however the version that shows up in winget is the earliest v9.2

# Expected behavior

Winget displaying the latest version as v10.2

# Actual behavior

Winget displays the latest version as v9.2

# Environment

```none
Windows Package Manager v1.0.11591
Windows: Windows.Desktop v10.0.22000.71
Package: Microsoft.DesktopAppInstaller v1.11.11591.0
```

**Comment by quangkieu** [comment]
I think this is issue that manifest did not updated. As winget does not access github directly. You should open in winget-pkgs

**Comment by Timber1900** [comment]
What do you mean by `manifest did not updated`. 
All manifests are in the master branch of winget-pkgs, and installing with the `-v v10.2` option installs the correct version, which makes me believe the problem is with the cli itself

**Comment by Timber1900** [comment]
- Also running `winget show Timber100.WebDL --versions` show all the versions in the incorrect ordering

![image](https://user-images.githubusercontent.com/9287896/126197488-caaa6913-736c-4c7e-b17b-ffdc06bb6717.png)
Interestingly the .X part is sorted correctly, the only wrong part being v9 vs v10

**Comment by gkroonder** [comment]
> Interestingly the .X part is sorted correctly, the only wrong part being v9 vs v10
It is sorting as alpha not numerical; zz9something is "greater" than zz1something. Same for v9 vs v1 (~v10).

But I think this is clear to the devs.

Regards,
George

**Comment by denelon** [comment]
I believe the sorting for Timber1900.WebDL has been worked out. We've got an open PR looking at better behavior for software versions with preambles, but this Issue looks safe to close.

<img width="867" alt="version sorting" src="https://user-images.githubusercontent.com/61799811/214176082-0cb9cee2-9c9d-4903-8acc-932f9dcbb62c.png">
