### ISSUE TITLE
Cannot install VSCode on Win10/ARM64 device

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/winget-cli#131]
# Environment

Windows 10 20129 on ARM64 device.

```none
winget --info
Windows Package Manager v1.0.41271.0
Copyright (c) Microsoft Corporation. All rights reserved.

Links:
  Privacy Statement: https://aka.ms/winget-privacy
  License agreement: https://aka.ms/winget-license
  3rd Party Notices: https://aka.ms/winget-3rdPartyNotice
  Homepage:          https://aka.ms/winget
```

## Any other software?

Office, VS2019, Windows Terminal, WSL + Ubuntu, git

# Steps to reproduce

1. Open Windows Terminal in PowerShell 7 profile
1. Enter `winget search vscode` - VSCode is found
1. Enter `winget install vscode` 

# Expected behavior

VSCode installs as usual

# Actual behavior

VS unable to install. Displays error `No installers are applicable to the current system`
![image](https://user-images.githubusercontent.com/961950/81738864-3faf4600-944f-11ea-9d91-b7e39f501b41.png)

## Note
⚠ ARM64 devices can install & run most x86 apps & tools if no ARM64 native app is available.

**Comment by Muazislam** [comment]
What do you mean by #132 . I don't get what it means.
