### ISSUE TITLE
--override: how to handle spaces in path?

### ISSUE THREAD

**Issue by MarGeb1** [microsoft/winget-cli#1317]
# Brief description of your issue

I want to install Firefox or another program to a specific path that contains spaces, but it fails.

# Steps to reproduce

When I do a local install from Windows cmd with the Mozilla.Firefox.90.0.msi downloaded by winget, the line

`Mozilla.Firefox.90.0.msi Install_Directory_Path="D:\Mozilla Firefox\" /passive`

works fine but when I call winget with 

`winget install Mozilla.Firefox --override "Install_Directory_Path="D:\Mozilla Firefox\" /passive"`

msiexec shows me the syntax help what means, that the arguments are not correct.

Same result when I surround the path with single or no quotation marks. Also swapping the arguments had no effect.

A [discussion](https://github.com/microsoft/winget-cli/discussions/1296) didn't help.

# Expected behavior

A silent install of Firefox to "D:\Mozilla Firefox".

# Actual behavior

msiexec shows me the syntax help what means, that the arguments are not correct.

# Environment

Windows Package Manager v1.0.11692
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19043.1110
Paket: Microsoft.DesktopAppInstaller v1.12.11692.0

Windows 10 21H1 and 11 - clean install.

Any other software? nope
```

**Comment by yao-msft** [comment]
Hi @MarGeb1

You'll need to escape the quotes inside the --override value.

I just tried the following command and it works as expected:

`winget install Mozilla.Firefox --override "Install_Directory_Path=\"D:\Mozilla Firefox\" /passive"`

Thanks

**Comment by MarGeb1** [comment]
> winget install Mozilla.Firefox --override "Install_Directory_Path=\"D:\Mozilla Firefox\" /passive"

**Comment by MarGeb1** [comment]
Hi yao-msft,

here's my output when I use your line:

![winget](https://user-images.githubusercontent.com/72304411/126738462-faf39e56-cb5c-4666-bf32-22871c5656fd.png)

**Comment by yao-msft** [comment]
Hi @MarGeb1 

Escaping quotes in powershell is a bit different, You can use the following command
`winget install Mozilla.Firefox --override "Install_Directory_Path=\`"D:\Mozilla Firefox\`" /passive"`

Thanks

**Comment by MarGeb1** [comment]
Hi @yao-msft,

> Escaping quotes in powershell is a bit different, You can use the following command
> 
> winget install Mozilla.Firefox --override "Install_Directory_Path=\`"D:\Mozilla Firefox\`" /passive"

that did it, now it works as espected.

Thank you!

**Comment by manelrodero** [comment]
Hi,

Sorry for commenting in a closed issue but I've found another problem that is related to this.

See this tweet: https://twitter.com/manelrodero/status/1550564083732185095.

Using the following line for installing Java JRE:

winget.exe install --id Oracle.JavaRuntimeEnvironment --override "/s INSTALLCFG=`"$Env:TEMP\JavaRE64.cfg`" INSTALLDIR=`"$Env:ProgramFiles\Program Files\Java\jre8`""

makes winget trying to install ''Files\Java\jre8'' application instead of "Oracle.JavaRuntimeEnvironment" and it FAILS :-/

Workaround is using a non-spaces path like this:

INSTALLDIR=`"$Env:SystemDrive\Progra~1\Java\jre8`"

But would be great to have winget expand variables correctly ;-)

**Comment by LeonBouquiet** [comment]
I found that wrapping the entire custom string in _single_ quotes, and then escaping the double quotes with _2 double quotes_ works, i.e.:

`winget install --Id icsharpcode.ILSpy --custom 'TARGETDIR=""C:\Program Files\ILSpy""'`
