### ISSUE TITLE
Honor 429s & RetryAfter when interacting with a Rest based Source

### ISSUE THREAD

**Issue by jamespik** [microsoft/winget-cli#1318]
# Description of the new feature/enhancement
With the introduction of client->Rest based sources, the client may encounter error scenarios different from what it handles when sources are purely local. For example, a rest source may have a maximum throughput limit and deem it necessary to return 429 Too Many Requests.  Ideally, the client would understand how to do backed-off retry for a small window of time before failing and informing the user that the source is currently busy.

# Proposed technical implementation details
Honor 
   HTTP/1.1 429 Too Many Requests
   Content-Type: text/html
   Retry-After: 2
For example.

**Comment by soredake** [comment]
After reinstalling windows i tried to install all my packages with winget, but get 429s from github as many of my apps are hosted there. It would be nice if winget can go to sleep for some time after 429 and retry later.

**Comment by denelon** [comment]
This was implemented with some of the CDN related improvements made.
