### ISSUE TITLE
Multiple Architectures in one manifest

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#132]
# Description of the new feature/enhancement

The client should support manifests with multiple architectures. 

# Proposed technical implementation details (optional)

I should be able to have x86, x64, 32bit, 64bit, and ARM installers available from the same manifest (assuming the version of the package is the same). The client should chose the appropriate installer based on the machine's architecture.

**Comment by soapdog** [comment]
> The client should also be able to determine packages that are not supported with the current architecture and not display them to the user.

In case of Windows on ARM, it would be great if x86 apps were also listed (maybe with some warning label).

**Comment by jedieaston** [comment]
I know this is mostly done now, but one request: can there be a flag for specifying what architecture you want to install in `winget install`? It would be really handy for testing x86 builds of software on x64.

**Comment by denelon** [comment]
> I know this is mostly done now, but one request: can there be a flag for specifying what architecture you want to install in `winget install`? It would be really handy for testing x86 builds of software on x64.

https://github.com/microsoft/winget-cli/issues/906

**Comment by jedieaston** [comment]
Thanks!

**Comment by denelon** [comment]
The 1.0 manifest schema and 0.3-Preview client supports multiple architectures in one manifest.

**Comment by gerardog** [comment]
People googling how to do this. Use WingetCreate, and architecture: neutral
