### ISSUE TITLE
WinGet installation on Windows Server 2019

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-cli#1321]
## Brief description of your issue
WinGet command is not available on Windows Server 2019.

## Steps to reproduce
Run this script.
```
Invoke-WebRequest -Uri "https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx" -Method Get -OutFile "$workingDir\Microsoft.VCLibs.x64.14.00.Desktop.appx" -PassThru 
Add-AppxPackage -Path "$workingDir\Microsoft.VCLibs.x64.14.00.Desktop.appx"
Write-Host "Successfully installed Microsoft.VCLibs.x64.14.00.Desktop.appx"

Invoke-WebRequest -Uri "https://github.com/microsoft/winget-cli/releases/download/v1.0.11692/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle" -Method Get -OutFile "$workingDir\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle" -PassThru 
Add-AppxPackage -Path "$workingDir\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle"
Write-Host "Successfully installed Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle"
```
Now, try entering `winget` in the command line.

## Expected behavior
WinGet command should be available from the command line.

## Actual behavior
WinGet command is not available. Throws error.

## Environment
Windows Server 2019 with only the following things installed:
- Microsoft.VCLibs.x64.14.00.Desktop.appx
- Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
----------------------------------------------------------------------------------
Edit: I got to know that WinGet works on Windows Server 2019. We have to enable developer mode first and then run some commands. (Reference: https://github.com/microsoft/winget-cli/issues/144#issue-618617462)

Is there any way to do all this using the command line? No GUI.

**Comment by al-cheb** [comment]
@vedantmgoyal2009, https://github.com/microsoft/winget-cli/issues/144#issuecomment-849108158

**Comment by vedantmgoyal2009** [comment]
Thanks a lot. This made my work much easier. Thanks again.

**Comment by Karl-WE** [comment]
please follow this discussion to find more information about this topic and a rock solid deployment method
https://github.com/microsoft/winget-cli/discussions/2361
