### ISSUE TITLE
document error codes used by winget

### ISSUE THREAD

**Issue by mi-hol** [microsoft/winget-cli#1325]
I was unable to find a list of error codes used by winget to i.e. indicate a failed download.
Without error codes automation via powershell is prevented for certain use cases (i.e. automatic retry for a failed download)

An example of the required documentation can be found on https://devblogs.microsoft.com/oldnewthing/20180920-00/?p=99785

Example automation is published on  https://adamtheautomator.com/regsvr32-exe/#Handling_Errors_for_regsvr32exe

**Comment by mi-hol** [comment]
related to #674

**Comment by KevinLaMS** [comment]
Great request.  Thanks.

**Comment by mi-hol** [comment]
any news on this topic?

**Comment by mdanish-kh** [comment]
PR https://github.com/microsoft/winget-cli/pull/3202 added a doc listing exit codes returned by WinGet

https://github.com/microsoft/winget-cli/blob/master/doc/windows/package-manager/winget/returnCodes.md

cc @denelon if this needs to be closed
