### ISSUE TITLE
List only Upgradable Packages

### ISSUE THREAD

**Issue by JazzX** [microsoft/winget-cli#1327]
After searching the documentation and the issues i did not find a solution for this. You can only  use `winget list` but this lists all packages and the `-q` or `--query`  attribute has no documentation on how to use it. 

A command option for the list funktion would be a good solution:
`winget list --updates`

**Comment by KevinLaMS** [comment]
Related to #1155 
Great idea JazzX

**Comment by asoluter** [comment]
Doesn't `winget upgrade` without further arguments work in the desired way?

**Comment by JazzX** [comment]
You are right. I did not try this because the console description  (on a German windows at least) only says Upgrades selected Applications.  I think it would good to add this to the description of the upgrade command.

**Comment by denelon** [comment]
@JazzX thanks for pointing this out. I read through the help, and the linked documentation. Neither shows the example for `winget upgrade` with no additional arguments or parameters. This is something we need to update.

**Comment by EArmour** [comment]
Looks like this was addressed with #1580 so I think this can be closed.

**Comment by JazzX** [comment]
Yes, indeed.
