### ISSUE TITLE
'install git' matches multiple apps, messaging unclear

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/winget-cli#133]
# Environment

```none
winget --info
Windows Package Manager v0.1.41301 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.208
Package: Microsoft.DesktopAppInstaller v1.0.41301.0

Links:
  Privacy Statement: https://aka.ms/winget-privacy
  License agreement: https://aka.ms/winget-license
  3rd Party Notices: https://aka.ms/winget-3rdPartyNotice
  Homepage:          https://aka.ms/winget
```

# Steps to reproduce
Attempt to install git with winget:

```
winget install git
```
## Expected behavior

Git installs without further prompting.

## Actual

Git fails to install. Unclear for the user what to do next.

```
Multiple apps found matching input criteria. Please refine the input.
Name                    Id                                Version      Matched
-----------------------------------------------------------------------------------
Git                     Git.Git                           2.26.2       Moniker: git
Atom                    GitHub.Atom                       1.45.0
GitKraken               Axosoft.GitKraken                 6.5.4
Logitech Harmony Remote Logitech.Harmony                  1.0.1.308
GitHub Desktop          GitHub.GitHubDesktop              2.4.3
AppInstallerFileBuilder Microsoft.AppInstallerFileBuilder 1.2020.211.0 Tag: GitHub
```
🏆 For a bonus: Why are "Atom" and "Logitech Harmony Remote" packages returned in the list when installing git?

**Comment by Dormanil** [comment]
Yeah, please make the install search far more precise. I tried installing .NET Core soon after the news dropped. `winget install dotnet` matches both .NET Core and .NET Framework. Searching by ID (`winget install --id microsoft.dotnet`) gave me the same result. Took me two more minutes figuring out the intended way of installing it via the moniker.

**Comment by ocitrev** [comment]
I think it would help if the matched text is highlighted with an alternate color when dealing with ambiguous/multiple results.

**Comment by Dormanil** [comment]
I mean, I am not blind. I see why both are results. I just want the install side of things to expect wholly unambiguous queries, instead of winget forcing the developer to find the one value that disambiguates it and then repeat their query with the right switch flipped. Highlighting would be totally fine when `search`ing for available packages.

**Comment by jonwis** [comment]
```
D:\ndr\src > winget install --id git.git
Multiple apps found matching input criteria. Please refine the input.
Name   Id         Version
-------------------------
Git    Git.Git    2.26.2
GitLFS Git.GitLFS 2.11.0
PS amd64fre D:\ndr\src user/jonwis/build-fix-apt7exp 5/25/2020 1:57 PM
D:\ndr\src > winget install --exact --id git.git
No app found matching input criteria.
PS amd64fre D:\ndr\src user/jonwis/build-fix-apt7exp 5/25/2020 2:01 PM
```

Note the casing requirement and the `--exact`.

**Comment by NicTanghe** [comment]
From using Linux with larger package repositories and community repos. I can say fuzzy search is a required inconvenience.

**Comment by SubhamK108** [comment]
At the moment, when installing apps with multiple search results, the following nomenclature is working perfectly:

`winget install --name <appName> -e`

Note that the <appName> is Case Sensitive !

**Comment by leepryor** [comment]
> ```
> D:\ndr\src > winget install --id git.git
> Multiple apps found matching input criteria. Please refine the input.
> Name   Id         Version
> -------------------------
> Git    Git.Git    2.26.2
> GitLFS Git.GitLFS 2.11.0
> PS amd64fre D:\ndr\src user/jonwis/build-fix-apt7exp 5/25/2020 1:57 PM
> D:\ndr\src > winget install --exact --id git.git
> No app found matching input criteria.
> PS amd64fre D:\ndr\src user/jonwis/build-fix-apt7exp 5/25/2020 2:01 PM
> ```
> 
> Note the casing requirement and the `--exact`.

I had the same issue as well. Found the above fix of using the --name -e worked. It looks like it could be a case sensitive issue.

**Comment by maisonhai3** [comment]
> At the moment, when installing apps with multiple search results, the following nomenclature is working perfectly:
> 
> `winget install --name <appName> -e`
> 
> Note that the _appName_ is Case Sensitive !

It works. And then a graphical installer appears. I just expected as silently installing as Ubuntu did.

**Comment by Borkason** [comment]
I agree. This is too complicated. I don't want to study winget to be able to use winget.

Fuzzy search is great. But when I want to install something, I want simple commands. `winget install` should accept the **exact id by default**. So `winget install git.git` installs that package and `winget install git` should give you an error that a package with that name does not exist, but also do a fuzzy search for git to suggest what you probably meant.

At the very least `winget install --id` should expect an exact match and not ask me whether I want to install git.git or git.gitlfs when I specifically wrote `winget install --id git.git`.
