### ISSUE TITLE
During execution of "winget search", the percentual progression is accompanied by corrupted text.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [microsoft/winget-cli#1331]
# Brief description of your issue
During execution of "winget search 𝑥 | sort", the percentual progression is accompanied by corrupted text.

# Steps to reproduce
Have executed the command that is "winget search 𝑥 | sort"

# Expected behavior
The output should be 1 list of percentages.

# Actual behavior
["ÆΓû" is printed many times, but is accompanied by the  𝑥% of progression that should be there.](https://github.com/microsoft/winget-cli/files/6904122/2021-07-30T23.15.38Z.TXT)

# Environment
```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I am not certain that the environment information is correct, but I am not able to verify its correctness because I am not certain of what all of it means.

**Comment by KevinLaMS** [comment]
@BEEDELLROKEJULIANLOCKHART I just tried the steps with my PC and am not seeing that.
1) your environment in the bug does not provide which version of the OS or Winget client you have.  Can you please provide the numbers?
2) given the odd characters you are providing, I am wondering if this is a console or some codepage issue.  What is the language of the OS you are running?  What window are you running the command in?  The Command prompt or terminal?
3) Can you provide the code page of the window?  in command prompt, right click the UPPER LEFT corner and choose properties.  You can get the code page there.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I was running `winget` via [PowerShell Standard](http://github.com/PowerShell/PowerShell) that was invoked by [53621FSApps.FluentTerminal](http://github.com/felixse/FluentTerminal) within a virtual machine that was being executed by http://github.com/flathub/org.gnome.Boxes from KDE Neon. The machine was running the Windows 11 Preview.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I am not able to provide any more information, as I have done some things to my installation of http://github.com/flathub/org.gnome.Boxes since this report that does mean that the original virtual machine is not accessible. I am apologetic because I may have wasted your time, and thus shall close this issue. However, I can assure that my installation was not corrupted; I had not installed anything but some [Universal Windows Platform](http://github.com/topics/universal-windows-platform) software from the [Microsoft Store](http://microsoft.com/store).
