### ISSUE TITLE
Mark Installed Packages To Not Upgrade

### ISSUE THREAD

**Issue by EzekialSA** [microsoft/winget-cli#1335]
# Mark Installed Packages To Not Upgrade

In a lot of enterprise environments there are controls that exist to force certain versions of things like Microsoft Office. Winget is cool in that it will do a check of installed apps that it didn't install and try to update them, that should definitely stay, but I have the issue where office will fail to install because the enterprise forces updates on a semi annual schedule instead of latest.

# Proposed technical implementation details (optional)

Be able to do a "winget list", find the Microsoft.Office entry or whatever it may be -> winget flag --ignore-upgrade Microsoft.Office

That way it allows winget to work in tandem with enterprise applications such as SCCM or InTune, without competing.

**Comment by jedieaston** [comment]
Probably a dupe of (or at least very related to) #476.

**Comment by denelon** [comment]
Duplicate of #476
