### ISSUE TITLE
Add Purchase URL to schema

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#1345]
# Description of the new feature/enhancement

Some packages require some form of "entitlement" to install a particular package. When a user is interacting with a source, some apps may require purchase or parental consent. The canonical example is the Microsoft Store. If the user is not authenticated or does not posses an entitlement for the App, the user should be provided a Purchase URL so they can acquire the entitlement. In the case of the Microsoft Store this could be a deep link to the store where the user can authenticate, purchase, or request parental consent.

# Proposed technical implementation details (optional)

REST API Issue - https://github.com/microsoft/winget-cli-restsource/issues/54

**Comment by vedantmgoyal2009** [comment]
* @denelon the issue can be closed here while the issue at the https://github.com/microsoft/winget-cli-restsource/issues/54 can left opened, if not yet implemented.
