### ISSUE TITLE
Winget says unknown version for package it just installed

### ISSUE THREAD

**Issue by josh-65** [microsoft/winget-cli#1356]
# Brief description of your issue
When looking at a package upgraded/installed then running the upgrade command it will say unknow version but show the lasted version as available.

![image](https://user-images.githubusercontent.com/26977075/128747722-96bf2cba-24d3-4de5-b186-30cfd1b4f82e.png)

# Steps to reproduce
1) Install a package (Paper cut mobility)
2) Run winget upgrade.
3) See version say unknown with available having a version number.

# Environment
```none
Windows: Windows.Desktop v10.0.19043.1151
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
```

**Comment by ItzLevvie** [comment]
This happens because WinGet relies on the information provided from Control Panel, so in this case, the application developers didn't add a `DisplayVersion` key so WinGet can't find the version number. Please report this to applications' developers to see if this is something they can resolve.

**Comment by ImJoakim** [comment]
The reason for this is because the version from `winget upgrade` or `winget list` relies on the information from the ARP (App or Remove Programs) in the control panel.

The ideal solution is to request the publisher of the software to add a version to the installer.

**Comment by josh-65** [comment]
Alright ill make a request on there end.

**Comment by remidebette** [comment]
Hi everyone,

Can someone provide a more in depth technical explanation to the google teams about what should be done to fix the versionning of their installer?
They do not seem to understand the issue:
https://issuetracker.google.com/issues/258012256

And since their code is not public, the community cannot do it for them like [fbstj](https://github.com/fbstj) and [jedieaston](https://github.com/jedieaston) did for rustup here https://github.com/rust-lang/rustup/pull/3047

**Comment by Masamune3210** [comment]
WinGet will show unknown version when the entry for the app in the registry is either missing or has otherwise issues with it's version entries.

**Comment by Ramshu** [comment]
I had a similar problem with the software “Hard Disk Low Level Format Tool” no matter how many times I updated or reinstalled it, the version number always appeared as unknown.

I solved it by editing the registry: “Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Hard Disk Low Level Format Tool_is1” I added a “string value” with the name “DisplayVersion” and as value I put the version of the program “4.40”

This solution may work for any application.

**Comment by Masamune3210** [comment]
This isnt them not understanding the issue. This is them deciding its not their issue to worry about. Its basically their way of dusting their hands off and walking away from it
> Hi everyone,
> 
> Can someone provide a more in depth technical explanation to the google teams about what should be done to fix the versionning of their gcloud SDK installer? They do not seem to understand the issue: [issuetracker.google.com/issues/258012256](https://issuetracker.google.com/issues/258012256)
> 
> And since their code is not public, the community cannot do it for them like [fbstj](https://github.com/fbstj) and [jedieaston](https://github.com/jedieaston) did for rustup here [rust-lang/rustup#3047](https://github.com/rust-lang/rustup/pull/3047)
