### ISSUE TITLE
Upon update of vim.vim package Windows Defender automatic quick scan detects "Trojan:Script/WacatacB!ml", then quarantines it. Supply chain hack? (I am not a programmer PLEASE HELP!)

### ISSUE THREAD

**Issue by denterwiser** [microsoft/winget-cli#1357]
# Brief description of your issue
Upon update of vim.vim package Windows Defender automatic quick scan detects "Trojan:Script/WacatacB!ml", then quarantines it. Supply chain hack? (I am not a programmer PLEASE HELP!)

**PLEASE REDIRECT ME IF I'M MISUNDERSTANDING INSTRUCTIONS. I will obey you. I am not a programmer and may misunderstand. Please don't flame me.**

# Steps to reproduce
1. Run "winget update" then "winget update vim.vim"
2. Automatic quick scan runs
3. Automatic quick scan quarantines the install.exe file located in "C:\Program Files\Vim\vim82\install.exe"

# Expected behavior
I expected the normal update to occur without the installer being quarantined.

# Actual behavior
Windows Defender is detecting Trojan:Script/WacatacB!ml and quarantining it.

![Trojan](https://user-images.githubusercontent.com/55665952/128774080-bedd1e1b-3d23-484c-b686-0f8d7820ed4e.png)

# Environment
winget --info
Windows Package Manager v1.0.11692
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1151
Package: Microsoft.DesktopAppInstaller v1.12.11692.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Version 21H2 (OS Build 19044.1151)
Edition	Windows 10 Home
Version	21H2
Installed on	‎10/‎29/‎2020
OS build	19044.1151
Experience	Windows Feature Experience Pack 120.2212.3920.0

# Et Cetera
I tried to find the install.exe file to upload to Virus Total, but it isn't in the appropriate folder.

Currently I am 1) running the Microsoft Safety Scanner, then 2) I will run Microsoft Defender Full Scan. One Drive is simultaneously backing up some important files. I will change all of my passwords on a clean computer immediately following this.

**Comment by ImJoakim** [comment]
Seems like the recently added version (8.2.3318) is detected as a threat as described by you. I tested multiple versions, and I can only find this version having this issue. I made a PR to remove this specific version along with reporting it to the Vim team.

**Comment by ItzLevvie** [comment]
cc @denterwiser: 
![image](https://user-images.githubusercontent.com/11600822/129197672-86ba5bcb-39e7-4493-8c56-881adb233792.png)

All packages submitted to the WinGet package repository goes through various scans to make sure it's not a virus or a malicious application.

**Comment by DerfOh** [comment]
Hi Just leaving a comment that this has happened to me using winget in Windows 11 Pro. Windows Defender immediately marked it as a trojan after installing it.

![image](https://github.com/microsoft/winget-cli/assets/6360456/4d657628-5949-4d23-94cf-d290676e6f5d)

![image](https://github.com/microsoft/winget-cli/assets/6360456/c17caec6-db64-4652-abee-0c7d754edf57)

**Comment by Masamune3210** [comment]
!ml in the detection name indicates that it's a machine learning detection. It's a false positive, it happens. Heuristics aren't perfect.

**Comment by DerfOh** [comment]
> !ml in the detection name indicates that it's a machine learning detection. It's a false positive, it happens. Heuristics aren't perfect.

Understood, gave me a scare, guess I'll use something else until windows calms down
