### ISSUE TITLE
ERROR Shovel flavour of scoop is required

### ISSUE THREAD

**Issue by tower-town** [microsoft/winget-cli#1369]
PS C:\Users\hello> scoop install winget
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'winget' (1.0.11692) [64bit]
Loading Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle from cache.
Loading Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64.Appx from cache.
Loading Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x86.Appx from cache.
Loading Microsoft.VCLibs.140.00_14.0.30035.0_x64.Appx from cache.
Loading Microsoft.VCLibs.140.00_14.0.30035.0_x86.Appx from cache.
Checking hash of Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle ... ok.
Checking hash of Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64.Appx ... ok.
Checking hash of Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x86.Appx ... ok.
Checking hash of Microsoft.VCLibs.140.00_14.0.30035.0_x64.Appx ... ok.
Checking hash of Microsoft.VCLibs.140.00_14.0.30035.0_x86.Appx ... ok.
Extracting cosi.7z ... done.
Running pre-install script...
Running installer script...
ERROR Shovel flavour of scoop is required

**Comment by ItzLevvie** [comment]
This doesn't seem to be an issue for Windows Package Manager but you'll need to use https://github.com/Ash258/Scoop-Core to install it.
