### ISSUE TITLE
Support non-zero exit codes as success

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#137]
# Description of the new feature/enhancement

Some applications return non-zero codes that are not errors. There should be a way for the client to know the difference between these codes and actual errors.

# Proposed technical implementation details (optional)

A key could be added to the manifest syntax to indicate which non-zero codes should be treated as success. The client could then treat these non-zero return codes as success.

**Comment by chausner** [comment]
This is the case with installers wrapped in a WinRAR self-extracting archive, for example (e.g. https://github.com/microsoft/winget-pkgs/pull/535). RARSFX will return exit code 1000 if the installation succeeded, and any other code indicates an error.

**Comment by superusercode** [comment]
This also impacts adobe digital editions, and there are plenty more documented in installers listed on chocolatey/scoop https://chocolatey.org/packages/adobedigitaleditions#files.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-pkgs/pull/132

**Comment by denelon** [comment]
fixes microsoft/winget-pkgs#132

**Comment by denelon** [comment]
This feature is complete with the v1.0 schema and the v0.3 client release.
