### ISSUE TITLE
​

### ISSUE THREAD

**Issue by ItzLevvie** [microsoft/winget-cli#1371]
​

**Comment by denelon** [comment]
@ItzLevvie, I'm digging through some of the older issues now that WinGet 1.4 is out. I'm not sure if this is actually a bug in WinGet or something else. I'd like to get it routed to the correct team. I ran across something very [similar](https://stackoverflow.com/questions/59110563/different-behaviour-and-output-when-piping-in-cmd-and-powershell) which leads me to believe that piping the output is causing the trouble here. It might even be related to this [Issue at PowerShell](https://github.com/PowerShell/PowerShell/issues/1908).

We've been doing work on native PowerShell and had to structure the objects a bit differently to get sorting behavior to work as expected.
