### ISSUE TITLE
No update available (iTunes)

### ISSUE THREAD

**Issue by Zazou89** [microsoft/winget-cli#1372]
# Brief description of your issue
Hello,
An iTunes update is available but when I want to upgrade, it's not available

# Steps to reproduce

- `winget upgrade iTunes`

# Expected behavior

iTunes update

# Actual behavior

![image](https://user-images.githubusercontent.com/206181/129492374-d68517c2-e1e9-4289-8f5b-fabe3feee09b.png)

# Environment

```none
Windows Package Manager v1.0.11694
Copyright (c) Microsoft Corporation. Tous droits réservés.

Windows: Windows.Desktop v10.0.22000.132
Package: Microsoft.DesktopAppInstaller v1.15.11694.0
```

**Comment by quhxl** [comment]
This might be related to [this](https://github.com/microsoft/winget-cli/issues/1191#issuecomment-870667044)...

**Comment by KevinLaMS** [comment]
I agree it is the same issue.  Please feel free to bump up the rating of the open issue and possibly close this one as a duplicate.  #752

**Comment by Zazou89** [comment]
Sure ! You can close this one :)

**Comment by quhxl** [comment]
You can just close it yourself.
