### ISSUE TITLE
Possibility to flag a package as broken or out-of-date 

### ISSUE THREAD

**Issue by rhemberger** [microsoft/winget-cli#1380]
# Description of the new feature/enhancement
Please implement a way to flag a package as broken or outdated. 
As e.g. in AUR: https://aur.archlinux.org/ or Chocolatey

Prevents useless download and installation attempts.
# Proposed technical implementation details (optional)

Let WinGet ignore these packages.

**Comment by denelon** [comment]
Duplicate of #920
