### ISSUE TITLE
Client verbose logging does not log sufficient information to diagnose issues interacting with rest sources.

### ISSUE THREAD

**Issue by jamespik** [microsoft/winget-cli#1400]
In addition to logging that the client is sending GET and POST requests to specific endpoints and the http response code received back, we should log the full request response when verbose logging is enabled.  This will allow us to diagnose issues purely from logging and not require live repros of any issue.

**Comment by jedieaston** [comment]
I've been having a bunch of issues trying to figure out what command hits what endpoint on the current release of winget. Better logging would help a ton.

**Comment by denelon** [comment]
FYI "--verbose-logs" is the flag to turn verbose logs on per command. We're aiming to get another build out soon[tm].
