### ISSUE TITLE
possibility to add parameters for installation of package

### ISSUE THREAD

**Issue by herrxyz** [microsoft/winget-cli#1403]
# Description of the new feature/enhancement

Hey there, I would like to add parameters to the installation of a package, for example like `"sql-server-express  /SECURITYMODE=SQL /SAPWD=localadministrator"` ~~(I know that it's possible to change password afterwards)~~

some (a lot?) installation programms features installation using commandline with parameters for settings like folderpath, setting password, changing language etc
this request is inspired by chocolatey, in example `choco install sql-server-express -ia "/SECURITYMODE=SQL /SAPWD=localadministrator" -y`

**Comment by vedantmgoyal2009** [comment]
@denelon Needs author feedback or closed?

**Comment by denelon** [comment]
@vedantmgoyal2009 I think this is the "add switches" rather than "--override". I've been thinking about something like "--augment" to make the switches in addition to those in the manifest. That way users would still get silent and maybe scope in addition to what they add rather than having to use "--override" and know all the switches.

**Comment by vedantmgoyal2009** [comment]
Do you mean what git does?

`git <command> <more-cmd> -- <additional-blah-blah>`

**Comment by denelon** [comment]
Imagine you were using winget to install Visual Studio and you wanted to add some workloads.

You wouldn't necessarily want to have to look up the arguments for silent and scope, but you just wanted to add additional arguments for the installer.

winget would call the installer and have the switches for silent and scope, or during the "upgrade" flow the upgrade argument. You could then just pass the workloads with the "--augment" (or whatever we call it).

**Comment by ppvnf** [comment]
I think this is an important feature for Winget to have. In the issue https://github.com/microsoft/winget-cli/issues/2553 I compared how Chocolatey and Winget work:

> I think it's easier to explain what I mean by giving an example (VirtualBox). In Chocolatey if I want to install VirtualBox without adding a desktop icon, but enabling the extension pack, I would use `choco install virtualbox --params "/NoDesktopShortcut /ExtensionPack"`. It's also possible to use `choco info virtualbox` to find out about the parameters of certain package. I am not very experienced with Winget, so I would like to know if it has a similar feature (if it doesn't I would like to know the reason and suggest it to be implemented). I tried `winget show virtualbox` but couldn't find any package parameter. In the [docs ](https://learn.microsoft.com/en-us/windows/package-manager/winget/install) the only similar package parameters I saw were `--locale`, `-l` and `-a`. Thank you in advance.

**Comment by Trenly** [comment]
@denelon - See above linked PR

**Comment by denelon** [comment]
@Trenly
Can you share an example with the new argument?
After that, I'll close the Issue :)

**Comment by Trenly** [comment]
@denelon - By default the Firefox (Mozilla.Firefox) installer adds a desktop shortcut, a taskbar shortcut, and a start menu shortcut. Before this change, for a silent install with no taskbar shortcut, users would have to run `winget install Mozilla.Firefox --override '/S /TaskbarShortcut=false'` (note the /S is required as the silent install switch from the manifest).

With this change, users can now use `winget install Mozilla.Firefox --custom /TaskbarShortcut=false` and no longer need to manually add the silent switch from the manifest.

-----

Before this change `winget install Mozilla.Firefox -s --override /TaskbarShortcut=false` would not result in a silent install. With this change, `winget install Mozilla.Firefox -s --custom /TaskbarShortcut=false` will result in a silent install

**Comment by akash07k** [comment]
Hey @Trenly ,
With this `--custom` flag, how can we identify the supported parameters by a certain package/installer?
