### ISSUE TITLE
InstallerSuccessCodes in manifest schema does not provide any numerical limits

### ISSUE THREAD

**Issue by JohnMcPMS** [microsoft/winget-cli#1406]
This (and possibly other) field in the schema is meant to represent a number that has some numerical limit.  The schema should represent those limits.

For this specific case, the number is compared against 32 bit values returned by OS APIs.  The limit should be either the signed, unsigned, or both 32 bit spaces.  Both would only be provided as an option to make things easier for authoring, but we would store and use it only one way internally.

**Comment by sredna** [comment]
A process exiting with a HRESULT is not that common but can happen so the MSB might be set and the full 32-bits should be allowed. On the other hand, dealing with negative ERRORLEVELs in batch files is annoying so limiting to positive 31-bit numbers should be encouraged.

**Comment by denelon** [comment]
We will need to be able to map negative numbers as well due to some legacy installers. I believe I've seen -214xxxxxxx from a couple of packages.

**Comment by yao-msft** [comment]
Fixed as part of #1427
