### ISSUE TITLE
Winget install of Microsoft.PowerBI unistalls 64 bit version and installs 32 bit version

### ISSUE THREAD

**Issue by pontush-sweden** [microsoft/winget-cli#1418]
# Brief description of your issue
When running winget to upgrade Power BI Desktop x64 it unistalls x64 but then installs x86. Should match OS architecture?

# Steps to reproduce
run: winget install powerbi

# Expected behavior
Install x64 version if Windows is x64

# Actual behavior
Installing x86 version

# Environment

```none
[winget --info]
Windows Package Manager version v0.2.10771
Windows: Windows.Desktop version v10.0.19043.1165
Package: Microsoft.DesktopAppInstaller version v1.11.10771.0

Any other software?
```

**Comment by ImJoakim** [comment]
Seems like the bot removed the x64 installer when automatically updating in https://github.com/microsoft/winget-pkgs/pull/25757. I'll make a PR to add that back.
