### ISSUE TITLE
Winget tells me that Windows Terminal needs an update, but the Windows Store says no update is available

### ISSUE THREAD

**Issue by trparky** [microsoft/winget-cli#1425]
# Brief description of your issue
Winget tells me that Windows Terminal needs an update, but the Windows Store says no update is available.
# Steps to reproduce

1. Install Windows Terminal from the Windows Store (not the preview version).
2. Execute "winget upgrade"
3. Winget tells you that there's an update for package ID Microsoft.WindowsTerminal and that version 1.10.2383.0 is available but that's only the preview version, not the stable version.

# Expected behavior
How about no indication of an update for this package?

# Actual behavior
It's telling me that there's an update when there is no update available.

# Environment
PS C:\Users\trpar> winget --info
Windows Package Manager v1.0.11692
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1165
Package: Microsoft.DesktopAppInstaller v1.12.11692.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget

**Comment by ImJoakim** [comment]
`Windows Terminal` and `Windows Terminal Preview` both have the `1.10.2383.0` version available.

![image](https://user-images.githubusercontent.com/52826317/131794121-f3d030b6-b069-44a6-933e-f2852646cf3d.png)

**Comment by trparky** [comment]
Not according to the Windows Store where I installed it from.

**Comment by trparky** [comment]
OK, this is weird. I tried doing that a day ago, namely the "winget upgrade Microsoft.WindowsTerminal" which caused the Terminal app to close but then upon re-opening Terminal and executing "winget upgrade" it told me that it was still the old version. I assumed that since it was installed via the Windows Store it had to be updated via the Windows Store hence me trying to force a manual update via winget would not work. However, this time, it did work.

**Comment by trparky** [comment]
https://aka.ms/AAdpcqw

**Comment by Karl-WE** [comment]
The current version is Version: 1.10.2383.0
I would reset then uninstall the app via settings > app and reinstall it.

**Comment by Karl-WE** [comment]
@denelon I haven't had any issues in this regards anymore. It appears to be fixed.
Can you repro @denelon ?

**Comment by denelon** [comment]
I'm fairly confident the issue is resolved for Windows 11, but I'm not sure if it's resolved for Windows 10. WinGet doesn't check for the minimum OS when evaluating the latest available version.

**Comment by Karl-WE** [comment]
So repro steps are
Windows 10 22H2
Install older Release or Microsoft Terminal
Install winget 1.4
Launch Terminal
Call winget to upgrade Terminal resp. Upgrade --all

Is that correct?

**Comment by denelon** [comment]
Yes, that's the correct sequence of events.

There were two MSIX packages (one requiring Win10 and the other requiring Win11). At one point in time, the Win11 package was the "latest" version so when users on Win 10 attempted to upgrade, they got an error because Win11 was required.

If the order were flipped, I believe the Win10 package would have installed on Win11, but likely would have been missing some functionality available in the Win11 version.

I haven't checked recently about the status of their releases, and I know WinGet still does not check the minimum OS version to detect the latest available compatible version of a package.

**Comment by denelon** [comment]
It's been quite a while since this issue was reported. Is this still happening?

**Comment by Karl-WE** [comment]
For me it's gone
