### ISSUE TITLE
winget missing from windows 11 (10.0.22000.65)

### ISSUE THREAD

**Issue by BladeFireLight** [microsoft/winget-cli#1426]
multiple sorces and a few people in the insiders at work show off winget on windows 11. 

I just installed the current dev and it's not present. will winget make it into the final of win11?

**Comment by jedieaston** [comment]
Try opening the Microsoft Store and checking for updates. Also, the current build number is 10.0.22000.168, so you probably need to run Windows Update.

**Comment by BladeFireLight** [comment]
I am in the beta channel.. no updates showing for windows. 

store updates all done and no winget

**Comment by jedieaston** [comment]
Ah, the beta channel. I wonder if you have to be in dev to get winget?

**Comment by BladeFireLight** [comment]
I do not believe so. my co workers around me all got it. and I did not.

**Comment by jedieaston** [comment]
Can you look in your App Execution Aliases and see if it appears there? 

These instructions should work: https://www.windowscentral.com/how-manage-app-execution-aliases-windows-10

Also, what edition of Windows are you on? Shouldn't matter, but just to be sure...

**Comment by BladeFireLight** [comment]
I do not see it in the aliases list. 

edition says Windows 11 Enterprise

**Comment by denelon** [comment]
The "App Installer" from the store should include the Windows Package Manager on all versions of Windows 11. It didn't make it into the initial Windows 11 install, but an update should be available for all Windows Insider builds.

**Comment by BladeFireLight** [comment]
![image](https://user-images.githubusercontent.com/8352828/131927995-e1649925-e13f-415b-8041-6cfa1b4280f5.png)
I have installed all updates and so see an app installer winstore app and now the aliases have app insaller pointing to python and python3

still no winget from the command line
![image](https://user-images.githubusercontent.com/8352828/131928176-c1855046-e311-41fd-9ef2-138f3f49f741.png)

**Comment by jedieaston** [comment]
Do you have any pending updates in the Microsoft Store?

**Comment by BladeFireLight** [comment]
nope

**Comment by denelon** [comment]
Are you logged on with a user account that has admin rights on the machine?

 Is it the same user account that installed the Windows Package Manager?

**Comment by BladeFireLight** [comment]
Yes and yes

**Comment by denelon** [comment]
Thanks, I've contacted a couple of other internal teams to see what other steps we can take to troubleshoot what might be happening. I'd like to isolate whether the problem is related to the Windows Package Manager, MSIX installation, or something else. I haven't been able to reproduce this in any of my environments yet.

**Comment by BladeFireLight** [comment]
could it be something as simple as a missing Path entry?

**Comment by jedieaston** [comment]
It could be. 

Can you see if there is a winget.exe file in `%LOCALAPPDATA\Microsoft\WindowsApps`?

**Comment by BladeFireLight** [comment]
file not found.

**Comment by erayrafet** [comment]
I have the exact same issue with the latest Win 11 beta.

![image](https://user-images.githubusercontent.com/34194191/132846749-8bac6b8c-db22-451e-bf22-88672754a937.png)
![image](https://user-images.githubusercontent.com/34194191/132846761-f707df58-7302-4ecf-b217-deca48cfddf4.png)

**Comment by jedieaston** [comment]
@erayrafet Can you post the output of $env:PATH from PowerShell?

**Comment by erayrafet** [comment]
Here: 
![image](https://user-images.githubusercontent.com/34194191/132871183-b7961b9b-dab1-459a-aa58-6742f2c7afd3.png)

> @erayrafet Can you post the output of $env:PATH from PowerShell?

**Comment by denelon** [comment]
I see what appears to be a missing semicolon after "\WindowsApps" before the "C:Users\erayr\NexusTools".

**Comment by jedieaston** [comment]
That's odd. 

@erayrafet, can you search in the start menu for "Edit environment variables for your account", then in the panel that opens, click edit and send a screenshot of it? I'm wondering if those strings are actually stuck together or there's something funny going on with PowerShell. I don't know how that could've happened though.

**Comment by erayrafet** [comment]
> That's odd.
> 
> @erayrafet, can you search in the start menu for "Edit environment variables for your account", then in the panel that opens, highlight the "Path" entry, click edit and send a screenshot of it? I'm wondering if those strings are actually stuck together or there's something funny going on with PowerShell. I don't know how that could've happened though.
> 
> Here's mine for reference:
> <img alt="image" width="394" src="https://user-images.githubusercontent.com/21368066/132882853-fe4c7308-6353-4262-8a33-b0945c464ad6.png">

![image](https://user-images.githubusercontent.com/34194191/132892663-a14795d7-5b72-44fb-8fb9-ccd4884ef6e6.png)

**Comment by erayrafet** [comment]
By edditing the env paths, I was able to fix the problem. Kudos to you, @jedieaston!
![image](https://user-images.githubusercontent.com/34194191/132893355-1cfc1dd9-cd20-4b9c-8739-5f0c4c4f0012.png)
![image](https://user-images.githubusercontent.com/34194191/132893400-7506afd7-c619-4ff6-a86d-c5fbaf683ad8.png)

**Comment by BladeFireLight** [comment]
lucky you. 
my path is good 
![image](https://user-images.githubusercontent.com/8352828/132919212-9667fc46-14c4-48db-97f7-f003dd176ef7.png)
but the files are missing
![image](https://user-images.githubusercontent.com/8352828/132919255-273a697b-bdde-45d3-bd4a-d2ab646ba052.png)
![image](https://user-images.githubusercontent.com/8352828/132919319-573a012f-0298-489b-9135-053094009f3d.png)

**Comment by jedieaston** [comment]
Okay, so I just confirmed it is not a fluke. Fresh install of Windows 11 Insider Preview (22454): 
<img width="664" alt="image" src="https://user-images.githubusercontent.com/21368066/132963448-bdc707bc-0998-41d9-8b89-a4e1a49db5a6.png">

Interestingly, it also has the old Microsoft Store installed.

**Comment by erayrafet** [comment]
> Okay, so I just confirmed it is not a fluke. Fresh install of Windows 11 Insider Preview (22454):
> <img alt="image" width="664" src="https://user-images.githubusercontent.com/21368066/132963448-bdc707bc-0998-41d9-8b89-a4e1a49db5a6.png">
> 
> Interestingly, it also has the old Microsoft Store installed.
> 
> Edit: The Microsoft Store picked up like 20 updates after a few minutes and winget is now installed after an App Installer update. Is it not going to be in the RTM ISO (I know that it hasn't been released yet but if we're going to have to run the Microsoft Store before winget works on clean installs of Windows 11 that'll be super lame).

Indeed. I had done a clean install too.

**Comment by nascentt** [comment]
Not sure if the same issue or not, but winget report 2 entries and therefore fails to upgrade.

```
Python 3                              Python.Python.3                 3.9.5150.0  3.9.7150.0  winget
winget upgrade python.python.3
Multiple installed packages found matching input criteria. Please refine the input.
Name                  Id
------------------------------------------------------------
Python 3              Python.Python.3
Python 3.9.5 (32-bit) {708847ae-c2de-49fb-9b85-8d2e9c991358}
```

**Comment by jedieaston** [comment]
@nascentt you're looking for https://github.com/microsoft/winget-cli/issues/752 I think.

**Comment by denelon** [comment]
Sadly, we did not make the cut off date to be part of the ISO for the initial release of Windows 11. We are working through the process to be included in a future update. There are a couple of different approaches we're looking at to make sure we (the App Installer with the Windows Package Manager) are installed as quickly as possible.

**Comment by BladeFireLight** [comment]
so that would be the a reason for why it's not installed for me? 

If we want winget installed before you get it into a rollup. we have to do the manual install I take it?

**Comment by jedieaston** [comment]
Are you still not seeing an update for the App Installer in the Microsoft Store? If not, can you see what version of it you have installed?

**Comment by BladeFireLight** [comment]
nope

so I manually downloaded and install the msix package

**Comment by aminya** [comment]
Related to 
https://github.com/PowerShell/PowerShell/issues/13138
https://github.com/microsoft/winget-cli/issues/995

**Comment by denelon** [comment]
@BladeFireLight,

We've published the v1.1 [release candidate](https://github.com/microsoft/winget-cli/releases/tag/v1.1.12653) and updated our [troubleshooting guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting).

Can you confirm if this is still happening?

**Comment by aminya** [comment]
Still no winget. 


In [this comment](https://github.com/microsoft/winget-cli/issues/221#issuecomment-632985508), it was mentioned that 

> One of the initial goals is to make sure the Windows Package Manager works on earlier versions of Windows without a PowerShell dependency. That is one of the primary reasons this is a .exe and written in C++.


 If this is a C++ executable, why is it so hard to install and put it on the path?

**Comment by jedieaston** [comment]
That's weird. It's good that you got it working though!

**Comment by denelon** [comment]
@aminya I'm glad you got it working as well. We've had a few cases where other programs modified the path entry, but nothing solid enough to completely isolate it so we can make the fix.

**Comment by franklesniak** [comment]
Is there a way to synchronously install App Installer? If not, there needs to be!

With winget not being available immediately out of the box in Windows 11, I don't see sysadmins adopting it because they won't be able to use it during OS deployment, autopilot, etc.

In the absence of winget being included in the ISO for Windows 11, we need a process like:
1. Install OS
2. Run some command(s) to install App Installer. The command is synchronous (it waits until App Installer is installed and returns an error code if it fails to install)
3. Assume it's safe to call winget

More discussion: https://twitter.com/FrankLesniak/status/1448294637941280774?s=20

**Comment by franklesniak** [comment]
Keeping the party going by mentioning that I posted to Feedback Hub: https://aka.ms/AAe2dpu

**Comment by denelon** [comment]
The Windows Package Manager should be in an automatic update delivered by the Microsoft Store on Windows 11. It was not included in the base image for the initial release. If Group Policy or other settings are blocking the Microsoft Store, this could affect a user's ability to use the Microsoft Store UI to request the update.

**Comment by jedieaston** [comment]
@franklesniak the best solution might be for you to write some PowerShell to pull the latest release from GitHub, install it, and then run whatever commands you want with winget. It'll still catch updates from the Microsoft Store, but since there's no way to tell the Microsoft Store to run updates and get a response when they are done, it's probably the best solution for now.

**Comment by franklesniak** [comment]
Indeed - thank you both. After I posted last night, I saw another post that said the Windows Store would detect and update App Installer even if someone installed App Installer via Github (https://twitter.com/FrankLesniak/status/1455747254027948032?s=20). I haven't tried this myself, but it sounds like a good path forward.

**Comment by GethDeeo** [comment]
@jedieaston sorry to hijack this issue, but I'm doing something similar and I have questions: https://github.com/microsoft/winget-cli/discussions/1691  
Provisioning ran just fine, but on first boot the snippet  
```
Write-Host (Get-Date)
while (!(Get-Command -Name winget -ErrorAction SilentlyContinue)) {
  Start-Sleep 5
}
Write-Host (Get-Date)
```
produces the second timestamp ~15 minutes later (and there is really no `winget.exe` in `%LOCALAPPDATA%\Microsoft\WindowsApps` during that time). After that, winget is fully functional in the same ps session.  
What is happening in that 15 minutes? Can it be sped up?

**Comment by denelon** [comment]
@GethDeeo this isn't likely to change before the next servicing release for Windows 11. We have work scheduled to be included in the base image for the next release.
