### ISSUE TITLE
winget: The term 'winget' is not recognized as a name of a cmdlet

### ISSUE THREAD

**Issue by insinfo** [microsoft/winget-cli#1428]
winget: The term 'winget' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

https://github.com/microsoft/winget-cli/releases/download/v1.0.11692/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle

![image](https://user-images.githubusercontent.com/12227024/131908052-86367613-c855-4ea8-b535-61fc8c23bcfa.png)

![image](https://user-images.githubusercontent.com/12227024/131907999-5d34805b-9a72-42ec-a63e-89c8f940b4b1.png)

```powershell
PS C:\WINDOWS\system32> Get-AppxPackage microsoft.DesktopAppInstaller


Name              : Microsoft.DesktopAppInstaller
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 1.12.11692.0
PackageFullName   : Microsoft.DesktopAppInstaller_1.12.11692.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.12.11692.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe,
                    Microsoft.DesktopAppInstaller_1.12.11692.0_neutral_split.scale-100_8wekyb3d8bbwe,
                    Microsoft.DesktopAppInstaller_1.12.11692.0_neutral_split.language-pt_8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok



PS C:\WINDOWS\system32> winget
winget : O termo 'winget' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável.
Verifique a grafia do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto e tente novamente.
No linha:1 caractere:1
+ winget
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (winget:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32> AppInstallerCLI.exe
AppInstallerCLI.exe : O termo 'AppInstallerCLI.exe' não é reconhecido como nome de cmdlet, função, arquivo de script
ou programa operável. Verifique a grafia do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto
e tente novamente.
No linha:1 caractere:1
+ AppInstallerCLI.exe
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AppInstallerCLI.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32>
```

**Comment by jedieaston** [comment]
Does it appear in your App execution aliases? 

These instructions should work: https://www.windowscentral.com/how-manage-app-execution-aliases-windows-10

**Comment by insinfo** [comment]
> Does it appear in your App execution aliases?

![image](https://user-images.githubusercontent.com/12227024/132550478-d40ca746-04f2-4f84-b17e-048d8f9e9942.png)

**Comment by denelon** [comment]
@insinfo

We've published the v1.1 [release candidate](https://github.com/microsoft/winget-cli/releases/tag/v1.1.12653) and updated our [troubleshooting guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting).

Can you confirm if this is still happening?

**Comment by insinfo** [comment]
![image](https://user-images.githubusercontent.com/12227024/135695480-300eb777-b2c5-4601-a718-b3b43372c8d5.png)
it's working now

**Comment by insinfo** [comment]
I upgraded my machine with an SSD and upgraded windows to version 21H1 today so I don't know if the upgrade resolved the issue or was it something else

**Comment by denelon** [comment]
@insinfo thanks for confirming!

**Comment by pimentelleo** [comment]
I am with this issue, but i really need to do something to fix as changing entirely OS isn't an option
