### ISSUE TITLE
Winget command missing from server 2019

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/winget-cli#144]
Winget command missing from server 2019 

# Environment

```none
[winget --info]
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.server 17763.1
Package: Microsoft.DesktopAppInstaller v1.0.41331.0


Any other software?
```

# Steps to reproduce
1.	Install the latest Windows Package Manager
2.	I cannot find the Windows Package Manager though I have it installed.

# Expected behavior

Winget should be available from the command line.
# Actual behavior

Winget is not available from the command line.
The only way to get it to work, 
1) enable developer mode in settings
2)  execute the following powershell command
Get-AppxPackage Microsoft.DesktopAppInstaller | %{ Invoke-CommandInDesktopPackage -PackageFamilyName $_.PackageFamilyName -AppId winget -Command C:\Windows\System32\cmd.exe -PreventBreakaway }
3) navigate to the app package and run AppInstallerCli.exe

**Comment by huangsijun17** [comment]
`PS C:\Users\huang\Desktop> Add-AppPackage .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle
Add-AppPackage : 部署失败，原因是 HRESULT: 0x80073CF3, 包无法进行更新、相关性或冲突验证。
Windows 无法安装程序包 Microsoft.DesktopAppInstaller_1.10.42101.0_x64__8wekyb3d8bbwe，因为此程序包依赖于一个找不到的框
架。请随要安装的此程序包一起提供由“CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US”
发布的框架“Microsoft.VCLibs.140.00.UWPDesktop”(具有中性或 x64 处理器体系结构，最低版本为 14.0.25426.0)。当前已安装的
名称为“Microsoft.VCLibs.140.00.UWPDesktop”的框架为: {}
注意: 有关其他信息，请在事件日志中查找 [ActivityId] c57f47ef-7ae0-0002-8953-7fc5e07ad601，或使用命令行 Get-AppPackageLo
g -ActivityID c57f47ef-7ae0-0002-8953-7fc5e07ad601
所在位置 行:1 字符: 1
+ Add-AppPackage .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbund ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\huang\...bbwe.appxbundle:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand`


run ` Add-AppPackage .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle` in powershell on windows server 2019

**Comment by santagada** [comment]
I can't get it to install at all in windows server 2019, running the package gives me the error:

PS C:\Downloads> Add-AppxPackage .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict
validation.
Windows cannot install package Microsoft.DesktopAppInstaller_1.10.42241.0_x64__8wekyb3d8bbwe because this package
depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published
by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor
architecture and minimum version 14.0.25426.0, along with this package to install. The frameworks with name
"Microsoft.VCLibs.140.00.UWPDesktop" currently installed
Windows cannot install package Microsoft.DesktopAppInstaller_1.10.42241.0_x64__8wekyb3d8bbwe because this package
depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published
by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor
architecture and minimum version 14.0.25426.0, along with this package to install. The frameworks with name
"Microsoft.VCLibs.140.00.UWPDesktop" currently installed are: {}
NOTE: For additional information, look for [ActivityId] 4f8c593d-86eb-0000-a679-8c4feb86d601 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 4f8c593d-86eb-0000-a679-8c4feb86d601
At line:1 char:1
+ Add-AppxPackage .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbun ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\builde...bbwe.appxbundle:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by kuzi-moto** [comment]
Use this method to install the missing dependencies:

https://github.com/microsoft/terminal/issues/3097#issuecomment-615373769

**Comment by santagada** [comment]
Thanks for the comment, but I would prefer to not go to a shady website on a windows server instance to get links to download tools... feels like microsoft should support their own operating system.

**Comment by kuzi-moto** [comment]
I agree, but for what it's worth I believe you are actually still downloading the packages from Microsoft. I think that the site is just providing the direct link which is hosted by Microsoft.

You could still visit it on another machine/VM/etc. to get the link if you're interested enough.

**Comment by denelon** [comment]
Windows Server 2019 does not support execution aliases.

**Comment by al-cheb** [comment]
How to create winget alias - https://github.com/al-cheb/winget_install_script/blob/main/Install-WinGet.ps1
```PS > Get-CimInstance Win32_OperatingSystem | Select-Object Caption,Version

Caption                                  Version
-------                                  -------
Microsoft Windows Server 2019 Datacenter 10.0.17763


PS > C:\Windows\System32\winget.exe --info
Windows Package Manager v1.0.11451
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Server v10.0.17763.1935
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget

PS > C:\Windows\System32\winget.exe show
Multiple packages found matching input criteria. Please refine the input.
Name                           Id                                Source
-----------------------------------------------------------------------
Robo3T                         3T.Robo3T                         winget
Robo3T - Beta                  3T.Robo3TBeta                     winget
ndm                            720kb.ndm                         winget
Aya                            7room.Aya                         winget
7-Zip                          7zip.7zip                         winget
7-Zip - Alpha                  7zip.7zipAlpha                    winget
8x8 Work                       8x8.VirtualOfficeDesktop          winget```

**Comment by Karl-WE** [comment]
See also
https://www.andreasnick.com/112-install-winget-and-appinstaller-on-windows-server-2022.html

**Comment by denelon** [comment]
We aren't targeting Windows Server 2019 as a supported SKU for the Windows Package Manager. There are several challenges with dependencies like the Store for updates, App Execution Aliases. You may be able to overcome the hurdles and get the Windows Package Manager installed, but it is not supported in this environment.

**Comment by Karl-WE** [comment]
@denelon thanks for the follow up. Are there better chances for Server 2022? Will Windows Server support be removed from the milestone altogether?

**Comment by denelon** [comment]
We're still looking at all the dependencies on Windows Server 2022. It looks a bit more straight forward, but still doesn't have the Microsoft Store as a default package. That would potentially inhibit automatic updates to the Windows Package Manager. Unfortunately, it will likely not be a "supported" SKU, but we're considering it as "experimental" if we can make sure all of the appropriate teams and dependencies are all aligned for Windows Server 2022.

**Comment by denelon** [comment]
One of the options we're looking at is being able to include the Windows Package Manager in the Microsoft Store "msstore" source for updates. One of the challenges is related to enterprises disabling the Microsoft Store source by policy. That would effectively nullify our ability to get updates. Several chicken and egg problems to resolve here.

**Comment by Karl-WE** [comment]
Hi @denelon I fully agree with your challenges and concern.

As you can mostly only speak for your product, I would propose to make a check for this policy (it is in registry policies) and if set throw an error message when trying to download.

In my professional role I always try to convince enterprises to block the app access to private MS Store via GPO but not blocking the communication as preinstalled apps would not update, neither modern drivers would work correctly as DCH driver have thankfully separated their tools into the store. I am curious how this will work with Windows 11 when the business store is gone. 

In addition to this it would also compromise the ability to use the business store (as long it will remain) for enterprise deployments. 

Doubt that **enterprises that fully block** the store would use Winget.

These enterprises from SMB to SMC mostly use 

1. DNS blocks in perimeter firewalling 
2. Redirections via AD DNS, some even setup their AD DNS to never ask root servers means they really care to assign their DNS requests in the AD DNS manually 
3. They use lmhost of Windows to prevent the resolution
4. They use one or more GPOs, as outlined.

I hope this helps you to consider the options I see regularly in the wild.

**Comment by soroshsabz** [comment]
I think winget for windows server core is very needed and critical

**Comment by AlexDev404** [comment]
https://stackoverflow.com/a/75794127/10976415
