### ISSUE TITLE
If I disable experimental store, "newstore" remains.

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#1446]
# Brief description of your issue

@adrianghc [asked](https://github.com/microsoft/winget-cli/issues/1437#issuecomment-915662960):

Why does newstore not get removed automatically when disabling the feature?

# Steps to reproduce

Disable the experimental store and the source named "newstore" doesn't get removed.

# Expected behavior

The source named "newstore" should get removed.

# Actual behavior

It's described in the steps.

**Comment by adrianghc** [comment]
```
Windows Package Manager v1.0.11694
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22000.176
Paket: Microsoft.DesktopAppInstaller v1.15.11694.0
```

**Comment by Jaifroid** [comment]
See also https://github.com/microsoft/winget-cli/issues/1437#issuecomment-915669229 - same bug exists in default winget on Windows 11 Beta.

![image](https://user-images.githubusercontent.com/4304337/132604131-5757e858-6e5d-4a9a-a424-a106299dde2b.png)

**Comment by denelon** [comment]
Any sources not in use may be removed with `winget source remove <source>`.

We have made the store a stable feature in the latest release. This experimental setting is no longer needed.

You may also use `winget source reset` to restore the client to the default sources.
