### ISSUE TITLE
list and export commands display different packages

### ISSUE THREAD

**Issue by github-account1111** [microsoft/winget-cli#1464]
# Brief description of your issue

Shouldn't they be the same? Meaning the installed packages available on winget should be shown as available on winget both on the `list` list and the `export` list.
# Steps to reproduce

1. Run:
```
winget list
winget export --output out.txt
```
2. Compare the two outputs.

# Expected behavior

If a package is on the `export` list, then it's also displayed as available on the `list` list, and visa versa.

# Actual behavior

Certain packages listed on the `list` list are shown as unavailable on the export list (and visa versa), e.g. 7-zip.

# Environment

```none
Windows Package Manager v1.0.11692
Windows: Windows.Desktop v10.0.17763.2145
Package: Microsoft.DesktopAppInstaller v1.12.11692.0

Any other software?
```

**Comment by vedantmgoyal2009** [comment]
Can you please post screenshots for a better understanding of the issue?

**Comment by github-account1111** [comment]
Sure.
`winget list`
![image](https://user-images.githubusercontent.com/5728319/133321337-5fe517f8-4f88-4bb8-98aa-d83273461038.png)

`winget export`
![image](https://user-images.githubusercontent.com/5728319/133321666-f6c5aee0-0027-47f0-a993-aebedff226da.png)

Also, why it add the extra space after semicolon?

**Comment by denelon** [comment]
Export would be the subset of packages that have been identified in one of the configured sources. Export should always at least be a subset of list, but not all packages are available in any known sources today. Many packages may not yet be in either the Microsoft Community Repository or the experimental store source.

We will have to look at the white space issue with the JSON output.

**Comment by github-account1111** [comment]
But in this case, export is a superset. It has things list doesn't have.

I'm not sure I follow the explanation. Export pulls from Community Repo and experimental store, while export pulls from those two + somewhere else? What is the reasoning behind this? Why not have them pull from the same sources?

**Comment by denelon** [comment]
The "Available" and "Version" column in the `winget list` output are displaying if a package has an upgrade available from a configured source. It doesn't provide an indication if there is a mapping to a source. My comment was in reference to the list command providing a list of "everything" installed on the machine (whether it's available in a configured source or not). The export command would be a subset of the installed packages based on those matched with a configured source. The UI is a bit confusing which is why we have added an issue for #1155 "Enhancements to list command" coming that should help provide a bit more clarity.

**Comment by github-account1111** [comment]
Oh I think I see now. Just to make sure I'm understanding correctly: if I want to know which of the installed packages is available through winget (no matter whether they were installed using winget or an exe/store/another package manager), `list` is useless, because it only says if an update is available through winget? Meaning 7-zip was listed only in `export` because I already have the latest version?

What do you mean by "a mapping to a source"? I tried searching through the linked issue and the repo but didn't find anything.

**Comment by denelon** [comment]
Sadly, yes, list isn't going to display all available packages until we get the other feature completed.

You may have more than one source. "winget" is the default source pointing to the community repository. We're also working on an experimental source for the Microsoft Store Apps. If that is enabled and/or you have private repositories configured, list would show upgrades available across sources. Similarly, if you had packages from more than one source, export would include Apps from all configured sources during export. The import side would only install Apps from configured sources, it will not automatically add additional sources, you would get a warning.

**Comment by github-account1111** [comment]
Okay thanks for a very thorough explanation and bearing with me. I think this can be closed? Since it's not a bug but my ignorance. Save for the white space part.

**Comment by vedantmgoyal2009** [comment]
Feel free to close yourself.

**Comment by denelon** [comment]
I'm OK with leaving it open if you'd like the whitespace fixed.

**Comment by denelon** [comment]
@github-account1111 we're using a library to generate the file, and the whitespace doesn't seem to be trivial to address. I'm going to go ahead and close this as "not planned".
