### ISSUE TITLE
Dev builds for winget

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-cli#1465]
# Description of the new feature/enhancement

As a regular contributor, I want to get sort of development/nightly builds of winget so that I should know what features/enhancements are being made to the Windows Package Manager and would submit feedback for bugs and improvements. Currently, the builds are only published in the Windows Package Manager Insider program, Windows Insider Dev channel builds and GitHub which are intended for the public to test and submit feedback.

# Proposed technical implementation details (optional)

There should be a private beta program so that users interested can signup for it and receive development/nightly releases.

**Comment by jedieaston** [comment]
BTW, not that this is a replacement, but if you have an hour to set it up, the compilation instructions in the README work. You need some additional workloads (Spectre mitigation libraries for example), but I got it running in a VM pretty easily.

**Comment by JohnMcPMS** [comment]
What mechanism are you asking for to receive the builds?  We can't really automate it being delivered through the Store due to Microsoft security policies, which means it being a nightly of the "official" package would not be possible.

We do publish the binary [as an artifact on the CI builds](https://dev.azure.com/ms/winget-cli/_build/latest?definitionId=344&branchName=master); although that is not really usable alone (we would at least need to publish the PRI file).

I think the most feasible option would be for our CI build to create a signed MSIX package from our dev project.  This would allow for a side-by-side install (it uses `wingetdev` as the alias).  If it takes too long for the CI build, we could instead create a scheduled build daily for this purpose.

**Comment by jedieaston** [comment]
If you could build `wingetdev` daily (or on a PR merge, maybe?), that would be really nice.

**Comment by vedantmgoyal2009** [comment]
I think there can be a private repository also where we can discuss and give feedback. Same as GitHub Copilot does.
![image](https://user-images.githubusercontent.com/83997633/133355618-4d57c67b-bff7-4429-b0b2-4a2ac2b43a38.png)

**Comment by jedieaston** [comment]
The public repo can be used for that just fine though. We shouldn’t have another place, we already split feedback about the product between two (well, four if you include create and restsource) repos. We don’t need another one with restrictions.

**Comment by vedantmgoyal2009** [comment]
> The public repo can be used for that just fine though. We shouldn’t have another place, we already split feedback about the product between two (well, four if you include create and restsource) repos. We don’t need another one with restrictions.

Well, I think that f a user on a stable branch would come to report issues and give feedback, then he might end up being confused with issues reported for development branch and it would really mess up with issues reported for development branch.

**Comment by jedieaston** [comment]
That could probably be handled by a tag added to the issue. But a bug is a bug, if it's in the dev build it'll go to production eventually unless someone fixes it. I don't see why they should be treated differently (VSCode's issues don't work that way, as a example).

**Comment by vedantmgoyal2009** [comment]
Well, I have no problem. I was only sharing my thoughts and suggestions. Where the WinGet team would like, I give my feedback there. 🙂

**Comment by rcdailey** [comment]
What ever happened to zip files with simple executables in them :)

**Comment by Masamune3210** [comment]
Msix is actually a lot better than zip in a lot of cases, mostly it handles system registration and dependencies a whole lot better

**Comment by vedantmgoyal2009** [comment]
So when can we expect dev builds? I am excited to try new features 😁.

**Comment by jedieaston** [comment]
As a stopgap, I've setup a repository that will build nightlies: https://github.com/jedieaston/winget-build

The README explains everything, but basically every night GitHub Actions will build a exe version of wingetdev (and the DLLs/resources), throw them in a zip and create a release. It seems to work well, at least for the cases I personally wanted to test.

**Comment by vedantmgoyal2009** [comment]
I have updated the automation and I can have a nightly build built on every new commit pushed on winget-cli repository.
