### ISSUE TITLE
RESET is confusing

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/winget-cli#1486]
I think this is both a bug and a doc issue.
It is not clear what reset is going to do.  While we require the user to be an admin and use --force, it is not clear we are going to delete data too.

winget source reset
The following sources will be reset if the --force option is given:
Name    Argument
------------------------------------------------------------------
bugbash https://s1
msstore https://s2
winget  https://winget.azureedge.net/cache

C:\WINDOWS\system32>winget source reset --force
Resetting all sources...Done

C:\WINDOWS\system32>winget source reset
The following sources will be reset if the --force option is given:
Name    Argument
-----------------------------------------------------
msstore https://s2
winget  https://winget.azureedge.net/cache

Maybe we should add a comment, "This will remove source **bugbash**, are you sure you want to continue?"

**Comment by denelon** [comment]
This must also honor any Group Policy configured by IT Administrators.

**Comment by denelon** [comment]
Documentation at Microsoft Learn describes what `winget source reset` does.
