### ISSUE TITLE
User vs. System installation (non MSIX)

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#149]
As a user I want to be able to specify whether the software installs for me or any user on my machine.

Note:
The manifest needs to support specifications for both.
The client should default to user mode "out of the box" if no preference is supplied in the manifest and both are possible.
The user should be able to specify user or machine based installation with the client regardless of the manifest default if both are possible.

**Comment by thlac** [comment]
It would also be great if it was possible to run this in context of the localsystem user specifically for machine-based installations. Not sure if this is possible due to being bundled in DesktopAppInstaller, but this would be a great for extending with group policy based deployments or other unattended means of deployment.

**Comment by JohnMcPMS** [comment]
I have added the user control, but this issue still needs work per-installer type to determine if we can dynamically specify scope to the underlying installer. For instance, MSI supports specifying it, as well as embedding the value. And MSIX can be installed for the machine, but requires additional code to convert the user install to a machine install.

So for each type, we need to understand:

1. Are there command line options that let us choose the scope dynamically?
2. Is there metadata embedded in the installer that will tell us the scope?
3. If 2, can it be overridden or would that lead to a dysfunctional package?

With this we could then improve the default behaviors, as currently we don't allow unknown scopes to meet the requirement of a particular given one.

**Comment by denelon** [comment]
#965
