### ISSUE TITLE
winget list shows random (not installed) programms

### ISSUE THREAD

**Issue by leonbcode** [microsoft/winget-cli#1505]
# Brief description of your issue

`winget list` shows programms that aren't installed.

# Steps to reproduce

`winget list`
Right now there is no further information.

# Expected behavior

The command `winget list` should show a list of installed programs.

# Actual behavior

Beside the programs I have installed, there is this following unusual behavior:
- programs I had installed in the past and programs I have never installed show up. (I can't find these programs anywhere)
- programs show multiple times with different versions.
- random program ids

example:
```
Microsoft Photos  9WZDNCRFJBH4  93.0.961.52
Microsoft Photos  9WZDNCRFJBH4  16001.14326.20426.0
Microsoft Photos  9WZDNCRFJBH4  1.0.98.0
Microsoft Photos  9WZDNCRFJBH4  1000.22000.1.0
Microsoft Photos  9WZDNCRFJBH4  12106.1001.33.0
Microsoft Photos  9WZDNCRFJBH4  1.0.41182.0
Microsoft Photos  9WZDNCRFJBH4  1.0.42192.0
```

There is no interaction possible with these programs, e.g. `winget uninstall`

[winget list output.txt](https://github.com/microsoft/winget-cli/files/7227762/winget.list.output.txt)

# Environment

```none
[winget --info]
Windows Package Manager v1.0.11694
Windows: Windows.Desktop v10.0.22000.194
Package: Microsoft.DesktopAppInstaller v1.15.11694.0
```

**Comment by denelon** [comment]
@leonbcode this may already be fixed in our latest development build. Can you install that and see if the problem has been fixed?

https://github.com/microsoft/winget-cli/releases/tag/v1.0.12576

**Comment by leonbcode** [comment]
Yep it fixed the problem. Thank you.
