### ISSUE TITLE
winget install jdk11 but my computer has not jdk and where  is the winget install path

### ISSUE THREAD

**Issue by nocsg** [microsoft/winget-cli#1509]
# Brief description of your issue

# Steps to reproduce

# Expected behavior

# Actual behavior

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
```

**Comment by jedieaston** [comment]
We don't have a package with the moniker `jdk11`. What command are you using to do this?
