### ISSUE TITLE
Support Delivery Optimization

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#151]
Some enterprise tools integrate with delivery optimization (DO) to minimize network traffic.  We need to be good citizen and be DO aware.

As an enterprise administrator I want to have the benefit of reduced traffic to the Internet so I can reduce the cost and load on my network.

# Proposed technical implementation details (optional)

Provide the ability to use DO when downloading resources from the Internet when using the Windows Package Manager.

Edited: description.

**Comment by jszabo98** [comment]
What other enterprise tools integrate with delivery optimization?

**Comment by denelon** [comment]
The reference to #528 is a reminder to look at eliminating additional redundant downloads of the source based on different per user TTL values.

**Comment by skycommand** [comment]
> Most enterprise tools integrate with delivery optimization (DO)

"Most enterprise tools"? Really? If you don't mind, please name them all.

**Comment by ecovio1** [comment]
@skycommand 

Is there any need to be offensive ? that question doesn't like a sincere one.
think of that line as a justification for feature efforts and that's a good sign.

**Comment by denelon** [comment]
@skycommand I edited the description. as @ecovio1 mentioned, it was an initial justification for the feature. I was multi-tasking during the few days ahead of the preview announcement, and didn't always have as much time or focus on crisp descriptions as I would have liked.

**Comment by skycommand** [comment]
@denelon Thanks. I guess I was excited for no reason. And to make matter worse, my excitement led @ecovio1 to assume bad faith.

Bummer.

**Comment by denelon** [comment]
@skycommand no harm was done :smile:. It's hard to convey intent via text, and English is a particularly messy and complicated language. I am always looking for ways to improve the product and to try and meet people where they are. It's also hard sometimes to remember humans are on the other end of the Internet. The Windows Package Manager is a very exciting product I have the privilege to be able to work on. I look forward to any suggestions you may have or other features that would make things better.

**Comment by skycommand** [comment]
Hmm... Your last post got me thinking and I've formed an initial idea. I think adding Delivery Optimization support has no cons. It's a positive. But I think it is ineffective.

Consider the case of delivering Windows updates via Delivery Optimization:

- Each update is no bigger than 1 GB each month.
- Updates are cumulative, so delivering one (the latest) is enough.
- All Windows 10 computers in one site need them.
- Even if the site computers don't need it, the rest of the Internet can benefit from it. Windows 10 has a large installation base.

Now, the same thing cannot be said about the delivery of large apps, like Blender:

- App sizes are larger
- There orders of magnitude more app installation per month than update installations
- They are usually one-off installations for specialized purposes
- Not everyone needs them; wheres 100% of Windows 10 users optimally have to install a cumulative update, less than 1% need to install, e.g., Blender.

No, I think the suitable solution here is a managed cache, similar to ConfigMgr and WSUS. In other words, a local admin should set up a local repo that downloads the apps the local network users need. The network nodes, in turn, fetch from the local repo before looking up the cloud repo.

**Comment by Karl-WE** [comment]
@skycommand

DO isn't that ineffective imho and enabled by default on Windows 10 and 11. But also available on Windows Servers, starting with 2016.

It's widely used for a range of downloads today and growing

- winget, as discussed here
- Office C2R installer for Legacy and M365 Versions
- Windows Update and related techniques (sources could be Configmgr, Intune, Azure Update Management, Azure Update Management Center, WSUS, sconfig,) 
- drivers and firmware lately managed and provided by OEMs into WU
- MS Edge updates
- Microsoft Store / Appx

This list might be incomplete, as I am writing it from the top of my mind. 

From our customers dashboards I am seeing the effectiveness is usually ~ 45-50% savings compared to direct downloads. 

I know Branchcache is able to deliver better from the Configmgr community, and large Apps are even repackaged as WIM to add dedup and compression, so I hear the point. 

Is this information any helpful to you?

**Comment by skycommand** [comment]
@Karl-WE I've already see this: <https://techcommunity.microsoft.com/t5/windows-it-pro-blog/security-best-practices-for-windows-server-update-services-wsus/bc-p/1619772/highlight/true#M1983>
