### ISSUE TITLE
Support installers that require elevated priveleges

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#152]
As a user I want graceful behavior when I try to install an application that requires admin privileges and I'm in user mode.

Notes:
Some applications don't gracefully behave when installation is initiated in user mode and admin mode is required.
We should consider an attribute in the Manifest (like SupportedMode: Admin, RequiresAdmin: true, or something like that)
When the value is specified, the client should not try to perform the install if it's not elevated and the user should be informed.

There should be some automation added when we validate the manifest after PR to check and see if the attribute should have been added.

The client should be able to validate a manifest that has the attribute.

# Proposed technical implementation details (optional)

**Comment by megamorf** [comment]
See:
* #330
* #281
* #271
* #218

**Comment by Trenly** [comment]
@denelon - Resolved by #2126 ?
