### ISSUE TITLE
Support for apps installed outside of the Package manager

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#153]
I want to use the winget client as my tool for configuring all apps on my PC.  Even if I have not installed the app through winget I can list / update / uninstall and repair the app.

By passing a command line argument to the winget, the winget will query the control panel for all ARP entries and all Windows Store and Sideloaded apps. 

winget list --win32
winget update <appname> --win32
winget uninstall <uninstall> --win32

*--win32 is a placeholder name.

**Comment by megamorf** [comment]
If you use WMI to query installed programs make sure to not query `Win32_Product` and instead use `Win32reg_AddRemovePrograms`. `Win32_Product` is not query optimized and interacting with that class will initiate a consistency check of packages installed, verifying and repairing the install.

I believe this is still the case with current builds of Windows 10 even if the original kb is somewhat dated: https://support.microsoft.com/en-in/help/974524/event-log-message-indicates-that-the-windows-installer-reconfigured-al

**Comment by KevinMarquette** [comment]
I think `Win32Reg_AddRemovePrograms` is a SCCM client thing, not exactly sure.

**Comment by megamorf** [comment]
@KevinMarquette Oh, you are right. The class is indeed tied to SCCM and not available by default. An alternative approach would be to enumerate the entries in `<HKCU|HKLM>\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall`.

**Comment by denelon** [comment]
This was completed several releases back. I just missed closing this issue.
