### ISSUE TITLE
winget aggresively now prompts to accept terms unnecessarily 

### ISSUE THREAD

**Issue by nascentt** [microsoft/winget-cli#1535]
# Brief description of your issue
Prompts "Do you agree to all the source agreements terms" even when doing a `winget upgrade` that has no action
there's no way to see which applications are out of date without answering yes to that prompt.  that prompt shouldn't even show on passive commands.

There also needs to be a way to accept the terms via config, or parameter to avoid breaking non-interactive use.

**Comment by denelon** [comment]
@nascentt, there is an `--accept-package-agreements` parameter for package level agreements.

There is an `--accept-source-agreements` parameter for source level agreements.

One you have accepted a source agreement, you shouldn't be prompted again unless the source agreement changes.

Can you confirm if you are being prompted after accepting the source level agreement?
