### ISSUE TITLE
Support for Group Policy Management

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#154]
As an IT professionalI want to be able to control the winget configuration for machines I manage policies for.

**Comment by denelon** [comment]
Here is a list of policies we're considering:

**Disable Windows Package Manager**
This policy will prevent users from being able to use the Windows Package Manager. 

**Disable Settings Command**
This policy will prevent users from being able to change their settings.

**Disable Experimental Features**
This policy will prevent users from being able to enable experimental features in the Windows Package Manager.

**Disable Local Manifest Files**
This policy will prevent users from being able to install packages with local manifest files.

**Set Auto Update Interval In Minutes**
This policy will apply the auto update interval for package-based sources. Note the default setting is five minutes.

**Set Progress Bar**
This policy will apply a visual style to the progress bar. Note the options are: accent, rainbow, plain, and retro.

**Exclude Default Sources**
This policy will remove the default sources included with the Windows Package Manager. Enterprises may add these sources with the Include Enterprise Sources policy.

**Include Enterprise Sources**
This policy will add sources provided by the enterprise IT administrator. Keep in mind this policy can be used to add the default sources removed by the Exclude Default Sources policy.

**Disable Source Configuration Options**
This policy will prevent users from being able to add or remove sources other than those specified by the Exclude Default Sources and Include Enterprise Sources policies. Users will still be able to receive updates to any existing sources in their configurations.

**Comment by sebawern** [comment]
I‘d rather (or also?) like to be able to configure this using Intune (even if that means using CSPs).

**Comment by denelon** [comment]
We will have CSP as well.

**Comment by jedieaston** [comment]
These look great! 

Two questions:

1. For "Enable Windows Package Manager Settings Command", does this block the user from editing the file in %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json by changing file system permissions, or does it just block the ` winget settings ` command?

2. For "Enable Windows Package Manager Allowed Sources", is there a way (currently or planned) for a user to get a list of the allowed sources?

**Comment by denelon** [comment]
@jedieaston, thanks for taking a look. We're planning on "retaining" the settings such that if the policies are "removed", the user will default back to their settings file. It's just going to block the "winget -settings" command. The intent is just to reduce the confusion when there are settings conflicting with policies.

The policies will be available via `winget --info`. We use that for troubleshooting, and figure that's the best place. Since we ask for that output with bugs, it's hopefully an obvious place to see what is affecting users.

**Comment by jedieaston** [comment]
I just thought of another one that would be nice to see: limit users to installing only "User-scoped" manifests that can be installed without admin rights. Preferably, this would also hide manifests that are scoped for the entire system from showing up in `winget search`. 

This would help a ton with preventing user confusion when they get winget and half the things they try to install don't work, since this way winget can hopefully explain what's going on or not show them packages they won't be able to install anyway.

**Comment by denelon** [comment]
The initial work for group policy has been released.

https://aka.ms/winget-policy also hosts the files for ADMX Ingestion.
