### ISSUE TITLE
Key to request for administrator privileges

### ISSUE THREAD

**Issue by albertopasqualetto** [microsoft/winget-cli#1547]
# Description of the new feature/enhancement
It would be good having a feature which requests for administrator privileges without opening a new window of the terminal.

# Proposed technical implementation details (optional)
With a button and also a keyboard shortcut.

**Comment by denelon** [comment]
@albertopasqualetto I'm not sure how this would work. There is no "native" Windows "sudo" equivalent. What you are asking for might be better requested from https://github.com/Microsoft/Terminal.

**Comment by Masamune3210** [comment]
As a quick fix, scoop has a sudo you can download that works reasonably well, but yeah I agree Terminal is probably the better idea, if anything because it would be shell-wide rather than a specific program

**Comment by albertopasqualetto** [comment]
Sorry, completely mistaken the git project! Thanks
