### ISSUE TITLE
Installed Packages Snapshot

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#155]
As a developer I want to take a snapshot of the packages installed on my machine so I can sync that setup on another machine.

Effectively the initial ask was for something that would allow one to define a desired state based on what is currently installed and then configure another machine to match that state

Note:
This is a much more complicated scenario to fully resolve.
One of the concerns is that the manifest file could have been altered from the time one user installed it until the second one did

The challenge is making sure the subsequent users could be informed if something was different from what was available or originally installed on the first machine.

**Comment by Bjego** [comment]
I'm really looking forward to this feature. Hopefully it will support the following changes:

- install (new components)
- update (existing components)
- uninstall (no longer needed components)

**Comment by denelon** [comment]
Duplicate of #220
