### ISSUE TITLE
Spelling and grammar errors in the winget in-line documentation for Icelandic language

### ISSUE THREAD

**Issue by sgsthor** [microsoft/winget-cli#1557]
The one-line description of Winget is in Icelandic:
"Winget-skipanalínubúnaðurinn gerir það kleift að setja upp forrit of aðra pakka úr skipanalínunni."

But should be:
"Winget-skipanalínuforritið gerir það kleift að setja upp forrit og aðra pakka frá skipanalínunni."

"búnaðurinn" vs. "forritið" - búnaður is a physical device - like a watch, thermometer or hammer. Forrit is a program (software).
"of" vs. "og" => Of is "too" as in "too much". Og is "and".
"úr skipanalínunni" indicates that the programs and packages come from the command line, while "frá skipanalínunni" refers to the install action coming from the command line.

**Comment by denelon** [comment]
We've reduced the number of supported languages based on the Microsoft policy for developer tools.
