### ISSUE TITLE
Support a collection of packages

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#156]
As a developer I want to be able to specify a set of packages for the Package Manager to install.

Ideally this would allow a single file to be able to drive a more complex scenario that supports installing multiple packages. The shapshot ask would likely output it's results in this form. The collection could reference multiple manifests in one or more repositories. Initially the scope might need to be reduced to a single repository. If that's the case, this Issue should be split.

**Comment by masx200** [comment]
I support it!

**Comment by denelon** [comment]
This is not the same thing as #219

**Comment by mimi89999** [comment]
Is this what other package managers call virtual packages? A package that does not have files or an installer in itself, but only has dependencies.

**Comment by denelon** [comment]
Duplicate of #220

**Comment by mimi89999** [comment]
Unless I misunderstood what this issue is about, it's not a duplicate of the other issue.

**Comment by denelon** [comment]
The import/export feature leverages a JSON file representing a set of packages. You can either perform an export to build the file, or craft the file by hand. Once you have this file, you can "import" the file and all of the valid packages will be installed.

**Comment by denelon** [comment]
Here is an example of the file:

```JSON
{
	"$schema" : "https://aka.ms/winget-packages.schema.1.0.json",
	"CreationDate" : "2021- 3- 2 14:40:17.181",
	"Sources" : 
	[
		{
			"Packages" : 
			[
				{
					"Id" : "Microsoft.Whiteboard"
				},
				{
					"Id" : "SixgillLLC.hyperlabel"
				}
			],
			"SourceDetails" : 
			{
				"Argument" : "https://winget.azureedge.net/msstore",
				"Identifier" : "Microsoft.Winget.MSStore.Source_8wekyb3d8bbwe",
				"Name" : "msstore",
				"Type" : "Microsoft.PreIndexed.Package"
			}
		},
		{
			"Packages" : 
			[
				{
					"Id" : "Microsoft.WindowsTerminalPreview"
				},
				{
					"Id" : "Microsoft.WindowsTerminal"
				},
				{
					"Id" : "Microsoft.dotnetRuntime"
				}
			],
			"SourceDetails" : 
			{
				"Argument" : "https://winget.azureedge.net/cache",
				"Identifier" : "Microsoft.Winget.Source_8wekyb3d8bbwe",
				"Name" : "winget",
				"Type" : "Microsoft.PreIndexed.Package"
			}
		}
	],
	"WinGetVersion" : "0.2.10572"
}
```
