### ISSUE TITLE
[bug] Conan cannot be installed through Winget due to Windows defender blocking AppInstallerCLI.exe

### ISSUE THREAD

**Issue by aminya** [microsoft/winget-cli#1579]
### Environment Details (include every applicable attribute)
  * Operating System+version: Win 11
  * Compiler+version: - 
  * Conan version: 1.41.0
  * Python version: 3.9

### Steps to reproduce (Include if Applicable)

Try to install Conan using Winget.

I use the protected folders feature of Windows Defender, but the Conan installer should not need to modify those folders! Also, the warning that I get is also related to the protected folders.

### Logs (Executed commands with output) (Include/Attach if Applicable)

Blocked: AppInstallerCLI.exe
Blocked by: Attack surface reduction
Rule: Use advanced protection against ransomware
Affected: C:\Users\aminy\AppData\Local\Temp\WinGet\JFrog.Conan.1.41.0.exe

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-asr?view=o365-worldwide

The link says that this only applies to Enterprise Windows, although I am on a normal edition. 

![image](https://user-images.githubusercontent.com/16418197/136927743-b72eb453-1609-4c59-913d-00a5eab10661.png)

```
> winget --info
Windows Package Manager v1.1.12701
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.194
Package: Microsoft.DesktopAppInstaller v1.16.12701.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

Mirror of https://github.com/conan-io/conan/issues/9777

**Comment by aminya** [comment]
Only Conan. I also got a dialogue error saying something like: the path does not exist.

**Comment by denelon** [comment]
@aminya this issue is quite old and several releases of WinGet have come and gone. Is this still happening?

**Comment by aminya** [comment]
I have not tested, but I don't think it is relevant now
