### ISSUE TITLE
JSON locale Schema does not match REST Source

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#1595]
# Brief description of your issue
The JSON Schema shows that `Moniker` is valid in the locale manifest file and the defaultLocale manifest file. The REST source shows that locale does not contain `Moniker` and that defaultLocale extends locale adding only the moniker field

# Steps to reproduce
Compare the [1.0.0 JSON Schema](https://github.com/microsoft/winget-cli/blob/master/schemas/JSON/manifests/v1.0.0/manifest.locale.1.0.0.json#L105) to the [1.0.0 REST Source](https://github.com/microsoft/winget-cli-restsource/blob/main/documentation/WinGet-1.0.0.yaml#L1144)
Compare the [1.1.0 JSON Schema](https://github.com/microsoft/winget-cli/blob/master/schemas/JSON/manifests/v1.1.0/manifest.locale.1.1.0.json#L126) to the [1.1.0 REST Source](https://github.com/microsoft/winget-cli-restsource/blob/main/documentation/WinGet-1.1.0.yaml#L1421)

### Alternative Reproduction steps
1. Clone the winget-pkgs repository and open it in VS Code
1. Find a package that has a locale and a defaultLocale (I used Google chrome)
1. Edit the locale manifest to have a moniker key and save the file
1. Run `winget validate <path-to-manifest>` on the manifest you just edited
1. Note that it shows a warning that Moniker is unknown

# Expected behavior
The JSON schema should match the behavior exhibited by WinGet and the REST source

# Actual behavior
These items do not match

# Environment

```none
PS C:\WINDOWS\system32> winget --info
Windows Package Manager v1.1.12653
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1237
Package: Microsoft.DesktopAppInstaller v1.16.12653.0
```

**Comment by denelon** [comment]
Is this the same as #1592?
