### ISSUE TITLE
winget' is not recognized

### ISSUE THREAD

**Issue by TomaszMyszak** [microsoft/winget-cli#1603]
### Brief description of your issue

winget : The term 'winget' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
 the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ winget search java
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (winget:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

### Steps to reproduce

after instalation don't work

### Expected behavior

working 

### Actual behavior

not working

### Environment

```shell
nothing 

C:\Windows\system32>winget --info
'winget' is not recognized as an internal or external command,
operable program or batch file.


C:\Windows\system32>winget --help
'winget' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by HUMORCE** [comment]
Troubleshooting:
https://github.com/microsoft/winget-cli/blob/master/doc/troubleshooting/README.md#executing-winget-doesnt-display-help

**Comment by jedieaston** [comment]
What version of Windows are you on?

**Comment by TomaszMyszak** [comment]
this problem was in Windows 10, now I upgrade do 11 ver and I use winget :-)

**Comment by s4sutler100** [comment]
PS C:\Users\Steven Sutler> /winget
/winget: The term '/winget' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by ItzLevvie** [comment]
Have you tried `winget` instead of `/winget`?

**Comment by Tebzaaa** [comment]
It might be an issue with the user you are currently signed in with not recognizing the path.
====================================
Makesure the windows Package manager is installed on your appstore and uptodate

If you are still having issue you can set the path to winget explicitly
