### ISSUE TITLE
winget should download and launch the installation of a package if the name in the command "winget install" is exactly the good package name or the good package ID, even if there are other software with almost the same name.

### ISSUE THREAD

**Issue by SuperPat45** [microsoft/winget-cli#1609]
### Brief description of your issue

winget does not install a software if there is a second software having almost the same name.

### Steps to reproduce

`winget install CCleaner`
or
`winget install Piriform.CCleaner`

### Expected behavior

winget should download and launch the installation of a package if the name in the command "winget install" is exactly the good package name or the good package ID, even if there are other software with almost the same name.

### Actual behavior

I have a message:

> Several packages match your criteria. Please refine your search.

And I am unable to install this software…

![winget](https://user-images.githubusercontent.com/7791600/137773549-47c3e7fe-a3cb-4106-8687-9525679ade54.png)

### Environment

```shell
Windows Package Manager v1.1.12653
Windows: Windows.Desktop v10.0.19044.1288
Package: Microsoft.DesktopAppInstaller v1.16.12653.0
```

**Comment by Trenly** [comment]
I hink this is already implemented with the `-e` parameter, but I would have to double check tobe sure.

I am against this idea of this as a default behavior though. I realize this may be an edge case, but there are situations where there may be multiple release channels for a single package and a user unknowingly types in the exact name of one of them. While it certainly may not be the worst thing for most packages, there are some packages which have a separate identifier for the normal edition and the full edition. If the default here was to install a package if the name matched exactly, it could lead to the user not knowing that there was a full version and a normal version. 

Again, this is a bit of an edge case, and `winget search` can be used as a workaround to the edge case, but I personally believe that consumers should be as informed as possible to make decisions, and not asking for a refined input takes away some of that ability for choice
