### ISSUE TITLE
"winget list" and "winget upgrade" say I have a package installed that I don't.

### ISSUE THREAD

**Issue by darkvertex** [microsoft/winget-cli#1624]
### Brief description of your issue

"winget list" says I have a package installed that I don't, but said package does not appear in "winget export" output.

(Should "winget list" and "winget export" output match? Both are for listing what's installed, correct?)

### Steps to reproduce

I don't know how to reproduce this on another machine than my own, but for me, I do `winget list Blender` and two versions are listed as installed, which is not true. Only 1 is.

### Expected behavior

I expect `winget list` to list packages that are _actually_ installed.

`winget list Blender` should be saying:
```
Name    Id                        Version Available Source
----------------------------------------------------------
Blender BlenderFoundation.Blender 2.93.5            winget
```

### Actual behavior

`winget list Blender` gives me:
```
Name    Id                        Version Available Source
----------------------------------------------------------
Blender BlenderFoundation.Blender 2.93.5            winget
Blender BlenderFoundation.Blender 2.92.0  2.93.5    winget
```

- 2.92.0 is not actually installed right now.
- It doesn't show up in the "Add or remove programs" list in native Windows either:
![image](https://user-images.githubusercontent.com/941331/138378059-c10113e8-74fe-46f5-84b2-d00e437c1fe5.png)

- It doesn't exist on disk either. The only blender.exe that exists is 2.93.5.

I have no clue where winget is detecting this from.

### Environment

```shell
Windows: Windows.Desktop v10.0.19042.1288
Package: Microsoft.DesktopAppInstaller v1.16.12653.0
```

**Comment by denelon** [comment]
We've added better support for side-by-side package management in WinGet 1.8-preview releases, and we're going to make that support stable. These issues appear to be caused by installers not properly removing entries during an upgrade flow or an uninstall flow. WinGet is using data from the registry to display what is installed on the system.
