### ISSUE TITLE
Support installing APK into windows subsystem for android (WSA)

### ISSUE THREAD

**Issue by oxygen-dioxide** [microsoft/winget-cli#1625]
### Description of the new feature / enhancement

Windows 11 supports windows subsystem for android now. I hope that we can install apk with winget.

### Proposed technical implementation details

Firstly, download apk from the download link provided in manifest.
Secondly, use adb (bundled with winget package) to install this apk.

**Comment by W2725730722** [comment]
It's good

**Comment by upintheairsheep** [comment]
> Tangentially related, but does anyone know if there's a way to install APKs on the subsystem without ADB right now?

I think via some filesystem hacks it is.

**Comment by upintheairsheep** [comment]
@Trenly This issue deserves a pull request, it is relatively easy to implement:
1. Windows Subsystem for Android is installed
2. ADB must be installed on the machine
3. It must connect to the Subsystem, bypassing the developer mode restriction, which I think the uninstallation in control panel already has.


A nice feature in the manifest would be for adding the adb install flags that allow for stuff like test apps to be installed.

**Comment by RokeJulianLockhart** [comment]
@oxygen-dioxide, why https://github.com/microsoft/winget-cli/issues/1625#event-12035696430?

**Comment by oxygen-dioxide** [comment]
> @oxygen-dioxide, why [#1625 (comment)](https://github.com/microsoft/winget-cli/issues/1625#event-12035696430)?

Because WSA isn't supported by Microsoft anymore. Besides, even if WSA is still in support, I don't think it is a good idea to manage APKs in the same tool that manages windows applications now. It would be better to have another tool to manage Android apps.
