### ISSUE TITLE
Change enviroment paths after upgrade program

### ISSUE THREAD

**Issue by geazi-anc** [microsoft/winget-cli#1635]
### Description of the new feature / enhancement

# Feature
After upgrade a program by Winget, change automaticaly  enviroment path of a program to latest version of this program.

For example: I have installed python 3.8.4. When I upgrade it to latest version, change enviroment path of python 3.8.4 to new version of python.

Currently, when upgrade python, in this case, I need change enviroment path manualy to new folder of new python version upgraded by Winget.

**Comment by Karl-WE** [comment]
This would be the same with Oracle Java JRE
common variables are $env:path, $env:javahome etc. 

I agree with @denelon this is out of scope and belongs to the responsibility of the package.

Kindly suggest to close this one and ask @geazi-anc to report to the app vendor Suggesting an improvement over there.

Unless it could be reproduced that calling the installer manually produces a different result. In that case the yaml in winget-pkgs
might miss an optional installation switch for the path variable.
