### ISSUE TITLE
Default winget source unavailable? 

### ISSUE THREAD

**Issue by pearson** [microsoft/winget-cli#1638]
### Brief description of your issue

On this Windows 10 install that was just upgraded to Windows 11, `winget` only shows results from the msstore. 

Example output from `winget search 7zip`:

> ```
> Failed when searching source; results will not be included: winget
> Name                                                                                      Id           Version Source
> -----------------------------------------------------------------------------------------------------------------------
> Zip Quick View - rar 7zip uncompress drag/drop                                            9NKWR8FH731C Unknown msstore
> Zip - Real Zip: Unzip & Extract Zip, Rar, 7z, 7zip & More, also a File Compression App (… 9NSXFD2VRPQG Unknown msstore
> Unarchiver One Archive File Manager -Compress Extract RAR,7zip,zip,7z,ISO                 9P8405B66PZV Unknown msstore
> Open Rar Zip 7Zip Unrar Tar Unzip : Extract & Archives All Files                          9NQ657WKQDXW Unknown msstore
> Zip Unlock - Unpack RAR, open zip, 7zip, gzip                                             9N487GM876Q7 Unknown msstore
> Easy Unrar - ZArchiver, Unzip & Zip, gzip, 7zip                                           9PLNC0QX58D9 Unknown msstore
> 9 ZIP - open rar, zip, 7zip, gzip                                                         9NBLGGH3TDHG Unknown msstore
> WinRare+ .. preview, extract and create: rar, zip, 7zip, gzip                             9PG2VPDGMJ71 Unknown msstore
> 8 Zip - open and extract RAR, ZIP, 7zip, 7z, ZipX, Iso, Cab for free                      9WZDNCRFJB33 Unknown msstore
> ```

Some steps that were taken:
- Install the current release of `winget`, which has the same version number as what was already installed
- `winget source reset winget`, which actually deleted the `winget` source, as is noted in #1575 
- `winget source add --name winget https://winget.azureedge.net/cache` resulted in the following output:

> ```
> Adding source:
>   winget -> https://winget.azureedge.net/cache
>   ██████████████████████████████  0%
> Failed to open the added source.
> Removing source: winget...
> Done
> ```

### Steps to reproduce

It is unclear how to reproduce this problem on other systems.

### Expected behavior

1. Packages from the winget source would be displayed
2. The original winget source should be added back to the sources list with `winget source add --name winget https://winget.azureedge.net/cache`

### Actual behavior

Only results from the `msstore` source are being displayed, as if the `winget` source is currently unavailable.

### Environment

```shell
Windows Package Manager v1.1.12653
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.282
Package: Microsoft.DesktopAppInstaller v1.16.12653.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by maehne** [comment]
@ItzLevvie: Thanks for your feedback! Unfortunately, I overlooked it due to busy work weeks with lot of e-mail traffic.

I think the main issue was not on the server side, but it is a bug in `winget`'s implementation: In fact, `winget` is only able to update the `winget` source, when I am logged in with my administrator account and issue the command in a terminal. However, I have a differently named normal user account, which I use for my day-to-day work. When I open the Windows Terminal as Administrator and issue `winget` from that terminal, I consistently get an error that it cannot update the `winget` source. Maybe this is worth its own issue or it is already tracked as an issue?

**Comment by nwp90** [comment]
A big thank-you to @maehne for that last comment - saved us much frustration.
