### ISSUE TITLE
Add YAML Schema for package definition files

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/winget-cli#165]
Please add a schema (and documentation) for the package definition files so that modern editors like VSCode can help us write package files more easily and correctly.

Useful references that may help:

* https://json-schema-everywhere.github.io/yaml
* http://rx.codesimply.com/

**Comment by denelon** [comment]
@bitcrazed https://github.com/microsoft/winget-cli/tree/master/schemas/JSON/manifests/v1.0.0

With the YAML plugin for Visual Studio Code manifests are easier to author.

Include the comment on the top line of the file.

Single file "singleton" manifest schema:
```YAML
# yaml-language-server: schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
```

Multiple file YAML manifest schemas:
```YAML
# yaml-language-server: schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json
```
```YAML
# yaml-language-server: schema=https://aka.ms/winget-manifest.defaultlocale.1.0.0.schema.json
```
```YAML
# yaml-language-server: schema=https://aka.ms/winget-manifest.locale.1.0.0.schema.json
```
```YAML
# yaml-language-server: schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
```
