### ISSUE TITLE
[Bug]: Java(jre) Upgrade issue

### ISSUE THREAD

**Issue by kdpuvvadi** [microsoft/winget-cli#1657]
### Brief description of your issue

Upgrading jre is problematic. Java allows multiple version installations. That causing issue. I've installed jre version `8.0.2910.10`. Later tried upgrading with `winget upgrade --id Oracle.JavaRuntimeEnvironment` . It installed version `8.0.3010.9`. Now if i try to upgrade with `winget upgrade` it shows multiple installed version found error.

### Steps to reproduce

- Install Jre version `8.0.2910.10` with `winget install Oracle.JavaRuntimeEnvironment -v 8.0.2910.10`
- Install jre version `8.0.3010.9` with `winget install Oracle.JavaRuntimeEnvironment -v 8.0.3010.9`
- try upgrading with  `winget upgrade --id Oracle.JavaRuntimeEnvironment`

### Expected behavior

Upgrade the JRE

### Actual behavior

```
$ winget upgrade --id Oracle.JavaRuntimeEnvironment
Multiple installed packages found matching input criteria. Please refine the input.
Name                       Id
-----------------------------------------------------------------
Java 8                     Oracle.JavaRuntimeEnvironment
Java 8 Update 301 (64-bit) {26A24AE4-039D-4CA4-87B4-2F64180301F0}
```

### Environment

```shell
Windows Package Manager v1.1.12653
Windows: Windows.Desktop v10.0.19043.1288
Package: Microsoft.DesktopAppInstaller v1.16.12653.0
```

**Comment by WrinkleRelease** [comment]
Same issue. I have only one version of Java on my system, but upgrade fails.

```
C:\Windows\System32>winget list --id Oracle.JavaRuntimeEnvironment
Name   Id                            Version    Available   Source
------------------------------------------------------------------
Java 8 Oracle.JavaRuntimeEnvironment 8.0.3010.9 8.0.3110.11 winget

C:\Windows\System32>winget upgrade --id Oracle.JavaRuntimeEnvironment
No applicable update found.
```

### Environment
```
Windows Package Manager v1.1.13405
Windows: Windows.Desktop v10.0.19042.1415
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```

**Comment by denelon** [comment]
@WrinkleRelease do you see the same upgrade available via `winget upgrade`?

**Comment by OfficialEsco** [comment]
`winget upgrade Oracle.JavaRuntimeEnvironment; winget --info`
Default logs location: `%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir`
Past the log(s) or a snipped of the log, however you will most likely see this
```
2021-10-28 21:04:21.686 [CLI ] Installer [X64,Exe,Machine,] not applicable: Installed package type is not compatible with Exe
2021-10-28 21:04:21.686 [CLI ] Installer [X86,Exe,Machine,] not applicable: Installed package type is not compatible with Exe
```

**Comment by denelon** [comment]
We have several draft PRs related to the 1.1 schema we need to finish, and we need to implement the code start checking the Apps & Features section.

**Comment by denelon** [comment]
@WrinkleRelease no, that's enough confirmation. We're trying to isolate the various reasons we aren't able to disambiguate, or to deal with nested installer types. Sometimes an .exe installer contains an MSI, and in that case, we see a mismatch between the installer type. We still need to implement the code to support this in the 1.1 schema.

**Comment by denelon** [comment]
It's been a while since I updated this issue, and a couple of new Java releases have come out.

Are we handling these correctly, or do we have more work to do here?

**Comment by kdpuvvadi** [comment]
Seems like it is working as intended. 

## install `8.0.2910.10`

```
$ winget install Oracle.JavaRuntimeEnvironment -v 8.0.2910.10
Found Java [Oracle.JavaRuntimeEnvironment] Version 8.0.2910.10
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://javadl.oracle.com/webapps/download/AutoDL?BundleId=244584_d7fc238d0cbf4b0dac67be84580cfb4b
  ██████████████████████████████  80.6 MB / 80.6 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

## Check for upgrade 

```
$ winget upgrade
Name                                            Id                                     Version          Available
--------------------------------------------------------------------------------------------------------------------
Java 8 Update 291 (64-bit)                      Oracle.JavaRuntimeEnvironment          8.0.2910.10      8.0.3610.9
```

## Upgrade jre

```
$ winget upgrade Oracle.JavaRuntimeEnvironment
Found Java 8 [Oracle.JavaRuntimeEnvironment] Version 8.0.3610.9
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://javadl.oracle.com/webapps/download/AutoDL?BundleId=247947_0ae14417abb444ebb02b9815e2103550
  ██████████████████████████████  62.1 MB / 62.1 MB
Successfully verified installer hash
Starting package uninstall...
Successfully uninstalled
Starting package install...
Successfully installed
```

We can close this issue.
