### ISSUE TITLE
"Special" return codes are treated as duplicate

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-cli#1668]
### Brief description of your issue

If you have a manifest that lists a return code that winget has a special case for (like 3010 for MSIs that require restarts), `winget validate` thinks it is duplicated in the manifest even if it is not.

This is breaking validation for some manifests, see https://github.com/microsoft/winget-pkgs/pull/33657. 

### Steps to reproduce

1. Create a manifest for a MSI that lists 3010 as a `ExpectedReturnCode`.
2. Run `winget validate <path to newly created manifest>`

### Expected behavior

Manifest validation successful.

Or, if we don't want people being able to say they expect 3010 (which I don't think is the intended behavior), something like "Manifest validation failed. 3010 cannot be an expected return code." (but formatted correctly)

### Actual behavior

```
Manifest validation failed.
Manifest Error: Duplicate installer return code found.
```
(but there isn't a duplicate in the manifest).

### Environment

```shell
Windows Package Manager v1.1.12663
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.282
Package: Microsoft.DesktopAppInstaller v1.16.12663.0
```
```

**Comment by JohnMcPMS** [comment]
The manifest you linked to actually has 3010 as an `InstallerSuccessCodes` value.  Fortunately, @yao-msft just fixed this in #1646 and I think it is on its way to the production service (timeframe unknown).

**Comment by JohnMcPMS** [comment]
And now I see that you already verified that it didn't fix it on the linked PR.  I guess there is a good test case here then @yao-msft .

**Comment by yao-msft** [comment]
I think it's because the fix is not released with latest winget yet. I just tried build with the fix [here](https://dev.azure.com/ms/winget-cli/_build/results?buildId=238861&view=artifacts&pathAsName=false&type=publishedArtifacts) using the manifests in the issue description, manifest validation passed.

**Comment by jedieaston** [comment]
My local master wasn't synced up, it's working now. I can close this now, or leave it open until it hits the validation service. Sorry for the confusion!

**Comment by yao-msft** [comment]
This fix is released in prod this morning.
