### ISSUE TITLE
winget install OBSProject.OBSStudio = Installer failed with exit code: 6

### ISSUE THREAD

**Issue by danielsoaresp** [microsoft/winget-cli#1675]
### Brief description of your issue

`winget install OBSProject.OBSStudio`
Found OBS Studio [OBSProject.OBSStudio] Version 27.1.3
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://github.com/obsproject/obs-studio/releases/download/27.1.3/OBS-Studio-27.1.3-Full-Installer-x64.exe
  ██████████████████████████████  86.4 MB / 86.4 MB
Successfully verified installer hash
Starting package install...
**Installer failed with exit code: 6**

### Steps to reproduce

Try to install OBS Studio via Winget .

### Expected behavior

Expected normal installation.

### Actual behavior

Installer failed with exit code: 6

### Environment

```shell
winget --info
Windows Package Manager v1.1.12663
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.282
Package: Microsoft.DesktopAppInstaller v1.16.12663.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
Licence Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by denelon** [comment]
Exit code 6 is coming from the OBS Studio installer. The installer is an EXE (specifically nullsoft), so the error codes aren't standardized as they are in an MSI or a MSIX package. I did a quick search, and didn't see anything telling me what their installer error code 6 refers to. We have added a section on Expected Return Codes in the new 1.1 manifest schema so the error can be mapped to a friendly message for users, but we don't know what the specific error is in this case.

**Comment by jedieaston** [comment]
I can't replicate this. Can you try restarting your computer and running it again? I wonder if it's something silly, like a file being locked.

**Comment by danielsoaresp** [comment]
> Exit code 6 is coming from the OBS Studio installer. The installer is an EXE (specifically nullsoft), so the error codes aren't standardized as they are in an MSI or a MSIX package. I did a quick search, and didn't see anything telling me what their installer error code 6 refers to. We have added a section on Expected Return Codes in the new 1.1 manifest schema so the error can be mapped to a friendly message for users, but we don't know what the specific error is in this case.

Thanks for the response! I believe it was indeed a file lock error as @jedieaston mentioned. 

> I can't replicate this. Can you try restarting your computer and running it again? I wonder if it's something silly, like a file being locked.

Thanks for your suggestion, i've rebooted and instalation proceed as usuall.

` winget install OBSProject.OBSStudio`
Found OBS Studio [OBSProject.OBSStudio] Version 27.1.3
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://github.com/obsproject/obs-studio/releases/download/27.1.3/OBS-Studio-27.1.3-Full-Installer-x64.exe
  ██████████████████████████████  86.4 MB / 86.4 MB
Successfully verified installer hash
Starting package install...
Successfully installed

**Comment by cjwijtmans** [comment]
i get the same error. i never ran obs studio so idoubt a file is locked.

**Comment by No0Vad** [comment]
@cjwijtmans Same here just now. But if you run the .exe file winget downloads you'll see what file is causing the error.
In my case the installer did not like that NZXT CAM running 🤷

**Comment by AdonNeet** [comment]
i have same problem but i dont want to uninstall it, how?
![image](https://github.com/microsoft/winget-cli/assets/95969256/8a53da87-d55f-42d6-82bc-dd47306072ac)

**Comment by No0Vad** [comment]
@adonneet If you add `-i` to your command (example: ` winget upgrade --id OBSProject.OBSStudio -i`) it will show the installer and it will tell you which app is blocking.

For me it's always NZXT CAM, closing that app fixes it and opening it again after works.

**Comment by AdonNeet** [comment]
i see, ok let me check it

**Comment by giaco77** [comment]
> @AdonNeet If you add `-i` to your command (example: ` winget upgrade --id OBSProject.OBSStudio -i`) it will show the installer and it will tell you which app is blocking.
> 
> For me it's always NZXT CAM, closing that app fixes it and opening it again after works.

the -i parameter actually made my day! Thanks so much! <3

**Comment by AurevoirXavier** [comment]
> @AdonNeet If you add `-i` to your command (example: ` winget upgrade --id OBSProject.OBSStudio -i`) it will show the installer and it will tell you which app is blocking.
> 
> For me it's always NZXT CAM, closing that app fixes it and opening it again after works.

Works, for me it's Nvidia Broadcast.

**Comment by redboyhun** [comment]
for me it was Webex

**Comment by Shioe1** [comment]
The normal Installer from the Website can also tell you which process is blocking the installation. For me it was Chrome.

**Comment by k0pernikus** [comment]
> [@AdonNeet](https://github.com/AdonNeet) If you add `-i` to your command (example: ` winget upgrade --id OBSProject.OBSStudio -i`) it will show the installer and it will tell you which app is blocking.
> 
> For me it's always NZXT CAM, closing that app fixes it and opening it again after works.

I cannot thank you enough. I was completely stomped figuring out what was blocking the install.

---

If you do not want to leave the powershell session, you can see what is currently running with:

```
> Get-Process

 NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
 ------    -----      -----     ------      --  -- -----------
     31    31.90      24.41       0.00   10400   0 apigateway
     13    15.82      14.18       0.00    6772   0 app-service
...
```

If you know the application, figure out the `ProcessName`, in my case it was Google Chrome and its ProcessName is `chrome`:

```
Get-Process | grep -i chrome
     26    51.23     104.38       1.23    6176   2 chrome
     25    28.52      74.91       0.22    8620   2 chrome
...
```

I then killed the instances and applied the upgrade via:

```
> Stop-Process -Name chrome && winget upgrade --id OBSProject.OBSStudio --silent
```

**Comment by yannara** [comment]
Still same problem :(

**Comment by No0Vad** [comment]
@yannara I still believe using interactive flag `-i` is the easiest way to see which process is blocking and then terminate it so you can install OBS.

https://github.com/microsoft/winget-cli/issues/1675#issuecomment-1582357844

**Comment by yannara** [comment]
> [@yannara](https://github.com/yannara) I still believe using interactive flag `-i` is the easiest way to see which process is blocking and then terminate it so you can install OBS.
> 
> [#1675 (comment)](https://github.com/microsoft/winget-cli/issues/1675#issuecomment-1582357844)

yep.... I am trying to automate the entire solution, there will be no manual command input for this....

**Comment by No0Vad** [comment]
> > [@yannara](https://github.com/yannara) I still believe using interactive flag `-i` is the easiest way to see which process is blocking and then terminate it so you can install OBS.
> > [#1675 (comment)](https://github.com/microsoft/winget-cli/issues/1675#issuecomment-1582357844)
> 
> yep.... I am trying to automate the entire solution, there will be no manual command input for this....

Ahh, I see. The only solution I can think of is you have a list of known processes to close do what **k0pernikus** did here
 https://github.com/microsoft/winget-cli/issues/1675#issuecomment-3485734647.

**Comment by k0pernikus** [comment]
On another machine, the offending programs were:

- Signal Desktop App
- Loigtech's Logi Tune

<img width="502" height="388" alt="Image" src="https://github.com/user-attachments/assets/ae847bc6-3709-470e-8f7f-bbe0df309cc1" />

**Comment by spider623** [comment]
I know this is old but today i get the error from chrome, some how now even chrome was a webcam.... commenting for future reference
