### ISSUE TITLE
Pass credentials on the command line or prompt once for admin credentials

### ISSUE THREAD

**Issue by TWanamaker** [microsoft/winget-cli#1676]
### Description of the new feature / enhancement

I would like to run winget upgrade --all, and walk away from it. Instead, I get multiple requests to enter my admin level credentials which is somewhat annoying.

### Proposed technical implementation details

It would look something like this on the command line.

--user <user_id> --password <user_password> (future --certificate <path_to_private_key>)
or
--credentials userid/userpassword

Another option 

--escalate or --elevate -e
This would ask for the credentials once to avoid passing credentials on the command line.

**Comment by jedieaston** [comment]
One way a lot of us do it is through something like [`gsudo`](https://github.com/gerardog/gsudo) (`winget install gerardog.gsudo`).

It allows you to run a single command as a administrator, so you can do `gsudo winget upgrade --all` and winget along with all of the processes will be elevated.

**Comment by TWanamaker** [comment]
That works for me!

Please close or delete this ticket.

**Comment by jedieaston** [comment]
You can close it, by going to the bottom of this page and clicking "Close issue".

**Comment by TWanamaker** [comment]
No longer needed
