### ISSUE TITLE
P.S.A. Holidays

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#1684]
Hello everyone. I wanted to let you all know as we enter into the holidays, there will be periods of less activity. Many of the Microsoft employees working on the project have substantial amounts of paid time off subject to loss if they are not taken this year. Many of the areas of focus during this time are in support of engineering improvements to help make the team more efficient when troubleshooting issues, or spending time "on-call" to support various aspects of the services and integration between GitHub and Azure DevOps.

**Comment by CharlotteEm** [comment]
> Many of the Microsoft employees working on the project have substantial amounts of paid time off subject to loss if they are not taken this year

We're really sad that your vacation and bonus will be lost if you don't work on the holidays.

**Comment by Masamune3210** [comment]
its how most companies are, unfortunately. have fun with your time off and relax everybody

**Comment by EqualDust** [comment]
winget is disgusting

**Comment by Meir017** [comment]
@denelon I think you should lock this thread as it's just an announcement and there is not need for subscribers to get notified about reaction comments...

**Comment by BentramLawrence** [comment]
on top of it all, supposedly everyone in this thread is a spammer? instead of actually fixing the product, msft engineers just pretend users are spam
