### ISSUE TITLE
Add Windows7 support

### ISSUE THREAD

**Issue by mrx23dot** [microsoft/winget-cli#1686]
### Description of the new feature / enhancement

Not everyone is going to upgrade to Windows 10, think older HW/third countries/industrial apps.

Admins still have to support these, even after MS dropped support.

**Comment by TreeBranches** [comment]
How do you expect this to happen when the Windows Store is not on Windows 7?

**Comment by mrx23dot** [comment]
winget install python golang

Is it hardcoded to use Windows Store? (is it just an empty cli interface for Windows Store?)

Or an winget.exe could download the installer over https and run it in the background, without any MS login.

**Comment by Masamune3210** [comment]
The store isnt required at least to retrieve apps as msstore source isn't required. Getting the app and modifying the code to run on older versions of Windows is probably the issue more than the store part

**Comment by mrx23dot** [comment]
Well, github say it's written 86% in C++, it shouldn't be that hard to write portable code (even to compile it to 32bit, -m32), 
path names have general format %APPDATA% etc.
Starting an installer is `cmd.exe installer.exe parameters`.
I guess you keep a database of installed apps in a .ini file, which is fully portable.
openssl lib can handle TLS 1.3 transfer.

**Comment by OfficialEsco** [comment]
Knew i've seen this question before https://github.com/microsoft/winget-cli/discussions/1020

Somewhat relatable https://github.com/microsoft/winget-cli/discussions/847

**Comment by ItzLevvie** [comment]
Related: https://github.com/microsoft/winget-cli/issues/1008

![image](https://user-images.githubusercontent.com/11600822/143626025-bc9c725e-6210-40e1-86df-6e24bcc2ecbf.png)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This comment is response to "http://github.com/microsoft/winget-cli/issues/1686#issuecomment-980389836":

MSIX is available for Windows 7. Do observe "http://docs.microsoft.com/windows/msix/msix-core/msixcore" for verification of support.

**Comment by ItzLevvie** [comment]
Thanks ;)

Didn't know MSIX is available for Windows 7, but there seems to be some downsides with it: https://docs.microsoft.com/en-us/windows/msix/msix-core/msixcore#considerations-of-msix-core.

Seems like people will have to use AppInstallerCLI.exe and set it as %PATH% rather than using the MSIX version.

It also looks like WinGet will need to support older versions of Windows first before using MSIX Core, according to: MSIX Core enables the installation of MSIX apps on previous versions of Windows, provided that the apps are already built to work on those versions of Windows.

**Comment by mrx23dot** [comment]
Not sure why the MSIXCore win+R restriction, "echo %appdata%" works great on local cmd.exe.
I also assume you would run WinGet as admin, which should be very close to win+R cmd.
Maybe if it changes system-env-vars you might need win+R, but Chocolately has a great script to reload them from normal cmd.exe.

There shouldn't be many win10 dependencies in WinGet to compile it to win7, I would imagine getting windows version and paths. Could someone try to compile it to win7 and share the compiler error log to see how much work is it?

What are the minimum .NET requirements for WinGet?

**Comment by sredna** [comment]
> It looks like you can only run WinGet in Win + R

This is probably related to the alias. Win+R is `ShellExecute`  which means it probably has registered an App Paths in the registry meaning `start /b winget ...` should work in cmd.exe or you can just modify %path% yourself.

**Comment by mrx23dot** [comment]
This should work in that case:
- setx PATH "C:\myfolder;%PATH%"
- Open a new cmd session. (As setx activates from new session)

Instead last step use this script in same window: https://github.com/chocolatey-archive/chocolatey/blob/master/src/redirects/RefreshEnv.cmd

**Comment by mrx23dot** [comment]
Wasn't the goal to build it on .NET which suppose to provides abstraction?

**Comment by Masamune3210** [comment]
You can only do so much abstraction before you require a specific feature from the system.

**Comment by denelon** [comment]
We will not be targeting below Windows 10 (1809).

**Comment by sskras** [comment]
@Masamune3210 commented [on Nov 29, 2021](https://github.com/microsoft/winget-cli/issues/1686#issuecomment-982009141):

> You can only do so much abstraction before you require a specific feature from the system.

So what specific features does `winget-cli` need that are missing from Windows 7 ?

**Comment by TreeBranches** [comment]
> @Masamune3210 commented [on Nov 29, 2021](https://github.com/microsoft/winget-cli/issues/1686#issuecomment-982009141):
> 
> > You can only do so much abstraction before you require a specific feature from the system.
> 
> So what specific features does `winget-cli` need that are missing from Windows 7 ?

See here:
https://github.com/microsoft/winget-cli/issues/1686#issuecomment-981799599

**Comment by sskras** [comment]
@TreeBranches: 

> See here: [#1686 (comment)](https://github.com/microsoft/winget-cli/issues/1686#issuecomment-981799599)

OK, it's the API for "Packaging, deployment, and query of Windows Store apps".
Do you mean it's the only feature that is missing on w7 ?

**Comment by sredna** [comment]
> Isn't possible to read os version/type universally, without GetPackageFamilyName

Windows 7 does not support UWP/SparsePackage so all they would have to do is use `GetProcAddress` on `GetPackageFamilyName` and if it is not there then winget is not packaged.

**Comment by TreeBranches** [comment]
That would mean that "They" would have to cater the tool to work on an OS that "They" haven't supported for over three years, and currently has a global market share of 3.6% (according to gs.statcounter.com) and declining.

If your hardware can run 7, it can run 10.

**Comment by sskras** [comment]
> That would mean that "They" would have to cater the tool to work on an OS that "They" haven't supported for over three years, 

Yes, just like the tool workder before [v0.2.2941 Preview](https://github.com/microsoft/winget-cli/releases/tag/v0.2.2941-preview#:~:text=Note&text=Binaries,1809.) circa Oct 29, 2020:

    Binaries removed. We have discontinued support for versions of Windows 10 prior to version 1809

> and currently has a global market share of 3.6% (according to gs.statcounter.com) and declining.

To make comparison more fair, it will need to count only installations that were running `winget` in a permanent manner during 2020, before dropping the aforementioned support. Which numbers now are probably hard to get (if possible at all).

> If your hardware can run 7, it can run 10.

I take this an off-topic at the very least. With the same success I could say that anyone running w10 can run Debian or Ubuntu instead and replace `winget` with `apt` which supports everything down to [Debian 2.1](http://archive.debian.org/debian/dists/slink/).

I stress that it's quite offensive to say. The UX is entirely different (both 7-vs-10 and 10-vs-Ubuntu).

> Else, fork it and you can do it.

Sure, that's why asked you [to summarize / if I got the needed features missing from w7 right from the comment](https://github.com/microsoft/winget-cli/issues/1686#issuecomment-1589061799) (and since you pointed me to it).

**Comment by Masamune3210** [comment]
I mean, the issue is closed and the statement has been made. 7 has been out of support for quite a while now, is it really surprising to see that this isn't going to ever support it when even open-source projects with communal effort behind it is also doing the same thing?

**Comment by sskras** [comment]
@Masamune3210:

> is it really surprising to see that this isn't going to ever support it 

Partly yes. The EOL OSes usually stops being moving targets (their APIs don't change anymore).  Which means the code to support them needs little changes (if any).  If the code runs on 7, it runs.  Things will not change here anymore.

And statements about 7 being insecure has nothing to do with the real expectations.
If the OS is EOL, no single tool would make it fully secure, and no user expects that.

The only exception I see here could be network related: the SSL handling.  I don't know how the SSL handshakes are handled in `winget` http client part yet, so just guessing if it would be an issue on 7.

> when even open-source projects with communal effort behind it is also doing the same thing?

That's a project (or even mindset) specific thing. Eg last two coming to my mind right now:
- [midipix](https://www.luciaillanes.de/en/projects#:~:text=environment%20for%20Windows%20XP/Server%202003%20or%20later) project (a better Cygwin) support things down to XP/2003.
- [Ziglang](https://github.com/ziglang/zig/issues/7242#issuecomment-736772022) welcomes the support for 7 too.

So it depends.

**Comment by TreeBranches** [comment]
> Partly yes. The EOL OSes usually stops being moving targets (their APIs don't change anymore). Which means the code to support them needs little changes (if any). If the code runs on 7, it runs. Things will not change here anymore.

They won't change, but the application will. It was evidently left as an "if it works, great if not, well we don't support it anyway" state.

> I take this an off-topic at the very least. With the same success I could say that anyone running w10 can run Debian or Ubuntu instead and replace winget with apt which supports everything down to [Debian 2.1](http://archive.debian.org/debian/dists/slink/).

>
> I stress that it's quite offensive to say. The UX is entirely different (both 7-vs-10 and 10-vs-Ubuntu).

Of course they can, but if the end-user wants to stick to their EOL OS for whatever reason, they can't be shocked that people are going to drop support for it.

You linking to other projects which do support them is irrelevant.

**Comment by sskras** [comment]
> They won't change, but the application will. It was evidently left as an "if it works, great if not, well we don't support it anyway" state.

Yes, but the logic that only works on 7 would not. If yes, for what reasons?

> Of course they can, but if the end-user wants to stick to their EOL OS for whatever reason, they can't be shocked that people are going to drop support for it.

We are not shocked. At least me. We are demanding.

> You linking to other projects which do support them is irrelevant.

And earlier you wrote:

    when even open-source projects with communal effort behind it is also doing the same thing?

Do you think your last statement be applied to that quote too?

**Comment by Masamune3210** [comment]
Compilers have a support list, as well as other things like code signing. Both have been removing support for older OS's. Most people do not have the time, patience, and, frankly, the inclination, to support multiple codebases just because some people want to be stubborn and use a OS that lost general support years ago, and has been EOL for almost 4 months now.

**Comment by denelon** [comment]
Sometimes, it's not about being stubborn. I know of a few cases with highly regulated industries or special purpose hardware using older OSs can't easily be updated. If there is enough of a business case to invest in "legacy" technologies vs. the forklift update scenario, that's what needs to be done. 

Unfortunately, we aren't in a position with enough business justification to apply our limited resources to support older versions of the OS, but there might be value in forking the project and seeing what can be done to muscle through a problem by a determined community.

**Comment by erkinalp** [comment]
@denelon Would you accept if a third party backport is offered in a pull request?

**Comment by denelon** [comment]
I believe this could be a reasonable option. The real concern here is the statement on support, and the risk of future changes we make potentially breaking an older OS that we don't test or certify. Any SKU of Windows that we "support" would be a limitation of what we're able to maintain. I'll need to discuss this with a few other internal folks to determine if it makes sense.
