### ISSUE TITLE
winget upgrade should have the option to hide packages with Unknown version from output

### ISSUE THREAD

**Issue by MrBeeMovie** [microsoft/winget-cli#1692]
### Description of the new feature / enhancement

winget upgrade currently shows packages with a version of Unknown as being out of date. Since the version is Unknown the package may or may not be out of date. It would be useful to have the option to hide packages with an Unknown version or allow for the option to list only unknown packages with the upgrade command defaulting to not showing these Unknown version packages.

### Proposed technical implementation details

No suggestion.

**Comment by jedieaston** [comment]
Maybe this should just be a argument, `--include-unknown`, which enables unknown packages to be upgraded? By default if `winget upgrade` finds a installed app that doesn't publish version info to the ARP table it won't attempt an upgrade.

Wouldn't be too hard to implement if there's agreement.

**Comment by MrBeeMovie** [comment]
> Maybe this should just be a argument, `--include-unknown`, which enables unknown packages to be upgraded? By default if `winget upgrade` finds a installed app that doesn't publish version info to the ARP table it won't attempt an upgrade.
> 
> Wouldn't be too hard to implement if there's agreement.

I would be fine with this solution.

**Comment by felipecrs** [comment]
I even think that by default such packages should be ignored on `winget upgrade --all`, but still shown on `winget upgrade` so that the user is at least aware of it.

**Comment by jedieaston** [comment]
Perhaps a setting? I would (personally) prefer winget not to show unknown version apps in the upgrade table by default, since 99/100 times "Unknown" ends up meaning "It updates itself", but I can understand that some people may think differently. 

It also may be a confusing user experience for a app to be listed for upgrade, then when the user wants to upgrade it and runs `winget upgrade --all` as they usually would, it doesn't get upgraded since they didn't pass the additional option. A setting that tells winget to use the current behavior (when in doubt, upgrade) that is enforced for both flows would make a little more sense to me.

**Comment by MrBeeMovie** [comment]
> I even think that by default such packages should be ignored on `winget upgrade --all`, but still shown on `winget upgrade` so that the user is at least aware of it.

I disagree since the point of `winget upgrade` is to see a list of packages that have available updates. If the version is "Unknown" it is not certain whether it has an available update or not. In regards to whether or not the user should be aware, they can use the `--include-unknown` flag mentioned by @jedieaston if they wish to know about these packages.

**Comment by felipecrs** [comment]
I mean like a third column:

```console
$ winget upgrade
Name         Id            Version Available  Source Auto-update   
----------------------------------------------------------
balenaEtcher Balena.Etcher 1.7.0   1.7.1      winget true
GOG GALAXY   GOG.Galaxy    Unknown 2.0.43.71a winget false
```

Then:

```console
$ winget upgrade --all
Found balenaEtcher [Balena.Etcher] Version 1.7.1
[...]
```

**Comment by felipecrs** [comment]
> `--include-unknown`

Is cool for me too.

**Comment by jedieaston** [comment]
--include-unknown is now in the initial 1.3 preview, available in GitHub Releases:
```
PS C:\Windows\system32> winget install WinDirStat
Found WinDirStat [WinDirStat.WinDirStat] Version 1.1.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://sourceforge.net/projects/windirstat/files/windirstat/1.1.2%20installer%20re-release%20%28more%20languages%21%29/windirstat1_1_2_setup.exe/download
  ██████████████████████████████   630 KB /  630 KB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\Windows\system32> winget upgrade
Name           Id              Version     Available    Source
--------------------------------------------------------------
Microsoft Edge Microsoft.Edge  92.0.902.67 98.0.1108.50 winget
calibre        calibre.calibre 4.16.0      5.36.0       winget
2 upgrades available.
1 package has a version number that cannot be determined. Use "--include-unknown" to see all results.
PS C:\Windows\system32> winget upgrade --include-unknown
Name           Id                    Version     Available    Source
--------------------------------------------------------------------
Microsoft Edge Microsoft.Edge        92.0.902.67 98.0.1108.50 winget
WinDirStat     WinDirStat.WinDirStat Unknown     1.1.2        winget
calibre        calibre.calibre       4.16.0      5.36.0       winget
3 upgrades available.
PS C:\Windows\system32>

```

Do you feel like this resolves the issue, or do we still need a setting?

**Comment by MrBeeMovie** [comment]
> --include-unknown is now in the initial 1.3 preview, available in GitHub Releases:
> 
> ```
> PS C:\Windows\system32> winget install WinDirStat
> Found WinDirStat [WinDirStat.WinDirStat] Version 1.1.2
> This application is licensed to you by its owner.
> Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
> Downloading https://sourceforge.net/projects/windirstat/files/windirstat/1.1.2%20installer%20re-release%20%28more%20languages%21%29/windirstat1_1_2_setup.exe/download
>   ██████████████████████████████   630 KB /  630 KB
> Successfully verified installer hash
> Starting package install...
> Successfully installed
> PS C:\Windows\system32> winget upgrade
> Name           Id              Version     Available    Source
> --------------------------------------------------------------
> Microsoft Edge Microsoft.Edge  92.0.902.67 98.0.1108.50 winget
> calibre        calibre.calibre 4.16.0      5.36.0       winget
> 2 upgrades available.
> 1 package has a version number that cannot be determined. Use "--include-unknown" to see all results.
> PS C:\Windows\system32> winget upgrade --include-unknown
> Name           Id                    Version     Available    Source
> --------------------------------------------------------------------
> Microsoft Edge Microsoft.Edge        92.0.902.67 98.0.1108.50 winget
> WinDirStat     WinDirStat.WinDirStat Unknown     1.1.2        winget
> calibre        calibre.calibre       4.16.0      5.36.0       winget
> 3 upgrades available.
> PS C:\Windows\system32>
> ```
> 
> Do you feel like this resolves the issue, or do we still need a setting?

This is great!!! Thank you! You guys are doing amazing work!!!!
