### ISSUE TITLE
Some package installed by winget are not marked by winget anymore

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-cli#1704]
### Brief description of your issue

I installed many packages via winget and then when I launched the winget list command I checked some packages source are not belong to winget anymore. 

### Steps to reproduce

the steps are simple:
1. I installed some packages via winget install
2. I typed winget list
3. I checked some packages source with winget list command on the right side are not belonged to winget anymore. 

### Expected behavior

if Installed packages via winget. the source should be marked as a winget. 

### Actual behavior

multiples packages source are not belong to winget. 

### Environment

```shell
winget version v1.1.12653
```

**Comment by denelon** [comment]
Can you provide a couple of examples?

The output from list displays packages sources when an upgrade is available.

We have an enhancement on the backlog to improve this:  #1155

**Comment by dtantono** [comment]
there are few packages like:
1. winget install --id=Logitech.Options  -e
2. winget install --id=OBSProject.OBSStudio  -e
3. winget install --id=WinDirStat.WinDirStat  -e
4. winget install --id=BraveSoftware.BraveBrowser  -e
etc
So, when I install these packages. I checked it on winget list especially source column. it is not part of winget anymore. Any thoughts about this?

**Comment by denelon** [comment]
I think it's an unclear UX related to the output from `winget list`. The "Available" and "Source" columns get populated when an upgrade is detected as available. We've recently added some additional logic to record which packages have been installed, but the display from "list" doesn't show when a package is available in a source if no available upgrade is detected.

**Comment by keentext** [comment]
yep, and windows 11 is shipping with a broken product by default.  

the more time passes, the worst windows and microsoft software becomes.

**Comment by vedantmgoyal2009** [comment]
@keentext kindly learn to respect one's work.

**Comment by keentext** [comment]
> @keentext kindly learn to respect one's work.

we wouldn't need respect if we had a great product

**Comment by Trenly** [comment]
https://github.com/microsoft/winget-cli/blob/73d35a20097f1c1efc243c2aa87ba377f65eaf2e/CODE_OF_CONDUCT.md

**Comment by vedantmgoyal2009** [comment]
More specifically: https://opensource.microsoft.com/codeofconduct/#:~:text=Trolling%2C%20insulting%20or%20derogatory%20comments%2C%20and%20personal%20or%20political%20attacks

**Comment by Masamune3210** [comment]
Just stop feeding them, all it does it make it worse unfortunately. You can't reason with someone determined to not listen

**Comment by ItzLevvie** [comment]
Not to mention that these are all sock puppet accounts created within a month or two ago (with similar biography):
- https://github.com/CharlotteEm
- https://github.com/JennyStig
- https://github.com/ShanConn
- https://github.com/keenbowl3009
- https://github.com/keentext

**Comment by denelon** [comment]
I'm closing this issue in favor of:
* #1155
