### ISSUE TITLE
didn't refresh current version info after 'winget upgrade xxx'

### ISSUE THREAD

**Issue by wowpaladin111** [microsoft/winget-cli#1706]
### Brief description of your issue

After using winget upgrade command to upgrade some software, the current version info remains the old one but didn't refresh.

### Steps to reproduce

winget list
winget upgrade xxx
winget list xxx

### Expected behavior

current version number should be upgraded.

### Actual behavior

didn't refresh

### Environment

```shell
Windows Package Manager v1.1.12663
Windows: Windows.Desktop v10.0.22000.318
Microsoft.DesktopAppInstaller v1.16.12663.0
```

**Comment by denelon** [comment]
Can you share some specific examples?

**Comment by wowpaladin111** [comment]
It seemed that some apps such as Wechat didn't refresh the version number in Windows' application settings. Not an issue of winget.
Please ignore and close the thread. Thanks.
