### ISSUE TITLE
Confusion about versions

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [microsoft/winget-cli#1723]
I am trying to install Python 3.7. If I search I get the following

```
PS C:\Users\Luke> winget search "python 3" --source winget
Name               Id                     Version    Source
-------------------------------------------------------------
Python 3           Python.Python.3        3.10.150.0 winget
IronPython 3       Microsoft.IronPython.3 3.4.0.0001 winget
```

I only see an option for Python 3.10, but I see the version I want is located in winget-pkgs [here](https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/Python/Python/3/3.7.9150.0).

Isn't winget-pkgs the default source listed as `winget` in the output above? If it is, why do all the Python versions listed therein not show in a search?

**Comment by ItzLevvie** [comment]
`winget search` will only show the latest version of a package.

`winget install Python.Python.3 --version 3.7.9150.0` should allow you to install the version you want.

You can see all versions of Python 3 by doing `winget show Python.Python.3 --versions`.

**Comment by Anti-Distinctlyminty** [comment]
Thank you for the rapid response @ItzLevvie. It didn't occur to me that `winget search` was not the place to find versions. In my head, `winget search` was the tool that allows you to whittle down the possibilities to find parameters to use with `winget install`. I may be in the minority.

**Comment by NicTanghe** [comment]
Annyway to make winget not update a package ?

**Comment by Masamune3210** [comment]
Not yet. Pinning a package is being worked on though
