### ISSUE TITLE
Some winget commands are not recognised after updating to Windows 10 21H2

### ISSUE THREAD

**Issue by ksdc-vaughann** [microsoft/winget-cli#1729]
### Brief description of your issue

Some winget commands, such as --upgrade, --list, --features, are not recognised after updating to Windows 10 21H2. winget --version works as expected.

### Steps to reproduce

Type "winget --upgrade" and press enter.

### Expected behavior

The app should scan installed packages and list those for which an update is available.

### Actual behavior

Receive the following error "Argument name was not recognized for the current command : '--upgrade'".

### Environment

```shell
Windows Package Manager v1.1.12986
Windows: Windows.Desktop v10.0.19044.1348
Package: Microsoft.DesktopAppInstaller v1.16.12986.0
```

**Comment by OfficialEsco** [comment]
The commands are
```
winget install
winget show
winget source
winget search
winget list
winget upgrade
winget uninstall
winget hash
winget validate
winget settings
winget features
winget export
winget import
winget --version or -v
winget --info
```

**Comment by ksdc-vaughann** [comment]
Sorry about that, I was using the incorrect commands.
