### ISSUE TITLE
winget upgrade --all failed to upgrade some apps

### ISSUE THREAD

**Issue by xarthurx** [microsoft/winget-cli#1730]
### Brief description of your issue

I've encountered this issue several times but cannot remember the cases before.
The recent one is `Quicklook`.

![image](https://user-images.githubusercontent.com/1921878/142592020-33b9b308-9fab-42ff-a1bb-54a4c3faf820.png)
 (there is an '--all' in the second command)

### Steps to reproduce

`winget upgrade --all`

or

`winget upgrade --id  QL-Win.QuickLook`

### Expected behavior

`Quicklook` is updated.

### Actual behavior

Nothing happened.

### Environment

```shell
Windows Package Manager v1.1.12986
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.318
Package: Microsoft.DesktopAppInstaller v1.16.12986.0
```

**Comment by OfficialEsco** [comment]
Do winget --info to get to the log folder (probably `%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir`) and read the second to last log

**Comment by xarthurx** [comment]
```
2021-11-19 14:15:20.755 [REPO] Downloading manifest
2021-11-19 14:15:20.755 [CORE] WinINet downloading from url: https://winget.azureedge.net/cache/manifests/q/QL-Win/QuickLook/3.7.1.0/59e5-QL-Win.QuickLook.yaml
2021-11-19 14:15:20.764 [CORE] Download hash: 1a429374891cd35cefbd24c69bffe7ab19a8b871c65f8c9da6024b40b7195a28
2021-11-19 14:15:20.764 [CORE] Download completed.
2021-11-19 14:15:20.765 [CLI ] Starting installer selection.
2021-11-19 14:15:20.765 [CLI ] Installer [X64,Msi,User,] not applicable: Installer scope does not matched currently installed scope: User != Machine
```

**Comment by OfficialEsco** [comment]
You've somehow installed it machine-wide, did you manually install it to somewhere else?
I've triple checked the installer, the default installation location is `C:\Users\WDAGUtilityAccount\AppData\Local\Programs\QuickLook\`, so for this to trigger as machine-wide i'm guessing you selected `C:\Program Files\`?

If so, this might be a oversight that i don't think is a simple fix, UNLESS we remove the scopes from any installer that does not prompt for user/machine permissions

**Comment by xarthurx** [comment]
Thank you for the quick response.
I've uninstalled it and re-install it with `winget`.
Seems fine now, I'm closing this issue and will re-open it if future issue emerges.
