### ISSUE TITLE
Adobe Acrobat Reader DC cannot be installed

### ISSUE THREAD

**Issue by cheesecracker** [microsoft/winget-cli#1735]
### Brief description of your issue

I tried to use winget to install Adobe Acrobat Reader DC a few days ago but it failed.  And it's still not working toady.

### Steps to reproduce

I typed the following command (which is the "officially recommended" command by https://winget.run/pkg/Adobe/AdobeAcrobatReaderDC)
winget install -e --id Adobe.AdobeAcrobatReaderDC

### Expected behavior

Adobe Acrobat Reader DC got installed

### Actual behavior

Nothing is installed.  Instead, there is this message:
No package found matching input criteria.

### Environment

```shell
Windows Package Manager v1.1.12986
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1348
Package: Microsoft.DesktopAppInstaller v1.16.12986.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by OfficialEsco** [comment]
Your issue is with https://winget.run / https://github.com/winget-run. Not winget.

```
PS C:\Users\Esco> winget search adobe
Name                      Id                          Version      Match
-----------------------------------------------------------------------------
Avocode                   Avocode.Avocode             4.15.1       Tag: adobe
Adobe Acrobat Reader DC   Adobe.Acrobat.Reader.32-bit 21.007.20099 Tag: adobe
Adobe Acrobat DC (64-bit) Adobe.Acrobat.Reader.64-bit 21.007.20099 Tag: adobe
Cryptr                    Adobe.Cryptr                0.5.0
Brackets                  Adobe.Brackets              1.14.17770
```

The ID's are now `Adobe.Acrobat.Reader.32-bit` and `Adobe.Acrobat.Reader.64-bit` because Adobe don't use the same PackageName/Publisher for their x86 and x64 software.

x64:
```
Publisher: Adobe
PackageName: Adobe Acrobat DC
```

x86:
```
Publisher: Adobe Systems Incorporated
PackageName: Adobe Acrobat Reader DC
```

Please use the official search instead of a outdated 3rd party site.

**Comment by cheesecracker** [comment]
OK, thanks for the new ID.

What is the official search?  Where is it?
I hope you are not talking about "winget search" command.  I mean, come on, we live in the 2020's already.  Things are on the web and it's intuitive.  People would use web tool 99 times out of 100.  Using this **archaic** method is not very up-to-date.

**Comment by ItzLevvie** [comment]
> OK, thanks for the new ID.
> 
> What is the official search? Where is it? I hope you are not talking about "winget search" command. I mean, come on, we live in the 2020's already. Things are on the web and it's intuitive. People would use web tool 99 times out of 100. Using this **archaic** method is not very up-to-date.

Someone has created a third-party website for it: https://winstall.app
