### ISSUE TITLE
Rename to "winpkg"

### ISSUE THREAD

**Issue by Zachary-Rude** [microsoft/winget-cli#1739]
### Description of the new feature / enhancement

Hi, [Microsoft](https://github.com/microsoft)!

I'm glad that you've made an official Windows package manager.

I'm writing this issue because I'm not happy with the program's name. I would _really_ like it if you would rename WinGet to WinPKG.

### Proposed technical implementation details

Here's why I think you should rename WinGet:

A few months ago, I tried to make a [Chromebrew](https://github.com/skycocker/chromebrew) alternative for Chromebooks (that is a fork of Crew), known as [Chromepkg](https://github.com/Zachary-Rude/chromepkg). Sadly, CrPKG failed to work on my Chromebook (even though Crew still works). After that epic fail, CrPKG had been discontinued, and the very few Chromebook users who once used and loved CrPKG should now migrate to Chromebrew or an alternative package manager that still works.

Shortly before I wrote this issue, I had tried (or rather wanted) to make a Windows package manager, named WinPKG (in honor of CrPKG), but I had forgot about WinGet. As far as I currently know as of the time I wrote the issue, various Windows package managers exist, none of them called WinPKG. Ever since CrPKG's shutdown I have dreamt of a package manager known as WinPKG, so just rename WinGet to WinPKG, and I will be happy!

EDIT: CrPKG now works properly, so it is no longer discontinued.

---

Sadly, my signature was eaten by [an evil kumquat](https://en.scratch-wiki.info/wiki/Evil_Kumquat).

**Comment by sredna** [comment]
I would assume it is too late to rename it now. All documentation would have to change, all web links, Github change etc. They would have to maintain a winget.exe alias so they don't break automated scripts.

Even if it is not too late, WinGet is (IMHO) more of a "getter" than a real package manager with proper dependency tracking.

**Comment by Masamune3210** [comment]
To be fair, dependency support is being worked on but yeah I agree, definitely not worth changing the name this far in

**Comment by denelon** [comment]
@Zachary-Rude

Early on, we had plenty of discussions about naming the product. One of the things I did during that phase was to create a .bat file that simply called the `winget` tool and passed the parameters so I could see what typing proposed names looked and felt like. Maybe something like that would be a simple workaround to allow you to type `WinPKG` 😁

I hope the evil kumquat gets indigestion.

**Comment by masterflitzer** [comment]
@Zachary-Rude you can create a powershell alias, add this to your profile.ps1: `New-Alias winpkg winget`
