### ISSUE TITLE
Issue with pip after installing python

### ISSUE THREAD

**Issue by keentext** [microsoft/winget-cli#1745]
### Brief description of your issue

python is broken. 
when I install things through pip, the packages are not visible to terminal, to the os, they are not in path, and in general it's guaranteed you'll have an awful experience on windows especially if you rely on winget/windows store to get things. 

for example, after "winget install python; winget search youtube-dl; pip install youtube-dl; youtube-dl --version" says that pip is not installed. 

winget and the windows store are the flagship features that demonstrate how microsoft products are always broken, poorly implemented, and designed to increase frustration and to make user's and developer's life more difficult. 

### Steps to reproduce

winget install python; winget search youtube-dl; pip install youtube-dl; youtube-dl --version

### Expected behavior

everything should just work when things are installed through the system official package manager. 

### Actual behavior

windows has the windows store, has the stupid winget crap, all these are incompatible, and each offers half of the other product features, and either one of those will cause frustration and things will be broken and not working. 

### Environment

```shell
Windows: Windows.Desktop v10.0.22000.348
Package: Microsoft.DesktopAppInstaller v1.16.12986.0
```

**Comment by keentext** [comment]
Years people are complaining that winget does not support zip packages, and recently I've been starting to test winget because it got bundled with windows 11, and the more I try this, the more I truly and deeply hate microsoft products and the entire windows/microsoft ecosystem. 

every single microsoft product is always broken and badly designed like winget. https://github.com/microsoft/winget-cli/issues/1681

**Comment by keentext** [comment]
Scoop, for example https://github.com/ScoopInstaller/Scoop/issues/451, has clear criterias of making sure that no packages submitted are broken and that things work together. Microsoft spent years on winget, stole someone's idea, and will now bundle winget with windows and we'll be forced to have a shitty product instead of quality and properly maintaned software.

**Comment by vedantmgoyal2009** [comment]
@keentext if you don't like Microsoft or windows, just switch to macOS or Linux, but stop criticizing someone's work. And yes, you have better ideas, then just make your own package manager and use it. 

Also, please stop showing your frustration on the repository.

> ![image](https://user-images.githubusercontent.com/83997633/143464107-2f8dd7ff-8bc2-47e3-bbe5-1a207be27703.png)

**Comment by keentext** [comment]
> @keentext if you don't like Microsoft or windows, just switch to macOS or Linux, but stop criticizing someone's work. And yes, you have better ideas, then just make your own package manager and use it.
> 
> Also, please stop showing your frustration on the repository.
> 
> > ![image](https://user-images.githubusercontent.com/83997633/143464107-2f8dd7ff-8bc2-47e3-bbe5-1a207be27703.png)

we know for a fact that winget was rushed, and that v1 was released with uninstalling broken so that it could be bundled with win 11. these kind of practices should not be respected; pushing broken rushed products into users only makes the user's experience worse, and the only people happy in the end are the msft employees who got their bonuses.

**Comment by vedantmgoyal2009** [comment]
Everyone's opinion is different but still, you need to follow the code of conduct: https://opensource.microsoft.com/codeofconduct/#:~:text=Trolling%2C%20insulting%20or%20derogatory%20comments%2C%20and%20personal%20or%20political%20attacks

**Comment by denelon** [comment]
@keentext,

The steps to reproduce are mixing technology stacks. It's also not clear which version of python was installed from which source. Was the python installed from the Microsoft Store, or the community catalog? There are differences between the two packages installers, and subsequently the installed behavior. This may be affecting what you are experiencing with pip.
