### ISSUE TITLE
Provide a way to opt-out from preview flight

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/winget-cli#1746]
### Description of the new feature / enhancement

Many months ago, I signed up for the preview flight of winget via the link in the README here in the repo. At this point I no longer want to be part of the preview flight, but instead get the same version of everything that "normal" users get that haven't signed up.  I would like to have some way to opt-out from the preview flight.

### Proposed technical implementation details

Maybe just another web form where I can submit my MSA email address to be removed from the preview flight?

**Comment by ItzLevvie** [comment]
Duplicate of https://github.com/microsoft/winget-cli/discussions/866#discussioncomment-611421.

**Comment by ItzLevvie** [comment]
Duplicate of https://github.com/microsoft/winget-cli/discussions/866.

**Comment by denelon** [comment]
Duplicate of #866
