### ISSUE TITLE
Fork software need to re-setup everything a new install is made

### ISSUE THREAD

**Issue by xarthurx** [microsoft/winget-cli#1747]
### Brief description of your issue

When installing the software "Fork" (a git client) through winget, everything there's a new version released and installed, user settings will be overwritten and I need to setup everything again.

### Steps to reproduce

1. Install `Fork`
2. Setup fork
2. Wait for a new version release
2. Install the new version

### Expected behavior

The newly installed version should inherit the original user settings.

### Actual behavior

user settings are overwritten and not respected.

### Environment

```shell
Windows Package Manager v1.1.12986
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.318
Package: Microsoft.DesktopAppInstaller v1.16.12986.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by xarthurx** [comment]
The settings should exist in `~\AppData\Local\Fork`

**Comment by jedieaston** [comment]
This looks (although I'm not 100% certain) to be a bug with Fork's installer (or intentional behavior, since if you're re-running the installer it may be that your local install is borked). 

I'd suggest reaching out to them and asking them to add an argument to their installer that disables this behavior (`/upgrade`, perhaps?). Maybe there already is such an option and it just isn't documented, I tried to get their installer to list the options and it wouldn't.

**Comment by xarthurx** [comment]
Would you do this (feature request)?
I don't 100% understand the specific feature to request.

Thank you.

**Comment by jedieaston** [comment]
Done :)

#1748.

**Comment by denelon** [comment]
@xarthurx,

I've linked a couple of related issues to #1748. I'm going to go ahead and close this issue since we've captured the work in other feature requests.

**Comment by BentramLawrence** [comment]
everyone hates winget, extremely frustrating and wastes your time
