### ISSUE TITLE
Provide a way to opt-out for updating on package manifest

### ISSUE THREAD

**Issue by felipecrs** [microsoft/winget-cli#1749]
### Description of the new feature / enhancement

Some programs does not fill the version in "Programs and Resources" correctly, like GOG Galaxy. Thus, when running `winget upgrade`, it wrongly detects that a new version is available.

I submitted a support ticket to them asking to fix this issue a very long while ago, and I didn't receive any response.

### Proposed technical implementation details

It would be cool if we could set in the package manifest that update should not be offered, as a measure to deal with such cases.

**Comment by felipecrs** [comment]
Or, perhaps even better, in such cases, winget should NOT try to update the program on `winget upgrade --all`.

**Comment by jedieaston** [comment]
Would you be okay with the solution I proposed in https://github.com/microsoft/winget-cli/issues/1692? It doesn't set a universal "don't upgrade these list", but for things like GOG (no ARP table version number) it would be an easy fix.

**Comment by felipecrs** [comment]
Definitely. Closing this. Thank you!
