### ISSUE TITLE
Factor out a library from winget-cli so that bindings in other languages can be written

### ISSUE THREAD

**Issue by arsdragonfly** [microsoft/winget-cli#1756]
### Description of the new feature / enhancement

It's common[[1]](https://github.com/rpm-software-management/libdnf)[[2]](https://github.com/Debian/apt) for package managers to be built in a way such that the command-line interface sits on top of a core library. The core library would have an API interface that is used both by the official command-line tool and other tools written in possibly different languages (e.g. a python tool that makes use of the python-apt bindings to maintain packages installed by apt)

**Comment by denelon** [comment]
We're currently working to move the functionality into the COM interface. This work is in progress but is not yet completed. We are also working on providing a sample tool leveraging the COM interface.

**Comment by denelon** [comment]
I'm not sure it's going to be able to support the use case suggested here in terms of managing packages for other languages/toolchains, but it's an interesting idea.

**Comment by arsdragonfly** [comment]
Yes, COM interface would allow interoperability from other languages/toolchains.

**Comment by denelon** [comment]
We have continued adding commands to the COM interface, and we've added a sample project to show how to integrate with the COM API.
