### ISSUE TITLE
Import command option to not upgrade installed packages

### ISSUE THREAD

**Issue by jpawlowski** [microsoft/winget-cli#1763]
### Description of the new feature / enhancement

`winget import` currently will also install newer versions of packages that are already installed.

There shall be the option to ignore packages that are already installed on the system, no matter the version. This will safe a lot of time when one just wants to install any missing software and not mix this up with upgrades.

### Proposed technical implementation details

Implement a command line option `--ignore-installed` to skip re-installing(=upgrading) a package.

**Comment by jedieaston** [comment]
Related: https://github.com/microsoft/winget-cli/issues/929

**Comment by Trenly** [comment]
@denelon - #2655

**Comment by denelon** [comment]
@Trenly did this make it into 1.4 Release Candidate (2)?

**Comment by Trenly** [comment]
> @Trenly did this make it into 1.4 Release Candidate (2)?

![image](https://user-images.githubusercontent.com/12611259/212379825-3c2fce62-8fbe-47a8-bb86-5d279def72e4.png)
