### ISSUE TITLE
Enumurate on multiple match found and acept user input

### ISSUE THREAD

**Issue by NicTanghe** [microsoft/winget-cli#1767]
### Description of the new feature / enhancement

Hello currently when multiple matches are found they are not enumurated and user input is not requested.

Coming from arch and having dyslectia i can tell you that ginving a number saves allot of time.

If a screenshot of yay -S is required I`ll add one later.

### Proposed technical implementation details

```

to_install =   possible_matches[int.user_input()]

winget install $to_install

**Comment by jedieaston** [comment]
Duplicate of #1620.
