### ISSUE TITLE
Cache downloads

### ISSUE THREAD

**Issue by sirinath** [microsoft/winget-cli#1771]
### Description of the new feature / enhancement

Cache downloads for future use so they don't need to redownload.

**Comment by jedieaston** [comment]
They are already being cached, if your temp folder isn’t being cleared, repeated runs of `winget install` will reuse the previous download if the SHA256 hash matches.

**Comment by denelon** [comment]
As @Jedieaston stated, the downloads are already cached for subsequent installs.
