### ISSUE TITLE
Add installation option to prefer machine scope

### ISSUE THREAD

**Issue by sirinath** [microsoft/winget-cli#1772]
### Description of the new feature / enhancement

Add an option to prefer machine scope and fall back to user scope if it is not applicable. e.g. `--scope machine user` try machine 1st and failing try user.

**Comment by jedieaston** [comment]
This can be achieved via setting the installBehavior.preferences.scope setting to machine. (I know that’s more permanent than you want, but just letting you know). 

https://docs.microsoft.com/en-us/windows/package-manager/winget/settings#scope

**Comment by denelon** [comment]
The default behavior is "user" if both are available in the manifest. If you specify the scope via the command line, and the scope is available, it will be installed. If the scope is not available, it will not be installed. You may also specify a preference, or a requirement in settings. Preferences will be honored if they can be but may continue if another option is available while requirements will behave the same way as the command line options.
