### ISSUE TITLE
winget command tool is NOT installed by installing "App Installer" in Microsoft Store

### ISSUE THREAD

**Issue by cheesecracker** [microsoft/winget-cli#1793]
### Brief description of your issue

I install "App Installer" in Microsoft Store.  But typing "winget" in PowerShell still shows that the term 'winget' is not recognized.

### Steps to reproduce

1. Install Windows 10 from scratch (I use Microsoft's official ISO image: SW_DVD9_Win_Pro_10_21H2_64BIT_Eng_Intl_Pro_Ent_EDU_N_MLF_X22-83626.ISO)
2. Open Microsoft Store
3. Search App Installer
4. Install it
5. Open PowerShell (in elevated mode) and try to run "winget"

### Expected behavior

Expected to get the blah blah blah about winget command tool

### Actual behavior

```
winget : The term 'winget' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ winget
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (winget:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Environment

No "winget --info" can be provided because it's NOT installed

winver ==> "Version 21H2 (OS Build 19044.1288)

### Comment
When App Installer is installed by Microsoft Store *for the first time*, winget does not work.  We have to wait for an undetermined amount time and *suddenly* Microsoft Store would say it has found some update for App Installer.  Then we have to wait for about 15 minutes to let Microsoft Store to download and install (again?) App Installer.  After this, winget works.

Something is very obscure in the relationship between App Installer and Microsoft Store.
```

**Comment by o-l-a-v** [comment]
What version of "App Installer" do you have? Mine says 1.16.13405.0 when running:

```powershell
(Get-AppxPackage -Name 'Microsoft.DesktopAppInstaller').'Version'
```

(WIN + R => "powershell" and press enter, then ^)

**Comment by juner** [comment]
Is `winget.exe` set to `ON` in `app execution aliases`? 

[How to Manage App Execution Aliases in Windows 10](https://www.tenforums.com/tutorials/102096-manage-app-execution-aliases-windows-10-a.html)

**Comment by cheesecracker** [comment]
In reply to @o-l-a-v 

Hope my answer is human-readable :)

### O/S just installed (ie _even before_ Microsoft Store was ever opened for the 1st time)
* `(Get-AppxPackage -Name 'Microsoft.DesktopAppInstaller').'Version'`
  gives 1.0.30251.0
* Optionally, the command "winget" gives the same error as in my original post.
* In  `%LOCALAPPDATA%\Microsoft\WindowsApps`  , no winget.exe
* `pushd "%ProgramW6432%\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe"`
  "AppInstallerCLI.exe" is **not** there
* `Set-Location -Path ('{0}\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe' -f $env:ProgramW6432)`
 `Test-Path -Path '.\AppInstallerCLI.exe'`
  Returns False

### Open Microsoft Store for the _first time_.  Verified that "App Installer" is _indicated as installed_ in Microsoft Store
* `(Get-AppxPackage -Name 'Microsoft.DesktopAppInstaller').'Version'`
  gives 1.0.30251.0 (same result like above)
* Optional: try "winget" == same result
* In  `%LOCALAPPDATA%\Microsoft\WindowsApps`  , **still** no winget.exe
* `pushd "%ProgramW6432%\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe"`
  "AppInstallerCLI.exe" is not **still** there
* `Set-Location -Path ('{0}\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe' -f $env:ProgramW6432)`
   `Test-Path -Path '.\AppInstallerCLI.exe'`
  **Still** returns False

### Open "App Installer" again in Microsoft Store and wait for it to update this app (and it really takes ages...)
* `(Get-AppxPackage -Name 'Microsoft.DesktopAppInstaller').'Version'`
  gives 1.16.13405.0
* Optional: try "winget" == gives expected result (those blah blah blah)
* In  `%LOCALAPPDATA%\Microsoft\WindowsApps`  , winget.exe is finally there!
* `pushd "%ProgramW6432%\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe"`
  A **LOT** of files are added in that folder!  Amongst them, "AppInstallerCLI.exe"!
* `Set-Location -Path ('{0}\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe' -f $env:ProgramW6432)`
  `Test-Path -Path '.\AppInstallerCLI.exe'`
  Returns True

**Comment by cheesecracker** [comment]
> Is `winget.exe` set to `ON` in `app execution aliases`?
> 
> [How to Manage App Execution Aliases in Windows 10](https://www.tenforums.com/tutorials/102096-manage-app-execution-aliases-windows-10-a.html)

**BEFORE** update in Microsoft Store
  Only pythonxx.exe are in the list (and all are set to ON)

**AFTER** update in Microsoft Store
  winget.exe is also in the list (and it's set to ON)

**Comment by denelon** [comment]
The version of App Installer coming in the Windows 10 distribution is the original version that shipped with Windows 10. It does take time for everything to synchronize and for the store to determine an update is available. Once you have the most recent version of App Installer on the system. The Windows Package Manager is available. This also holds true for Windows 11. We are working to be a part of the original distribution for the next update to Windows 11 so the Windows Package Manager can be present before getting an updated App Installer.

**Comment by jazzdelightsme** [comment]
> It does take time for everything to synchronize and for the store to determine an update is available.

FYI: It is possible to write some script code to programmatically (and synchronously) trigger those updates: https://github.com/microsoft/winget-cli/discussions/1738#discussioncomment-5484927

**Comment by cheesecracker** [comment]
> FYI: It is possible to write some script code to programmatically (and synchronously) trigger those updates: [#1738 (reply in thread)](https://github.com/microsoft/winget-cli/discussions/1738#discussioncomment-5484927)

I agree.  Automation is **good**.  But we need to wait for an undetermined period of time.  Being able to trigger those things is even **better**.

**Comment by beingmerry** [comment]
I continue to have this issue on Windows 10 22H2. Winget is showing in the correct location `%LOCALAPPDATA%\Microsoft\WindowsApps` and the app alias is `ON` but I still cannot access winget from the CLI.
![image](https://github.com/microsoft/winget-cli/assets/11280134/18564a7e-15b2-4f71-b94a-3c790cef9a00)

**Comment by yeskiy** [comment]
For those, who can't really find a solution for that.

1. Check, that `winget.exe` is located in `%LOCALAPPDATA%\Microsoft\WindowsApps`
2. search `path` in your windows search (you should open `Edit enviroment variables in your computer` and hit `Enviroment Variables...` button)
3. Find `Path` or `PATH` item in `User variables for [name]` and double-click on that
4. Click `New`
5. type `%LOCALAPPDATA%\Microsoft\WindowsApps` and hit `Enter` on your keyboard
6. Restart a pc (or use `refreshenv` if you have `choco`)
7. Success (Probably)
