### ISSUE TITLE
Catastrophic failure (DesktopAppInstaller UI, side-loading)

### ISSUE THREAD

**Issue by nbevans** [microsoft/winget-cli#1799]
### Brief description of your issue

Just had this with App Installer. Another "Catastrophic failure (0x8000ffff)"... tried everything, several reboots. In the end Add-AppxPackage was the only way to get the app to install.

### Steps to reproduce

Random. Seems very machine and PRNG dependent thus far.

### Expected behavior

That there is no catastrophic error.

### Actual behavior

![image](https://user-images.githubusercontent.com/542188/146035714-fa13347b-6d38-4deb-af46-7c7642003245.png)

### Environment

```shell
Screenshot shows build version of DesktopAppInstaller.
```

**Comment by denelon** [comment]
@nbevans no, this is for the Windows Package Manager distributed with the App Installer.  I'll reach out to the team to see if I can help direct this issue to the right repository.

**Comment by nbevans** [comment]
Currently there is no way to reach the maintainers of DesktopAppInstaller and that is a big problem.

Can you get them to create themselves a GitHub project - even if they only use it for Issues?

**Comment by denelon** [comment]
I believe this issue has been resolved. There have been a few updates that are App Installer related completely separate from WinGet.
