### ISSUE TITLE
winget won't hit breakpoints in Visual Studio when debugging unless debugger type is manually chosen

### ISSUE THREAD

**Issue by arsdragonfly** [microsoft/winget-cli#1804]
### Brief description of your issue

Title

### Steps to reproduce

clone and debug AppInstallerCLIPackage in AppInstallerCLI
set a breakpoint in main.cpp

### Expected behavior

the breakpoint should be hit

### Actual behavior

the breakpoint won't trigger, unless you manually go to AppInstallerCLIPackage Debug Properties, Debug -> Debugger type and set Background task process to "Desktop CLR and Native" (default is Core CLR)
![image](https://user-images.githubusercontent.com/4067473/146168206-89e9e626-0c3c-4931-b42d-c582bffcf8d4.png)

### Environment

```shell
winget latest master
Visual Studio 2019
```

**Comment by denelon** [comment]
It's been a while since this was reported. Is this still happening?
