### ISSUE TITLE
Package does not install due to the file name exceeding the maximum amount of characters

### ISSUE THREAD

**Issue by ItzLevvie** [microsoft/winget-cli#1808]
### Brief description of your issue

![image](https://user-images.githubusercontent.com/11600822/146393082-f7b98986-4417-4d7f-826d-d424edcfbef9.png)

Logs from the `DiagOutputDir` folder with `--verbose-logs`:
1) `winget validate` = https://pastebin.com/raw/NxWVKnvg
2) `winget install` = https://pastebin.com/raw/QdchskSe

### Steps to reproduce

Install the WinGet package from https://github.com/microsoft/winget-pkgs/pull/37971 

^ https://github.com/Dragon1573/winget-pkgs/tree/bf22a2a5a907bef7cf7c4d00595ede8745b7e84d/manifests/h/Huawei/HiSuite/11.0.0.580

### Expected behavior

For the WinGet package to install successfully on my PC.

### Actual behavior

Due to how weird the file name is for the installer, it has seemingly exceeded the maximum amount of characters you can write in a file name.

Perhaps if WinGet spots a file name that is too long, it should possibly truncate it to avoid this issue?

### Environment

```shell
Windows Package Manager (Preview) v1.2.3411-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22523.1000
Package: Microsoft.DesktopAppInstaller v1.17.3411.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by denelon** [comment]
That's interesting. I haven't seen one that long before. We should take a look at both the URL length and the installer name length. It would also make for a strange UAC where we try to use the installer name to help provide more clarity.

**Comment by vedantmgoyal2009** [comment]
That looks like a password generated using some program 😂
