### ISSUE TITLE
Winget install error: Package adquisition request/checkout error: storage account not found

### ISSUE THREAD

**Issue by JMoreno97** [microsoft/winget-cli#1817]
### Brief description of your issue

It's the first time I used winget. I run `winget install "Arduino IDE"` and after accept terms it throws `Package adquisition request/checkout error: storage account not found` (translation may not be exact, the error is thrown in Spanish).

### Steps to reproduce

Run  `winget install "Arduino IDE"`

### Expected behavior

Arduino IDE to be installed

### Actual behavior

It throws: `Package adquisition request/checkout error: storage account not found` and package is not installed

### Environment

```shell
Windows Package Manager (Preview) v1.2.3411-preview
Windows: Windows.Desktop v10.0.19044.1415
Paquete: Microsoft.DesktopAppInstaller v1.17.3411.0
```

**Comment by denelon** [comment]
This package appears to be coming from the "msstore" source. Is this still happening?

**Comment by JMoreno97** [comment]
> This package appears to be coming from the "msstore" source. Is this still happening?

No, now seems to be solved. Thanks!
