### ISSUE TITLE
Support for installation of portable/standalone apps

### ISSUE THREAD

**Issue by KiruyaMomochi** [microsoft/winget-cli#182]
# Description of the new feature/enhancement

There are programs like [starship](https://github.com/starship/starship/) or [aria2](https://github.com/aria2/aria2), which only provide portable *archived* files.
There maybe also some apps just releases an *standalone* .exe file.
Although we can request they to build an msi/msix package, it will be more convenient if we support to *install* them directly. 

For the portable apps, the *install* may mean extract the archive to *Program Files*, then create a [shim](https://github.com/chocolatey/shimgen)-like redirection for the program, put it into a specific directory, and add the directory to PATH.

Related: 
* https://github.com/microsoft/winget-pkgs/issues/174
* https://github.com/microsoft/winget-cli-restsource/issues/116

Edited by @denelon

**Comment by timvisee** [comment]
Yes, I'd like to see this as well. Many other tools you might use in the CLI (it is a CLI package installer after all) are provided as standalone binaries. I'd like to package [ffsend](https://github.com/timvisee/ffsend).

Existing package managers for Windows such as scoop or Chocolatey allow the installation of standalone binaries as well. Some inspiration might be taken from there.

**Comment by RobCannon** [comment]
I would love to be able to install tools like terraform, packer, kubectl, etc..  I could use scoop.sh, but I would love to have one tool to handle everything.  winget should be able to install command line tools to a common directory in the user's directory but also make sure that directory is part of the path.

**Comment by marcomorain** [comment]
I'm looking for this support to package the CircleCI CLI tool.

👍

**Comment by koppor** [comment]
This is useful for the [mob tool](https://github.com/remotemobprogramming/mob#swift-git-handover-with-mob) which is fundamental for [remote mob programming](https://www.remotemobprogramming.org/). A [release](https://github.com/remotemobprogramming/mob/releases) for windows is a single `.tar.gz` file containing a single `.exe` file.

**Comment by darrenj** [comment]
Also useful for the [ngrok](https://ngrok.com) tool for HTTP tunnelling.

**Comment by karsten3s** [comment]
To piggy back off of this, how would we go about installing applications like [https://github.com/ggreer/the_silver_searcher](url) where there will be no direct developer support for windows? There are unofficial windows builds but can those be considered?

**Comment by zubairq** [comment]
I would like to be able to package a standalone app too, Yazz Pilot which is a single .exe file. Any estimate on when this will be coming?

**Comment by ajeetdsouza** [comment]
Is there any update on this? I'd love to be able to package [zoxide](https://github.com/ajeetdsouza/zoxide/) via WinGet. Being a command-line app, it is distributed as a single binary.

This would be a very useful feature for a lot of similar apps. Note that [Scoop](https://github.com/ScoopInstaller/Main) already supports this.

**Comment by denelon** [comment]
We're targeting [milestone 18](https://github.com/microsoft/winget-cli/milestone/20) for this.

**Comment by denelon** [comment]
This looks very similar to #194.

I think they are duplicates of each other.

I believe the ask is to have the ability to download the standalone program (in the form of a .exe) and make it available via the path so that a user can "install" it and use it.

**Comment by whihathac** [comment]
Need this for nuget.exe too.

**Comment by whihathac** [comment]
Missing support for Kubernetes-CLI too - https://github.com/kubernetes/kubectl/issues/968https://github.com/kubernetes/kubectl/issues/968

**Comment by keenbowl3009** [comment]
> I think you are overreacting a bit, most people either don't care about whether their app is a portable app or not or are specifically downloading it because they need it to be portable.

I care. My use case is, "I was trying your tool to see if it works well and solves my problem, I determined it doesn't, now I want it gone like I never installed it in the first place, with no side effects.".

**Comment by denelon** [comment]
Hey all, I'm working on the specification for portable / standalone applications. I'm hoping to get through an engineering review to look for missed edge cases this week. I'll be posting the specification after that, and another PM/Security/etc... review.

**Comment by denelon** [comment]
Note: This will not include compressed files like an .exe inside of a .zip. I want to get this specification completed before moving on to the more complex set of edge cases for compressed files containing portable / standalone executables or other "nested" installers.

**Comment by denelon** [comment]
Discussion at: https://github.com/microsoft/winget-cli/discussions/1887

**Comment by bc3tech** [comment]
🎉 could you link us to the docs on how to develop for/use it? Thanks!

**Comment by bc3tech** [comment]
fair enough, thanks for the context! I'm happy to await broader rollout as well :)

**Comment by scottwillmoore** [comment]
Is there any roadmap (or tracking issue, should I create one?) to add start menu entries for portable applications? This appears to be discussed as [future considerations](https://github.com/microsoft/winget-cli/blob/master/doc/specs/%23182%20-%20Support%20for%20installation%20of%20portable%20standalone%20apps.md#future-considerations) in the specification. I don't think it would add much complication, as I don't believe there are many edge cases (at least in the context of portable applications). It would be really nice for portable GUI applications to appear in the start/search menu.

**Comment by denelon** [comment]
@scottwillmoore

Feel free to create new issues. And, take a look at the general [Roadmap](https://github.com/microsoft/winget-cli/discussions/2063).
