### ISSUE TITLE
[Microsoft.EdgeWebView2Runtime]Unable to install, error code 2147748098

### ISSUE THREAD

**Issue by Vzz1c** [microsoft/winget-cli#1824]
### Brief description of your issue

[Microsoft.EdgeWebView2Runtime]Unable to install, error code 2147748098

**Comment by jedieaston** [comment]
What version of Windows are you on? I wonder if this has something to do with Edge WebView2 being already installed.

**Comment by Vzz1c** [comment]
> What version of Windows are you on? I wonder if this has something to do with Edge WebView2 being already installed.

21H2
19044.1415
At present, all other software can be installed normally, only EdgeWebView2Runtime has been unable to install normally, of course, on the official website to manually download the installation package can be installed.
I have tried several times to repeatedly uninstall, using winget has been unable to install

**Comment by jedieaston** [comment]
I've reproduced this, it looks like the WebView2 installer blocks reinstall if it's currently installed. This isn't a winget issue, but we can work around it by changing the `UpgradeBehavior` key in the manifest to `uninstallPrevious`, which cleans up the previous version before upgrade. 

It's worth noting that WebView2 is "evergreen" and should keep itself up-to-date (in fact, there's no way to block it updating itself). So the likelihood of `winget upgrade` catching it before it upgrades itself is low.

**Comment by Vzz1c** [comment]
is unable to install, and not the problem of upgrading, I just tried, the problem is not solved

**Comment by Grimst** [comment]
Hello, 
i have the same issue right now 

**winget upgrade Microsoft.EdgeWebView2Runtime**

_Found Microsoft Edge WebView2 Runtime [Microsoft.EdgeWebView2Runtime] Version 97.0.1072.76
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install..._

Installer failed with exit code: 2147748098

**winget --info**

Windows Package Manager (Preview) v1.2.3411-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1469
Package: Microsoft.DesktopAppInstaller v1.17.3411.0

Cheers
Steve

**Comment by OfficialEsco** [comment]
Ok since there are a few issues around this, `Microsoft.EdgeWebView2Runtime` requires to be installed with terminal ran as Administrator because it does not self elevate.
This will be resolved once winget-cli supports the field `ElevationRequirement: elevationRequired`.

as user: 
```
PS M:\> winget install Microsoft.EdgeWebView2Runtime
Found Microsoft Edge WebView2 Runtime [Microsoft.EdgeWebView2Runtime] Version 98.0.1108.43
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/257e16c7-6b27-41bc-b212-64d0a9418970/MicrosoftEdgeWebView2RuntimeInstallerX64.exe
  ██████████████████████████████   116 MB /  116 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 2147748098
```

Upgrade with administrator and without the uninstallPrevious switch
```
PS M:\> winget upgrade Microsoft.EdgeWebView2Runtime
Found Microsoft Edge WebView2 Runtime [Microsoft.EdgeWebView2Runtime] Version 98.0.1108.43
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Successfully installed
```

Additional answer to the ones who still see `Microsoft.EdgeWebView2Runtime` as a available upgrade; check if you have 2 different `Microsoft Edge WebView2 Runtime`'s installed (could be another architecture)

Related issues: https://github.com/microsoft/winget-cli/issues/1883, https://github.com/microsoft/winget-cli/issues/1824, https://github.com/microsoft/winget-cli/issues/1904, https://github.com/microsoft/winget-cli/issues/1873, https://github.com/microsoft/winget-pkgs/discussions/44812

**Comment by ljredux** [comment]
This package is just completely broken for me.     I was getting exit code error: 2147747880 even when trying to install it as admin, so I uninstalled it.  Problem is, when I reinstall it, it installs  102.0.1245.33 even though 102.0.1245.39 is the latest version listed.   When I try to upgrade, I am back to exit code error: 2147747880.

**Comment by OfficialEsco** [comment]
I think `2147747880` means Version already installed #63275 got past validation with the wrong version
![VirtualBoxVM_9wOyKnTXWa](https://user-images.githubusercontent.com/15158490/173185334-eaa8592a-3812-4a25-bcae-9277c161c8e0.png)

**Comment by cjwijtmans** [comment]
I just uninstalled it and its not coming back at all. Apparently my puter does not need it.

**Comment by jasonw4331** [comment]
I just received this error code `2147747880` on the Windows 11 Beta preview with package version 106.0.1370.47
I also see error `2147748109` when attempting as administrator.
It claims to be installed and displays this:
![image](https://github.com/microsoft/winget-cli/assets/16521025/b5517caa-d212-4145-81da-f93d35118e24)

Closing the message I get a file not found error and a refusal by winget to reinstall the WebView2 Runtime
