### ISSUE TITLE
How do I add packages?

### ISSUE THREAD

**Issue by auchenberg** [microsoft/winget-cli#183]
How do I add packages? I can't find instructions anywhere.

**Comment by JohnMcPMS** [comment]
Packages are stored in the [Community Repo](https://github.com/microsoft/winget-pkgs).

**Comment by doctordns** [comment]
Pleas add the ability to add packages directly using this tool.

**Comment by gerardog** [comment]
This is all I could find:
* https://docs.microsoft.com/en-us/windows/package-manager/package/
* https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv0.1.md

**Comment by yugabe** [comment]
Please put this info in the readme in this repo, it wasn't easy to figure out and stumbled upon it accidentally here.
