### ISSUE TITLE
Xbox apps/games from the Microsoft Store cannot be installed

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-cli#1833]
### Brief description of your issue

Games that use Xbox services appear to not be available for installation from the msstore source, even though they appear in search.

### Steps to reproduce

1. Run `winget search -s msstore "Microsoft Solitaire Collection"`.
2. Note that it appears available for installation.
3. Run `winget install -s msstore "Microsoft Solitaire Collection"`.
4. It doesn't install :-(

### Expected behavior

To absolutely pwn some noobs in Klondike.

### Actual behavior

The REST source is sending a 404, claiming there isn't an available product for that package version. I can replicate this with the  Minecraft Launcher and Halo Infinite, all free games (so there isn't any weirdness I know of with Game Pass entitlements or something). 

I've attached verbose logs so everyone can see the full responses, but it might be that the source is just blocking Xbox games from being installed, in which case I suppose this should be a feature request (but there should be documentation that games are not currently supported, and searching for games shouldn't return any results). 

[WinGet-2022-01-05-08-59-28.471.log](https://github.com/microsoft/winget-cli/files/7815380/WinGet-2022-01-05-08-59-28.471.log)

### Environment

```shell
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.376
Package: Microsoft.DesktopAppInstaller v1.16.13405.0

Any other software? Well, I'd say Microsoft Solitaire Collection, but...
```

**Comment by ryantheleach** [comment]
I'm also running into issues with games on the windows store.

![image](https://user-images.githubusercontent.com/141554/165864202-df6f9125-a015-4d58-88ab-67d41e37356d.png)

[WinGet-2022-04-29-08-50-49.671.log](https://github.com/microsoft/winget-cli/files/8587254/WinGet-2022-04-29-08-50-49.671.log)

**Comment by MatheusPese** [comment]
Can't install the new Minecraft Launcher from the store, just the old one that does not work.

**Comment by denelon** [comment]
This is a limitation with the Microsoft Store source. They have policies in place regarding which Apps they will expose for WinGet. There are various reasons related to age restrictions, locale restrictions, and potentially other reasons/policies Apps aren't exposed to the WinGet CLI.

**Comment by denelon** [comment]
This bug has been open for a long time. I was digging through some of our oldest issues to see which ones had been resolved. This appears to be resolved by the removal of the titles that aren't offered to WinGet via the Microsoft Store:

![Image](https://github.com/user-attachments/assets/5868662c-1619-4010-87ce-9cd88e59f328)
