### ISSUE TITLE
Error 0x80070005 | Can´t Reinstall or Update Winget

### ISSUE THREAD

**Issue by bocadoce** [microsoft/winget-cli#1848]
### Brief description of your issue

This issue first happened to me when I was trying to update winget it self runing `winget source update`.

Then I started to troubleshot my system by updating windows and microsoft store, also ran all the common cmd commands to restore windows health with no success. Then I tried to uninstall winget somehow, but the problem still remains 

### Steps to reproduce

Adding winget as a source (I removed him when I was trying to fix the problem)
`winget source add -n winget -a https://winget.azureedge.net/cache`

Updating winget itself (Now I can't do it because it was removed)
`winget source update` or `winget source update`

### Expected behavior

Winget is installed or updated.

### Actual behavior

Get the following error message:

_An unexpected error occurred while executing the command:
Operation failed: Deployment Add operation with target volume C: on Package Microsoft.Winget.Source_2022.113.1114.986_neutral__8wekyb3d8bbwe from:  (Microsoft.Winget.Source_8wekyb3d8bbwe.msix)  failed with error 0x80070005. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
0x80070005 : Access is denied._

### Environment

```shell
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.434
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```

**Comment by jedieaston** [comment]
Can you run `winget source reset --force` from an administrator PowerShell/command prompt and see if that fixes it? 

If that doesn't work, can you run `winget source update` and then `Get-AppxLog` from a PowerShell and post the result? I'm curious where it is getting stuck.

**Comment by bocadoce** [comment]
Thank you for your reply

Running `winget source reset --force`, unfortunately didn't solved my issue.

So there it is the result of `Get-AppxLog `:

Time                      ID           Message
----                      --           -------
13/01/2022 14:55:25       603          Started deployment Add operation on a package with main parameter Microsoft.Winget.Source_8wekyb3d8bbwe.msix and
                                       Options 0 and 0. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.

13/01/2022 14:55:25       157          The app package signature was validated for core content of the app package published by CN=Microsoft Corporation,
                                       O=Microsoft Corporation, L=Redmond, S=Washington, C=US. Payload won't be validated until the files are read.

13/01/2022 14:55:25       170          The streaming reader was created successfully for app package
                                       Microsoft.Winget.Source_2022.113.1513.22_neutral__8wekyb3d8bbwe.

13/01/2022 14:55:25       10002        Creating Resiliency File C:\ProgramData\Microsoft\Windows\AppRepository\57cd0e6b-51a8-4c91-ba14-2bfc5dd2125d_S-1-5-2
                                       1-2522548505-2053243288-1719614762-1001_12.rslc for Add Operation on Package
                                       Microsoft.Winget.Source_2022.113.1513.22_neutral__8wekyb3d8bbwe.

13/01/2022 14:55:25       607          Deployment Add operation on package Microsoft.Winget.Source_2022.113.1513.22_neutral__8wekyb3d8bbwe has been
                                       de-queued and is running for user SID S-1-5-21-2522548505-2053243288-1719614762-1001.

13/01/2022 14:55:25       854          Successfully added the following uri(s) to be processed:
                                       file:///C:/Users/Tiago/AppData/Local/Temp/WinGet/Microsoft.Winget.Source_8wekyb3d8bbwe.msix.

13/01/2022 14:55:25       855          Finished resolving action lists. DeploymentRequest action lists: addPackageList:
                                       Microsoft.Winget.Source_2022.113.1513.22_neutral__8wekyb3d8bbwe.

13/01/2022 14:55:26       605          The last successful state reached was PreStagePackagesInUseClosed. Failure occurred before reaching the next state
                                       Staged. hr: 0x80070005

13/01/2022 14:55:26       472          Moving package folder \\?\C:\Program
                                       Files\WindowsApps\Microsoft.Winget.Source_2022.113.1513.22_neutral__8wekyb3d8bbwe to \\?\C:\Program Files\WindowsApp
                                       s\Deleted\Microsoft.Winget.Source_2022.113.1513.22_neutral__8wekyb3d8bbwe53120158-eea7-4a24-865e-8ad9a1bad02f.
                                       Result: 0x0.

13/01/2022 14:55:26       401          Deployment Add operation with target volume C: on Package
                                       Microsoft.Winget.Source_2022.113.1513.22_neutral__8wekyb3d8bbwe from:  (Microsoft.Winget.Source_8wekyb3d8bbwe.msix)
                                        failed with error 0x80070005. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment
                                       issues.

13/01/2022 14:55:26       404          AppX Deployment operation failed for package Microsoft.Winget.Source_2022.113.1513.22_neutral__8wekyb3d8bbwe with
                                       error 0x80070005. The specific error text for this failure is: Deployment Add operation with target volume C: on
                                       Package Microsoft.Winget.Source_2022.113.1513.22_neutral__8wekyb3d8bbwe from:
                                       (Microsoft.Winget.Source_8wekyb3d8bbwe.msix)  failed with error 0x80070005. See
                                       http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.

**Comment by jedieaston** [comment]
The Microsoft Store works on your machine, right? (Like, if you go to the Microsoft Store and run updates they install okay?)

**Comment by bocadoce** [comment]
> The Microsoft Store works on your machine, right? (Like, if you go to the Microsoft Store and run updates they install okay?)

Yes

**Comment by bocadoce** [comment]
I don't know what was causing the issue, but I reinstalled windows with an iso file, keeping the apps and files.
After that my problem was solved... That's what matters

Probably it was a Windows problem
