### ISSUE TITLE
`winget upgrade --all`. Insert blank line after intial "Found" list.

### ISSUE THREAD

**Issue by JohnLukeBentley** [microsoft/winget-cli#1858]
### Description of the new feature / enhancement

`winget upgrade --all` outputs to the user: an initial list of "Found" packages; then attempts to install each of these packages one by one. 

I suggest it would be more readable if a blank line would be inserted between these two aspects. 

Example current output: 

    PS C:\Users\john> winget upgrade --all
    Found IrfanView [IrfanSkiljan.IrfanView] Version 4.58
    Found PSpad editor [JanFiala.PSpad] Version 5.0.6.589
    Found Signal [OpenWhisperSystems.Signal] Version 5.27.1
    Found  [IrfanSkiljan.IrfanView] Version 4.58
    This application is licensed to you by its owner.
    Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
    Downloading https://download.betanews.com/download/967963863-1/iview458_x64_setup.exe
      ██████████████████████████████  3.56 MB / 3.56 MB
    Successfully verified installer hash
    Starting package install...
    Successfully installed    
    .... [Other install output omitted]

Example proposed output:

    PS C:\Users\john> winget upgrade --all
    Found IrfanView [IrfanSkiljan.IrfanView] Version 4.58
    Found PSpad editor [JanFiala.PSpad] Version 5.0.6.589
    Found Signal [OpenWhisperSystems.Signal] Version 5.27.1

    Found  [IrfanSkiljan.IrfanView] Version 4.58
    This application is licensed to you by its owner.
    Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
    Downloading https://download.betanews.com/download/967963863-1/iview458_x64_setup.exe
      ██████████████████████████████  3.56 MB / 3.56 MB
    Successfully verified installer hash
    Starting package install...
    Successfully installed    
    .... [Other install output omitted]

Otherwise it reads as if [IrfanSkiljan.IrfanView] was found twice.

### Proposed technical implementation details

Throw in a newline at the place suggested.

**Comment by jedieaston** [comment]
That output probably needs to be cleaned up too (maybe a different issue). It's a sideeffect of winget trying to print agreements for those packages and those packages not having any agreements.

What about if at the beginning of an upgrade it printed the upgrade table, which gives a little bit cleaner output for humans?

```
Name                         Id                                    Version      Available    Source
---------------------------------------------------------------------------------------------------
Docker Desktop               Docker.DockerDesktop                  4.3.2        4.4.2        winget
Postman                      Postman.Postman                       9.7.1        9.8.3        winget
Microsoft Teams              Microsoft.Teams                       1.4.00.31569 1.4.00.32771 winget
ZeroTier One                 ZeroTier.ZeroTierOne                  1.6.6        1.8.4        winget
Visual Studio Community 2022 Microsoft.VisualStudio.2022.Community 17.0.4       17.0.5       winget
7-Zip                        7zip.7zip                             21.06.00.0   21.07        winget
Go Programming Language      GoLang.Go                             1.17.5       1.17.6       winget
PowerToys (Preview)          Microsoft.PowerToys                   0.51.1       0.53.3       winget

Found Docker Desktop (Docker.DockerDesktop) ....
```

**Comment by JohnLukeBentley** [comment]
@jedieaston yes I think the upgrade table followed by a blank line, as you exemplify, is better.

I eventually came to the same conclusion in the separate but related issue *winget upgrade V winget upgrade --all produces different sets of packages* #1854

**Comment by JohnMcPMS** [comment]
How about we just don't have the list or the table?  I believe the agreements are done up front to keep the long operation from having a blocking prompt, which makes sense.  But I don't think it ever needed to output the "Found ..." if there were no agreements.  That way we would either have:
```
> winget upgrade --all
Found Foo
...
Agree? Y

{1/N) Found Bar
...
```
or with no agreements:
```
> winget upgrade --all
(1/N) Found Bar
...
```

The changes to @jedieaston 's PR are minimal; just remove the table and added newline (I think that the prompt + user input will generate a good look, but could put the newline there instead if needed).

**Comment by JohnLukeBentley** [comment]
I suggest the table is essential (and as @jedieaston currently has it in the Pull Request "I reused the upgrade table from `winget upgrade` for this too"). For the key pieces of information it provides - a summary of what winget will attempt to upgrade; and current and available versions - I think important to help make one situationally aware.

The package agreements issue is above my head, so I won't comment on it (at least it does seem like a separate issue).

@jedieaston could you confirm I'm reading your code right? Your `ReportListResult(true)`, the reuse of " the upgrade table from `winget upgrade`", is a reference to the same code base. That is, so if we change the design of the table in one place (`winget upgrade` say) that would flow through to the other place (`winget upgrade -all`). Is that right?

**Comment by jedieaston** [comment]
> Your ReportListResult(true), the reuse of " the upgrade table from winget upgrade", is a reference to the same code base. That is, so if we change the design of the table in one place (winget upgrade say) that would flow through to the other place (winget upgrade -all). Is that right?

> How about we just don't have the list or the table? 

I could go either way, personally. I originally was going to just make the changes to agreements as you suggest, but other package managers (apt, pacman) usually print a list of packages so the user knows what it is planning to upgrade even if it fails half way through:

```
easton@Spintax /m/c/U/easton> sudo apt upgrade -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  gdb gdbserver libnss-systemd libpam-systemd libruby2.7 libsystemd0 libudev1 linux-libc-dev linux-libc-dev:i386
  openssh-client openssh-server openssh-sftp-server ruby2.7 systemd systemd-sysv systemd-timesyncd
  ubuntu-advantage-tools udev vim vim-common vim-runtime vim-tiny xxd
23 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

....
```

Removing the table would simplify things (and the user can always do `winget upgrade; winget upgrade --all`), but I think the table would be handy in `upgrade --all` as one last message to the user about what is about to happen.
