### ISSUE TITLE
Document workaround for Microsoft.UI.Xaml dependency

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-cli#1861]
### Brief description of your issue

The latest pre-release version of winget requires Microsoft.UI.Xaml version 2.7, which doesn't have an external (no MSStore) download link. As such, it's impossible to install on Windows Sandbox or LTSC builds of Windows.

<img width="490" alt="image" src="https://user-images.githubusercontent.com/21368066/149962173-868e0407-d255-409d-b15d-d60e6e8b66d0.png">

### Steps to reproduce

1. Open a Windows Sandbox.
2. Go to [releases](https://github.com/microsoft/winget-cli/releases/) and download the latest pre-release version of winget/DesktopAppInstaller.
3. Download the desktop bridge package from [here](https://docs.microsoft.com/en-us/troubleshoot/cpp/c-runtime-packages-desktop-bridge).
4. Install the pre-release version of winget, supplying the desktop bridge package as a dependency.

### Expected behavior

winget to install, with the dependency support stuff ready to test!

### Actual behavior

```
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict validation.
Windows cannot install package Microsoft.DesktopAppInstaller_1.17.3411.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework
"Microsoft.UI.Xaml.2.7" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version
7.2109.13004.0, along with this package to install. The frameworks with name "Microsoft.UI.Xaml.2.7" currently installed are: {}
NOTE: For additional information, look for [ActivityId] 5730573a-07cf-000f-f88c-3057cf07d801 in the Event Log or use the command line Get-AppPackageLog -ActivityID
5730573a-07cf-000f-f88c-3057cf07d801
At line:1 char:1
+ Add-AppxPackage .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbun ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\WDAGUt...bbwe.msixbundle:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

PS C:\Users\WDAGUtilityAccount\Downloads>
```

(And before someone says it, yes I know how to get stuff from the Store for offline installation. But that's not the kosher method, and I'd rather someone ask the team that packages Microsoft.UI.Xaml to make it available at a URL like the Desktop Bridge team did.)

### Environment

```shell
Windows: Windows.Desktop v10.0.22000.434

Any other software? This is the Sandbox build of Windows, so there is not a Microsoft Store available.
```

**Comment by soroshsabz** [comment]
I have the same issue

**Comment by github-account1111** [comment]
@jedieaston is there a similar URL for Winget itself?
Specifically the latest pre-release builds.
Maybe something along the lines of https://github.com/microsoft/winget-cli/releases/pre-release/download

**Comment by ItzLevvie** [comment]
Latest pre-release build of WinGet can be found at https://github.com/microsoft/winget-cli/releases

^ Direct URL: https://github.com/microsoft/winget-cli/releases/download/v1.3.1872/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle

Microsoft.UI.Xaml.2.7 can be downloaded from https://globalcdn.nuget.org/packages/microsoft.ui.xaml.2.7.0.nupkg and then extract `Microsoft.UI.Xaml.2.7.appx` from `tools\AppX\x64\Release` and sideload (via Add-AppxPackage or via App Installer GUI) that onto your PC.

**Comment by github-account1111** [comment]
But the "v1.3.1872" bit will change with next update.
I want one that'll always give the latest possible release (pre-release or not).

**Comment by ItzLevvie** [comment]
You will have to do what @vedantmgoyal2009 is doing by using the GitHub API and then getting the latest pre-release build or the latest release build of WinGet.

Without the GitHub API it only allows you to download the latest release build (instead of the latest pre-release build) at https://github.com/microsoft/winget-cli/releases/latest which is from 2nd of February 2022

**Comment by github-account1111** [comment]
Thanks Levvie.
Is there a reason I shouldn't just grab the first entry in the response body, since that seems to always be the latest prerelease, which is what I want?

**Comment by jedieaston** [comment]
Nope. If the latest release is marked as stable you'll get that one, but that's usually the latest one so you should be okay.

**Comment by github-account1111** [comment]
Gotcha thanks!

I was able to get things working yesterday, but now it broke out of nowhere.
I traced it back to [a new Xaml version](https://www.nuget.org/packages/Microsoft.UI.Xaml#versions-body-tab) which was released 12 hours ago.

So to clarify: when you say Xaml.2.7, do you mean 2.7.0 from 2021 or 2.7.1 from 4 months ago?
It's definitely not 2.8 because that causes winget to fail to install, whereas the former 2 don't.

**Comment by jedieaston** [comment]
It has to be 2.7.x, the "patch" version (the last number) shouldn't matter.

**Comment by MarcoPeraza** [comment]
I have a powershell function for this @ItzLevvie @github-account1111 : 

```

function Get-GithubLatestRelease {
    param (
        [parameter(Mandatory)][string]$project, # e.g. paintdotnet/release
        [parameter(Mandatory)][string]$pattern, # regex. e.g. install.x64.zip
        [switch]$prerelease
    )

    # Get all releases and then get the first matching release. Necessary because a project's "latest"
    # release according to Github might be of a different product or component than the one you're
    # looking for. Also, Github's 'latest' release doesn't include prereleases.
    $releases = Invoke-RestMethod -Method Get -Uri "https://api.github.com/repos/$project/releases"
    $downloadUrl = $releases |
                   Where-Object { $_.prerelease -eq $prerelease } |
                   ForEach-Object { $_.assets } |
                   Where-Object { $_.name -match $pattern } |
                   Select-Object -First 1 -ExpandProperty "browser_download_url"

    return $downloadUrl
}
```

Call it like this 

`Get-GithubLatestRelease -project "microsoft/winget-cli" -pattern "Microsoft.DesktopAppInstaller.+.msixbundle" -prerelease`

Note: the purpose of the -pattern parameter is not just to identify the file to download but also to filter out "releases" that don't have the relevant asset (e.g. the most recent release according to github might just be a documentation release).

**Comment by github-account1111** [comment]
If I install Store apps this way using winget, will they auto-update?
If not, can I update them through winget?

Or am I stuck with whatever version was out at the time of installation?

**Comment by github-account1111** [comment]
But I thought the whole premise of this issue is for when there is no Store 😅
Or are you saying Microsoft.UI.Xaml.2.7.appx (in conjunction with VCLibs) _is_ the Store (sans GUI) and is what will auto-update things?

**Comment by jedieaston** [comment]
Oh, I misunderstood your question. This doesn't install the Store, and you can't install Store apps without the Store being installed (winget will give you a error about not being logged in). Win32 apps can be installed from the Store without it being installed, but they won't be upgraded unless there's also a version of the app in the community repo.

**Comment by github-account1111** [comment]
>but they won't be upgraded unless there's also a version of the app in the community repo.

That's a bummer..
So then this isn't very useful unless one is okay with using outdated software.

I assumed that since winget can install from the Store (e.g. `9N97ZCKPD60Q` and `9PMMSR1CGPWG` got installed without issues after Xaml 2.7) it will also be able to update from the Store.
Perhaps that's a planned feature?
I even recall reading that the new Store is just a winget frontend.

**Comment by github-account1111** [comment]
>they won't be upgraded unless there's also a version of the app in the community repo

Following up, but my Unigram was just upgraded, and that's UWP and from the Store, so I think they will get upgraded!

**Comment by Trolldemorted** [comment]
@denelon why should this be a docs issue?

winget should work on LTSC and Sandbox without us jumping through obscure hoops.

**Comment by denelon** [comment]
We're working on a solution for making it easier to "bootstrap" WinGet on Windows Server without Microsoft Store access.

**Comment by itapai** [comment]
> We're working on a solution for making it easier to "bootstrap" WinGet on Windows Server without Microsoft Store access.

Why just Windows Server? Will it be possible to bootstrap winget on Windows Desktop as well?

**Comment by denelon** [comment]
The solution we're working on should apply to any version of Windows that is recent enough to have our dependencies available.

**Comment by nhooyr** [comment]
```ps1
Invoke-WebRequest -Uri https://www.nuget.org/api/v2/package/Microsoft.UI.Xaml/2.7.3 -OutFile .\microsoft.ui.xaml.2.7.3.zip
Expand-Archive .\microsoft.ui.xaml.2.7.3.zip
Add-AppxPackage .\microsoft.ui.xaml.2.7.3\tools\AppX\x64\Release\Microsoft.UI.Xaml.2.7.appx

Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.3.2691/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
Add-AppxPackage .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
```

note: You have to install 2.7, installing latest 2.8.1 of `Microsoft.UI.Xaml` results in the same error as before when installing `winget`

**Comment by BrianL-STCU** [comment]
@nhooyr Your script _seemed_ to work great. On a new workstation, after the XAML install, my machine seemed to know what to do with a _.msixbundle_ file. The second part seems like you can abbreviate to `Add-AppxPackage https://aka.ms/getwinget`, but either way it succeeds, except I don't seem to have **winget** actually installed anywhere. I don't get errors anymore, but `winget` isn't a command that works using the current Path, and I can't find winget.exe anywhere on my machine.

**Comment by AriMSD** [comment]
Here is what is working for me today.

```
Add-AppxPackage -Path https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx

Invoke-WebRequest -Uri https://www.nuget.org/api/v2/package/Microsoft.UI.Xaml/2.7.3 -OutFile .\microsoft.ui.xaml.2.7.3.zip
Expand-Archive .\microsoft.ui.xaml.2.7.3.zip
Add-AppxPackage .\microsoft.ui.xaml.2.7.3\tools\AppX\x64\Release\Microsoft.UI.Xaml.2.7.appx

Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.4.10173/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
Add-AppxPackage .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
```

The provenance of all these files is direct from Microsoft, except for the command that uses NuGet to extract a file. You're on your own deciding if they are trustworthy.

**Comment by Andrej730** [comment]
@AriMSD solution almost worked for me but needed to add the license to avoid #700 on Windows 10 Enterprise LTSC 2019

```
Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.4.10173/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.4.10173/3463fe9ad25e44f28630526aa9ad5648_License1.xml -OutFile .\3463fe9ad25e44f28630526aa9ad5648_License1.xml
Add-AppxProvisionedPackage -Online -PackagePath .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -LicensePath .\3463fe9ad25e44f28630526aa9ad5648_License1.xml -Verbose
```

**Comment by denelon** [comment]
The `Repair-WinGetPackageManager` cmdlet in the [Microsoft.WinGet.Client](https://www.powershellgallery.com/packages/Microsoft.WinGet.Client/) PowerShell Module does much of the work to handle dependencies, but Microsoft.UI.Xaml is still not handled in the most optimal way. We're looking at some options here to see if we can improve the situation without needing to download and decompress the dependency.

We've also been looking to update the dependency to Microsoft.UI.Xaml 2.8 from 2.7 in WinGet:
* https://github.com/microsoft/winget-cli/issues/3380

**Comment by Trenly** [comment]
> We're looking at some options here to see if we can improve the situation without needing to download and decompress the dependency.

GitHub releases of the Appx files are now available; see https://github.com/microsoft/winget-pkgs/pull/111841

**Comment by ChaoticHolon** [comment]
These should work (all online), for the latest version of WinGet-Cli

`Add-AppxPackage -Path https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx

Add-AppxPackage -Path https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.7.3/Microsoft.UI.Xaml.2.7.x64.appx

Add-AppxPackage -Path https://github.com/microsoft/winget-cli/releases/download/v1.5.1881/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle

Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.5.1881/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.5.1881/c6bee58ade21451eb54dc52e559a314c_License1.xml -OutFile .\c6bee58ade21451eb54dc52e559a314c_License1.xml
Add-AppxProvisionedPackage -Online -PackagePath .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -LicensePath .\c6bee58ade21451eb54dc52e559a314c_License1.xml -Verbose`

**Comment by neheb** [comment]
How about

```
Add-AppxProvisionedPackage -Online -PackagePath .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -LicensePath .\27abf0d1afe340e7a64fb696056b2672_License1.xml -Verbose -DependencyPackagePath https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx;https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.8.5/Microsoft.UI.Xaml.2.8.x64.appx
```

**Comment by Trenly** [comment]
@jedieaston - Should this be closed now that UI.Xaml is distributed at the GitHub?

**Comment by LuciDuki** [comment]
I have a similar Problem with fresh installed Windows 10 22H2.

using
`powershell Add-AppxPackage .\VCLibs.appx -ForceUpdateFromAnyVersion
powershell Add-AppxPackage .\UI.appx -ForceUpdateFromAnyVersion
powershell Add-AppxPackage -Path ".\winget.msixbundle" -InstallAllResources`

to install it with a batch file i get following error on the last step:
`Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict
validation.
Windows cannot install package Microsoft.DesktopAppInstaller_1.22.10661.0_x64__8wekyb3d8bbwe because this package
depends on a framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.8" published by
"CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor
architecture and minimum version 8.2310.30001.0, along with this package to install. The frameworks with name
"Microsoft.UI.Xaml.2.8" currently installed are: {Microsoft.UI.Xaml
Windows cannot install package Microsoft.DesktopAppInstaller_1.22.10661.0_x64__8wekyb3d8bbwe because this package
depends on a framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.8" published by
"CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor
architecture and minimum version 8.2310.30001.0, along with this package to install. The frameworks with name
"Microsoft.UI.Xaml.2.8" currently installed are: {Microsoft.UI.Xaml.2.8_8.2306.22001.0_x64__8wekyb3d8bbwe}
NOTE: For additional information, look for [ActivityId] 981811d9-7a58-0002-cf23-1898587ada01 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 981811d9-7a58-0002-cf23-1898587ada01
At line:1 char:1
+ Add-AppxPackage -Path .\winget.msixbundle -InstallAllResources
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (D:\Data\Installscript\winget.msixbundle:String) [Add-AppxPackage], IOExcept
   ion
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand`


Any Ideas?

**Comment by Trenly** [comment]
@luciduki - Are you using the 2.8 version of Microsoft.UI.Xaml, and not the 2.7 version? https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.8.6

**Comment by LuciDuki** [comment]
@Trenly - Yes, as it states here:
``` The frameworks with name "Microsoft.UI.Xaml.2.8" currently installed are: {Microsoft.UI.Xaml.2.8_8.2306.22001.0_x64__8wekyb3d8bbwe}```

Already found the issue... installed is version 8.**2306**.22001.0_x64__8wekyb3d8bbwe, but it wants version 8.**2310**.30001.0.
Only Problem is i cant find this version to download. i always get the 2306 if i download the newest

**Comment by Trenly** [comment]
> @Trenly - Yes, as it states here: ` The frameworks with name "Microsoft.UI.Xaml.2.8" currently installed are: {Microsoft.UI.Xaml.2.8_8.2306.22001.0_x64__8wekyb3d8bbwe}`
> 
> Already found the issue... installed is version 8.**2306**.22001.0, but it wants version 8.**2310**.30001.0. Only Problem is i cant find this version to download. i always get the 2306 if i download the newest

I see, I must have missed that. I believe the telease of Microsoft.UI.Xaml I linked above is what the `Repair-WinGetPackageManager` cmdlet installs, so that should work. . .

**Comment by Trolldemorted** [comment]
Out of curiousity, why does a winget depend on UI libs? Does it use xaml somewhere?

**Comment by Trenly** [comment]
> Out of curiousity, why does winget depend on UI libs? Does it use xaml somewhere?

-----

> It doesn't. But winget is packaged along DesktopAppInstaller (the UI that shows up when you double-click on an .msix/.msixbundle), which has a dependency on WinUI 2.7.

_Originally posted by @florelis in https://github.com/microsoft/winget-cli/issues/3380#issuecomment-1624195433_
