### ISSUE TITLE
Virtualbox update available but no applicable update found

### ISSUE THREAD

**Issue by leochras** [microsoft/winget-cli#1864]
### Brief description of your issue

Running `winget upgrade` outputs an update for Virtualbox but when I try to upgrade winget says it found no applicable updates.

### Steps to reproduce

```
PS C:\Users\leoch> winget upgrade
Name                 Id                Version Available Source
---------------------------------------------------------------
Portmaster           Safing.Portmaster Unknown 0.7.0     winget
Oracle VM VirtualBox Oracle.VirtualBox 6.1.30  6.1.32    winget
2 upgrades available.
PS C:\Users\leoch> winget upgrade virtualbox
No applicable update found.
PS C:\Users\leoch> winget upgrade oracle.virtualbox
No applicable update found.
PS C:\Users\leoch> winget upgrade Oracle.Virtualbox
No applicable update found.
PS C:\Users\leoch> winget upgrade Oracle.VirtualBox
No applicable update found.
```

### Expected behavior

winget upgrades virtualbox to version 6.1.32

### Actual behavior

winget gets confused and says it doesn't find any applicable updates.

### Environment

```shell
PS C:\Users\leoch> winget --info
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.438
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```

**Comment by jedieaston** [comment]
This is because VirtualBox runs a msi file inside of its exe file, which the current stable version of winget can't handle for upgrades. Luckily, https://github.com/microsoft/winget-cli/pull/1796 was merged yesterday which will allow us to fix this problem in the manifests.

**Comment by leochras** [comment]
Thank you for clarifying. Removing VirtualBox and installing it again is not a nice workaround, though.
