### ISSUE TITLE
Ubuntu 16.04 cann't upgrade from 1604.2019.523.0 to 1604.2020.824.0

### ISSUE THREAD

**Issue by hardcorp74** [microsoft/winget-cli#1868]
Ubuntu 16.04 cann't upgrade from 1604.2019.523.0 to 1604.2020.824.0
![image](https://user-images.githubusercontent.com/5231223/150476134-94d27695-16ba-4320-9183-d914f9e02c8a.png)

**Comment by jedieaston** [comment]
Can you run `winget upgrade Canonical.Ubuntu.1604 --verbose-logs` and post the log file? It should be in `%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir`

**Comment by HarDX** [comment]
[WinGet-2022-01-22-02-24-56.407.log.zip](https://github.com/microsoft/winget-cli/files/7916655/WinGet-2022-01-22-02-24-56.407.log.zip)
