### ISSUE TITLE
Windows PC Health Check uninstalled but still showing up in winget upgrad

### ISSUE THREAD

**Issue by themizzi** [microsoft/winget-cli#1870]
### Brief description of your issue

I have removed the Windows PC Health Check numerous times, but it still shows when running `winget upgrade`

### Steps to reproduce

Install the Windows PC Health Check. Then uninstall it. Then run `winget upgrade`.

### Expected behavior

After uninstalling Windows PC Health Check, it no longer shows in `winget upgrade`

### Actual behavior

Windows PC Health Check still shows in `winget upgrade`

### Environment

```shell
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1469
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```
```

**Comment by themizzi** [comment]
Closing this issue because I resolved it. the PC Health Check uninstaller remained in the registry. Removing that registry key got rid of this issue. Likely a problem with the PC Health Check uninstaller itself.

**Comment by GravlLift** [comment]
If anyone comes to this thread looking for exactly which registry key you need to delete, mine was located at

```
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{guid}
```

Where I assume `guid` is some arbitrary guid generated by my machine. It might be different for you, but it'll contain an entry of `DisplayName` with a value of `Windows PC Health Check`.
