### ISSUE TITLE
"--no-window" option when install or upgrade

### ISSUE THREAD

**Issue by neko3cs** [microsoft/winget-cli#1872]
### Description of the new feature / enhancement

Could you add "--no-window" option when run install or upgrade command?

I think there are times when I don't want to open the progress window.

**Comment by jedieaston** [comment]
The `--silent` option will tell the installer not to appear if the installer supports that (and many do!)

**Comment by BUGProtectionAssociation** [comment]
Do you want to force a window minimization? Some programs that require the click of a button may not install or update properly. This can only wait for those programs to actively adapt.

**Comment by denelon** [comment]
As @jedieaston commented, you can try to install with "--silent" or "-h".

The default is "silent with progress" which may pop a window from the package to show progress but does not require user interaction. The Windows Package Manager "can" install packages using their interactive mode as well with "--interactive" or "-i" if the installer supports that mode.
