### ISSUE TITLE
[Microsoft Edge WebView2 Runtime] winget upgrade --all attempts to download when already up to date

### ISSUE THREAD

**Issue by kvnxiao** [microsoft/winget-cli#1873]
### Brief description of your issue

winget tries to upgrade my Microsoft Edge WebView2 Runtime when my current version is already up to date.

winget tries to download `Version 97.0.1072.69` when my `Apps & Features` page in the settings already shows `97.0.1072.69`

```
~
❯ winget upgrade --all
Found Microsoft Edge WebView2 Runtime [Microsoft.EdgeWebView2Runtime] Version 97.0.1072.69
Found  [Microsoft.EdgeWebView2Runtime] Version 97.0.1072.69
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/88c30f40-82c2-4353-a5a4-dd81c61711ed/MicrosoftEdgeWebView2RuntimeInstallerX64.exe
  ██████████████████████████████  8.00 MB /  114 MB
Package download canceled.

Cancelled
```

![image](https://user-images.githubusercontent.com/14130413/150674915-0a6ef4cc-fb2a-4c0f-9444-bdf4630fcb77.png)

### Steps to reproduce

Ran `winget upgrade --all` on `Windows 11 Pro`

winver.exe:
```
Microsoft Windows
Version 21H2 (OS Build 22000.438)
...
```

### Expected behavior

Winget should not try to download edge webview2 runtime since it is already up to date

### Actual behavior

Winget attempts to download and install the latest version of webview2 runtime even though it is already installed.

### Environment

```shell
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.438
Package: Microsoft.DesktopAppInstaller v1.16.13405.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by jedieaston** [comment]
Can you run `winget upgrade` and print the table it shows?

**Comment by kvnxiao** [comment]
@jedieaston  It seems I cannot reproduce this anymore after running through the latest windows update on my machine.

**Comment by Nejat** [comment]
I'm have similar problems, except mine completes downloading and fails upgrading.

I cannot uninstall it: the option is disabled.
I cannot re-install it, the installer says it's already installed

```powershell
~: winget upgrade
Name                            Id                            Version      Available    Source
----------------------------------------------------------------------------------------------
Microsoft Edge WebView2 Runtime Microsoft.EdgeWebView2Runtime 97.0.1072.76 98.0.1108.43 winget
1 upgrades available.
```

```powershell
~: winget upgrade --all
Found Microsoft Edge WebView2 Runtime [Microsoft.EdgeWebView2Runtime] Version 98.0.1108.43
Found  [Microsoft.EdgeWebView2Runtime] Version 98.0.1108.43
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/257e16c7-6b27-41bc-b212-64d0a9418970/MicrosoftEdgeWebView2RuntimeInstallerX64.exe
  ██████████████████████████████   116 MB /  116 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 2147748098
```

How else can this component be upgraded?

**Comment by jedieaston** [comment]
This issue isn’t fixed, it may be able to be fixed if/when https://github.com/microsoft/winget-cli/issues/1885 happens. Or if WebView2’s installer is changed to work correctly under this scenario. 

Sorry for the confusion.

**Comment by Nejat** [comment]
Is there a way of uninstalling the current version?

**Comment by jedieaston** [comment]
`winget uninstall "Microsoft Edge WebView2 Runtime" ` should work, I believe (or uninstall it from "Add and Remove Programs").
