### ISSUE TITLE
Windows Package Manager 1.2 manifest schema

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#1891]
### Description of the new feature / enhancement

This is a parent issue to track outstanding schema requests for the 1.2 schema. 
Inclusion in this list is **not a commitment**. Other schema items may be added or removed.

>Note: We will be targeting the 1.2 schema with the 1.3 client.

* #1994
* #1984
* #1916
* #1889
* #1888 
* #1345 
* #1277
* #607

Related to:
* #1145
* #970 
* #182
* #140
* microsoft/winget-cli-restsource/issues/118

Also related to schema, but not implemented or targeted for the 1.3 client release:
* #163 
* #147

**Comment by denelon** [comment]
See:
* #1997

**Comment by Trenly** [comment]
@denelon - Is this completed?

**Comment by denelon** [comment]
LOL! Yes, this was complete, I was just looking at the related open issues and saw the one at the REST source that isn't marked complete, and the features enabled by the schema that still haven't been implemented.
