### ISSUE TITLE
Winget upgrade and install don't give any feedback

### ISSUE THREAD

**Issue by LeonarddeR** [microsoft/winget-cli#1893]
### Brief description of your issue

When I execute winget upgrade or winget install, I'm not getting any output. Executing winget without a command, winget list or winget --version, all works fine.

### Steps to reproduce

Either execute `winget upgrade` or `winget install <something>`

### Expected behavior

Show output

### Actual behavior

No output is shown. This is the log:
[WinGet-2022-02-02-12-33-48.659.log](https://github.com/microsoft/winget-cli/files/7986014/WinGet-2022-02-02-12-33-48.659.log)

### Environment

```shell
Windows: Windows.Desktop v10.0.22000.469                                                                                                                                                                         
Package: Microsoft.DesktopAppInstaller v1.17.3411.0
```

**Comment by leonardder** [comment]
I was able to fix this by forcefully removing the app installer from %LOCALAPPDATA%\Packages\ and reinstall it. It would have been helpful if these commands don't stay silent when there's an error in the log, though.

**Comment by JohnMcPMS** [comment]
This looks like a bug in how we handle a failure in reading certain settings.  I would expect an error to be output, but obviously that isn't happening here.

**Comment by denelon** [comment]
This issue is quite old. Is this still happening?
