### ISSUE TITLE
winget install KDE.KDEConnect failed while this software could be found by `winget search` [Error Code:0x80190194]

### ISSUE THREAD

**Issue by HUGHNew** [microsoft/winget-cli#1907]
### Brief description of your issue

> I have submitted in [Feedback Hub](https://aka.ms/AAfndpo) yet.
Error occurred when I tried to install KDEConnect by winget.
I could get some info by `winget search KDEConnect` , but I couldn't install it either directly or by id.

### Steps to reproduce

winget install --id KDE.KDEConnect

### Expected behavior

install KDEConnect successfully

### Actual behavior

~~Error~~
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : 未找到(404)。 ~~**Not Found** in Chinese~~
![image](https://user-images.githubusercontent.com/52786639/152691793-12fe4d17-49b0-4de5-877f-e986299d1d15.png)

### Environment

```shell
[winget --info]
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1466
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```

**Comment by denelon** [comment]
I'm unable to reproduce the error.

I'm not sure if their side was having network issues, or if you may have been experiencing network issues while trying to download from their Content Distribution Network (CDN).

```
PS C:\Windows\system32> winget install kdeconnect
Found KDE Connect [KDE.KDEConnect] Version 21.12.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://binary-factory.kde.org/view/Windows%2064-bit/job/kdeconnect-kde_Release_win64/871/artifact/kdeconnect-kde-21.12.2-871-windows-msvc2019_64-cl.exe
  ██████████████████████████████  56.9 MB / 56.9 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

**Comment by HUGHNew** [comment]
Thx! I have asked my friend nearby to try it again and found out that there was something wrong with my network.
