### ISSUE TITLE
How do I ignore a package update

### ISSUE THREAD

**Issue by AirBashX** [microsoft/winget-cli#1908]
### Description of the new feature / enhancement

I have a few software I don't want to update.When I update all software, can I ignore the update of these software?

**Comment by KaranKad** [comment]
Duplicate of https://github.com/microsoft/winget-cli/issues/1439

**Comment by denelon** [comment]
Duplicate of https://github.com/microsoft/winget-cli/issues/1439

Related to:
* #476
