### ISSUE TITLE
Winget Import/Export

### ISSUE THREAD

**Issue by HEROgold** [microsoft/winget-cli#1913]
### Brief description of your issue

Winget import shows the ```Multiple packages are found``` message (yellow on the image.), even though i just exported the whole list.
I made sure im on the last update by using the command ```winget source update```.

![afbeelding_2022-02-09_143623](https://user-images.githubusercontent.com/21345384/153212032-1b5b6d79-aa8d-4aa0-bbf1-ed41ddd8205c.png)

### Steps to reproduce

1. winget export -o app_list
2. winget import app_list

### Expected behavior

after export I expect the app_list file to contain all the Id's of the installed packages winget can find.
when importing i expect each package to be installed correctly.

### Actual behavior

after export I expect the app_list file to contain all the Id's of the installed packages winget can find.
when importing some packages might have multiple or idential identifiers, when this happens it does not install those packages and i have to manually scroll back in the console to find the app and install it manually.

### Environment

```shell
C:\Users\marti>winget --info
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. Alle rechten voorbehouden.

Windows: Windows.Desktop v10.0.19042.1466
Pakket: Microsoft.DesktopAppInstaller v1.16.13405.0

Logboeken: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Koppelingen
---------------------------------------------------------------------------------
Privacyverklaring         https://aka.ms/winget-privacy
Gebruiksrechtovereenkomst https://aka.ms/winget-license
Mededelingen van derden   https://aka.ms/winget-3rdPartyNotice
Startpagina               https://aka.ms/winget
Windows Store-voorwaarden https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by jedieaston** [comment]
Related to #1413 (it's the same behavior, just in a different command).

**Comment by denelon** [comment]
We've recently added better support for side-by-side packages. I'm expecting that to help in this case. You can test with the experimental feature in a WinGet 1.8 preview.

**Comment by denelon** [comment]
@HEROgold is this still happening in WinGet 1.9?

**Comment by HEROgold** [comment]
@denelon it appears to work as expected. Ijust tested with V1.9.25200
