### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by thennothinghappened** [microsoft/winget-cli#1921]
### Brief description of your issue

Running winget to install, upgrade or uninstall any package gives the error
```Failed in attempting to update the source: winget
Failed when searching source: winget
An unexpected error occurred while executing the command:
database disk image is malformed
0x87af000b : The database disk image is malformed
```

### Steps to reproduce

Running winget to install, upgrade or uninstall any package gives the error

### Expected behavior

Install package correctly.

### Actual behavior

```Failed in attempting to update the source: winget
Failed when searching source: winget
An unexpected error occurred while executing the command:
database disk image is malformed
0x87af000b : The database disk image is malformed
```
Is logged, and winget stops.
I have tried deleting the database files since that was recommended by an appx command similar issue, rebooting also hasn't helped.

### Environment

```shell
Windows Package Manager v1.2.0
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1288

Logs: %TEMP%\WinGet
```

**Comment by Trenly** [comment]
Have you tried `winget source update`?
What version of winget are you running?

**Comment by thennothinghappened** [comment]
> Have you tried `winget source update`?
> What version of winget are you running?

I've given that a shot but it also errors, version of winget was posted in the issue, 1.2.0

**Comment by ItzLevvie** [comment]
> > Have you tried `winget source update`?
> > What version of winget are you running?
> 
> I've given that a shot but it also errors, version of winget was posted in the issue, 1.2.0

What about downloading the source from https://winget.azureedge.net/cache/source.msix and installing that into your system?

**Comment by thennothinghappened** [comment]
I was not able to track down the source of the issue. Luckily I was on a fresh windows install, so I ended up reinstalling as on a reboot the issue had progressed to all UWP apps failing to open (start menu, settings, etc).
As I am no longer on that install, I can't say more as to what caused the issue other than it possibly being caused by installing winget via another package manager, I believe it was chocolatey.
I currently have winget installed with no issues, installed from releases.
