### ISSUE TITLE
Specify installer mode in settings (default Silent with Progress)

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#1942]
### Description of the new feature / enhancement

I would like to be able to specify my default installer mode in settings.

If I make "Silent" my preference, packages will be installed with the default "Silent with Progress" or "Interactive" if the package does not support "Silent".

>Note: changing the default behavior in the client is considered a breaking change. The default will continue to be "Silent with Progress".

**Comment by denelon** [comment]
Yes, I believe the general philosophy at this point it:

Reasonably sane default behavior that works for "most users".
Settings supports preferences to select the preference, but able to default to another option if one is available.
Settings supports requirements to select the requirement at the expense of not being able to continue the operation.
Command line arguments from user input override settings.

In this case, the default "Silent with Progress" is being maintained so we can avoid potentially breaking behavior.

**Comment by anthonyvdotbe** [comment]
What's the difference with #910, if any?

**Comment by denelon** [comment]
Duplicate of #910

**Comment by denelon** [comment]
Thanks @anthonyvdotbe
