### ISSUE TITLE
Automatic restart after visual studio update

### ISSUE THREAD

**Issue by DrDonkz** [microsoft/winget-cli#1957]
### Brief description of your issue

Computers automatically restart after receiving the new visual studio update. This issue started yesterday, and hasn't been happening in the past 2 weeks before yesterday. Maybe an idea to disable automatic reboots when winget --upgrade all is being run?

### Steps to reproduce

install an old version of visual studio 2019, then update using winget.

### Expected behavior

App updates, but a reboot should be pending

### Actual behavior

Students got a restarting computer during the middle of some exams because the PC started updating visual studio and didnt prompt or anything about a restart coming.

### Environment

```shell
Windows Package Manager (Preview) v1.2.3411-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.526
Package: Microsoft.DesktopAppInstaller v1.17.3411.0
```

**Comment by denelon** [comment]
This is likely due to a runtime requiring a reboot to ensure the right version is invoked. We see this in some cases with VC++ runtimes. 

We've got a few features for suppressing reboots and other related behavior in teh backlog, but that could cause a torn state with Visual Studio. We may need to see if we can detect which packages have this kind of behavior and prompt before the install continues. One of the other challenges is related to a goal of unattended installs for `winget import`.

**Comment by denelon** [comment]
It's been a while since this issue was reported, and WinGet now defaults to deferred reboot. Is this issue still happening?

**Comment by DrDonkz** [comment]
Good afternoon,

I haven't run into the issue for quite a while, so I think it's fixed. Thank you!



Kind regards,

Max Jonkers
IT-Department

E   ***@***.***

 [https://attachments.office.net/owa/m.jonkers%40sgdelangstraat.nl/service.svc/s/GetAttachmentThumbnail?id=AAMkADI1NmMxZTQ5LWMxOGQtNGYwNC05MzU3LWM2MjMxODI3OTk5YwBGAAAAAABVOMApctrnQJP09BXvJpIbBwAvA6%2FteJplT5CIW9pZ9gkXAAAAAAEMAAAvA6%2FteJplT5CIW9pZ9gkXAAQPWp1xAAABEgAQAMCivyfjyv1At7D4b3X5xPU%3D&thumbnailType=2&token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkQ4OThGN0RDMjk2ODQ1MDk1RUUwREZGQ0MzODBBOTM5NjUwNDNFNjQiLCJ0eXAiOiJKV1QiLCJ4NXQiOiIySmozM0Nsb1JRbGU0Tl84dzRDcE9XVUVQbVEifQ.eyJvcmlnaW4iOiJodHRwczovL291dGxvb2sub2ZmaWNlLmNvbSIsInVjIjoiMDZkZmYzZWI5YmQ4NGM0MWI5MmFlNTYxN2ZkZDQzZWYiLCJzaWduaW5fc3RhdGUiOiJbXCJkdmNfbW5nZFwiLFwiZHZjX2NtcFwiLFwiaW5rbm93bm50d2tcIixcImttc2lcIl0iLCJ2ZXIiOiJFeGNoYW5nZS5DYWxsYmFjay5WMSIsImFwcGN0eHNlbmRlciI6Ik93YURvd25sb2FkQGY2NjhiNDljLTRhYjQtNDhjMi1hNjljLTQ2MWY2ODNhNTA0YiIsImlzc3JpbmciOiJXVyIsImFwcGN0eCI6IntcIm1zZXhjaHByb3RcIjpcIm93YVwiLFwicHVpZFwiOlwiMTE1Mzk3NzAyNTYxNjU3MTUxM1wiLFwic2NvcGVcIjpcIk93YURvd25sb2FkXCIsXCJvaWRcIjpcImNlOWRlMzRmLTVlNmUtNDI4Zi05NTBlLWUwN2E0NDIyMzI5YlwiLFwicHJpbWFyeXNpZFwiOlwiUy0xLTUtMjEtMjIxODg2ODYyOS02MTQyNzE2MDQtMzcyMzY4MzI3Ny02MDE4MzkwXCJ9IiwibmJmIjoxNjc5ODk5MTA0LCJleHAiOjE2Nzk4OTk3MDQsImlzcyI6IjAwMDAwMDAyLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMEBmNjY4YjQ5Yy00YWI0LTQ4YzItYTY5Yy00NjFmNjgzYTUwNGIiLCJhdWQiOiIwMDAwMDAwMi0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvYXR0YWNobWVudHMub2ZmaWNlLm5ldEBmNjY4YjQ5Yy00YWI0LTQ4YzItYTY5Yy00NjFmNjgzYTUwNGIiLCJoYXBwIjoib3dhIn0.lon-4MW6Wb9grCofPbsbYqLN83JOK8i2YPkV3vHbzq9-6tA0MYtbMekdof1axEs7lJkJvJJ-cw1KOS3kWg7o2yhSbbotgOvjMfyqIow0K6SE5to4qzgbN2Fo4uMcrzeOlLesUGhtHPa9TN6QLFqhn3q_tEbMaK-kcHQcisxoiyZlELwSS8RmU1AvAiLuCvzP430dhDlavP9nUvXvygZYTfzh0SZmH0vqaop-U84A6R5SdvvuSEFcQmXqVvRwhylCCJUbZD0C8ddUFf2MQX6loHuaH68Y9KZSOOhiuzA9g13SvU92d3k_vJGE83r6rDOLaBqGAYeN-XkFoXzAjeY2wg&X-OWA-CANARY=u2AW0teNMkCpE-CHrU7PE6Awd6ihLtsYeLoH0diaCXZXbpHXZiuIRijKeGfQi3VVzlxY1refCRk.&owa=outlook.office.com&scriptVer=20230310007.21&animation=true]

 Olympiaweg 8b | 5143 NA Waalwijk | T 0416 67 39 30

OMO Scholengroep De Langstraat bestaat uit het Dr. Mollercollege,
het d'Oultremontcollege, het Van Haestrechtcollege, Walewyc-mavo en de Overlaat.

Disclaimer
Dit e-mailbericht is slechts bestemd voor de geadresseerde en kan informatie bevatten die persoonlijk of vertrouwelijk is en niet openbaar mag worden gemaakt. Indien een ander dan geadresseerde dit e-mailbericht ontvangt of anderszins in handen krijgt, is hij niet gerechtigd tot kennisneming, verspreiding of vermenigvuldiging daarvan.

________________________________
Van: Demitrius Nelon ***@***.***>
Verzonden: woensdag 12 juni 2024 01:46
Aan: microsoft/winget-cli ***@***.***>
CC: Max Jonkers ***@***.***>; Author ***@***.***>
Onderwerp: Re: [microsoft/winget-cli] Automatic restart after visual studio update (Issue #1957)


It's been a while since this issue was reported, and WinGet now defaults to deferred reboot. Is this issue still happening?
