### ISSUE TITLE
Output can't be used with Powershell

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/winget-cli#196]
# Brief description of your issue

`winget.exe show | select 'Name'`

Returns blank results. It looks like the output for winget isn't consistent with Powershell, which is the default shell in Windows.

# Expected behavior

I should be able to start powershell via `Win X` and use winget.

# Actual behavior

`winget` outputs unstructured data.

# Environment

```Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19613.1005
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

Links:
  Privacy Statement: https://aka.ms/winget-privacy
  License agreement: https://aka.ms/winget-license
  3rd Party Notices: https://aka.ms/winget-3rdPartyNotice
  Homepage:          https://aka.ms/winget
```

**Comment by jantari** [comment]
That is to be expected and cannot be solved.

I think what you're really asking for is perhaps a `-j` switch (or similar) that causes winget to output structured data in JSON etc. then you can `winget.exe show -j | convertfrom-json | select name`

**Comment by mikemaccana** [comment]
Is the intention that users launch cmd to run winget?

**Comment by AspenForester** [comment]
Rolling out a new tool in 2020 as an exe instead of, or at least, without a set of native PowerShell Commands seems, well, surprising.  But I also feel like this happened with Project Honolulu, too, where the project team completely missed the desires of the target audience on the first release.

**Comment by ThomasNieto** [comment]
Created https://github.com/microsoft/winget-cli/issues/221 for native PowerShell cmdlets.

**Comment by KevinMarquette** [comment]
Definitely provide json output support. I'm done with parsing standard output.

**Comment by denelon** [comment]
It looks like Issue #184 covers JSON output.

**Comment by denelon** [comment]
It looks like two features were created to address this concern. @mikemaccana if you believe they don't address this Issue please create a new one. #184 #221

**Comment by mikemaccana** [comment]
#184 and #221 doesn't address the concern as windows commands should output structured data by default. `winget.exe show | select 'Name'` won't work. It should work. 

@denelon: powershell is the default terminal for windows. winget should support Windows defaults, and not need extra winget-specific steps like outputting a different format and then converting from it. 

If the `winget` team doesn't want to support powershell by default, then why?

**Comment by jantari** [comment]
> @denelon: if the `winget` team doesn't want to support Windows' standard shell, then why?

One possible reason is that PowerShell is not in WinPE (by default) and also not in Windows Server Nano. It would be nice for a package manager to work on Windows Nano.

Also, PowerShell cmdlets must be written in PowerShell or C#. They are going to be slower than this app, which is native C++.

But that is only a guess, I don't know their reasons.
