### ISSUE TITLE
Add `winget remove` as an alias command for `winget uninstall`

### ISSUE THREAD

**Issue by adityamwagh** [microsoft/winget-cli#1978]
### Description of the new feature / enhancement

Most popular package managers (`apt`, `dnf`) have `remove` as the argument to uninstall/remove the packages from the system. I feel `winget` should also provide this functionality. This seems very easy to implement, and shouldn't take much time.

Cheers!

### Proposed technical implementation details

When the argument parser reads `remove`, call the method to `uninstall`! As simple as that!

**Comment by Trenly** [comment]
If anyone has any strong opinions on aliases, i.e, if any others should be added, please post a comment on the linked PR

**Comment by xtqqczze** [comment]
See also: #2430
