### ISSUE TITLE
URGENT `winget install julia -s msstore` just started to install some random software

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/winget-cli#2005]
### Brief description of your issue

We have an installer for the [Julia programming language](https://julialang.org/) in the Windows store, see [here](https://www.microsoft.com/en-us/p/julia/9njnww8pvkmn). For quite a while we have instructed users to install Julia on Windows by running `winget install julia -s msstore`, and that has always worked flawlessly.

Sometime in the last days or so, this completely broke, and the command now installs some other software from the Windows Store named `Julian Date Selector`. This is, to put it mildly, a disaster. We really need our software delivery technology to install our software, not something else... Could you please try to give this a very high priority so that this is fixed ASAP? Having errors like this linger around for any even marginally extended period of time really would mean that we would have to reconsider whether this whole store/winget/msix tech stack is reliable enough for us...

Some other diagnostics:

The command `winget search julia` currently produces
```
Name                 Id              Version Source
-----------------------------------------------------
Julian Date Selector 9NSGP4VDNW0R    Unknown msstore
Julia                Julialang.Julia 1.7.2   winget
```
whereas `winget search 9njnww8pvkmn` produces
```
Name  Id           Version Source
-----------------------------------
Julia 9NJNWW8PVKMN Unknown msstore
```
That also seems wrong?

### Steps to reproduce

Run `winget install julia -s msstore`.

### Expected behavior

That should install https://www.microsoft.com/en-us/p/julia/9njnww8pvkmn.

### Actual behavior

It actually installs https://www.microsoft.com/en-us/p/julian-date-selector/9nsgp4vdnw0r instead.

### Environment

```shell
winget --info
Windows Package Manager (Preview) v1.2.3131-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1566
Package: Microsoft.DesktopAppInstaller v1.17.3131.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by ItzLevvie** [comment]
There's an issue with the Microsoft Store source; tracked at https://github.com/microsoft/winget-cli/issues/1988.

cc @denelon

**Comment by davidanthoff** [comment]
Oh wow, does this mean this has been broken for five days already? I really hope this is an all-hands-on-deck situation at MS.

**Comment by denelon** [comment]
Related to:
* #1988

**Comment by davidanthoff** [comment]
Yes, seems the same issue, I'll close here.
