### ISSUE TITLE
winget (v1.2) upgrade --all --silent only installs the first package silently

### ISSUE THREAD

**Issue by o-l-a-v** [microsoft/winget-cli#2008]
### Brief description of your issue

```winget upgrade --all --silent``` only installs the first package silently. The rest shows progress.

I had following upgrades available when running ```winget upgrade```.

```
Name                                               Id                                Version       Available     Source
-----------------------------------------------------------------------------------------------------------------------
Microsoft Teams                                    Microsoft.Teams                   1.5.00.2164   1.5.00.4689   winget
Microsoft Visual C++ 2015-2022 Redistributable (x… Microsoft.VC++2015-2022Redist-x86 14.31.30919.0 14.31.31103.0 winget
Microsoft Teams                                    Microsoft.Teams                   1.4.0.19572   1.5.00.4689   winget
Microsoft Visual C++ 2015-2022 Redistributable (x… Microsoft.VC++2015-2022Redist-x64 14.31.30919.0 14.31.31103.0 winget
Eclipse Temurin JDK with Hotspot 11                EclipseAdoptium.Temurin.11        11.0.12.7     11.0.14.101   winget
5 upgrades available.
```

First Teams installed silently, but neither of the VCRedist or JDK did.

### Steps to reproduce

Have more than one package to upgrade, then:

* ```winget upgrade --all --silent```

### Expected behavior

All packages should install silently.

### Actual behavior

Only the first package installs silently.

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1586
Package: Microsoft.DesktopAppInstaller v1.17.10271.0
```

**Comment by o-l-a-v** [comment]
In this example, "MKVToolnix" updated silently, but "Oh My Posh" didn't.

![image](https://user-images.githubusercontent.com/6450056/158382047-3106ec34-03ef-4348-974d-7795ca1b07ae.png)

**Comment by ppvnf** [comment]
--silent doesn't properly work for me sometimes (it shows a pop-up briefly). I don't think there's any pattern tho. Some packages are silent and other aren't

**Comment by Spacellary** [comment]
Same behavior here when doing `winget upgrade --all --silent` with things like VSCode for example.

**Comment by Blattinum** [comment]
Same thing here. The first one—GitHub Desktop—upgraded silently fine, but the rest of the queue (M365 apps, Git, Visual Studio libraries, etc.) popped up GUIs.

**Comment by o-l-a-v** [comment]
Tried v1.4.3531 now, it shows a different behavior: First package was not installed silently, but the second one was.

<details><summary>Output from CMD</summary>

```
C:\Users\olavb\Desktop\Winget>winget.exe --version
v1.4.0

C:\Users\olavb\Desktop\Winget>winget.exe upgrade
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

Do you agree to all the source agreements terms?
[Y] Yes  [N] No: y
Name                       Id                      Version Available Source
---------------------------------------------------------------------------
Oh My Posh version 12.28.1 JanDeDobbeleer.OhMyPosh 12.28.1 12.28.2   winget
Obsidian                   Obsidian.Obsidian       1.0.3   1.1.8     winget
2 upgrades available.

C:\Users\olavb\Desktop\Winget>winget upgrade --all --silent
Name                       Id                      Version Available Source
---------------------------------------------------------------------------
Oh My Posh version 12.28.1 JanDeDobbeleer.OhMyPosh 12.28.1 12.28.2   winget
Obsidian                   Obsidian.Obsidian       1.0.3   1.1.8     winget
2 upgrades available.

(1/2) Found Oh My Posh [JanDeDobbeleer.OhMyPosh] Version 12.28.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v12.28.2/install-amd64.exe
  ██████████████████████████████  6.77 MB / 6.77 MB
Successfully verified installer hash
Starting package install...
Successfully installed

(2/2) Found Obsidian [Obsidian.Obsidian] Version 1.1.8
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/obsidianmd/obsidian-releases/releases/download/v1.1.8/Obsidian.1.1.8.exe
  ██████████████████████████████  64.6 MB / 64.6 MB
Successfully verified installer hash
Starting package install...
Successfully installed


C:\Users\olavb\Desktop\Winget>
```

</details>

**Comment by jonasjancarik** [comment]
I seem to still have this issue with `v1.5.441-preview`. I use this hacky one-liner as a workaround: `$output = winget upgrade; $colNum = ($output | Select-Object -Skip 2 -First 1 | Select-String -Pattern 'Id').Matches.Index; ($output | Select-Object -Skip 4 | Where-Object { $_ -ne '' } | ForEach-Object { Write-Output "ColNum: $colNum, Line: $_"; $_.Substring($colNum).Split(' ')[0] }) | ForEach-Object { Write-Output $_; winget upgrade --id $_ --silent }`

**Comment by denelon** [comment]
@jonasjancarik which package isn't installing/upgrading silently?

I'm curious if it's the update mechanism in the package as opposed to WinGet failing to honor the switch.

**Comment by jonasjancarik** [comment]
Good question, I will try to figure out. It's true the original issue was that any package that was not the first one on the list wouldn't be installed silently, now it seems like it's only happening with specific packages. I'll report back.

**Comment by jonasjancarik** [comment]
I think you're right. It seems to have been an issues with `PostgreSQL.PostgreSQL` which was displaying an unzipping dialog for some reason.

**Comment by visschersm** [comment]
I had an popup for Visual Studio BuildTools 2022 as well. Though it is nice to have way less pop ups since using version 1.4

**Comment by o-l-a-v** [comment]
This issue is not fixed @florelis, @denelon.

I tried `--all --silent` today in CMD first running as user for 2 of 5 programs, all showed progress. Then tried in CMD running as admin for the three remaining programs, all showed progress. I know these installers doesn't show progress when `--upgrade --silent --id <id>`.

Logs however says that silent switch is specified. But I'm lead to believe that logs does not show what is actually sent to the installer.

Windows 10 22H2 19045.2846.
Winget 1.4.10173 from App Installer 1.19.10173.0 from Microsoft Store.

Programs upgraded, which all install silently with no progress if `--upgrade --silent --id <id>`:

* Foxit.FoxitReader
* Git.Git
* JanDeDobbeleer.OhMyPosh
* Nlitesoft.NTLite
* WinMerge.WinMerge (also prompted to restart `explorer.exe` after upgrade completed)

Logs: [DiagOutputDir.zip](https://github.com/microsoft/winget-cli/files/11364580/DiagOutputDir.zip)

**Comment by florelis** [comment]
@o-l-a-v 
The fix is not on v1.4. You'd have to be on v1.5 preview.
On the [releases page](https://github.com/microsoft/winget-cli/releases) you can see which changes are on each release. The fix for this was #2794 which only got picked up starting on [v1.5.101-preview](https://github.com/microsoft/winget-cli/releases/tag/v1.5.101-preview)

The installer logs show that the /SILENT flag was passed, so we can be sure winget sent the args. But I think the combination of flags in this case actually amount to "silent with progress" instead of "silent".

**Comment by seidorveritas** [comment]
Hello,

issue still occuring in `winget update --all --silent` with Winget v1.7.10582

**Comment by o-l-a-v** [comment]
@seidorveritas 

Not for me. If you don't provide logs and the list of packages you tried to upgrade this is impossible to troubleshoot.

**Comment by rafaelsnv** [comment]
@o-l-a-v

Commented with wrong accout, here is the log file:

[WinGet-2024-03-01-10-41-07.760.log](https://github.com/microsoft/winget-cli/files/14462586/WinGet-2024-03-01-10-41-07.760.log)

If you need any other files, just let me know.

**Comment by o-l-a-v** [comment]
@rafaelsnv 

I'm not a maintainer in this project, just a user that faced the same problem with an earlier version of Winget. :)

Just thought that saying "it doesn't work" with no logs, terminal output etc. isn't very helpful.

Would be helpful to know what package showed progress.

**Comment by rafaelsnv** [comment]
Hello again,

Here is an output from my last `winget update --all --silent` :

```Windows PowerShell
Copyright (C) Microsoft Corporation. Todos os direitos reservados.

Experimente a nova plataforma cruzada PowerShell https://aka.ms/pscore6

PS C:\Users\Rafael Vieira> winget update
Nome                                             ID                                Versão         Disponível     Origem
-----------------------------------------------------------------------------------------------------------------------
Foxit PDF Reader                                 Foxit.FoxitReader                 2023.3.0.23028 2024.1.0.23997 winget
Microsoft Edge                                   Microsoft.Edge                    122.0.2365.66  122.0.2365.80  winget
GitKraken                                        Axosoft.GitKraken                 9.11.0         9.13.0         winget
Microsoft Windows Desktop Runtime - 6.0.21 (x86) Microsoft.DotNet.DesktopRuntime.6 6.0.21         6.0.27         winget
Microsoft Visual Studio Code (User)              Microsoft.VisualStudioCode        1.87.0         1.87.1         winget
6 atualizações disponíveis.

Os pacotes a seguir têm uma atualização disponível, mas exigem uma segmentação explícita para atualização:
Nome    ID              Versão   Disponível Origem
--------------------------------------------------
Discord Discord.Discord 1.0.9034 1.0.9035   winget
PS C:\Users\Rafael Vieira> winget update --all --silent
Nome                                             ID                                Versão         Disponível     Origem
-----------------------------------------------------------------------------------------------------------------------
Foxit PDF Reader                                 Foxit.FoxitReader                 2023.3.0.23028 2024.1.0.23997 winget
Microsoft Edge                                   Microsoft.Edge                    122.0.2365.66  122.0.2365.80  winget
GitKraken                                        Axosoft.GitKraken                 9.11.0         9.13.0         winget
Microsoft Windows Desktop Runtime - 6.0.21 (x86) Microsoft.DotNet.DesktopRuntime.6 6.0.21         6.0.27         winget
Microsoft Visual Studio Code (User)              Microsoft.VisualStudioCode        1.87.0         1.87.1         winget
6 atualizações disponíveis.

Os pacotes a seguir têm uma atualização disponível, mas exigem uma segmentação explícita para atualização:
Nome    ID              Versão   Disponível Origem
--------------------------------------------------
Discord Discord.Discord 1.0.9034 1.0.9035   winget

(1/4) Encontrado Foxit PDF Reader [Foxit.FoxitReader] Versão 2024.1.0.23997
Este aplicativo é licenciado para você pelo proprietário.
A Microsoft não é responsável por, nem concede licenças a pacotes de terceiros.
Baixando https://cdn01.foxitsoftware.com/product/reader/desktop/win/2024.1.0/FoxitPDFReader20241_L10N_Setup.exe
  ██████████████████████████████   267 MB /  267 MB
Hash do instalador verificado com êxito
Iniciando a instalação do pacote...
   /

     Now installing, please wait...
   |

     Setup failed.
O instalador falhou com o código de saída: 1603
O registro do instalador está disponível em: C:\Users\Rafael Vieira\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Foxit.FoxitReader.2024.1.0.23997-2024-03-08-15-04-17.747.log

(2/4) Encontrado GitKraken [Axosoft.GitKraken] Versão 9.13.0
Este aplicativo é licenciado para você pelo proprietário.
A Microsoft não é responsável por, nem concede licenças a pacotes de terceiros.
Baixando https://release.axocdn.com/windows/GitKrakenSetup.exe
  ██████████████████████████████   231 MB /  231 MB
Hash do instalador verificado com êxito
Iniciando a instalação do pacote...
Instalado com êxito

(3/4) Encontrado Microsoft .NET Windows Desktop Runtime 6.0 [Microsoft.DotNet.DesktopRuntime.6] Versão 6.0.27
Este aplicativo é licenciado para você pelo proprietário.
A Microsoft não é responsável por, nem concede licenças a pacotes de terceiros.
Baixando https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/6.0.27/windowsdesktop-runtime-6.0.27-win-x64.exe
  ██████████████████████████████  54.6 MB / 54.6 MB
Hash do instalador verificado com êxito
Iniciando a instalação do pacote...
Instalado com êxito

(4/4) Encontrado Microsoft Visual Studio Code [Microsoft.VisualStudioCode] Versão 1.87.1
Este aplicativo é licenciado para você pelo proprietário.
A Microsoft não é responsável por, nem concede licenças a pacotes de terceiros.
Baixando https://vscode.download.prss.microsoft.com/dbazure/download/stable/1e790d77f81672c49be070e04474901747115651/VSCodeUserSetup-x64-1.87.1.exe
  ██████████████████████████████  93.5 MB / 93.5 MB
Hash do instalador verificado com êxito
Iniciando a instalação do pacote...
Instalado com êxito

3 pacotes têm números de versão que não podem ser determinados. Use --include-unknown para ver todos os resultados.
1 os pacotes estão fixados e precisam ser atualizados explicitamente.
PS C:\Users\Rafael Vieira>```

All packages have displayed the confirmation popup.

Regards

**Comment by o-l-a-v** [comment]
@rafaelsnv 

Confirmation as in admin ellevation / consent? 🤔

**Comment by rafaelsnv** [comment]
@o-l-a-v 

Yes it is.

Actually after your question, I noticed that the error might be related to the Windows Terminal app. 
I ran the command directly from CMD (as administrator) and the popups did not appear.

Maybe this is a new issue? 😅

**Comment by o-l-a-v** [comment]
@rafaelsnv 

Yes. If you install apps that requires admin permission, either run CMD / PowerShell / Terminal as admin and don't get prompted with UAC for each app, or don't and get prompted with UAC for each app. This is expected behavior. 🙂
