### ISSUE TITLE
Specify where tool is located for ZIP installers

### ISSUE THREAD

**Issue by heaths** [microsoft/winget-cli#202]
For nuget-packaged tool installers, tools are often in a "tools" subdirectory of the .nupkg - a ZIP file using the OPC standard. It would be great if developer could specify the subdirectory that should be added to the `PATH` environment variable, assuming that is within the future scope of this project, as Chocolatey and Scoop already support.

**Comment by denelon** [comment]
This looks like it may be a duplicate of #140

**Comment by denelon** [comment]
Duplicate of #140
