### ISSUE TITLE
"upgrade --all" states that apps are upgraded, but they aren't

### ISSUE THREAD

**Issue by weiss-d** [microsoft/winget-cli#2027]
### Brief description of your issue

Winget finds a bunch of apps to upgrade, runs the installers successfully, but as a result apps are not being upgraded.

### Steps to reproduce

I.e. I have foobar2000 v1.6.7
`winget upgrade` says it has v1.6.10 (see screenshot). Then I run `winget upgrade PeterPawlowski.foobar2000` and in seems to install it correctly according to the output (see screenshot).

### Expected behavior

Then when I run foobar2000 after update I should see v1.6.10...

### Actual behavior

... but I still have 1.6.7 (see screenshot), and when I run `winget upgrade` once again it shows me that 1.6.10 available.

The same situation repeats for 5-10 apps each time (now it repeats for all apps listed in the screensot).

![image](https://user-images.githubusercontent.com/62437174/158740817-fd3bf046-4fb1-4b1a-9eab-b065394485b4.png)

### Environment

```shell
PS C:\Users\weiss-d> winget --info
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1586
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

...
```
```

**Comment by denelon** [comment]
Is upgrade installing the new version as a separate "side by side" package? What do you see in Windows Apps & Features?

You can also run `winget list foo` to search installed programs with "foo" in their name.

**Comment by weiss-d** [comment]
@denelon looks like it's not the case

```
PS C:\Users\weiss-d> winget list foobar
Name       Id                        Version Available Source
-------------------------------------------------------------
foobar2000 PeterPawlowski.foobar2000 1.6.7   1.6.10    winget
```

**Comment by denelon** [comment]
Would you mind running `winget upgrade foobar2000 --verbose-logs` and sharing the output, or submitting feedback via https://aka.ms/winget-feedback so we can get the logs? I'm wondering if we're detecting a false positive from an installer launching a child process or if something else is happening.

**Comment by Trenly** [comment]
Just want to add in that I'm not seeing this behavior in the sandbox using client v1.2.10271
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Windows\system32> winget source remove msstore
Removing source: msstore...
Done
PS C:\Windows\system32> winget install foobar2000 -v 1.6.7
Found foobar2000 [PeterPawlowski.foobar2000] Version 1.6.7
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.foobar2000.org/files/foobar2000_v1.6.7.exe
  ██████████████████████████████  4.55 MB / 4.55 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\Windows\system32> winget list foobar
Name       Id                        Version Available
------------------------------------------------------
foobar2000 PeterPawlowski.foobar2000 1.6.7   1.6.10
PS C:\Windows\system32> winget upgrade foobar2000 --verbose-logs
Found foobar2000 [PeterPawlowski.foobar2000] Version 1.6.10
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.foobar2000.org/files/foobar2000_v1.6.10.exe
  ██████████████████████████████  4.55 MB / 4.55 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\Windows\system32> winget list foobar
Name       Id                        Version
--------------------------------------------
foobar2000 PeterPawlowski.foobar2000 1.6.10
```

**Comment by weiss-d** [comment]
Looks like `--verbose-logs` doesn't change the output.

```
PS C:\Users\weiss-d> winget upgrade foobar2000 --verbose-logs
Found foobar2000 [PeterPawlowski.foobar2000] Version 1.6.10
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.foobar2000.org/files/foobar2000_v1.6.10.exe
  ██████████████████████████████  4.55 MB / 4.55 MB
Successfully verified installer hash
Starting package install...
Successfully installed

PS C:\Users\weiss-d> winget list foobar
Name       Id                        Version Available Source
-------------------------------------------------------------
foobar2000 PeterPawlowski.foobar2000 1.6.7   1.6.10    winget
PS C:\Users\weiss-d>
```

I use genuine win10pro with the latest updates btw.

**Comment by ItzLevvie** [comment]
You're seeing this issue because `PeterPawlowski.foobar2000` requires administrator privileges.

So `ElevationRequirement: elevationRequired` would solve this problem once WinGet gets support for it in future releases.

**Comment by weiss-d** [comment]
But how I could installed it in the first place without Administrator privileges then?

**Comment by denelon** [comment]
The installer may not have the logic to warn the user. I've seen that behavior with several different packages. The installer may also not trigger the UAC to get administrative permission even if it can detect it as well. There are many variables at play.

**Comment by denelon** [comment]
You may see different behavior if you pass "--interactive" to get an interactive install. Sometimes the silent install flags bypass extra behavior for installers that has been built into the interactive mode.

**Comment by weiss-d** [comment]
@denelon thank you! Updating with `--interactive` flag did the job.

**Comment by denelon** [comment]
I don't know if there is a specific flag we could pass to the installer to get a failure we could act on, but that may be possible.
