### ISSUE TITLE
Add list option to format output as json

### ISSUE THREAD

**Issue by MrDRamos** [microsoft/winget-cli#2032]
### Description of the new feature / enhancement

The list command outputs a human readable table of installed packages that is not easy to parse by an external tool. Formatting the list output as JSON by adding a --JsonOutput command line option would be very useful.

**Comment by denelon** [comment]
We've discussed having "--json" as an argument to do exactly this, but hadn't created an issue for it :)

**Comment by MiroslavMikus** [comment]
I am playing with it right now and thought how good it would be to have the `--json` parameter.
For someone having the same problem right now  -> [Here](https://www.codewrecks.com/post/general/winget-update-selective/) is a nice Powershell script which can parse the output to a custom object. Just be aware that the table heders are important and they are OS language-dependent 😄

**Comment by WillPittenger** [comment]
It's strange a `--as-yaml` option wasn't baked into `winget search` and `winget show` from day one.  Just spit out the YAML as you get it.  The existing system almost seems designed to make parsing impossible.  How much work would be needed to implement either YAML or JSON output?

**Comment by MrDRamos** [comment]
I agree 100% with PowerShell support! The reason JSON output was requested is because it is readily consumed by PowerShell.

**Comment by CoryG89** [comment]
Not sure if everyone is aware of this already or not, but for those that are looking to get winget search results in JSON format, I was looking for the same and came upon the winget.run REST API which serves my purposes fine for now until winget itself is able to provide the same functionality.

https://docs.winget.run/docs/introduction/

https://github.com/winget-run/wingetdotrun

**Comment by alexandair** [comment]
Instead of `--json` or `--jsonoutput`, I would suggest implementing `--output` that can accept `json` as a value and maybe some other values in the future. Just how Azure CLI does today.

**Comment by denelon** [comment]
In addition to the PowerShell module, COM APIs are also available for object-based integration.

**Comment by youk** [comment]
@denelon PowerShell module and COM APIs obviously don't cover all use cases. What about those who don't use PowerShell? Please reopen the issue as it asked for **a command-line switch**.
