### ISSUE TITLE
Add list option to filter out entries that have a newer version available

### ISSUE THREAD

**Issue by MrDRamos** [microsoft/winget-cli#2033]
### Description of the new feature / enhancement

I would like to quickly get a list off all installed packages that are outdated before invoking an upgrade. 

### Proposed technical implementation details

Add a command line option to the list command e.g --outdated that filters the results to only show packages that have a newer version available

**Comment by Trenly** [comment]
Try `winget upgrade` without any arguments

**Comment by MrDRamos** [comment]
Thank you, that does exactly what I was looking for!
I did not see this feature in the documentation. 
Personally I still think it more intuitive to get this output by specifying an explicit option, because it makes the users intention clear.

**Comment by Trenly** [comment]
@denelon - Has this been resolved with the above PR?
