### ISSUE TITLE
can't launch winget 

### ISSUE THREAD

**Issue by jochen1727** [microsoft/winget-cli#2040]
### Brief description of your issue

Hi,
I have created a master and syspreped my windows master but after rebooting, I cant' launch winget.
However when I execute the command get-appxprovisionedpackage -online I ve got Microsoft.Desktopappinstaller present.
I ve checked the value of my environment variable path and microsotftapps location variable is present.
I think the issue come from sysprep step where that delete all files into microsoftapps folder.
Could i install winget in programfiles folder instead user's folder?

Thank you for you help

**Comment by denelon** [comment]
@jochen1727 I'm guessing you have an older version of "App Installer" on the system. The Windows Package Manager isn't in the base OS image. It requires an update from the Microsoft Store to get the Windows Package Manager.

**Comment by jochen1727** [comment]
@ denelon I ve got windows 11 pro with last updates.

**Comment by denelon** [comment]
Which version of App Installer is present?

https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting

**Comment by jochen1727** [comment]
Version 1.18.
I think that append when I sysprep my windows that erase all filles in my 
C:\Users\Administrateur\AppData\Local\Microsoft\WindowsApps 
and when I log in at reboot, no more winget!!!!
I thought as it was in AppxprovisionedPackage and it would reinstall automatically.

**Comment by jedieaston** [comment]
I think that's expected on a sysprep.

@denelon is there any chance a App Installer w/ winget will make it into the ISO before 22H2? It'd still be nice to have winget (and a more up-to-date Microsoft Store) available when bootstrapping new machines.

**Comment by denelon** [comment]
@jedieaston it's a bit more complicated than that, but I believe we will be in the next ISO unless some other process change is happening.

**Comment by jochen1727** [comment]
Any ideas on how to reinstall winget after syspreping ?

Because Microsoft.DesktopAppInstaller is on my windows image, should it be installed for each new user?

Thks guys

**Comment by denelon** [comment]
It will require either getting the upgraded "App Installer" from the store, or installing a version of the App Installer from the releases in this repository.

**Comment by denelon** [comment]
@jochen1727 I've been digging through some of the documentation issues. I was wondering if this has been resolved now that WinGet is included in the base OS image?
