### ISSUE TITLE
WinGet showing that PowerShell needs to have an update when it is in the version of the update.

### ISSUE THREAD

**Issue by fgclue** [microsoft/winget-cli#2047]
### Brief description of your issue

So well, I was updating my applications when I saw that it said PowerShell (Microsoft.PowerShell) Needed an update. It said that the version I'm using was 7.2.1, While I was using 7.2.2. Here's the images.

[Image 1](https://i.imgur.com/REEFWeA.png)
[Image 2](https://i.imgur.com/fayhPIx.png)

If this is able to be fixed, Please do it.

This issue took very long to write.

### Steps to reproduce

Note: I don't know if this works for other people.

Step 1:

Download App Installer on the Microsoft Store

Step 2:

Run winget install Microsoft.PowerShell

`winget install Microsoft.PowerShell`

Step 3:

Check if PowerShell is in 7.2.2

```
C:\Directory> pwsh
PowerShell Version 7.2.2
```

Step 4:

Run winget upgrade

`winget upgrade`

And done!

You'll See This:
```
C:\Directory> winget upgrade

Name                            Id                            Version      Available    Source
----------------------------------------------------------------------------------------------
PowerShell                      Microsoft.PowerShell          7.2.1.0      7.2.2.0      winget
```

That's how you do the bug.

### Expected behavior

I was expecting to PowerShell not appear when I run `winget upgrade`.

### Actual behavior

It says that PowerShell needs an update but it doens't.

### Environment

```shell
C:\Directory> winget --info

Windows Package Manager (Preview) v1.2.0-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.527

Logs: %TEMP%\WinGet

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

C:\Directory>
```

**Comment by ItzLevvie** [comment]
I'm unable to reproduce:
![image](https://user-images.githubusercontent.com/11600822/160249128-92fda43f-f661-494d-958c-5b3fc6e0e3a3.png)

What does it show in Apps & features?

This is what I see:
![image](https://user-images.githubusercontent.com/11600822/160249160-ab6d2ec2-3aca-45f3-bdd9-bdb9ec1b353b.png)

**Comment by fgclue** [comment]
No, It doens't show it was 7.2.1.0. It shows was 7.2.2.0. Maybe this only happens for me?

**Comment by Ayamigah16** [comment]
I did the above installation and tried starting my vagrant ubuntu, but this came up:

The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.

  Installed version: N/A
  Minimum required version: 3
