### ISSUE TITLE
An even better progress bar

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#2055]
### Description of the new feature / enhancement

@chausner noticed the progress bar could be improved. 

### Proposed technical implementation details

This enhances the progress bar to use more fine-grained blocks, in steps of 1/8 of the width of a block, by leveraging the [Block Element](https://www.fileformat.info/info/unicode/block/block_elements/list.htm) Unicode characters.

E.g. before:

![image](https://user-images.githubusercontent.com/15180557/160217308-f5a410f5-296a-4b20-9f72-9ef0713cb092.png)

After:

![image](https://user-images.githubusercontent.com/15180557/160217225-c5e8c711-37dd-4880-a22c-94244a2f3b38.png)

**Comment by denelon** [comment]
@JohnMcPms thinks it's Smooooooooth...

![smooth](https://user-images.githubusercontent.com/11687500/160909899-b63bfbd1-8e05-4292-8e48-c363d0c3299e.gif)

**Comment by sba923** [comment]
What I currently get seems to use the "partial box" glyphs in the wrong order:

![Administrator_ PowerShell - 7 2 6 2022-08-17 20-27-36](https://user-images.githubusercontent.com/12860484/185377318-d332b410-c386-4cce-948a-b8bd09b213d0.gif)

**Comment by denelon** [comment]
@chausner would you mind taking a look?

**Comment by chausner** [comment]
@sba923 What font are you using in the terminal? If it's a custom font, can you please try switching to a default font temporarily and check whether the problem persists?

**Comment by sba923** [comment]
Of course, this had to be a font problem.

With `Cascadia Code` the behavior is correct.

With `CaskaydiaCove NF` (my default font needed by `oh-my-posh`), the behavior is not correct.

I'll check the glyphs used by the new progress bar in the two fonts, and will most likely report an issue for `CaskaydiaCove NF`.

**Comment by sba923** [comment]
Of course, this had to be a font problem.

With `Cascadia Code` the behavior is correct.

With `CaskaydiaCove NF` (my default font needed by `oh-my-posh`), the behavior is not correct.

I'll check the glyphs used by the new progress bar in the two fonts, and willort an issue for `CaskaydiaCove NF`.

**Comment by sba923** [comment]
QED

With `Cascadia Code`:

<img width="646" alt="image" src="https://user-images.githubusercontent.com/12860484/185502288-9398ff22-1253-4416-9b72-f3895d7f4820.png">

With `CaskaydiaCove NF`:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/12860484/185502438-c564c1e0-275b-4396-998a-07c639f25689.png">

**Comment by sba923** [comment]
The plot thickens: the required glyphs don't seem to exist in `CaskaydiaCove NF`:

![image](https://user-images.githubusercontent.com/12860484/185505125-13b2eccb-8a29-4c0b-a3db-f18165bd79c5.png)

<img width="358" alt="image" src="https://user-images.githubusercontent.com/12860484/185505164-49b894b3-ac00-42f9-b44e-17d4d84b25d4.png">

**Comment by denelon** [comment]
Hopefully they are willing to add them. It would be really cool if you could `winget upgrade CaskaydiaCove`:
* #166

**Comment by sba923** [comment]
Opened https://github.com/ryanoasis/nerd-fonts/issues/883

**Comment by sba923** [comment]
> What I currently get seems to use the "partial box" glyphs in the wrong order:
> 
> ![Administrator_ PowerShell - 7 2 6 2022-08-17 20-27-36](https://user-images.githubusercontent.com/12860484/185377318-d332b410-c386-4cce-948a-b8bd09b213d0.gif)
> 
> 

Isn't this a good enough reason to make the new smooth progress bar a configurable opt-in setting?

**Comment by sba923** [comment]
> Hopefully they are willing to add them. 

It's coming: https://github.com/ryanoasis/nerd-fonts/issues/883#issuecomment-1220267985

Tested OK with their latest build:

![image](https://user-images.githubusercontent.com/12860484/185586194-f94285ca-87db-4ea0-9f0a-a8a0c8727887.png)

**Comment by denelon** [comment]
@sba923 thanks for finding the root cause and raising the issue at nerd-fonts!

**Comment by sba923** [comment]
> @sba923 thanks for finding the root cause and raising the issue at nerd-fonts!

You're very welcome!

**Comment by sba923** [comment]
> It would be really cool if you could `winget upgrade CaskaydiaCove`:
> 
> * [Support for installation of fonts #166](https://github.com/microsoft/winget-cli/issues/166)

In the meantime, I'd like to know how to determine the versions of `Cascadia Code` and `CaskadiaCove NF` installed on my systems (from PowerShell, of course. What else? 😜)

**Comment by denelon** [comment]
> In the meantime, I'd like to know how to determine the versions of `Cascadia Code` and `CaskadiaCove NF` installed on my systems (from PowerShell, of course. What else? 😜)

I'll ask around.

**Comment by KK-Designs** [comment]
> @JohnMcPMS thinks it's Smooooooooth...
> 
> ![smooth](https://user-images.githubusercontent.com/11687500/160909899-b63bfbd1-8e05-4292-8e48-c363d0c3299e.gif) 

Does the wingetdev include an option for testing the upgrade command? If so, where can I download that?

**Comment by SCIEN-00** [comment]
I would like something like this:
![image](https://github.com/user-attachments/assets/bec6a337-2c9f-4ab5-86ef-14f034daed3d)
more information and cleaner imo 🤔
