### ISSUE TITLE
App Installer fails to install completely on Windows 10 v2004

### ISSUE THREAD

**Issue by jfro** [microsoft/winget-cli#206]
# Brief description of your issue
App Installer seems to not completely install properly on my machine running Windows insider version 2004. 
# Steps to reproduce
1. Enroll a machine into Windows Insider program, preview release ring
2. Update machine, so it's on version 2004
3. Enroll in preview program for winget
4. Use enroll email's link to App Installer on the Store to install it (seemed already installed?)
5. Try to find App Installer or the winget CLI tool

# Expected behavior
Expected to at least be able to use `winget` from powershell and I assume see an App Installer app when checking Start or searching for apps.

# Actual behavior
Got no winget in powershell & no sign of App Installer besides in apps settings for uninstall.

Dug into Event Viewer and saw some crashes related to App Installer being deployed & launched. Wasn't able to see how to do a Feedback Hub with the crash as there's never a prompt or UI to do one associated with the crash information.

# Environment
Windows 10 Version 2004 Build 19041.264
Dell XPS 15 7590
Since I have no winget to be found, here's info of the appx package for app installer:
```Name              : Microsoft.DesktopAppInstaller
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 1.0.32912.0
PackageFullName   : Microsoft.DesktopAppInstaller_1.0.32912.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.0.32912.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00.UWPDesktop_14.0.27810.0_x64__8wekyb3d8bbwe,
                    Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe,
                    Microsoft.DesktopAppInstaller_1.0.32912.0_neutral_split.scale-100_8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
```

**Comment by pibesk** [comment]
I have exactly same issue on Windows 10 v2004.
Did same steps to get winget.

**Comment by theterminator3000** [comment]
I noticed this earlier whilst trying to update App Installer on a device which had only recently upgraded to Windows 10 v2004. Worked around it by installing the msixbundle from [https://github.com/microsoft/winget-cli/releases](https://github.com/microsoft/winget-cli/releases)

**Comment by pibesk** [comment]
> 
> 
> I noticed this earlier whilst trying to update App Installer on a device which had only recently upgraded to Windows 10 v2004. Worked around it by installing the appxbundle from https://github.com/microsoft/winget-cli/releases

This worked for me too.

**Comment by utybo** [comment]
> Wasn't able to see how to do a Feedback Hub with the crash as there's never a prompt or UI to do one associated with the crash information.

You can file a feedback hub thing at any moment by using Windows+F.

**Comment by JohnMcPMS** [comment]
@jfro, @pibesk 
Please do file a Problem through Feedback Hub, using Developer Platform > App deployment if the preview is failing to install.  Note that there is a delay between signing up through the form and being in the flight.  Also, you may need to seek the update in the Store if within the first 24 hours.

**Comment by m-sterspace** [comment]
I have what I think is the same issue on 1909

**Comment by claudiutomescu** [comment]
> > I noticed this earlier whilst trying to update App Installer on a device which had only recently upgraded to Windows 10 v2004. Worked around it by installing the appxbundle from https://github.com/microsoft/winget-cli/releases
> 
> This worked for me too.

Worked for me as well

**Comment by jfro** [comment]
yeah might be just the delay in getting the right version or recent update to App Installer in store fixed it. winget is now recognized.
