### ISSUE TITLE
winget upgrade/list not showing any result

### ISSUE THREAD

**Issue by johntony366** [microsoft/winget-cli#2060]
![image](https://user-images.githubusercontent.com/88877609/161115188-2a1ac2f7-7042-401e-bfe2-79199d1048e2.png)

https://user-images.githubusercontent.com/88877609/161116829-7c93b23f-6557-40ed-bf11-4997da1e08e1.mp4

Fresh install of Windows 11 Pro. As shown in the image, winget list and winget upgrade are not resulting in any output. Every time, the slash icon rotates for around 23 seconds and then nothing happens. I have tried restarting which did not fix my issue. Currently at a loss for what to try next. I did find a similar unresolved issue here: https://www.reddit.com/r/windowsinsiders/comments/sijael/winget_upgradelist_not_showing_any_result/

**Comment by johntony366** [comment]
Logs for winget list command
```
2022-03-31 23:22:03.443 [CORE] WinGet, version [1.2.10271], activity [{9EAC7572-1719-4034-81D6-0DD6EE1F5F93}]
2022-03-31 23:22:03.444 [CORE] OS: Windows.Desktop v10.0.22000.593
2022-03-31 23:22:03.444 [CORE] Command line Args: "C:\Users\John\AppData\Local\Microsoft\WindowsApps\winget.exe" list
2022-03-31 23:22:03.444 [CORE] Package: Microsoft.DesktopAppInstaller v1.17.10271.0
2022-03-31 23:22:03.444 [CORE] IsCOMCall:0; Caller: winget-cli
2022-03-31 23:22:03.450 [CLI ] WinGet invoked with arguments: 'list'
2022-03-31 23:22:03.450 [CLI ] Found subcommand: list
2022-03-31 23:22:03.452 [CLI ] Leaf command to execute: root:list
2022-03-31 23:22:03.452 [CLI ] Executing command: list
2022-03-31 23:22:03.455 [REPO] GetCurrentSourceRefs: Source named 'microsoft.builtin.desktop.frameworks' from origin Default is hidden and is dropped.
2022-03-31 23:22:03.455 [REPO] Default source requested, multiple sources available, adding all to source references.
2022-03-31 23:22:03.455 [REPO] Adding to source references msstore
2022-03-31 23:22:03.455 [REPO] Adding to source references winget
2022-03-31 23:22:03.455 [REPO] Source past auto update time [5 mins]; it has been at least 15 mins
2022-03-31 23:22:03.456 [REPO] Source past auto update time [5 mins]; it has been at least 600 mins

```

**Comment by denelon** [comment]
@johntony366,

Can you try `winget source update --verbose-logs`?
It looks like the cache is stale. I'm wondering if there is a network issue.

**Comment by johntony366** [comment]
Yep, that fixed it. Thanks!

**Comment by ManikandanMani** [comment]
I have same issue, I executed this command `winget source update --verbose-logs` and winget list but it didn't output anything for me.

**Comment by ManikandanMani** [comment]
@denelon, thanks for reaching out, now i executed `winget source update --verbose-logs` and it updated the sources, then executing winget upgrade fixed it.

**Comment by chylex** [comment]
Ran into the same issue, the logs show that at least one of the updates was "Done" but it didn't actually do anything. Before the second updates finished, I realized that Wireguard VPN launched at boot and had an old invalid configuration, so I didn't have access to the internet.

I would expect `winget source update` (especially with `--verbose-logs`) to tell me that it can't connect, instead of silently failing and not updating the local cache.

![obrazek](https://user-images.githubusercontent.com/3685160/171388638-d204a98f-dda2-45bd-93fd-c02f9c9555ea.png)

**Comment by ktrNozomi** [comment]
@brainz80 I use `winget source list` and `winget source remove winget` to remove the stuck source, then everything works... It appears that this cache doesn't exist: https://winget.azureedge.net/cache.

**Comment by hueldoeu** [comment]
> @johntony366,
> 
> Can you try `winget source update --verbose-logs`? It looks like the cache is stale. I'm wondering if there is a network issue.

"winget source update" has helped me but everytime on one damn PC of one of my customers, only god knows why, winget wont "source update" in the beginning when i command "winget upgrade" to see, which program needs to be updated

**Comment by hueldoeu** [comment]
> "winget source update" has helped me but everytime on one damn PC of one of my customers, only god knows why, winget wont "source update" in the beginning when i command "winget upgrade" to see, which program needs to be updated

winget source reset --force help me [winget source reset --force](https://github.com/microsoft/winget-cli/issues/1656#issuecomment-954289074)

**Comment by Shashank5665** [comment]
tried everything above, still not fixed

**Comment by bolandross** [comment]
> tried everything above, still not fixed

Same here, any ideas?

**Comment by hueldoeu** [comment]
> > tried everything above, still not fixed
> 
> Same here, any ideas?

format c:
newly fresh win10/11/12/... install

**Comment by bolandross** [comment]
Unfortunately, I am experiencing this problem on a fresh installed Windows 11 😅

**Comment by ChristopheL77** [comment]
I had the same issue, I update App Installer from the store and it started to work.

![image](https://github.com/microsoft/winget-cli/assets/16576956/d4cabc16-6bcf-4466-ac01-2651f4c59e0e)

**Comment by Aetherinox** [comment]
Yup, this issue is getting rather annoying, brand new fresh install, winget does nothing but spin. And I've done the recommendations above. It just spins until I kill it. System has internet (obviously).

**Comment by ChristopheL77** [comment]
Did you update app installer (get updates then update) in Windows store ?

**Comment by Nick2bad4u** [comment]
Same Issue here now. I tried the source thing and still nothing. Any idea how this was fixed?

**Comment by ChristopheL77** [comment]
> Same Issue here now. I tried the source thing and still nothing. Any idea how this was fixed?

Did you update app installer in Microsoft Store ?

**Comment by Nick2bad4u** [comment]
> > Same Issue here now. I tried the source thing and still nothing. Any idea how this was fixed?
> 
> Did you update app installer in Microsoft Store ?

`Get-AppxPackage -Name 'Microsoft.DesktopAppInstaller' | Reset-AppxPackage`

This fixed it for me.
