### ISSUE TITLE
Source option for list command ignored

### ISSUE THREAD

**Issue by DuNuNuBatman** [microsoft/winget-cli#2064]
### Brief description of your issue

The source option for the winget list command appears to not be working. Here's an example of the packages installed and you can see Ubuntu was installed via winget, but the others in the image weren't.
![image](https://user-images.githubusercontent.com/4228513/161349579-5c0f52c1-7321-4dc9-b1b6-e074009d1281.png)

### Steps to reproduce

run winget list -s|--source winget

### Expected behavior

Get list of packages installed on the system by winget only.

### Actual behavior

Getting all packages installed, but the source column is hidden. As you can see, they match the packages in the description.
![image](https://user-images.githubusercontent.com/4228513/161348996-c5606743-6f2a-4478-ac9f-d2affa68a6c1.png)

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.556
Package: Microsoft.DesktopAppInstaller v1.17.10271.0
```

**Comment by Trenly** [comment]
* Duplicate of #1019
* Related to #1155

**Comment by DuNuNuBatman** [comment]
Yes, this appears to be a duplicate of the attached, thanks.
