### ISSUE TITLE
winget upgrade error

### ISSUE THREAD

**Issue by cjwddtc** [microsoft/winget-cli#2066]
### Brief description of your issue

there were two listary in winget ,the regular one is 5.x,the beta version is 6.x,I want to use regular version，but when I use winget upgrade --all，winget will upgrade to the beta version。

### Steps to reproduce

`winget install Bopsoft.Listary`
`winget upgrade --all`

### Expected behavior

nothing happen

### Actual behavior

winget install the Bopsoft.Listary.Beta

### Environment

```shell
Windows 程序包管理器(预览) v1.3.692-preview
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22000.593
程序包: Microsoft.DesktopAppInstaller v1.18.692.0

日志: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
Seems like the Prod version and Beta version have the same product code, which is causing the issue. The PR linked at [winget-pkgs](/microsoft/winget-pkgs) should resolve this issue
