### ISSUE TITLE
winget executable returns no output & re-install fails

### ISSUE THREAD

**Issue by benfranklin79** [microsoft/winget-cli#2067]
### Brief description of your issue

Winget does not produce any output even after an attempted re-install plus the re-install does not seem to work properly.

### Steps to reproduce

I run `winget` and get no output. Normally when I run it I get the help output. I tried uninstalling winget and then reinstalling but had the same problem. I uninstalled it via `Add or Remove programs` then downloaded the msixbundle via https://github.com/microsoft/winget-cli/releases/tag/v1.2.10271. When I run this it tells me that the `App installer is already installed` but I hit the `reinstall` button anyway and get this:

![image](https://user-images.githubusercontent.com/3197935/161438506-5c3e7f00-8d12-4013-81ab-7e9cdd813a5c.png)

I hit re-install it seems to install quite quickly but I get the same problem with winget, no output and no hint of it being installed by going to add/remove programs.

### Expected behavior

When running `winget` I expect to get the usual help output as an indication that the executable is being run.

### Actual behavior

No output

### Environment

```shell
Winget version: 1.2.10271

Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎20/‎01/‎2022
OS build	19044.1586
Serial number	010121214957
Experience	Windows Feature Experience Pack 120.2212.4170.0
```

**Comment by Trenly** [comment]
Out of curiosity, have you tried `winget.exe` instead of using just `winget` ? 
Is `C:\Users\<YourUsername>\AppData\Local\Microsoft\WindowsApps` in `$env:Path` ?

**Comment by benfranklin79** [comment]
`winget.exe` does the same as `winget`. I did run `$env:Path.Split(";") | Select-String "WindowsApp"` and got the path you mentioned. I even found `winget.exe` in the subfolder `Microsoft.DesktopAppInstaller_8wekyb3d8bbwe` and ran it. Got the same result, no output. At least now I know the executable is there and exists but it's simply doing nothing.

**Comment by jedieaston** [comment]
After you run it, what's the value of $LASTERRORCODE in PowerShell?

**Comment by benfranklin79** [comment]
Hi @jedieaston , thanks for response! I believe it's `$LASTEXITCODE` and that has value `-1978335231`

**Comment by Trenly** [comment]
Just out of curiosity - `Get-AppxPackage | sls 'AppInstaller'` ?

**Comment by benfranklin79** [comment]
I got the following:

```
Get-AppxPackage: The 'Get-AppxPackage' command was found in the module 'Appx', but the module could not be loaded. For more information, run 'Import-Module Appx'
```

I tried running `Import-Module Appx` and got:

```
Import-Module: Operation is not supported on this platform. (0x80131539)
```

**Comment by Trenly** [comment]
> The output I get is:
> 
> ```
> Microsoft.DesktopAppInstaller_1.17.10271.0_x64__8wekyb3d8bbwe
> ```

You could try this in Powershell 5.1
 ```
Remove-AppxPackage 'Microsoft.DesktopAppInstaller_1.17.10271.0_x64__8wekyb3d8bbwe'; $dest = New-TemporaryFile; iwr https://github.com/microsoft/winget-cli/releases/download/v1.2.10271/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile $dest; Add-AppxPackage $dest
```

**Comment by benfranklin79** [comment]
Thanks @Trenly that worked!

**Comment by Trenly** [comment]
> Thanks @Trenly that worked!

Sweet! Not sure why the re-install failed when run manually, but I guess removing the package and then re-installing did the trick
