### ISSUE TITLE
Official Logo for Windows Package Manager 

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-cli#2074]
### Description of the new feature / enhancement

Some developers feature winget on the downloads page of the website so there should be an official logo for Windows Package Manager so that **end-users** can identify winget easily.

For e.g. https://www.masterpackager.com/downloads shows winget as an install option but since there's no logo for winget, the publisher uses logo from https://winstall.app. Hence, users may come to see different logos for winget at different websites, which may result in confusion.

If I find more websites, I will update this comment.

**Comment by denelon** [comment]
https://docs.microsoft.com/windows/dev-environment/
![Logo](https://docs.microsoft.com/nl-nl/windows/images/winget.png)
