### ISSUE TITLE
Winget broken

### ISSUE THREAD

**Issue by hyperio546** [microsoft/winget-cli#2100]
### Brief description of your issue

Winget doesn't work at all

### Steps to reproduce

Install appinstaller and required dependencies
And it won't start

### Expected behavior

Winget to work

### Actual behavior

Winget doesn't work

### Environment

```shell
ResourceUnavailable: Program 'winget.exe' failed to run: An error occurred trying to start process 'C:\Users\themoonmeetsthesun\AppData\Local\Microsoft\WindowsApps\winget.exe' with working directory 'C:\Users\themoonmeetsthesun'. No applicable app licenses found.At line:1 char:1
+ winget
+ ~~~~~~.
```

**Comment by themoonmeetsthesun** [comment]
![image](https://user-images.githubusercontent.com/96462198/163510927-950481fc-8860-4f13-8a8f-363740d9e4ff.png)
Oh and this is broken

**Comment by Masamune3210** [comment]
Issue with your box I'm pretty sure, not winget. Running latest perfectly fine here. Had 11 do that before, something caused all non-system packages to just completely give the ghost, not sure what causes it unfortunately

**Comment by themoonmeetsthesun** [comment]
> Issue with your box I'm pretty sure, not winget. Running latest perfectly fine here. Had 11 do that before, something caused all non-system packages to just completely give the ghost, not sure what causes it unfortunately

Oh 🙁

**Comment by denelon** [comment]
@themoonmeetsthesun,

What operating system version are you using? Is it a stable release or an insider build?

We do include the license file in the GitHub releases, which is what the error appears to be related to, but I'm not sure that would resolve the problem if this is affecting the entire system.

Have you taken a look at our [troubleshooting guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting)?

You could try submitting feedback via [feedback hub](https://aka.ms/winget-feedback) so we can get logs and see if there is anything we can do.

**Comment by themoonmeetsthesun** [comment]
> 

It's difficult to explain
It was originally windows 10 enterprise ltsc 2021
But after activation it became windows 10 iot something

But this is a serious issue. I think I have seen this same issue somewhere else too.

**Comment by ItzLevvie** [comment]
> It was originally windows 10 enterprise ltsc 2021

For Windows SKUs that don't have a built-in Microsoft Store, you can follow the instructions at https://github.com/microsoft/winget-cli/discussions/1956#discussion-3886961.

Also, running WinGet on these SKUs should be considered experimental and unsupported so you may not always get the help you need and sometimes you may need a series of "hacks" to get it up and running.

> But after activation it became windows 10 iot something

You will need to contact your company or organization and check with them if they gave you the wrong key for activation.

**Comment by themoonmeetsthesun** [comment]
> 

First of all its a vm
Second I don't work anywhere
Third it's tiny10 by ntdev who made it
Fourth I use that for experiments because my laptop is shit

**Comment by themoonmeetsthesun** [comment]
Soo I will try that once my main laptop finishes resetting and then I will come back with the results later.

**Comment by themoonmeetsthesun** [comment]
> > 
> 
> First of all its a vm Second I don't work anywhere Third it's tiny10 by ntdev who made it Fourth I use that for experiments because my laptop is shit

Fifth it doesn't make sense for me to use the full windows 10 just for experimenting

**Comment by jedieaston** [comment]
> tiny10 by ntdev 

Tiny10 has limited/no support for AppX packages. You won't be able to use winget, unfortunately (unless you compile it yourself).

**Comment by themoonmeetsthesun** [comment]
> > tiny10 by ntdev 
> 
> Tiny10 has limited/no support for AppX packages. You won't be able to use winget, unfortunately (unless you compile it yourself).

Uhh really? Because I did get it working on another installation of it on another machine.

**Comment by denelon** [comment]
This issue is quite old we're now on WinGet 1.7 and this issue should be resolved.

**Comment by hyperio546** [comment]
> This issue is quite old we're now on WinGet 1.7 and this issue should be resolved.

bro really closed it after 2 years 💀
