### ISSUE TITLE
Cannot build solution in VS 2019.

### ISSUE THREAD

**Issue by vikekh** [microsoft/winget-cli#2102]
### Brief description of your issue

I experience problems building the solution with tag `v1.2.10271`. I get errors like the following:

```
Specified EntryPointExe 'winget.exe' was not found in the project outputs.
```

### Steps to reproduce

1. Install the prerequisites:
   - Windows 10 1809 (17763) or later
   - [Developer Mode enabled](https://docs.microsoft.com/windows/uwp/get-started/enable-your-device-for-development)
   - [Visual Studio 2019](https://visualstudio.microsoft.com/downloads/)
   - The following workloads:
     - .NET Desktop Development
     - Desktop Development with C++
     - Universal Windows Platform Development
   - The following extensions:
      - [Microsoft Visual Studio Installer Projects](https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2017InstallerProjects)
2. Download repository with tag `v1.2.10271`
3. Open Visual Studio 2019 and build the solution

### Expected behavior

Build the application.

### Actual behavior

I get errors:

```
Specified EntryPointExe 'winget.exe' was not found in the project outputs.
```

Is there something that's not listed that I need or do I need to set some option when building?

### Environment

Windows: Windows 10 Pro v19044.1645
Visual Studio: Visual Studio Community 2019 v16.11.12

**Comment by jedieaston** [comment]
What project do you have set as your Startup Project? It should be set to "AppInstallerCLIPackage" for the app to start right:
<img width="574" alt="image" src="https://user-images.githubusercontent.com/21368066/163830656-bc128fe6-602b-4093-addf-07c54eff570f.png">

**Comment by vikekh** [comment]
> What project do you have set as your Startup Project? It should be set to "AppInstallerCLIPackage" for the app to start right: <img alt="image" width="574" src="https://user-images.githubusercontent.com/21368066/163830656-bc128fe6-602b-4093-addf-07c54eff570f.png">

It wasn't that but your screenshot pointed out another thing. I had arch set to "Any CPU", setting it to "x64" I could build. Thanks!
