### ISSUE TITLE
Cant install from MS Store

### ISSUE THREAD

**Issue by mawid6** [microsoft/winget-cli#2122]
### Brief description of your issue

Trying to install from MS Store, does not work.

Workaround: Try to find installer. Does not work. (Installer is also a bit hidden. could maybe update the docs and make it more clear, please?). 
After finding it, however, it cannot update the app. 
So I try to remove it (using standard windows add remove), but it will not let me. I try repair and reset, does not remedy the situation.

Maybe installation is half finished and blocking uninstall/update, perhaps.

### Steps to reproduce

Use a windows pc. 
* Go to store.
* Search for winget.
* The tool is the third entry in the search results, after some games. For whatever reason.
* Click install

![image](https://user-images.githubusercontent.com/77722885/165266714-b63b8236-6e2c-4815-bff9-c2169c343dde.png)

### Expected behavior

* **Expected:** Is installed

### Actual behavior

* Actual: It says "Waiting" forever. 
![image](https://user-images.githubusercontent.com/77722885/165266714-b63b8236-6e2c-4815-bff9-c2169c343dde.png)

### Environment

```shell
Not installed, see?
```

**Comment by denelon** [comment]
The "App Installer" contains the Windows Package Manager in the Microsoft Store. I've included screenshots below. You may also directly install via the [latest release](https://github.com/microsoft/winget-cli/releases/latest) from GitHub.

<img width="904" alt="Screenshot 2022-04-27 083612" src="https://user-images.githubusercontent.com/61799811/165556540-392fec48-5f28-4e6c-ab64-c9dbbf7e52cd.png">

![image](https://user-images.githubusercontent.com/61799811/165556609-a6b06d80-1a72-426f-8293-101e64c8beb2.png)

**Comment by mawid6** [comment]
@denelon: Can you see that you posted the exact same screenshot I posted, but yours is in english?

**Comment by mawid6** [comment]
Hi again, so I tried looking at the store today, and it reports and error and a "Try again" button (note: **_swedish_** in shot below). The button seems to do nothing.
I go to add/remove in windows and the buttons are disabled/greyed out, see shot 2 below.
BR! /marcus
![image](https://user-images.githubusercontent.com/77722885/166213599-24c0f59b-901a-4682-830e-5c21bd690ae5.png)
![image](https://user-images.githubusercontent.com/77722885/166213772-10ed53bd-8c98-4e10-b027-fed36dd17d6c.png)

**Comment by denelon** [comment]
@mawid6 
It looks like other Apps may need updates. Is one of those pending updates the Microsoft Store? I'm not sure what else could be causing this.

Does the App Installer get updated if you download and install from the GitHub releases in this repository?

**Comment by chipbite** [comment]
Thanks @denelon.
I actually forgot to try the manual install before! Sorry. 
That actually worked! (The installer package had some issue with displaying hte name, see shot below). So it is installed now. Lets see how it pans out. 

Thanks alot for your support! 👍 

![image](https://user-images.githubusercontent.com/559199/166422041-270e294c-84fe-4658-9fff-c4e0e256c010.png)

**Comment by mawid6** [comment]
closing. (private-work account confusion here ;-)

**Comment by denelon** [comment]
@mawid6

I'm glad you got it resolved! 

Just as an informational note: The strange display string was a bug in an older version of App Installer. It has been fixed.
