### ISSUE TITLE
Add a way to provide the executables locally instead of downloading them

### ISSUE THREAD

**Issue by signed-log** [microsoft/winget-cli#2127]
### Description of the new feature / enhancement

Some sources, like sourceforge, do automatic mirror redirection. But, sometimes this redirection sends you to a very slow mirror, although a better mirror is available, and due to the non-interactive nature of that process, it is impossible to choose the appropriate mirror

Adding a way to bypass downloads by provding our own executables may help speed some environnements like the example above. It could also where executables are stored in a central location, without having to remake manifests to specify source for every used file. 

### Proposed technical implementation details

Add a `--file` command switch, that would take a Path as a argument, if passed, such switch would : 
- prevent the Download routine from starting
- copy the file to the winget download folder
- check the integrity and continue the install as usual (keeping the security aspect, custom manifests will still be the preferred way to ship custom executables).

**Comment by Trenly** [comment]
I’m not sure I understand the value this feature would provide. If you already have the file downloaded, why not run the executable directly?

**Comment by signed-log** [comment]
You can do that, but having `winget` doing that would mean likely easier bulk install (for non-corporate environnments) and the premade automation scripts can be used, even in slow network conditions because you would have the executable ready

Sure, for MSIs that would likely be a useless feature, but take some `exe`s that are hard to script, that can be really useful

**Comment by Trenly** [comment]
> You can do that, but having `winget` doing that would mean likely easier bulk install (for non-corporate environnments) and the premade automation scripts can be used, even in slow network conditions because you would have the executable ready
> 
> Sure, for MSIs that would likely be a useless feature, but take some `exe`s that are hard to script, that can be really useful

**Comment by Trenly** [comment]
> Sure, for MSIs that would likely be a useless feature, but take some `exe`s that are hard to script, that can be really useful

I’m still not understanding the benefit, since all winget does is run the executables. If they are hard to script normally, I don’t see how putting them through winget would make it any easier

**Comment by signed-log** [comment]
Yeah, you're likely right that it would not serve anything, thanks, closing !

**Comment by justhx0r** [comment]
Since `winget.exe` is `AutoElevate`, allowing the user to install local files `might` not be the best idea though

**Comment by justhx0r** [comment]
But, according to the `documentation`:
```
winget install --manifest \<path>
```
To provide a local `.yaml` file for installation
