### ISSUE TITLE
winget upgrade git - No applicable update found

### ISSUE THREAD

**Issue by blakeduffey** [microsoft/winget-cli#2132]
### Brief description of your issue

i have git 2.35.3 installed.

I see that git 2.36 is available from winget

when I attempt an upgrade, I get an error

winget list git

Name             Id               Version  Available Source
-----------------------------------------------------------
Git              Git.Git          **2.35.3   2.36.0**    winget

### Steps to reproduce

winget upgrade git
No applicable update found.

winget upgrade --id git.git
No applicable update found.

### Expected behavior

it should upgrade the installed version to 2.36

### Actual behavior

error

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1645
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by denelon** [comment]
I'm not sure if it's specific to 2.35.3.

I had 2.35.1.2 installed, so I ran upgrade and it succeeded.

Can you reproduce this and run with "--verbose-logs" and share them?

<img width="577" alt="git" src="https://user-images.githubusercontent.com/61799811/165855021-7a2fcb72-59ed-4b77-ab17-e60e9de321f6.png">

**Comment by blakeduffey** [comment]
Issuing

Winget upgrade git --verbose-logs

Gets me the same result

No applicable update found.

**Comment by bbyk** [comment]
it seems that `--id git.git` limits you to `git.git` and not to the actual id that is `Git.Git`
