### ISSUE TITLE
When I enter the "winget install oh-my-posh" command, there's NO response, it just STUCK LOADING...

### ISSUE THREAD

**Issue by WqxLoveCoding** [microsoft/winget-cli#2133]
### Brief description of your issue

When I enter "winget install oh-my-posh" command to install oh-my-posh, there's NO response, it just STUCK LOADING...Then I try turning off the firewall, it still doesn't work. I also tried "winget search oh-my-posh", also STUCK LOADING...

![image](https://user-images.githubusercontent.com/57825815/165944463-95e35900-b931-4e82-8154-1ca86c988015.png)
![image](https://user-images.githubusercontent.com/57825815/165944972-c0e305b6-2728-44fc-96b2-c9a9edb7a169.png)

### Steps to reproduce

When I enter "winget install oh-my-posh" command to install oh-my-posh, there's NO response, it just STUCK LOADING...Then I try turning off the firewall, it still doesn't work. I also tried "winget search oh-my-posh", also STUCK LOADING...

### Expected behavior

How can I fix it?

### Actual behavior

When I enter "winget install oh-my-posh" command to install oh-my-posh, there's NO response, it just STUCK LOADING...Then I try turning off the firewall, it still doesn't work. I also tried "winget search oh-my-posh", also STUCK LOADING...

### Environment

```shell
Windows 程序包管理器 v1.2.10271
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22000.652
程序包: Microsoft.DesktopAppInstaller v1.17.10271.0

日志: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
Can you provide the log files that are created when you run `winget install oh-my-posh --verbose-logs` ?

**Comment by WqxLoveCoding** [comment]
> ```shell
> DiagOutputDir
> ```

yeah, it shows below
![image](https://user-images.githubusercontent.com/57825815/165948252-e11f9ae9-0e2d-4290-ae93-973f3ee40654.png)

**Comment by WqxLoveCoding** [comment]
@Trenly yeah, it shows below
![image](https://user-images.githubusercontent.com/57825815/165948496-11ef233b-b188-4335-aab3-ff49214aa246.png)

**Comment by WqxLoveCoding** [comment]
> Can you provide the log files that are created when you run `winget install oh-my-posh --verbose-logs` ?

yeah, it shows below
![image](https://user-images.githubusercontent.com/57825815/165951398-abbc3646-2ae2-43ac-84b4-e582b305450f.png)

**Comment by WqxLoveCoding** [comment]
Or should I use the latest version of winget? I didn't download or update any version of winget cause Windows 11 has a built-in version

**Comment by denelon** [comment]
@WqxLoveCoding

It appears you have the latest stable release.

You could try to change the network downloader [settings](https://docs.microsoft.com/windows/package-manager/winget/settings#downloader) to use "wininet" instead of "do". In some cases, we've seen this help.

**Comment by WqxLoveCoding** [comment]
OK, fine, I can finally install it, maybe due to my network error yesterday, thank'u all.
