### ISSUE TITLE
Winget on powershell opens a "open with" window

### ISSUE THREAD

**Issue by Nirgranth** [microsoft/winget-cli#2147]
### Brief description of your issue

run winget on powershell on upgrading to win 11

### Steps to reproduce

![image](https://user-images.githubusercontent.com/48947296/167500982-f45dd112-2292-48f2-9f44-9a6c45535cf0.png)

### Expected behavior

run winget

### Actual behavior

opens a "open with" window

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.652
Package: Microsoft.DesktopAppInstaller v1.17.10271.0
```

**Comment by Nirgranth** [comment]
![image](https://user-images.githubusercontent.com/48947296/167501338-3bf9d52e-01b1-4cf2-a86a-85268ac65aae.png)

**Comment by denelon** [comment]
If you can reproduce this, would you be willing to file a Feedback Hub issue?

https://aka.ms/winget-feedback

That would allow us to get the logs to see if we can determine what is happening. It is strange that the `winget --info` command is giving the right results, but `winget` isn't showing the "help" output. What do you get if you run `winget -?`

**Comment by Nirgranth** [comment]
no its just on powershell, the cmd works fine, its not the command
![image](https://user-images.githubusercontent.com/48947296/167754152-adec290b-a9cf-4369-bdc5-f3558ca9aed4.png)
![image](https://user-images.githubusercontent.com/48947296/167754182-5690547d-3091-4684-96ad-c71bd4af53ed.png)

**Comment by SteveL-MSFT** [comment]
@nirgranth, can you try with https://github.com/PowerShell/PowerShell/releases/tag/v7.1.5 (specifically version 7.1.5) to see if this still repros?  This will help to potentially identify the issue.

**Comment by Nirgranth** [comment]
![image](https://user-images.githubusercontent.com/48947296/168170416-8214f8ea-d052-42bf-aa05-c79c20f876cb.png)

**Comment by SteveL-MSFT** [comment]
@nirganth, thanks.  At least that confirms it's something else eliminating a potential code path I thought might be related.

**Comment by daxian-dbw** [comment]
I cannot reproduce this on my Win11 machine, but my machine was not upgraded from Win10, but pre-installed with Win 11 -- not sure if that plays a part here.

![Animation](https://user-images.githubusercontent.com/127450/168188797-f548b09e-edfd-4131-a1b5-29a890fb137d.gif)

```
PS:27> winget --info
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.613
Package: Microsoft.DesktopAppInstaller v1.17.10271.0
```

**Comment by Nirgranth** [comment]
maybe i can send my windows image?
i have tried image cleanup doesnt seem to help

**Comment by Nirgranth** [comment]
one more odd thing i tried to "remove" powershell it dint work
![image](https://user-images.githubusercontent.com/48947296/168201868-5032d281-903f-42cb-8995-eb972d135f72.png)

**Comment by winhelponline** [comment]
> no its just on powershell, the cmd works fine, its not the command ![image](https://user-images.githubusercontent.com/48947296/167754152-adec290b-a9cf-4369-bdc5-f3558ca9aed4.png) ![image](https://user-images.githubusercontent.com/48947296/167754182-5690547d-3091-4684-96ad-c71bd4af53ed.png)

What happens when you select Notepad from the list and click OK?

Also, running a Process Monitor trace should narrow down the issue.

**Comment by Nirgranth** [comment]
> What happens when you select Notepad from the list and click OK?
![image](https://user-images.githubusercontent.com/48947296/168405327-6ebceae7-6891-4ccb-bfff-76e2ad76c058.png)


> Also, running a Process Monitor trace should help narrow down the issue.
[Logfile.CSV](https://github.com/microsoft/winget-cli/files/8691923/Logfile.CSV)
[Logfile.zip](https://github.com/microsoft/winget-cli/files/8691924/Logfile.zip)

**Comment by winhelponline** [comment]
It appears from the log that there is an extensionless file named "C:\Windows\System32\winget". Simple rename that file and be prepared to be amazed.

**Comment by winhelponline** [comment]
> > What happens when you select Notepad from the list and click OK?
> > ![image](https://user-images.githubusercontent.com/48947296/168405327-6ebceae7-6891-4ccb-bfff-76e2ad76c058.png)
> 
> > Also, running a Process Monitor trace should help narrow down the issue.
> > [Logfile.CSV](https://github.com/microsoft/winget-cli/files/8691923/Logfile.CSV)
> > [Logfile.zip](https://github.com/microsoft/winget-cli/files/8691924/Logfile.zip)

It appears from the log that there is an extensionless file named "C:\Windows\System32\winget". Simple rename that file and be prepared to be amazed.

**Comment by Nirgranth** [comment]
> > > What happens when you select Notepad from the list and click OK?
> > > ![image](https://user-images.githubusercontent.com/48947296/168405327-6ebceae7-6891-4ccb-bfff-76e2ad76c058.png)
> > 
> > 
> > > Also, running a Process Monitor trace should help narrow down the issue.
> > > [Logfile.CSV](https://github.com/microsoft/winget-cli/files/8691923/Logfile.CSV)
> > > [Logfile.zip](https://github.com/microsoft/winget-cli/files/8691924/Logfile.zip)
> 
> It appears from the log that there is an extensionless file named "C:\Windows\System32\winget". Simple rename that file and be prepared to be amazed.

yes but its 0kb
[winget.zip](https://github.com/microsoft/winget-cli/files/8692158/winget.zip)

**Comment by winhelponline** [comment]
> > It appears from the log that there is an extensionless file named "C:\Windows\System32\winget". Simple rename that file and be prepared to be amazed.
> 
> yes but its 0kb [winget.zip](https://github.com/microsoft/winget-cli/files/8692158/winget.zip)

Ok. I guess that file can be deleted.

**Comment by Nirgranth** [comment]
> It appears from the log that there is an extensionless file named "C:\Windows\System32\winget". Simple rename that file and be prepared to be amazed.
 
renaming to winget.exe

![image](https://user-images.githubusercontent.com/48947296/168410277-490d8085-3114-4353-982b-c251382c2e89.png)

breaks in cmd to i have to keep in extensionless

**Comment by Nirgranth** [comment]
> Ok. I guess that file can be deleted.

Deleting worked but is it okay?

**Comment by winhelponline** [comment]
> > Ok. I guess that file can be deleted.
> 
> Deleting worked but is it okay?

Yes. This file is not needed.
