### ISSUE TITLE
Develop Intune integration

### ISSUE THREAD

**Issue by chritea** [microsoft/winget-cli#215]
# Description of the new feature/enhancement

As an Enterprise Administrator I want to be able to select and deploy WinGet packages directly from Intune like I can with the Microsoft Store for Business. An auto update mechanism exists which helps me to stay current with 3rd party software on my devices.

**Comment by JoshPhillips59** [comment]
Seconded

**Comment by pl4nty** [comment]
Related to #151, Intune integration would need DO support (and Microsoft Connected Cache too?)

**Comment by denelon** [comment]
This looks like it might be similar to #118 and #213. I'm fine keeping this open to look at specific needs for Intune.

**Comment by sjansen1** [comment]
Please implement this, packaging is such a time consuming task with all the different types of installers, having access to winget would be a big plus.

**Comment by denelon** [comment]
https://techcommunity.microsoft.com/t5/windows-it-pro-blog/evolving-the-microsoft-store-for-business-and-education/ba-p/2569423

**Comment by Simpuhl** [comment]
2022, any updates on this ?

**Comment by denelon** [comment]
According to the blog post, first half of 2022. It's likely to be closer to the middle of the year.

**Comment by roconnor04** [comment]
Really hope this comes sooner rather than later.

**Comment by denelon** [comment]
Work is in progress.

Related to:

* #1909
* #1853 
* microsoft/winget-cli-restsource/issues/101
* microsoft/winget-cli-restsource/issues/100

**Comment by Romanitho** [comment]
To wait for official support, we have this  
https://github.com/Romanitho/Winget-Install

**Comment by larsuhartmann** [comment]
Really hoping on this - are there any updates regarding the timeframe we can expect it?

**Comment by janne-tech** [comment]
is there any update intune preview H1 ?

**Comment by denelon** [comment]
We are actively working on the Intune integration via Windows Package Manager. The Intune team will determine when they are going to have a preview. I'll see if anything has been published. If you are interested, send me an e-mail and I will forward the request to the Intune team.

**Comment by janne-tech** [comment]
Im very intrested

**Comment by Romanitho** [comment]
Let's support PowerShell first, no ? 😋  
Then, it will be naively supported 😅

**Comment by denelon** [comment]
https://techcommunity.microsoft.com/t5/windows-it-pro-blog/update-to-endpoint-manager-integration-with-the-microsoft-store/ba-p/3585077

**Comment by denelon** [comment]
Latest update: https://www.youtube.com/watch?v=11ezQMwnR_4

**Comment by jacraff** [comment]
Is there any information as to when WinGet/Intune Integration will be in Preview and whether Windows 10 will be supported?

**Comment by kornflex** [comment]
> To wait for official support, we have this https://github.com/Romanitho/Winget-Install

I tried :
winget installed as local system , winget.exe is in the directory.
When I try to install "kiosk browser" : nothing.  check.ps1 return an error in intune reporting.

When I try by myself to install package as local system, winget do nothing : no error, command is launch and I get C: prompt

I try on windows 20h2

**Comment by denelon** [comment]
Updates to Windows App Management in Intune with Winget

https://www.youtube.com/watch?v=QtftJQn9WYQ

**Comment by denelon** [comment]
We've published a NuGet package with "in process" access to talk to the WinGet COM APIs. We're still working on documentation to help explain how the Integration with Intune works so others can also leverage the same mechanism for MDM integration.

As WinGet is delivered via MSIX, the system level access requires additional effort to enable.

**Comment by byjrack** [comment]
Looking forward to having a more first party experience for adding winget entries to the Company Portal similar to the MSStore integration added.

Also would like to see Intune expose a winget REST source that mirrored Company Portal so users can use the cli to pull in things they want.  May have some limits based on scoping etc, but have them work better together with fewer registries.

**Comment by denelon** [comment]
We've provided the full capabilities for Intune to leverage WinGet. We will continue adding new capabilities via the COM APIs as we develop new functionality in Windows Package Manager.

**Comment by denelon** [comment]
@byjrack, I'm not aware of a public issue tracker for them. I'll forward your request and see what we can do here.

**Comment by SorenLundt** [comment]
Would this allow us to install any WIn32App from winget-pkgs repo ?

So far I have been using this to integratie with InTune:
https://github.com/SorenLundt/WinGet-Wrapper

**Comment by byjrack** [comment]
Yup I think we all use some sort of variant of that today, but it's definitely not a first party option.

Expectation is that it acts more like the experience with Store apps.

I am [also trying to figure out](https://github.com/microsoft/winget-cli/discussions/3766) if there is a method to use it via the existing COM interface implementation as well.  Will still need some scripting, but maybe simplify some of the integration in scripts.

**Comment by b00walk** [comment]
As we migrate more and more customers across to intune from SCCM the need for an easier way to keep applications up to date is getting bigger by the day. Winget is such a great utility for individuals, if it was extended to enterprise administrators it would be a game changer.

**Comment by webstean** [comment]
Really long overdue - winget has no future until it is enterprise enabled.

**Comment by byjrack** [comment]
The funny thing is that the Intune Store integration is done by winget so all the bones are there.  What is missing is the ability to input a custom source and ID in Intune then have AgentExecutor do all the rest.  There are definitely some other sharp edges like managing updates over time that might need something similar to what Store does, but the basics are all there.  

I have had some success with making a factory pattern with posh, but it's much higher cost than it should be.  individual intunewin files since there isn't metadata available at ex time, custom update notifications, etc.
