### ISSUE TITLE
Update doesn't work for Visual Studio 2022

### ISSUE THREAD

**Issue by NN---** [microsoft/winget-cli#2165]
### Brief description of your issue

WinGet fails upgrading Visual Studio and then cannot continue with upgrades.

### Steps to reproduce

Install Visual Studio 2022 17.2.0

```>winget upgrade --all
Found Visual Studio Enterprise 2022 [Microsoft.VisualStudio.2022.Enterprise] Version 17.2.1
(1/1) Found Visual Studio Enterprise 2022 [Microsoft.VisualStudio.2022.Enterprise] Version 17.2.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/05734053-383e-4b1a-9950-c7db8a55750d/98dcfd76797e262c8c40b100ce3de93a65c2dd9e0ba6cba2e2a1c928a8658eef/vs_Enterprise.exe
  ██████████████████████████████  1.60 MB / 1.60 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1
```

### Expected behavior

Upgrade works

### Actual behavior

Upgrade fails

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.675
Package: Microsoft.DesktopAppInstaller v1.17.10271.0
```

**Comment by denelon** [comment]
Can you run the command with "--verbose-logs" and share the output?

**Comment by NN---** [comment]
I have already updated manually.
Probably will happen during the next update.

**Comment by jedieaston** [comment]
This happens if you don't run winget with admin, the Visual Studio installer won't elevate for an upgrade by itself. 

We may need a `upgradeElevationRequirement` (if there's other apps that do this besides VS, otherwise they should make it try to elevate on upgrade).

**Comment by Trenly** [comment]
> This happens if you don't run winget with admin, the Visual Studio installer won't elevate for an upgrade by itself.
> 
> We may need a `upgradeElevationRequirement` (if there's other apps that do this besides VS, otherwise they should make it try to elevate on upgrade).

Or perhaps #2062

**Comment by jedieaston** [comment]
I like the solution you proposed! Since upgrade is a different mode for switches it makes sense to have a different ElevationRequirement for it.

**Comment by sba923** [comment]
Same issue here. Seems to have started with VS2022 v17.2.

![image](https://user-images.githubusercontent.com/12860484/169779027-15677815-1db6-4841-b4a9-84bc19e2cf5d.png)

[winget fails to upgrade VS2022 - 202205231038.zip](https://github.com/microsoft/winget-cli/files/8752886/winget.fails.to.upgrade.VS2022.-.202205231038.zip)

**Comment by jedieaston** [comment]
Was VS running when you tried to upgrade?

**Comment by sba923** [comment]
> Was VS running when you tried to upgrade? Long shot, but I've seen it error out for that too. 

No, VS wasn't running.

**Comment by jedieaston** [comment]
Related: https://github.com/microsoft/winget-pkgs/issues/32921

**Comment by GNQG** [comment]
I encountered almost same problem on Microsoft.VisualStudio.2022.BuildTools.
I found manifests for version >= 17.2.0 aims to installers for LTSC 17.2 Channel, not Current Channel (See [this](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs-servicing#long-term-servicing-channel-ltsc-support).)
I guess upgrading from Current Channel to LTSC Channel causes some problems.

**Comment by jedieaston** [comment]
That's my fault, I have a script that updates Visual Studio but it wasn't grabbing the right links for Enterprise/Build Tools/Professional. Let me fix it...

**Comment by denelon** [comment]
Is this resolved?

**Comment by denelon** [comment]
@sba923 I didn't see an entry for Visual Studio Build Tools 2017. It's possible they just haven't been submitted yet. You may [request them](https://github.com/microsoft/winget-pkgs/issues/new/choose).
