### ISSUE TITLE
The docs website does not have a table of content

### ISSUE THREAD

**Issue by utybo** [microsoft/winget-cli#217]
https://docs.microsoft.com/windows/package-manager

Most docs on the docs.microsoft.com website seem to have a table of content on the left panel, but winget's left panel is empty, making it quite annoying to navigate through the docs.

**Comment by denelon** [comment]
Are you seeing something different @utybo ?

![image](https://user-images.githubusercontent.com/61799811/82722269-ef6b8b80-9c79-11ea-9bd2-78114bdd753f.png)

**Comment by utybo** [comment]
Yup, I can see it now. Thanks!
