### ISSUE TITLE
Option to exclude specific ID from upgrade --all

### ISSUE THREAD

**Issue by Akitarmo** [microsoft/winget-cli#2177]
### Description of the new feature / enhancement

I'd like to propose an additional option for "upgrade --all" that would allow to exclude specified programs (most likly via ID) from upgrading, even if a upgrade would be able. 

To be clear, I'm speaking of multiple ID capability, not only one:)

The Usecase that prompts me to post this is to exclude programs that are known to have issues.
For Example, Applications like Teams, GOG Galaxy or Discord get detected every time but only throw errors and I'd like to just exlude them from beeing upgraded some times to avoid these Errors.

But it could also be usefull if one's not using a default installation of a Program and needs to follow a specific upgrade way, therefore can't have it beeing upgraded by winget.

**Comment by Akitarmo** [comment]
I'm aware of #476 , My proposal would be to have a more temporary solution than pinning a package too.

Maybe I want a package ignored in my weekly running automated upgrade script, but only there. 
So other than pinning a package where you would need to store the pinned ID somewhere, this would be more of a search filter for the current running command only.

To be clear, I would love to see both theese Options to be implemented simultaneously because they serve different use cases.

**Comment by Trenly** [comment]
Seems like #2014 would accomplish the same thing

**Comment by Akitarmo** [comment]
Ah, yes, didn't see that sorry.

Would - - nomatch be able to handle multiple Patterns?

**Comment by Trenly** [comment]
> Ah, yes, didn't see that sorry.
> 
> Would - - nomatch be able to handle multiple Patterns?

Regex can match multiple using the or operator, yes

**Comment by Akitarmo** [comment]
Then I'm closing my Issue as a Duplicate if #2014
