### ISSUE TITLE
Can not find winget after installation in Window 10.

### ISSUE THREAD

**Issue by zydjohnHotmail** [microsoft/winget-cli#2180]
### Brief description of your issue

Can not find winget after installation in Window 10.

### Steps to reproduce

Download installer from:
https://github.com/microsoft/winget-cli/releases/download/v1.2.10271/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
Install it by right click and choose install, wait until the installation finishes, and try to run it, but failed.

### Expected behavior

I should be able to locate where winget command is, but not.

### Actual behavior

Where command didn't report the location of winget.

I have downloaded and installed winget from this URL:
https://github.com/microsoft/winget-cli/releases/download/v1.2.10271/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle

It looks OK when I installed it, actually, it is already installed as I can see from the installation screen.
However, I can’t find where is the winget command.
See the following output:
C:\>where python
C:\Program Files\Python39\python.exe
C:\ProgramData\Anaconda3\python.exe
C:\Program Files\Inkscape\bin\python.exe

C:\>where winget
INFO: Could not find files for the given pattern(s).

[C:\](https://github.com/)>
I am using Windows 10 (Version 21H2: OS Build 19044.1706).

### Environment

```shell
Winget version: 1.17.10271.0

I want to install streamlink via winget, but I can't find where winget is located.
```

**Comment by denelon** [comment]
Have you taken a look at the [troubleshooting](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting) guide?

**Comment by denelon** [comment]
@zydjohnHotmail We've had several releases since this issue was reported. Is this still happening?
