### ISSUE TITLE
winget upgrade: specific list of apps

### ISSUE THREAD

**Issue by pavangayakwad** [microsoft/winget-cli#2182]
### Description of the new feature / enhancement

Anyone coming from linux background and using winget will easily expect following command to simply upgrade the cherry-picked apps.

`winget upgrade Git.Git Notepad++.Notepad++ Microsoft.Teams qBittorrent.qBittorrent`

It seems there is no such functionality in winget yet.

**Comment by denelon** [comment]
Duplicate of #1855
