### ISSUE TITLE
Windows Package Manager 1.5 manifest schema

### ISSUE THREAD

**Issue by ryfu-msft** [microsoft/winget-cli#2187]
### Description of the new feature / enhancement

This is a parent issue to track outstanding schema requests for the 1.4 schema. Inclusion in this list is **not a commitment**. Other schema items may be added or removed.

>Note: We will be targeting the 1.5 schema with the 1.5 client.

Edited: The remaining open items were moved to:
* https://github.com/microsoft/winget-cli/issues/2446

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/2446
