### ISSUE TITLE
Allow multiple apps to be installed using a single command

### ISSUE THREAD

**Issue by brunovieira97** [microsoft/winget-cli#219]
# Description of the new feature/enhancement

Let us call `winget install` with a list of apps, so it'll install them at the same time OR in sequence.

Proposal for command: `winget install app-1 app-2 app-3`

**Comment by shawnwildermuth** [comment]
Or via config file like Chocolatey (e.g. packages.config)

**Comment by masx200** [comment]
I support it!

**Comment by denelon** [comment]
This is not the same thing as #156

**Comment by actuallysayan** [comment]
I support this!

**Comment by ecovio1** [comment]
@denelon  @brunovieira97 

managing multiple apps in a single command should be supported for all commands ,    not `install `only but for `list / upgrade / uninstall` too.

**Comment by brunovieira97** [comment]
> @denelon @brunovieira97
> 
> managing multiple apps in a single command should be supported for all commands , not `install `only but for `list / upgrade / uninstall` too.

I definitely agree with you! At least `uninstall` should be covered as well for feature parity between installation and removal process of an app. But implementing this for `upgrade` too would be very much welcome!

**Comment by sanamhub** [comment]
I upvote (support) for this issue!

This is extremely needed thing 🚀

**Comment by danstis** [comment]
To work around this limitation, I added the following PowerShell function to my profile (`notepad $profile`):
```powershell
# Function to process multiple WinGet Upgrades
function Winget-Upgrade {
	Param(
		# List of packages to upgrade
		[Parameter(Position = 0, Mandatory = $true)]
		[string[]] $Packages
	)
	foreach ($Package in $Packages) {
		$Package = $Package.Trim()
		Write-Host ('Upgrading {0}...' -f $Package) -ForegroundColor Green
		WinGet Upgrade $Package
	}
}
```

With this in place you can upgrade multiple packages like this: 
`Winget-Upgrade Package1.Package1,Package2.Package1`

**Comment by alie2n** [comment]
I also think that this should be supported. It would make usage a lot easier.
I know that you can script it or generate a json file for future use. But it is not nearly as easy as apt-get, chcolatey, yum, etc.

**Comment by asifm** [comment]
> With this in place you can upgrade multiple packages like this: `Winget-Upgrade Package1.Package1,Package2.Package2`

Excellent. 

For others: After adding this to your profile, don’t forget to reload the profile by doing `. $profile`

**Comment by tnixeu** [comment]
This was the first thing I wanted to do, when I just used it for the first time.

@danstis thx for the script.

I have not used power shell scripts util now, so I had to change the execution policy in order to conveniently use winget.

**Comment by emoxam** [comment]
> > With this in place you can upgrade multiple packages like this: `Winget-Upgrade Package1.Package1,Package2.Package2`
> 
> Excellent.
> 
> For others: After adding this to your profile, don’t forget to reload the profile by doing `. $profile`

There is no such commnd as ". $profile" not at cmd nor at PS. What did you mean ?

**Comment by emoxam** [comment]
> Winget-Upgrade

There is not such app as Winget-Upgrade. If you mean Winget Upgrade - than it's still doesn't work.

**Comment by emoxam** [comment]
That should be available without any PS movement!

**Comment by emoxam** [comment]
When and how ill we get the new release ?

**Comment by sanamhub** [comment]
> When and how ill we get the new release ?

This feature will land in `v1.5` which is `Due by April 30, 2023`
For more: https://github.com/microsoft/winget-cli/milestone/39

**Comment by emoxam** [comment]
> This feature will land in `v1.5` which is `Due by April 30, 2023`
> For more: https://github.com/microsoft/winget-cli/milestone/39

And if i joined the Windows Package Manager Insider program?

**Comment by sanamhub** [comment]
> And if I joined the Windows Package Manager Insider program?

I think this is it: https://devblogs.microsoft.com/commandline/windows-package-manager-preview/

**Comment by emoxam** [comment]
> I think this is it: https://devblogs.microsoft.com/commandline/windows-package-manager-preview/

Will it appears here ? https://github.com/microsoft/winget-cli/tags
How fast ?

**Comment by denelon** [comment]
We're looking to cut another preview in the next week or two. It will show up in the releases as a "preview" and it will be published to Windows Insider Dev.

**Comment by jo-chemla** [comment]
The below winget command do work for `winget install`-ing multiple packages at once via their ids.
As pointed above by @denelon @brunovieira97 and others, it would also be great to support multiple package ids for `uninstall` and maybe `upgrade` commands, for feature parity.

```
winget install package-id-1 package-id-2 --accept-package-agreements --accept-source-agreements
```

**Comment by jo-chemla** [comment]
Indeed, I was using the same arguments for install and uninstall `--disable-interactivity --accept-package-agreements --accept-source-agreements` although uninstall does not support `--accept-package-agreements` (which makes sense). Great to hear!

**Comment by JasonCraneAdkins** [comment]
And how does this work with the integrated Powershell module

Example:
install-wingetpackage JiriPolasek.ColorsforCommandPalette JiriPolasek.DevNumbersforCommandPalette   
Error Message:
Install-WinGetPackage: No packages matched the given input criteria.

**Comment by beedell-roke** [comment]
> https://github.com/microsoft/winget-cli/issues/219#issuecomment-2999678723

@JasonCraneAdkins, have you tried passing an array to `-ID`, like `-ID @('JiriPolasek.ColorsforCommandPalette', 'JiriPolasek.DevNumbersforCommandPalette')`? If not, I'd say post `Get-Error`'s CLIXML to a new Q&A discussion.

**Comment by JasonCraneAdkins** [comment]
Now i Did.

Here is the output

`
#> install-wingetpackage -id @('JiriPolasek.MediaControlsforCommandPalet','JiriPolasek.RecentFilesforCommandPalette')                                                                                                                                                                                                     

Install-WinGetPackage: Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Id'. Specified method is not supported.
 
#> get-error                                                                                                                                                                                                                                                                                                              

Exception             :
    Type              : System.Management.Automation.ParameterBindingException
    Message           : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Id'. Specified method is not supported.
    ParameterName     : Id
    ParameterType     : [System.String]
    TypeSpecified     : [System.Object[]]
    ErrorId           : CannotConvertArgument
    Line              : 1
    Offset            : 27
    CommandInvocation :
        MyCommand        : Install-WinGetPackage
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : 35
        Line             : install-wingetpackage -id @('JiriPolasek.MediaControlsforCommandPalet','JiriPolasek.RecentFilesforCommandPalette')
        Statement        : install-wingetpackage -id @('JiriPolasek.MediaControlsforCommandPalet','JiriPolasek.RecentFilesforCommandPalette')
        PositionMessage  : At line:1 char:1
                           + install-wingetpackage -id @('JiriPolasek.MediaControlsforCommandPalet …
                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        InvocationName   : install-wingetpackage
        PipelineLength   : 1
        PipelinePosition : 1
    ErrorRecord       :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Id'. Specified method is not supported.
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [Install-WinGetPackage], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CannotConvertArgument,Microsoft.WinGet.Client.Commands.InstallPackageCmdlet
        InvocationInfo        :
            MyCommand        : Install-WinGetPackage
            ScriptLineNumber : 1
            OffsetInLine     : 27
            HistoryId        : 35
            Line             : install-wingetpackage -id @('JiriPolasek.MediaControlsforCommandPalet','JiriPolasek.RecentFilesforCommandPalette')
            Statement        : @('JiriPolasek.MediaControlsforCommandPalet','JiriPolasek.RecentFilesforCommandPalette')
            PositionMessage  : At line:1 char:27
                               + … package -id @('JiriPolasek.MediaControlsforCommandPalet','JiriPolasek …
                               +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite        :
        Name          : CoerceTypeAsNeeded
        DeclaringType : [System.Management.Automation.ParameterBinderBase]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data              : System.Collections.ListDictionaryInternal
    InnerException    :
        Type       : System.NotSupportedException
        TargetSite :
            Name          : CoerceTypeAsNeeded
            DeclaringType : [System.Management.Automation.ParameterBinderBase]
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Message    : Specified method is not supported.
        Source     : System.Management.Automation
        HResult    : -2146233067
        StackTrace :
   at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String parameterName, Type toType, ParameterCollectionTypeInformation collectionTypeInfo, Object currentValue)
    Source            : System.Management.Automation
    HResult           : -2146233087
    StackTrace        :
   at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String parameterName, Type toType, ParameterCollectionTypeInformation collectionTypeInfo, Object currentValue)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindNamedParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter)
   at System.Management.Automation.ParameterBinderController.BindNamedParameters(UInt32 parameterSets, Collection`1 arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidArgument: (:) [Install-WinGetPackage], ParameterBindingException
FullyQualifiedErrorId : CannotConvertArgument,Microsoft.WinGet.Client.Commands.InstallPackageCmdlet
InvocationInfo        :
    MyCommand        : Install-WinGetPackage
    ScriptLineNumber : 1
    OffsetInLine     : 27
    HistoryId        : 35
    Line             : install-wingetpackage -id @('JiriPolasek.MediaControlsforCommandPalet','JiriPolasek.RecentFilesforCommandPalette')
    Statement        : @('JiriPolasek.MediaControlsforCommandPalet','JiriPolasek.RecentFilesforCommandPalette')
    PositionMessage  : At line:1 char:27
                       + … package -id @('JiriPolasek.MediaControlsforCommandPalet','JiriPolasek …
                       +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1`

**Comment by beedell-roke** [comment]
> https://github.com/microsoft/winget-cli/issues/219#issuecomment-2999710471

@JasonCraneAdkins, I explicitly suggested that you discuss this in a new Q&A for a reason – until you've confirmed that you've located a bug, it's not worth filing an issue for, and even if you knew it was, it would be a separate issue to this, since the scope is the PowerShell module's translation later.

I still suggest that you re-file this there, asking whether this is possible, and if so, how. When you do, please link it here, and I'll try to assist.

Though, I can't easily assist you, because that log is unreadable: you need to render it with semantic markup. I suggest that you read the Markdown basics on fenced code blocks.
