### ISSUE TITLE
Skip some app that don't want to be upgraded

### ISSUE THREAD

**Issue by gavinn212** [microsoft/winget-cli#2196]
### Description of the new feature / enhancement

Hi, the idea is simple, some cracked software (not proud of that, but they're expensive) won't work once it's upgraded. Or some work requires a specific version of the software. It would be nice to allow users to choose some app that won't check the available upgrade

**Comment by Masamune3210** [comment]
App Pinning is what you are looking for and it already has a issue tracking it

**Comment by jedieaston** [comment]
Duplicate of https://github.com/microsoft/winget-cli/issues/476

**Comment by jedieaston** [comment]
Duplicate of #476
