### ISSUE TITLE
Winget failed to run:

### ISSUE THREAD

**Issue by windosws** [microsoft/winget-cli#2205]
### Brief description of your issue

In my powershell terminal i tried to do a command with winget but its not working at all.

### Steps to reproduce

Using the terminal and process everything you want with winget.

### Expected behavior

Install git with winget

### Actual behavior

The program winget.exe failed to run when i try to use winget in powershell  to install Git or other.

By the way its saying in french "The specified path was not found" for " Le chemin d’accès spécifié est introuvable"

![image](https://user-images.githubusercontent.com/101200483/171285513-9c764169-98e7-4c10-b761-d432e08e0e42.png)

### Environment

```shell
Windows Package Manager 1.2.10271
Also Windows 11
```

**Comment by Trenly** [comment]
@windosws - Are you still experiencing this issue?
