### ISSUE TITLE
Searching fot dotnet package

### ISSUE THREAD

**Issue by havit1** [microsoft/winget-cli#2218]
### Brief description of your issue

winget show command returns not user friendly error

### Steps to reproduce

winget show dotnet

### Expected behavior

Readable message if error occured

### Actual behavior

An unexpected error occurred while executing the command:
0x8a150039 : Invalid data returned by rest source

### Environment

```shell
Windows Package Manager v1.2.10941
Windows: Windows.Desktop v10.0.22000.708
Package: Microsoft.DesktopAppInstaller v1.17.10941.0
```

**Comment by denelon** [comment]
<img width="867" alt="2218" src="https://user-images.githubusercontent.com/61799811/172180839-1c030147-9271-4c16-961b-e9a7bfd0a532.png">

**Comment by denelon** [comment]
<img width="577" alt="winget show dotnet" src="https://user-images.githubusercontent.com/61799811/173168929-2a967f2b-e766-4af9-b6cd-d0453aeb810d.png">
