### ISSUE TITLE
Upgrade command to ignore software that has no version

### ISSUE THREAD

**Issue by tomgron** [microsoft/winget-cli#2223]
### Description of the new feature / enhancement

As I use winget upgrade --all extensively (almost every day), I end up "upgrading" software that might not even need upgrading. This is due to the fact that some of the software apparently doesn't expose their version info correctly (as shown in picture below).

Thus, I suggest an extra option that could skip the software that has no version to compare to - and then I could skip them if needed to - most of the time ending up to download lots of bytes for no reason.

![image](https://user-images.githubusercontent.com/1743381/172258514-edac2078-e0cd-45f6-bfdf-fddf4502fb8d.png)

### Proposed technical implementation details

If (version == "Unknown" && options.Contains('skipUnknownVersions')) { skipToNext() }? Something like this?

**Comment by Masamune3210** [comment]
Your version of Winget must be out of date, ignoring unknown versions is already a thing

**Comment by denelon** [comment]
This has been resolved in the current release.
