### ISSUE TITLE
[zh-tw][translate] "Package" should be translated into "(程式)包".

### ISSUE THREAD

**Issue by dominoFire** [microsoft/winget-cli#2226]
### Brief description of your issue

Copied winget part from customer report: https://developercommunity.visualstudio.com/t/zh-twtranslate-Package-should-be-t/10058803

-----

Suggestions

English String: Package

Current Translation: 套件/封裝

Suggested Translation: 程式包

Reasons and Details

I think it is NOT proper to translate “Package” into “套件”. It will confuse users with concepts of “Package” and “Kit” because “Kit” is also translated into “套件”. However, these two things are different. Therefore, I suggest that “Package” be translated into “包” int zh-TW locale, just like “zh-CN”.

There is a [Chinese article](https://breezymove.blogspot.com/2013/04/package.html) talking about the translation of “Package”, which I fully identify it.

In Chinese, there is a concept called “affix (詞綴)”. For example, “Tiger” is translated into “虎”. However, we usually speak “老虎”, where “老” is the affix, when we don’t mean to specify which type of tiger it is. It is because we seldom speak “one word” in Chinese.

The reason why I choose “程式” as affix is because both “Code” and “Library” choose “程式” as affix as well.

Code: 程式碼

Library: 程式庫

Package: 程式包

Screenshots

![image](https://user-images.githubusercontent.com/1192347/172497148-497de328-d165-473f-992d-86baa995c180.png)

### Steps to reproduce

winget --help

### Expected behavior

Console output extracted from image [Edited]:

Replaced 套件 or 封裝 with 程式包

```
C:\Users\hwhsu1231>winget --help 
Windows 程式包管理員 v1.2.10941 Copyright (c) Microsoft Corporation.著作權所有,並保留一切權利。

Winget 命令列實用程式可讓您從命令列安裝應用程式和其他 程式包

使用:winget [<命令>] [<選項>]
```

### Actual behavior

Console output extracted from image [Edited]:

```
C:\Users\hwhsu1231>winget --help 
Windows 封裝管理員 v1.2.10941 Copyright (c) Microsoft Corporation.著作權所有,並保留一切權利。

Winget 命令列實用程式可讓您從命令列安裝應用程式和其他 套件

使用:winget [<命令>] [<選項>]
```

### Environment

```shell
See linked VS Community Feedback ticket for more info.
```

**Comment by brlin-tw** [comment]
I'd suggest 軟體包 instead, which literally means "software package".  "software" includes code and non-code resources(like documentation, etc.)

**Comment by denelon** [comment]
@dominoFire

I have the response from the linguist - in short:
They disagree that it's a problem for "package" and "kit" to use the same translation. It could only potentially be an issue if both terms show up in the same string with no context (which is extremely unlikely).
They believe that the current translation is the right one, and the proposed new translations would look odd in most of the scenarios where we use "package".

If you want to follow up on this, feel free to send me an e-mail.
