### ISSUE TITLE
Add `--locale` argument to `show`

### ISSUE THREAD

**Issue by florelis** [microsoft/winget-cli#2238]
### Description of the new feature / enhancement

Add a `--locale` argument to `show` so I can see a package's info in the language I want to install. I want to be able to do
```
> winget show MyApp --locale es
# Shows in Spanish
> winget install MyApp --locale es
# Installs in Spanish
```
instead of
```
> winget show MyApp
# Shows in English or default
> winget install MyApp --locale es
# Installs in Spanish
```

**Comment by Trenly** [comment]
[Policy] Command-Show

**Comment by mdanish-kh** [comment]
`--locale` was added to `winget show` as part of:

- https://github.com/microsoft/winget-cli/pull/2570/

[comment]: <Close with reason: Resolved;>
