### ISSUE TITLE
third-party repository support

### ISSUE THREAD

**Issue by patrick330602** [microsoft/winget-cli#226]
# Description of the new feature/enhancement

the current package managers for windows such as `Scoop` allows you to create your own repository, it would be awesome if you can add your own repo to allow users to customize the repo to their needs. 

# Proposed technical implementation details (optional)

**Comment by megamorf** [comment]
This is already possible as per https://github.com/microsoft/winget-cli#sources:
> The client is built around the concept of sources; a set of packages effectively. Sources provide the ability to discover and retreive the metadata about the packages, so that the client can act on it.
>
> The default source reflects that data available from the Community repo.
>
> We plan to better support additional sources, and additional types of sources, in the future. For now, additional sources can be configured, but only one used at a time.

```powershell
PS > winget source list
PS > winget source add --help
```

You can also simply throw some manifests on a fileshare and install them via:

```powershell
PS > winget install --manifest \\fileserver\share\packagerepo\manifests\mycompany\myapp\1.0.0.yaml
```
See https://aka.ms/winget-command-source for details.

**Comment by megamorf** [comment]
Related issues:
* #160 
* #203
* #213
* #226

**Comment by AntoineTurmel** [comment]
@megamorf but how do you make your own "source" server ?

**Comment by megamorf** [comment]
@AntoineTurmel As of right now the only available source type is `Microsoft.PreIndexed.Package` which is defined as:
https://github.com/microsoft/winget-cli/blob/e997f3e394e66f2389f4f33f36c58b1c2768e975/src/AppInstallerRepositoryCore/Microsoft/PreIndexedPackageSourceFactory.h#L11-L18

Repo updates are done via Azure DevOps pipelines which don't seem to be included in the repos so  no luck there. The only workaround for now is to have manifests and setups on a share and reference those paths in the manifest files. Then, as mentioned before, provide the `--manifest` during the winget install call.

**Comment by denelon** [comment]
#118 May be the most simple way to achieve third-party repository support.

**Comment by rbleattler** [comment]
> This is already possible as per https://github.com/microsoft/winget-cli#sources:
> 
> > The client is built around the concept of sources; a set of packages effectively. Sources provide the ability to discover and retreive the metadata about the packages, so that the client can act on it.
> > The default source reflects that data available from the Community repo.
> > We plan to better support additional sources, and additional types of sources, in the future. For now, additional sources can be configured, but only one used at a time.
> 
> ```powershell
> PS > winget source list
> PS > winget source add --help
> ```
> 
> You can also simply throw some manifests on a fileshare and install them via:
> 
> ```powershell
> PS > winget install --manifest \\fileserver\share\packagerepo\manifests\mycompany\myapp\1.0.0.yaml
> ```
> 
> See https://aka.ms/winget-command-source for details.



> This is already possible as per https://github.com/microsoft/winget-cli#sources:
> 
> > The client is built around the concept of sources; a set of packages effectively. Sources provide the ability to discover and retreive the metadata about the packages, so that the client can act on it.
> > The default source reflects that data available from the Community repo.
> > We plan to better support additional sources, and additional types of sources, in the future. For now, additional sources can be configured, but only one used at a time.
> 
> ```powershell
> PS > winget source list
> PS > winget source add --help
> ```
> 
> You can also simply throw some manifests on a fileshare and install them via:
> 
> ```powershell
> PS > winget install --manifest \\fileserver\share\packagerepo\manifests\mycompany\myapp\1.0.0.yaml
> ```
> 
> See https://aka.ms/winget-command-source for details.

Excellent contribution. Thank you for going out of your way to make this information available to those searching for some sort of solution.

**Comment by denelon** [comment]
It is possible to add additional repositories using `winget source add`.

For help you can execute `winget source -?`

Support for REST API based repositories is nearly complete in the client as of v0.3.

We will be providing a reference implementation of a REST API based source along with our v1.0 release.

**Comment by denelon** [comment]
Updating this issue to help users find the reference implementation at
https://github.com/microsoft/winget-cli-restsource

**Comment by mherrmann** [comment]
For people looking for a private repository, we offer this now as a hosted service at https://winget.pro.

**Comment by Croydon** [comment]
> For people looking for a private repository, we offer this now as a hosted service at https://winget.pro.

Since this service isn't part of Microsoft, I don't think that you should use the winget name like that

**Comment by rbleattler** [comment]
I definitely agree with this…  


> > For people looking for a private repository, we offer this now as a hosted service at https://winget.pro.
> 
> Since this service isn't part of Microsoft, I don't think that you should use the winget name like that

**Comment by thilojaeggi** [comment]
Not sure if it's ok to also advertise here but seeing since Winget.pro did it, I've created WinGetty over here: https://github.com/thilojaeggi/WinGetty which does everything Winget.pro does and more with the addition of it being open source and self-host able.
