### ISSUE TITLE
a "repository" command that allows us to search the entire repository for a specified string

### ISSUE THREAD

**Issue by solomoncyj** [microsoft/winget-cli#2267]
### Description of the new feature / enhancement

a "repository" command that allows us to search the entire repository for a specified string
this will help with cmdlets not working normally
eg. 
>list all packages in the winget-pkgs repository
```winget repository```
>list all packages in the winget-pkgs repository containing the string "rust"
```winget repository rust ```

**Comment by Trenly** [comment]
> > list all packages in the winget-pkgs repository containing the string "rust"
> > `winget repository rust `

![image](https://user-images.githubusercontent.com/12611259/174935675-0f13f696-21c7-4233-9abd-b03687a40a4b.png)
