### ISSUE TITLE
Add aliases for installation and uninstallation

### ISSUE THREAD

**Issue by wmstack** [microsoft/winget-cli#2303]
### Description of the new feature / enhancement

Make `add` and `i` aliases for `install` in winget. `add` is used by NPM, by the yarn package manager, and by cargo-edit. Different names improve the experience for newcomers, which, if they come from different package managers, might be used to different names for installing packages, and it would be delightful if they just work.

Also add `r` or `rm` and `remove` as aliases to `uninstall`. `remove` is used by the apt-package manager, so it would be helpful if users of apt can have the same feel with Winget. One letter subcommand aliases might feel wrong, however, NPM has one for installation. Another option is to have `u` as an alias for uninstall, though I don't recommend it.

Could also add `ls` as an alias for `list`. However, it depends on how much the team focuses on UX or DX. I personally strongly suggest those aliases, which need to be strongly tied to historical command names. For example, the apt package manager for linux was perhaps the oldest and most popular, and it has the `remove` keyword for removing a package. So if we reuse its subcommand names, we reduce the friction.

### Notes
One downside is this would give us fewer names for new commands. However, I think that if the package manager makes two similar names for different commands, then it is not a good package manager, solely for that reason. My experience with the rustup package manager in particular strengthens that feeling about similar names, because it has both a target subcommand and a toolchain subcommand and I always mess them up.

Edit: I want to show you the NPM package manager `npm-install` synopsis:
https://docs.npmjs.com/cli/v8/commands/npm-install
```
npm install [<package-spec> ...]

aliases: add, i, in, ins, inst, insta, instal, isnt, isnta, isntal, isntall
```
What do you think?

### Proposed technical implementation details

Make `i`, `add` aliases for `install`, and document them, including in the help page. Make `rm` and `remove` aliases for `uninstall` and document them in the help page as well. Make `ls` an alias for `list`.

**Comment by PlexPt** [comment]
+1

**Comment by vedantmgoyal2009** [comment]
This is something I would also upvote for.

**Comment by wmstack** [comment]
> This is something I would also upvote for, except making remove, etc.. an alias for uninstall.

Not sure why you are against making remove and alias for uninstall. Even NPM has that...
Source: https://docs.npmjs.com/cli/v8/commands/npm-uninstall/
```
npm uninstall [<@scope>/]<pkg>...

aliases: unlink, remove, rm, r, un
```

**Comment by Trenly** [comment]
If anyone has any strong opinions on aliases, i.e, if any others should be added, please post a comment on the linked PR
