### ISSUE TITLE
winget and python installations

### ISSUE THREAD

**Issue by sbwiecko** [microsoft/winget-cli#2306]
### Description of the new feature / enhancement

I wish winget would not suggest any major upgrades for Python when different versions of Python are installed.

For example, when Python v3.9 and Python v3.10.5 are installed on the same system, winget will still offer an upgrade from 3.9.13 to 3.10.5, although v3.9.13 and v3.10.5 are up to date.

### Proposed technical implementation details

I want winget to check for the availability of minor updates for each version of Python instead.
Each version of Python, i.e., Python 3.8, Python 3.9, Python 3.10, should have its own line in `winget upgrade` as it is with `winget list`.

**Comment by Trenly** [comment]
Seems like this is the same as #476 ?

**Comment by sbwiecko** [comment]
Not so sure, I'm not suggesting blocking a program but rather separate it based on its major versions, just like `winget list` does.

**Comment by vedantmgoyal2009** [comment]
@denelon python versions have been now put under separate package identifiers, so this can be marked as fixed.
