### ISSUE TITLE
Winget does not start, 0x80070057 in Event Viewer

### ISSUE THREAD

**Issue by zdimension** [microsoft/winget-cli#2329]
### Brief description of your issue

Winget does not start at all.

### Steps to reproduce

Install Winget from MSIX bundle. This works fine on my other Windows boxes.

### Expected behavior

I expected Winget to work properly.

### Actual behavior

Winget does not start. In the CMD or in PowerShell, nothing is printed.

After running `winget`, the Event Viewer contains two identical (same time, same content) events from AppModel-State, with description
```
Échec de l’instanciation du dossier de stockage C:\Users\...\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState pour le package Microsoft.DesktopAppInstaller_8wekyb3d8bbwe avec le code d’erreur : -2147024809
```
Detailed data:
```xml
<EventData>
  <Data Name="FolderString">C:\Users\...\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState</Data> 
  <Data Name="PackageString">Microsoft.DesktopAppInstaller_8wekyb3d8bbwe</Data> 
  <Data Name="Error">-2147024809</Data> 
</EventData>
```
I tried uninstalling the Microsoft.DesktopAppInstaller package (to reinstall it afterwards), but even that fails.
```
PS C:\WINDOWS\system32> Remove-AppxPackage Microsoft.DesktopAppInstaller
Remove-AppxPackage : Échec du déploiement avec HRESULT : 0x80073CFA, Échec de la suppression. Contactez votre fournisseur de logiciel. (Exception de HRESULT : 0x80073CFA)
Le gestionnaire de package a abandonné l’opération Remove, car un argument non valide a été transmis : Microsoft.DesktopAppInstaller.
REMARQUE: pour obtenir des informations supplémentaires, recherchez [ActivityId] 2305a5aa-867d-0000-e22e-20237d86d801 dans le journal des événements ou utilisez la ligne de commande Get-AppPackageLog -ActivityID 2305a5aa-867d-0000-e22e-20237d86d801
Au caractère Ligne:1 : 1
+ Remove-AppxPackage Microsoft.DesktopAppInstaller
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Microsoft.DesktopAppInstaller:String) [Remove-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.RemoveAppxPackageCommand
```
Short of reinstalling Windows (which is obviously a non-solution), I don't see anything else to try.

### Environment

Winget does not start, so I can't run winget --info.

Windows 10 Pro 21H2 19044.1766 x64

**Comment by JohnMcPMS** [comment]
My guess is that `C:\Users\...\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe` has gotten into a bad state somehow.  If you can remove that location, then I think it should start working.  There might be more subtle ways than that, but it should be effective without causing any large issues (just some minor data loss if you had been using it before).

**Comment by zdimension** [comment]
@JohnMcPMS just tried, now I'm getting a different error!
![image](https://user-images.githubusercontent.com/4533568/178791490-a38ce41c-1d19-47f2-8a88-81480e32c3df.png)

Let's see what pwsh has to say about it:
![image](https://user-images.githubusercontent.com/4533568/178791563-d0370d08-a58b-4616-8de1-ff1d4ad0d0d9.png)

**Comment by JohnMcPMS** [comment]
Did you Add-AppxPackage it back?  I don't know what state the package is in at this point.  If it is "there", you could try to Reset it from the settings app.

**Comment by zdimension** [comment]
Reinstalling the latest GH appx file using Add-AppxPackage fixed the problem. Still no idea how it ended in the broken state it was in before (winget never worked on this machine). Thanks!
