### ISSUE TITLE
winget does not run in WSL2 due to exec format error

### ISSUE THREAD

**Issue by mdales** [microsoft/winget-cli#234]
# Brief description of your issue

When invoking winget from WSL it does not run due to exec format error

# Steps to reproduce

I run $HOME/AppData/Local/Microsoft/WindowsApps/winget.exe

# Expected behavior

Winget shows me a list of command options

# Actual behavior
```
Failed to execute process '/mnt/c/Users/mdale/AppData/Local/Microsoft/WindowsApps/winget.exe'. Reason:
exec: Exec format error
The file '/mnt/c/Users/mdale/AppData/Local/Microsoft/WindowsApps/winget.exe' is marked as an executable but could not be run by the operating system.
```

# Environment

WSL2 with Ubuntu, running on slow ring insider build 19041. Winget does run from PowerShell. The path I used is from Get-Command winget in Powershell.

**Comment by ChrisMcKee** [comment]
As its a windows package manager I'd be surprised if there's any expectation for it to run in WSL considering its Linux. Ubuntu has snap/apt etc

**Comment by mdales** [comment]
Just to be clear, I don't expect winget to install things inside WSL, but WSL is my default shell, and I run other windows commands from inside there. I'd still like to be able to provision windows apps like Visual Studio from my WSL shell.

But I agree this isn't to replace snap/apt etc.

**Comment by szkocot** [comment]
I have same expectations about winget as @mdales. It should work well with wsl2 and windows terminal as a complete development and package manager environment (that was missing in windows as many devs/pro users were forced to move to Ubuntu).

**Comment by jusefn** [comment]
I have figured out a workaround for this.

- Open your `~/.bashrc` file in your editor of choice (or `~/.zshrc` if you use zsh instead of bash) 

- Add the following line at the end of the file
`function winget { cmd.exe /c "winget $1";}`

- Then launch `source ~/.bashrc` (or `source ~/.zshrc`) if you don't want to relaunch your shell.

And winget should work inside a WSL2 shell.

I hope this is helpful.

**Comment by JtMotoX** [comment]
> EDIT: Figured out you would need 3 variables for passing additional commands/options

Thanks @jusefn this is just what I was looking for.  I did notice that I was getting a UNC error when I used your function so I added the cd command to fix that error.  I also added the $@ parameter which will just pass as many parameters that you pass, may that be 1, 2, 3, ...

```bash
function winget { (cd /mnt/c; cmd.exe /c "winget $@";) }
```

**Comment by vbrozik** [comment]
In my case (Windows 10 21H2, build 19044.2130) the behaviour is even worse. No error message is being shown, no error status code returned. The system behaves as if the command executed correctly:
```
~$ winget.exe
~$ echo $?
0
```

**Comment by Trenly** [comment]
@mdales - Is this issue still happening?

```
trenly@CORSAIR-JLU545:/mnt/e/winget-pkgs$ /mnt/c/users/Trenly/AppData/Local/Microsoft/WindowsApps/winget.exe --version
v1.9.25200
trenly@CORSAIR-JLU545:/mnt/e/winget-pkgs$ /mnt/c/users/Trenly/AppData/Local/Microsoft/WindowsApps/winget.exe search Google.Chrome -s winget
Name                       Id                             Version
-----------------------------------------------------------------------
Google Chrome              Google.Chrome                  131.0.6778.86
Google Chrome Beta         Google.Chrome.Beta             132.0.6834.15
Google Chrome Beta (EXE)   Google.Chrome.Beta.EXE         132.0.6834.15
Google Chrome Canary       Google.Chrome.Canary           133.0.6857.0
Google Chrome Dev          Google.Chrome.Dev              133.0.6847.2
Google Chrome Dev (EXE)    Google.Chrome.Dev.EXE          133.0.6847.2
Google Chrome (EXE)        Google.Chrome.EXE              131.0.6778.86
Chrome Remote Desktop Host Google.ChromeRemoteDesktopHost 131.0.6778.26
```

**Comment by vbrozik** [comment]
I can confirm that in my case `winget.exe` works now:

``` terminal
vbrozik@NTT-44Q83J3:~$ winget.exe --version
v1.9.25200

vbrozik@NTT-44Q83J3:~$ winget.exe list | head
Name                                           Id                                              Version          Source
-----------------------------------------------------------------------------------------------------------------------
AutoHotkey                                     AutoHotkey.AutoHotkey                           2.0.18           winget
Docker Desktop                                 Docker.DockerDesktop                            4.36.0           winget
Git                                            Git.Git                                         2.47.0.2         winget
Intel(R) Arc Software & Drivers                ARP\Machine\X64\Intel(R) Arc Software & Drivers 1.0.916.8
Mozilla Firefox (x64 en-US)                    Mozilla.Firefox                                 132.0.2          winget
Mozilla Maintenance Service                    ARP\Machine\X64\MozillaMaintenanceService       129.0.2
Notepad++ (64-bit x64)                         Notepad++.Notepad++                             8.7.1            winget
Microsoft 365 Apps pro velké organizace - cs-… ARP\Machine\X64\O365ProPlusRetail - cs-cz       16.0.18025.20214
```

**Comment by mdales** [comment]
I can't reproduce this anymore due to lack of environment. Feel free to close based on @vbrozik comment.
