### ISSUE TITLE
winget upgrade does not regognize installed updates

### ISSUE THREAD

**Issue by Heldenkrieger01** [microsoft/winget-cli#2349]
### Brief description of your issue

I have installed Typora.Typora via winget, previously version 1.3.6. After the prompt to update to 1.3.8, which was successfully installed by winget, the update keeps appearing on winget upgrade and winget will try to update again.

Almostm the same thing happens with Rustlang.Rustup. The version says unknown, avialable is 1.24.3, but this version is already installed.

### Steps to reproduce

-

### Expected behavior

winget recognizes the installed version correctly and does not prompt for an unnecessary update.

### Actual behavior

winget prompts for updates which are already installed

### Environment

```shell
Windows Package Manager v1.2.11601

Windows: Windows.Desktop v10.0.22622.290
Package: Microsoft.DesktopAppInstaller v1.17.11601.0
```

**Comment by denelon** [comment]
If the version is displayed as "Unknown" the installer for that package didn't report a version to the registry as you would see in Windows Apps & Features or in Add Remove Programs. It's up to the installer to report the software version installed.

If an "upgrade" is actually just installing a newer version of a package side-by-side then the Windows Package Manager would see the "older" version and still think an upgrade is necessary. We have work in progress for Windows Package Manager 1.4-preview to address this scenario.

**Comment by Trenly** [comment]
Typora actually was using the wrong URL's, I've submitted two PR's over at pkgs to fix Typora

**Comment by zuhairmahd** [comment]
This is happening on Microsoft packages:

PS C:\Windows\System32>
PS C:\Windows\System32> winget upgrade --all
Name                                                  Id                                Version  Available   Source
-------------------------------------------------------------------------------------------------------------------
Winamp                                                Radionomy.Winamp                  5.8      5.8         winget
Python 3.10.4 (64-bit)                                Python.Python.3                   < 3.10.5 3.10.4150.0 winget
Microsoft ASP.NET Core 6.0.6 - Shared Framework (x86) Microsoft.DotNet.AspNetCore.6     6.0.6    6.0.7       winget
Microsoft Windows Desktop Runtime - 6.0.6 (x86)       Microsoft.DotNet.DesktopRuntime.6 6.0.6    6.0.7       winget
Microsoft .NET SDK 6.0.203 (x64)                      Microsoft.DotNet.SDK.6            6.0.203  6.0.302     winget
5 upgrades available.

(1/5) Found Winamp [Radionomy.Winamp] Version 5.8
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.nullsoft.com/winamp/misc/winamp58_3660_beta_full_en-us.exe
  ██████████████████████████████  7.82 MB / 7.82 MB
Successfully verified installer hash
Starting package install...
Successfully installed

(2/5) Found Python 3 [Python.Python.3] Version 3.10.4150.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.python.org/ftp/python/3.10.4/python-3.10.4-amd64.exe
  ██████████████████████████████  27.1 MB / 27.1 MB
Successfully verified installer hash
Starting package install...
Successfully installed

(3/5) Found Microsoft ASP.NET Core Runtime 6.0 [Microsoft.DotNet.AspNetCore.6] Version 6.0.7
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/6.0.7/aspnetcore-runtime-6.0.7-win-x64.exe
  ██████████████████████████████  8.58 MB / 8.58 MB
Successfully verified installer hash
Starting package install...
Successfully installed

(4/5) Found Microsoft .NET Windows Desktop Runtime 6.0 [Microsoft.DotNet.DesktopRuntime.6] Version 6.0.7
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/6.0.7/windowsdesktop-runtime-6.0.7-win-x64.exe
  ██████████████████████████████  55.0 MB / 55.0 MB
Successfully verified installer hash
Starting package install...
Successfully installed

(5/5) Found Microsoft .NET SDK 6.0 [Microsoft.DotNet.SDK.6] Version 6.0.302
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.302/dotnet-sdk-6.0.302-win-x64.exe
  ██████████████████████████████   196 MB /  196 MB
Successfully verified installer hash
Starting package install...
Successfully installed

PS C:\Windows\System32>
PS C:\Windows\System32> winget upgrade
Name                                                  Id                                Version  Available   Source
-------------------------------------------------------------------------------------------------------------------
Winamp                                                Radionomy.Winamp                  5.8      5.8         winget
Python 3.10.4 (64-bit)                                Python.Python.3                   < 3.10.5 3.10.4150.0 winget
Microsoft ASP.NET Core 6.0.6 - Shared Framework (x86) Microsoft.DotNet.AspNetCore.6     6.0.6    6.0.7       winget
Microsoft Windows Desktop Runtime - 6.0.6 (x86)       Microsoft.DotNet.DesktopRuntime.6 6.0.6    6.0.7       winget
Microsoft .NET SDK 6.0.203 (x64)                      Microsoft.DotNet.SDK.6            6.0.203  6.0.302     winget
5 upgrades available.
PS C:\Windows\System32> exit

C:\Windows\System32>

**Comment by Trenly** [comment]
@zuhairmahd - As denelon said
> If an "upgrade" is actually just installing a newer version of a package side-by-side then the Windows Package Manager would see the "older" version and still think an upgrade is necessary. We have work in progress for Windows Package Manager 1.4-preview to address this scenario.

See also #2345 and #1413

**Comment by Heldenkrieger01** [comment]
> Typora actually was using the wrong URL's, I've submitted two PR's over at pkgs to fix Typora

After _another_ install of the update, Typora finally went away, thank you!

**Comment by krystofkrticka** [comment]
I also have this issue if I take Python as example it says that there is newer version but that's not true 
![image](https://user-images.githubusercontent.com/37749100/180394837-c2006686-a274-440a-bef5-50501b224afa.png)
this is what winget shows but when I open appwiz.cpl and search for Python I have higher version than what winget says.
![image](https://user-images.githubusercontent.com/37749100/180395031-bef945ea-dc3c-48be-bc2e-8a45ff804800.png)

Same goes with UltraVNC from which winget says I have 1.3.6.0 but appwiz.cpl says that I have version 1.3.8.1.
