### ISSUE TITLE
Can't uninstall winget-cli

### ISSUE THREAD

**Issue by ermshiperete** [microsoft/winget-cli#236]
# Brief description of your issue

It is not possible to uninstall winget-cli

# Steps to reproduce

- [download]((https://github.com/microsoft/winget-cli/releases/download/v0.1.4331-preview/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle)) winget-cli from GitHub release page and install
- Open "Add or remove programs" (Apps & features) in Windows, search for winget and click uninstall

# Expected behavior

winget-cli is no longer available, can be installed again.

# Actual behavior

winget-cli is still available. Trying to install it again shows the message "App Installer is already installed".

It no longer shows up in "Add or remove programs" though.

# Environment

```none
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18362.836
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
```

**Comment by steviecoaster** [comment]
`Get-AppXPackage Microsoft.DesktopAppInstaller | Remove-AppXPackage`

**Comment by KevinLaMS** [comment]
Thanks for providing the work around.  It is a interesting issue.

**Comment by driver1998** [comment]
But the problem is AppInstaller (the UWP portion of this) is the builtin APPX/MSIX handler, it is the UI show up when you double click a APPX/MSIX file. You'll lost this functionally if you uninstall AppInstaller.

I always wonder why winget is bundled inside AppInstaller though.

**Comment by denelon** [comment]
The Windows Package Manager is now a stable product. It is shipped within the "App Installer". It's possible to revert to a stable release by installing the stable release from the Microsoft Store (assuming you aren't on a Windows Insider build or are a member of the Windows Package Manager Insider program) or [GitHub releases](https://github.com/microsoft/winget-cli/releases).
