### ISSUE TITLE
Installing appxbundle shows unclear "Update ms-resource:appDisplayName?" text

### ISSUE THREAD

**Issue by riverar** [microsoft/winget-cli#237]
# Steps to reproduce

1. Download the [appxbundle](https://github.com/microsoft/winget-cli/releases/download/v0.1.4331-preview/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle).
2. Double-click the .appxbundle.
3. Observe confusing AppInstaller dialog text.

![image](https://user-images.githubusercontent.com/475132/82419109-c3aa9480-9a32-11ea-8c40-65f3edf618b1.png)

# Environment

```none
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.207
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
```

**Comment by MarkTiedemann** [comment]
Had the same issue. Running `Get-AppxPackage -AllUsers | Foreach { Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml" }` in an elevated PowerShell, as suggested on [Reddit](https://www.reddit.com/r/Windows10/comments/70tbti/msresourceappdisplayname_in_start_menu_seems_to/), fixed it.

**Comment by denelon** [comment]
Is this issue resolved?

**Comment by riverar** [comment]
@denelon Appears to be.

![image](https://user-images.githubusercontent.com/475132/103836632-7a00cf80-503e-11eb-8e21-57d84587a839.png)

**Comment by denelon** [comment]
Thanks for the quick update. We will dig in and see where the issue is.

**Comment by riverar** [comment]
@denelon No issue. You asked if it was resolved and I said yes. 👍

**Comment by JohnMcPMS** [comment]
I will have to look into it, but I believe that the bug and this display is in the older version of the package.  So if you are updating *from* that version, it will always be there.  @shessane , do you know what version the package was before the update?

**Comment by JohnMcPMS** [comment]
Confirmed that the bug is in the code of the package, and thus our new packages will still show up like this if the currently installed package is older and has the bug in it.

**Comment by shessane** [comment]
I think you are right. I've tried running the installer last year but I failed to get it work.
Any idea on how to clean my previous installation ? Many thanks

**Comment by JohnMcPMS** [comment]
You shouldn't need to do anything extra if you have already updated to the latest package.  You can check with PowerShell:
```PowerShell
> Get-AppxPackage Microsoft.DesktopAppInstaller
```
And making sure that the version is 1.11.10***.0
