### ISSUE TITLE
Winget not updated. Stuck on v1.2.11601

### ISSUE THREAD

**Issue by myokeeh** [microsoft/winget-cli#2372]
### Brief description of your issue

I have a machine that is stuck on v1.2.11601. It is the Store version via App Installer. There are no updates for App Installer when I check the Store app.

### Steps to reproduce

N/A

### Expected behavior

App Installer should update winget

### Actual behavior

App Installer doesn't update winget

### Environment

```shell
Windows Package Manager v1.2.11601
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.232
Package: Microsoft.DesktopAppInstaller v1.17.11601.0
```

**Comment by denelon** [comment]
@myokeeh, you have the latest stable client. We're in a release candidate state for Windows Package Manager 1.3 and preview state for Windows Package Manager 1.4. Newer clients may be installed via this GitHub repositories [releases](https://github.com/microsoft/winget-cli/releases], or in Windows Insider builds (and the Windows Package Manager Insiders group) as referenced on the main [README](https://github.com/microsoft/winget-cli/blob/master/README.md).

**Comment by vedantmgoyal2009** [comment]
@myokeeh is the issue resolved now?

cc @denelon
