### ISSUE TITLE
winget is localized for my region, even when my UI-language is set to en-US

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/winget-cli#238]
# Brief description of your issue

I am running an English version of Windows, but live in The Netherlands. So my UI culture and my region settings are different. All my apps should be defaulting to showing their UI in English, but the currency and date formats in Dutch.

winget shows most of its text as Dutch:
![image](https://user-images.githubusercontent.com/4173387/82429301-f16ff780-9a8b-11ea-8497-38ce5a83dcef.png)

# Steps to reproduce

Windows Country or region: The Netherlands
Windows Regional format: English (Europe)
![image](https://user-images.githubusercontent.com/4173387/82460443-7291b380-9ab9-11ea-8f86-da3cf099064a.png)

Windows Display Language: English
![image](https://user-images.githubusercontent.com/4173387/82460476-7e7d7580-9ab9-11ea-9512-671249cf56ad.png)

# Expected behavior

the text output from winget is English

# Actual behavior

the text output is Dutch

# Environment

```none
Windows Package Manager v0.1.41331 Voorbeeld
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.264
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
```

**Comment by jessehouwing** [comment]
Found the reason. Because this is a store app,  my Microsoft Account display language is used. This is pretty counterintuitive.

To see what your current language is, check the display language
![image](https://user-images.githubusercontent.com/4173387/82491628-3116fd80-9ae5-11ea-9669-c281a248966e.png)

Then open the Microsoft store app and download updates. It may take a while for the setting to sync.

I consider this a bug, my Windows installation has a UI language set, applications should follow it, but I'm guessing this is a WinRT remnant from the phone era we're now stuck with. I'd like a way to override the display language through configuration.

See also:

 * https://support.office.com/en-us/article/Display-language-doesn-t-change-in-Mail-and-Calendar-apps-for-Windows-10-3df52f6d-e9fe-4a65-9446-1b0a2f213368

**Comment by FaffeF** [comment]
This mess is very common in Microsoft apps, and was a major annoyance for years in Windows 10. Please don't bring it back.

**Comment by KevinLaMS** [comment]
Thanks for reporting this.  I am struggling a little bit with the repo however.  I am finding that the language for the client is responding to the Windows display language. 
IMO, the language used by the client should come from Windows display language, so it is correct.  Did it eventually update per the link you provided?  

We can investigate adding a language override in options.  
Thanks

**Comment by jessehouwing** [comment]
Yeah, the appstore language change eventually synced to windows. I'm happily on English now.

It's funny how much of Windows assumes I will constantly deliberately switch between languages.

**Comment by FaffeF** [comment]
I think I found out what my problem was: my Windows preferred language order was English (Sweden), Swedish (Sweden), English (United States).

This probably meant that Winget ignored English (Sweden) and went straight to Swedish. I don't understand the reasoning behind the separation between preferred language and Windows display language, but my expectation would be that if your app doesn't support English (whatever), just do English (US/UK/AUS/CAN), cause the differences are small enough that it doesn't matter.

Still didn't fix the Windows Store app.

**Comment by denelon** [comment]
Is this issue resolved?

**Comment by FaffeF** [comment]
Seems to work, adhering to the order of languages in the "Preferred languages" list, as output by Get-WinUserLanguageList.

This is probably correct, though as a user I can't really understand why there is a setting for "Windows display language" that is separate from "Preferred language"

**Comment by denelon** [comment]
This issue appears to be related to how Windows handles language priority.

**Comment by yeya** [comment]
> We can investigate adding a language override in options. Thanks

Language override by options will be great. The default font of cli \ powershell doesn't support my windows display language so I like to set only winget to english.

**Comment by craftzdog** [comment]
`Set-WinUserLanguageList` solved the issue.

https://docs.microsoft.com/en-us/powershell/module/international/set-winuserlanguagelist?view=windowsserver2019-ps

**Comment by PeterVeg** [comment]
Thank you, this is great.
