### ISSUE TITLE
Wrong version shown

### ISSUE THREAD

**Issue by WSemeniuk** [microsoft/winget-cli#2381]
This morning when running "winget upgrade", I received the following list:

PS C:\Users\W> winget upgrade

Name            Id              Version Available Source
--------------------------------------------------------
Mozilla Firefox Mozilla.Firefox 86.0    103.0     winget
NAPS2           Cyanfish.NAPS2  Unknown 6.1.2     winget
GOG GALAXY      GOG.Galaxy      Unknown 2.0.49.1  winget

This is odd as the version of FF I have installed on my computer is current 104.0[
![image](https://user-images.githubusercontent.com/46420594/181261293-deb2d0da-679c-440b-aebc-6d46391899f9.png)
](url)

For now, I will just ignore it (as I do with the apps showing unknown versions) but thought that others might be seeing similar issues.

**Comment by Trenly** [comment]
Duplicate of #2380
