### ISSUE TITLE
Support additional arguments as well as overridden arguments

### ISSUE THREAD

**Issue by gmckeown** [microsoft/winget-cli#239]
# Description of the new feature/enhancement

Some installers, for example WinSCP, pop up a dialog asking whether I wish to install for current user or all users (note: #149 might be relevant for this _specific_ case).

WinSCP supports the /ALLUSERS  and /CURRENTUSER options to cater for this; however, if I use ``--override`` it clears all options specified in the manifest and replaces them. So the following ends up performing an interactive install:

```winget install --override "/ALLUSERS" winscp```

So I locate the manifest, identify that it has the /VERYSILENT option and change my command to:

```winget install --override "/VERYSILENT /ALLUSERS" winscp```

This achieves what I want -- a completely silent install with my chosen option.

# Proposed technical implementation details (optional)

A new switch that *adds* the listed arguments to the installer command-line rather than replaces them. This would supplement the ``--override`` option rather than replacing it.

Something along the lines of the following would then allow me to retain the manifest-specified default options, whilst still including my choices:

```winget install --pass-args "/ALLUSERS" winscp```

They key benefit here is that if the authors of the manifest add new default options, I don't have to manually modify my install command to match.

**Comment by RehanSaeed** [comment]
I would like to see custom install arguments for each app when I do:

```
> winget install Microsoft.VisualStudio --help
> --python - Installs python
> --Node - Installs Node
> etc....
```

I would also like a **guided installation** where the installer UI shows up and I can personally select options and manually hit next, next, next, finish.

```
> winget install Microsoft.VisualStudio --guided
```

**Comment by iDolmatov** [comment]
I found an opportunity to specify additional attributes in the manifest and in the source code, but this is not fully implemented.
Cannot be started with the described command. You cannot get data from manifest when getting information about a package (_winget show_) and when polling a command (example _winget install TestApp -custom -?_).
https://github.com/microsoft/winget-cli/discussions/1067

**Comment by denelon** [comment]
@RehanSaeed `winget install <package> --interactive` should do what you're looking for.

```
 winget install -?
Windows Package Manager v1.0.11451
Copyright (c) Microsoft Corporation. All rights reserved.

Installs the selected package, either found by searching a configured source or directly from a manifest. By default, the query must case-insensitively match the id, name, or moniker of the package. Other fields can be used by passing their appropriate option.

usage: winget install [[-q] <query>] [<options>]

The following arguments are available:
  -q,--query        The query used to search for a package

The following options are available:
  -m,--manifest     The path to the manifest of the package
  --id              Filter results by id
  --name            Filter results by name
  --moniker         Filter results by moniker
  -v,--version      Use the specified version; default is the latest version
  -s,--source       Find package using the specified source
  --scope           Select install scope (user or machine)
  -e,--exact        Find package using exact match
  -i,--interactive  Request interactive installation; user input may be needed
  -h,--silent       Request silent installation
  --locale          Locale to use (BCP47 format)
  -o,--log          Log location (if supported)
  --override        Override arguments to be passed on to the installer
  -l,--location     Location to install to (if supported)

More help can be found at: https://aka.ms/winget-command-install
```

**Comment by iDolmatov** [comment]
> @RehanSaeed `winget install <package> --interactive` should do what you're looking for.

This is not what he is asking for. We need a hidden installation, but with the ability to specify parameters.

The existing parameters in the manifest must be saved so that the user does not rewrite them.
The key I mentioned would be quite applicable when you specify additional parameters after this key. If some switches from the "Silent" / "SilentWithProgress" / "Interactive" lines are duplicated with those entered after "Custom", then the duplicated switches are not reused.
Additionally, should be added a  "--help-custom" command, which will show the valid parameters based on the data from the manifest. If there is no data in the manifest, look at the type of the installer and indicate the known switches for this type.

At the moment, none of the moderators and developers have been able to fully explain how the "Custom" switch works. The description of this key explicitly states that it is used for additional parameters. It is not logical if it is automatically added to the required parameters. Either this key is not fully implemented, or there is a bug with its work and lack of description.

**Comment by iDolmatov** [comment]
Examples (not real data).
Use
`winget install <package> --interactive /custom /D=C:\MyProgram`
`winget install <package> /custom /D=C:\MyProgram`
`winget install <package> --scope USER /custom /Portable /D=F:\MyProgram`

Help (not real data)
`winget install <package> --helpcustom`
Answer: `/D /F /L=%Location%`

**Comment by denelon** [comment]
@iDolmatov "Custom" switches are passed to the installer regardless of whether it is executed with "Silent", "SilentWithProgress", or "Interactive". The "Custom" switches are optional, and not required. The only time "Silent" and "SilentWithProgress" are required is when you have an .exe installer (not Nullsoft, Inno, or another known "InstallerType") to support those installation modes in the client.

**Comment by iDolmatov** [comment]
https://github.com/microsoft/winget-pkgs/tree/master/manifests/a/AIMP/AIMP
`    Custom: /RUN`

What's wrong? Bug?

Try use:

> PS C:\Users\Dolma> winget install AIMP /custom
> Windows Package Manager v1.0.11451
> (с) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
> 
> Нашел позиционный аргумент, когда никто не ожидал : '/custom'
> 
> Устанавливает выбранный пакет, обнаруженный либо путем поиска в настроенном источнике, либо непосредственно из манифеста. По умолчанию запрос должен сравнить идентификатор, имя или моникер пакета (без учета регистра). Можно использовать и другие поля, указав соответствующий параметр.
> 
> использование: winget install [[-q] <query>] [<параметры>]
> 
> Доступны следующие аргументы:
>   -q,--query        Запрос, используемый для поиска пакета
> 
> Доступны следующие опции:
>   -m,--manifest     Путь к манифесту пакета
>   --id              Фильтровать результаты по идентификатору
>   --name            Фильтровать результаты по имени
>   --moniker         Фильтровать результаты по моникеру
>   -v,--version      Использовать указанную версию; по умолчанию используется последняя версия
>   -s,--source       Поиск пакета с помощью указанного источника
>   --scope           Выберите область установки (пользователь или компьютер)
>   -e,--exact        Поиск пакета по точному совпадению
>   -i,--interactive  Запросить интерактивную установку; может потребоваться ввод данных пользователем
>   -h,--silent       Запросить автоматическую установку
>   --locale          Используемый языковой стандарт (формат BCP47)
>   -o,--log          Расположение журнала (если поддерживается)
>   --override        Переопределить аргументы, передаваемые установщику
>   -l,--location     Место для установки (если поддерживается)
>   --force           Переопределить проверку хэша установщика
> 
> Дополнительную справку можно получить по адресу: https://aka.ms/winget-command-install
> PS C:\Users\Dolma> winget install AIMP -custom
> Windows Package Manager v1.0.11451
> (с) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
> 
> Только один псевдоним символа может появляться после одного - : '-custom'
> 
> Устанавливает выбранный пакет, обнаруженный либо путем поиска в настроенном источнике, либо непосредственно из манифеста. По умолчанию запрос должен сравнить идентификатор, имя или моникер пакета (без учета регистра). Можно использовать и другие поля, указав соответствующий параметр.
> 
> использование: winget install [[-q] <query>] [<параметры>]
> 
> Доступны следующие аргументы:
>   -q,--query        Запрос, используемый для поиска пакета
> 
> Доступны следующие опции:
>   -m,--manifest     Путь к манифесту пакета
>   --id              Фильтровать результаты по идентификатору
>   --name            Фильтровать результаты по имени
>   --moniker         Фильтровать результаты по моникеру
>   -v,--version      Использовать указанную версию; по умолчанию используется последняя версия
>   -s,--source       Поиск пакета с помощью указанного источника
>   --scope           Выберите область установки (пользователь или компьютер)
>   -e,--exact        Поиск пакета по точному совпадению
>   -i,--interactive  Запросить интерактивную установку; может потребоваться ввод данных пользователем
>   -h,--silent       Запросить автоматическую установку
>   --locale          Используемый языковой стандарт (формат BCP47)
>   -o,--log          Расположение журнала (если поддерживается)
>   --override        Переопределить аргументы, передаваемые установщику
>   -l,--location     Место для установки (если поддерживается)
>   --force           Переопределить проверку хэша установщика
> 
> Дополнительную справку можно получить по адресу: https://aka.ms/winget-command-install
> PS C:\Users\Dolma> winget install AIMP --custom
> Windows Package Manager v1.0.11451
> (с) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
> 
> Имя аргумента не распознано для текущей команды : '--custom'
> 
> Устанавливает выбранный пакет, обнаруженный либо путем поиска в настроенном источнике, либо непосредственно из манифеста. По умолчанию запрос должен сравнить идентификатор, имя или моникер пакета (без учета регистра). Можно использовать и другие поля, указав соответствующий параметр.
> 
> использование: winget install [[-q] <query>] [<параметры>]
> 
> Доступны следующие аргументы:
>   -q,--query        Запрос, используемый для поиска пакета
> 
> Доступны следующие опции:
>   -m,--manifest     Путь к манифесту пакета
>   --id              Фильтровать результаты по идентификатору
>   --name            Фильтровать результаты по имени
>   --moniker         Фильтровать результаты по моникеру
>   -v,--version      Использовать указанную версию; по умолчанию используется последняя версия
>   -s,--source       Поиск пакета с помощью указанного источника
>   --scope           Выберите область установки (пользователь или компьютер)
>   -e,--exact        Поиск пакета по точному совпадению
>   -i,--interactive  Запросить интерактивную установку; может потребоваться ввод данных пользователем
>   -h,--silent       Запросить автоматическую установку
>   --locale          Используемый языковой стандарт (формат BCP47)
>   -o,--log          Расположение журнала (если поддерживается)
>   --override        Переопределить аргументы, передаваемые установщику
>   -l,--location     Место для установки (если поддерживается)
>   --force           Переопределить проверку хэша установщика
> 
> Дополнительную справку можно получить по адресу: https://aka.ms/winget-command-install
> PS C:\Users\Dolma>

**Comment by denelon** [comment]
The "Custom" flags are passed to the installer in addition to the "Silent" or "SilentWithProgress" or "Interactive" depending on what install mode was selected.

For a "Silent" install, the installer would receive `/RUN /AUTO /SILENT`.
For a "SilentWithProgress" install, the installer would receive `/RUN /AUTO`.
For an "Interactive" install, the installer would receive `/RUN`.

**Comment by iDolmatov** [comment]
Thank you. Insufficient description of the parameter and its name misled me. Thought it meant another installation mode. It turns out that this is a kind of "ForcedSwitch".

Please indicate which is always used:
https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1

https://github.com/microsoft/winget-cli/blob/master/schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json
`Custom switches will be passed directly to the installer by winget` _in any installation mode._

**Comment by denelon** [comment]
I'm working on another set of documents designed to explain all of the fields fully.  I'm also writing more thorough guidance on [authoring manifests](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#authoring-manifests). The current document is a stub so I can start doing some refactoring on other documents. More to come 😊

**Comment by spacewaffles309** [comment]
Really glad I found this discussion at this time, because I'm really interested in how this all works too.  I just started tinkering with chocolatey and I'm not entirely happy with how it behaves and the options available, so I'm looking forward to the extra info here and seeing if it's what I'm after.  I sure would like to be able to run a command and have a dozen packages update in the background, all going to customized locations and different drives.

**Comment by denelon** [comment]
@gmckeown we added support for "user" vs. "machine" install. Manifests can have both flavors. We still don't have an additive argument for passing arguments in addition rather than an override, so I'll keep this issue open.

**Comment by Trenly** [comment]
@denelon - See above linked PR

**Comment by denelon** [comment]
All, @Trenly implemented "--custom".

If you pass "--custom" and arguments, they will be added to the existing arguments provided by WinGet and the manifest.

*Note: if you use "--override", the "--custom" arguments are ignored.*
