### ISSUE TITLE
winget not working with command prompt (works with Powershell)

### ISSUE THREAD

**Issue by Table-09** [microsoft/winget-cli#2391]
### Brief description of your issue

I have been using winget on my desktop for a while, had done a semi-recent windows clean install and everything worked great for many months, until may or june when my winget randomly started showing this on command prompt

"'winget' is not recognized as an internal or external command,
operable program or batch file."

when I use Powershell it works instantly

### Steps to reproduce

No idea, I hardly ever install new programs and I came in one day and cmd refused to access winget so there was nothing new added to my computer at or near the same time that would have caused this, and it has persisted through in-place upgrades and installs as well as cumulative updates recently. 

### Expected behavior

the list of winget options (which appears in powershell with no issue)

### Actual behavior

CMD -> type WINGET  -> shows "unrecognized" 

ADMIN CMD -> type WINGET  -> still shows "unrecognized" 

### Environment

```shell
Latest version of Winget from Github, I have uninstalled and used the one from Microsoft store, it makes no difference.

Powershell works regardless both times.


I have tried clean installs and repair installs, etc... it's driving me crazy

I have seen the troubleshooting guides but I've tried it all, even the environment variables path i set correctly and it still wouldn't work in cmd
```

**Comment by denelon** [comment]
Do you get different results if you run `winget.exe`? I've seen a similar report elsewhere.

**Comment by table9gaming** [comment]
> Do you get different results if you run `winget.exe`? I've seen a similar report elsewhere.

no, I am getting errors still saying it's not recognized.

I opened up windows terminal and the only settings I changed were to "RUN AS ADMIN" and some of the appearance settings/transparency effects, and NOW powershell doesn't recognize winget at all!!!!

This is crazy, I just uninstalled Terminal and it's still not working????

what in gods name is happening?

**Comment by table9gaming** [comment]
I just downloaded the most recent winget version from github. 

NOW I am getting a windows semi-UAC pop-up which says "THIS APP CANNOT RUN ON YOUR PC"

**Comment by table9gaming** [comment]
i shut my computer down and ran an Ubuntu usb on my other computer with everything for winget working to another usb,  i was able to replace the winget.exe with the one i copied and now at least when i type "winget" it says there is something wrong and need to reinstall but Microsoft store says it's up to date. will try the version on github at some point

**Comment by ItzLevvie** [comment]
Have you taken a look at https://github.com/microsoft/winget-cli/discussions/2388#discussioncomment-3270559?

**Comment by table9gaming** [comment]
i tried that and it ended up making things worse.

I renamed the winget in system32 to wingetold.exe and .msix packages wouldn't install

i force installed it with powershell using "Add-AppxPackage -Path to .msix" and it's back to working in powershell but not cmd still

i have ruby and msys2 and python and wsl installed as well as discord, i read discord may interfere with it but i'm not entirely sure if that was resolved. If anything i feel like ruby or python might have done it but i doubt uninstalling them would make it work again

**Comment by Table-09** [comment]
(added to #2388) 

![image](https://user-images.githubusercontent.com/79593307/182406923-1e10affe-81f7-4a9d-a00f-13c6da0b9b22.png)
![image](https://user-images.githubusercontent.com/79593307/182406962-151bcba1-c93d-4dde-844d-1d8ce1f85a07.png)
![image](https://user-images.githubusercontent.com/79593307/182407321-c12b98af-4d24-4cec-bf52-7af8e6ba061b.png)
![image](https://user-images.githubusercontent.com/79593307/182407382-c86d47d5-dbb6-4aba-96c1-392cff4cad68.png)


Works in powershell but not cmd, this is driving me crazy. I even copied winget files from a brand new install after the powershell version stopped working, it allowed me (after not being recognized in either ps or cmd) to use it in PS after doing an in-place install, copying winget files from new computer and force-adding the app-pkg via powershell

**Comment by lechacon** [comment]
I don't know what the issue is, so here are a couple of ideas for diagnosing where the error is. Once we know what it was, we may be able to find a solution.

From cmd:
* If you do `echo %PATH%`, do you see `C:\Users\<username>\AppData\Local\Microsoft\WindowsApps` in there? If you don't, the issue may be that something is overwriting the `%PATH%`, preventing CMD from finding `winget.exe`.
* If you do `dir %LOCALAPPDATA%\Microsoft\WindowsApps`, do you see `winget.exe` there?
* What happens if you execute it with the full path, like `%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe`?

You said that you "copied the winget files from a brand new install". What do you mean by that? Did you manually edit the files under `C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_...`? If you did, that may cause many unexpected problems as the folder needs to have very specific permissions for the apps to work and you're not supposed to modify it.

You also said that you renamed a `winget` file under `System32`. That sounds very suspect to me as we don't create that file. Do you have any idea what that file is or what it contains? E.g., from looking at the file properties.

**Comment by Table-09** [comment]
> I don't know what the issue is, so here are a couple of ideas for diagnosing where the error is. Once we know what it was, we may be able to find a solution.
> 
> From cmd:
> * If you do `echo %PATH%`, do you see `C:\Users\<username>\AppData\Local\Microsoft\WindowsApps` in there? If you don't, the issue may be that something is overwriting the `%PATH%`, preventing CMD from finding `winget.exe`.
> * If you do `dir %LOCALAPPDATA%\Microsoft\WindowsApps`, do you see `winget.exe` there?
> * What happens if you execute it with the full path, like `%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe`?
> 
> You said that you "copied the winget files from a brand new install". What do you mean by that? Did you manually edit the files under `C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_...`? If you did, that may cause many unexpected problems as the folder needs to have very specific permissions for the apps to work and you're not supposed to modify it.
> 
> You also said that you renamed a `winget` file under `System32`. That sounds very suspect to me as we don't create that file. Do you have any idea what that file is or what it contains? E.g., from looking at the file properties.

-under %localappdata% the winget.exe is indeed there

-the winget.exe at /system32 i believe was just a symlink that windows created to the local data windows apps folder

- i tried copying winget.exe from a new install after doing a few things suggested in this thread/other thread resulted in powershell no longer working for winget. i tried the apt- install ps command but it wouldn't work/ refused to install/  said errors with permissions

 after copying the winget files that were not completely locked down, i booted into my original windows install and opened powershell, instead of saying "you don't have permission to access this app" in a uac style pop-up, or a variation of "this doesn't exist"  it said "you must reinstall or fix". i tried installing normal .msix pack - didn't work. 

i then ran apt install with ps and directed it to where i downloaded on the root of c and like magic powershell winget now works,  but cmd is not working. 

my secondary computer set up right next to it (which i had done the  install around the same time as my current computer) has both ps and cmd working with winget. 

cmd on that machine also defaults to system32 winget (it appears) but no issue. 



idk what could be causing it,  i know msys2 ruby and python all had environmental paths but i made sure the winget was (as mentioned in the aforementioned thread) added to that list and on top, but that didn't make a difference. i uninstalled msys2 python and ruby among a number of other programs (discord as well)  but the issue still persists for cmd only. 


i also had issues with IWS requests for dling files constantly failing, idk if it is related or if web 3.0 got rid of any website having direct downloads to the files (even right clicking copy link url doesn't work anymore - still redirects before actual download(

**Comment by lechacon** [comment]
Does `echo %PATH%` show the `WindowsApps` folder?

Does running winget with the full path `%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe` work?

**Comment by Table-09** [comment]
> Does `echo %PATH%` show the `WindowsApps` folder?
> 
> Does running winget with the full path `%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe` work?

i believe running the echo command does show the windows apps folders

thanks for the quick reply, i really should have left the Desktop on so i could rdp to it and get that answer to you. I'll be able to test it tomorrow morning

**Comment by Table-09** [comment]
> Does `echo %PATH%` show the `WindowsApps` folder?
> 
> Does running winget with the full path `%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe` work?

ok, running "%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe" gives me this...

![image](https://user-images.githubusercontent.com/79593307/182623837-71a2feeb-71de-494c-99e5-dace6e4c06fb.png)

**Comment by lechacon** [comment]
So winget is working correctly on cmd, but for some reason it's not finding it in the PATH. You can try `echo %PATH%` as a starting point to figure out why it isn't there. Maybe there's a typo or something is overwriting the PATH.

**Comment by Table-09** [comment]
![image](https://user-images.githubusercontent.com/79593307/182660371-5d176067-1859-4035-a8e2-fb3e0e426752.png)

does this provide any insight?

**Comment by Table-09** [comment]
`C:\WINDOWS\system32>echo %PATH%

C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Paragon Software\APFS for Windows\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\HP\Common\HPDestPlgIn\;C:\Program Files (x86)\Paragon Software\LinuxFS for Windows\;C:\Program Files\PuTTY";C:\ProgramData\chocolatey\bin;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Ruby31-x64\bin`

**Comment by lechacon** [comment]
> `C:\Program Files\PuTTY"`

I believe the unmatched quotes at the end of that one item are messing up the parsing for the rest of the PATH, so cmd does not see WindowsApps in the PATH. It could be that it works on PowerShell because its parsing of the PATH is smarter.

To confirm that it is this, you could see if the same thing (works on PS but not on cmd) happens for Chocolatey and Rub31, which are the other apps that have it's directory after the mismatched quotes in the PATH.

To fix it you would have to edit the PATH to remove the quotes after PuTTY, or figure out who is setting it and fixing it there.

**Comment by Table-09** [comment]
![image](https://user-images.githubusercontent.com/79593307/182674100-3a11ed54-cd67-44ab-8cb6-4da13880b56d.png)

I am looking all over the place and I don't see anything related to PuTTy on my system. I uninstalled it, would reinstalling it put the variable back in for me to edit? seems kind of strange its stuck there since i also uninstalled chocolatey and ruby

**Comment by ItzLevvie** [comment]
Have you checked if it's hidden somewhere here?

![image](https://user-images.githubusercontent.com/11600822/182676605-f90fc039-58a9-4a0d-aa05-241b6c172161.png)

since that semi-colon isn't meant to be there at the path

**Comment by lechacon** [comment]
I imagine that is not showing PuTTy for the same reason: the parsing is messed up by the quote, and that's why chocolatey has the semicolon @itzlevvie mentioned at the beginning.

I don't think reinstalling it will help. I would suggest manually modifying the environment variable to remove the quotes.

Seems like you can do it from PowerShell with

```PS
[Environment]::SetEnvironmentVariable( 'VARIABLE_NAME', 'VALUE', [EnvironmentVariableTarget]::Machine )
```

The name would be `PATH`, and the value would be what you currently have as PATH, without the PuTTy element.

**Comment by Table-09** [comment]
> 
I have tried 

`[Environment]::SetEnvironmentVariable(` PATH, C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Paragon Software\APFS for Windows\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\HP\Common\HPDestPlgIn\;C:\Program Files (x86)\Paragon Software\LinuxFS for Windows\;C:\ProgramData\chocolatey\bin;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Ruby31-x64\bin, [EnvironmentVariableTarget]::Machine `)`

and 

`[Environment]::SetEnvironmentVariable(` 'PATH', 'C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Paragon Software\APFS for Windows\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\HP\Common\HPDestPlgIn\;C:\Program Files (x86)\Paragon Software\LinuxFS for Windows\;C:\ProgramData\chocolatey\bin;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Ruby31-x64\bin' [EnvironmentVariableTarget]::Machine )``

both just spit out a bunch of "unexpected" / missing arguments etc..

**Comment by lechacon** [comment]
It needs to have the quotes.

It doesn't look obviously wrong to me. I'd need to see the actual error message to know what is wrong.

**Comment by Table-09** [comment]
> It needs to have the quotes.
> 
> It doesn't look obviously wrong to me. I'd need to see the actual error message to know what is wrong.

Oh my.

so idk how i didn't realize it, but when I put in that last command I was in Windows Terminal Powershell (Admin) not Powershell (admin)

Not sure how much of a difference it makes since i could have sworn they were configured to run the same way in the settings (as admin at the same directories)

the Terminal I guess couldn't parse the entire command and thought it was multiple things, not sure why when It was pasted from the same clipboard, lol.

Winget is NOW WORKING on CMD!!!

Thank you!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
this was driving me crazy

so I'm guessing PUTTY at some point (when it was updated or something) got bad instructions and added that extra character, which obliterated the capabilities of anything in the PATH list after it :P 

That is something I'll need to keep an eye out for from now on. I could have sworn i installed PUTTY through either NINITE or WINGET, am I right in thinking it was a bad update distribution that caused this syntax error?

I'm definitely bookmarking this and saving all these commands for later use or if anyone else comes across this problem ! :)

**Comment by Table-09** [comment]
Thank you everyone for your help!  <3

I'll try reinstalling putty at some point when i feel brave enough and see if it causes the same issue, lol

**Comment by denelon** [comment]
I've observed most MSIX based installers do a great job cleaning up things like environment variables, and mixed results with MSI and .exe-based installers. I've been talking with others about building tools to help diagnose these kinds of issues. It's a different initiative, but I think it would be a next logical step to help publishers diagnose and troubleshoot issues, and essentially give more confidence that software can work and play well with the Windows Package Manager.

**Comment by Masamune3210** [comment]
a PATH validator would be very useful if nothing else, since I have found quite a few installers over the years that will just positively mangle the PATH variable
