### ISSUE TITLE
Improve version parsing to better support "preambles"

### ISSUE THREAD

**Issue by JohnMcPMS** [microsoft/winget-cli#2394]
### Description of the new feature / enhancement

The version parsing could be improved to ignore leading, non-numeric values that are then followed by a more normal version number.  This would apply to versions like `v1.2.3`, as well as the package detailed in microsoft/winget-pkgs#67794

For example `ad 7.0.13` would equal `7.0.13` and `v1.2.3` would equal `1.2.3`.
`foo1` would equal `bar1`, but `1.foo2` would not equal `1.bar2`, as only leading non-numeric characters would be ignored.

### Proposed technical implementation details

For the first version part (where parts are split by the `.` character), determine if there is a number at the end (currently only decimal integers are supported) and use it as the integer portion.  Do not use the "preamble" in the version at all.

**Comment by Trenly** [comment]
Related to #1298

**Comment by luzpaz** [comment]
What's the tipping point for this issue to be solved ?

**Comment by Pandoriaantje** [comment]
> What's the tipping point for this issue to be solved ?

There seems to be no mechanism to handle beta/release candidate, etc. version numbering, which leaves the users at the hands of however winget interprets the version number. This could lead to false 'upgrades'.

**Comment by denelon** [comment]
That's correct, we still have a big chunk of work left in order to handle channels.
* #147

**Comment by Trenly** [comment]
Resolved by #4558
