### ISSUE TITLE
[Package Issue]: Microsoft.VC++2013Redist-x86 and x64 could not install 

### ISSUE THREAD

**Issue by Mannshoch** [microsoft/winget-cli#2398]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Download not work

Winget:
```
InternetOpenUrl() failed
0x80072efd : unknown error
```

### Steps to reproduce

winget install Microsoft.VC++2013Redist-x86
winget install Microsoft.VC++2013Redist-x64

### Actual behavior

```
InternetOpenUrl() failed
0x80072efd : unknown error
```

### Expected behavior

Sucessful installation

### Environment

```shell
Windows Package Manager v1.2.11601
Windows: Windows.Desktop v10.0.19044.1826
Package: Microsoft.DesktopAppInstaller v1.17.11601.0
```

### Screenshots and Logs

Log file is empty.

**Comment by Mannshoch** [comment]
No the Website do not open.

**Comment by denelon** [comment]
It's likely blocked then. That's the direct download link.

**Comment by Mannshoch** [comment]
This Morning I tested it again. Now it's working. Both winget and Downloading manually.

I am relived. I need it.

**Comment by Mannshoch** [comment]
Happens again. The download site seems a bit unstable. 
Downloading from
Https://www.microsoft.com/en-us/download/details.aspx?id=40784
Works, but again not from the pages shown by winget show ...

I detected the problem again accidentially becaus i retested an internal FAQ I currently write.

**Comment by Mannshoch** [comment]
Now also Microsoft.VC++2015-2022Redist-x64 and 86
Have the same problem.

**Comment by Mannshoch** [comment]
I digged into networking behavoir. (Not my strongest).

It seems that this is a Provider specific Problem.
If I try to connect the Domain download.visualstudio.microsoft.com my computer get a Timout. I supose its not a DNS Problem but with the IP-Address. That I could not reach from our Provider.

Access with Smartphone tethering over another provider was Possible.
