### ISSUE TITLE
winget upgrade -i --all install apps NOT in interactive mode

### ISSUE THREAD

**Issue by Actuallymax** [microsoft/winget-cli#2428]
### Brief description of your issue

winget upgrade -i --all install apps NOT in interactive mode

### Steps to reproduce

winget upgrade -i --all

### Expected behavior

upgrade all apps  in interactive mode

### Actual behavior

install apps NOT in interactive mode

### Environment

```shell
Windows 程序包管理器 v1.2.11601
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22622.450
程序包: Microsoft.DesktopAppInstaller v1.17.11601.0
```

**Comment by Trenly** [comment]
Duplicate of #2008
