### ISSUE TITLE
Winget doesn't work when run from elevated cmd

### ISSUE THREAD

**Issue by koniu80** [microsoft/winget-cli#2443]
### Brief description of your issue

Winget works fine from non-elevated cmd. From elevated cmd it gives "Failed when searching source; results will not be included: winget" error on almost every command 

### Expected behavior
Expected to be able to use winget on elevated prompt without the need to enter admin password to install software 

### Actual behavior
If I run exactly same command on elevated and non-elevated prompts I get different behaviours

![image](https://user-images.githubusercontent.com/28823472/184086304-6d5a5e75-f0f9-4ae1-8e30-91c5efa0be44.png)

![image](https://user-images.githubusercontent.com/28823472/184086514-cae16a24-ac6d-4ea0-ba01-1099f026e3f9.png)

Source update doesn't make any difference

![image](https://user-images.githubusercontent.com/28823472/184100540-0b60761d-1155-4719-adf8-1647e8f6dcfa.png)

### Comment

I think I have read though all the solutions I could find, most of them point to the issue with PATH, but in my case I can run the software, but it doesn't work as expected. Please advise.

**Comment by denelon** [comment]
Which version of winget is this?

The output from `winget --info` helps to troubleshoot.

Does winget run in administrator mode from "C:\Users\Administrator>"?

Try running `winget source reset --force` in the administrator prompt.

**Comment by koniu80** [comment]
Hi,

See below. No change 

![image](https://user-images.githubusercontent.com/28823472/184304811-32968d19-a007-446e-bda3-85febb043c19.png)

**Comment by mark-eagles** [comment]
Getting same issue from Administrator command prompt on Win 10:

![image](https://user-images.githubusercontent.com/115399556/197223757-1124d046-4d9d-4162-b19e-f64204bb8fea.png)

**Comment by mark-eagles** [comment]
The following fixed this issue for me (running from admin powershell), I installed the Microsoft.Winget.Source app with the following:

Invoke-WebRequest 'https://cdn.winget.microsoft.com/cache/source.msix' -OutFile 'c:\downloads\Microsoft.Winget.Source.msix' -UseBasicParsing

Push-Location 'c:\downloads';
Add-AppxPackage -Path 'Microsoft.Winget.Source.msix';
Pop-Location;

**Comment by Bognar** [comment]
I am having the same issue; I can run as local user but not as admin from cmd and PowerShell.
The invoke command from above did not help in my case.

**Comment by xillibit** [comment]
> I am having the same issue; I can run as local user but not as admin from cmd and PowerShell.
> The invoke command from above did not help in my case.

For me it's fixed in 1.5.101-preview
