### ISSUE TITLE
Add Powershell Module for Winget Similar like WingetTools

### ISSUE THREAD

**Issue by srinivasan-mk** [microsoft/winget-cli#2450]
### Description of the new feature / enhancement

I am using windows 11 and Winget installed by Default, I wanted to use Winget output through Powershell for logging and automation. It would be really useful when we have a PowerShell module for Winget to automate installation and uninstallation.

I found below git repo has Powershell module for Winget for your reference.

[Winget Tools](https://github.com/jdhitsolutions/WingetTools)

**Comment by jedieaston** [comment]
Duplicate of https://github.com/microsoft/winget-cli/issues/221

**Comment by denelon** [comment]
Duplicate of #221
