### ISSUE TITLE
Increase Package Identifier Segmentation Limit

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#2460]
### Description of the new feature / enhancement

In the 1.2 and 1.4 schema, Packages are limited to three "Extensions" or "Segments" after the primary segment. This means that `Publisher.One.Two.Three` is a valid package identifier, but `Publisher.One.Two.Three.Four` is not. 
https://github.com/microsoft/winget-cli/blob/c46f651326df41d745816688ff98e072be20eb2d/schemas/JSON/manifests/v1.2.0/manifest.version.1.2.0.json#L9
To allow for better organization of manifests in the community repository, catalog health, and for users to more easily find a specific package, the segment limit should be increased

microsoft/winget-pkgs#70722 is a good example of when additional segments are useful, especially as packages which install side-by-side may have multiple release channels.

I propose the most common identifier scheme is `Publisher.Package.MajorVersion.MinorVersion.MajorChannel.MinorChannel`, where fields that are not present are omitted. To accommodate this, the limit should be increased to 5 or 6, or removed entirely

### Proposed technical implementation details

Change the `{1,3}$` to `{1,6}$` or even `{1,}$`

**Comment by denelon** [comment]
I know we've started seeing more examples of things being broken out. I like binary numbers, and sometimes a few more positions might be useful. I don't want to go with "open ended", but I would be willing to consider `{1,8}$`.

**Comment by Trenly** [comment]
8 seems reasonable

**Comment by denelon** [comment]
My thinking is it would add "PatchVersion", and "PatchChannel", or another useful subcategory for "Package" or "Product" subcategories.

**Comment by denelon** [comment]
I'm sure not many people want to type `winget install publisher.package.1.2.3.4.5.6` but it's not as bad with automation.

**Comment by Trenly** [comment]
> I'm sure not many people want to type `winget install publisher.package.1.2.3.4.5.6` but it's not as bad with automation.

I would argue that . is easier than -
