### ISSUE TITLE
winget search without any query or option results in a 'No packages found' error

### ISSUE THREAD

**Issue by ChristianVerhoeven** [microsoft/winget-cli#2468]
### Brief description of your issue

According to the Microsoft documentation https://docs.microsoft.com/en-us/windows/package-manager/winget/search#show-all using winget search without any query or options should result in all available manifests from winget. But when using winget search results in a error stating there are no packages found.

Can we have the ability back to return all packages from a source instead of needing to filter.

### Steps to reproduce

Using winget search

### Expected behavior

Returning all available packages from a source

### Actual behavior

Returns an error no packages found

### Environment

```shell
Windows: Windows.Desktop v10.0.22000.856
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0
```

**Comment by ChristianVerhoeven** [comment]
After doing some digging we found a PR where this 'feature' should not be implemented to restrict search to require a filter
https://github.com/microsoft/winget-cli/pull/2125

**Comment by ItzLevvie** [comment]
You can workaround this by running in Command Prompt or Windows PowerShell:
```
winget search --name "" --source winget
```

**Comment by ChristianVerhoeven** [comment]
> You can workaround this by running the command below in Command Prompt or Windows PowerShell:
> 
> ```
> winget search --name "" --source winget
> ```

This doesn't work, still getting No package found matching input criteria. as return
`
PS C:\Users\ChristianVerhoeven> winget search --name "" --source winget
No package found matching input criteria.
PS C:\Users\ChristianVerhoeven>
`

**Comment by ItzLevvie** [comment]
``winget search --name `"`" --source winget`` in Windows PowerShell version 5:
![image](https://user-images.githubusercontent.com/11600822/186156522-136ea7f6-0d0a-4c01-8e2e-93e62e65b0f9.png)

`winget search --name "" --source winget` in Windows PowerShell version 7 (and in Command Prompt):
![image](https://user-images.githubusercontent.com/11600822/186156322-e9a61323-364b-44ed-8494-b2193abeb95a.png)
![image](https://user-images.githubusercontent.com/11600822/186156417-6a0764df-46ff-4c3c-8808-0e8bf8d85197.png)

**Comment by ChristianVerhoeven** [comment]
> `` winget search --name `"`" --source winget `` on Windows PowerShell version **5**: ![image](https://user-images.githubusercontent.com/11600822/186156522-136ea7f6-0d0a-4c01-8e2e-93e62e65b0f9.png)
> 
> `winget search --name "" --source winget` on Windows PowerShell version **7** and on Command Prompt: ![image](https://user-images.githubusercontent.com/11600822/186156322-e9a61323-364b-44ed-8494-b2193abeb95a.png) ![image](https://user-images.githubusercontent.com/11600822/186156417-6a0764df-46ff-4c3c-8808-0e8bf8d85197.png)

Here you are escaping your ", when I do that I can use the workaround. Thanks for the tip!

**Comment by denelon** [comment]
The change to the default search was intentional. The same is true for other commands expecting a query argument. We may look at another argument to support a full query in the future. This way the REST source implementors can determine if they want to expose a full search argument.

**Comment by ChristianVerhoeven** [comment]
> The change to the default search was intentional. The same is true for other commands expecting a query argument. We may look at another argument to support a full query in the future. This way the REST source implementors can determine if they want to expose a full search argument.

Why is this issue closed? The fact remains that the official documentation page doens't reflect your statement and still explains to use winget search without a query or option to get a full list.

The documentation should be updated to reflect changes made 4 months ago so other people don't have to spend half a day on Google to find out why they are getting error's while the official documentation says it should work.

**Comment by denelon** [comment]
@ChristianVerhoeven it was a miss when we updated the documentation at Microsoft Docs. I'm working with the team to get this updated. 

Issue:
* #2470
