### ISSUE TITLE
If an application does not support the location parameter and its passed or the path provided is invalid user should be prompted

### ISSUE THREAD

**Issue by SemnoSao** [microsoft/winget-cli#2469]
### Description of the new feature / enhancement

The location parameter indicates the path a user wants to download an app to, if it's not possible to use that parameter or its invalid formatted one should be prompted if it's okay to install to a default path. The unprompted default is not optimal as the reason to why one would want that could be many and packages don't inform their support of location beforehand.

**Comment by xIUPITERx** [comment]
This feature would be quite important when downloading multiple apps (e.g. via a batch file or script), if a few of the apps refuse to be installed at the designated place it gets messy very quickly.

**Comment by Trenly** [comment]
It can already be specified if an application is known to not support the location parameter - 
https://github.com/microsoft/winget-cli/blob/73f05cdf9b72eed991ccc5609f459f385cb9ec2f/schemas/JSON/manifests/v1.4.0/manifest.installer.1.4.0.json#L456-L467

The other problem is that sometimes the installers do support the location parameter but the switch just isn't known. Changing the default behavior to prompt if the package isn't known for certain to support the location parameter would be breaking
