### ISSUE TITLE
Access Denied when installing an app

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/winget-cli#247]
# Brief description of your issue
When validating installs, periodically the installer fails with access denied.
for example PR  https://github.com/microsoft/winget-pkgs/pull/396

and

Capture file list
query registry
run install
Found Netbeans 11.3 (x64) [Apache.Netbeans]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://downloads.apache.org/netbeans/netbeans/11.3/Apache-NetBeans-11.3-bin-windows-x64.exe
  ██████████████████████████████   193 MB /  193 MB
Successfully verified installer hash
An unexpected error occurred while executing the command:
rename: Access is denied.: "C:\Users\kevin\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet\Apache.Netbeans.11.3", "C:\Users\kevin\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet\Apache.Netbeans.11.3.exe"
failed to install
winget install -m netbeans.txt

# Steps to reproduce

try to install PR 396 manually.  same with netbeans

# Expected behavior

# Actual behavior

Fails to install and aborts

# Environment
C:\temp>winget --info
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18363.719
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

Links:
  Privacy Statement: https://aka.ms/winget-privacy
  License agreement: https://aka.ms/winget-license
  3rd Party Notices: https://aka.ms/winget-3rdPartyNotice
  Homepage:          https://aka.ms/winget

**Comment by LukasNespor** [comment]
The **Access denied** error occurs even when running the installer manually from the folder
```
C:\Users\{UserName}\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet
```

**Comment by KevinLaMS** [comment]
Duplicate of #
Looks to be a duplicate reactivate if you disagree.

**Comment by wirosl** [comment]
Was having this problem with GIMP and Visual Studio Code.
Found a workaround by right clicking CMD / Powershell and selecting "Run as Administrator", and then installing via winget, after which both installed without problems.

**Comment by cderv** [comment]
Hi @KevinLaMS , 

Of which issue this is a duplicate ? There is no number in your previous command. 
I also get Access Denied windows with some app (like Git or new one I work on https://github.com/microsoft/winget-pkgs/pull/1304)

**Comment by superusercode** [comment]
Any update on the issue that replaced this one?

**Comment by megamorf** [comment]
I believe @KevinLaMS meant to reference issue #189.

**Comment by AmitKKhanchandani** [comment]
@megamorf correct

**Comment by yao-msft** [comment]
Sorry, I'll use #189 for tracking
