### ISSUE TITLE
Documentation for Winget search is not correct

### ISSUE THREAD

**Issue by ChristianVerhoeven** [microsoft/winget-cli#2470]
### Brief description of your issue

The documentation page on Winget search states that for a full list of available packages you need to use Winget search without any query or options provided. It turns out the development team decided to change that 4 months ago (with a PR on 26 of April) https://github.com/microsoft/winget-cli/pull/2125 and not update the documentation page.

The documentation should be updated to reflect changes made 4 months ago so other people don't have to spend half a day on Google to find out why they are getting error's while the official documentation says it should work.

**Comment by denelon** [comment]
I apologize for missing it. It was a subtle change, and I can see how frustrating it was to try and figure out why it wasn't working. The only reference I found was https://docs.microsoft.com/windows/package-manager/winget/search#show-all. Please let me know if you find others.

**Comment by ChristianVerhoeven** [comment]
Besides some non-Microsoft blog posts I haven't found any other Microsoft documentation besides the one I mentioned.

**Comment by denelon** [comment]
The documentation has been updated at https://docs.microsoft.com/windows/package-manager/winget/search
