### ISSUE TITLE
Idea on how handling of multiple versions of one Packet could be handled.

### ISSUE THREAD

**Issue by SR-Lut3t1um** [microsoft/winget-cli#250]
# Allow a version change with a single command.
As a software developer myself, I often feel the need of having multiple versions of a package installed. E.g. JDK's Python Node.js etc. most of the time those versions are allowed to coexist on a OS Installation yet the Path settings always need to decide for one version. For me personally this is something frustrating as you cannot just change the current JDK without resetting you JAVA_HOME systemvariable. I feel like it would add a lot to a packetmanager if I could simply select the version of a packet to be used in the current directory. 

An example implementation would look somewhat like this:

```
java --version ->
__________________
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode) 
```

```
winget ls java ->
_________________
openjdk 11.0.1 // Current
graalvm 20.0.0
```

```
winget set java graalvm --verbose --local
___________________________________________
working only in current directory
removed java directory from path
removed JAVA_HOME systemvariable
added graalvm directory to path
set JAVA_HOME to (path of graal)
```

```
java --version ->
_________________
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)
```

```
 cd .. && java --version ->
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
``` 

Thank's for reading and have a nice day ;)

**Comment by denelon** [comment]
@SR-Lut3t1um I'm not sure an elegant solution to the problem exists. 
 I contacted one of our Java experts, and he referenced this article: https://medium.com/@brunoborges/manage-multiple-jdks-on-mac-os-linux-and-windows-wsl2-3a73467b685c

**Comment by brunoborges** [comment]
I'm not convinced it should be the package manager's job to switch JDKs (or any other tool FWIW). 

I do hope that we get something like [direnv](https://direnv.net/) for Windows one day, though.

**Comment by SR-Lut3t1um** [comment]
> @SR-Lut3t1um I'm not sure an elegant solution to the problem exists.
> I contacted one of our Java experts, and he referenced this article: https://medium.com/@brunoborges/manage-multiple-jdks-on-mac-os-linux-and-windows-wsl2-3a73467b685c

The problem with these solutions however is that it's always one tool per language. So you need virtualenv for Python, SDKman for Java, etc... and at the end of the day I do think that the root of the problem is managing Packages thus the right tool to solve 
this issue is the PacketManager of a system.
Also I don't know any PacketManager in Linux that is able to solve this issue adequately, making Windows the first OS that's able to solve this Issue.

**Comment by denelon** [comment]
I'm doing some backlog cleanup. I don't think we're going to have WinGet manage other applications like this issue suggests. It seems each language/SDK/program has their own way of handling this, and adding WinGet to the mix would do more harm than good.
