### ISSUE TITLE
Can't install python or filezilla via winget

### ISSUE THREAD

**Issue by briantho** [microsoft/winget-cli#2513]
### Brief description of your issue

Hi, I've been installing packages all day on a new machine all via winget. 2 of the packages I can't install are filezilla and python3. I've tried both powershell, and cmd, both return this error afterwards

No package found matching input criteria

### Steps to reproduce

running

winget install -e --id Python.Python.3

or 

winget install -e --id TimKosse.FileZilla.Client

from a command prompt or via powershell results in this error
No package found matching input criteria

### Expected behavior

I expect the package to be installed

### Actual behavior

says the package can't be found

### Environment

```shell
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.918
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0

running on windows 11 pro
```

**Comment by ItzLevvie** [comment]
`Python.Python.3` can be installed via `winget install --id Python.Python.3.10`

`TimKosse.FileZilla.Client` was removed per developer's request.

**Comment by briantho** [comment]
> `Python.Python.3` can be installed via `winget install --id Python.Python.3.10`
> 
> `TimKosse.FileZilla.Client` was removed as per the application developer's request.

wow, thanks. changing from Python.Python.3 to Python.Python.3.10 seemed to work. 
should probably be changed at [winget.run](https://winget.run/pkg/Python/Python.3) website, so more people don't have the same problem

**Comment by vedantmgoyal2009** [comment]
https://winget.run/ is no longer updated. Use https://winstall.app/ which updates in almost real-time.

**Comment by briantho** [comment]
> https://winget.run/ is no longer updated. Use https://winstall.app/ which updates in almost real-time.

Thanks, I didn't realize that winget.run isn't updated anymore. Going to close this issue, as my issue is solved
