### ISSUE TITLE
Feature Request: Print command added to path for portable installs

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#2516]
> I've just installed Process Explorer
> 
> `winget install Microsoft.Sysinternals.ProcessExplorer`
> 
> but can't find out how to start it :) Start menu show me nothing on "Process Explorer" or "procexp" search requests

_Originally posted by @energister in https://github.com/microsoft/winget-cli/issues/377#issuecomment-1235685206_

I propose that when a portable package is installed, the alias used for calling the program be printed to the command output
```
PS C:\Windows\system32> winget install microsoft.sysinternals.processexplorer
Found Process Explorer [Microsoft.Sysinternals.ProcessExplorer] Version 16.43
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://live.sysinternals.com/procexp.exe
  ██████████████████████████████  2.70 MB / 2.70 MB
Successfully verified installer hash
Starting package install...
Path environment variable modified; restart your shell to use the new value.
Command line alias: 'process-explorer'
Successfully installed

**Comment by Trenly** [comment]
@denelon - I may be able to do this one; Any issues you foresee with the proposed implementation?

**Comment by denelon** [comment]
@ryfu-msft take a look :)
