### ISSUE TITLE
Passing arguments to dependencies

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#2521]
### Description of the new feature / enhancement

In some cases, I need to pass arguments to dependencies.

If I install package A and it depends on package B (and package B needs an argument {either the same as A or different}) then I'd like to be able to specify those arguments in such a way that they can pass through.

`winget install foo --override some-important-switch`
  `foo depends on bar`
  `installing bar` <-- The argument "some-important-switch" is passed through
  `installing foo` <-- clearly this gets the "some-important-switch" argument

Note: the ask also should take into consideration the ability to "augment" arguments rather than just to override, I don't want to lose my scope or my silent switches.  This is something like "--augment" rather than "--override" where the additional switches are in addition to those already being handled by the Windows Package Manager.

**Comment by Trenly** [comment]
[Policy] Area-Input
