### ISSUE TITLE
[Zip] Nested Installer Files Validation

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#2523]
* Non-Portable Installer Type doesn't warn when `PortableCommandAlias` is included for a NestedInstallerFile

> Note: The below items are likely not implemented yet, as Portable support hasn't been implemented for Zip files yet. I'm placing them here as a consideration to ensure they are validated against

* Portable Installer Type doesn't throw an error when two entries have the same `RelativeFilePath`
  *  This might be acceptable as long as they have different command aliases?
* Portable Installer Type doesn't throw an error when two entries have the same `PortableCommandAlias`

**Comment by denelon** [comment]
@ryfu-msft please take a look at this.

**Comment by ryfu-msft** [comment]
Thanks for catching this, additional validation will be added in #2500

**Comment by sitiom** [comment]
> * This might be acceptable as long as they have different command aliases?

Seems like this isn't implemented: https://github.com/microsoft/winget-pkgs/pull/94699#issuecomment-1404896681

**Comment by denelon** [comment]
This version isn't in the validation pipelines yet. We're waiting for the 1.4 client rollout to the majority of users. We want to avoid as much confusion as possible with the "winget" source having .zip-based packages they can't install with earlier versions of winget.

**Comment by sitiom** [comment]
What I mean is that `winget validate` fails locally and that an exception should be made for the same `RelativeFilePath` but different `PortableCommandAlias`.

**Comment by denelon** [comment]
@sitiom can you create a new issue with an example?

**Comment by sitiom** [comment]
https://github.com/microsoft/winget-cli/issues/2884
