### ISSUE TITLE
Unable to install Microsoft Authenticator

### ISSUE THREAD

**Issue by jahvari** [microsoft/winget-cli#2526]
I have been trying to install Microsoft Authenticator via winget and I am unable to do so. 

#1: I first attempted to install via the name, and this is the output I got. 

C:\Windows\system32>winget install microsoft authenticator
Windows Package Manager (Preview) v1.4.2161-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Found a positional argument when none was expected : 'authenticator'

Installs the selected package, either found by searching a configured source or directly from a manifest. By default, the query must case-insensitively match the id, name, or moniker of the package. Other fields can be used by passing their appropriate option.

usage: winget install [[-q] <query>] [<options>]

The following command aliases are available:
  add

The following arguments are available:
  -q,--query                   The query used to search for a package

The following options are available:
  -m,--manifest                The path to the manifest of the package
  --id                         Filter results by id
  --name                       Filter results by name
  --moniker                    Filter results by moniker
  -v,--version                 Use the specified version; default is the latest version
  -s,--source                  Find package using the specified source
  --scope                      Select install scope (user or machine)
  -a,--architecture            Select the architecture to install
  -e,--exact                   Find package using exact match
  -i,--interactive             Request interactive installation; user input may be needed
  -h,--silent                  Request silent installation
  --locale                     Locale to use (BCP47 format)
  -o,--log                     Log location (if supported)
  --override                   Override arguments to be passed on to the installer
  -l,--location                Location to install to (if supported)
  --force                      Override the installer hash check
  --dependency-source          Find package dependencies using the specified source
  --accept-package-agreements  Accept all license agreements for packages
  --header                     Optional Windows-Package-Manager REST source HTTP header
  --accept-source-agreements   Accept all source agreements during source operations
  -r,--rename                  The value to rename the executable file (portable)

More help can be found at: https://aka.ms/winget-command-install

#2 I then tried to install it via its ID from the Microsoft Store page, (https://www.microsoft.com/en-us/p/microsoft-authenticator/9nblgggzmcj6?activetab=pivot:overviewtab)

I ran was "winget install 9nblgggzmcj6"

Found Microsoft Authenticator [9NBLGGGZMCJ6] Version Unknown
This package is provided through Microsoft Store. winget may need to acquire the package from Microsoft Store on behalf of the current user.
Version: Unknown
Publisher: Microsoft Corporation
Publisher Support Url: mailto:wp_azureauthapp@microsoft.com
Description:
  Introducing the updated Microsoft Authenticator! One app to quickly and securely verify your identity online, for all of your accounts.

  This app provides an extra layer of protection when you sign in, often referred to as two-step verification or multi-factor authentication. If you’ve enabled this for your Microsoft accounts, you’ll get a notification from this app after trying to sign in. Just tap approve and you’re good to go. For any other account, or if you’re offline, our built-in security code generator has got you covered.

  New features and updated app design are only available if you have completed the Windows 10 Anniversary update. Without the update, you will receive an older version of the app which only supports two-step verification for work and school accounts.

  This new app replaces the Azure Authenticator, and Multi-Factor Authentication apps.
License: ms-windows-store://pdp/?ProductId=9NBLGGGZMCJ6
Privacy Url: https://go.microsoft.com/fwlink/p/?LinkId=723405
Agreements:
Category: Business
Pricing: Free
Free Trial: No
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
Seizure Warning: https://aka.ms/microsoft-store-seizure-warning
Store License Terms: https://aka.ms/microsoft-store-license

The publisher requires that you view the above information and accept the agreements before installing.
Do you agree to the terms?
[Y] Yes  [N] No: y
An unexpected error occurred while executing the command:
0x803fb104 : unknown error

This was ran from CMD as administrator.

**Comment by Trenly** [comment]
I see the same behavior when using the store ID. Here is the [full log](https://pastebin.com/8PTe3Mxi) from my sandbox to help the engineers diagnose the issue

```
2022-09-17 20:05:02.497 [CLI ] Package agreements accepted by CLI flag
2022-09-17 20:05:02.507 [FAIL] WindowsPackageManager.dll!00007FFBE0D5CF28: LogHr(1) tid(141c) 803FB104 
2022-09-17 20:05:02.508 [CLI ] Caught winrt::hresult_error: 0x803fb104 : unknown error
```

**Comment by JohnMcPMS** [comment]
Attempt 1 is due to spaces; `winget install "microsoft authenticator"` should solve that.

The error you are seeing is (I believe) due to the package not being available in your market on the Store.  If you can install it manually using the Store application, then it should be available and work from `winget`.  But `winget` does not enable bypassing the publisher's restrictions.

**Comment by jahvari** [comment]
@JohnMcPMS 

I tried winget install "microsoft authenticator" like you said and this is what it returned. Not sure what market restriction I would have as I am located in the US. I guess when I search the microsoft store app from windows 10, I am unable to find it.

winget install "microsoft authenticator"
No package found matching input criteria.

**Comment by BUGProtectionAssociation** [comment]
Microsoft Authenticator is a phone app only now.
You could install it on android or ios. Windowsphone has been forgot.
All right. winget not support install app to phone or wsa. And never support windowsphone for long long future！
