### ISSUE TITLE
Test in Windows Sandbox

### ISSUE THREAD

**Issue by felipecrs** [microsoft/winget-cli#253]
# Description

A new CLI option, such as the command `winget sandbox-test <manifest>`, or `winget install --sandbox-test <manifest>`, for testing packages install in Windows Sandbox.

# Proposed technical implementation details

It should create a new Sandbox, and try to perform the `winget install -m <manifest>` there.

Sandboxes can be customized and set to run a PowerShell Script or commands on its startup through an XML configuration file `.wsb`. 

See: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file

This way we would have fully isolated test environments for each time, very practical, fast, and lightweight (different than a VirtualBox machine and Vagrant).

**Comment by felipecassiors** [comment]
Making progress... 
![otYuUDYBQi](https://user-images.githubusercontent.com/29582865/82527918-fd9c9900-9b0d-11ea-8c98-e86fb146a6d6.gif)

**Comment by felipecassiors** [comment]
I'm creating a new PowerShell script and pushing as a tool in the https://github.com/microsoft/winget-pkgs repository. For further details check https://github.com/microsoft/winget-pkgs/pull/827.

> A GIF is worth a thousand words.
> 
> ![Q7LdAo2R31](https://user-images.githubusercontent.com/29582865/82714447-f76d0080-9c64-11ea-8e66-09b1d239ac7b.gif)
