### ISSUE TITLE
Winget installing outdated packages

### ISSUE THREAD

**Issue by github-account1111** [microsoft/winget-cli#2538]
### Brief description of your issue

Winget installs old versions of some packages.
It also fails to show the new versions when running `winget upgrade`.

For example, Signal 5.9.0 has been available for 18 days now:
https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OpenWhisperSystems/Signal
yet winget keeps insisting that 5.8.0 is the latest version.

This is happening on a clean Windows 10 install and has happened on two different laptops now.

### Steps to reproduce

Run `winget install --id 'OpenWhisperSystems.Signal' --accept-package-agreements --accept-source-agreements`.

### Expected behavior

Signal 5.9.0 is installed.

### Actual behavior

Signal 5.8.0 is installed.
No upgrades are shown when running `winget upgrade`

### Environment

```shell
Windows Package Manager (Preview) v1.4.2161-preview
Windows: Windows.Desktop v10.0.19044.2006
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2161.0
```

**Comment by ItzLevvie** [comment]
Would you be able to paste whatever is shown in `winget show OpenWhisperSystems.Signal`?

This is what I see which is currently the latest version of Signal:
```
Found Signal [OpenWhisperSystems.Signal]
Version: 5.58.0
Publisher: Signal Messenger, LLC
Publisher Url: https://www.signal.org
Publisher Support Url: https://github.com/signalapp/Signal-Desktop/issues
Author: Open Whisper Systems
Moniker: signal
Description: Signal is an encrypted communications application. It uses the Internet to send one-to-one and group messages, which can include files, voice notes, images and videos, and make one-to-one voice and video calls.
Homepage: https://www.signal.org
License: GPLv3
License Url: https://www.gnu.org/licenses/gpl-3.0.en.html
Privacy Url: https://www.signal.org/legal/#privacy-policy
Copyright: Copyright (c) Open Whisper Systems
Copyright Url: https://www.signal.org/legal/#terms-of-service
Tags:
  chat
  cross-platform
  encryption
  foss
  messaging
  open-source
  privacy
  security
  texting
Installer:
  Installer Type: nullsoft
  Installer Url: https://updates.signal.org/desktop/signal-desktop-win-5.58.0.exe
  Installer SHA256: 53b3a7ae351823753cbe409f9e56586eb903e296ed5cb8d35c55d82e4e71fecc
```

Just an FYI: GitHub Web's algorithm works a bit weirdly so the bottom one won't always be the latest version of a particular package.

**Comment by github-account1111** [comment]
I'm sorry you're right I misread the page I linked above (I literally took 5.58.0 for 5.8.0, maybe I'm dyslexic lol).
The latest version is indeed 5.60.
It just hasn't been added to the manifests.

**Comment by mdanish-kh** [comment]
> I'm sorry you're right I misread the page I linked above (I literally took 5.58.0 for 5.8.0, maybe I'm dyslexic lol). The latest version is indeed 5.60. It just hasn't been added to the manifests.

Added in https://github.com/microsoft/winget-pkgs/pull/80343
