### ISSUE TITLE
[Azure Data Studio] User installer can only be downloaded as admin

### ISSUE THREAD

**Issue by yualan** [microsoft/winget-cli#255]
This bug tracker is monitored by Windows Package Manager development team and other technical folks.

**Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**.
Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

If this is an application crash, please also provide a Feedback Hub submission link so we can find your diagnostic data on the backend. Use the category "Apps > Windows Package Manager" and choose "Share My Feedback" after submission to get the link.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible.

-->

# Brief description of your issue
When downloading Azure Data Studio from winget, I have to run Command Prompt in Administrator mode. However, the installation method is User Installer, so it should work even without admin mode.
# Steps to reproduce

1. Open command prompt 
2. Run winget install azure data studio
3. When new dialog opens, attempt to install.

# Expected behavior

It should install without issue.

# Actual behavior

Access denied message

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop v10.0.18362.836
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

**Comment by KevinLaMS** [comment]
Duplicate of #152
