### ISSUE TITLE
update source failed

### ISSUE THREAD

**Issue by Rainsheep** [microsoft/winget-cli#2552]
### Brief description of your issue

winget upgrade
尝试更新源时失败： winget

### Steps to reproduce

winget upgrade or winget install
尝试更新源时失败： winget

### Expected behavior

success

### Actual behavior

尝试更新源时失败： winget

### Environment

```shell
Windows 程序包管理器 v1.3.2091
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22000.978
系统体系结构: X64
程序包: Microsoft.DesktopAppInstaller v1.18.2091.0

日志: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by denelon** [comment]
Can you try `winget source reset --force` in administrator mode?

**Comment by Rainsheep** [comment]
@denelon 
I tried `winget source reset --force`, it success.
but when I run `winget upgrade`.  it prompts `尝试更新源时失败： winget`

**Comment by denelon** [comment]
That is most likely a network issue attempting to download the "winget" source package with the local cache of the package manifest pointers.

**Comment by thimo-seitz** [comment]
In my temporary directory `%USERPROFILE%\AppData\Local\Temp\WinGet` there were files that could not be overwritten. After emptying the directory, the problem was solved.

**Comment by radiorz** [comment]
. #1808

**Comment by radiorz** [comment]
#1808

**Comment by radiorz** [comment]
#1808

**Comment by yanggggjie** [comment]
I encounter  the same issue, and I turn my proxy to global pattern, it works.

**Comment by Dragon1573** [comment]
I switch my proxy to "Global" mode, but it still failed to update the index ...

The latest version of `voidtools.Everything.Lite` is currently `1.4.1.2022`, which is PRed by me.

<details>
<summary>Screenshots below</summary>

![image](https://user-images.githubusercontent.com/49941141/200111222-d796b094-50f6-423e-877e-993ee2d6f2bc.png)

![image](https://user-images.githubusercontent.com/49941141/200111230-d8371bea-a6ad-4bcc-aae3-e967df84bd2f.png)

![image](https://user-images.githubusercontent.com/49941141/200111249-b11f1ae1-0773-43ea-a784-785a9ddc4357.png)

</details>

**Comment by radiorz** [comment]
> I switch my proxy to "Global" mode, but it still failed to update the index ...
> 
> The latest version of `voidtools.Everything.Lite` is currently `1.4.1.2022`, which is PRed by me.
> 
> Screenshots below

Set your proxy to USA and global mode, an try again. 
It works for me.

**Comment by Dragon1573** [comment]
> @radiorz:
>
> Set proxy to `USA` and `Global Mode` and try again.

Thank you, I also works for me. ヽ(￣▽￣)ﾉ

Maybe I enabled some special "Mode" of CFA, so it infected the `winget.exe`. Now everything works fine as follows.

![image](https://user-images.githubusercontent.com/49941141/200316247-1924e21e-cda8-4981-a077-963a2f226766.png)

![image](https://user-images.githubusercontent.com/49941141/200316323-eeeecc9b-0d78-412e-9e08-1dc88708e823.png)
