### ISSUE TITLE
Install for All Users. (if possible)

### ISSUE THREAD

**Issue by somedeveloper00** [microsoft/winget-cli#2554]
### Description of the new feature / enhancement

Currently I was trying to install python3 with winget, and it was very upsetting that I couldn't just install it in "C:\Program FIles" folder. So I had to go the old ways and google "Python" and install the launcher"... It'd be so good if we could use winget to install for all users!

### Proposed technical implementation details

winget install python --scope=all
winget install pyton -sudo
winget install pyton -u:all

**Comment by Trenly** [comment]
This is possible using `--scope=machine`, but only if the application supports it and the switches that need to be passed to the installer are contained in the manifest.  In the case of Python 3.10, the manifest does support the machine scope

https://github.com/microsoft/winget-pkgs/blob/5aa3c6d062b7d0288b8ed8c8c8b59d6729f0d712/manifests/p/Python/Python/3/10/3.10.7/Python.Python.3.10.installer.yaml#L35-L49

**Comment by somedeveloper00** [comment]
> This is possible using `--scope=machine`, but only if the application supports it and the switches that need to be passed to the installer are contained in the manifest. In the case of Python 3.10, the manifest does support the machine scope
> 
> https://github.com/microsoft/winget-pkgs/blob/5aa3c6d062b7d0288b8ed8c8c8b59d6729f0d712/manifests/p/Python/Python/3/10/3.10.7/Python.Python.3.10.installer.yaml#L35-L49

oh, my bad then. I couldn't find the `scope` within the `--help` page, so I never knew it existed. thanks. I'm closing this issue/request with this
