### ISSUE TITLE
[Package Issue]: Microsoft.VC++2015-2022Redist.x64

### ISSUE THREAD

**Issue by lychichem** [microsoft/winget-cli#2567]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

No applicable update found.

### Brief description of your issue

Winget fails to list package id for Microsoft.VC++2015-2022Redist-x64
![image](https://user-images.githubusercontent.com/9316590/193375499-1ba05546-ac79-4532-bbfd-26dc7cf76f3c.png)

### Steps to reproduce

1. `winget install Microsoft.VCRedist.2015+.x64`
2. `winget list`

### Actual behavior

winget list Microsoft Visual C++ 2015-2022 Redistribut… as {ac8ae441-cfc2-41f2-bbca-7b6668740f8d}

### Expected behavior

winget should list Microsoft.VCRedist.2015+.x64 as Microsoft.VCRedist.2015+.x64

### Environment

```shell
Windows 程序包管理器(预览) v1.4.2161-preview
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22623.730
系统体系结构: X64
程序包: Microsoft.DesktopAppInstaller v1.19.2161.0

日志: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by ppvnf** [comment]
Good job! 2015-2022 x64 has been fixed for me:
![Captura de tela 2022-10-02 142737](https://user-images.githubusercontent.com/73800734/193467621-ec819236-ec7d-40fe-ba23-d521f30f3071.png)
2010 x64/x86 are the only ones left.

**Comment by lychichem** [comment]
Checked again and confirmed it was fixed.

**Comment by albertosantini** [comment]
Thanks for your efforts.
It is also ok for me.

```
$ winget list "visual c++"
Name                                                               Id                           Version       Source
---------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.40664       Microsoft.VCRedist.2013.x64  12.0.40664.0  winget
Microsoft Visual C++ 2015-2022 Redistributable (x86) - 14.34.31823 Microsoft.VCRedist.2015+.x86 14.34.31823.3 winget
Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.40664       Microsoft.VCRedist.2013.x86  12.0.40664.0  winget
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.34.31823 Microsoft.VCRedist.2015+.x64 14.34.31823.3 winget
```
