### ISSUE TITLE
the name winget is not cool.

### ISSUE THREAD

**Issue by HUMORCE** [microsoft/winget-cli#257]
# the name **winget** is not cool.

I understand i can set aliase for that.

if we can't find an interesting name like pacman, don't make it too long.

just keep it regular,
wpm, pm, pkg, wpkg is good.

**Comment by KevinLaMS** [comment]
Ouch.  :(

**Comment by ilmax** [comment]
On the other side I like it very much

**Comment by vexx32** [comment]
It's already been used before, too, though I don't know how widespread [win-get](http://win-get.sourceforge.net/)'s usage was.

**Comment by vexx32** [comment]
It's already been used before, too, though I don't know how widespread [win-get](http://win-get.sourceforge.net/)'s usage was.

**Comment by HUMORCE** [comment]
but when typing _winget install what_, just like this:
`wget get github.com`

**Comment by loganintech** [comment]
As someone flips between using Ubuntu and Windows on a daily basis, having `winget` and `apt-get` be similar is A-ok with me.

**Comment by denelon** [comment]
We did quite a bit of name shopping and approval process stuff before we got where we are.  I still have a collection of .bat files with a couple of lines to hide output and pass parameters in :)

**Comment by jsxnis** [comment]
Take it or leave it

**Comment by HUMORCE** [comment]
> As someone flips between using Ubuntu and Windows on a daily basis, having `winget` and `apt-get` be similar is A-ok with me.

why not APT.

> We did quite a bit of name shopping and approval process stuff before we got where we are. I still have a collection of .bat files with a couple of lines to hide output and pass parameters in :)



> Take it or leave it

make another interface for winget is also okay.
i am thinking about that.

**Comment by h404bi** [comment]
> don't make it too long.

no code is the best code, and no name is the best name. YEAH!
