### ISSUE TITLE
[solved] Python 2.7.8 will be installed again and again (wrong buildnumber (18150) in repository)

### ISSUE THREAD

**Issue by Daniel-from-Germany** [microsoft/winget-cli#2575]
### solving
remove all python installations and only install python via winget
check your installations: winget list python
e.g.: winget uninstall "Python 2.7.8"
install python2: winget install python.python.2

### Brief description of your issue

C:\Windows\System32>winget upgrade --all -h
Name         ID              Version  Verfügbar Quelle
------------------------------------------------------
Python 2.7.8 Python.Python.2 2.7.8150 2.7.18150 winget
1 Aktualisierungen verfügbar.
2 Pakete haben Versionsnummern, die nicht bestimmt werden können. Wenn Sie „--include-unknown“ verwenden, werden möglicherweise weitere Ergebnisse angezeigt.

(1/1) Gefunden Python 2 [Python.Python.2] Version 2.7.18150
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Downloading https://www.python.org/ftp/python/2.7.18/python-2.7.18.amd64.msi
  █▌                              1024 KB / 19.6 MB

### Steps to reproduce

winget install Python.Python.2
winget source update
winget upgrade --all -h

### Expected behavior

Python 2.7.8 will be installed again and again

### Actual behavior

Python 2.7.8 will be installed again and again

### Environment

```shell
C:\Users\user>winget --info
Windows-Paket-Manager v1.3.2091
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22621.521
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.18.2091.0

Protokolle: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
Can you post the output of `winget list python`

**Comment by Daniel-from-Germany** [comment]
Name                               ID                              Version     Verfügbar   Quelle
-------------------------------------------------------------------------------------------------
Python 2.7.18 (64-bit)             Python.Python.2                 2.7.18150               winget
PyCharm Community Edition 2021.2.2 JetBrains.PyCharm.Community.EAP 212.5284.44 223.4884.74 winget
ElevenClock                        SomePythonThings.ElevenClock    3.8.2                   winget
Python 2.7.8                       Python.Python.2                 2.7.8150    2.7.18150   winget
Python 2.7.18                      Python.Python.2                 2.7.18150               winget

**Comment by Trenly** [comment]
It looks like you have multiple versions of python installed, which is causing the repeated upgrade. Because you have Python 2.7.8 installed, the upgrade command doesn't recognize that you also have 2.7.18 installed, and thinks that the upgrade is available.

Removing Python 2.7.8 should mitigate the issue

**Comment by Daniel-from-Germany** [comment]
Okay, thanks, i have remove all pythons and install it with:
winget install python.python.2, thanks, that solved the problem

**Comment by denelon** [comment]
We're working on some improvements to the "install" flow. We are going to perform a check to see if the package is installed already and if it looks like the latest package is an upgrade, we will switch to the upgrade flow. This should help with those annoying loops. They are generally caused by older versions being present and detecting there is an upgrade available to the older version without checking if the latest version is already installed.
