### ISSUE TITLE
Package Manager Install Detection

### ISSUE THREAD

**Issue by Smorgan05** [microsoft/winget-cli#259]
About a year or two ago I checked in with MS on creation of a Windows Package Manager.  In that time I've been piecing together my own implementation because the packagemanagement code did not have the features I wanted and the code is difficult to expand on.  The other problem is the coverage gaps in terms of the various installers used on windows (msi, steam, innosoft) just to name a few.  I wanted to see what the plans going forward were such as whether Microsoft is committing to a rewrite of how Install checking occurs.  I understand that this is early in development but I am interested to see where this goes.

I have a drop in replacement for checking program installs on windows and I may be interested in helping.  My email is on my github page.

**Comment by Smorgan05** [comment]
Please close out comment.

**Comment by denelon** [comment]
@Smorgan05 you might want to watch #120 and #121.

**Comment by Smorgan05** [comment]
@denelon I already have the code to do these things.  Based on how WinGet came about from AppGet.   I just don't have much interest in working with Microsoft.  I feel more comfortable pursuing my own project.
