### ISSUE TITLE
Increase Protocols Limit

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#2600]
### Description of the new feature / enhancement

Some packages support more than 16 protocols. For example - https://curl.se/

The limitation on the number of nodes causes incomplete metadata

### Proposed technical implementation details

Increase to max 64

**Comment by denelon** [comment]
@ryfu-msft is this a fit for 1.4?

**Comment by ryfu-msft** [comment]
> @ryfu-msft is this a fit for 1.4?

Changes have been made and will be included in 1.4.
