### ISSUE TITLE
Why did you automatically delete old versions of packages?

### ISSUE THREAD

**Issue by simkoG** [microsoft/winget-cli#2602]
### Brief description of your issue

I cannot use `winget` to install older versions of `Mailbird.Mailbird`. Why did you make a package manager if you don't allow the users to install any avaiable versions? 

https://github.com/microsoft/winget-pkgs/commit/479ff745fedb4bf5d47e02a71cb734105679fae4

### Steps to reproduce

The current version of Mailbird.Mailbird is `2.9.68` as of today. 

1) `winget install --id Mailbird.Mailbird --version 2.9.67` (2.9.67 is the previous version). 
2) See errors. 

### Expected behavior

Install `2.9.67` version without any error.

### Actual behavior

```
No version found matching: 2.9.67
```

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.674
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Masamune3210** [comment]
One possible cause is that the installers are no longer being offered by the application's site or place of distribution

**Comment by ItzLevvie** [comment]
This is something you'll have to talk to the publisher.

`Mailbird.Mailbird` currently only has a Download URL that **_always_** points to the latest version which prevents historical versions from being in the repository.

**Comment by simkoG** [comment]
Dear @ItzLevvie, that's good to know. I am going to point this out to the developers.
