### ISSUE TITLE
Sort Results of "List" Command

### ISSUE THREAD

**Issue by helmanfrow** [microsoft/winget-cli#2608]
### Description of the new feature / enhancement

It would be nice if I could specify the sort order for the output of the _winget list_ command.
Usually I want to see the results displayed in alphabetic order so I can quickly scan the list and find what I'm looking for.

### Proposed technical implementation details

Something like _winget list --sort a desc_ would be great.

**Comment by Trenly** [comment]
Duplicate of #1769

**Comment by Trenly** [comment]
See also #1352
