### ISSUE TITLE
No need for Windows 10 Insider build?

### ISSUE THREAD

**Issue by dakom** [microsoft/winget-cli#262]
I do not think I have a windows insider build. Specifically, if I follow [the instructions to enable it](https://insider.windows.com/en-us/getting-started/#install) - I get to a screen that says:

> Diagnostic data must be set to Full to get preview builds

Yet, I am able to upgrade the App Installer package and execute `winget`. I am _registered_ on the Insider Program, though I'm not sure if that matters.

Is this a mistake in the documentation here? i.e. it's not really necessary to install a Windows Insider build?

**Comment by martinmine** [comment]
You don't need to be on an insider build to it. Only requirement is that you're on 1709 or newer (see "Which versions of Windows will be supported?" here: https://devblogs.microsoft.com/commandline/windows-package-manager-preview/) I'm on 1909 and installed `winget` through the release page here on GitHub and it works just fine.

**Comment by dakom** [comment]
So in the [README.md](https://github.com/microsoft/winget-cli/blob/master/README.md#microsoft-store-recommended) should

> Install a Windows 10 Insider build

Be changed to:

> Install Windows 10 version 1709 or newer

?

**Comment by martinmine** [comment]
The Readme [clearly states](https://github.com/microsoft/winget-cli/blob/master/README.md#installing-the-client) you need to must have 1709 or higher. The section you linked requires an insider build and is only required when you install it through the store (you can get it through Store, on the release page, or building it yourself), as the title in the section you linked specifies.

**Comment by dakom** [comment]
I do not have the Insider Build afaik and I was able to install it through the store...?

**Comment by martinmine** [comment]
When youre not on an insider build of W10, the one you installed on the store will not have Winget. You can install it here: https://github.com/microsoft/winget-cli/releases/tag/v0.1.4331-preview

**Comment by dakom** [comment]
Am I using an insider build without being aware of it?

![image](https://user-images.githubusercontent.com/6406986/82578600-4186b100-9b95-11ea-906c-924e247f49b5.png)

With this build, I was able to install winget through the store - not github releases

**Comment by kilasuit** [comment]
@dakom you are on the September 2019 release - hence 1909 and this requires at least the September 2017 release of Windows 10 & not one of the insider builds

**Comment by dakom** [comment]
Hence, this is wrong, no?

> In order to get automatic updates from the Microsoft Store that contain the client, one must do one of the following:
> * Install a Windows 10 Insider build

**Comment by martinmine** [comment]
It says _one of the following_ where the other option is "Join the Preview flight ring by signing up", which you say you are on the initial post on this thread.

**Comment by dakom** [comment]
d'oh, you're right! 

The language of "one must do one of the following:" is a bit odd though... this is a bit nitpicky, but I do think there's room for improvement. Maybe something like:

----
In order to get automatic updates from the Microsoft Store that contain the client, one must either:

* Install a [Windows 10 Insider](https://insider.windows.com/) build
or
* Join the Preview flight ring by [signing up](http://aka.ms/winget-InsiderProgram)

**Comment by kilasuit** [comment]
I think the language there is clear enough, just needs thorough reading and not speed reading (which I know trips me up a fair bit)

**Comment by o-alquimista** [comment]
I'm not _running_ an insider build, but I am _subscribed_ to Windows Insider Program, and that's how I got winget automatically installed. That's the part that needs clarification.

Join Windows Insider Program + meet minimum version requirement. 2 requirements.
