### ISSUE TITLE
Automated updates

### ISSUE THREAD

**Issue by ChristianGalla** [microsoft/winget-cli#263]
# Description of the new feature/enhancement

As a user I always want to use the newest version of a program I installed. As addition to #120 I want the new versions to be installed automatically.

Currently there are some programs that have no update mechanism, some are prompting for updates and some are installing updates automatically for example via a custom service.

If programs are not updated, new useful features cannot be used. Also, there may be bugs that were already fixed and security vulnerabilities.

If software developers do not have to implement their own update mechanism, they can focus on the main functionality of their programs. Also, users do not have to do updates manually.

# Proposed technical implementation details

The easiest implementation I can think of is a scheduled task or service to automatically call winget's update method (#120).

Ideally, this should be handled by Windows Update like updates for drivers or Microsoft Office. This way updates can be installed when no program instance is running.

# Open topics

Maybe there should be a flag to disable automated updates for some programs if someone wants to stick to a specific version?

There can be some breaking changes between program versions. Maybe there should be no automated updates between major versions? Unfortunately, not all programs are using [semantic versioning](https://semver.org/), so this may be difficult to implement. Also, there may be no (security) updates for an old major version anymore, which leaves a vulnerable system.

If programs already have an updater included, winget's updater or the included updater has to be disabled. I think the yaml file should have a new parameter to disable winget's updater and / or a setup parameter to disable the installation of a build in update service.

**Comment by doctordns** [comment]
The desire to be running the latest version is good. IT Pros, however, need to manage that process. Configuration management means having control over what updates and when they get applied. 
Winget appears to be aimed at the individual developed, rather than IT Pros, but more control would be good for IT Professionals.

**Comment by kramfs** [comment]
> The desire to be running the latest version is good. IT Pros, however, need to manage that process. Configuration management means having control over what updates and when they get applied.
> Winget appears to be aimed at the individual developed, rather than IT Pros, but more control would be good for IT Professionals.

I guess this is an evolving topic especially at this early stage but I'd imagine the scenario you posted can be controlled using the repository a.k.a `source` where only approved apps are available

**Comment by doctordns** [comment]
Unfortunately, that does not help. Winget.exe is Linux like and not easily automatable. If you are doing configuration management in any sort of larger organisation, you want to be able to script. A tool with such limited scripting ability is not a great one.

**Comment by slaet** [comment]
and please add also the possibility to update all Application that are installed trough winget. That all Applications has the latest version, that we can add a Scheduled Task for example running once a Week to update all Applications. This would be a benefit for security related aspects of Buggy Applications.

**Comment by denelon** [comment]
Duplicate of #212
