### ISSUE TITLE
winget doesn't install Visual C++

### ISSUE THREAD

**Issue by pleabargain** [microsoft/winget-cli#2632]
### Brief description of your issue

winget upgrade -all fails to install new C++

### Steps to reproduce

winget upgrade -all 
run
test: 
winget upgrade 
NEW C++ package is not installed

### Expected behavior

flawless updates

### Actual behavior

update fails
![winget_fail](https://user-images.githubusercontent.com/640846/197453994-baabdb5a-249c-45b8-886b-c7b4cc225d3d.png)

### Environment

```shell
win 10
```

**Comment by pleabargain** [comment]
yes:
![image](https://user-images.githubusercontent.com/640846/199707541-531828dd-89f0-429e-8254-2b3635c78eef.png)


I just updated windows. C++ not updating
![image](https://user-images.githubusercontent.com/640846/199707380-9c5ffb9d-6b1a-481a-85e7-d9ec4cd465f8.png)

**Comment by stephengillie** [comment]
This is the same as in #84721, where a workaround of installing the x86 version allowed the x64 version to upgrade.

**Comment by pleabargain** [comment]
Working for me now.
