### ISSUE TITLE
winget search gives outdated package version

### ISSUE THREAD

**Issue by Shengyis** [microsoft/winget-cli#2633]
### Brief description of your issue

winget search xxx 
gives the outdated result. For example, I can manually check the newest version of  "Fndroid.ClashForWindows" on https://github.com/microsoft/winget-pkgs is 0.20.6, 
![Screenshot 2022-10-24 144616](https://user-images.githubusercontent.com/72622897/197464053-23ebed8b-04f5-4338-8a61-eec6354edb2d.png)
however my search result only returns version 0.20.4
![Screenshot 2022-10-24 144437](https://user-images.githubusercontent.com/72622897/197463821-6215b6f5-22d3-46a7-81aa-f86a219fb7b2.png)
I guess the database does not update ? My winget source is https://cdn.winget.microsoft.com/cache, already tried
winget source reset --force
also tried to change source to https://winget.azureedge.net/cache but gives the same issue.

### Steps to reproduce

winget search "clash for windows"

### Expected behavior

return version 0.20.7

### Actual behavior

return outdated version 0.20.4

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.754
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
https://github.com/microsoft/winget-pkgs/issues/86160

**Comment by Shengyis** [comment]
See https://github.com/microsoft/winget-pkgs/issues/86160
And now I can see updates
I close the issue.
