### ISSUE TITLE
package not found

### ISSUE THREAD

**Issue by lmielke** [microsoft/winget-cli#2649]
### Brief description of your issue

On running winget import myfile.json I am getting a 
package not found for import: Microsoft.VC++2013 Redist-x64 winget
Error. This interrupts the entire install, so nothing gets installed.

### Steps to reproduce

{
    "$schema" : "https://aka.ms/winget-packages.schema.2.0.json",
    "CreationDate" : "2022-04-20T10:21:17.220-00:00",
    "Sources" : 
    [
        {
            "Packages" : 
            [
                {
                    "PackageIdentifier" : "Google.Chrome"
                },
                {
                    "PackageIdentifier" : "DominikReichl.KeePass"
                },
                {
                    "PackageIdentifier" : "Microsoft.WingetCreate"
                },
                {
                    "PackageIdentifier" : "Microsoft.VisualStudio.2019.Community"
                },
                // {
                //     "PackageIdentifier" : "Microsoft.VC++2013Redist-x64"
                // },
                {
                    "PackageIdentifier" : "Microsoft.OneDrive"
                },
                {
                    "PackageIdentifier" : "Google.Drive"
                },
                {
                    "PackageIdentifier" : "Microsoft.WindowsPCHealthCheck"
                },
                {
                    "PackageIdentifier" : "Microsoft.PowerShell"
                },
                // {
                //     "PackageIdentifier" : "Microsoft.VC++2013Redist-x86"
                // },
                {
                    "PackageIdentifier" : "Microsoft.WindowsTerminal"
                }
            ],
            "SourceDetails" : 
            {
                "Argument" : "https://winget.azureedge.net/cache",
                "Identifier" : "Microsoft.Winget.Source_8wekyb3d8bbwe",
                "Name" : "winget",
                "Type" : "Microsoft.PreIndexed.Package"
            }
        }
    ],
    "WinGetVersion" : "1.2.10271"
}

### Expected behavior

Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.40664       Microsoft.VCRedist.2013.x64                           12.0.40664.0                     winget

### Actual behavior

package not found for import: Microsoft.VC++2013 Redist-x64 winget

### Environment

```shell
Windows Package Manager v1.3.2691
Windows: Windows.Desktop v10.0.19044.2130
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0
```

**Comment by Trenly** [comment]
This is because the package identifier has changed. Updating your import file to reference `Microsoft.VCRedist.2013.x64` or `Microsoft.VCRedist.2013.x86` should resolve the issue

**Comment by robertstrom** [comment]
I have an issue with an application not being found. I can do a search and it is found but it errors when I run `winget upgrade --all`

```
(21/22) Found CherryTree [Giuspen.Cherrytree] Version 0.99.49.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.giuspen.com/software/cherrytree_0.99.49.0_win64_setup.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).
```

Thanks

**Comment by denelon** [comment]
> This is because the package identifier has changed. Updating your import file to reference `Microsoft.VCRedist.2013.x64` or `Microsoft.VCRedist.2013.x86` should resolve the issue

Closing this issue since it's based on a renamed package problem.

@robertstrom, I clicked on the link displayed in the manifest after running `winget show Giuspen.Cherrytree` and I got a 404 error. It appears the publisher either moved or removed that installer.
