### ISSUE TITLE
Unable to Remove Application from List After It Was Manually Uninstalled/Removed

### ISSUE THREAD

**Issue by B4RN154N** [microsoft/winget-cli#2651]
### Brief description of your issue

I had two versions of Blender installed on my machine, now it seems that they are both gone. Whenever I update with winget I get an error as it's failing to remove them. 

Here's the issue:

```
PS C:\WINDOWS\system32> winget list Blender
Name    Id                        Version Available Source
----------------------------------------------------------
Blender BlenderFoundation.Blender 2.79.2  3.3.1     winget
Blender BlenderFoundation.Blender 2.82.1  3.3.1     winget
PS C:\WINDOWS\system32> winget uninstall Blender
Multiple installed packages found matching input criteria. Please refine the input.
Name    Id
---------------------------------
Blender BlenderFoundation.Blender
Blender BlenderFoundation.Blender
PS C:\WINDOWS\system32> winget uninstall -e --name Blender --id BlenderFoundation.Blender --version 2.79.2
No installed package found matching input criteria.
PS C:\WINDOWS\system32> winget uninstall -e --name Blender --id BlenderFoundation.Blender --version 2.82.1
No installed package found matching input criteria.
PS C:\WINDOWS\system32>
```

I've inherited this computer from previous colleges, so it might have been uninstalled improperly. 

### Suspected repro steps:
Install the two specific versions of Blender (*2.79.2, 2.82.1*) and then delete them via file explorer or through *"Add or remove programs"* system menu. 

### Expected behavior

When the user tries to uninstall software that was uninstalled outside of winget, winget removes those packages from its list of entries since those apps cannot be found and should not be updated/uninstalled.

### Actual behavior

When calling uninstall on a package that cannot be found/doesn't exist, winget doesn't remove it from the list, so it will try and fail to remove that package every time.

### Environment

```shell
Windows Package Manager v1.3.2691
Windows: Windows.Desktop v10.0.19044.2130
Package: Microsoft.DesktopAppInstaller v1.18.2691.0
```

**Comment by Trenly** [comment]
Uninstall by version doesn't work currently. See https://github.com/microsoft/winget-cli/issues/1886

If you use `appwiz.cpl` (The Add & Remove Programs Menu) to uninstall the application, it should remove the entry from winget.

Also related to -
* https://github.com/microsoft/winget-cli/issues/1886
* https://github.com/microsoft/winget-cli/issues/2476
* https://github.com/microsoft/winget-cli/issues/1619

**Comment by BarnabasMakkay** [comment]
Unfortunately, Blender does not appear on that list.

**Comment by Trenly** [comment]
> Unfortunately, Blender does not appear on that list.

In that case it is an issue with Blender not removing it's entries from the registry when the uninstaller is run. You may need to use a tool such as Revo Uninstaller to remove the errant registry entries

**Comment by B4RN154N** [comment]
Yeah, you were right. Revo Uninstaller found the leftovers and removed it. All working now 👍🏻 
Cheers!
