### ISSUE TITLE
Cant add winget source

### ISSUE THREAD

**Issue by Nollknolle** [microsoft/winget-cli#2669]
### Brief description of your issue

when i would like to add the winget source again i get the following error.

```ps
winget source add --name winget https://winget.azureedge.net/cache
```

```
Quelle wird hinzugefügt:
  winget -> https://winget.azureedge.net/cache
Unerwarteter Fehler beim Ausführen des Befehls:
0x8051100f : unknown error
```

Source List:
```
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
```

### Steps to reproduce

winget source add --name winget https://winget.azureedge.net/cache

### Expected behavior

adds the source

### Actual behavior

get the above error

### Environment

```shell
Windows: Windows.Desktop v10.0.22000.318
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.18.2691.0
```

**Comment by codewater30** [comment]
Same issue here

**Comment by codewater30** [comment]
Oh, I found out that if i run `winget source reset --force`, the  https://cdn.winget.microsoft.com/cache source gets back

**Comment by SwamiVT** [comment]
Had the same issue, ran `winget source reset --force` to get the source back but still have the current issue

```
winget upgrade
Failed in attempting to update the source: winget
Failed when searching source; results will not be included: winget
No installed package found matching input criteria
```

**Comment by yujinlin0224** [comment]
Same error here
![圖片](https://user-images.githubusercontent.com/11353779/200119303-f40624de-2790-4edc-98b1-bb22243dcae1.png)

**Comment by jrm523** [comment]
> Had the same issue, ran `winget source reset --force` to get the source back but still have the current issue
> 
> ```
> winget upgrade
> Failed in attempting to update the source: winget
> Failed when searching source; results will not be included: winget
> No installed package found matching input criteria
> ```

I have the same issue and believe there is a larger issue going on.. https://github.com/microsoft/winget-cli/issues/1656

**Comment by jo20201** [comment]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>ResourceNotFound</Code>
<Message>The specified resource does not exist. RequestId:3851d20e-e01e-0071-7c2a-f1db5e000000 Time:2022-11-05T15:24:03.5192764Z</Message>
</Error>

**Comment by prodrigues1912** [comment]
I'm also having the same problem. Apparently Winget CDN is down: https://cdn.winget.microsoft.com/cache.

**Comment by chriskuipers** [comment]
Was troubleshooting `winget` source not working for over an hour, just to discover that the Winget CDN does appear to be down... Well, at least I now know it's not me :-)

**Comment by YDX-2147483647** [comment]
According to #2666 , the CDN might be down in some countries.

**Comment by David-Noble-at-work** [comment]
In my case: this is because winget doesn’t like multiple users to be using it. Imagine that apt or end (formerly my) only worked for one user. That’s where winget is at.

**Comment by ParallaxCoder** [comment]
i had same issue. (i still have) winget cdn having issue. it return 0KB source file (https://cdn.winget.microsoft.com/cache/source.msix) 

i managed to download valid source.msix using a VPN with Canada location. now it works without VPN but 0KB source is still a thing without VPN.

it shows `Failed in attempting to update the source: winget`

![image](https://user-images.githubusercontent.com/70336922/200351229-d8a01e93-ea2b-44f2-8dc8-9beb73e26dcb.png)

**Comment by denelon** [comment]
@Nollknolle have you been able to resolve this with `winget source reset --force` in administrator mode?

**Comment by IronManStank** [comment]
Same issue here! I had tried to resolve this with winget source reset --force in administrator mode but still showed the same issue. It seems the Winget CDN is down: https://cdn.winget.microsoft.com/cache.

**Comment by denelon** [comment]
@IronManStank I don't think the CDN is down, but we have been playing whack a mole with random endpoints. We've had an open investigation with our provider for weeks, and we're hopefully down to the isolated individual endpoints. We're also bringing in additional third-party monitoring to help find issues sooner.

I've seen a few people with work arounds by specifying known good endpoints in their hosts file. It's been pretty painful to isolate and fully resolve. Apologies for all the frustration this is causing.

**Comment by denelon** [comment]
https://cdn.winget.microsoft.com/cache/source.msix is the package that gets installed to update the local database of packages.
