### ISSUE TITLE
Windows Store link in repo README is broken

### ISSUE THREAD

**Issue by axelfontaine** [microsoft/winget-cli#2672]
### Brief description of your issue

It results in a 404. One has to manually search for winget in the store itself, however it is not immediately obvious that App Installer and winget are the same thing. The description in the store should also make that clearer.

**Comment by iDolmatov** [comment]
I don't see any problems. The title is clearly written.

> Microsoft Store [Recommended]
> The client is distributed within the [App Installer](https://www.microsoft.com/p/app-installer/9nblggh4nns1) package.

**Comment by Masamune3210** [comment]
The msixbundle is also named Microsoft. DesktopAppInstaller

**Comment by axelfontaine** [comment]
It must have been a temporary hiccup yesterday. It is now working for me as well. Sorry for the noise on the issue tracker. Closing.
