### ISSUE TITLE
winget source update canceled 

### ISSUE THREAD

**Issue by wlxxd** [microsoft/winget-cli#2678]
### Brief description of your issue

Using "winget source update" returns canceled.
Using "winget list" returns a list + "Error trying to update source: winget"

![Bild_2022-11-07_184949792](https://user-images.githubusercontent.com/72802595/200379789-f320afae-975d-4864-8fa7-894a64b36c99.png)
![Bild_2022-11-07_185132370](https://user-images.githubusercontent.com/72802595/200380170-9545e2e6-b907-498d-8865-5473885680db.png)
(German pictures)

### Steps to reproduce

Launch Command Prompt with elevated privileges.
Enter "winget source update" or "winget list"

### Expected behavior

Winget updates its source.

### Actual behavior

No source update of winget.

### Environment

```shell
Windows-Paket-Manager v1.3.2691
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22621.755
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.18.2691.0

Protokolle: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by iDolmatov** [comment]
Duplicate #2666

**Comment by eggheadedmonkey** [comment]
Try restarting the "Delivery Optimization" service.
Read more here: https://github.com/microsoft/winget-cli/issues/2666#issuecomment-1306412311

**Comment by denelon** [comment]
@wlxxd can you check again?

**Comment by wlxxd** [comment]
> @wlxxd can you check again?

Error fixed with commands from https://github.com/microsoft/winget-cli/issues/2666#issuecomment-1303448425 .

```
> winget source reset --force
> winget source list
```
