### ISSUE TITLE
Please create an offline installation file. Suggestions

### ISSUE THREAD

**Issue by oklokl** [microsoft/winget-cli#2693]
### Description of the new feature / enhancement
General User Download User version Regarding offline installation. This is a suggestion.
[End User Download Tool.]

https://www.microsoft.com/store/productId/9NBLGGH4NNS1
https://apps.microsoft.com/store/detail/%EC%95%B1-%EC%84%A4%EC%B9%98-%EA%B4%80%EB%A6%AC%EC%9E%90/9NBLGGH4NNS1?hl=ko-kr&gl=kr
<img width="325" alt="1" src="https://user-images.githubusercontent.com/1571600/201445532-3e6aacbf-e44c-496a-8a2f-05908b71ff25.png">
![2022-11-12](https://user-images.githubusercontent.com/1571600/201446642-0862880d-2a2e-431b-8f05-087caa16b3da.png)

https://learn.microsoft.com/ko-kr/sysinternals/downloads/process-utilities
ex> 

https://learn.microsoft.com/ko-kr/sysinternals/downloads/process-utilities/winget_general_user.zip  (The way I want to deliver the new additional downloads) 

I want to download ms app installer as offline file.
here. Or I would like to download it from github.
What I'm saying.
Not the upload user. public. Download is what the user is talking about.
It's a user file for ordinary people like me.
I want to download the download executable program exe offline.
MS Store is notorious for being very insecure around the world.
Most of them have problems with downloads. therefore
It is also available for download on the MS Store.
I wish I could get the offline exe installation file as well.

Here again I say. It's not the upload user.
I'm talking about files for users like me, download users.

`winget install wingetcreate` X This command is not what you want. <-This is for professionals. That is, for developers.

for example.
my example command
`curl.exe --output "winget_general_user.exe" --url "https://download.sysinternals.com/files/winget_general_user.exe"`
(Download command for general users I want)

Conclusion It would be good to download the general user files as well.
And the files are not 'Ms Store' only.
It is not only offered by 'Ms Store'.

I would like to offer a variety.
I would like to be able to download it through the website or url.

I love `winget` so I am promoting it.
But even the developers don't know.

The reason is that it is only available in 'Ms Store'. Even the developers don't know.
Moreover, users do not know any more.

For users as well as for developers... I would like some improvement.

my wish
thank you

Use Google Translate I don't speak English.

### Proposed technical implementation details

`curl.exe --output "winget_general_user.exe" --url "https://download.sysinternals.com/files/winget_general_user.exe"`
https://learn.microsoft.com/ko-kr/sysinternals/downloads/process-utilities/winget_general_user.zip
https://learn.microsoft.com/ko-kr/sysinternals/downloads/process-utilities/winget_Download_tools_user.zip

https://live.sysinternals.com/winget_general_user.exe
or
https://live.sysinternals.com/winget_Download_tools_user.exe

https://github.com/microsoft/winget-cli/releases/download/winget_general_user.zip

.

and..

Of course, I wish there was a developer version as well.
Promote it to developers.

https://live.sysinternals.com/wingetcreate.exe
You don't need to add this.
Because I am a user. haha joke.

**Comment by Masamune3210** [comment]
Offline install package is already a thing, its the msixbundle in the releases
![image](https://user-images.githubusercontent.com/1053504/201447316-ff8c2380-2139-48d3-a307-aa2adae18caf.png)

**Comment by oklokl** [comment]
Sorry, I'm a computer newbie.
what about the link? (url)?
I couldn't find it no matter how much I searched.
thank you.

**Comment by Masamune3210** [comment]
Releases page, right side of the main repo page.

**Comment by Trenly** [comment]
The direct URL to download the installer is https://github.com/microsoft/winget-cli/releases/latest/download/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
