### ISSUE TITLE
UAC prompt when installing application

### ISSUE THREAD

**Issue by suhailmalik07** [microsoft/winget-cli#271]
It's ugly when you install a package using the command line and after that, a window prompt appears for a mouse click. Instead of this, something like `sudo` which ask for password before downloading the package will be beautiful and look consistent.

Yeah, you're right we can open the terminal `as an administrator` but when you working only on CLI it breaks the flow. It doesn't feel nice that you opened another terminal window just for installing a program.

**Comment by TheRndCoder** [comment]
In Windows, the closest thing to 'sudo' is Runas: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc771525(v=ws.11)

But the only problem is that the command input is larger compared to just 'sudo winget install package', using runas you would have to do: 'runas /user:<localmachinename>\administrator winget install package' (haven't tested that yet)

**Comment by byteduck** [comment]
Could winget elevate itself and then install the packages?

**Comment by dmex** [comment]
> Could winget elevate itself and then install the packages?

You can run the winget command from an elevated command prompt and won't see any UAC prompts when installing packages.

**Comment by jessehouwing** [comment]
start the command prompt elevated using:

    winkey, 'cmd', ctl-shift-enter'

**Comment by suhailmalik07** [comment]
Yeah, you're right we can open the terminal `as an administrator` but when you working only on CLI it breaks the flow. It doesn't feel nice that you opened another terminal window just for installing a program.

**Comment by suhailmalik07** [comment]
> In Windows, the closest thing to 'sudo' is Runas: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc771525(v=ws.11)
> 
> But the only problem is that the command input is larger compared to just 'sudo winget install package', using runas you would have to do: 'runas /user:\administrator winget install package' (haven't tested that yet)

This can do the work if implemented with windows 10 and winget. Never thought MSFT already had something similar to `sudo`.

**Comment by dhenze-dwz** [comment]
> start the command prompt elevated using:
> 
> ```
> winkey, 'cmd', ctl-shift-enter'
> ```

For some reason I am getting UAC prompts despite doing this. Any ideas?

**Comment by JoBrad** [comment]
Opening a separate elevated prompt not only breaks the user workflow, but also introduces other follow-up steps, too. The user potentially needs to refresh the environment in the other terminal instance, or even destroy it and start over, depending on the updates made.

**Comment by madrian-es** [comment]
> > start the command prompt elevated using:
> > ```
> > winkey, 'cmd', ctl-shift-enter'
> > ```
> 
> For some reason I am getting UAC prompts despite doing this. Any ideas?
> 
> Edit: Nevermind, fixed it. Some weird issue with SmartScreen.

I'm having the same issue, how did you fix it?

**Comment by dhenze-dwz** [comment]
> > > start the command prompt elevated using:
> > > ```
> > > winkey, 'cmd', ctl-shift-enter'
> > > ```
> > 
> > 
> > For some reason I am getting UAC prompts despite doing this. Any ideas?
> > Edit: Nevermind, fixed it. Some weird issue with SmartScreen.
> 
> I'm having the same issue, how did you fix it?

iirc all I did was change the local group policy via gpedit.msc:
`Local Computer Policy -> Computer Configuration -> Administrative Templates -> Windows Components -> Windows Defender SmartScreen -> Explorer -> Configure Windows Defender SmartScreen`

Either enable and set to warn, or disable.

**Comment by ofersadan85** [comment]
I solved it for myself through winget itself using `gsudo`:

    winget install gerardog.gsudo
    gsudo winget upgrade --all

When it is run from a normal (non admin) user, it will only ask for privileges escalation once (similar to how a normal `sudo` would work)

**Comment by masterflitzer** [comment]
> `gsudo winget upgrade --all`

gsudo is amazing, it even comes with an sudo alias so you can do `sudo winget upgrade --all`

**Comment by denelon** [comment]
I've been going through the backlog checking on older issues. This one seems to be resolved with the release of [sudo](https://devblogs.microsoft.com/commandline/introducing-sudo-for-windows/) on Windows.
