### ISSUE TITLE
winget install "PotPlayer" hash..error

### ISSUE THREAD

**Issue by oklokl** [microsoft/winget-cli#2710]
### Brief description of your issue

There has been a recent data center fire in Korea.
So, a Korean company called `daum, kakao` had its servers shut down for a day.
Korea lacks IT consumer support. Anyway..
Error like image occurs.
[Installer hashes do not match. This setting cannot be overridden when running as an administrator.]

And Korean `daum` company did not know about `winget` program at all. :(

They only repeated that it was managed by `ms`?.

I said no.

Although he (they) said he was registering.

Didn't believe my words.

:)

Anyway..

I am speaking with google translator. The cliff of language.. Please understand.

### Steps to reproduce

![1](https://user-images.githubusercontent.com/1571600/202831284-78dd4cb2-7c4f-4d12-bc83-ded420a3193d.png)
Hash error as shown in image.

### Expected behavior

`winget install "PotPlayer" --id "Daum.PotPlayer" -s "winget" --accept-package-agreements`
I'm installing just fine like this.

### Actual behavior

C:\Windows\system32>`winget install "PotPlayer" --id "Daum.PotPlayer" -s "winget" --accept-package-agreements`
Found PotPlayer [Daum.PotPlayer] version 220914
The license for this application has been granted to the user by its owner.
Microsoft is not responsible for and does not license third-party packages.
Downloading https://t1.daumcdn.net/potplayer/PotPlayer/Version/Latest/PotPlayerSetup64.exe
  ██████████████████████████████  ██████████████████████████████  32.6 MB / 32.6 MB
Installer hash does not match. You cannot ignore this setting when running as an administrator.

### Environment

```shell
Microsoft Windows [Version 10.0.19045.2251]
(c) Microsoft Corporation. All rights reserved.

winget -v = v1.3.2691

Windows10 home kr insider 

Other programs install just fine.
Recently the `vlc` program had the same error but it was fixed.
```

**Comment by jharris3299** [comment]
Try here:

https://www.filehorse.com/download-daum-potplayer-64/74284/

**Comment by oklokl** [comment]
I also know the basic download path.
thank you.
I get it via command.
That is the strength of `winget`.

**Comment by SynapseScribe** [comment]
same now
