### ISSUE TITLE
[Bug] Winget `install` and `upgrade` is not working properly.

### ISSUE THREAD

**Issue by Zliced13** [microsoft/winget-cli#2712]
### Brief description of your issue

When I execute this command in my terminal, `winget source update; winget upgrade`, I get this error output:
![(WindowsTerminal)x3V9B1_11-19-2022](https://user-images.githubusercontent.com/101912712/202875414-1001af5d-0642-46e8-ae5c-04b55cd55b80.jpg)
```
> winget source update; winget upgrade                                                                
Updating all sources...
Updating source: msstore...
Done
Updating source: winget...
  ██████████████████████████████  5.00 MB / 5.00 MB
Done
An unexpected error occurred while executing the command:
0x8a150009 : Cannot write to index; it is a higher schema version
```

### Steps to reproduce

Open PowerShell and execute this command:
```
winget source update; winget upgrade
```

### Expected behavior

I expected **Winget** to function properly as it usually does.

### Actual behavior

It's not working, and it's given me an error output code.

### Environment

```shell
Windows Package Manager v1.3.0
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.2251
System Architecture: X64

Logs: %TEMP%\WinGet\defaultState

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by denelon** [comment]
@Zliced13 it appears the version of WinGet in the output isn't one of the GitHub releases. Could you try with one of the versions from [releases](https://github.com/microsoft/winget-cli/releases)?

**Comment by Zliced13** [comment]
I figured out my problem, turns out the built-in winget isn't working properly. So I got rid of it using this command:
```cmd
powershell.exe "Get-AppxPackage Microsoft.DesktopAppInstaller | Remove-AppxPackage"
```
Then, I used a package manager called [**Scoop**](https://scoop.sh) to install **Winget**:
```cmd
scoop install winget
```

Now when I execute `winget source update; winget upgrade`, I will work properly.
```
> winget source update; winget upgrade                                                                
Updating all sources...
Updating source: msstore...
Done
Updating source: winget...
Done
No installed package found matching input criteria.
1 package has a version number that cannot be determined. Using "--include-unknown" may show more results.
```

**Comment by denelon** [comment]
I'm glad you got it working correctly.

**Comment by Mozziliac** [comment]
Sorry to re-hash this. But I'd love to give input on this for anyone having issues with this still.
This was bugging me for a while but finally figured it out.

If youre schema version is higher, 
That means you manually installed a preview version of winget and reinstalled a stable version.
Re-install the preview version, and winget will work.
