### ISSUE TITLE
"Github Issues" problem: preview is not available when submitting new issues

### ISSUE THREAD

**Issue by yilmazdurmaz** [microsoft/winget-cli#2717]
As (possibly) most of us do, I usually use the preview feature of forums, or here in GitHub, before submitting a post/report. This is so that we do not send hard-to-get garbage content. I can say it is one of the most useful secondary features.

I noticed this feature is currently missing in this repository's "new issue" pages. I have checked all templates you have, all are missing it.

I learned about the issue templates only a few days ago, yet checking on one of my repositories, the suggested default templates have no problem with the preview.

Is this a problem with your custom issue templates?
or is there a setting I failed to see, and you have it activated? and if so why?

PS: it is still possible to have a preview when editing an already-submitted issue, but is a bit annoying as you too would agree.

**Comment by Trenly** [comment]
When using issue forms, the preview is per field and is not available for the form as a whole

**Comment by yilmazdurmaz** [comment]
Hi @Trenly,

> When using issue forms, the preview is per field and is not available for the form as a whole

Honestly, I was not expecting what you said.

It seems Edge or Github had a stroke on me at the time I posted this issue. I had a post before this one, in the "Bug" category, and thus came this post after my experience. It works fine now.

Thanks for informing me of the actual behavior.
