### ISSUE TITLE
Installing an app a second time should skip if already installed

### ISSUE THREAD

**Issue by lythix** [microsoft/winget-cli#272]
Issuing an install command for a package should not download and install a package if that version is already installed. 
Some fallback behaviour could be to do a repair, or upgrade. 
If the same version (or the latest version) is installed, there is no reason to re-download and install the app.

**Comment by megamorf** [comment]
This is a duplicate of #216.

**Comment by denelon** [comment]
Duplicate of #216, and thanks @megamorf
