### ISSUE TITLE
powershell got closed when run command `winget`

### ISSUE THREAD

**Issue by gitawego** [microsoft/winget-cli#274]
# Brief description of your issue

powershell got auto closed when run command: winget, 

no issue when running in cmd

# Steps to reproduce

* install [Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle](https://github.com/microsoft/winget-cli/releases/download/v0.1.4331-preview/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle)
* open powershell, type command `winget`
* powershell will get closed automatically.

# Expected behavior

show winget help info

# Actual behavior

powershell terminal got closed automatically

# Environment

```none
[winget --info]
Windows Package Manager version: Windows Package Manager v0.1.41331 Preview
Windows: Windows.Desktop version: windows 10 pro with latest patch
Package: Microsoft.DesktopAppInstaller version: 1.0.41331.0
Windows terminal: 1.0.1401.0

Any other software?
```

**Comment by denelon** [comment]
@gitawego It looks like this is an issue with PowerShell running in Terminal.  They have great instructions on how to report issues.

https://github.com/microsoft/terminal/issues/new?assignees=&labels=&template=Bug_Report.md&title=

Please link back to this issue so we can keep an eye on it also.

**Comment by megamorf** [comment]
Could not reproduce this with PS 5.1 and PS 7.0.1 with the old Windows console and the new Microsoft Terminal.

**Comment by gitawego** [comment]
I just reinstalled windows terminal and Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle, it works now. in powershell, when enter `winget`, the ps terminal doesn't exist anymore
