### ISSUE TITLE
How to get that prompt when you run winget for the first time to come back?

### ISSUE THREAD

**Issue by onyx-nxt** [microsoft/winget-cli#2745]
How do you get that prompt when you run winget for the first time to come back? It says about some agreement and requires a Y or N response. How would I see that message again?

**Comment by mdanish-kh** [comment]
The prompt is about Microsoft Store requiring you to accept to source agreements. You can get the initial behavior by performing a source reset in an administrative terminal.

```pwsh
winget source reset --force
```
