### ISSUE TITLE
hey when i tried to uninstall my vm using winget but couldnt it says couldnt find package and i tried to get the id of it but it said "couldnt find package "

### ISSUE THREAD

**Issue by Forgeuser** [microsoft/winget-cli#2775]
### Brief description of your issue

when i try to uninstall my vm doesnt work when i do list doesnt work

### Steps to reproduce

install oracle vm virtualbox and go to terminal and type 

winget uninstall []Oracle VM VirtualBox

and when i do 

winget list Oracle VM VirtualBox 

### Expected behavior

expected to uninstall the app or show me the id

### Actual behavior

it says "package not found"

### Environment

```shell
winget uninstall Oracle VM VirtualBox 
"package not found" 
winget list Oracle VM VirtualBox 
"package not found"
```

**Comment by Trenly** [comment]
What happens when you try `winget uninstall virtualbox`

**Comment by Forgeuser** [comment]
lemme try

**Comment by Forgeuser** [comment]
it works!!!! tysm man how about installing roblox i tried installing roblox i said 
winget install roblox-player 
but didnt work

**Comment by Trenly** [comment]
> it works!!!! tysm man how about installing roblox i tried installing roblox i said
> winget install roblox-player
> but didnt work

Try `winget search roblox` to see what packages are available for install, and then use the package ID to install the one you want

**Comment by Forgeuser** [comment]
thank you so much man really appreciate it

**Comment by Forgeuser** [comment]
also i tried doing winget search roblox but it only got the fake roblox
