### ISSUE TITLE
Winget v1.4.3531 passes `/SILENT` to Inno installers when using `--silent`, should use `/VERYSILENT`

### ISSUE THREAD

**Issue by o-l-a-v** [microsoft/winget-cli#2793]
### Brief description of your issue

Winget [v1.4.3531](https://github.com/microsoft/winget-cli/releases/tag/v1.4.3531) passes `/SILENT` to Inno installers instead of `/VERYSILENT` when using `--silent`.

This behavior is not present in the latest stable from Microsoft Store, v1.3.2691, which passes `/VERYSILENT` as it should.

#### Related issues that got me here
* https://github.com/JanDeDobbeleer/oh-my-posh/issues/3233
* https://github.com/microsoft/winget-cli/issues/2008

#### Resources
* https://github.com/microsoft/winget-pkgs/tree/master/manifests/j/JanDeDobbeleer/OhMyPosh
* https://jrsoftware.org/ishelp/index.php?topic=setupcmdline

### Steps to reproduce

Command:

* `winget install --exact --silent --scope user --id JanDeDobbeleer.OhMyPosh`

v1.3.2691 / latest in App Installer from Microsoft Store:

* No progress is shown, winget logs says `/VERYSILENT` was passed.

[v1.4.3531](https://github.com/microsoft/winget-cli/releases/tag/v1.4.3531)

* Progress is shown, logs says `/SILENT` was passed.

### Expected behavior

`/VERYSILENT` should be used to be `--silent`.

### Actual behavior

`/SILENT` was used, which is not `--silent`.

#### v1.3.2691 installed with Microsoft Store app App Installer

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2364
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0
```

#### v1.4.3531 extracted from msix with 7-zip

```shell
Windows Package Manager v1.4.0
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2364
System Architecture: X64
```

**Comment by florelis** [comment]
I just tried doing that with the same v1.4.3531 and it did use `/VERYSILENT`.

Log snippet:
```
2022-12-21 15:10:43.160 [CORE] WinGet, version [1.4.3531], activity [{175C57E7-D866-4BAF-83D3-80629FD20E3A}]
...
2022-12-21 15:10:43.167 [CLI ] WinGet invoked with arguments: 'install' '--exact' '--silent' '--scope' 'user' '--id' 'JanDeDobbeleer.OhMyPosh'
...
2022-12-21 15:10:45.637 [CLI ] Installer args: /VERYSILENT /NORESTART /LOG="C:\Users...
```

I went to check the code that adds `/VERYSILENT` for silent mode in Inno installers, and it hasn't changed recently
https://github.com/microsoft/winget-cli/blob/0853f0e35d40abdd90a2aea545d5a52a375bb445/src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp#L586

`/SILENT` is still used for SilentWithProgress, which is the default for winget, so maybe it's a manifestation of that same bug with `upgrade --all --silent`?

**Comment by o-l-a-v** [comment]
@florelis 

Hmm, interesting. I only tried v1.4 with `--all --silent`. Strange that the 1st package got installed with progress, and not the 2nd one.

I tried to quickly gather info and make sense of this strange behavior before going to bed, my investigation was obviously a bit too hasty.

**Comment by florelis** [comment]
I had a hunch on what the cause was and it seemed easy enough, so I went ahead and submitted a fix :)
