### ISSUE TITLE
The type initializer for 'Microsoft.WinGet.Client.Common.BaseClientCommand' threw an exception.

### ISSUE THREAD

**Issue by jdhitsolutions** [microsoft/winget-cli#2795]
### Brief description of your issue

Installed the preview release that supports the PowerShell module. Commands like `Get-WingetSource` fail with error `The type initializer for 'Microsoft.WinGet.Client.Common.BaseClientCommand' threw an exception.`. Looking at the complete exception I wonder if there are leftover hard-coded references.

![image](https://user-images.githubusercontent.com/12089920/209188212-4b84a8b1-933d-43bb-af4a-3bfc3ad866c5.png)

### Steps to reproduce

Installed the 1.4.351 preview release and the PowerShell module. Import the module, try to run a command like `Get-Wingetsource`.

### Expected behavior

Commands should work without error.

### Actual behavior

![image](https://user-images.githubusercontent.com/12089920/209188699-8e7a2071-60f0-42a8-8086-a873ffc1cbbe.png)

### Environment

```shell
Windows Package Manager v1.4.3531
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.2130
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.3531.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

PowerShell module 0.0.1 alpha
```

**Comment by jdhitsolutions** [comment]
I tested in both Windows 10 and Windows 11 on different machines with the same error. Running under PowerShell 7.3.1.

**Comment by denelon** [comment]
Do you mind sharing the steps you used?

I downloaded and extracted the folder from assets to my "user" directory.

<img width="867" alt="PowerShell" src="https://user-images.githubusercontent.com/61799811/209195293-f93c31e4-72e0-42d2-a095-42ce59f86587.png">

**Comment by ryfu-msft** [comment]
@jdhitsolutions, the error above tells me that the module is searching for the 'winrtact.dll' and is unable to load that dll. This is unlikely the issue, but double check to make sure that file is located alongside Microsoft.WinGet.Client.dll. 

I would also try completely closing PowerShell and restarting it just to clean up any previously loaded modules before trying to import the module again.  Just to confirm, which file are you importing? Make sure you are importing the data file (Microsoft.WinGet.Client.psd1), which should point you to the correct module files based on your architecture. 

The last thing I can think of is the data file will select the correct module path based on your processor architecture. If you happen to be using the PowerShell x86, but your machine is 64-bit, this could also throw an error as you may be trying to call the x64 module files. The module platform needs to match the PowerShell platform.

**Comment by jdhitsolutions** [comment]
I extracted the module files and imported the psd1 file. The module loads without error. I can run Get-WingetVersion without error. I've several machines and multiple sessions.

![image](https://user-images.githubusercontent.com/12089920/209207973-e8b5dc08-0fbc-42c2-9935-fdac8e22765e.png)

![image](https://user-images.githubusercontent.com/12089920/209208059-d38fc486-e292-4ca4-bc07-139be307d9d3.png)

![image](https://user-images.githubusercontent.com/12089920/209208203-7950219c-81e8-496f-850d-a17a8aaedfe4.png)

I moved the module to a Windows PowerShell folder before I realized the module only runs under PowerShell 7. But that is irrelevant as I can still import the module by path.

**Comment by jdhitsolutions** [comment]
I can see the x64 files getting loaded. 
![image](https://user-images.githubusercontent.com/12089920/209208748-edbb03c9-8156-46c3-a4e6-1d7414b1a8e0.png)

**Comment by jdhitsolutions** [comment]
Here's the full exception from `Get-Error`.

```powershell
Exception             :
    Type           : System.TypeInitializationException
    TypeName       : Microsoft.WinGet.Client.Common.BaseClientCommand
    TargetSite     : Void .ctor()
    Message        : The type initializer for 'Microsoft.WinGet.Client.Common.BaseClientCommand' threw an exception.
    InnerException :
        Type       : System.DllNotFoundException
        Message    : Unable to load DLL 'winrtact.dll' or one of its dependencies: The specified module could not be
found. (0x8007007E)
        TargetSite :
            Name          : InitializeUndockedRegFreeWinRT
            DeclaringType : Microsoft.WinGet.Client.Common.BaseClientCommand
            MemberType    : Method
            Module        : Microsoft.WinGet.Client.dll
        Source     : Microsoft.WinGet.Client
        HResult    : -2146233052
        StackTrace :
   at Microsoft.WinGet.Client.Common.BaseClientCommand.InitializeUndockedRegFreeWinRT()
   at Microsoft.WinGet.Client.Common.BaseClientCommand..cctor() in
D:\a\_work\1\s\external\pkg\src\PowerShell\Microsoft.WinGet.Client\Common\BaseClientCommand.cs:line 23
    Source         : Microsoft.WinGet.Client
    HResult        : -2146233036
    StackTrace     :
   at Microsoft.WinGet.Client.Common.BaseClientCommand..ctor() in
D:\a\_work\1\s\external\pkg\src\PowerShell\Microsoft.WinGet.Client\Common\BaseClientCommand.cs:line 30
   at lambda_method85(Closure)
   at System.Management.Automation.CommandProcessor.Init(CmdletInfo cmdletInformation)
CategoryInfo          : NotSpecified: (:) [], TypeInitializationException
FullyQualifiedErrorId : System.TypeInitializationException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 3
    Line             : find-wingetpackage -moniker git.git
    PositionMessage  : At line:1 char:1
                       + find-wingetpackage -moniker git.git
                       + ~~~~~~~~~~~~~~~~~~
    InvocationName   : find-wingetpackage
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1

```

**Comment by jdhitsolutions** [comment]
And to verify, all we needed to do was extract the module files. There was no install or registration step. I am also running in an elevated session.

**Comment by denelon** [comment]
That's all I did. The screenshot above is right after I downloaded and extracted the files. It also works in admin mode for me (screenshot below).

<img width="867" alt="admin" src="https://user-images.githubusercontent.com/61799811/209211496-8dbe3cc3-b131-47ec-b33e-b143c92213fc.png">

**Comment by jdhitsolutions** [comment]
@denelon Is this your development machine? Did you test on a new machine? I didn't see any Pester tests in the module.

**Comment by jdhitsolutions** [comment]
I extracted to different locations with the same results. I have also tested on 2 different machines running windows 10 and Windows 11.

**Comment by jdhitsolutions** [comment]
My .NET skills are limited, but I do know PowerShell and how modules work. If I try to manually add the DLL using `Add-Type` I get the error `Add-Type: Bad IL format. The format of the file 'C:\Program Files\PowerShell\7\Modules\Microsoft.Winget.client\x64\Core\winrtact.dll' is invalid.`. I get no errors with the other DLL files in the directory.

**Comment by ryfu-msft** [comment]
@jdhitsolutions, Thanks for your info. I believe the issue lies in a missing dependency that is not explicitly called out in our PowerShell documentation. There is a dependency on the Microsoft Visual C++ Redistributable package that needs to be installed on your machine. Can you try running ```winget install --id Microsoft.VCRedist.2015+.x64```? Once you do that, import the module on a new shell window and try again.  I was able to repro your error on a clean VM and installing this package resolved the issue.

**Comment by jdhitsolutions** [comment]
That's the answer. Pesky documentation.

**Comment by ryfu-msft** [comment]
I'll make sure to update the documentation to call this out explicitly. Thanks for your help with resolving this issue!

**Comment by denelon** [comment]
@ryfu-msft if it's not too late, link the PR to this issue so it isn't closed until the documentation is updated please :)
