### ISSUE TITLE
Winget reporting the wrong version for some apps 

### ISSUE THREAD

**Issue by Bennett-Fourr** [microsoft/winget-cli#2817]
### Brief description of your issue

Winget shows the wrong version for some apps and trys to upgrade when they are fully up to date as showen below

### Steps to reproduce

Download Safing Portmaster than run "winget upgrade" 

### Expected behavior

It to show the correct version

### Actual behavior

It shows the wrong version and trys to upgrade even when up to date
![Screenshot 2023-01-04 174136](https://user-images.githubusercontent.com/94060774/210665489-350ee847-ace9-446f-9bfb-67082203a07b.png)
![Screenshot 2023-01-04 174213](https://user-images.githubusercontent.com/94060774/210665492-8d396667-63f8-4f9e-953c-5ca621f7b5f0.png)

### Environment

```shell
Windows Package Manager v1.3.2691

Windows: Windows.Desktop v10.0.22621.963
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0


Safing Portmaster v1.0.4
```

**Comment by denelon** [comment]
The version displayed by WinGet is what is displayed in Windows Apps & Features.

The "installer" is responsible for setting the registry keys for those values.

The functionality for 1.3 is described in the blog:

https://devblogs.microsoft.com/commandline/windows-package-manager-1-3/#new-version-reporting

**Comment by NoSubstitute** [comment]
Oh, @denelon I have that problem with these VC++ redists.
Is that also something wrong in the registry, or am I just doing something wrong?
I have run those updates dozens of times, and they just keep coming back.

![image](https://user-images.githubusercontent.com/12572734/210798944-4b6739d5-8492-419e-9757-98bb82393545.png)

**Comment by denelon** [comment]
What is that UI coming from? It doesn't look like Windows Apps & Features.

In general, we currently have challenges with many of the VC redists due to the various architectures being installed. We have work in progress to improve the situation. We have a set of heuristics that truncate architecture and other things listed in parenthesis at the end of the "displayName". We need to improve the logic for manifests with the correct "AppsAndFeatures" entries.

**Comment by NoSubstitute** [comment]
@denelon it is the winget UI.

**Comment by otherside1** [comment]
How do you use winget ui

**Comment by NoSubstitute** [comment]
Install and run. Super easy.
Perhaps even available in the Store.
https://github.com/marticliment/WingetUI

**Comment by Karl-WE** [comment]
> What is that UI coming from? It doesn't look like Windows Apps & Features.
> 
> In general, we currently have challenges with many of the VC redists due to the various architectures being installed."

From my point of view winget already does a good job on c++ Redist and recognizing outdated versions. 

Thankfully with 2015-2022 (named 2015+ in winget-pkgs) the side-by-side Installation of Redist has come to an end after nearly a decade.

**Comment by Araxeus** [comment]
This also seems to happens for standalone executables?

for example:
```
Name                             Id                       Version        Available      Source
----------------------------------------------------------------------------------------------
Carapace                         rsteube.Carapace         0.23.0         0.24.4         winget
```

This refuses to go away... 

https://github.com/microsoft/winget-pkgs/blob/378cbdd2da94fe64ab662ca192639781004b122b/manifests/r/rsteube/Carapace/0.24.4/rsteube.Carapace.installer.yaml#L14

I have also several others apps that always show as outdated, and while https://github.com/microsoft/winget-cli/issues/1439 is not implemented, this is very annoying

```
Name                             Id                       Version        Available      Source
----------------------------------------------------------------------------------------------
FACEIT                           FACEITLTD.FACEITClient   1.31.5         1.31.13        winget
Carapace                         rsteube.Carapace         0.23.0         0.24.4         winget
EA app                           ElectronicArts.EADesktop 12.148.0.5405  12.164.0.5421  winget
Microsoft .NET SDK 6.0.203 (x64) Microsoft.DotNet.SDK.6   6.0.203        6.0.408        winget
```

**Comment by aadithya96** [comment]
I have the same issue with powershell. My installed version is 7.3.4, though winget shows it as 7.3.1
![image](https://user-images.githubusercontent.com/7714583/236168607-7d31dd1f-2043-49f9-89ce-bc4960c0a48b.png)

**Comment by mdanish-kh** [comment]
@aadithya96 Can you share output of `winget list "PowerShell"`, I'm wondering if there are multiple versions installed

**Comment by aadithya96** [comment]
@mdanish-kh You were right, there are 2 versions shown. Any idea on how to remove those?
![image](https://user-images.githubusercontent.com/7714583/236179142-6386f40b-c862-4bf1-8508-6d46d17f5c71.png)

**Comment by mdanish-kh** [comment]
You'll have to manually remove the older version from Apps&Features or `appwiz.cpl`

**Comment by mdanish-kh** [comment]
Regarding the original issue, this is a problem with the Portmaster package not updating the DisplayVersion string in the registry and should be brought up to the publisher to resolve. Related issue in the portmaster repo: https://github.com/safing/portmaster/issues/1050

**Comment by Mrgaton** [comment]
I have same issue on 2024
