### ISSUE TITLE
Can I get the downloaded package file?

### ISSUE THREAD

**Issue by inkuaxjieng** [microsoft/winget-cli#2821]
### Description of the new feature / enhancement

In some places where the network is not good, offline installation is very important. I don't know if the installation package can be kept instead of deleted after installation.

**Comment by denelon** [comment]
We're looking at a `winget download` feature to just download packages.

As a workaround, you can use `winget show <packageID.` and download from the URL.

**Comment by denelon** [comment]
Duplicate of #658
