### ISSUE TITLE
Output of winget search "" is not complete

### ISSUE THREAD

**Issue by Frxhb** [microsoft/winget-cli#2860]
### Brief description of your issue

I would like to use winget to search for all packages and store them in a text file or a variable. Later on I would like to sort them in a list with "Name" and "ID". Unfortunately it seems like you cannot search just for winget package Names and IDs directly using winget.exe.
<br>
What I have tried so far:

```powershell
Clear-Host

if (Test-Path -path "$env:temp\download_winget"){
    write-host "Folder exists. Continuing..."
}
else{
    write-Host "There is no folder called winget_download!`nCreating..."
    mkdir "$env:temp\download_winget"
    
}

$get_winget_packages = winget search . --accept-source-agreements | Out-File "$env:temp\download_winget\winget_packages.txt" -Encoding utf8

```

(Yes I know, you can also use ```winget search """"```)

I even tried it with a new powershell process with windowstyle maximized:

```
Start-Process powershell.exe -ArgumentList ("winget search ." , "| Out-File '$env:temp\download_winget\winget_packages_lol.txt' -Encoding utf8") -WindowStyle Maximized
```

### Steps to reproduce
```powershell
Clear-Host

if (Test-Path -path "$env:temp\download_winget"){
    write-host "Folder exists. Continuing..."
}
else{
    write-Host "There is no folder called winget_download!`nCreating..."
    mkdir "$env:temp\download_winget"
    
}

$get_winget_packages = winget search . --accept-source-agreements | Out-File "$env:temp\download_winget\winget_packages.txt" -Encoding utf8

gc $get_winget_packages 

```

### Expected behavior

I want to have an output with all correct winget packages ID and Names.

### Actual behavior

As you can see, I displayed with ```gc "$env:temp\download_winget\winget_packages.txt"``` the content of the earlier created file. Unfortunately some of the lines are not displayed correctly. For example:

```powershell
Name                                      ID                                  Version            Ãœbereinstimmung Quelle
-----------------------------------------------------------------------------------------------------------------------
...
...
...
Windows Package Manager Manifest Creator  Microsoft.WingetCreate              1.1.2.0                            winget
Remote Desktop Services Infrastructure Aâ€¦ Microsoft.WindowsVirtualDesktopAgeâ€¦ 1.0.5739.9800                      winget
Windows Terminal Preview                  Microsoft.WindowsTerminal.Preview   1.16.3463.0                        winget
Windows Admin Center                      Microsoft.WindowsAdminCenter        1.3.53858.0                        winget
Windows Assessment and Deployment Kit     Microsoft.WindowsADK                10.1.22621.1                       winget
```

I did not find any solution to get all winget packages full Name or full ID using ```winget search .```
Even running this directly in PowerShell or CMD, it will display some package Names and ID not fully. Changing the Encoding to utf32, ascii, utf7 or something else wont change anything too. <br>
Is there a workaround to show the correct/full names of all winget packages Name and ID?
![2023-01-17 15_31_46-Administrator_ Windows PowerShell](https://user-images.githubusercontent.com/68739220/212925788-df8464b8-1e2c-4814-a779-7ff83e7bee5a.png)

### Environment

```shell
Windows-Paket-Manager v1.2.10691
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22621.1105
Paket: Microsoft.DesktopAppInstaller v1.17.10691.0

Protokolle: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
Seems like this duplicates https://github.com/microsoft/winget-cli/issues/2603

**Comment by Frxhb** [comment]
Seems like a duplicate, yes. Thanks alot.
