### ISSUE TITLE
Heading size "Installed packages" in Dutch

### ISSUE THREAD

**Issue by Stephan-P** [microsoft/winget-cli#2865]
### Brief description of your issue

WinGetUI version 1.5.3
When the UI language is set to Dutch, then the heading of the tab "Installed packages" is of a smaller font size than the headings of the tabs "Explore packages" and "Software Updates"

![image](https://user-images.githubusercontent.com/10008599/213199139-7b27c2d9-04f1-4bd2-b535-9555b485446c.png)

![image](https://user-images.githubusercontent.com/10008599/213199309-e7176782-c6ae-4c74-9e7e-b90d33086009.png)

### Steps to reproduce

Settings - UI language - Dutch

### Expected behavior

All tab headings of the same font size

### Actual behavior

Tab "Installed Packages" shows a header in smaler font size.

Note that that this issue does not occur when UI language is set to English.

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1105
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0
```

**Comment by ItzLevvie** [comment]
If this is still an issue for you then it will need to be reported to https://github.com/marticliment/WingetUI/issues because this is a third-party software.

**Comment by Stephan-P** [comment]
We are at https://github.com/marticliment/WingetUI/issues and I've immediately closed the issue I created after I discovered that this isn't an issue in the app after all.
