### ISSUE TITLE
Ability to install multiple packages in one command

### ISSUE THREAD

**Issue by retnikt** [microsoft/winget-cli#287]
# Description of the new feature/enhancement

I would like to be able to install multiple packages in one command like:
```
winget install package1 package2 package3
```
Instead of 
```
winget install package1
winget install package2
winget install package3
```
This is a standard feature of all package managers I can think of, from `apt-get` to `yarn`.

# Proposed technical implementation details (optional)

**Comment by megamorf** [comment]
This issue is a duplicate. Please use the search function before needlessly opening tickets:
* #156
* #219

**Comment by retnikt** [comment]
Sorry I couldn't see that

**Comment by masx200** [comment]
I support it!

**Comment by SalahAdDin** [comment]
@denelon, how can we do this?

**Comment by jo-chemla** [comment]
Simple: https://github.com/microsoft/winget-cli/issues/4566

```
winget install --disable-interactivity --accept-source-agreements --accept-package-agreements 7zip.7zip Mozilla.Firefox VideoLAN.VLC OBSProject.OBSStudio Microsoft.VisualStudioCode Microsoft.WindowsTerminal TheDocumentFoundation.LibreOffice SomePythonThings.WingetUIStore GitHub.GitHubDesktop BlenderFoundation.Blender Gyan.FFmpeg 

```
