### ISSUE TITLE
"winget list" Wrong source is listed. Manually installed program has source "winget"

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [microsoft/winget-cli#2882]
### Brief description of your issue

When I ran "winget list" I expected to get a list of all of the packages that I had installed by running `winget packagenamehere`, but instead I got a list of most of my installed programs. This list included the ["Everything" alpha release](https://www.voidtools.com/forum/viewtopic.php?f=12&t=9787#download), which I installed manually through an exe from their forums. Winget listed this program's source as "winget", despite me having installed it through an exe and not through winget.

### Steps to reproduce

- [Install the Everything alpha](https://www.voidtools.com/forum/viewtopic.php?f=12&t=9787#download)
- run `winget list`

### Expected behavior

A program shouldn't be listed in "winget list" if it wasn't installed through winget
```
C:\Users\User>winget list
Name                                                Id                                                       Version           Available    Source
--------------------------------------------------------------------------------------------------------------------------------------------------
```

Alternatively, the Source field should be empty:
```
C:\Users\User>winget list
Name                                                Id                                                       Version           Available    Source
--------------------------------------------------------------------------------------------------------------------------------------------------
Everything 1.5.0.1332a (x64)                        voidtools.Everything.Alpha                               1.5.0.1332                           
```

### Actual behavior

```
C:\Users\User>winget list
Name                                                Id                                                       Version           Available    Source
--------------------------------------------------------------------------------------------------------------------------------------------------
Everything 1.5.0.1332a (x64)                        voidtools.Everything.Alpha                               1.5.0.1332                     winget
```

### Environment

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2486
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
```

**Comment by mdanish-kh** [comment]
The source field isn't stating which source the package was installed from (there is no way for winget to detect that behavior), rather it is saying that `Everything 1.5.0.1332a` is available through the "winget" source.

**Comment by ItsIgnacioPortal** [comment]
> The source field isn't stating which source the package was installed from (there is no way for winget to detect that behavior), rather it is saying that `Everything 1.5.0.1332a` is available through the "winget" source.

I see. I got the wrong impression. I've now found #1155
