### ISSUE TITLE
Check if Package installed

### ISSUE THREAD

**Issue by ghost1372** [microsoft/winget-cli#291]
hi is there any command to check if package installed?

**Comment by ghost1372** [comment]
@KevinLaMS  Just as we can easily install packages (winget install id), a simple command (winget exist id)  can check the user's system for the installation of that package and return true or false

**Comment by megamorf** [comment]
No, there's no implementation for that yet. Subscribe to #153

**Comment by KevinMarquette** [comment]
It would be even more helpful if we could also specify a PowerShell `ExistsScript` script in the manifest to check if the package needs to be installed to support the exist option. The `winget exist sysinternals` would use that script to return true or false.  If provided, it could also run before the install to see if it even needs to install anything and it could run after the install to verify it was installed. This is a pattern used by DSC so its something the PowerShell community is aware of.

**Comment by andypiper** [comment]
I'd like the ability to know which packages are installed / have been installed via winget; and to ideally export to a file for future setups. My use case is a brand new Surface Laptop 3, migrating from an HP, would be great to know what I just winget-installed, and to export to a file for a future new setup, similar to a Brewfile. I understand that winget is not homebrew, but this would be very useful.

**Comment by denelon** [comment]
@andypiper the experimental "list" command will tell you everything that is installed on the system. We have #220 export/import on the backlog to do what you're talking about.

**Comment by iDolmatov** [comment]
Also available for one application.

Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19043.1023
Microsoft.DesktopAppInstaller v1.11.11451.0


![image](https://user-images.githubusercontent.com/19782385/120401940-73ab2100-c35a-11eb-96ff-47959f796940.png)

**Comment by Croydon** [comment]
I have a script that installs and updates certain software. It does not currently use winget, because of the lack of an easy way to check first if a package is already installed.

Basically, do a `winget install` if package X  in version Y is not yet installed, if it is already installed, return true and do nothing.

**Comment by sanamhub** [comment]
This behavior is different as per the apps:

Note: Below packages are already installed!

When AnyDesk is already installed: 
Input: `winget install  AnyDeskSoftwareGmbH.AnyDesk`
Output: `Installer failed with exit code: 11341828`

When Notepad++ is already installed:
Input: `winget install Notepad++.Notepad++`
Output: `Multiple packages found matching input criteria. Please refine the input.`

Where, Some other packages get insalled again.. 😞 
Really need a solution for this.. Like check if already installed and skip install or check if exists..

Btw, `winget` downloads the package at first and proceeds next (error/install/shows already exists)

**Comment by sanamhub** [comment]
> @KevinLaMS Just as we can easily install packages (winget install id), a simple command (winget exist id) can check the user's system for the installation of that package and return true or false

`winget exist id` didn't work!

**Comment by alanlivio** [comment]
To the ones still looking for answer, this work for me:

```
winget list -q $id | Out-Null
if ($?) {  echo "$id installed" }
```

**Comment by rdev32** [comment]
> [alanlivio](/alanlivio)

thank you brother! you saved me another week
