### ISSUE TITLE
Tab Complete Installed / Available packages

### ISSUE THREAD

**Issue by mrlinuxfish** [microsoft/winget-cli#2920]
### Description of the new feature / enhancement

I was just now updating packages using `winget upgrade --all` which gave me a message `Package agreements were not agreed to. Operation cancelled.`. Finding an open issue to allow for `--all` and `--accept-package-agreements` I noticed I probably have to upgrade packages one at a time to find the one which requires the package agreement.

I was attempting to tab complete `winget upgrade Microsoft.WindowsTerminal` as it was the first item in the list, but the tab completion of `winget upgrade Mic` is `winget upgrade .\Microsoft\`.

Tab completion is exceptionally helpful for not having to manually type or copy paste package names.

### Proposed technical implementation details

Pressing tab would complete package names when relevant.

**Comment by florelis** [comment]
https://github.com/microsoft/winget-cli/blob/master/doc/Completion.md
