### ISSUE TITLE
Upgrading a running app upgrades the metadata but not the app.

### ISSUE THREAD

**Issue by Digiroka** [microsoft/winget-cli#2934]
when running **winget upgrade** against a running application, the task shows success, but the application is still the old version. However, the winget metadata is updated so winget reports the new version.

Steps to reproduce:

1. Winget uninstall --id 7zip.7zip
2. winget install --id 7zip.7zip --source winget --version 21.06
3. launch 7zip and keep running
4. winget upgrade --id 7zip.7zip 
5. wait for completion
6. close running 7zip app
7. winget list --id 7zip.7zip
8. you will see new version listed in result
9. launch 7zip - look at version info, old version shown

subsequently, you can use **Winget uninstall --id 7zip.7zip --version 21.06** (not listed) to unistall.

This issue leads to incorrect reporting - can metadata updates be blocked and an error reported if the app is running?

Thanks

**Comment by R-Adrian** [comment]
sometimes if the app is running the actual replacement of the binary files is done by the windows installer at system reboot... can you please check for pending file replacements at system boot?
or simply, just reboot the system and check what version binaries you find after reboot.

**Comment by Digiroka** [comment]
That fixed it - thank you for your help!
