### ISSUE TITLE
Adding a .wapproj file to an existing WPF app breaks solution build in Visual Studio 2022

### ISSUE THREAD

**Issue by pygmypenguin** [microsoft/winget-cli#2964]
### Brief description of your issue

I have a desktop application that currently builds and run with no issues. It is build primarily on WPF, with a couple older controls in WinForms and one vcxproj that enables directX rendering. This application currently builds and publishes with Visual Studio's msbuild.exe. In order to modernize our deployment, we want to add a Windows Application Packaging project to take advantage of some modern versioning and distribution principles.

After going through the "Add a new project wizard" to add this project, Visual Studio's built-in "build" command fails with `Specified EntryPointExe '' was not found in the project outputs`. I've seen a few different solutions online about how to "fix" this but none of them have worked, and all of them seem to require going into the .wapproj or Project.appxmanifest and modifying various elements manually. I would rather not do this if possible, since it appears that these two file types are not very well documented.

### Steps to reproduce

- setup Visual Studio '22 to have the following workflows installed:
![image](https://user-images.githubusercontent.com/11782269/218867755-09a3bc7e-47fe-4dfe-b959-1e6f7bc39e7d.png)
- Enable developer mode on system
![image](https://user-images.githubusercontent.com/11782269/218870841-4b9dc094-d09f-4841-b2cf-541915151e43.png)
- create a new WPF desktop project and ensure it starts successfully
- Create a "Deploy" solution folder (not sure this is necessary, but it's what I've done)
- Add a new Windows Application Packaging project to the Deploy folder
- Add the WPF project as an reference to the Applications section 
- Using the designer, edit the Application and Visual Assets sections of the Package.appxmanifest file in the .wapproj (set supported orientations and use the generator to create relevant visual assets)
- Set Configuration and Platform to Release and x64, respectively, and build (`Ctrl + Shift + B`)
- alternatively, from the root of the solution in a bash shell, run msbuild (`msbuild -p:Configuration=Release -p:Platform=x64 `)

### Expected behavior

The solution builds with no errors

### Actual behavior

The solution fails to build with the following output: 

```
Build FAILED.

"C:\git\TesseractXL\TesseractXL.MSIX\TesseractXL.MSIX.wapproj" (default target) (1) ->
(_ConvertItems target) ->
  C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets(744,5): error : Specified EntryPointExe '' was not found in the project outputs. [C:\git\TesseractXL\TesseractXL.MSIX\TesseractXL.MSIX.wapproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:04.20
```

### Environment

```shell
Visual Studio version: Microsoft Visual Studio Professional 2022 (64-bit) 17.4.3
Windows OS Build: 19042.2486 
Target Application (TesseractXL.csproj) relevant PropertyGroup:

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>net6.0-windows</TargetFrameworks>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<Company>DRW</Company>
		<Authors />
		<OutputPath>..\Build\$(Configuration)</OutputPath>
		<BaseOutputPath>..\Build</BaseOutputPath>
		<StartupObject>TesseractXL.Program</StartupObject>
		<ApplicationIcon>Tesseract.ico</ApplicationIcon>
		<PlatformTarget>x64</PlatformTarget>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>
```
wapproj (TesseractXL.MSIX.wapproj) relevant property groups:
```
<PropertyGroup>
    <WapProjPath Condition="'$(WapProjPath)'==''">$(MSBuildExtensionsPath)\Microsoft\DesktopBridge\</WapProjPath>
  </PropertyGroup>
  <Import Project="$(WapProjPath)\Microsoft.DesktopBridge.props" />
  <PropertyGroup>
    <ProjectGuid>78051ebc-748e-4f0a-8301-738533d0811e</ProjectGuid>
    <TargetPlatformVersion>10.0.19041.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.17134.0</TargetPlatformMinVersion>
    <DefaultLanguage>en-US</DefaultLanguage>
    <AppxPackageSigningEnabled>false</AppxPackageSigningEnabled>
    <NoWarn>$(NoWarn);NU1702</NoWarn>
    <EntryPointProjectUniqueName>..\TesseractXL\TesseractXL.csproj</EntryPointProjectUniqueName>
  </PropertyGroup>
```
```

**Comment by denelon** [comment]
@pygmypenguin I don't think this issue has anything to do with WinGet. It appears to be an issue with Visual Studio.

You could try: https://developercommunity.visualstudio.com/VisualStudio/report

**Comment by pygmypenguin** [comment]
hm you're right, my apologies

**Comment by denelon** [comment]
No worries. I hope I pointed you in the right direction.
