### ISSUE TITLE
ID of added pin inconsistent with output

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#2977]
### Brief description of your issue

* Related to #2976

When I ran `winget pin CCleaner` on a new machine, it indicated that a pin was added for the ID `Piriform.CCleaner`. However, the pin was actually added for `Piriform.CCleaner.ProTrial`

### Steps to reproduce

1) `winget install --id Piriform.CCleaner -e`
2) `winget pin add CCleaner`
3) `winget pin list`

### Expected behavior

Pin added for `Piriform.CCleaner` as shown in the output of `Found CCleaner [Piriform.CCleaner]`

### Actual behavior

[Pin add #1 - WinGet-2023-02-15-21-44-39.723.log](https://github.com/microsoft/winget-cli/files/10752005/WinGet-2023-02-15-21-44-39.723.log)
[Pin add #2 - WinGet-2023-02-15-21-44-46.457.log](https://github.com/microsoft/winget-cli/files/10752006/WinGet-2023-02-15-21-44-46.457.log)
[Pin list - WinGet-2023-02-15-21-45-03.796.log](https://github.com/microsoft/winget-cli/files/10752008/WinGet-2023-02-15-21-45-03.796.log)

```
PS C:\WINDOWS\system32> winget pin add CCleaner
Found CCleaner [Piriform.CCleaner]
Pin added successfully
PS C:\WINDOWS\system32> winget pin add CCleaner
Found CCleaner [Piriform.CCleaner]
There is already a pin for package CCleaner Professional Trial
PS C:\WINDOWS\system32> winget pin list
Id                         Source Version
------------------------------------------
Microsoft.Office           winget Blocking
Microsoft.WindowsSDK       winget Blocking
Piriform.CCleaner.ProTrial winget Pinning
```

![image](https://user-images.githubusercontent.com/12611259/219265023-0ce5d793-36e4-42c5-9041-8cd1787aa54c.png)

### Environment

```shell
PS C:\WINDOWS\system32> winget --info
Windows Package Manager (Preview) v1.5.441-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2486
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.441.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by florelis** [comment]
One of the changes I did with pinning was allowing one single installed package to be associated to multiple available packages. That way, you would be able to pin a package from all sources at once.

What I'm imagining is happening here is that the package matches with both Piriform.CCleaner.ProTrial and PiriformCCleaner, then it gets inconsistent with which one it picks to show at any given point. I need to think how to fix that

**Comment by Trenly** [comment]
> One of the changes I did with pinning was allowing one single installed package to be associated to multiple available packages. That way, you would be able to pin a package from all sources at once.
> 
> What I'm imagining is happening here is that the package matches with both Piriform.CCleaner.ProTrial and PiriformCCleaner, then it gets inconsistent with which one it picks to show at any given point. I need to think how to fix that

I think the idea of matching with multiple packages is good because of the possibility of multiple sources, but it should also probably not match multiple packages from the same source - Unless all matches are pinned

**Comment by florelis** [comment]
There is currently not any version of Piriform.CCleaner.ProTrial in winget-pkgs; looks like the bot removed it due to hash mismatch.   So I'm not able to test how it would behave with #3167, but I'm guessing it doesn't fix it.
Would we want to add back the package?

**Comment by mdanish-kh** [comment]
> Would we want to add back the package?

6.10 version is currently present in the repo 👀(albeit with an incorrect PackageVersion) https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/Piriform/CCleaner/ProTrial/6.10.0.10347

**Comment by florelis** [comment]
> > Would we want to add back the package?
> 
> 6.10 version is currently present in the repo 👀(albeit with an incorrect PackageVersion) https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/Piriform/CCleaner/ProTrial

Oh, you're right. I just went to https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/Piriform/ and got confused because I didn't see CCleaner.ProTrial there.

Anyways; the change in #3167 also seems to fix this issue :)
