### ISSUE TITLE
Filter search for supported architecture

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/winget-cli#300]
# Brief description of your issue
Search should only show results that you can install on your machine.

# Steps to reproduce
This is just an example of a given app. I'm sure others exist.
1. Use an ARM64 device (i.e. Surface Pro X)
2. `winget search powertoys`
3. result is found
4. `winget install powertoys`

# Expected behavior

When searching, the result should be suppressed or included with a note saying that it is not supported for your current architecture.

# Actual behavior

I get excited that I can download powertoys, then I get hit in the face with this when I try to install it:
```
No installers are applicable to the current system
```

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version v10.0.19631.1
Package: Microsoft.DesktopAppInstaller version v1.0.41331.0
```

**Comment by megamorf** [comment]
This is already being tracked in #132.
