### ISSUE TITLE
Broad or general dependencies

### ISSUE THREAD

**Issue by stephengillie** [microsoft/winget-cli#3009]
### Description of the new feature / enhancement

Sometimes a package requires a dependency which is supplied by multiple developers. Git is a good example, having Git.Git and Microsoft.Git, among others. Currently, dependencies have to be exactly specified. This feature would allow a wildcard or other way of allowing any developer's version of the software to be used. 

Another example might be if a project could use any version of Python 3, instead of having to specify a specific minor version. This could also be used for JRE and JDK packages, if those PackageIdentifiers were standardized.

### Proposed technical implementation details

Use an asterisk (*) as a wildcard in the name. Using Git as an example: 
```
Dependencies:
  PackageDependencies:
    - PackageIdentifier: *.Git
```

This would allow any developer's version of Git to satisfy the dependency requirement. 

Again with Python as an example: 
```
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Python.Python.3.*
```

This would allow any minor version of Python 3 to satisfy the dependency requirement. 

Last but not least, JRE: 
```
Dependencies:
  PackageDependencies:
    - PackageIdentifier: *.*.18.JRE
```

This would allow any developer's version of JRE version 18 to satisfy the dependency requirement.

**Comment by Trenly** [comment]
This seems similar to #2969 in a way, but also different.

I like the concept, but I would be very concerned about false matches. For example, what if someone adds a game like "Generic Game 18 - Just Run Everywhere" and the package identifier isn't carefully scanned. I know this is an edge case, but external REST sources could very easily not adhere to the same standards as the community repo. An executable could be added to a rest source as `Python.Python.3.ScriptValidator` which would be treated as a match. but might not actually provide python3

**Comment by stephengillie** [comment]
Duplicate of #2969
