### ISSUE TITLE
Change WinGet behavior when the Microsoft Store UI is disabled

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#3025]
### Description of the new feature / enhancement

I want to be able to leverage WinGet to install packages in the Microsoft Store if the Microsoft Store UI is disabled.

*Note: The current behavior in WinGet is to check to see if the Microsoft Store UI is disabled. If the Microsoft Store UI is disabled, WinGet blocks installing Microsoft Store Apps.*

This is targeted as a 1.6 release milestone to afford enterprise customers the time necessary to configure policy appropriately given the nature of the change.

Related to:
* #3024

**Comment by BarbieAction** [comment]
Settings Require Private Store only on Windows 11 will block the store and allow Winget.
https://learn.microsoft.com/en-gb/windows/client-management/mdm/policy-csp-ApplicationManagement?WT.mc_id=Portal-fx#requireprivatestoreonly
