### ISSUE TITLE
Winget stopped working for no reason

### ISSUE THREAD

**Issue by SleepDaemon** [microsoft/winget-cli#3039]
### Brief description of your issue

I don't know how to describe other than winget in general doesn't work

here are ss of what im getting

![image](https://user-images.githubusercontent.com/88533953/222744519-e4f866ac-3df3-4142-b308-363335f1ec7f.png)
![image](https://user-images.githubusercontent.com/88533953/222744554-a62f8263-ac4c-42fd-b756-56b4914dca04.png)

### Steps to reproduce

just typing winget in either powersheel or cmd

### Expected behavior

i dont know what the output is for when you type winget. prob tells you what version is installed

### Actual behavior

i get error

### Environment

```shell
dont know since winget itself is not working.
```

**Comment by SleepDaemon** [comment]
`Add-AppxPackage https://github.com/microsoft/winget-cli/releases/latest/download/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle`

i tried using this command to perhaps reinstall it but got this instead
![image](https://user-images.githubusercontent.com/88533953/222748502-c2f6a55a-c9e6-4cea-bd55-9fe825e99947.png)

**Comment by SleepDaemon** [comment]
i have also tried using windows repair but that doesnt work either

**Comment by SleepDaemon** [comment]
Installing using via ms store works

**Comment by stephengillie** [comment]
Hi @SleepDaemon,

An internet search on the first part of the error, `80073CF0, Package could not be opened` suggests that the issue is from an incomplete package download, and that downloading again actually downloads that cached incomplete package. And the suggested solution (this is untested) was to remove the incomplete file, located within `C:\Windows\SoftwareDistribution\DeliveryOptimization`. Please be careful with this suggestion as it might cause other issues. If possible, please consider duplicating your computer onto a VM and testing it there. 

Hope this helps, sorry if it does not.

**Comment by denelon** [comment]
@SleepDaemon the current release is available via https://aka.ms/getwinget. You may also use the Microsoft Store to install the App Installer, or any of the .msixbundle packages from the GitHub [releases](https://github.com/microsoft/winget-cli/releases).

**Comment by SleepDaemon** [comment]
> @SleepDaemon the current release is available via https://aka.ms/getwinget. You may also use the Microsoft Store to install the App Installer, or any of the .msixbundle packages from the GitHub [releases](https://github.com/microsoft/winget-cli/releases).

I get this pop up every time with any .msixbundle
![image](https://user-images.githubusercontent.com/88533953/222776495-a3177a57-d144-4da0-bbf8-6c1abbd4bea2.png)

**Comment by denelon** [comment]
Do you have a firewall or something else that might be impacting network access?

You may also be able to [repair](https://learn.microsoft.com/windows/msix/desktop/managing-your-msix-reset-and-repair) the App Installer.

**Comment by SleepDaemon** [comment]
> @SleepDaemon the current release is available via https://aka.ms/getwinget. You may also use the Microsoft Store to install the App Installer, or any of the .msixbundle packages from the GitHub [releases](https://github.com/microsoft/winget-cli/releases).

For App installer from MS store, top: loading - bottom: loaded

i dont know but doesnt work.
![image](https://user-images.githubusercontent.com/88533953/222776805-babc15d0-b15d-4a5c-bef1-410feec510df.png)
![image](https://user-images.githubusercontent.com/88533953/222776970-5314f9b8-fce8-400e-9ce9-17f695bd2cca.png)

**Comment by SleepDaemon** [comment]
> Do you have a firewall or something else that might be impacting network access?
> 
> You may also be able to [repair](https://learn.microsoft.com/windows/msix/desktop/managing-your-msix-reset-and-repair) the App Installer.

i dont think it is firewall, i reset it to defualt windows few weeks back.

**Comment by SleepDaemon** [comment]
> Do you have a firewall or something else that might be impacting network access?
> 
> You may also be able to [repair](https://learn.microsoft.com/windows/msix/desktop/managing-your-msix-reset-and-repair) the App Installer.

I can't find the app installer in windows settings next best thing is to reset it using powershell command but I need the specific app installer name/address. I don't know how to get mine.

**Comment by SleepDaemon** [comment]
> Did you take a look at the [Troubleshooting Guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting#common-issues)?

no ill take a look

**Comment by SleepDaemon** [comment]
> Did you take a look at the [Troubleshooting Guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting#common-issues)?

Nope nothing worked
![image](https://user-images.githubusercontent.com/88533953/222784912-28d7a587-7547-41ba-9495-0e9ffdc842f9.png)
![image](https://user-images.githubusercontent.com/88533953/222784923-2f486e1a-61d8-4915-9b9b-c78a6372a4d2.png)

**Comment by SleepDaemon** [comment]
also going to the winget.exe location and try running it from there I get this
![image](https://user-images.githubusercontent.com/88533953/222785732-de225888-bc02-485b-b037-cef2e435153a.png)

**Comment by bh604** [comment]
I'm getting the same error after doing a system recovery. Any luck with this?

**Comment by SleepDaemon** [comment]
> I'm getting the same error after doing a system recovery. Any luck with this?

I'm gonna try registering it again as mentioned troubleshoot. I checked to see if the path was in the environment variable and it was. So if this doesn't fix it then idk what will.

**Comment by Trenly** [comment]
@sleepdaemon - Any luck?

**Comment by SleepDaemon** [comment]
Hi, ye I got it fixed but I can't remember what I did to fix it or even anything I did actually fixed it. Either I did something which I can't remember that fixed it or it just fixed itself overtime.
