### ISSUE TITLE
Package install locations should be remembered when updating

### ISSUE THREAD

**Issue by TCAtrevor** [microsoft/winget-cli#3045]
### Description of the new feature / enhancement

I have a package which I installed using the `--location` option to change its install directory. Whenever that package has an update, it will create a new installation in its default install directory instead of where I had originally chosen, unless I update it by itself to specify `--location` again. It would be highly convenient if WinGet could continue installing updates into the directory I originally installed a package to.

### Proposed technical implementation details

I believe WinGet should remember when you install a package using the `--location` option, and automatically pass it through again anytime it is updating the package unless you specify otherwise, like I currently have to.

**Comment by Trenly** [comment]
* Related to #1002

**Comment by denelon** [comment]
Duplicate of #1002
* #1002
