### ISSUE TITLE
Winget List - add machine-parseable output

### ISSUE THREAD

**Issue by apcsb** [microsoft/winget-cli#3051]
### Description of the new feature / enhancement

#1155 
Winget List is useful for scripting to check if a package is present, but current output is human-oriented.
I often need to check if a specific package version is installed, or what version of a specific package is installed.
Currently I have to parse text output, which is not fun, given the variable column names/widths etc.

**Proposal:** Add an option to display the results as CSV/JSON/XML/anything else machine readable vs human-readable for scripting. This is in addition to what export offers. Export currently dumps a lot, requires a file and takes a lot of time. This should run quickly (a single package and dump to stdout (for capture/redirection).

### Proposed technical implementation details

`winget list <query> --out-json`
returns a JSON object into stdout (for redirection / capture)

Optionally `--out-csv`, `--out-xml` etc.

**Comment by stephengillie** [comment]
This would be very useful for projects like:
* https://github.com/microsoft/winget-pkgs/pull/96846

**Comment by Trenly** [comment]
Have you tried using the PowerShell Cmdlets? They should provide the output as a powershell object
