### ISSUE TITLE
Wrong .NET SDK version number when using winget upgrade

### ISSUE THREAD

**Issue by CanePlayz** [microsoft/winget-cli#3070]
### Brief description of your issue

`winget list` does correctly detect the versions of the .NET SDK that I have installed by using the manifest field which matches version from Apps & Features with actual version numbers.

```
PS C:\Users\jjpfs> winget list dotnet

Name                             ID                     Version Source
-----------------------------------------------------------------------
Microsoft .NET SDK 7.0.201 (x64) Microsoft.DotNet.SDK.7 7.0.201 winget
Microsoft .NET SDK 6.0.406 (x64) Microsoft.DotNet.SDK.6 6.0.406 winget
```

However, when I run `winget upgrade`, it offers an update and mixes up .NET 6 and 7 as you can see by the different name and ID.

```
PS C:\Users\jjpfs> winget upgrade

Name                             ID                     Version   Available Source
----------------------------------------------------------------------------------
Microsoft .NET SDK 6.0.406 (x64) Microsoft.DotNet.SDK.7 < 7.0.100 7.0.201   winget
```

### Steps to reproduce

Have different .NET SDKs installed and run `winget upgrade`

### Expected behavior

Show the right version number and don't offer an update

### Actual behavior

Shows wrong version number and offers an update

### Environment

```shell
Windows 11
Winget v1.5.441-preview
```

**Comment by CanePlayz** [comment]
Oh, sorry, I didn't find those other issues because I was searching for .NET SKD and both of those issues talk about the runtime.

**Comment by CanePlayz** [comment]
> No worries. We've identified a fix for a few scenarios. I'm trying to map "Area-Matching" to help group these related issues together so we can see which ones are addressed.

👍

**Comment by CanePlayz** [comment]
Also seems to happen for a PowerShell Preview, currently my PowerShell shows:

```
PowerShell 7.4.0-preview.2
PS C:\Users\jjpfs> winget upgrade
Name                             ID                           Version   Available Source
----------------------------------------------------------------------------------------
PowerShell 7-preview-x64         Microsoft.PowerShell.Preview > 7.3.8.0 7.4.0.2   winget
Microsoft .NET SDK 6.0.407 (x64) Microsoft.DotNet.SDK.7       < 7.0.100 7.0.202   winget
```

**Comment by mdanish-kh** [comment]
> Also seems to happen for a PowerShell Preview, currently my PowerShell shows:

This would be fixed once these PRs get merged
- https://github.com/microsoft/winget-pkgs/pull/99811
- https://github.com/microsoft/winget-pkgs/pull/99812
- https://github.com/microsoft/winget-pkgs/pull/99813

**Comment by CanePlayz** [comment]
> > Also seems to happen for a PowerShell Preview, currently my PowerShell shows:
> 
> This is another issue and would be fixed once below PRs get merged. I'll mark this comment as off-topic once these get merged; if you still have problems I'd say we open a new issue for it.
> 
> - https://github.com/microsoft/winget-pkgs/pull/99811
> - https://github.com/microsoft/winget-pkgs/pull/99812
> - https://github.com/microsoft/winget-pkgs/pull/99813
> 
> 
> 

Okay, thanks 👍

**Comment by CanePlayz** [comment]
A bit more information:

When running `winget list` it recognized all SDKs as `Microsoft.DotNet.SDK.7`:

```
Microsoft .NET SDK 8.0.100-preview.6.23330.1… Microsoft.DotNet.SDK.7                               > 7.0.306        8.0.100-previ… winget
Microsoft .NET SDK 7.0.306 (x64)              Microsoft.DotNet.SDK.7                               7.0.306                         winget
Microsoft .NET SDK 6.0.412 (x64)              Microsoft.DotNet.SDK.7                               < 7.0.100        7.0.306        winget
```

**Comment by MagicAndre1981** [comment]
@CanePlayz same like for me with the [.net runtime](https://github.com/microsoft/winget-cli/issues/3004#issuecomment-1640479337) where list shows IDs correctly, but upgrade command treats 6 runtime as 7 runtime.

**Comment by CanePlayz** [comment]
> @CanePlayz same like for me with the [.net runtime](https://github.com/microsoft/winget-cli/issues/3004#issuecomment-1640479337) where list shows IDs correctly, but upgrade command treats 6 runtime as 7 runtime.

Yeah, it's all just a big mess right now and all over the place.

**Comment by CanePlayz** [comment]
Interestingly, it works on my Surface:

```
Microsoft .NET SDK 8.0.100-preview.6.23330.1… Microsoft.DotNet.SDK.Preview                              8.0.100-preview.6… winget
Microsoft .NET SDK 7.0.306 (x64)              Microsoft.DotNet.SDK.7                                    7.0.306            winget
Microsoft .NET SDK 6.0.412 (x64)              Microsoft.DotNet.SDK.6                                    6.0.412            winget
```

**Comment by CanePlayz** [comment]
It might be worth looking into more feedback, cause it seems to be working on my PC now too! Did you change anything with those packages that could have done this?

**Comment by rkl110** [comment]
The problem seams to be the way you installed the SDK/Runtime. If you used winget in works fine, if you used the installer (https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.20-windows-x64-installer) you get an update 'error'.

**Comment by MagicAndre1981** [comment]
for me the issue with Dotnet Runtime is still the same even after this weeks patchday.

**Comment by CanePlayz** [comment]
> for me the issue with Dotnet Runtime is still the same even after this weeks patchday.

How about now?

**Comment by MagicAndre1981** [comment]
> > for me the issue with Dotnet Runtime is still the same even after this weeks patchday.
> 
> How about now?

[since November 2023 ](https://github.com/microsoft/winget-cli/issues/3004#issuecomment-1811155145)and installing .net 8 it works for me on that 1 laptop that suffered the issue for over 1 year.

**Comment by CanePlayz** [comment]
Great, then I will close this issue.

**Comment by CanePlayz** [comment]
> > Great, then I will close this issue.
> 
> doe it work for you now, too for the SDKs?

Yup, been working for quite a while now

**Comment by MagicAndre1981** [comment]
> 
> Yup, been working for quite a while now

just noticed that on one system I see the SDK mismatch again where 6.0.419 is detected as Mirosoft.DotNet.SDK.7 and offers 7.0.406 as upgrade
