### ISSUE TITLE
Add a website wich lists all the packages as wel as instructions on how to add community packages.

### ISSUE THREAD

**Issue by NicTanghe** [microsoft/winget-cli#308]
PS. fucking finaly dont you guys think this is  years overdue ?

**Comment by megamorf** [comment]
This repo's README.md points you to https://github.com/microsoft/winget-pkgs/ which contains all manifests as well as steps on how to submit your own. This issue can be closed.

**Comment by chausner** [comment]
There is already community-built package catalogue online: https://winstall.app/

**Comment by jerrythiesen** [comment]
> This repo's README.md points you to https://github.com/microsoft/winget-pkgs/ which contains all manifests as well as steps on how to submit your own. This issue can be closed.

Agreed. Should be closed. Also comment is Off-Topic and not productive.

**Comment by NicTanghe** [comment]
the repo's repo points to a github page with all the packages wwich is not at all like a website you can search for packages on like the aur or chocolatey has. closed becouse it zas solved by chausner's answer.
