### ISSUE TITLE
GitHub Repository bug: "Used by:" button show it like gmock

### ISSUE THREAD

**Issue by KindDragon** [microsoft/winget-cli#310]
I removed the template because it GitHub template related.

GitHub show for that I can install install using command `dotnet add package gmock` (???)
![изображение](https://user-images.githubusercontent.com/224272/82735846-73cb1680-9d2d-11ea-8677-c46807dd4ecd.png)

**Comment by denelon** [comment]
@KindDragon I'm not sure exactly what changed, but it looks like this may have been resolved.
