### ISSUE TITLE
Applications Installed via Winget takes 45-minutes to install

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/winget-cli#3108]
### Brief description of your issue

Many applications upgraded via Winget in Microsoft Terminal takes between 30 to 45 minutes to install.
Why does it take so long.
I have taken the same application by manually downloading the update version from its original website download section,
and installed it and it only takes around 5 minutes to install.

But when I update / upgrade applications via Winget, it takes an enormous amount of time.
Very very frustrating.

### Steps to reproduce

Update any application via Winget.

### Expected behavior

Be installed Quickly without having to wait 45 minutes for any application to install.

### Actual behavior

Applications taking an enormous amount of time to install or update is between 30 to 45 minutes.
Its extremely annoying.

### Environment

```shell
Windows Package Manager v1.4.10173
```

**Comment by Trenly** [comment]
Can you provide any of the winget logs from performing an update?

Is the delay mostly before or after it says "Starting package install. . ."?

Have you tried changing the [download settings](https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#downloader) to see if `wininet` or `do`makes a difference?

Is it with all packages, or just certain ones? It could be a CDN issue if its just certain packages.

**Comment by stephengillie** [comment]
Hi @RobFosterNYC,

Upgrade is 3 parts:
- Identify: A list of installed applications is gathered, and their versions compared to the public manifests, to determine if any upgrades are available. This step should take less than 30 seconds - is this taking a significant amount of time? 
- Download: Are the packages downloading in a normal amount of time? Does it take about as long to download the package through a browser as through the package manager? They use the same means so should take the same time. 
- Install: Again, this is using the same means to install package upgrades as running the upgraded package's installer, so should take about the same length of time. Are packages taking significantly longer to install? 

The answers to these questions will help to identify which part of the system to focus further diagnosis.

**Comment by RobFosterNYC** [comment]
Hi @Trenly  and @stephengillie 
Sorry for the late reply, its a work week, hectic morning and extended stupid work meetings.

Anyways, @Trenly  I only have the following in the settings, 
`
{
    "$schema": "https://aka.ms/winget-settings.schema.json",

    // For documentation on these settings, see: https://aka.ms/winget-settings
    // "source": {
    //    "autoUpdateIntervalInMinutes": 5
    // },
}
`

I will add some settings feature from the page you linked as soon as I can, to see if something changed for the better, soon.
I didn't know you could do that.  Must have blew right by me without me paying attention.  Anyways thanks for this info.


@stephengillie 

#1 - NO, The list comes up in around 30-seconds of it doing its thing.
#2 - 50% of the time its a bit slow when its downloading. It depends on the package.
#3 - Here is where I have to wait 30 to 45 minutes.

I have ample RAM on this particular system 32-GB and I am running NVme SSD by Samsung (990-Pro)
All my windows updated are updated.  I am running Windows 10. and my internet package is the 1GB/sec package.
So its very fast isp speeds.


.

**Comment by Smith-Steve** [comment]
Yea, this is definitely still a problem. I was beginning to loose faith. At least it looks like it finishes... eventually.

**Comment by denelon** [comment]
If anyone is still having this problem, could you try to change the "downloader" to "wininet" in `winget settings` and confirm if the behavior is different?

**Comment by mmpmendes** [comment]
Hello guys I still have this issue

**Comment by muddymind** [comment]
Hi! I have a similar issue but it's not related to the downloading part but rather running the installer downloaded.

For example, installing VC redist 2015 takes around 7-8min with winget but if I download it myself and run it manually (same installer downloaded from the same address) takes 1min at most. 

I noticed this also with Golang, firefox and several other packages.

This is being ran on an intel 13800h while completely idle and while running the installer via winget both the cpu usage and ssd load is quite low.

**Comment by jozefcifre** [comment]
The issue persists. It's taking over an hour just to install the latest pythonmanager.
