### ISSUE TITLE
Latest release is wrongly tagged

### ISSUE THREAD

**Issue by csholmq** [microsoft/winget-cli#311]
Super minor detail. But title says 0.1.41331 but the tag says 0.1.4331 :)

![bild](https://user-images.githubusercontent.com/1297882/82737371-fc978180-9d30-11ea-824f-6628f3420ae3.png)

**Comment by denelon** [comment]
Latest release is now https://github.com/microsoft/winget-cli/releases/tag/v0.1.41821-preview
