### ISSUE TITLE
Provide like `exclude` parameter

### ISSUE THREAD

**Issue by kkbruce** [microsoft/winget-cli#3113]
### Description of the new feature / enhancement

From https://github.com/microsoft/winget-cli/issues/3055

I don't want to upgrade to the latest version of the software, and I want to skip the upgrade of some software during the upgrade. I hope to provide parameters like `exclude` to specify that some software will not be upgraded until winget-cli itself solves the problem.

### Proposed technical implementation details

`winget upgrade --exclude xxxx --all`

**Comment by denelon** [comment]
Duplicate of #2339
