### ISSUE TITLE
P.S.A - CDN Infrastructure update

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#3114]
We're making some changes with our CDN infrastructure.

We do not anticipate any downtime, but we wanted to inform you for what is hopefully an "uneventful" event.

This is planned for ~April 3rd - April 4th~ April 10th.

**Comment by mvasquez** [comment]
Unfortunately, it seems like it is not an uneventful event. winget has been giving me the infamous "Failed in attempting to update the source: winget", message, and if I run a wget on https://cdn.winget.microsoft.com/cache/source.msix, it's returning RawContentLength as zero. After reading #2666, I checked the most current issues regarding the topic, and this is the one. Hence, I'm letting you know that there are issues out there with these CDN changes.

**Comment by denelon** [comment]
Thanks for reporting this. We will get a purge / reload running.

**Comment by mvasquez** [comment]
> @mvasquez we haven't made any of the planned changes yet. We've been working with our current CDN provider to address the zero-byte file issue. We are hopeful that the changes we're making will fully resolve the zero-byte issue. Do you know when IP address from the CDN provider is returning the zero-byte file? If so, we can manually force a flush and reset.

Sorry, it took me a bit to reply to this. But things look like they're working now. Thanks a bunch, for the corrective actions.

**Comment by zachcarp** [comment]
We, unfortunately, were unable to make the change on the 3rd or 4th. We are planning to make the changes today (5th).

**Comment by denelon** [comment]
We've decided to delay the change until April 10th. 
Additional logging and monitoring is being put in place, and we are doing some additional testing against the new alerting and monitoring before rolling the changes out.

**Comment by denelon** [comment]
We've applied the changes. Now we're waiting for the DNS information to propagate.
