### ISSUE TITLE
winget upgrade --all wont upgrade anything

### ISSUE THREAD

**Issue by elNino0916** [microsoft/winget-cli#3123]
### Brief description of your issue

When I try to upgrade all packages, it won't upgrade anything. I tried it on the preview release and the stable release.

### Steps to reproduce

Run winget upgrade --all

### Expected behavior

It should upgrade all packages

### Actual behavior

It is only displaying the available upgrades

### Environment

```shell
Windows Package Manager (Preview) v1.5.441-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1485
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.441.0
```

**Comment by denelon** [comment]
@elNino0916 can you run with "--verbose-logs" and share them so we can see what is happening?

**Comment by elNino0916** [comment]
I re-installed windows and now its working.
