### ISSUE TITLE
Transient error - `0x80070490 : Element not found`; Required clean install of winget

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#3124]
### Brief description of your issue

`winget upgrade` results in `0x80070490 : Element not found.`

Tried forcing a source update and a source reset - no change. Manually removed source appx and tried again - no change. Installed a previous version of winget - no change.

Occurred only on 1 of my 2 machines.

Completely uninstalled winget and reinstalled - issue resolved

### Steps to reproduce

`winget upgrade`

### Expected behavior

Upgrades to be listed

### Actual behavior

`0x80070490 : Element not found.`

[WinGet-2023-03-30-13-43-15.254.log](https://github.com/microsoft/winget-cli/files/11114996/WinGet-2023-03-30-13-43-15.254.log)
[WinGet-2023-03-30-13-40-09.034.log](https://github.com/microsoft/winget-cli/files/11114997/WinGet-2023-03-30-13-40-09.034.log)

### Environment

```shell
Tested with 1.4.10173 and 1.5.441-preview.

PS D:\Git\winget-pkgs> winget --info
Windows Package Manager (Preview) v1.5.441-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.2728
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.441.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Lutra-Fs** [comment]
Meets the same issue here, but I am in dev build of Windows. How can I do a clean install for winget? Many thanks.

**Comment by Skeb1ns** [comment]
I have 1 or 2 clients in my environment with the same behavior.

"Completely uninstalled winget and reinstalled - issue resolved"

What did you do to perform a reinstall of winget? I can't find anything about this online.
