### ISSUE TITLE
[Pinning] - Usage of `--id` should bypass installed package check

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#3141]
### Description of the new feature / enhancement

The current implementation of pinning checks to try and map to an installed package before adding the pin. Since the pin only requires the package ID and source list, when `--id` is provided, there should be no need to attempt the mapping. The given ID can be added to the pinning database directly.

This will help when there are side-by-side installs or matching issues which may prevent pinning due to multiple packages found.

### Proposed technical implementation details

This behavior probably should not be default, but enabled through settings.

```json
"pinning" : {
    "directIdAddition" : true
}
```

**Comment by florelis** [comment]
@Trenly Do you think this would still be needed after #3167?

**Comment by Trenly** [comment]
> @Trenly Do you think this would still be needed after #3167?

Yes, because #3167 still fails when trying to pin Microsoft.Teams due to multiple strong matches when the Teams Machine Wide Installer is present

**Comment by florelis** [comment]
I ended up including this in #3167, so I'm closing the issue. Feel free to re-open if I missed anything.
