### ISSUE TITLE
Publish PowerShell Modules to PowerShell Gallery

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#3176]
### Description of the new feature / enhancement

When releases are made available to the public, the Microsoft.WinGet.CLI PowerShell module should be published to the PowerShell Gallery. This issue is intended to track the remaining build automation to handle publishing to the PowerShell Gallery.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-cli/issues/3176#event-11171900155

@denelon, https://www.powershellgallery.com/packages?q=Microsoft.WinGet.CLI solely returns https://www.powershellgallery.com/packages/Microsoft.WinGet.Client/. Am I merely too impatient?
