### ISSUE TITLE
winget tries to install new powershell but the version is already installed 

### ISSUE THREAD

**Issue by pleabargain** [microsoft/winget-cli#3179]
### Brief description of your issue

![image](https://user-images.githubusercontent.com/640846/234052259-0f5fe7f4-d27a-4397-ad7b-63a5e1563f78.png)

powershell 7.3.4 is already installed but winget thinks it is PS7.3.2

### Steps to reproduce

winget upgrade --all

### Expected behavior

Identify correct version of software

### Actual behavior

misreading PS version #

### Environment

```shell
C:\Users\denni>winget --info
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2846
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by denelon** [comment]
Can you share the output from `winget list powershell`?

I'm curious what versions are reported.

**Comment by gwojan** [comment]
@denelon I have a similar issue except with the latest PowerShell Preview.

```
winget list powershell
Name                       Id                                Version      Available Source
------------------------------------------------------------------------------------------
PowerShell 7-x64           Microsoft.PowerShell              7.3.4.0                winget
PowerShell 7-preview-x64   Microsoft.PowerShell.Preview      > 7.3.8.0    7.4.0.2   winget
```

I have PowerShell 7.4-preview2 installed but winget doesn't seem to understand that. My guess is winget is confused by remnants of a previous update via Windows Update. I mistakenly enabled the `Update via Windows Updates` bits only to find out Windows Update updates PowerShell via a 32bit `setup.exe` instead of a `.msi` file. Thoughts?

**Comment by mdanish-kh** [comment]
@gwojan The PowerShell Preview issue is different and being tracked in 
- https://github.com/microsoft/winget-cli/issues/3110

**Comment by tomfranken** [comment]
Same issue:

![image](https://user-images.githubusercontent.com/13257026/234383590-a948c1f2-8949-4662-b3d9-8d867a881901.png)

**Comment by pleabargain** [comment]
Winget apparently can't even get to the other installs due to c++ bug interfering!

![image](https://user-images.githubusercontent.com/640846/235834594-9120e7a2-ab34-4d29-bb43-5756b9730619.png)

**Comment by pleabargain** [comment]
Still show that PS needs to upgrade.
![image](https://github.com/microsoft/winget-cli/assets/640846/479ee9ef-da98-4e65-9cef-412bc7d8d450)

here's the output for
winget list powershell

![image](https://github.com/microsoft/winget-cli/assets/640846/4a690834-4a30-43d5-bd68-e5aa562fe4ff)

I can't seem to uninstall the old powershell either:
![image](https://github.com/microsoft/winget-cli/assets/640846/e800714f-4b80-4061-ac82-7cc561a0066d)

**Comment by mdanish-kh** [comment]
@pleabargain Looks like you have two versions of PowerShell installed side-by-side and WinGet still has some work to do on how to handle those properly (https://github.com/microsoft/winget-cli/issues/2129). For now, you'll have to manually uninstall `PowerShell 7.3.2.0-x64` from `appwiz.cpl` (or Apps&Features)

**Comment by Trenly** [comment]
[Policy] Side-By-Side

**Comment by denelon** [comment]
We've been working on the side-by-side scenarios. You could try the latest release and enable the experimental feature on:
* https://github.com/microsoft/winget-cli/releases/tag/v1.8.924-preview

Please provide feedback at:
* https://github.com/microsoft/winget-cli/discussions/4281

**Comment by denelon** [comment]
WinGet 1.8 now has better support for side-by-side packages. Is this problem still happening?
