### ISSUE TITLE
Installing different package version displays latest version number

### ISSUE THREAD

**Issue by Rover656** [microsoft/winget-cli#318]
# Brief description of your issue
When you install a package while explicitly stating a version (with -v/--version) it will display "Found [package name] [Latest version] [Package id]" instead of "Found [package name] [selected version] [package id]".
# Steps to reproduce
- Install any package with a desired version lower than the latest (In my case I was installing AdoptOpenJDK 11.0.7).
- Observe the "Found" message, it displays an incorrect version number.

# Expected behavior
The correct version number should be displayed in the "found" message.

# Actual behavior
The latest version number is displayed instead. This can be confusing to see when selecting a different package version.
![image](https://user-images.githubusercontent.com/20544390/82759214-ccf58180-9de3-11ea-82b6-d155173f8ef9.png)

# Environment

```none
[winget --info]
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18363.836
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
```

**Comment by Trenly** [comment]
@denelon - I believe this has been resolved
```
PS C:\Windows\system32> winget show Badlion.BadlionClient --versions
Found Badlion Client [Badlion.BadlionClient]
Version
-------
3.12.0
3.11.0
3.8.0
3.6.4
|
PS C:\Windows\system32> winget install Badlion.BadlionClient --version 3.8.0
Found Badlion Client [Badlion.BadlionClient] Version 3.8.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://client-updates-cdn77.badlion.net/Badlion%20Client%20Setup%203.8.0.exe
                                  0.00 B /  126 MB
```
