### ISSUE TITLE
Microsoft.WinGet.Client depends on PowerShell 7

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#3183]
According to the [Quick Start Guide](https://github.com/microsoft/winget-cli/tree/master/src/PowerShell/Microsoft.WinGet.Client#quick-start-guide) in https://github.com/microsoft/winget-cli/tree/master/src/PowerShell/Microsoft.WinGet.Client, the module requires Powershell and not Windows PowerShell. But the minimum version that is specified in the PowerShell Gallery is 5.1.0. (which is the Windows PowerShell version)

![image](https://user-images.githubusercontent.com/75471378/234150480-c0030d1e-670d-44c8-a595-e71f10a522ba.png)
![image](https://user-images.githubusercontent.com/75471378/234150291-7330f655-e84e-436e-9936-c5ea4135f43e.png)

So what really is the minimum required version?

_Originally posted by @rollingmoai in https://github.com/microsoft/winget-cli/discussions/3182#discussioncomment-5714035_

**Comment by denelon** [comment]
Microsoft.WinGet.Client does need PowerShell 7 today. We need to update the module to properly reflect the requirements. We also need to remove some of the crescendo metadata as the module had to be manually rewritten to expose rich PowerShell objects.

**Comment by gwojan** [comment]
> Microsoft.WinGet.Client does need PowerShell 7 today. We need to update the module to properly reflect the requirements. We also need to remove some of the crescendo metadata as the module had to be manually rewritten to expose rich PowerShell objects.

Wow! That's really cruel and I don't even use Windows PowerShell 5.1. 😉

**Comment by ethanbergstrom** [comment]
To piggy-back onto this - I'm not able to switch my [OneGet](https://github.com/ethanbergstrom/winget) or [AnyPackage](https://github.com/AnyPackage/AnyPackage.WinGet) providers over to the official PowerShell module due to both ecosystems supporting Windows PowerShell 5.1 and Desired State Configuration 1.1.

Which, in turn, means I have to continue maintaining my Crescendo module, and all the hoop-jumping involved with [parsing and cleaning up WinGet's often-mangled CLI output](https://github.com/ethanbergstrom/Cobalt/blob/v0.4.0/src/Cobalt.ps1#L48-L113).

I was hoping to archive that project, but doesn't look like I can yet. Are there plans to add PS 5.1 compatibility to the module?

**Comment by denelon** [comment]
We're still working through the matrix of requirements to get to support for Windows PowerShell. I'd like to be able to support it, but we ran into several complex scenarios getting everything to work in both Windows PowerShell and PowerShell 7 using the same module.

**Comment by byjrack** [comment]
Any updates on a strategy to support both 5.1 and 7+?  If supporting in the same module is too challenging what about supporting modules for 5 and for 7?

Been trying to look into using it with our Company Portal for evergreen installs of machine scoped apps, but it's getting tougher and tougher to build the requirements for a given Program.  I need to carry a ps7 bootstrap, the client psm, and make sure that nuget etc are in good shape.  Definitely possible, but hoping to make things more factory for our team.

**Comment by piotrminkina** [comment]
It would be very nice if there would be WinGet support for PowerShell 5.1, which is installed by default with Windows. Such good support is currently lacking.

**Comment by jszabo98** [comment]
Saying "Minimum PowerShell version 5.1.0" is very confusing.

**Comment by byjrack** [comment]
I have not tested it thoroughly, but for the moment it looks like I have all the major cmdlets working in 5.1 so looking forward to deprecating my wrapper and get this going.

**Comment by byjrack** [comment]
Found a big gotcha.... even with starting powershell in MTA it looks like these cmdlets in 5.1 won't function in SYSTEM context.  Won't be able to use it in our use case which is orchestration via Intune IME.  There are some apps that we are doing in User, but lots that we publish are still dependent on admin rights for some feature and given we can't handle UAC in these cases we will need to stick with the wrapper module.  

I keep hoping the Intune team will consider supporting generic package manager sources vs only Store, but doesn't seem to be any interest in that thus far.

**Comment by byjrack** [comment]
@denelon just to set my own expectations.  Will there be work done to make these cmdlets work in SYSTEM context or is the  apartment and context handling with COM just too complicated to do securely?  Completely get if not, but trying to keep some hope alive that I can smooth out our Intune orchestration.
