### ISSUE TITLE
When downloading the software installation package from the HTTP server, do you support multi-thread download and resumable download?

### ISSUE THREAD

**Issue by masx200** [microsoft/winget-cli#319]
# Description of the new feature/enhancement

When downloading the software installation package from the HTTP server, do you support multi-thread download and resumable download?

Does it support HTTP2 and HTTP over quic protocols?

# Proposed technical implementation details (optional)

**Comment by megamorf** [comment]
Relates to:
* #151
* #225

**Comment by denelon** [comment]
Duplicate of #225
