### ISSUE TITLE
Settings being wiped

### ISSUE THREAD

**Issue by Virakal** [microsoft/winget-cli#3200]
### Brief description of your issue

Every few days my settings file resets to the default (the JSON schema link and commented example setting) and all of my pins are cleared, even when I re-enable the pinning feature.

### Steps to reproduce

Unfortunately I'm not sure what triggers this. Possibly an upgrade? I just notice when I run `winget upgrade` and my pinned packages show up again.

### Expected behavior

Settings file and configured pins persist forever.

### Actual behavior

Settings are getting reset and configured pins are being deleted.

### Environment

```shell
Windows Package Manager (Preview) v1.5.441-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2846
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.441.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by denelon** [comment]
@Virakal the pinning feature is still experimental. We're still developing the feature and are likely to have one or two more breaking changes before it's made stable. Can you try with the latest preview version and share verbose logs with the scenario when this happens?

**Comment by denelon** [comment]
You can either enable verbose logs as default in your settings or you can run the command with "--verbose-logs" and optionally you can run with "--logs" to have the directory with logs open if you're in a solid repro state.

Otherwise, you can just run `winget --logs` and it will open the folder so you can grab the "second" newest log.
