### ISSUE TITLE
Add support for script-based installers

### ISSUE THREAD

**Issue by upintheairsheep** [microsoft/winget-cli#3223]
### Description of the new feature / enhancement

Add support for bat, vbs, and powershell scripts to be available as installers (or portable programs). 
Example powershell installer: https://github.com/ipasimulator/ipasim/releases/download/v1.0.1/ipasim-build-v1.0.1-2023-01-01.zip

Please give me an example bash and vbs installer

![image](https://user-images.githubusercontent.com/43690204/236370770-b6e01e15-9d77-47f8-8e78-fabc1f0104d0.png)

### Proposed technical implementation details

It's really simple to just run the program.

**Comment by Masamune3210** [comment]
Scripts are explicitly refused due to the security issues they can bring. I don't think this is likely to change any time soon

**Comment by denelon** [comment]
Originally from https://devblogs.microsoft.com/commandline/winget-install-learning/

---
* No scripts during install – something that we completely agreed with and don’t allow with MSIX
* Rich manifest definition within GitHub – the power of being open combined with rich declarative meta data about the app is so important to meet goal \# 1
* Support all types of Windows applications installers
* Seamless updates for applications in the repository
