### ISSUE TITLE
winget sees 5 upgrades only manages 3

### ISSUE THREAD

**Issue by pleabargain** [microsoft/winget-cli#3229]
### Brief description of your issue

5 upgrades 
only managed
![image](https://user-images.githubusercontent.com/640846/236735442-99f457c1-7e36-4d38-ac71-2f3f6afec136.png)

### Steps to reproduce

start winget upgrade --all

### Expected behavior

all packages updated

### Actual behavior

some packages updated

### Environment

```shell
C:\Users\denni>winget --info
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2846
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
```

**Comment by denelon** [comment]
I suspect the VC Redistributable and the PowerShell had already been upgraded and installed on the system. The behavior of WinGet for side-by-side packages still has work to be done.

**Comment by pleabargain** [comment]
> 

Thanks for responding.

**Comment by denelon** [comment]
WinGet 1.8 has better support for side-by-side packages. Is this problem still happening?
