### ISSUE TITLE
Can't Install GIT

### ISSUE THREAD

**Issue by est66** [microsoft/winget-cli#324]
Multiple app have the id git.git --> impossible to install Git

**Comment by megamorf** [comment]
Try `winget install --id git.git`

**Comment by helpimnotdrowning** [comment]
`winget install -e --name Git` ended up working for me.

**Comment by markaldridge** [comment]
or `winget install Git --exact`

**Comment by billxc** [comment]
-e works fine for me. Seems that a friendly reminder is needed for such situation.

**Comment by Jalalx** [comment]
I had the same problem then I found the `-e` or `--exact` option. I think `-e` is should not be required when the `--id` option is provided.

**Comment by est66** [comment]
Thanks for theses responses 👌
