### ISSUE TITLE
Upgrade loop

### ISSUE THREAD

**Issue by igorskyflyer** [microsoft/winget-cli#3248]
### Brief description of your issue

Hello, I've been facing an upgrade loop for quite some time. I have a Microsoft Visual C++ 2015-2019 Redistributable (x86) installed on my machine and `winget` detects an available upgrade for it (and confusingly it offers an x64 upgrade not x86? 🧐)

Anyway, here are some screenshots:

<div align="center">
	<img src="https://github.com/microsoft/winget-cli/assets/20957750/574e99f0-3570-498b-8363-a1f89e38696f" alt="Before upgrade">
	<p>Showing the available upgrade here</p>
	<img src="https://github.com/microsoft/winget-cli/assets/20957750/b07757e3-f442-45ad-b3ea-636cde470d1e" alt="After upgrade - fail">
	<p>Throwing an error that the upgrade isn't available</p>
	<img src="https://github.com/microsoft/winget-cli/assets/20957750/cfcd6554-1e38-47c8-a6b8-b6bfd73f857d" alt="After upgrade - success">
	<p>Manages to install the upgrade</p>
</div>

Even after a successful upgrade the upgrade is being offered again and again and again, hence the name of this issue. 😅

### Steps to reproduce

1. Install Microsoft Visual C++ 2015-2019 Redistributable (x86),
2. check for upgrades,
3. do the upgrade.

### Expected behavior

The upgrade should be completed successfully and not detected as upgradable.

### Actual behavior

The upgrade keeps getting detected as available.

### Environment

```shell
Windows Package Manager: v1.4.10173
Windows: Windows.Desktop v10.0.19045.2965
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by denelon** [comment]
Thanks for sharing. We have a few things we're working on with the label "Area-Matching". There is some work in progress with the latest preview.

**Comment by igorskyflyer** [comment]
Thanks for the input. 😉
Great to hear it's already in the works. 👍🏼

**Comment by Trenly** [comment]
[Policy] Area-Matching
[Policy] Side-by-side

**Comment by denelon** [comment]
We've been working on the side-by-side scenarios. You could try the latest release and enable the experimental feature on:
* https://github.com/microsoft/winget-cli/releases/tag/v1.8.924-preview

Please provide feedback at:
* https://github.com/microsoft/winget-cli/discussions/4281

**Comment by denelon** [comment]
The side-by-side support is now available in WinGet 1.8. Is this loop still happening?

**Comment by igorskyflyer** [comment]
I'll test it out today and get back to you. 🤓

**Comment by igorskyflyer** [comment]
Weirdly, now it doesn't show any upgrades for the C++ redistributable(s). Tried it a few times, with and without the `--include-unknown` flag and even after a restart.

<div align="center">
	<img src="https://github.com/microsoft/winget-cli/assets/20957750/c62187ba-9345-4775-9fc6-962b0136d561" alt="Igor Dimitrijević (igorskyflyer) uploaded an image">
</div>

**Comment by denelon** [comment]
Is this issue safe to close then?

**Comment by igorskyflyer** [comment]
> Is this issue safe to close then?

I guess so, will re-open if I notice that behavior again, thank you.
