### ISSUE TITLE
Spec says `SystemAppId` is required, but it doesn't appear to be.

### ISSUE THREAD

**Issue by ptorr-msft** [microsoft/winget-cli#325]
The [v0.1 spec](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv0.1.md) says:

> SystemAppId is a required field...

but none of the examples use it and the validator doesn't require it.

**Comment by wjk** [comment]
This feature will be used by the uninstallation feature (when and if it is ever implemented). This string is the name of the key where the app writes its uninstall data for Apps & Features to use (except for MSIX packages, which use a different value here). If this field becomes optional, then it will be possible (and, honestly, far too easy) to write packages that cannot be uninstalled using winget; the admin can only remove them manually through Settings. Hope this helps!

**Comment by sredna** [comment]
It is technically legal for a installer to generate a unique uninstall subkey name each time it is installed. Probably not something worth supporting but it could in theory happen.

A more important issue is, if .zip packages are ever supported they are not going to have a uninstaller so SystemAppId must be optional for this package type or support a special "zip" value that causes winget to create a uninstall entry (pointing to winget --uninstallzip "c:\installdir" or a custom generated batch file or whatever).

**Comment by denelon** [comment]
The manifest schema has been substantially changed with the 1.0 version. This issue is now obsolete.
