### ISSUE TITLE
WINGET: Failed to open the source; try removing and re-adding it An unexpected error occurred while executing the command:

### ISSUE THREAD

**Issue by PepeMedin4** [microsoft/winget-cli#326]
# Brief description
I try to use the winget but this have errors, maybe connection errors.

I got the next error massage:
`Failed to open the source; try removing and re-adding it An unexpected error occurred while executing the command:`

# Steps to reproduce
When I try to execute the command:
`winget search code
`
I got the next error massage:
`Failed to open the source; try removing and re-adding it An unexpected error occurred while executing the command:
`

And this other command:
`winget source add --name Otro https://winget.azureedge.net/cache`

Send this error message:
`
Adding source:
  Otro -> https://winget.azureedge.net/cache
An unexpected error occurred while executing the command:
`

```
PS C:\> ping winget.azureedge.net                                                                                       
Haciendo ping a cs9.wpc.v0cdn.net [2606:2800:157:1508:1539:174:1a75:1191] con 32 bytes de datos:
Respuesta desde 2606:2800:157:1508:1539:174:1a75:1191: tiempo=151ms
Respuesta desde 2606:2800:157:1508:1539:174:1a75:1191: tiempo=31ms
Respuesta desde 2606:2800:157:1508:1539:174:1a75:1191: tiempo=10ms
Respuesta desde 2606:2800:157:1508:1539:174:1a75:1191: tiempo=10ms

Estadísticas de ping para 2606:2800:157:1508:1539:174:1a75:1191:
    Paquetes: enviados = 4, recibidos = 4, perdidos = 0
    (0% perdidos),
Tiempos aproximados de ida y vuelta en milisegundos:
    Mínimo = 10ms, Máximo = 151ms, Media = 50ms

```

# Environment

`winget --info`
```
Windows Package Manager v0.1.41331 Vista previa
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18363.836
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

Links:
  Privacy Statement: https://aka.ms/winget-privacy
  License agreement: https://aka.ms/winget-license
  3rd Party Notices: https://aka.ms/winget-3rdPartyNotice
  Homepage:          https://aka.ms/winget
```

**Comment by megamorf** [comment]
@PepeMedin4 Does your network require a proxy server to access websites?

**Comment by PepeMedin4** [comment]
@megamorf thanks for your answer, but no, I don't require a proxy server to access websites.

**Comment by eduardodx** [comment]
@PepeMedin4, the same happened here with me when I was using the default DNS provided by my ISP. I changed the DNS at the OS level (network prefs) and everything worked as expected. 
I see that you are able to ping the server, but winget still does not work. Maybe there is something blocking this specific application (some rule, maybe).

**Comment by PepeMedin4** [comment]
Thanks  @eduardodx. What DNS are using?
I am using  8.8.8.8 and 8.8.4.4 as DNS, restore to the ISP DNS but I have the same error.

Maybe some rule like you said. Pls let me know your DNS Provider.
Regards

**Comment by PepeMedin4** [comment]
Thanks @eduardodx. What DNS are using?
I am using 8.8.8.8 and 8.8.4.4 as DNS, restore to the ISP DNS but I have the same error.

Maybe some rule like you said. Pls let me know your DNS Provider.
Regards

**Comment by eduardodx** [comment]
You're welcome!

I'm using NextDNS. With the ISP DNS I cann't even ping the azure url.

**Comment by PepeMedin4** [comment]
Solved:
@eduardodx, @megamorf the error was that I just need TLS 1.2.
In my Internet options for Windows 10 was check SSL 3.0 and TLS1.0.
**I changed this configuration a SSL 3.0 and TLS 1.2.**
And ready:
```
PS C:\WINDOWS\system32> winget search code
Name                   Id                             Version  Matched
--------------------------------------------------------------------------------------------------------
Visual Studio Code     Microsoft.VisualStudioCode     1.45.1   Command: code
Cppcheck               Cppcheck.Cppcheck              2.0      Tag: code
Packet Sender          NagleCode.PacketSender         6.2.3
K-Lite Codec Pack Mega CodecGuide.K-LiteCodecPackMega 15.4.8
Code::Blocks           Codeblocks.Codeblocks          20.03
vim                    vim.vim                        8.2.0754 Tag: code editor
HandBrake              thehandbraketeam.handbrake     1.3.2    Tag: handbrake video converter transcoder
```
Thanks a lot!!

**Comment by huangsijun17** [comment]
Me too. All SSL is turned on.

**Comment by PepeMedin4** [comment]
Hi @ huangsijun17
Is your Microsoft Store working? I remember trying to fix this, when I found the solution. Maybe it is another Windows error. Luck!!

**Comment by captainhook** [comment]
I just managed to fix this by installing the pre-release from https://github.com/microsoft/winget-cli/releases
