### ISSUE TITLE
Lack of information regarding "pin" 

### ISSUE THREAD

**Issue by pearson** [microsoft/winget-cli#3263]
### Brief description of your issue

While performing a `winget upgrade -r`, the latest v1.4.10173 release gave me the output `1 package(s) is pinned and needs to be explicitly upgraded.` That package was `Discord.Discord`.

The issue is the lack of documentation regarding the pin feature, both in the application and at [learn.microsoft.com](https://learn.microsoft.com/en-us/windows/package-manager/). After some searching, it's clear that pin is a feature for the dev build. However, "pin" can clearly pop up in the stable build, as it did for me, so some documentation of the feature seems appropriate.

**Comment by denelon** [comment]
@pearson had you tried a preview version of WinGet with pinning, or has this machine only had the 1.4 version? I think this may be a bug if you've never had a newer version.

**Comment by denelon** [comment]
@florelis can you take a look at this one?

**Comment by pearson** [comment]
@denelon , this machine is a relatively new Windows 11 install (a couple of weeks) with no other WinGet installs. It's the version of WinGet that is installing with the current (as of about three weeks ago) version of the Windows 11 ISO from the Microsoft site -- I did not manually install WinGet.

I'd assumed that some pinning code was intentionally in the stable 1.4 release. If not, it definitely seems like a bug.

**Comment by denelon** [comment]
There is some code there, but it should be behind the feature toggle. This is clearly a bug :(

We will have to get a fix out.

**Comment by Trenly** [comment]
> There is some code there, but it should be behind the feature toggle. This is clearly a bug :(
> 
> We will have to get a fix out.

Its probably due to how the manifest field `RequiresExplicitUpgrade` is handled, since when pinning was added as experimental the explicit upgrade behavior was rolled into `pinnedByManifest`

**Comment by pearson** [comment]
> So I don't think it's an issue with the code, but rather with our docs to explain what that means.

That's pretty much it. When I saw the `is pinned and needs to be explicitly upgraded` message, my first thought was that it would be useful to pin a version of an app myself. That led to a bunch of searches for more information, and a bunch of time wasted. 😄 I was surprised to not find any documentation, outside of GitHub discussions about the dev version.

**Comment by florelis** [comment]
@pearson
I don't know if/where there are docs about the `RequireExplicitUpgrade` flag. So, to make up for it a bit of explanation:

That flag can be put in a manifest to make `winget upgrade --all` ignore the package, but you can still upgrade it explicitly with `winget upgrade <package>`. I think the main use case is stuff that auto-updates, so you don't want to have winget upgrading it since it will do it itself anyways. Another case could be when an update is destructive, like if it throws away user settings; not sure if this actually happens with any package.

You will be able to pin a version of a package yourself, once v1.5 is stable and assuming we make pinning not experimental. I imagine that's when we would publish more docs about it.

**Comment by pearson** [comment]
Thanks, @florelis . It definitely sounds like a useful feature.

**Comment by denelon** [comment]
I completely forgot to link to the [spec](https://github.com/microsoft/winget-cli/blob/master/doc/specs/%23476%20-%20Package%20Pinning.md) for pinning.

**Comment by denelon** [comment]
https://devblogs.microsoft.com/commandline/winget-configuration-preview/#winget-pinning

Once this feature is stable in the 1.5 release, we will update Microsoft Learn.

**Comment by denelon** [comment]
https://learn.microsoft.com/en-us/windows/package-manager/winget/pinning
