### ISSUE TITLE
Ability to exclude from winget upgrade --all

### ISSUE THREAD

**Issue by AliqQim** [microsoft/winget-cli#3268]
### Description of the new feature / enhancement

I would like to be able to exclude certain applications from being affected by this command: "winget upgrade --all"

### Proposed technical implementation details

"winget exclude ~path~"

**Comment by mdanish-kh** [comment]
Duplicate of #476

Pin a package feature is available in the preview version of WinGet. Please upgrade to latest preview version of WinGet from https://aka.ms/getwingetpreview, enable [pinning in experimental features](https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#pinning) and give `winget pin` command a try

**Comment by Trenly** [comment]
See above

**Comment by rastislavbodorik** [comment]
All related issues included this one has been closed with circular duplication reference without resolution
