### ISSUE TITLE
App Installer is locked down and winget is not available

### ISSUE THREAD

**Issue by nom4d72** [microsoft/winget-cli#3269]
### Brief description of your issue

I cannot use the winget command and winstore won't allow me to install or uninstall App Installer and if I try to install the msix package it'll give a warning that it's outdated that I ignored but as soon as installation starts, it crashes.

### Steps to reproduce

about 18 hours ago everything was fine but at some point msstore must have updated App Installer and now winget CLI won't work
after the commands it returns False
```
Set-Location -Path ('{0}\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe' -f $env:ProgramW6432)
PS C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.19.10173.0_x64__8wekyb3d8bbwe

Test-Path -Path '.\AppInstallerCLI.exe'  // False
```
the msix package gives a warning that it's outdated that I ignored but as soon as installation starts, it crashes. I tested multiple times.
### Expected behavior

to winget cli command prompts work
to msix to install

```
Set-Location -Path ('{0}\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe' -f $env:ProgramW6432)
PS C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.19.10173.0_x64__8wekyb3d8bbwe

Test-Path -Path '.\AppInstallerCLI.exe'  // To RETURN True
```

### Actual behavior

not working and basically under lockdown

### Environment

```shell
i can't execute winget --info. the exe is simply not there.
```

**Comment by florelis** [comment]
> `Test-Path -Path '.\AppInstallerCLI.exe'  // False`
I think it's now called `winget.exe`?

How are you trying to call winget?

**Comment by nom4d72** [comment]
> > `Test-Path -Path '.\AppInstallerCLI.exe'  // False`
> 
> I think it's now called `winget.exe`? How are you trying to call winget?

AppInstallerCLI.exe is what it's called in windows packages where it is installed.

look if i run winget.exe in terminal I get:
```
winget.exe: The term 'winget.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
in red

**Comment by ItzLevvie** [comment]
> AppInstallerCLI.exe is what it's called in windows packages where it is installed.

In previous versions of WinGet it was called `AppInstallerCLI.exe`

In newer versions of WinGet it is called `winget.exe`

You're running PowerShell so you need to type `.\winget.exe` instead of `winget.exe`

```powershell
PS C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.20.1361.0_x64__8wekyb3d8bbwe> winget.exe
winget.exe: The term 'winget.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

[general]
  The command "winget.exe" was not found, but does exist in the current location.
  PowerShell does not load commands from the current location by default (see 'Get-Help about_Command_Precedence').

  If you trust this command, run the following command instead:
    ➤ .\winget.exe
```

This is how it should look like:
```powershell
Set-Location -Path ('{0}\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe' -f $env:ProgramW6432)
.\winget.exe
```

**Comment by denelon** [comment]
@nom4d72 are you still having this problem with the latest version of WinGet?
