### ISSUE TITLE
Clarify the values allowed in the  ElevationRequirement field

### ISSUE THREAD

**Issue by joaompinto** [microsoft/winget-cli#3286]
After reading https://github.com/microsoft/winget-cli/issues/1284 and look into the spec I am not able to understand the elevatesSelf value purpose.

The "elevatesSelf" value is being set for installers which do need admin privileges (eg. Python.Python.3.11), this is counter intuitive to the "scope: User" .

- elevationRequired - is clear: should be filtered out on scope User
- elevationProhibited -  is clear: should be used with system/admin level privileges, should be filtered out on scope Machine
- elevatesSelf - ??

https://github.com/microsoft/winget-cli/blob/5a97e26ba3efb6b1f0d5997ec9de7d16b8fa52b9/schemas/JSON/manifests/v1.1.0/manifest.installer.1.1.0.json#L427-L435

**Comment by Trenly** [comment]
ElevationRequirement and Scope are only loosely related. 

* elevationRequired - Must be run from a shell that is running in an administrative context (e.g - Admin user using powershell/terminal/cmd with "Run as Administrator")
* elevationProhibited - Must be run from a shell that is not running in an administrative context
* elevatesSelf - If called from a non-administrative context, will request elevation. If called from an administrative context, may or may not request elevation.

Some applications require elevation to install in the user scope, others do not. Some will install to the machine scope without elevation, others will not

**Comment by denelon** [comment]
Looks like I didn't add the enumeration to:
https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.4.0/installer.md
