### ISSUE TITLE
Administrator permission request not issued

### ISSUE THREAD

**Issue by igorskyflyer** [microsoft/winget-cli#3288]
### Brief description of your issue

When upgrading the `Mp3tag.Mp3tag` application, after the application has been downloaded successfully and the installer is starting I get a message that an administrator request will prompt so the installer could proceed.

<div align="center">
	<img src="https://github.com/microsoft/winget-cli/assets/20957750/fb91ad9c-d589-4f84-91e7-fe59d53bb492" alt="Mp3Tag, WinGet, Terminal">
</div>

The prompt never occurs, thus, the installer fails to complete.

### Steps to reproduce

1. Install an old version of Mp3Tag (`Mp3tag.Mp3tag`),
2. Try to upgrade with `winget`.

### Expected behavior

The application should prompt for administrator permissions and proceed with installing.

### Actual behavior

The application fails to install because of insufficient privileges.

**NOTE**: when running the Windows Terminal itself as Administrator, the application does install successfully but the elevation prompt should appear when running in a non-administrator Terminal.

### Environment

```shell
Windows: Windows.Desktop v10.0.19045.3031
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by mdanish-kh** [comment]
That was my bad for mistakenly suggesting changing elevationRequirement from `elevationRequired` to `elevatesSelf` in the latest manifest PR. Looks like the installer only allows unattended installation for machine scope (all users) that requires elevation and there doesn't seem to be a silent InstallerSwitch for user scope. More detail here https://github.com/microsoft/winget-pkgs/issues/15863#issuecomment-853299100. I've created a PR to revert the change

**Comment by igorskyflyer** [comment]
@mdanish-kh, that was fast! 👏🏼😀
