### ISSUE TITLE
Add hidden winget complete command to enable tab-completion

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/winget-cli#331]
# Description of the new feature/enhancement

The `dotnet` cli tool from the .NET Core SDK has a hidden [complete command](https://github.com/dotnet/sdk/blob/b1223209644d900702287faea8e9b71f95ec49f8/src/Cli/dotnet/commands/dotnet-complete/CompleteCommand.cs) that works like this:

```
PS> dotnet complete --position 2 "re"
remove
restore
store
```

This can be hooked into environments like PowerShell to enable command/parameter completion for dotnet.exe e.g.:

```powershell
Register-ArgumentCompleter -Native -CommandName dotnet -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    dotnet complete --position $cursorPosition $commandAst | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
    }
}
```

# Proposed technical implementation details (optional)

I would like to see winget implement a hidden `complete` command that would provide completions for top-level commands e.g.:  install, show, source, search, hash, validate.  And then for each command, it should provide parameter completions e.g. `winget install --id Git.Git --s` should return `--source` and `--silent`.

**Comment by megamorf** [comment]
Relates to #146.

**Comment by rkeithhill** [comment]
Closing issue as this has been released, see [the doc](https://github.com/microsoft/winget-cli/blob/master/doc/Completion.md) for more details.
