### ISSUE TITLE
Cannot match id according to the shortest principle

### ISSUE THREAD

**Issue by lhy1024** [microsoft/winget-cli#333]
# Brief description of your issue

Cannot match id according to the shortest principle

# Steps to reproduce

![image](https://user-images.githubusercontent.com/19542290/82876175-f5f44e80-9f6a-11ea-9488-098e2a4ed7ae.png)

# Expected behavior

install successfully
# Actual behavior

cannot find out the correct one
# Environment
![image](https://user-images.githubusercontent.com/19542290/82876271-18866780-9f6b-11ea-8b9e-70c16b918843.png)

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
```

**Comment by lhy1024** [comment]
Although I can install it by `-e`, it is unfriendly for users.

**Comment by megamorf** [comment]
Please close this issue as this problem has been reported multiple times already:
* #133 
* #282
* #301
