### ISSUE TITLE
Ability to search for packages.

### ISSUE THREAD

**Issue by dustojnikhummer** [microsoft/winget-cli#334]
Add function to search for packages, similar to 

> choco find packagename

Example. I want to install Chrome.

> winget find chrome

and the result would be 

> found 3 packages
> chrome
> chrome-beta
> chrome-dev

**Comment by megamorf** [comment]
There is a search function already: `winget search [searchterm]`. Call `winget search --help` for optional parameters. This ticket can be closed.

**Comment by denelon** [comment]
As @megamorf pointed out, the "search" command has been implemented.
