### ISSUE TITLE
Command line alias not working?!

### ISSUE THREAD

**Issue by assarbad** [microsoft/winget-cli#3345]
### Brief description of your issue

This relates to https://github.com/microsoft/winget-pkgs/pull/109817

The issue is that the command line alias doesn't work.

### Steps to reproduce

Currently you need winget 1.4 and a local version of the manifest from https://github.com/microsoft/winget-pkgs/pull/109817

1. `winget install --manifest path\to\Rizin\Cutter\2.2.1`
2. wait for the installation to finish

### Expected behavior

After installation `cutter` should be executable and refer to the `cutter.exe` from the installed package.

### Actual behavior

The command line alias isn't accepted as executable.

```
D:\winget-pkgs\manifests\r\Rizin\Cutter>winget install --manifest 2.2.1
Found Cutter [Rizin.Cutter] Version 2.2.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "cutter"
Successfully installed

D:\winget-pkgs\manifests\r\Rizin\Cutter>cutter
'cutter' is not recognized as an internal or external command,
operable program or batch file.
```

This is equally true from PowerShell:

```
PS D:\winget-pkgs\manifests\r\Rizin\Cutter> cutter
cutter: The term 'cutter' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS D:\winget-pkgs\manifests\r\Rizin\Cutter> & cutter
&: The term 'cutter' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Environment

```shell
> winget --info
Windows Package Manager v1.4.11071
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3086
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.11071.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```
```

**Comment by assarbad** [comment]
No entry for `cutter.exe` inside `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths` or `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\App Paths` either!

And no corresponding app execution aliases:
![image](https://github.com/microsoft/winget-cli/assets/3238620/c5dacf95-0ecf-4009-a103-1d05952c0acc)

**Comment by denelon** [comment]
@assarbad we're not using App Execution Aliases for portable packages.
Depending on whether it was installed in user mode or administrator, and whether or not Developer Mode is enabled, there are a pair of different behaviors.

I'm not familiar with that package. Does the .zip file contain just the cutter.exe or are other files necessary for the package to run?

**Comment by Trenly** [comment]
It looks like the alias is added successfully, but it requires both linked DLL's and has a dependency on Microsoft Visual C++ 2015+

![image](https://github.com/microsoft/winget-cli/assets/12611259/3c8f96f8-5a40-45a5-b04b-b4f3154101de)

**Comment by kenvix** [comment]
You may need to check whether `C:\Users\USERNAME\AppData\Local\Microsoft\WinGet\Links` has been added to the PATH environment variable.
![image](https://github.com/microsoft/winget-cli/assets/4546175/60f7e2de-5bc4-468d-870e-823e9fba3d08)

Besides, I've noticed that when installing such portable software for the first time, winget automatically adds this environment variable, but does not refresh the system environment variable, so you need to manually refresh (open env settings and save as above) or restart your computer.

Also check whether there are symbolic links existing in the directory:
![image](https://github.com/microsoft/winget-cli/assets/4546175/6c4c1c6e-c736-4a90-99a7-1c0bda794da2)

**Comment by assarbad** [comment]
> @assarbad we're not using App Execution Aliases for portable packages. Depending on whether it was installed in user mode or administrator, and whether or not Developer Mode is enabled, there are a pair of different behaviors.
> 
> I'm not familiar with that package. Does the .zip file contain just the cutter.exe or are other files necessary for the package to run?

@denelon Sorry for the late response. Lost sight of this issue. There is a `cutter.exe`, but prior to @Trenly's remarks I didn't even realize it had this runtime dependency. That package is installed on practically all my machines.

I suppose this could be closed?! Feel free to reopen if I misjudged.
