### ISSUE TITLE
Installing Microsoft.Edge has bad UX

### ISSUE THREAD

**Issue by Bomret** [microsoft/winget-cli#335]
# Brief description of your issue
If a user wants to install the latest `Microsoft.Edge`, one would assume that this is done by `winget install Microsoft.Edge`, which is the exact ID. But this fails as winget seems to do a search first and by that also finds `Microsoft.EdgeDev` and `Microsoft.EdgeDev`. You have to pass in `winget install --exact --id Microsoft.Edge` which is not very intuitive. Specifiying the exact ID should be sufficient.

# Steps to reproduce
- run `winget install Microsoft.Edge`

# Expected behavior
Installation of `Microsoft.Edge` starts.

# Actual behavior
- installation does not start
- winget lists `Microsoft.Edge`, `Microsoft.EdgeDev` and `Microsoft.EdgeBeta` as it seems to be confused which one to take.

# Environment

```none
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18363.836
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
```

**Comment by megamorf** [comment]
@Bomret Thanks for reporting this problem. However, I'd recommend you close this issue as this problem has been reported multiple times already:

#133
#282
#301

**Comment by Bomret** [comment]
@megamorf sorry, I didn't find those issues. Will do!
