### ISSUE TITLE
Support licenses for Microsoft Store Apps (offline installation)

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#3354]
### Description of the new feature / enhancement

The XML namespace for license files is:
`xmlns="urn:schemas-microsoft-com:windows:store:licensing:ls"`

As we work towards:
* https://github.com/microsoft/winget-cli/issues/658
* https://github.com/microsoft/winget-cli/issues/578

We need a mechanism for using WinGet to install packages requiring the license in an environment where external connectivity is limited.

This primarily applies to UWP (Universal Windows Platform) Apps. This is likely something that would apply only to MSIX as an installer type and would be excluded by policy from the WinGet community repository. For enterprise use, there would either be a local manifest able to specify the license to apply, or a private REST source able to serve the URL to the license.

**Comment by sammiie** [comment]
To support licenses for Microsoft Store Apps (offline installation) as described in issue #3354, where external connectivity is limited, here are proposed technical implementation details:

1. Integrate License Handling in WinGet:

Enhance WinGet to include functionality for handling license files during app installations. This includes recognizing and processing licenses associated with UWP apps.
2. License File Format:

Define and document the format for license files. Use the XML namespace provided in the issue description: xmlns="urn:schemas-microsoft-com:windows:store:licensing:ls". Ensure that the format supports all necessary licensing information.
3. Offline License Manifests:

Allow for the creation of offline license manifests that specify the license files to be used during app installation. These manifests can be created manually or generated by enterprise IT administrators.
4. License Storage:

Develop a mechanism for securely storing license files locally on the target machine or within an organization's network. Encryption and access controls should be considered to protect license files.
5. Integration with MSIX Packages:

Ensure that this license handling mechanism primarily applies to MSIX packages, as they are the standard for UWP apps. Implement support for offline license installation specifically for MSIX packages.
6. Offline Installation Flow:

Modify the WinGet installation flow to check for the presence of a local license manifest or a designated license file for the app being installed. If found, use the license during installation.
7. License URL Retrieval from Private Sources:

For enterprise scenarios, provide a mechanism to retrieve license URLs from private sources (e.g., a private REST API). This allows organizations to manage and distribute licenses internally.
8. Command Line Options:

Extend the WinGet command line options to allow users to specify the location of the license manifest or license files during installation. For example, winget install <app_name> --license-manifest <path_to_manifest>.
9. Error Handling:

Implement error handling mechanisms to gracefully handle situations where the required license files are missing or invalid.
10. Documentation and Examples:
- Create comprehensive documentation and examples for IT administrators and developers to understand how to create license manifests, manage license files, and perform offline installations using WinGet.

11. Integration with Group Policies:
- Consider integrating this feature with Group Policies (GPO) to allow centralized management of licenses and offline installations within an enterprise environment.

12. Testing and Validation:
- Thoroughly test the license handling feature, including scenarios with limited external connectivity, to ensure that it functions as expected and maintains security standards.

13. Integration with Enterprise Deployment Tools:
- Ensure compatibility and integration with common enterprise deployment and management tools, such as Microsoft Endpoint Configuration Manager (SCCM).

14. User Education:
- Provide educational resources to help IT administrators and users understand how to use this feature effectively in both online and offline scenarios.

By implementing these technical details, WinGet can effectively support licenses for Microsoft Store Apps during offline installations, catering to enterprise environments with limited external connectivity while maintaining security and compliance.

**Comment by pl4nty** [comment]
Sorry to necro, was this ever implemented? I can't find where to pass the license.xml to WinGet with a self-hosted source (REST or preindexed). It would also help if WinGet can handle dependencies like `Dependencies.zip`, they're currently a pain in environments without access to the Store
