### ISSUE TITLE
winget should refresh the process env vars

### ISSUE THREAD

**Issue by SteveL-MSFT** [microsoft/winget-cli#3359]
### Description of the new feature / enhancement

It's a bit annoying that after installing a package, I have to restart the shell so that PATH (or other env vars) get updated.  Ideally, winget should just refresh the process env vars based on system/user env var changes.

**Comment by denelon** [comment]
Take a look at:
* https://github.com/microsoft/winget-cli/issues/549

We're looking at a few scenarios related to the path, and there is discussion and a possible workaround as well as some design work on how we might achieve this.

**Comment by denelon** [comment]
We're currently working on the dependency flow:
* https://github.com/microsoft/winget-cli/issues/2939

**Comment by mdanish-kh** [comment]
I would say this duplicates:
- #3077

Similar discussion at #222

**Comment by denelon** [comment]
Duplicate of #3077
