### ISSUE TITLE
Can't install PowerShell

### ISSUE THREAD

**Issue by TomBrien** [microsoft/winget-cli#336]
# Brief description of your issue

I can't install PowerShell due to duplicate IDs. I think this might in part be due to PowerShell core changing name to PowerShell (I may be wrong). In part this is related to #292 but due to the duplicate IDs I see no way of selecting the desired package. as `-v <version number>` seems to be ignored

# Steps to reproduce

1. Run `winget install powershell` returns:

# Expected behavior

PowerShell 7.0.1 installed

# Actual behavior

```
Multiple apps found matching input criteria. Please refine the input.
Name               Id                           Version
---------------------------------------------------------------
PowerShell         Microsoft.PowerShell         7.0.1
Powershell Core    Microsoft.Powershell         7.0.0
PowerShell-Preview Microsoft.PowerShell-Preview 7.1.0-preview.3
```
Attempting to specify the desired version via `winget install PowerShell -v 7.0.1` gives the same output

Specifying the `Id` rather than the `Name` via ` winget install Microsoft.PowerShell -v 7.0.1` once again just produces the list

# Environment

```none
[winget --info]
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18363.836
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
```

**Comment by megamorf** [comment]
@TomBrien Thanks for reporting this problem. However, I'd recommend closing this issue as this problem has been reported multiple times already:
* #133 
* #282
* #301 

What you are looking for as an immediate solution is the `--exact` (`-e`) parameter until the user experience of the winget commands has been improved.

**Comment by TomBrien** [comment]
My bad. cheers

**Comment by ebmarquez** [comment]
I'm seeing the same issue
```
C:\Users\emarq.REDMOND\Downloads\ICM> winget install --name PowerShell --id Microsoft.PowerShell
Multiple apps found matching input criteria. Please refine the input.
Name               Id                           Version
---------------------------------------------------------------
PowerShell         Microsoft.PowerShell         7.0.1
PowerShell-Preview Microsoft.PowerShell-Preview 7.1.0-preview.3
C:\Users\emarq.REDMOND\Downloads\ICM> winget install --name PowerShell --id Microsoft.PowerShell -v "7.0.1"
Multiple apps found matching input criteria. Please refine the input.
```

**Comment by megamorf** [comment]
@ebmarquez This issue has already been closed and a solution can be found in my reply above as well as in the issues that I've linked to.
