### ISSUE TITLE
Unable to uninstall somes package

### ISSUE THREAD

**Issue by MusaSSH** [microsoft/winget-cli#3362]
### Brief description of your issue

WinGet is unable to uninstall some packages I installed but it's able to install others.

I give an example of packages I'm unable to uninstall in the bottom fields and one of the packages I'm able to install and uninstall is Task.Task. I'd also be glad to know how to manually uninstall those packages during the time that WinGet has issues. Uninstalling them through Windows settings is redirecting me to winget uninstall command in PowerShell.

### Steps to reproduce

In my reproduce, I'll give examples from Genymobile.scrcpy and Gyan.FFmpeg as I can't uninstall them from my system.
- Run `winget install scrcpy`
- Check if that package now exists at `%LOCALAPPDATA%\Microsoft\WinGet\Packages` as `Genymobile.scrcpy_Microsoft.Winget.Source_8wekyb3d8bbwe`
- Run `winget uninstall scrcpy`

### Expected behavior

Expecting uninstall command to actually work like in this example.
```
PS C:\Users\user> winget uninstall scrcpy
Found scrcpy [Genymobile.scrcpy]
Starting package uninstall...
Successfully uninstalled
```

### Actual behavior

Command output will stay like this for a very, very long and immeasurable time. --verbose option is not printing any info as well.
```
PS C:\Users\user> winget uninstall scrcpy
Found scrcpy [Genymobile.scrcpy]
Starting package uninstall...
```

### Environment

```shell
Windows Package Manager (Preview) v1.6.1573-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.23481.1000
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.1573.0

Windows 11 Dev Channel 23481
PowerShell 7.3.4
```

**Comment by mdanish-kh** [comment]
Duplicate of #3279

**Comment by mdanish-kh** [comment]
@MusaSSH You can find some workarounds in the original issue for temporary solution

**Comment by MusaSSH** [comment]
I'll try them, thanks.

**Comment by ririshi** [comment]
Very old issue, but if anyone else finds this: `scrcpy` includes `adb`. If you start scrcpy, it will start an adb daemon, which will keep running even after scrcpy exits. Trying to uninstall scrcpy with the adb server still running, will fail.

You can run `adb kill-server` to stop the adb server. Then run `winget uninstall Genymobile.scrcpy` again to successfully uninstall.
