### ISSUE TITLE
ability to change default installation directory

### ISSUE THREAD

**Issue by CozyPenguin** [microsoft/winget-cli#337]
# Description of the new feature/enhancement

I've got a secondary drive for data as my ssd isn't big enough to hold more than windows and a few other programs, I'd like to have the ability to choose to install my programs on the other drive.

# Proposed technical implementation details (optional)

I think a good way to implement this would be either

1. using a command like `winget --change-default-install-dir "D:\Program Files"` 
2. using a config file where you can specify the new installation directory.

if it was a flag it could also be used for changing the installation directory on a per-installation basis, e.g. `winget install terminal -o "D:\Program Files\Terminal"`

**Comment by megamorf** [comment]
Relates to:
* #201
* #241
* #239

**Comment by G0rocks** [comment]
These issues are similar: #201 , #489

**Comment by filipworksdev** [comment]
Probably a better choice would be `winget --default-location` since --location is used per package to change the install location.

**Comment by denelon** [comment]
@Copystrike noted in https://github.com/microsoft/winget-cli/issues/201#issuecomment-1218349796 this has been implemented in settings.
