### ISSUE TITLE
Repair-WinGetPackageManager does not handle missing Microsoft.UI.Xaml.2.7 or license

### ISSUE THREAD

**Issue by JohnMcPMS** [microsoft/winget-cli#3374]
### Description of the missing feature / enhancement

While it will handle installing the VCLibs dependency, it will not install Microsoft.UI.Xaml.2.7.  It will also not apply the license file.

I believe that the goal of `Repair-WinGetPackageManager` is to have a functioning winget at the end, so it should handle these scenarios as well.  The license will be automatically acquired if the machine is connected and capable, but that may not always be the case.

### Proposed technical implementation details

The current best option is to follow the steps in #1861 , but it may be worth prodding the Xaml owners again for a direct release path.

Some investigation will be required for the license installation.  A quick check makes it seem like there is no direct, public API to add a license file.  It may require also allowing for `Repair-WinGetPackageManager -AllUsers` or similar so that `Add-AppxProvisionedPackage` can be used which will take in the license file.

**Comment by msftrubengu** [comment]
Fixed by #3423
