### ISSUE TITLE
[New Feature]: Update WinGet to use UI.XAML 2.8

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#3380]
### Description of the new feature/enhancement

Keeping dependencies current is generally a good idea.

It would also help resolve:
* https://github.com/microsoft/winget-pkgs/issues/108419

**Comment by A9G-Data-Droid** [comment]
Question: Why would a command line utility call anything from UI.Xaml?

Statement: A package manager needs to be able to run without any libraries or dependancies because that package manager is used to manage all libraries and dependencies. Consider making it self-contained.

**Comment by florelis** [comment]
> Why would a command line utility call anything from UI.Xaml?

It doesn't. But winget is packaged along DesktopAppInstaller (the UI that shows up when you double-click on an .msix/.msixbundle), which has a dependency on WinUI 2.7.

**Comment by A9G-Data-Droid** [comment]
That seems like an odd choice for a package manager that might be running on a headless server. 

These should be two completely different workflows:

1. Using `DesktopAppInstaller` to install 
2. Using `WinGet` to install 

When using workflow 2 I would expect all interaction to happen on the command line. Now on a system that has a desktop installed it would make sense for WinGet to be able to automatically install the `DesktopAppInstaller` when any package needs it, just like any other dependency.

**Comment by Trenly** [comment]
@denelon - This has been conpleted?

**Comment by huuub** [comment]
This problem is back... I installed xaml 2.8.6 but it needs 2.8???

**Comment by huuub** [comment]
I am using this as a workaround:
$progressPreference = 'silentlyContinue'
Write-Information "Downloading WinGet and its dependencies..."
Invoke-WebRequest -Uri https://aka.ms/getwinget -OutFile Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile Microsoft.VCLibs.x64.14.00.Desktop.appx
Invoke-WebRequest -Uri https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.8.6/Microsoft.UI.Xaml.2.8.x64.appx -OutFile Microsoft.UI.Xaml.2.8.x64.appx
Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx
Add-AppxPackage Microsoft.UI.Xaml.2.8.x64.appx
Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
