### ISSUE TITLE
Unable to tell between two products

### ISSUE THREAD

**Issue by jaweekes** [microsoft/winget-cli#339]
I attempted to install PowerShell, but it couldn't tell if I wanted "PowerShell", "PowerShell Preview", or "PowerShell Core", even when I tried the --version and the --id options.  It just couldn't figure out that I wanted only "PowerShell".

**Comment by megamorf** [comment]
@jaweekes Thanks for reporting this problem. However, I'd recommend closing this issue as this problem has been reported multiple times already:
* #133 
* #282
* #301 

What you are looking for as an immediate solution is the `--exact` (`-e`) parameter until the user experience of the winget commands has been improved.

**Comment by zachcarp** [comment]
Duplicate of #282
