### ISSUE TITLE
Did you change the winget list effect? It doesn't seem to show upgradable installed packages

### ISSUE THREAD

**Issue by dong-lufei** [microsoft/winget-cli#3390]
Now how do I know if the 30 or 40 packages I installed have a new version to upgrade

**Comment by robinmalik** [comment]
`winget --info`

**Comment by Trenly** [comment]
As far as I know, nothing has changed with how the default behavior of the list command works.

You can always use `winget upgrade` to list available upgrades

**Comment by denelon** [comment]
WinGet list currently only displays the available version when an update is available.

Duplicate of #1155
* #1155
