### ISSUE TITLE
Winget list dont show available version

### ISSUE THREAD

**Issue by Ramshu** [microsoft/winget-cli#3420]
### Brief description of your issue

When I use the `winget list` command, it should show two version columns, the current version on the system and the one available in the winget repositories. Currently it only shows me the version present in the system.
![image](https://github.com/microsoft/winget-cli/assets/13966796/1becaa1b-556e-4b7b-825e-dc719a300a23)

### Steps to reproduce

Use `winget list` command

### Expected behavior

It should show the version available for download.

### Actual behavior

Doesn't show version available in winget repositories

### Environment

```shell
Administrador de paquetes de Windows v1.5.1572
Windows: Windows.Desktop v10.0.19045.3155
Arquitectura del sistema: X64
Paquete: Microsoft.DesktopAppInstaller v1.20.1572.0
```

**Comment by ItzLevvie** [comment]
`winget list` will only show the `Available` column when there are updates available for a package.

I compared your `winget list` output to the `winget` source; and all of the packages that you have installed are up-to-date. They are the latest versions when compared to the package repository.

**Comment by Ramshu** [comment]
> `winget list` will only show the `Available` column when there are updates available for a particular package.
> 
> I compared your `winget list` output to the `winget` source; and all of the packages that you have installed are up-to-date. They are the latest versions you have installed when compared to the package repository.

I assumed that it works as you say... but a few hours ago I used winget list and it didn't show me the available versions, then I used the command winget upgrade --all and I update 4 applications.

**Comment by Ramshu** [comment]
> `winget list` will only show the `Available` column when there are updates available for a particular package.
> 
> I compared your `winget list` output to the `winget` source; and all of the packages that you have installed are up-to-date. They are the latest versions you have installed when compared to the package repository.
> 
> WinGet takes a look at the version numbers from Control Panel and compares them to the package repository, so even though `AIMP.AIMP`, `Bitdefender.Bitdefender`, and `MediaArea.MediaInfo.GUI` are outdated in the package repository, they are marked as latest updates in your `winget list` output because the version you have installed is higher than what's currently available in the package repository.

It seems that in the end you were right, I tried to undo [a fix I made for hddllftool](https://github.com/microsoft/winget-cli/issues/1356#issuecomment-1625263654) and the available version appears. Thank you very much and sorry for the inconvenience.
![image](https://github.com/microsoft/winget-cli/assets/13966796/73605509-db8a-4868-940f-068248c65544)
