### ISSUE TITLE
Cleanup old log files

### ISSUE THREAD

**Issue by florelis** [microsoft/winget-cli#3434]
### Description of the new feature / enhancement

(Assuming we're not doing it already and I just don't know about it...)

If we're not cleaning up old log files, the log folder will just keep growing in size indefinitely. I frequently delete old logs manually when I'm going through new logs, so I don't know how bad this can get wrt space.

**Comment by Trenly** [comment]
Cleans up after 7 days 

https://github.com/microsoft/winget-cli/blob/0a0eebfbf7322b3804f5f4c451bb08e9d017f687/src/AppInstallerCLICore/Core.cpp#L83-L84

https://github.com/microsoft/winget-cli/blob/0a0eebfbf7322b3804f5f4c451bb08e9d017f687/src/AppInstallerCommonCore/FileLogger.cpp#L107-L128

**Comment by Gijsreyn** [comment]
Hi @mdanish-kh. I know this issue has been closed for a while now, but do you know if this feature was also implemented in the winget-cli? I couldn't find it in the `settings.md`.

**Comment by Gijsreyn** [comment]
Thanks for the quick reply @mdanish-kh . I'll create an issue in this project :)

**Comment by Deadooshka** [comment]
It creates an empty log file on every winget start with higher log levels. Is it OK?
