### ISSUE TITLE
"The Server Certificate did not match any of the expected values"

### ISSUE THREAD

**Issue by DarylGraves** [microsoft/winget-cli#3444]
### Brief description of your issue

Just imaged my Windows 11 and ran Winget to install some applications. Every attempt to install an app returns this:

`Failed when searching source: msstore
An unexpected error occurred while executing the command:
0x8a15005e : The server certificate did not match any of the expected values.
`

Google tells me it's more likely SSL Interception but I have no SSL Interception configured. This laptop is going straight to the home WiFi. No VPN, No Ad-Blocker.

My Desktop Computer is running Winget fine, same Network, the only difference is the Desktop is on the LAN.

The only thing I've done "odd" is I tried to run Winget from a powershell script. Is there a T&C you need to accept for MS Store before it'll work? If so, is there a way to bring it back up because I can't find it.

### Steps to reproduce

Fresh build of Windows 11 Home (22H2), OS Build 22621.1992 with all Windows Updates (tried restoring laptop to factory settings too)
Run `winget install $app`

### Expected behavior

I expected the app to install.

### Actual behavior

`Failed when searching source: msstore
An unexpected error occurred while executing the command:
0x8a15005e : The server certificate did not match any of the expected values.
`

### Environment

```shell
Windows: Windows.Desktop v10.0.22621.1992
System Architecture: X64
Package: Microsoft.DesktopAppInstaller: V1.19.10173.0
```

**Comment by DarylGraves** [comment]
Ok I've just found the issue. Choosing to factory reset Windows 11 from the Control Panel, even when choosing the option to download all the files from the internet, installs v1.4.10173 which I now understand is broken... 

Weird as my machine is saying it's fully 100% up to date on Windows Updates and yet I'm still on v1.4 whereas My desktop is on v1.5.

I'll leave this open in case this is something you weren't aware of - It sounds like winget is potentially broken for anyone on a new machine?

**Comment by Trenly** [comment]
Because of how windows installation works on a clean install, winget doesn’t register itself until after several of the other windows components. The Microsoft Store update service *should* update the version of winget included in a clean install of Windows, but it may take some time as several other components also receive updates immediately upon install. So yes, it may be broken for a new install, but it should also fix itself if given sufficient time (at least in theory).

**Comment by Tataz2** [comment]
```
C:\Windows\system32>winget -v
v1.5.2201
```

Cannot install any packages.
`Failed when opening source(s); try the 'source reset' command if the problem persists.`


`winget source reset` does not help.

If I install winget by command
`Add-AppxPackage -Path https://cdn.winget.microsoft.com/cache/source.msix`
```
The version is still the same,
C:\Windows\system32>winget -v
v1.5.2201

```

but not I get an error:
```
Failed in attempting to update the source: winget
Failed when searching source: msstore
An unexpected error occurred while executing the command:
0x8a15005e : The server certificate did not match any of the expected values.
```
