### ISSUE TITLE
Add 'ReleaseDate' property to package manifest

### ISSUE THREAD

**Issue by donid** [microsoft/winget-cli#345]
The  'ReleaseDate' info could be very useful for users when browsing / searching for packages.
**Update**: to be more specific: this means the date on which the installer provider / software vendor released the installer/software for public download.

**Comment by SoftCreatR** [comment]
Well, in many (many!) cases, the release date is unknown, except if you are constantly watching for new releases.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/blob/2e693852fe7fae7f1643fdb799653645cdf0034f/schemas/JSON/manifests/v1.1.0/manifest.installer.1.1.0.json#L358-L362
