### ISSUE TITLE
winget list --upgrade-available suggests "Use --include-unknown to see all results"

### ISSUE THREAD

**Issue by TonyWhitley** [microsoft/winget-cli#3456]
### Brief description of your issue

e.g.
`winget list --upgrade-available`
`No installed package found matching input criteria.`
`5 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.`
but
`winget list --upgrade-available --include-unknown`
results in
```
Windows Package Manager v1.5.1881
Copyright (c) Microsoft Corporation. All rights reserved.

Argument name was not recognized for the current command: '--include-unknown'

### Steps to reproduce

winget list --upgrade-available --include-unknown


### Expected behavior

That it would list the unknown packages as well

### Actual behavior

An error message

### Environment

```shell
Windows Package Manager v1.5.1881
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2066
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1881.0
```

**Comment by stephengillie** [comment]
Some packages don't write version data to the Windows Registry, and so the WinGet package manager doesn't have version data to know if they need an upgrade.

**Comment by denelon** [comment]
Do you get the same output with `winget upgrade`?

**Comment by TonyWhitley** [comment]
Good question, no, the unknown ones are listed and will update (again, obviously winget can't tell they are already up to date)
```
winget upgrade --accept-package-agreements --accept-source-agreements --all --silent --include-unknown
Name                            Id                        Version Available Source
----------------------------------------------------------------------------------
Erlang OTP 24.0 (12.0)          Erlang.ErlangOTP          Unknown 26.0.1    winget
FlightGear v2019.1.1            FlightGear.FlightGear     Unknown 2020.3.18 winget
SpeedFan (remove only)          Almico.SpeedFan           Unknown 4.52      winget
FotoSketcher 3.80 (64-bit)      DavidTHOIRON.FotoSketcher Unknown 3.80      winget
MSI Kombustor 4.1.20.0 (64-bit) MSI.Kombustor.4           Unknown 4.1.20.0  winget
5 upgrades available.

**Comment by TonyWhitley** [comment]
I note that 
`winget list --help`
does not mention --include-unknown (fair enough) so I suppose the bug is that `winget list --upgrade-available` shouldn't suggest  `Use --include-unknown to see all results.` (though it would be useful thing to add to the `list` command).

**Comment by denelon** [comment]
Thanks for the responses. I think we should go ahead and "fix" the plumbing. I'm leaning towards making the --include-unknown work rather than removing it as an option. It's always exciting to see how customers want to use WinGet and I'd like to make sure things just work rather than forcing users to have to dig into docs and "learn the hard way".
