### ISSUE TITLE
Python 3.12 listed as update of Python 3.11

### ISSUE THREAD

**Issue by CanePlayz** [microsoft/winget-cli#3467]
### Brief description of your issue

`winget upgrade` falsely lists Python 3.12 as an update of Python 3.11

### Steps to reproduce

1. Install Python 3.11
2. Run `winget upgrade`

### Expected behavior

Don't show the 3.12 pre-release as an update, as it used to be

### Actual behavior

```
Name                   ID                 Version Available Source
------------------------------------------------------------------
Python 3.11.4 (64-bit) Python.Python.3.11 3.11.4  3.12.0b4  winget
```

### Environment

```shell
Windows: Windows.Desktop v10.0.25905.1000
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.21.1573.0
```

**Comment by radoslew** [comment]
Same problem here. It shows:
`Python 3.11.4 (64-bit)                         Python.Python.3.12                  < 3.12.0a1 3.12.0b4  winget`

**Comment by jrdodds** [comment]
Also seeing the same issue.

```
C:\Users\jrdodds>winget upgrade
Name                   Id                 Version Available Source
------------------------------------------------------------------
Python 3.11.4 (64-bit) Python.Python.3.11 3.11.4  3.12.0b4  winget
1 upgrades available.

```

First noticed the issue yesterday (July 23 ET).

**Comment by tigerinus** [comment]
Please fix this issue. Python should be upgradable only within the same patch version.

**Comment by CanePlayz** [comment]
My first action was to look into the manifest, but apparently the new 3.12 version was added the same way as the previous ones with which it worked, so the manifests don't seem to be the issue here I fear.

**Comment by stephengillie** [comment]
This might be due to a fix to another issue:
- https://github.com/microsoft/winget-pkgs/pull/113058/

**Comment by jrdodds** [comment]
The issue is fixed for me as well. Thanks

**Comment by ingframin** [comment]
I still get the same behavior where winget updates python 3.11 to 3.12b4
