### ISSUE TITLE
How to open Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle?

### ISSUE THREAD

**Issue by 4n70w4** [microsoft/winget-cli#347]
![image](https://user-images.githubusercontent.com/38257723/83018047-52b83d80-a02d-11ea-913a-6fa72943f350.png)

![image](https://user-images.githubusercontent.com/38257723/83017995-403e0400-a02d-11ea-9917-b5110e25d6d6.png)

**Comment by jedieaston** [comment]
You'll need to install the "App Installer" app from the Microsoft Store, and ensure that you can install applications from anywhere (Win+X -> Apps and Features -> Install apps from...)

Link to the store: https://www.microsoft.com/store/productId/9NBLGGH4NNS1

**Comment by denelon** [comment]
I think we may need some additional documentation on installation.

**Comment by 4n70w4** [comment]
How to install it without Microsoft Store?

```bash
(Get-WmiObject win32_operatingsystem).caption
```

```
Microsoft Windows 10 Enterprise LTSC
```

**Comment by joaoestevinho** [comment]
You can install it using PowerShell [Add-AppxPackage](https://docs.microsoft.com/en-us/powershell/module/appx/add-appxpackage?view=win10-ps) 

`Add-AppxPackage .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle`

**Comment by 4n70w4** [comment]
@joaoestevinho thanks!

**Comment by 4n70w4** [comment]
`Add-AppxPackage` don't work on LTSC 1809, requires the installation of 14.0.25426.0, but this version cannot be installed.
It turned out to be easier to upgrade to 2004 without LTSC.

https://github.com/microsoft/winget-cli/issues/356

**Comment by jvintzel** [comment]
would be good to see the whole error message, but I believe this is due to required dependency frameworks.  @denelon we should look into links to the framework packges.

**Comment by denelon** [comment]
All, we've updated the dependency frameworks. If your system has the "App Installer" you should be able to install any of the releases on the GitHub releases page to update the App Installer to the version with the Windows Package Manager included.
