### ISSUE TITLE
Auto scoop cleanup

### ISSUE THREAD

**Issue by xsm2** [microsoft/winget-cli#3472]
### Description of the new feature / enhancement

When updating scoop packages, older versions of the packages are not overwritten nor deleted, so you end up with multiple versions of the same package (for example I had 10 versions of llvm, 25gb in total). 

The command `scoop cleanup llvm` deletes every old version the package (I have used llvm as an example, it can be used with any other package), or as an alternative `scoop cleanup *` deletes every old version of every package. I think it would be nice to have an option in the scoop preferences to auto perform a cleanup every time an app it's instaled.

**Comment by denelon** [comment]
I think you meant to post this at https://github.com/ScoopInstaller/Scoop rather than WinGet.
