### ISSUE TITLE
Upgrade to schema draft 2020-12

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#3475]
### Description of the new feature / enhancement

Instead of draft-07 use draft/2020-12

https://json-schema.org/draft/2019-09/release-notes.html
https://json-schema.org/draft/2020-12/release-notes.html

### Proposed technical implementation details

"$schema": "https://json-schema.org/draft/2020-12/schema"

**Comment by Trenly** [comment]
[Policy] Area Manifest

**Comment by denelon** [comment]
Found this while digging in:
* https://github.com/microsoft/vscode/issues/187188

**Comment by Trenly** [comment]
I see; Fortunately, the schemas don't currently use the noted unsupported features

**Comment by denelon** [comment]
* https://github.com/microsoft/vscode/issues/165219

**Comment by gregsdennis** [comment]
What does ☝️ PR actually do?  What kind of support does it enable?
