### ISSUE TITLE
Port installed packages

### ISSUE THREAD

**Issue by fwd079** [microsoft/winget-cli#348]
# Port installed packages to winget

Good afternoon,

Since chocolatey is already installed at my Win10 and people like myself are keen to go winget way, are there any documentation/plans to _port_ package list across? 

# Proposed technical implementation details (optional)
Well for example:
```batch
winget port C:\PathToChocoPackageList
```

The winget then picks up the package list. adds to its own, I safely remove choco off my Windows and next time I use winget to upgrade all packages, then it upgrades all packages, including the ones I ported across from chocolatey.

Kind Regards.

**Comment by Trenly** [comment]
Winget works on all installed applications by default, assuming that it can correlate the installation data from the program to a package which is available in any of the configures sources - by default this is either the Microsoft Store or the winget-pkgs community repository. No porting needed!

If you install winget and run `winget list` it will show you all of the packages discovered on your system as well as their package identifier and which source they may map to
