### ISSUE TITLE
Winget PIN Didn't Prevent Winget UPGRADE

### ISSUE THREAD

**Issue by MrDamienJones** [microsoft/winget-cli#3484]
### Brief description of your issue

I expected the PIN command to stop installation of a newer version of an app.  During a trial where I pinned a version of Git then submitted an update command, the update happened with no pushback.  The pin then showed the newest version pinned as though that was the request I made to begin with.

### Steps to reproduce

PS C:\Users\Damien> winget pin add Git.Git
Found Git [Git.Git]
Pin added successfully

PS C:\Users\Damien> winget pin list
Name           Id                Version  Source Pin type
---------------------------------------------------------
Git            Git.Git           2.41.0.2 winget Pinning

PS C:\Users\Damien> winget update Git.Git
Found Git [Git.Git] Version 2.41.0.3
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/git-for-windows/git/releases/download/v2.41.0.windows.3/Git-2.41.0.3-64-bit.exe
  ██████████████████████████████  58.3 MB / 58.3 MB
Successfully verified installer hash
Starting package install...
The installer will request to run as administrator, expect a prompt.
Successfully installed

PS C:\Users\Damien> git -v
git version 2.41.0.windows.3

PS C:\Users\Damien> winget pin list
Name           Id                Version  Source Pin type
---------------------------------------------------------
Git            Git.Git           2.41.0.3 winget Pinning

### Expected behavior

Winget to not install the newer version of app (in this case Git)

### Actual behavior

Winget installed the newer version of Git with no reference to the pin

### Environment

```shell
Windows Package Manager v1.5.1881
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3208
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1881.0

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment]
I believe this is the default behavior of pins.

If you simply pin a package with no arguments, it is excluded from `winget upgrade --all` but can still be upgraded with `winget upgrade <package>`

If you want to block upgrades entirely, then you need to use `winget pin add <package> --blocking` to create a blocking pin, which will block all upgrades.

**Comment by MrDamienJones** [comment]
Dammit I looked all over the GitHub site and never thought to check Learn!  Thanks
