### ISSUE TITLE
Does `winget list` support a way to sort the results by name?

### ISSUE THREAD

**Issue by nbro** [microsoft/winget-cli#3504]
### Description of the new feature / enhancement

This looks like a very fundamental feature, but it doesn't seem to exist, or, at least, I didn't find it. Why wouldn't the results be shown in alphabetical order? Without that feature, `winget list` is quite painful because I need to look at all results to search for what I'm looking for.

### Proposed technical implementation details

I don't know. I'm not familiar enough with the code base right now.

**Comment by mdanish-kh** [comment]
Not currently. Please see https://github.com/microsoft/winget-cli/issues/1769 and also https://github.com/microsoft/winget-cli/issues/1155
