### ISSUE TITLE
Work or school account registration for preview

### ISSUE THREAD

**Issue by juchom** [microsoft/winget-cli#351]
# Description of the new feature/enhancement

When you go to the "Join the Windows Package Manager Insiders Program" page, it asks for the MSA used to sign in the store app. 

I gave my work or school account email, and I had no error. 

# Proposed technical implementation details (optional)

Could you please make clear if a work or school email works or if it has to be a real personal account (MSA) 

Thanks

**Comment by KevinLaMS** [comment]
We are using an office form in order to get the email.  There is no code behind to determine if the email is a true MSA or not.  The text does state that the email must be the MSA account.  It states:

"Please provide your Microsoft Account (MSA) that you use to sign in to the Microsoft Store app."
