### ISSUE TITLE
Make 100% sure localization of strings are correct, like Belgium (There are issue with the store package manager should avoid)

### ISSUE THREAD

**Issue by NicTanghe** [microsoft/winget-cli#352]
Here's an id

Make 100% sure you dont fuck up the ui for coutries where people speak diferent languages like Belgium (ur collegues fucked up bigtime with the store)

we dont really need a gui tho. could be nice as a full store replacer tho.

**Comment by megamorf** [comment]
The translations are created using the internal localizations services of Microsoft. If you have a concrete improvement then create a PR so that it can be forwarded to the team that is responsible. 

According to @JohnMcPMS  (see #240):
> The only option that I'm aware of is either using Feedback Hub, which will create a bug that can be routed internally, or something like a PR. The nice thing about the PR here is we can point the internal team to it, where they can see the string's symbolic name and I assume it makes the process easier.

**Comment by doctordns** [comment]
I believe it's Snover's 4th law:  Don't tell me I screwed up, tell me HOW I screwed up. If you want, hope, or expect traction,  you need to provide specific actionable feedback. So far I see nothing actionable and suggest you either add specifics or close this issue.

**Comment by TeddyAlbina** [comment]
> Here's an id
> 
> Make 100% sure you dont fuck up the ui for coutries where people speak diferent languages like Belgium (ur collegues fucked up bigtime with the store)
> 
> we dont really need a gui tho. could be nice as a full store replacer tho.

La belgique n'est pas un vrai pays  :p

**Comment by zachcarp** [comment]
@NicTanghe This looks like a duplicate of #238 

Is there anything in that issue that is not covered here?

**Comment by NicTanghe** [comment]
> 
> 
> > Here's an id
> > Make 100% sure you dont fuck up the ui for coutries where people speak diferent languages like Belgium (ur collegues fucked up bigtime with the store)
> > we dont really need a gui tho. could be nice as a full store replacer tho.
> 
> La belgique n'est pas un vrai pays :p

Bwa kweni ze vriend.
J`aime bien ici.

Well the Windows store is allot worse than using the language of my country it uses 
Dutch and French and English completely mangled for 0 reason since day 1 and 0 response on my tickets even tho everyone in Belgium has this issue but I'm not here to complain about that disaster. Obv Microsoft has seen the light because of vscode and using so much Linux to run their own systems now they have a better idea about how to improve their products.

This is just because i fear someone might reuse the same systems that were in place on the store. And warn them not to do that see screenshot.

![image](https://user-images.githubusercontent.com/13624265/83172127-693ac380-a117-11ea-9919-a7209af16415.png)

**Comment by NicTanghe** [comment]
![image](https://user-images.githubusercontent.com/13624265/83172479-f0883700-a117-11ea-8898-225dce842d11.png)

**Comment by NicTanghe** [comment]
> 
> 
> I believe it's Snover's 4th law: Don't tell me I screwed up, tell me HOW I screwed up. If you want, hope, or expect traction, you need to provide specific actionable feedback. So far I see nothing actionable and suggest you either add specifics or close this issue.

Sorry i thought everyone ws verry aware of the issue and never fixed it because all the places you could file bugs had a mention issues with the language being worked on.

**Comment by KevinLaMS** [comment]
tweaking title

**Comment by NicTanghe** [comment]
Thanks i should have done that myself but this issue has frustrated me since day 1 and i really wanted to use that store because it would have made softwaremanagment allot easier and that was a large part of my job. Now it seems like all problems will be fixed anyway.
