### ISSUE TITLE
[Sugestion] Donate to AppGet creator

### ISSUE THREAD

**Issue by franciscop** [microsoft/winget-cli#353]
# Donate to AppGet

It seems like WinGet gets many of the core ideas, file format, even code structure [from AppGet](https://github.com/appget/appget), but the original developer of that library @kayone has been taken unfair advantage of (personally, not license-wise). Whether this has been intentionally or a breakdown of communication remains to be seen.

Microsoft claims to have changed and to be better, so my suggestion is to donate generously to the project creator and credit him appropriately. He is well welcomed in the Developer community and the way that Microsoft has handled this [has made a large dent on some developer communities](https://news.ycombinator.com/item?id=23331287).

[Source for the claim](https://keivan.io/the-day-appget-died/)

# Proposed technical implementation details (optional)

```
[@microsoft] ======= $$$ ======> [@kayone]
```

**Comment by EwoutH** [comment]
Shame on you @aclinick. Prove that you, your team and Microsoft are better then this and make this right.

**Comment by MCOfficer** [comment]
I'd much rather wait for @kayone's opinion on this **before** starting a witch hunt.

**Comment by jdonaldson** [comment]
I'm came here from the hacker news post, I'd really like to hear Microsoft's side of the story on this.

**Comment by tjerkw** [comment]
My god Microsoft, what we're you thinking? I thought microsoft was embracing opensource and becoming a company I could like again.

But this is just an utter nightmare for microsoft. Handling a nice project like this.

https://keivan.io/the-day-appget-died/
https://news.ycombinator.com/item?id=23331287

@kayone we support you!

**Comment by toinbis** [comment]
`I'd much rather wait for @kayone's opinion on this before starting a witch hunt on his behalf.
`
He shared his story openly already. Community can demand answers as well on communities behalf.  

Morover - this repository Readme says "This project welcomes contributions and suggestions." At the moment MSFT is inviting people to contribute to the project - MSFT acknowledges community as a participant of this project. So community has a perfect right to raise questions.  

And to finish with sharing my opinion on the matter - I am sure there might be another part of the story - but at the moment MSFT, well, stole the car and invites everyone to come and fix it. 

Multiple shady decisions, combined to one story which doesn't smell good at all. Am sure everyone understand that shady decisions, well, happen in life. But on some occassions like this - they get in a spotlight. That's when you stand up, apologize & pay the cash. Put the money where your mouth was for the last couple of years, dear MSFT.

**Comment by MCOfficer** [comment]
> Community can demand answers as well on community behalf.

That's a fair point, with the important bit being the second half. The (original) first comment, however, sounded very much like a personal thing.

Bottom line of my remark: One should be careful not to seemingly demand things on Keivan's behalf. I'm sure there is more than one way to read his story, and we don't want to put words in his mouth.

**Comment by evolvingfridge** [comment]
In short, I hope it will not result in firing developer(s) who just wrote software instead of person(s) who actually made such disgusting decisions.

**Comment by kayone** [comment]
_Copying parts of my comment from_ https://github.com/appget/appget/issues/70

At the end of the day, I just wanted us Windows users to have a great package manager like Homebrew or apt-get etc. And realistically there is a higher chance we'll have a more successful one (might not be necessary ideal) under Microsoft's name than AppGet.

_**Perfect is the enemy of good**_.  I don't want to be the enemy of WinGet. I don't want people to get fired (some people have suggested), I just felt what happened was unfair and wanted to share my story with the few people I thought would read it. I don't want to ruin a product with the potential to do good, because of some personal vendetta.

As I said your feedback has been so far above and beyond what I had expected that I'm forever grateful.


✌️

**Comment by kayone** [comment]
As @evolvingfridge said, let's keep in mind that there are probably many people involved in this project that had no idea what is happening and were just pouring their heart into their work and doing their best.

**Comment by franciscop** [comment]
I am suggesting (not demanding, no witch hunt) that Microsoft donates AND credits @kayone. Sorry if I voiced you in an unwanted way, since you are here please feel free to say if either of these two would be a bad idea in this context.

When I said "personally", I mean that @kayone has repeatedly expressed that his issue was on how Microsoft treated him, not on Microsoft copying AppGet itself. I also didn't mean personally about me, I'm totally uninvolved.

I think if there are involved people who are unaware, it's a good idea that they learn what is happening? I am definitely not asking for anyone to be punished, it seems that while the process was misshandled, the end result is very positive.

**Comment by kayone** [comment]
@franciscop sorry if my response sounded like it was targeted at your request. I defiantly didn't mean you, just speaking in general and wanted to express how I feel about the whole situation.

**Comment by tomwarrenuk** [comment]
I just want to weigh in here and say that @kayone has been very respectful and transparent about what happened. This shouldn't turn into a witch hunt in his name, or people pestering the winget team. Microsoft is a big company, and I'm sure there were multiple people and teams involved in some of the communication failures here. I'm hopeful that Microsoft will acknowledge some of the mistakes here, and give credit where credit is due.

**Comment by icefoxen** [comment]
Perhaps think about something along the lines of describing WinGet as inspired by or a derivative of AppGet, thanking the originator for the work put into it, and asking them "do you mind if we name this WinGet?" You know, like civilized people who want to treat their peers with respect do.

**Comment by aclinick** [comment]
@kayone First of all I regret how we handled the communication during the interview process. A post interview email should have come from me not just an automated email. I own that and I am truly sorry. 
I very much respect your contributions to the Windows Package Manager community. Your contributions along with those from other package managers are extremely valuable. Unfortunately our blog post did not reflect that and I should have caught that. 
Thank you for calling us out on this as it will help us be better members of the community.

**Comment by appetrosyan** [comment]
@aclinick I’m afraid saying that you admit you were wrong and admitting you’re wrong are not the same thing. This person should have been given a chance to do good, and the fact that you think that the email should have been personal, is a small symbolic step in the right direction that does not absolve you of the responsibility. 

Give him credit. Not here, but in the project code. The similarities are uncanny, and I think you should consider yourself lucky for not being sued for violating the Apache 2.0...

**Comment by evolvingfridge** [comment]
Please correct if my understanding @aclinick response is false:


> I very much respect your contributions to the Windows Package Manager community.

But we will not give you a credit, what so ever, nor I have to explain why.


> Your contributions along with those from other package managers are extremely valuable.

But they are not worthy of mentioning, nor will explain why.


> Unfortunately our blog post did not reflect that and I should have caught that.

But I am not going to take any corrective actions. 


> Thank you for calling us out on this as it will help us be better members of the community.

I will not explain what do I mean by "better members".

**Comment by kayone** [comment]
I'm sorry @aclinick but I'll have to agree with @evolvingfridge here.

**Comment by egormalyutin** [comment]
So sorry to interrupt, but what the hell, Microsoft? Is that how you support Open Source?

**Comment by jdonaldson** [comment]
As someone who remembers the "old" Microsoft, this thread is fascinating to me.  A windows package manager is vitally important, and hence an important thing for Microsoft to control.  In the old days, Microsoft would just run in with lawyers blazing, take what they wanted, and the only available repercussion would be an angry slashdot post.  Nowadays, they've been much better open source citizens, but I have to wonder how deep that commitment goes.  I think this issue will give very strong evidence.

**Comment by appetrosyan** [comment]
@jdonaldson The effect is the same, and I wouldn't say its better. It requires zero effort: acknowledge you used his work as inspiration when it clearly is. The author's not pressing charges, he doesn't want monetary compensation, he wants credit, and even though it takes no effort to do, is generally accepted as a token of good will, Microsoft refuses to acknowledge. This is about as bad an OpenSource citizen as you can get! 

The old Microsoft was better. It was more honest about its intentions.

**Comment by kbi911** [comment]
@kayone You Sir, handling this rightly it is just that @microsoftopensource and @aclinick not. I hate to see and read this episode for someone who is running a Microsoft partner company for 20 years. This is not the way i want to see or even read about Microsoft! You Sir Deserve Better.

**Comment by rashil2000** [comment]
> Moreover - this repository Readme says "This project welcomes contributions and suggestions." At the moment MSFT is inviting people to contribute to the project - MSFT acknowledges community as a participant of this project. 

Considering @toinbis's comment here, would it be appropriate if someone just opened up a pull request modifying this project's Readme, to include rightful credits to @kayone?
Response by MS officials on that PR would rightly indicate their intention to correct what they've wronged.

**Comment by aclinick** [comment]
Just published https://devblogs.microsoft.com/commandline/winget-install-learning/ and an upcoming update to the readme.md on the main repo to provide credit to @kayone.  I would like to thank @kayone for working with me over the last couple of days it was a pleasure as always.

**Comment by toinbis** [comment]
@aclinick -  thanks for sharing and update! For me (not that someone should care about my opinion for any reason;) personally this blog post is 20% that does 80% of job. It's great that:
a) This blog post as such was released.  
b) It's open, honest and straightforward.  
c)Those bullet points are a win - pointing to specific things of AppGet that influenced WinGet. Without those bullet points, it'd be just more noise. With those bullet points - problem (arguably) seems solved.

Thanks!  
If I would have opened the ticket, I'd click 'Comment and close' :)

**Comment by franciscop** [comment]
That looks pretty good, thanks @aclinick. If @kayone is happy with it I will close this issue (Microsoft can always close it if they think it's solved).

**Comment by rashil2000** [comment]
@franciscop I'd suggest we keep this issue open until the changes to the Readme as mentioned by @aclinick have been made. Just so we can keep track of stuff here.

**Comment by McoreD** [comment]
> Just published https://devblogs.microsoft.com/commandline/winget-install-learning/ and an upcoming update to the readme.md on the main repo to provide credit to @kayone. I would like to thank @kayone for working with me over the last couple of days it was a pleasure as always.

@aclinick  Microsoft might as well bring every feature over from AppGet now that it is acknowledged. One feature we should copy over is to prevent the PR person being the app maintainer.

**Comment by kayone** [comment]
Thanks @aclinick for the blog post, it means a lot.

There are a few areas Andrew and I have been discussing, hopefully we'll have something to share with you guys soon.

**Comment by Mental-floss** [comment]
I have worked in IT since 1988 and have observed Microsoft's sketchy behavior many times. IMO they have taken it to the level of being criminal in numerous instances.

**Comment by Masamune3210** [comment]
You seem very obsessed with this, even though the conversation is already over and done you insist on bringing it back up

**Comment by AliYar-Khan** [comment]
Shame on you, Microsoft!!! Disgusting

**Comment by Masamune3210** [comment]
Thanks for your input on this almost 5 year old issue....
