### ISSUE TITLE
Install VsCode extension

### ISSUE THREAD

**Issue by Stephanevg** [microsoft/winget-cli#3540]
### Description of the new feature / enhancement

Hi all,

A quick question, is it possible today to installa vscode extension today using winget ?
If so, can you tell me how, I couldn't find it :(

Thanks in advance!

**Comment by Trenly** [comment]
> A quick question, is it possible today to installa vscode extension today using winget ?

To install them as packages using `winget install` is not possible. However, using [`winget configure`](https://learn.microsoft.com/en-us/windows/package-manager/configuration/) and a DSC configuration file, it would be possible to ensure VS Code is installed and all the extensions needed are installed. Even if there isn’t a specific DSC resource for VS Code, you could use configuration to run the install and then use the `code --install-extension` command to install the desired extensions from the configuration file
