### ISSUE TITLE
[Feature Request] Provide alterative installation method for systems that do not have have Windows Store Installed/Enabled

### ISSUE THREAD

**Issue by EdwardFinn** [microsoft/winget-cli#356]
# Description of the new feature/enhancement

Issue: 
Unable to install via the .AppxBundle from Official Release Assets
![image](https://user-images.githubusercontent.com/11775457/83177424-09c7be00-a0ed-11ea-8fb6-fa1066b9efb7.png)

Reason: 
My windows installation does not have Windows Store installed/enabled. Which is a specific limitation of the LTSC version of Windows.

Windows Version Information:
WindowsProductName: Windows 10 Enterprise LTSC 2019
WindowsVersion: 1809

Also unable to install via Powershell with Add-AppxPackage

```
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict
validation.
Windows cannot install package Microsoft.DesktopAppInstaller_1.0.41331.0_x64__8wekyb3d8bbwe because this package
depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published
by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor
architecture and minimum version 14.0.25426.0, along with this package to install. The frameworks with name
"Microsoft.VCLibs.140.00.UWPDesktop" currently installed
Windows cannot install package Microsoft.DesktopAppInstaller_1.0.41331.0_x64__8wekyb3d8bbwe because this package
depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published
by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor
architecture and minimum version 14.0.25426.0, along with this package to install. The frameworks with name
"Microsoft.VCLibs.140.00.UWPDesktop" currently installed are: {}
NOTE: For additional information, look for [ActivityId] daec6466-2d41-000a-6105-04db412dd601 in the Event Log or use
the command line Get-AppPackageLog -ActivityID daec6466-2d41-000a-6105-04db412dd601
At line:1 char:1
+ Add-AppxPackage C:\Users\edfinn\Downloads\Microsoft.DesktopAppInstall ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\edfinn...bbwe.appxbundle:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

# Proposed resolution

Provide an alternate installation method that doesn't rely on the Windows Store. 

**edit**
Changed title, previous title "Unable to install via the .AppxBundle"
Leaving the rest of the post as it was originally, but please also read my follow up reply for additional information on the feature request.

**Comment by Chaython** [comment]
Try installing https://www.microsoft.com/en-us/download/details.aspx?id=53175
Then app installer
Then this.

**Comment by EdwardFinn** [comment]
@ranm-msft I may have laid out the initial request in a confusing manner, I'm intending this to be a feature request, so that WinGet can be installed on a unmodified LTSC Windows 10 install. In order to justify it, I was showing detailed information on why it could not be installed.

My understanding is the next Windows 10 LTSC release would be in 2021, given Microsoft's stated 3 year cadence on LTSC, even if WinGet is delivered bundled into the next windows release, it would be approximately 1 year until that happens.

My feature request is: To provide, with each official release, a secondary installer that is supported by and able to install WinGet on the Windows 10 LTSC channel.

Thank You for your consideration.


@Chaython Thank you for the advice, should this feature request be denied, I will pursue the method you have provided.

**Comment by denelon** [comment]
@EdwardFinn we've got some dependency work to do before this could be a reality. If you'd like to keep this Issue as a feature request, please change the name.

**Comment by EdwardFinn** [comment]
Sorry, confused by the process here, I made this requested changes to this case, has the feature request been denied?

**Comment by Chaython** [comment]
The MSFTbot is bad, almost as bad as the rest of their software :P
Just use choco https://chocolatey.org/ or the many other package managers.

**Comment by Affe2626** [comment]
I compiled it myself for LTSC but it doesn't work. 
This works for adding MS Store though https://github.com/kkkgo/LTSC-Add-MicrosoftStore

**Comment by denelon** [comment]
The Repair-WinGetPackageManager cmdlet in the Microsoft.WinGet.Client PowerShell module offers an alternative installation method outside of the Microsoft Store. Stable versions of App Installer are also available via the WinGet Community repository which supports upgrade scenarios (including dependencies).
