### ISSUE TITLE
WinGet 1.7 manifest schema

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#3568]
### Description of the new feature / enhancement

This is a parent issue to track outstanding schema requests for the 1.7 schema. Inclusion in this list is not a commitment. Other schema items may be added or removed.

* https://github.com/microsoft/winget-cli/issues/1885
* https://github.com/microsoft/winget-cli/issues/3523
* https://github.com/microsoft/winget-cli/issues/3354

**Comment by R-Adrian** [comment]
can we please also get package exclusion without pinning a specific version?  https://github.com/microsoft/winget-cli/issues/2339


examples of currenlty broken / misidentified packages that need to be ignored (or listed in the packages manifest only for supporting initial installation but not for updates via winget?)

**Discord.Discord**  - this one updates itself in the background but when it updates itself it leaves behind the version number from the initial installer in the registry and this confuses winget but not the Discord app itself - that one uses a different version detection mechanism and runs normally.

**Mozilla.Firefox.DeveloperEdition** - this one shows a "stable" version number in the registry and this confuses winget. The app itself does not use the registry for the version detection mechanism and it does normal self-updates in the background.
