### ISSUE TITLE
Git cannot be installed 

### ISSUE THREAD

**Issue by lhy1024** [microsoft/winget-cli#357]
![image](https://user-images.githubusercontent.com/19542290/82878433-0e199d00-9f6e-11ea-82d7-cda579059dac.png)

Git cannot be installed with error msg "access denied"（拒绝访问）

```
> winget --info 
Windows Package Manager v0.1.41331 insider

Windows: Windows.Desktop v10.0.19041.264

Package: Microsoft.DesktopAppInstaller v1.0.41331.0
```

**Comment by armujahid** [comment]
I am also facing exact same issue even in powershell as Administrator.

**Comment by thomthom** [comment]
I've run into this on two computers. Both got the Access denied  message without UAC. Downloading the installer manually from the Git website produce the UAC prompts and work fine.

**Comment by megamorf** [comment]
@thomthom Did you start the cmd/PowerShell process as administrator? That's a requirement for this to work because on programs inherit elevated privileges from their parent process.

**Comment by thomthom** [comment]
hm.. no, I didn't. I hadn't noticed that was a requirement. I guess I was expecting the UAC to prompt to elevate when needed.

Would that be possible to do? Short of that, detect it failed and provide a message as feedback suggesting to start a new terminal with elevated access?

**Comment by felipecrs** [comment]
Hi @denelon, we faced this today. This is probably due to the company's IT restrictions.

I can confirm what was said earlier, from `winget` folder it fails with access denied, but from desktop or any other folder, it works. Running `winget` as an administrator does not help.

/cc @mrbernardi
