### ISSUE TITLE
MSStore source is down

### ISSUE THREAD

**Issue by lychichem** [microsoft/winget-cli#3575]
### Brief description of your issue

Cannot use msstore source, and `winget upgrade --all` fails.

### Steps to reproduce

Run `winget upgrade` then `winget upgrade --all`

### Expected behavior

No error report.

### Actual behavior

First report cannot update msstore then cannot update packages.

### Environment

```shell
Windows 程序包管理器(预览) v1.6.2291-preview
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22621.2215
系统体系结构: X64
软件包: Microsoft.DesktopAppInstaller v1.21.2291.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale

管理员设置                                状态
------------------------------------------------
LocalManifestFiles                        已禁用
BypassCertificatePinningForMicrosoftStore 已禁用
InstallerHashOverride                     已禁用
LocalArchiveMalwareScanOverride           已禁用
```

**Comment by lychichem** [comment]
Besides, I cannot open msstore source in my browser
![image](https://github.com/microsoft/winget-cli/assets/9316590/9a8570c3-95b1-4628-b44c-ffd043236dec)
I don't know if it is related to Chinese internet censership.

**Comment by MagicAndre1981** [comment]
>  I don't know if it is related to Chinese internet censership.

no, I also have this while trying to update [Icaros to Version 3.3.1](https://github.com/microsoft/winget-pkgs/commit/d805eea62b08bd617d5f139ac3f75b61c7160a60). I simply removed the MS Store feed for now

**Comment by 171252** [comment]
Think I have the same or similar problem. After cmd start as admin and then enter "winget list" comes the following:
![image](https://github.com/microsoft/winget-cli/assets/97844259/d449db98-467d-4108-9a9b-3fca671ec3a1)

![image](https://github.com/microsoft/winget-cli/assets/97844259/8e79e02b-3886-455d-865d-82523785dfda)
What can I do?

**Comment by MagicAndre1981** [comment]
> What can I do?

use **winget source remove msstore** to remove the store feed.

**Comment by 171252** [comment]
Wonderful - thank you very much !!

**Comment by eccrk** [comment]
Having removed it trying to re-add it produces:

PS C:\Windows\System32> winget source add -n msstore -a --accept-source-agreements
Adding source:
  msstore -> --accept-source-agreements
An unexpected error occurred while executing the command:
0x80070003 : unknown error

**Comment by 171252** [comment]
The same by me:
![grafik](https://github.com/microsoft/winget-cli/assets/97844259/f016a172-e89f-4f42-b09b-c145bef7b313)

**Comment by denelon** [comment]
You can run `winget source reset --force` as administrator to remove and readd the default sources.

**Comment by denelon** [comment]
The source URL doesn't respond with a document without specifying the endpoint.
Try https://storeedgefd.dsx.mp.microsoft.com/v9.0/information to verify a response from the "msstore" REST source.

**Comment by lychichem** [comment]
> The source URL doesn't respond with a document without specifying the endpoint. Try https://storeedgefd.dsx.mp.microsoft.com/v9.0/information to verify a response from the "msstore" REST source.

Your link responce like this:
![image](https://github.com/microsoft/winget-cli/assets/9316590/8b857221-6133-4ff0-8c59-dfb6b7ffcc4f)
Is it okay? I still cannot use msstore source.

**Comment by 171252** [comment]
I don´t know, I am not an expert.

**Comment by denelon** [comment]
@lychichem that is the expected response via the browser. Can you share logs after running:

`winget search PowerToys -s msstore --verbose-logs --logs`

That will possibly help troubleshoot what might be happening.

**Comment by lychichem** [comment]
The issue was fixed for me. Closing

**Comment by TriAttack238** [comment]
I'm still having this issue, and nothing has worked so far. Here's the most recent logs when I run the requested command:

```
2023-09-14 14:58:53.586 [CORE] WinGet, version [1.5.2201], activity [{2034CECE-5558-4FEF-9811-2A7764E866DC}]
2023-09-14 14:58:53.586 [CORE] OS: Windows.Desktop v10.0.22621.2283
2023-09-14 14:58:53.587 [CORE] Command line Args: winget  search PowerToys -s msstore --verbose-logs --logs
2023-09-14 14:58:53.587 [CORE] Package: Microsoft.DesktopAppInstaller v1.20.2201.0
2023-09-14 14:58:53.587 [CORE] IsCOMCall:0; Caller: winget-cli
2023-09-14 14:58:53.590 [CLI ] WinGet invoked with arguments: 'search' 'PowerToys' '-s' 'msstore' '--verbose-logs' '--logs'
2023-09-14 14:58:53.590 [CLI ] Found subcommand: search
2023-09-14 14:58:53.590 [CLI ] Leaf command to execute: root:search
2023-09-14 14:58:53.590 [CLI ] Executing command: search
2023-09-14 14:58:53.594 [REPO] Additional sources GP is not enabled.
2023-09-14 14:58:53.594 [CORE] Setting action: Get, Type: Secure, Name: user_sources
2023-09-14 14:58:53.594 [CORE] Setting action: Get, Type: Secure, Name: admin_settings
2023-09-14 14:58:53.594 [CORE] Admin settings was not found
2023-09-14 14:58:53.594 [CORE] Adding chain to pinning configuration [Microsoft Store Source]:
DigiCert Global Root G2 : PublicKey
  Microsoft Azure TLS Issuing CA 01 : Subject | Issuer
    sfdataservice.microsoft.com : Subject | Issuer
2023-09-14 14:58:53.594 [CORE] Adding chain to pinning configuration [Microsoft Store Source]:
DigiCert Global Root G3 : PublicKey
  Microsoft Azure ECC TLS Issuing CA 02 : Subject | Issuer
    sfdataservice.microsoft.com : Subject | Issuer
2023-09-14 14:58:53.600 [CORE] Setting action: Get, Type: Standard, Name: sources_metadata
2023-09-14 14:58:53.600 [YAML] Detected UTF-8
2023-09-14 14:58:53.600 [REPO] Named source requested, found: msstore
2023-09-14 14:58:53.600 [REPO] User agent caller found: winget-cli
2023-09-14 14:58:53.600 [REPO] Sending http GET request to: https://storeedgefd.dsx.mp.microsoft.com/v9.0/information
2023-09-14 14:58:53.600 [REPO] Http GET request details:
GET / HTTP/1.1
Content-Type: application/json
User-Agent: winget-cli WindowsPackageManager/1.5.2201 DesktopAppInstaller/Microsoft.DesktopAppInstaller v1.20.2201.0


2023-09-14 14:58:53.866 [REPO] Response status: 200
2023-09-14 14:58:53.866 [REPO] Response details:
HTTP/1.1 200 OK
Cache-Control: max-age=0, no-cache, no-store
Connection: keep-alive
Content-Length: 853
Content-Type: application/json; charset=utf-8
Date: Thu, 14 Sep 2023 21:58:54 GMT
Expires: Thu, 14 Sep 2023 21:58:54 GMT
MS-CV: K9vIg7Kyp0ShASaW.0
Pragma: no-cache
Server: Microsoft-HTTPAPI/2.0
X-OSG-Served-By: Torus-EastAsia_Legacy0005RM_1.0.0.0

{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.PackageMetadata.PackageMetadataResponse, StoreEdgeFD","Data":{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.PackageMetadata.PackageMetadataData, StoreEdgeFD","SourceIdentifier":"StoreEdgeFD","SourceAgreements":{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.PackageMetadata.SourceAgreements, StoreEdgeFD","AgreementsIdentifier":"StoreEdgeFD","Agreements":[{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.PackageManifest.AgreementDetail, StoreEdgeFD","AgreementLabel":"Terms of Transaction","AgreementUrl":"https://aka.ms/microsoft-store-terms-of-transaction"}]},"ServerSupportedVersions":["1.0.0","1.1.0"],"RequiredQueryParameters":["market"],"RequiredPackageMatchFields":["market"]}}
2023-09-14 14:58:53.866 [REPO] User agent caller found: winget-cli
2023-09-14 14:58:53.866 [REPO] Sending http GET request to: https://storeedgefd.dsx.mp.microsoft.com/v9.0/information
2023-09-14 14:58:53.866 [REPO] Http GET request details:
GET / HTTP/1.1
Content-Type: application/json
User-Agent: winget-cli WindowsPackageManager/1.5.2201 DesktopAppInstaller/Microsoft.DesktopAppInstaller v1.20.2201.0


2023-09-14 14:58:53.908 [REPO] Response status: 200
2023-09-14 14:58:53.908 [REPO] Response details:
HTTP/1.1 200 OK
Cache-Control: max-age=0, no-cache, no-store
Connection: keep-alive
Content-Length: 853
Content-Type: application/json; charset=utf-8
Date: Thu, 14 Sep 2023 21:58:54 GMT
Expires: Thu, 14 Sep 2023 21:58:54 GMT
MS-CV: K9vIg7Kyp0ShASaW.0
Pragma: no-cache
Server: Microsoft-HTTPAPI/2.0
X-OSG-Served-By: Torus-EastAsia_Legacy0005RM_1.0.0.0

{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.PackageMetadata.PackageMetadataResponse, StoreEdgeFD","Data":{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.PackageMetadata.PackageMetadataData, StoreEdgeFD","SourceIdentifier":"StoreEdgeFD","SourceAgreements":{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.PackageMetadata.SourceAgreements, StoreEdgeFD","AgreementsIdentifier":"StoreEdgeFD","Agreements":[{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.PackageManifest.AgreementDetail, StoreEdgeFD","AgreementLabel":"Terms of Transaction","AgreementUrl":"https://aka.ms/microsoft-store-terms-of-transaction"}]},"ServerSupportedVersions":["1.0.0","1.1.0"],"RequiredQueryParameters":["market"],"RequiredPackageMatchFields":["market"]}}
2023-09-14 14:58:53.964 [CLI ] Checking Source agreements for source: msstore
2023-09-14 14:58:53.964 [REPO] Additional sources GP is not enabled.
2023-09-14 14:58:53.964 [CORE] Setting action: Get, Type: Secure, Name: user_sources
2023-09-14 14:58:53.964 [CORE] Setting action: Get, Type: Secure, Name: admin_settings
2023-09-14 14:58:53.964 [CORE] Admin settings was not found
2023-09-14 14:58:53.964 [CORE] Adding chain to pinning configuration [Microsoft Store Source]:
DigiCert Global Root G2 : PublicKey
  Microsoft Azure TLS Issuing CA 01 : Subject | Issuer
    sfdataservice.microsoft.com : Subject | Issuer
2023-09-14 14:58:53.964 [CORE] Adding chain to pinning configuration [Microsoft Store Source]:
DigiCert Global Root G3 : PublicKey
  Microsoft Azure ECC TLS Issuing CA 02 : Subject | Issuer
    sfdataservice.microsoft.com : Subject | Issuer
2023-09-14 14:58:53.964 [CORE] Setting action: Get, Type: Standard, Name: sources_metadata
2023-09-14 14:58:53.964 [YAML] Detected UTF-8
2023-09-14 14:58:53.964 [CLI ] Source agreements satisfied. Source: msstore
2023-09-14 14:58:53.965 [REPO] Sending http POST request to: https://storeedgefd.dsx.mp.microsoft.com/v9.0/manifestSearch
2023-09-14 14:58:53.965 [REPO] Http POST request details:
POST / HTTP/1.1
Content-Length: 162
Content-Type: application/json
User-Agent: winget-cli WindowsPackageManager/1.5.2201 DesktopAppInstaller/Microsoft.DesktopAppInstaller v1.20.2201.0
Version: 1.1.0

{"Filters":[{"PackageMatchField":"Market","RequestMatch":{"KeyWord":"US","MatchType":"CaseInsensitive"}}],"Query":{"KeyWord":"PowerToys","MatchType":"Substring"}}
2023-09-14 14:58:54.581 [REPO] Response status: 200
2023-09-14 14:58:54.581 [REPO] Response details:
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: *
Access-Control-Allow-Origin: 
Cache-Control: max-age=0, no-cache, no-store
Connection: keep-alive
Content-Length: 545
Content-Type: application/json; charset=utf-8
Date: Thu, 14 Sep 2023 21:58:55 GMT
Expires: Thu, 14 Sep 2023 21:58:55 GMT
MS-CV: m7U19KhiykSolzfe.6
Pragma: no-cache
Server: Microsoft-HTTPAPI/2.0
X-OSG-Served-By: Torus-WESTUS_Legacy0003GG_1.0.0.0

{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.ManifestSearch.ManifestSearchResponse, StoreEdgeFD","Data":[{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.ManifestSearch.ManifestSearchData, StoreEdgeFD","PackageIdentifier":"XP89DCGQ3K6VLD","PackageName":"Microsoft PowerToys","Publisher":"Microsoft Corporation","Versions":[{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.ManifestSearch.ManifestSearchVersion, StoreEdgeFD","PackageVersion":"Unknown"}]}]}
2023-09-14 14:58:54.582 [CLI ] Search result size: 1
2023-09-14 14:58:54.657 [CLI ] Leaf command succeeded: root:search
```

**Comment by robross0606** [comment]
Same here.  This problem is _not_ fixed.  I've tried resetting the sources and still get the same error if I try to do something like `winget upgrade -all`:

```
Failed when searching source: msstore
An unexpected error occurred while executing the command:
0x8a150044 : The rest source endpoint is not found.
```

However, upgrading an individual package works fine.

**Comment by eccrk** [comment]
Still not fixed for me

PS C:\Users\xxx> winget source reset --force
Resetting all sources...Done

PS C:\Users\xxx> winget upgrade --all
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

Do you agree to all the source agreements terms?
[Y] Yes  [N] No: y
Failed when searching source: msstore
An unexpected error occurred while executing the command:
0x8a150044 : The rest source endpoint is not found.

**Comment by 171252** [comment]
Judah Gabriel writes about it on X (Twitter), "The old website consisted of a React codebase built on an outdated UI framework. We created a new UI with a more thoughtful design, easier ways to discover new apps, and a modern web tech stack." As always, you can access the site itself via apps.microsoft.com.

**Comment by aliajboy** [comment]
Not fixed!

**Comment by EdwinLeeford** [comment]
`Get-AppxPackage *appInstaller* | Reset-AppxPackage`

**Comment by freedomsky11** [comment]
> winget search PowerToys -s msstore --verbose-logs --logs

just use this for resole problem, remember no to re-add msstore back to source, msstore is the problem reason.

**Comment by aliajboy** [comment]
I found the solution but I think just fix mine, not yours. but you can try to change your region. I changed it to USA and now everything works. 👍🏻

**Comment by bergmayer** [comment]
I have this issue, as well.  If I remove the msstore source based on the comments above, I can run "winget upgrade --all".  So that's nice, but...I want to use the msstore source sometimes.  Just removing it does not seem like a good solution. Resetting the sources or adding it back in any way just brings back the same error:

`Failed when searching source: msstore
An unexpected error occurred while executing the command:
0x8a150044 : The rest source endpoint is not found.`

**Comment by johnvondoe** [comment]
@bergmayer have you tried `Get-AppxPackage *appInstaller* | Reset-AppxPackage` ?

**Comment by EdwinLeeford** [comment]
@bergmayer
Have you tried this?
> `Get-AppxPackage *appInstaller* | Reset-AppxPackage`

**Comment by bergmayer** [comment]
> @bergmayer Have you tried this?
> 
> > `Get-AppxPackage *appInstaller* | Reset-AppxPackage`

Ok, that does work.  Thanks!

**Comment by Ann0nimus** [comment]
Hi, so i'm experiencing a similar error when trying to install MSCV with winget when using: "winget install Microsoft.VisualStudio.2022.BuildTools --force --override "--wait --passive --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows11SDK.22000"".
This is the error:
Failed when searching source: msstore
An unexpected error occurred while executing the command: 
0x8a15003b : Rest API internal error

**Comment by mecrayavcin** [comment]
> > [@bergmayer](https://github.com/bergmayer) Have you tried this?
> > > `Get-AppxPackage *appInstaller* | Reset-AppxPackage`
> 
> Ok, that does work. Thanks!

Not worked

Also

ping cdn.winget.microsoft.com

Pinging part-0012.t-0009.t-msedge.net [13.107.213.40] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.
