### ISSUE TITLE
Error: "无法打开此应用包"

### ISSUE THREAD

**Issue by Yanshiqwq** [microsoft/winget-cli#359]
无法打开此应用包
原因:
解析应用包时出错.
![批注 2020-05-29 090814](https://user-images.githubusercontent.com/56720055/83209872-f1f34700-a18b-11ea-9c85-795270c2fa04.png)

**Comment by oxygen-dioxide** [comment]
你的windows10版本是多少？电脑是x64还是arm?

**Comment by yao-msft** [comment]
Or I think maybe the package is corrupt during transmission?
Can you check if the sha256 matches? e1b5aa89c7354dd39db38c2ac33f0455c4529eb4cf77f023028d955122ea8377

**Comment by Yanshiqwq** [comment]
x64,不是arm awa

**Comment by Yanshiqwq** [comment]
![批注 2020-06-03 201441](https://user-images.githubusercontent.com/56720055/83635479-e1e9c600-a5d6-11ea-83b5-f4331dc71e64.png) emmmmmm

**Comment by Yanshiqwq** [comment]
![图片](https://user-images.githubusercontent.com/56720055/83635700-3d1bb880-a5d7-11ea-834a-ac9ca9e3a7b5.png)
貌似所有的appxbundle文件都无法安装??????

**Comment by yao-msft** [comment]
> 貌似所有的appxbundle文件都无法安装??????

That's weird. Is the OS version 1709 (Fall Creators Update) or later?

Can you try open Powershell and use following command and see if there's any error shown?
Add-AppxPackage <Path to .appxbundle>

Also there may be additional info at Event Viewer-> Applications and Services logs-> Microsoft->Windows->AppxDeploymentServer/Operational or AppxPackagingOM/operational

Thanks,
Yao

**Comment by Yanshiqwq** [comment]
![批注 2020-06-04 205325](https://user-images.githubusercontent.com/56720055/83759002-7f133000-a6a5-11ea-98cf-c04287004903.png)
我的Windows版本是1909-18363.720,是不是因为是内部版本所以才不能安装呢...?

**Comment by yao-msft** [comment]
内部版本应该没问题
在Powershell里面用Add-AppxPackage <Path to appxbundle>结果怎么样？

**Comment by Yanshiqwq** [comment]
奇怪了...好像只能用Add-AppxPackage安装emmm
或许我应该去Microsoft社区问问😂

**Comment by yao-msft** [comment]
WinGet is packaged as part of AppInstaller. Since you got the add-appxpackage working, now the AppInstaller should be able to open the release appxbundle correctly.

**Comment by denelon** [comment]
Based on the comment above, I believe this Issue has been resolved. Feel free to re-open the Issue or create another one if this is not the case.

**Comment by Maogxer** [comment]
也可能是网络问题~
