### ISSUE TITLE
Failed when searching source: msstore

### ISSUE THREAD

**Issue by TriAttack238** [microsoft/winget-cli#3596]
### Brief description of your issue

I have been trying to upgrade my programs through winget when I realized that my version is having trouble conntecting to the microsoft store.

### Steps to reproduce

I am on Windows 11 on an AMD 64-bit PC.

1. Open up a terminal in either command line or windows powershell.

2. Enter the command `winget uograde --all` 

### Expected behavior

Usually, this checks for programs that need to update and starts downloading and installing new updates one by one, no matter the source.

### Actual behavior

```
Failed when searching source: msstore
An unexpected error occurred while executing the command:
0x8a150044 : The rest source endpoint is not found.
```

This happens even after a `winget source reset --force`

### Environment

```shell
Windows: Windows.Desktop v10.0.22621.2134
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0
```

**Comment by denelon** [comment]
I think this is a Duplicate of #3575

**Comment by echo-64** [comment]
I tried installing some packages, and this method worked for me while I was experiencing this problem.  

You just need to identify the source, which you can find by searching for the package name.  

`winget search PACKAGE-NAME`

You will see something similar to the following:  

```terminal
Name              Id                         Version      Match         Source
------------------------------------------------------------------------------
PACKAGE-NAME          Provider.Package          1.10.15                winget
```

For example, if the source of this package is `winget`, install it now:    

`winget install PACKAGE-NAME --source winget`
