### ISSUE TITLE
Winget Service Status Down?

### ISSUE THREAD

**Issue by hbland-cjc** [microsoft/winget-cli#3606]
### Brief description of your issue

Unable to use the Winget CDN

### Steps to reproduce

winget install --id Git.Git
--or--
winget source update

### Expected behavior

App install or source complete update

### Actual behavior

![image](https://github.com/microsoft/winget-cli/assets/86969504/eddf2928-9701-48c7-a7b4-119851621f84)

### Environment

```shell
Windows Package Manager v1.5.2201
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.2295
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by denelon** [comment]
Can you try running `winget source reset --force` as an administrator?

**Comment by hbland-cjc** [comment]
Hi @denelon 

I had previously tried this prior to raising this, I have also based on previous issues tried reinstalling the app installer. Apologies I should have mentioned this in the original post

**Comment by denelon** [comment]
Are you able to navigate to: https://cdn.winget.microsoft.com/cache/source.msix

That's the package cache downloaded for the "winget" source. You could try downloading and installing it manually. I think this is likely some kind of networking issue.

You could also change the default downloader in your settings to "wininet".

```JSON
"network": {"downloader": "wininet"}
```

**Comment by hbland-cjc** [comment]
I am able to navigate to the link and have run the installer with the same return, and adding the above to the settings does not change this either

**Comment by hbland-cjc** [comment]
This has now resolved itself

**Comment by Hoangson2007** [comment]
Just pinging this issue to let the maintainers know that the Winget CDN has been down for a couple of days now. And even though I could download the source.msix file manually, it didn't seem to fix anything.
