### ISSUE TITLE
Don't mess up filesystem permission when using under a standard account

### ISSUE THREAD

**Issue by ArchGuyWu** [microsoft/winget-cli#3619]
### Brief description of your issue

| create a standard account as my main account, and some operations like modifying winget source requires administrator privileges to execute, so I used gsudo to resolve this.
After that, I found that I cannot execute winget under the standard account, it caused by filesystem permission changes in AppData\Local\Microsoft\WinGet\Settings and AppData\Local\Microsoft\WinGet\State.

### Steps to reproduce

gsudo winget source remove msstore
winget

### Expected behavior

 I can continue executing winget under the standard account,

### Actual behavior

I cannot execute winget under the standard account caused by filesystem permission changes in AppData\Local\Microsoft\WinGet\Settings and AppData\Local\Microsoft\WinGet\State.

### Environment

```shell
Windows Package Manager v1.5.2201
Windows: Windows.Server v10.0.20348.1970
Microsoft.DesktopAppInstaller v1.20.2201.0
```

**Comment by denelon** [comment]
If I'm understanding this correctly, it appears gsudo might be changing the file permissions.
