### ISSUE TITLE
Install multiple applications with one command (from file or standart input)

### ISSUE THREAD

**Issue by karaeren** [microsoft/winget-cli#362]
# Description of the new feature/enhancement
It would be nice if we could install multiple applications at the same time with a single command similar to apt-get, yarn etc... Or even, from a list of packages in a file (preferably exported from winget). I have created a [PowerShell script](https://gist.github.com/karaeren/5b1ca6e523231e4cbdb9ee52d5dfccf4) that does this with a file but I think this is a feature that should be implemented in the core.

# Proposed technical implementation details (optional)
Instead of writing multiple `winget install -e 'package_name'`s, we could write
`winget install -e Package1.ExactName Package2.ExactName` or
`winget install -e --path winget.txt` where winget.txt is a text file of a list of package names.

**Comment by megamorf** [comment]
Duplicate of #219.

**Comment by karaeren** [comment]
Closed.
