### ISSUE TITLE
winget list is missing 'Available' column

### ISSUE THREAD

**Issue by sleewharry** [microsoft/winget-cli#3633]
### Brief description of your issue

winget v1.5.2201
winget is missing 'Available' column, the column disappeared between two restarts

### Steps to reproduce

run winget list

### Expected behavior

expected to see column 'Available'

### Actual behavior

winget list does not return column 'Available', colums 'Name', 'Id', 'Version' and 'Source' are returned

### Environment

```shell
winget v1.5.2201
```

**Comment by Trenly** [comment]
Available only shows up if there are upgrades available to install. What is the output of `winget upgrade`

**Comment by sleewharry** [comment]
> Available only shows up if there are upgrades available to install. What is the output of `winget upgrade`
> 
> * Related to [Winget list dont show available version #3420](https://github.com/microsoft/winget-cli/issues/3420)
> * Related to [Missing Available column from winget list  #3219](https://github.com/microsoft/winget-cli/issues/3219)
> * Duplicate of [“winget list” don't get "Available" column #1618](https://github.com/microsoft/winget-cli/issues/1618)
> * Duplicate of [winget list does not show column with available update any more #2396](https://github.com/microsoft/winget-cli/issues/2396)

`winget upgrade` shows "11 upgrades available." with visible "Available" column
`winget list` - column "Available" not visible
