### ISSUE TITLE
winget not executes installer as admin 

### ISSUE THREAD

**Issue by serkonda7** [microsoft/winget-cli#3636]
### Brief description of your issue

I want to install KeePass (which is allowlisted) in a corporate environment via winget.
However the installer fails as it is blocked by a group policy.

The problem is that winget does not ask for elevated privileges as it did for other apps.

### Steps to reproduce

- Idk how our group policy looks like
- `winget install DominikReichl.KeePass`

### Expected behavior

winget opens admin credential dialog and installation succeeds

### Actual behavior

Installer: error 1260

winget: exits with 1

app: not installed

### Environment

```shell
Windows Package Manager v1.5.2201
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.3324
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0
```

**Comment by denelon** [comment]
Can you try installing the package with verbose logging and sharing the log file?

`winget install DominikReichl.KeePass -s winget --verbose-logs --logs`

**Comment by serkonda7** [comment]
Sure, here is the log. Please note however that I removed the SQL lines exposing other installed software on my system.

[WinGet-2023-09-19-08-01-29.481.log](https://github.com/microsoft/winget-cli/files/12656424/WinGet-2023-09-19-08-01-29.481.log)

The mentioned KeePass specific logfile `C:\Users\LN\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-DominikReichl.KeePass.2.54.0-2023-09-19-08-01-31.289.log` does not exist.

**Comment by denelon** [comment]
This looks like a failure from the installer itself. Is the package installed on the system already? If you run the installer directly from where it was downloaded (likely in interactive mode) does it install or error out?

**Comment by serkonda7** [comment]
It fails except I run the installer as localadmin manually. The problem is that winget is not asking ask for the admin credentials like it does for other apps.

**Comment by Trenly** [comment]
I don't think this is a Winget issue. I think it may be an issue with KeePass itself not requesting elevation. The way WinGet works currently is to simply download and run the installer with some default arguments - any of the packages that request admin credentials do so because it is the installer itself requesting the elevation

**Comment by Masamune3210** [comment]
Wouldnt this be what requiresElevation in the manifest is for?

**Comment by serkonda7** [comment]
Okay, thanks for the clarification
