### ISSUE TITLE
Installer hash does not match; this cannot be overridden when running as admin

### ISSUE THREAD

**Issue by fate1ess** [microsoft/winget-cli#3640]
### Brief description of your issue

CCleaner  cannot be upgraded.
Installer hash does not match; this cannot be overridden when running as admin

### Steps to reproduce

install CCleaner，can't update

### Expected behavior

can update

### Actual behavior

![截图_230919_1755](https://github.com/microsoft/winget-cli/assets/25172023/cefd1ae4-0913-4c19-addc-3459da9ac3b5)

### Environment

```shell
Windows Package Manager (Preview) v1.7.2491-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3448
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.2491.0

Winget Directories
--------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\D…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\s…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Masamune3210** [comment]
Either don't run the terminal as admin, override the hash (not recommended), and let UAC handle elevation for the installer, or wait for the hash to be fixed before you upgrade.

**Comment by stephengillie** [comment]
Hi @fate1less,

This is the expected behavior when running WinGet from an elevated session, and a hash mismatch is encountered. Hash mismatches are common when a manifest uses a vanity URL and the package becomes updated, such as a new version. The fix here is usually to submit this new version to WinGet's public manifests, and possibly remove the old.

**Comment by denelon** [comment]
Duplicate of #1812

* #1812

**Comment by denelon** [comment]
Feel free to submit an issue over at https://github.com/microsoft/winget-pkgs to request an update to the CCleaner package.

**Comment by Foadsf** [comment]
One possible workaround is what is described [here](https://stackoverflow.com/a/76828240/4999991). In an elevated terminal run:

```
 winget settings --enable InstallerHashOverride
```

now in a normal (i.e., non-elevated) terminal run:

```
winget install <packageName> --ignore-security-hash
```

please consider that this workaround is insecure and unsafe!

**Comment by github-account1111** [comment]
Could someone explain the logic? A hash-mismatched package can be installed through a non-elevated session, but not an elevated one? Shouldn't elevated sessions have *more* privileges, not less?

**Comment by Tornado-F5** [comment]
For those who came here by google search:
after running
winget source reset --force
winget source update
The error was gone for me
