### ISSUE TITLE
Interactive installation parameter does not work

### ISSUE THREAD

**Issue by chrpai** [microsoft/winget-cli#365]
# Brief description of your issue

winget install -i for an MSI pkg doesn't provide an interactive experience.

# Steps to reproduce

winget install -i iswix

I authored the iswix.msi and iswix winget-pkg.  I simply provided the url to the installer and that it was type .msi.   No arguments,  -i and -s all provide a silent installation.  I would expect winget-cli to automatically know how to set the MSI UILevel property since the command line help shows these options.  

# Expected behavior

I'd expect the installer to be called with UILevel 5 so that the MSI wizard loop to appear so I can do advanced selections.

# Actual behavior

The resulting logfile shows UILevel is set to 2  whether I include the -i switch or not.

# Environment

Windows: Windows.Desktop v10.0.19635.1
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
```

**Comment by megamorf** [comment]
I don't understand the issue description to be honest. A silent (a.k.a unattended) installation is the opposite of an interactive installation. Are you asking to be able to provide some sort of parameter to the `winget install` command that turns an unattended installation into an interactive one? Why not simply do `winget show`, use the displayed download url to pull the installer and run it manually?

```
PS C:\Users\megamorf> winget show -e --id Git.Git
Found Git [Git.Git]
Version: 2.26.2
Publisher: Git
Description: Git version control system.
Homepage: https://git-scm.com/
License: GNU General Public License, version 2
License Url: https://github.com/git-for-windows/git/blob/master/COPYING
Installer:
  SHA256: cdf76510979dace4d3f5368e2f55d4289c405e249399e7ed09049765489da6e8
  Download Url: https://github.com/git-for-windows/git/releases/download/v2.26.2.windows.1/Git-2.26.2-64-bit.exe
  Type: Inno
```

**Comment by chrpai** [comment]
winget install -?  already documents a switch for interactive installations.  For an MSI this is standard behavior to pass a /QN for silent installation or don't pass it for interactive.  For EXE installers it's typically adding a /S or not.

The following options are available:
  -m,--manifest     The path to the manifest of the application
  --id              Filter results by id
  --name            Filter results by name
  --moniker         Filter results by app moniker
  -v,--version      Use the specified version; default is the latest version
  -s,--source       Find app using the specified source
  -e,--exact        Find app using exact match
  -i,--interactive  Request interactive installation; user input may be needed
  -h,--silent       Request silent installation
  -o,--log          Log location (if supported)
  --override        Override arguments to be passed on to the installer
  -l,--location     Location to install to (if supported)

**Comment by megamorf** [comment]
Ah, I had to read your last response and then your original issue a number of times to actually understand what you consider the problem. 

I would recommend updating your original issue description and title to more clearly describe the issue and provide a concrete test case. 

Title suggestion:
`Requesting interactive installation parameter results in silent installation` or `Interactive installation parameter does not work`.

**Comment by chrpai** [comment]
I'm glad that you finally understand this simple problem.  I think it was worded just fine but I updated it to try to make you happy.

PS- I'm not sure why I would use winget show to manually download and install the MSI.  That kind of defeats the purpose of winget doesn't it?

**Comment by megamorf** [comment]
To me the purpose of winget is to run unattended installations of libraries and applications. I might want to add additional parameters that I want to be passed to the embedded installer to customize the installation. To me winget resembles a typical command line tool like homebrew, apt or chocolatey for which I never had the need to run an interactive setup. If I wanted an interactive installation I would not expect winget to do that for me - I'd grab the setup file and run it interactively completely bypassing winget.

**Comment by chausner** [comment]
> If I wanted an interactive installation I would not expect winget to do that for me - I'd grab the setup file and run it interactively completely bypassing winget.

Unattended installations, e.g. as part of a batch file, are one usecase. But I see winget also as a tool for people that want to go through the normal installation wizard (e.g. to customize installation options) but that do not want to go through all the manual steps of searching the Internet first for the homepage, downloading the right installer, installing, deleting the installer, etc.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/releases/tag/v0.1.41821-preview
