### ISSUE TITLE
"No installed package found matching input criteria." when trying to update 7zip

### ISSUE THREAD

**Issue by PCAssistSoftware** [microsoft/winget-cli#3690]
### Brief description of your issue

Getting this error when trying to update 7-zip.

"No installed package found matching input criteria."

I can only update by supplying the full name of the app in quotes rather than the Id e.g. winget update "7-Zip 21.07 (x64)" rather than winget upgrade --id 7zip.7zip

CLI output for reference:

winget upgrade --id 7zip.7zip
No installed package found matching input criteria.

winget update "7-Zip 21.07 (x64)"
Found 7-Zip [7zip.7zip] Version 23.01
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.7-zip.org/a/7z2301-x64.exe
██████████████████████████████ 1.51 MB / 1.51 MB
Successfully verified installer hash
Starting package install...
The installer will request to run as administrator, expect a prompt.
Successfully installed

### Steps to reproduce

winget upgrade --id 7zip.7zip
No installed package found matching input criteria.

winget update "7-Zip 21.07 (x64)"
Found 7-Zip [7zip.7zip] Version 23.01
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.7-zip.org/a/7z2301-x64.exe
██████████████████████████████ 1.51 MB / 1.51 MB
Successfully verified installer hash
Starting package install...
The installer will request to run as administrator, expect a prompt.
Successfully installed

### Expected behavior

Would expect it to update using 

winget upgrade --id 7zip.7zip

### Actual behavior

Getting "No installed package found matching input criteria."

### Environment

```shell
Windows 11

Windows Package Manager (Preview) v1.7.2491-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.23550.1000
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.2491.0
```

**Comment by PCAssistSoftware** [comment]
Failed in attempting to update the source: winget
Name              Id        Version Source
-------------------------------------------
7-Zip 23.01 (x64) 7zip.7zip 23.01   winget

**Comment by saqib-s** [comment]
@trenly 

PS C:\> winget list 7-zip
Name                      Id        Version    Available Source
---------------------------------------------------------------
7-Zip 22.00 (x64 edition) 7zip.7zip 22.00.00.0 23.01     winget
7-Zip 23.01 (x64 edition) 7zip.7zip 23.01.00.0           winget
PS C:\>

**Comment by Wallby** [comment]
@saqib-s

> PS C:> winget list 7-zip
> Name Id Version Available Source
> 7-Zip 22.00 (x64 edition) 7zip.7zip 22.00.00.0 23.01 winget
> 7-Zip 23.01 (x64 edition) 7zip.7zip 23.01.00.0 winget
> PS C:>

Is this the same issue #2129, caused by there being more than one version of 7-Zip installed?

**Comment by denelon** [comment]
We've added experimental support for better Side-by-Side behavior.

Please try the experimental feature.
You can see which features are enabled with `winget features`
You can enable settings with `winget settings` (this opens the .json file in your default editor)
`winget settings -?` provides URLs pointing to documentation on our features.

**Comment by sba923** [comment]
I confirm the issue (as described in #4540) goes away after:
- uninstalling 7-zip 24.06 using `MsiExec.exe '/X{23170F69-40C1-2702-2406-000001000000}'`
- uninstalling 7-zip 24.05 using `MsiExec.exe '/X{23170F69-40C1-2702-2405-000001000000}'`
- installing the latest 7-zip using `winget install 7zip`

![image](https://github.com/microsoft/winget-cli/assets/12860484/92de3679-990f-4cef-88f0-292c24d196cd)


I have no clue as to how two different versions could have been registered on the same machine, given that the installation path is the same... but that's another story

**Comment by denelon** [comment]
We now have better support for side-by-side installation. You should be able to uninstall individual versions of packages, and the upgrade flow should work as well using WinGet 1.8.
