### ISSUE TITLE
Class not registered

### ISSUE THREAD

**Issue by NickyMeuleman** [microsoft/winget-cli#370]
# Brief description of your issue/Steps to reproduce

After signing up for the Preview flight ring and installing the app installer via the instructions in the email.

When running `winget show`, or `winget search`, or `winget install powertoys`, ...

```
Failed to open the source; try removing and re-adding it
An unexpected error occurred while executing the command:
Install failed: Klasse is niet geregistreerd
```

Tried installing via the appx bundle instead and got this error while installing:

```
Installatie van app is mislukt met foutbericht: Klasse is niet geregistreerd (0x80040154)
```

# Environment

```none
Windows Package Manager v0.1.41331 Voorbeeld
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.264
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
```

**Comment by denelon** [comment]
Has this issue been resolved? If not, what results do you get with `winget source list`? If you have an empty list, you may be able to address this with `winget source add winget https://winget.azuredget.net/cache`

**Comment by NickyMeuleman** [comment]
```
>winget source list
Name   Arg
-----------------------------------------
winget https://winget.azureedge.net/cache
```

Will try again when the 2004 update becomes available for this machine through Windows update.

**Comment by Michaelvsk** [comment]
I do have the same problem. I am neither using a VPN connection, nor requiring a proxy for internet access.
When trying to access https://winget.azureedge.net/cache via a browser or `Invoke-WebRequest https://winget.azureedge.net/cache`, I get ResourceNotFound as an error.

Is that intended when doing GET on that cache file or might it be part or that problem?

**Comment by Michaelvsk** [comment]
Tested WinGet using the official Windows 10 Enterprise 1809 VM image on Azure and it is working there. `Invoke-WebRequest https://winget.azureedge.net/cache` still returns ResourceNotFound, so it seems to be intended behavior and not related to this error.

**Comment by Michaelvsk** [comment]
Sorry for spamming but I have totally overlooked the actual error but only searched for the first error line. 🤦‍♂️

> Failed to open the source; try removing and re-adding it
> An unexpected error occurred while executing the command:
> **Install failed: Deployment Add operation with target volume C: on Package Microsoft.Winget.Source_2020.618.2223.752_neutral__8wekyb3d8bbwe** from:  (Microsoft.Winget.Source_2020.618.2223.752_neutral__8wekyb3d8bbwe.msix)  failed with error 0x8000FFFF. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
0x8000ffff : Catastrophic failure

It seems that another package is going to be installed, whenn running winget and this fails on my site. So my problems are not related to this isssue

**Comment by denelon** [comment]
@Michaelvsk no worries. Yes, the winget "source" gets installed as a package. The URL doesn't have a default document, so it wouldn't respond with a 200 or content.

**Comment by rkasbohm** [comment]
I am also having the same issues.  

> Failed to open the source; try removing and re-adding it
An unexpected error occurred while executing the command:
Install failed: Deployment Add operation with target volume C: on Package Microsoft.Winget.Source_2020.629.1935.963_neutral__8wekyb3d8bbwe from:  (Microsoft.Winget.Source_2020.629.1935.963_neutral__8wekyb3d8bbwe.msix)  failed with error 0x8000FFFF. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
0x8000ffff : Catastrophic failure

**Comment by Michaelvsk** [comment]
@rkasbohm 
Please have a look at https://github.com/microsoft/winget-cli/issues/276
There is a manual workaround to install the source.msix manually using Powershell. That helped in my case. I suppose for me it is an issue with permissions/group-policies which let the automatic installation fail on my work notebook. No issues on my private PC.

But you need to manually install an updated source.msix every now and then. Cumbersome but working. :)

**Comment by rkasbohm** [comment]
I get the same error.  I don't have problems installing any other window's store app

> App installation failed with error message: Deployment Add operation with target volume C: on Package Microsoft.Winget.Source_2020.630.2349.618_neutral__8wekyb3d8bbwe from:  (source%20(2).msix)  failed with error 0x8000FFFF. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x8000ffff)

**Comment by NickyMeuleman** [comment]
> Will reinstall Windows soon, I'll try again then (been on the planning for a while now)

I did, it works now.
Wrote about it at https://nickymeuleman.netlify.app/blog/winget-windows-package-manager

**Comment by denelon** [comment]
@NickyMeuleman that's a nice write up. Thanks for sharing.
