### ISSUE TITLE
winget install fails for any install

### ISSUE THREAD

**Issue by flanakin** [microsoft/winget-cli#3704]
### Brief description of your issue

When I run any install, like `winget install vscode`, the ASCII spinner runs for a second and then stops. The console focus returns and the next line is red, like it didn't finish writing an error. I've seen this on 2 Windows 11 machines with the latest updates.

### Steps to reproduce

1. `winget install vscode`

### Expected behavior

Install the app 😊

### Actual behavior

![image](https://github.com/microsoft/winget-cli/assets/399533/625a96eb-73c9-4304-ad23-78d14a03a8f1)

### Environment

```shell
Windows Package Manager v1.2.10691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2361
Package: Microsoft.DesktopAppInstaller v1.17.10691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by mdanish-kh** [comment]
Since you're on WinGet 1.2, this is probably due to
- https://github.com/microsoft/winget-cli/issues/3652

Can you please upgrade to the latest version of WinGet (https://aka.ms/getwinget) and check again?

**Comment by Lau27182** [comment]
I had the same issue and you need to update to your windows package manager the lastest version. You can do this via the microsoft store. The thing you need to update is called "app-installer". The new Winget version should be 1.6.

This fixed it for me, hope i could help. :)

**Comment by denelon** [comment]
Yes, the issue is related to:
* #3652
