### ISSUE TITLE
Need a way to do silent installs from private repository

### ISSUE THREAD

**Issue by mpeckatwork** [microsoft/winget-cli#3714]
### Description of the new feature / enhancement

When attempting to do installs from our private repo, we are getting blocked by a prompt to trust the publisher.  
This is not the behavior when installing the same software from the public repo.  (Note:  we are using the same manifest as the public repo).

Need way to signify that the contents of our private repo are trustworthy so winget client will suppress the prompts.

### Proposed technical implementation details

Not recommending any specific implementation as long as the behavior is we are able to run "winget install <software> -s <private repo>" without having to responde to user prompts the same way  "winget install <software> -s winget"  would.

**Comment by mpeckatwork** [comment]
cc: @denelon

**Comment by Trenly** [comment]
Are you also using the `--accept-source-agreements` parameter?

**Comment by denelon** [comment]
We're considering adding another argument for user added sources like "--trust" to indicate the source should explicitly be trusted. We would likely default this behavior for GPO (Group Policy Object) added required sources.

**Comment by denelon** [comment]
With the latest version of WinGet you should be able to specify the trust level using "--trust-level" to avoid the prompt.

```Text
PS C:\Users\denelon> winget source add -?
Windows Package Manager (Preview) v1.9.1981-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Add a new source. A source provides the data for you to discover and install packages. Only add a new source if you trust it as a secure location.

usage: winget source add [-n] <name> [-a] <arg> [[-t] <type>] [<options>]

The following arguments are available:
  -n,--name                   Name of the source
  -a,--arg                    Argument given to the source
  -t,--type                   Type of the source

The following options are available:
  --trust-level               Trust level of the source (none or trusted)
  --header                    Optional Windows-Package-Manager REST source HTTP header
  --accept-source-agreements  Accept all source agreements during source operations
  --explicit
  -?,--help                   Shows help about the selected command
  --wait                      Prompts the user to press any key before exiting
  --logs,--open-logs          Open the default logs location
  --verbose,--verbose-logs    Enables verbose logging for winget
  --nowarn,--ignore-warnings  Suppresses warning outputs
  --disable-interactivity     Disable interactive prompts
  --proxy                     Set a proxy to use for this execution
  --no-proxy                  Disable the use of proxy for this execution

More help can be found at: https://aka.ms/winget-command-source
```
