### ISSUE TITLE
Winget-based Powershell package provider

### ISSUE THREAD

**Issue by sburbano** [microsoft/winget-cli#373]
# Description of the new feature/enhancement

I have read the [roadmap](https://github.com/microsoft/winget-cli/blob/master/doc/windows-package-manager-v1-roadmap.md), especially the targeted scenarios for v1.0. From a SysAdm PoV, having a command-line tool to manage installed applications and packages is certainly very useful. But, as it is, right now I see some mismatch between what a SysAdm would need and what is going to be provided.

Given that one of the greatest tools for sysadm automation (at least in Win world) is Powershell, it would be nice to have a PS module wrapping WinGet functionality, but in a more Powershell-ish way (think object-oriented results, pipelining, etc.) 

Moving one step even further I could even foresee winget becoming/providing a unified way of installing applications AND third-party Powershell modules.

With this idea in mind, I was wondering:

1) Is this aligned with WinGet vision? I understand that you can only do so much for v1.0. But would this be something you would consider or is it absolutely out of scope?

2) Would a hypothetical PR moving in this direction be likely to be accepted? I might consider stepping up for it, but I would like to start with a reasonable expectation of my work going somewhere. :sunglasses:

**Comment by megamorf** [comment]
Hey @sburbano, thanks for reporting this issue. However it seems this has been requested already, see: #221

@ethanbergstrom has also [started to work](https://github.com/microsoft/winget-cli/issues/221#issuecomment-631333519) on a OneGet Provider that you can find here: https://github.com/ethanbergstrom/winget

So I suggest you close this issue and add feedback to the one I linked :-)

**Comment by sburbano** [comment]
Hi @megamorf 

I don't know how I missed that one. Probably I shouldn't be opening issues late at night 😎

**Comment by AurimasNav** [comment]
> Hey @sburbano, thanks for reporting this issue. However it seems this has been requested already, see: #221
> 
> @ethanbergstrom has also [started to work](https://github.com/microsoft/winget-cli/issues/221#issuecomment-631333519) on a OneGet Provider that you can find here: https://github.com/ethanbergstrom/winget
> 
> So I suggest you close this issue and add feedback to the one I linked :-)

PackageManagement is officially deprecated, but it seems we can expect some kind of powershell integration - https://youtu.be/YI9Lw1NOxgU?t=2297
