### ISSUE TITLE
Query syntax not defined

### ISSUE THREAD

**Issue by ManuInNZ** [microsoft/winget-cli#374]
As a user when I have no details on how to use it for "advanced queries".
I suppose something along the lines of the example below might help with and without the exact match filter

`winget search --id="Git.Git" -e`

There is probably more example and might just need a tiny bit more examples of the switches use cases.

Thanks

**Comment by megamorf** [comment]
The search command currently only accepts two parameters: a search term and a list of options.

```
winget search [[-q] <query>] [<options>]
```

If no options are defined the query term is searched across all metadata fields. The string will be treated as a substring - so there is no complex query language hidden behind this. The search by default is also case insensitive. The following options are used to limit that search to certain fields, e.g. 

| Option | Description |
| --- | --- |
| --id | Limits the search to the ID of the application. The ID includes the publisher and the application name. |
| --name | Limits the search to the name of the application. |
| --moniker | Limits the search to the moniker specified. |
| --tag | Limits the search to the tags listed for the application. |
| --command | Limits the search to the name of the application.|

Source: [Docs](https://docs.microsoft.com/windows/package-manager/winget/search)

**Comment by ManuInNZ** [comment]
I get it but in the docs I have seen no examples showing how to use the
switches, e.g. --id=something

Cheers
Manu

**Comment by KevM** [comment]
I agree there is no guidance on how to resolve the desired package.

```pwsh
> winget install --id Git.Git
Multiple apps found matching input criteria. Please refine the input.
Name   Id         Version
-------------------------
Git    Git.Git    2.26.2
GitLFS Git.GitLFS 2.11.0
```

> Please refine the input.

It "would be nice" if the install was interactive that the user would be prompted which selection they wished to install.

**Comment by megamorf** [comment]
@KevM  Sorry, but your comment is not related to the original author's issue. The current issue with the `-e`/ `--exact` parameter has been discussed at length in various along with how the install command is to be used and even lead to the following spec [#292 - winget should install an app if there is an exact match.md](https://github.com/microsoft/winget-cli/blob/master/doc/specs/%23292%20-%20winget%20should%20install%20an%20app%20if%20there%20is%20an%20exact%20match.md).

**Comment by denelon** [comment]
@ManuInNZ are you referring to adding some additional samples with options on https://docs.microsoft.com/windows/package-manager/ ?

**Comment by ManuInNZ** [comment]
Hi there

Sorry that was a long ago now.
I think my point was merely yes to suggest an amendment to the docs and providing query examples like the one I had.

Cheers
Manu

**Comment by denelon** [comment]
@ManuInNZ the documentation at https://docs.microsoft.com/windows/package-manager/winget/install has gone through several revisions. Do you believe it is clear enough at this point to close this issue?

**Comment by ManuInNZ** [comment]
> @ManuInNZ the documentation at https://docs.microsoft.com/windows/package-manager/winget/install has gone through several revisions. Do you believe it is clear enough at this point to close this issue?

Happy with the updates, issue can be closed from my end. 

Cheers
Manu

Thanks for following up.
