### ISSUE TITLE
System context installs using the [Microsoft.WinGet.Client] module no longer appear to be working.

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#3746]
It appears that System context installs using the [Microsoft.WinGet.Client](https://www.powershellgallery.com/packages/Microsoft.WinGet.Client/0.2.1) PowerShell module no longer appear to be working after this change. 

`"%ProgramFiles%\PowerShell\7\pwsh.exe" -MTA --command Install-WinGetPackage` now returns the error message `Install-WinGetPackage: An error occurred while connecting to the catalog.`. This only occurs when trying to use the System user context. Normal user context installs are working as normal. 

This was working as expected for us the last few weeks using these instructions: https://github.com/microsoft/winget-cli/issues/3049#issuecomment-1613880312

The WinGet version being used is 1.6.2771.

_Originally posted by @sspears1 in https://github.com/microsoft/winget-cli/issues/3652#issuecomment-1755943671_

**Comment by denelon** [comment]
We're going to publish an updated PowerShell Microsoft.WinGet.Client module to the gallery with the fix.

**Comment by Chris-Sanford** [comment]
+1 on this issue.

**Comment by ryfu-msft** [comment]
https://www.powershellgallery.com/packages/Microsoft.WinGet.Client/0.2.2

This version of the module should resolve this issue.

**Comment by Chris-Sanford** [comment]
> https://www.powershellgallery.com/packages/Microsoft.WinGet.Client/0.2.2
> 
> This version of the module should resolve this issue.

This did the trick. Thanks for the quick fix!

**Comment by Kaidja** [comment]
Installed the latest version and now I get: "Get-WinGetPackage: Exception has been thrown by the target of an invocation" on PowerShell version 7.3.8

**Comment by dzaggiel** [comment]
Getting error using this module via psexec
![image](https://github.com/microsoft/winget-cli/assets/143708838/d07e06a5-8ead-4b30-b776-c0196a7d6724)
