### ISSUE TITLE
Capture the installed packages for updates only when required

### ISSUE THREAD

**Issue by ManuInNZ** [microsoft/winget-cli#375]
# Description of the new feature/enhancement
In a nutshell a similar mechanism to `cup all -y` from Chocolatey.
At this stage if I define a baseline config with a list of packages and rerun the script, it forces a reinstall of everything.

As a user when I use `winget install mypackage` the system should not download the whole package is already installed (unless I force).
As a user when I use `winget install mypackage` the system should propose a new version upgrade if available (unless I specify a version).
# Proposed technical implementation details (optional)
Capture the currently installed package, e.g. manifest copy, to compare to the install request for comparison of the locally stored version if existing.

**Comment by megamorf** [comment]
Hey @ManuInNZ, thanks for reporting this request. It seems to overlap a lot with already existing issues though:
* #119
* #153
* #216
* #291

So consider closing this issue and adding your feedback to one of the other issues instead :-)
