### ISSUE TITLE
Error 1618 - Cause and request for more informative error message

### ISSUE THREAD

**Issue by panasenco** [microsoft/winget-cli#376]
# Description of the new feature/enhancement

When an MSI installer is already running in the background, any other installers will fail with message "Installer failed with exit code: 1618".

This error code means there's another installer hiding somewhere. These suckers are hard to spot sometimes without closing/minimizing all other windows, so a more descriptive error message would save us a world of grief.

# Proposed technical implementation details (optional)

Catch error 1618 and other MSI installer error codes and show more descriptive error messages.

**Comment by chausner** [comment]
At least for MSI installers, the error codes could be looked up in [this table](https://docs.microsoft.com/en-us/windows/win32/msi/error-codes) and printed with the user-friendly error name and description.

**Comment by Trenly** [comment]
@denelon - I believe this was resolved with #1421 (at least according to the [blame](https://github.com/microsoft/winget-cli/blame/428ffb50527fbb20e39443e13cae2cfa7ec6cdcc/src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp#L606))

https://github.com/microsoft/winget-cli/blob/428ffb50527fbb20e39443e13cae2cfa7ec6cdcc/src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp#L606
