### ISSUE TITLE
Add support for downloading standalone executables (not installers) like Process Explorer

### ISSUE THREAD

**Issue by panasenco** [microsoft/winget-cli#377]
# Description of the new feature/enhancement

Would like to be able to use winget to install and run [Microsoft Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) and other tools that don't have installers, but are standalone executables.

# Proposed technical implementation details (optional)

**Comment by megamorf** [comment]
Hey @panasenco, thanks for creating this issue. However, this seems to be a duplicate of #182, #194 and #298, so please close this issue and subscribe to the ones I linked, thanks :-)

**Comment by panasenco** [comment]
Thanks megamorf, my apologies.

**Comment by phasemaster** [comment]
While the other issues are still open, your specific request seems to be solved: the Microsoft Process Explorer as part of the Sysinternals Suite is now available through winget: https://docs.microsoft.com/en-us/sysinternals/

**Comment by energister** [comment]
I've just installed it

`winget install Microsoft.Sysinternals.ProcessExplorer`

but can't find out how to start it :) There is no "Process Explorer" item in the Start menu

**Comment by ChristianSauer** [comment]
I have the same problem as @energister

**Comment by ItzLevvie** [comment]
You can run Process Explorer by running the `process-explorer` command.

It's defined here: https://github.com/Trenly/winget-pkgs/blob/master/manifests/m/Microsoft/Sysinternals/ProcessExplorer/16.43/Microsoft.Sysinternals.ProcessExplorer.installer.yaml#L8-L9

**Comment by ChristianSauer** [comment]
@ItzLevvie Thanks. But how can I discover that on my own as a user of winget?

**Comment by energister** [comment]
Agree with Christian: even `winget show Microsoft.Sysinternals.ProcessExplorer` shows nothing relevant

**Comment by HomemadeAdvanced** [comment]
Hello,
I have installed it with:
winget install --id="Microsoft.Sysinternals.ProcessExplorer"

It is located in (make sure to change USERNAME with your Windows Username):

C:\Users\USERNAME\AppData\Local\Microsoft\WinGet\Packages\Microsoft.Sysinternals.ProcessExplorer_Microsoft.Winget.Source_8wekyb3d8bbwe\


The procexp.exe should be located in the path.
