### ISSUE TITLE
Can I now implement the default silent installation by modifying the settings.json file without passing the -h parameter?

### ISSUE THREAD

**Issue by tianlongJ** [microsoft/winget-cli#3778]
### Description of the new feature / enhancement

Can I now implement the default silent installation by modifying the settings.json file without passing the -h parameter?If silent operation is available, I hope to use silent installation as the default installation method without passing the virus through cli parameters.

**Comment by denelon** [comment]
We have a separate issue to add more of the supported arguments to the export format, but I'm also considering using the WinGet Configuration syntax as a change to the output format for packages.json.

* https://github.com/microsoft/winget-cli/issues/1512

**Comment by denelon** [comment]
You can also use `winget settings` to specify silent as your default installation mode.
https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#interactivity

**Comment by denelon** [comment]
Duplicate of #1512

**Comment by tianlongJ** [comment]
> You can also use `winget settings` to specify silent as your default installation mode. https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#interactivity



> 你试过吗？`winget import <path to file> -h`

What I mean is not using the -h parameter and making silent installation the default option

**Comment by tianlongJ** [comment]
> You can also use to specify silent as your default installation mode. https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#interactivity`winget settings`

I can try this. My understanding of the description of this parameter is to not display interactive prompts, which is equivalent to the -i/--interactive parameter passing.
