### ISSUE TITLE
'wget --credit' does not show anything while it should at least credit Keivan and AppGet

### ISSUE THREAD

**Issue by tigerinus** [microsoft/winget-cli#378]
# Brief description of your issue

# Steps to reproduce
```
winget --credit
```

# Expected behavior

A message shows up and gives credits to Keivan and AppGet for the original idea.

# Actual behavior

The parameter `--credit`  is not recognized.

# Environment

```none
[winget --info]
Windows Package Manager version: any version
Windows: 20H1

Any other software?
```

**Comment by megamorf** [comment]
Hey @tigerinus, thanks for creating this issue. However, it seems that a better place for this  feedback is #353 where MS is discussing this with the community and Keivan. So I'd recommend closing this issue and adding your input to the one I linked :-)
