### ISSUE TITLE
Azure Marketplace images shipping with outdated version of WinGet

### ISSUE THREAD

**Issue by Smith8154** [microsoft/winget-cli#3793]
### Brief description of your issue

The Azure Marketplace image ships with an outdated version of WinGet that no longer works due to the old CDN being retired. As far as I'm aware, there is no way to automate updating WinGet. As a workaround, I am currently having to log in to each image after they are deployed and manually update WinGet via the Microsoft Store.

### Steps to reproduce

Create a new Azure VM using an Azure Marketplace image (I am using Windows 10 (22H2) EVD + Office ProPlus Gen 2), and immediately attempt to use WinGet. It will fail, as the version of WinGet is pointing to the retired CDN.

### Expected behavior

Azure Marketplace images should ship with the latest version of WinGet.

### Actual behavior

Azure Marketplace images ship with an older, non-working version of WinGet.

### Environment

```shell
NA
```

**Comment by denelon** [comment]
Are you looking for an "easier" way to do this (like a script) or is the ask about updating the image (with a newer version of WinGet) on the Azure Marketplace images?

**Comment by Smith8154** [comment]
I think updating the image in the Azure Marketplace would be preferred, but a script would certainly work as well.

**Comment by denelon** [comment]
Triggering updates via the store does require a bunch of clicking around, and you might get more than you bargained for in terms of how long that takes to complete given updates for other packages in the Microsoft Store.

I'm trying to find a supported mechanism to get the Microsoft Store to just update the App Installer without necessarily triggering all the other updates.

I believe you can install the "Microsoft.WinGet.Client" PowerShell module and then just run the "Repair-WinGetPackageManager" cmdlet in PowerShell 7 (Known chicken and egg scenario). I'm only bringing this up as we may have found a solution using Windows PowerShell which is available on first login. I'll check on that.

In the short term, you could just open https://aka.ms/getwinget in a browser and install the package after it downloads as a quicker method of updating WinGet.

**Comment by denelon** [comment]
What version of WinGet is included on that image?

If it's new enough not to require MSA authentication in the Microsoft Store, you could try:
`winget install "App Installer" -s msstore --force`

It's likely to look like it failed after some progress, but it does work on clients that were updated to use the device entitlement rather than the user entitlement.

**Comment by denelon** [comment]
This PowerShell command might also work:

`Add-AppPackage https://aka.ms/GetWinGet`

**Comment by Smith8154** [comment]
I tested those methods and they all worked to upgrade WinGet unattended.
