### ISSUE TITLE
Command aliases

### ISSUE THREAD

**Issue by MilkFather** [microsoft/winget-cli#380]
# Description of the new feature/enhancement

Inspired by #334 in which the author tried to use `find` to search for packages, I think some common command aliases could be added to WinGet so that the user would not get confused when using synonyms of a command.

# Proposed technical implementation details (optional)

Provide common aliases such as "find ==> search" and "get ==> install", etc.

```
> winget find git
Name                   Id                    Version                    Matched
-------------------------------------------------------------------------------------
Git                    Git.Git               2.26.2                     Moniker: git
......
```

**Comment by megamorf** [comment]
Could you elaborate on what benefit these aliases will bring in your opinion? Some package managers like apt or yum don't ship with command aliases and others like zypper or eopkg ship do but those are actually only shortened versions of their long forms, e.g.:

## eopkg

|Command|Alias|
|---|---|
|search|sr|
|install|it|
|remove|rm|

## zypper

|Command|Alias|
|---|---|
|search|se|
|install|in|
|remove|rm|

**Comment by MilkFather** [comment]
Different package managers use different command for the same action. For example, in apt you use `remove` while in Homebrew, Chocolatey and WinGet you should use `uninstall`. This can cause confusion to some users: A and B are synonyms literally, and command A works in some package manager, why does WinGet requires you to use B?

The example in #334 has shown such confusion: a long-time Chocolatey user simply finds `winget find` not working. "Find" and "search" are synonyms, so it will be **more user-friendly** to make `find` and `search` even `lookfor`(maybe) work.

Actually Chocolatey has done this: `choco find` and `choco search` are aliases for each other. WinGet should make words with similar or same meaning do the same thing.

**Comment by doctordns** [comment]
If anything, the verbs should be the same ss the verbs you'd use had the team done the sensible thing and implemented winget using PowerShell cmdlets. 
There is no good reason for losing consistency when consistency can be delivered easily. 

If you use PowerShell Verbs, then you could also use the verb aliases. 

WHY are people trying to reinvent the wheel?

**Comment by Trenly** [comment]
If anyone has any strong opinions on aliases, i.e, if any others should be added, please post a comment on the linked PR

**Comment by doctordns** [comment]
Where ever possible make aliases that are consistent with PowerShell. I know the team do not want cmdlets, but let's not diverge just because you can. Even if that boat has sailed
