### ISSUE TITLE
Failed in attempting to update the source & reporting wrong winget versions

### ISSUE THREAD

**Issue by eabase** [microsoft/winget-cli#3829]
### Brief description of your issue

winget is not able to get the updated source lists

### Steps to reproduce

`winget list`

Failed in attempting to update the source: winget

### Expected behavior

that it works

### Actual behavior

```powershell
# winget list
Failed in attempting to update the source: winget
...
PowerShell 7-x64               Microsoft.PowerShell               7.3.9.0              winget

# winget search -q "Microsoft.Powershell"
Failed in attempting to update the source: winget
Name               Id                           Version Source
---------------------------------------------------------------
PowerShell         Microsoft.PowerShell         7.3.5.0 winget
PowerShell Preview Microsoft.PowerShell.Preview 7.4.0.4 winget

# winget list -q "Microsoft.Powershell"
Failed in attempting to update the source: winget
Name                   Id                   Version Source
-----------------------------------------------------------
PowerShell 7.3.8.0-x64 Microsoft.PowerShell 7.3.8.0 winget
```

1. Not true. I just installed the latest using downloaded MSI. 
2. Has wrong name with a space in it "PowerShell 7-x64"?
3. `list` Reports the wrong version.
4. `search` on exact package reports the outdated versions.

### Environment

```shell
winget --info

Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3570
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by eabase** [comment]
Related issues:
#3826
#3825
#3806
#3805
#3804
#3798 ?

**Comment by eabase** [comment]
> This is a very old version of WinGet. I'd suggest updating to the latest stable version. You can either do this by checking for updates to "App Installer" in the Microsoft Store, installing from the GitHub releases, or using https://aka.ms/getwinget.

Are you saying that winget can't update itself?

How can I update winget from posh command line?

**Comment by denelon** [comment]
@eabase is the problem resolved with the latest version of WinGet?

We're doing work so WinGet can update itself if the Microsoft Store updates are disabled. The Microsoft Store will automatically update WinGet (via App Installer) unless updates disabled.

**Comment by eabase** [comment]
> @eabase is the problem resolved with the latest version of WinGet?
> 
> We're doing work so WinGet can update itself if the Microsoft Store updates are disabled. The Microsoft Store will automatically update WinGet (via App Installer) unless updates disabled.

Cool. 
Yes, it seem that is has been resolved. 
Also, on my instance MS Store is disabled (by policy), so being able to use winget for updates is near critical.

**Comment by eabase** [comment]
I just tried the above on a Home edition of Windows and it gave me: 

```powershell 
# Add-AppxPackage -Path 'Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle'

Add-AppxPackage: The 'Add-AppxPackage' command was found in the module 'Appx', 
but the module could not be loaded due to the following error: 
[Operation is not supported on this platform. (0x80131539)]
For more information, run 'Import-Module Appx'

# Import-Module Appx
Import-Module: Operation is not supported on this platform. (0x80131539)

# Import-Module -Name Appx -SkipEditionCheck
Import-Module: Operation is not supported on this platform. (0x80131539)
```

I then found the solution to be:
```powershell
# Import-Module -Name Appx -UseWindowsPowerShell

WARNING: Module Appx is loaded in Windows PowerShell using WinPSCompatSession remoting session; 
please note that all input and output of commands from this module will be deserialized objects. 
If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.
```

However, trying use that suggested syntax gave me the same error as before.  Very confusing to say the least. 

Please update your warning messages to actually fit "reality"...
