### ISSUE TITLE
How do we support VS Code Insiders in winget?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/winget-cli#383]
Related: https://github.com/microsoft/winget-pkgs/issues/277

`code-insiders` is published approximately daily, while we could automate a PR for stable I don't think it makes sense to do this for Insiders. We have a web endpoint that points to the latest version, can we just not include a `Version` in the manifest?

@KevinLaMS

**Comment by denelon** [comment]
As the Visual Studio Code release version and the insiders can be installed "side-by-side" we are looking at generating a manifest and having the submission as part of their release process. We would have the standard package and manifests for the release version. As well as the daily insiders build.

**Comment by WSLUser** [comment]
Couldn't you fetch the hash for comparison if you don't want to ignore it? You should be able to get this from Github at the very least.
