### ISSUE TITLE
Issue on adding private repository

### ISSUE THREAD

**Issue by Postuleit** [microsoft/winget-cli#3849]
### Brief description of your issue

When I attempt to add a custom source to my source list I get the following error

![image](https://github.com/microsoft/winget-cli/assets/149814216/fcd7fb02-2abf-48dc-b881-08ea4db75b2f)

### Steps to reproduce

Run the following command

winget source add -n api.winget.pro -a https://api.winget.pro/XXXXXX -t "Microsoft.Rest"

### Expected behavior

Source should be added to source list

### Actual behavior

Getting an error for Failed to open the source

### Environment

```shell
Windows Package Manager v1.6.2771
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.3086
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.2771.0
```

**Comment by mherrmann** [comment]
@Postuleit do you have an account at api.winget.pro? If yes, email us at winget@omaha-consulting.com and we'll be happy to help.

**Comment by denelon** [comment]
Closing this as an external issue.
