### ISSUE TITLE
Please support http and git

### ISSUE THREAD

**Issue by Borkason** [microsoft/winget-cli#385]
I'd like to suggest offering support for http and git based repositores.

PowerShellGet supports only NuGet or SMB repositories. SMB repositories have a number of downsides. But setting up and maintaining a NuGet server is such a high entry barrier and will never pay off the work you have to put into, if you only have a small number of modules that you develop.

With http and git support, you would be able to pull a module from any http or git server. Publishing modules would be integrated into the development flow. Locally develop your module and push with git into GitHub, GitLab, BitBucket etc. From there winget can simply download it via http GET. Versioning is done via branches or tags.

Take a look at the built-in Go package management. Modules are directly published to github (instead of something like npm or pypi) and can be retrieved and updated through `go get github.com/google/codesearch/index`.

Supporting http and git as repositories would simplify setting up company-managed repositories or publishing your created modules.

**Comment by WSLUser** [comment]
You do realize there are packages that take the release files from the Github release page from each project. Unless you're saying you should install "master" for projects via winget (which, while might be nice, probably isn't the greatest idea to do), your use-case is already covered.

**Comment by WSLUser** [comment]
I don't know what http support is missing. Everything literally links to a URL. What more can it do? Did you even try using the package manager before filing this issue?

**Comment by zachcarp** [comment]
Are you looking to install from source or are you looking to pull the most recent release?
