### ISSUE TITLE
winget fails : Failed in attempting to update the source: winget

### ISSUE THREAD

**Issue by pleabargain** [microsoft/winget-cli#3861]
### Brief description of your issue

run
 winget upgrade --all

returns
Failed in attempting to update the source: winget

Then it returns
Microsoft Visual C++ 2015-2022 Redistributable (x64) -… Microsoft.VCRedist.2015+.x86 14.36.32532.0 14.38.32919.0 winget
1 upgrades available.
1 package has a version number that cannot be determined. Using "--include-unknown" may show more results.

winget has installed Microsoft Visual C++ 2015-2022 Redistributable (x64)  6x before. 
winget never gets the other updates

### Steps to reproduce

winget upgrade --all

### Expected behavior

install all new apps

### Actual behavior

fails with 
Failed in attempting to update the source: winget
Name                                                    Id                           Version       Available     Source
-----------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x64) -… Microsoft.VCRedist.2015+.x86 14.36.32532.0 14.38.32919.0 winget
1 upgrades available.
1 package has a version number that cannot be determined. Using "--include-unknown" may show more results.

(1/1) Found Microsoft Visual C++ 2015-2022 Redistributable (x86) [Microsoft.VCRedist.2015+.x86] Version 14.38.32919.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/02a6d5c5-3e10-47de-8025-d97a1321d3e3/AD573D3198853FC71137A88E51ABDE844B84F29B0CE6DD91BBEC661BC0143B36/VC_redist.x86.exe
  ██████████████████████████████  13.2 MB / 13.2 MB
Successfully verified installer hash
Starting package install...
Successfully installed

### Environment

```shell
winget --info
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3636
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by denelon** [comment]
This is an older version of WinGet. Please update to a current version. You can either check in the Microsoft Store for updates, or use https://aka.ms/getwinget.

**Comment by pleabargain** [comment]
thank you
