### ISSUE TITLE
Error message should mention the -e(xact) flag for when multiple apps are found

### ISSUE THREAD

**Issue by Benjin** [microsoft/winget-cli#387]
![image](https://user-images.githubusercontent.com/1609827/83579401-028a2100-a4ee-11ea-8df2-1b5f415fdbf1.png)

Error message should mention the `-e` flag for specifying exact matches.

**Comment by Benjin** [comment]
Updated issue to reflect my own learning moment :)

**Comment by megamorf** [comment]
Hey @Benjin, this is being tracked in other issues already so your issue is actually a duplicate. Still, thank you for taking the time to report UX problems. 👍

**Comment by Benjin** [comment]
Even better!  Didn't notice that one when I searched for it.
