### ISSUE TITLE
winget causing DDOS like behavior

### ISSUE THREAD

**Issue by marekr** [microsoft/winget-cli#3879]
### Brief description of your issue

See https://github.com/microsoft/winget-pkgs/issues/125990

### Steps to reproduce

`winget download <package>`

### Expected behavior

1 HTTP request

### Actual behavior

thousands of http get requests

### Environment

```shell
Windows Package Manager v1.6.2771
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3570
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.2771.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Masamune3210** [comment]
Even going to a website involves more than 1 HTTP request....

**Comment by marekr** [comment]
> Even going to a website involves more than 1 HTTP request....

A download of a single file by a single user should only cause one http request, not thousands. At best, if an app does parallel downloads through http chunk mechanisms, more than 1 and less than 10.

**Comment by marekr** [comment]
To further this since I bothered to look at another timespan. winget has caused 2 million requests in 72 hours from just a small subset of IPs against our infrastructure for just two files.

![image](https://github.com/microsoft/winget-cli/assets/1838013/25ee6562-b4ab-447f-9d06-899d67d83878)

It seems winget with Delivery Optimization is logging the most abuse, but locally, winget without delivery optimization also exhibits the same behavior.

Additionally, from testing, winget does not throttle or stop in response to HTTP 429 (Too Many Requests). It instead goes full throttle and keeps hammering.

**Comment by Dragon1573** [comment]
> At best, if an app does parallel downloads through http chunk mechanisms, more than 1 and less than 10.

@marekr - I'm curious about it. Could you please explain it deeper? Thank you.

Currently, I'm using a modified version of Aria2 `v1.36.0` bundled with Motrix `v1.8.19`. This version of Aria2 increase "maximum parallel" to 64 threads than 16 threads in official version. Will it download the file with 64 HTTP requests? Or it will create and KEEP no more than 10 requests (or connections) open and reused by these 64 threads?

**Comment by marekr** [comment]
Not sure where you swaggered in from with a question about an unrelated app. I was making a generalization which I should have said "tens" rather than 10. Lol

Not over 270 parallel connections like happened in my test

**Comment by Dragon1573** [comment]
> Not sure where you swaggered in from with a question about an unrelated app.

Sorry for the confusion ... You are talking about "an app does parallel downloads through http chunk mechanisms", so I think if Aria2 or Motrix match this case ...

> Not over 270 parallel connections like happened in my test

According to this, a parallel downloader may create TENS of connections with the download server, but it SHOULD NOT open this large amounts of connections like DDoS attack. Is that right?

**Comment by denelon** [comment]
@marekr

The default downloader is delivery optimization which does initiate chunked range requests if I'm not mistaken. What are the sizes are the two files?

The latest version of the client should honor 429 retry-after.
https://github.com/microsoft/winget-cli/pull/3718

Two million requests absolutely seems inappropriate for a "small" number of IP addresses.

If you will send me a direct e-mail, I'll loop in engineering resources to help diagnose and troubleshoot.

**Comment by denelon** [comment]
DO (Delivery Optimization) usually downloads a file via 1MB chunks over parallel connections (up to 4 for foreground and 2 for background downloads).

**Comment by marekr** [comment]
Should DO/winget not cache the HTTP 307 for the session instead of hammering the original url?


Could it be CI or some other automated process hammering downloads and the parallel connection behavior is amplifying things?

After merge of the 7.0.9 KiCad bump, the Icelandic IPs stopped requesting 7.0.8, they continue to request away for the older 6.0.10 package.

The anomalous behavior seems to come from mostly the 12969 ASN from VODAFONE_ICELAND

**Comment by denelon** [comment]
I just heard back from the team on this. Here's what I learned, DO does handle 307 as a redirection. Prior to [Windows 11 22H2](https://en.wikipedia.org/wiki/Windows_11_version_history#Version_22H2_(2022_Update)), they were letting winhttp handle it and they don’t know what it does with a 307 (most likely, it will handle it properly).

**Comment by cmknox** [comment]
@marekr I wanted to jump on here and provide a bit more context. As mentioned above, the default behavior of downloading 1MB chunks is intended to be an optimization. If this is causing trouble in your network, I'm wondering if you'd be willing to turn off HTTP byte range support on your file servers? This will cause DO to do a full, single GET on the content instead of trying to optimize with smaller chunks. Could this be an option for you?

**Comment by denelon** [comment]
Has this issue been resolved?
