### ISSUE TITLE
winget download command has problem with cyrillic symbols in path

### ISSUE THREAD

**Issue by Paciupa** [microsoft/winget-cli#3881]
### Brief description of your issue

`winget download` doesn't work correctly with cyrillic symbols.

### Steps to reproduce

winget download Ghisler.TotalCommander -d C:\\__тест__

### Expected behavior

...
Установщик скачан: C:\\__тест__\Total Commander_11.01_X64_exe_en-US.exe

### Actual behavior

...
Установщик скачан: C:\\__С‚РµСЃС‚__\Total Commander_11.01_X64_exe_en-US.exe

### Environment

```shell
Диспетчер пакетов Windows версии 1.6.2771
Windows: Windows.Desktop v10.0.19045.3570
Архитектура системы: X64
Пакет: Microsoft.DesktopAppInstaller v1.21.2771.0

Another machine:

Диспетчер пакетов Windows версии 1.6.2771
Windows: Windows.Desktop v10.0.22621.2428
Архитектура системы: X64
Пакет: Microsoft.DesktopAppInstaller v1.21.2771.0
```

**Comment by yao-msft** [comment]
This should have been fixed as part of https://github.com/microsoft/winget-cli/pull/4464

**Comment by Paciupa** [comment]
Yes, it's been fixed. Thanks!
