### ISSUE TITLE
FileNotFoundException after Portable install!

### ISSUE THREAD

**Issue by MrHinsh** [microsoft/winget-cli#3882]
### Brief description of your issue

After installing using Winget, when running the portable app from the command line, I get a `FileNotFoundException` exception.

![image](https://github.com/microsoft/winget-cli/assets/5205575/f2e1eeb8-7cb2-4486-ac8d-3bee29f6128f)

This is incorrect behaviour as I can switch to the installed folder in `%localdata%\Microsoft\WinGet\Packages\nkdAgility.AzureDevOpsMigrationTools_Microsoft.Winget.Source_8wekyb3d8bbwe` and run from there with no issues.

![image](https://github.com/microsoft/winget-cli/assets/5205575/0029c9b7-1041-4bd2-a865-ec8f9c6450f1)

### Steps to reproduce

It's not consistently reproducible. I was creating an installation video and uninstall/reinstall a bunch of times.

On the 3rd uninstall/reinstall I received the `FileNotFound` when trying to run.

winget uninstall nkdAgility.AzureDevOpsMigrationTools
winget Install nkdAgility.AzureDevOpsMigrationTools

### Expected behavior

When running the symbolic link `devopsmigration` then the application should run:

```
devopsmigration 14.2.2+Branch.master.Sha.e09eca9a6911ac77ecd0e162a29cd4aa632c3ad4
Copyright (C) 2023 naked Agility with Martin Hinshelwood

ERROR(S):
  No verb selected.

  init       Creates initial config file

  execute    Record changes to the repository.

  help       Display more information on a specific command.

  version    Display version information.
```

### Actual behavior

Instead, I get an error for a missing file that is not in fact, missing fro the folder.

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Hosting.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
   at VstsSyncMigrator.ConsoleApp.Program.<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at VstsSyncMigrator.ConsoleApp.Program.Main(String[] args)
   at VstsSyncMigrator.ConsoleApp.Program.<Main>(String[] args)
```

### Environment

```shell
Windows Package Manager v1.6.2771
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.25992.1000
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.2771.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Enabled
```

https://github.com/nkdAgility/azure-devops-migration-tools/issues/1729

**Comment by MrHinsh** [comment]
Since this only occurs when using the symbolic link I am fairly sure that this is not an issue with my tool, but in the way the symbolic link is created?

**Comment by Trenly** [comment]
* Caused by #2711

**Comment by denelon** [comment]
@stephengillie can you verify?
If this doesn't work without the DLLs we should remove the package until we have the fix in.

**Comment by MrHinsh** [comment]
Please note @denelon that this package works and the DLL's are included in the package. This is a 100% portable package that only requires that .NET be installed.

This is an issue with the "symbolic link" only. 

Also for all of my installs, bar one, this has worked. After repeated uninstall/reinstall evolutions on the same machine this issue manifests.

**Comment by MrHinsh** [comment]
It looks like, based on https://github.com/microsoft/winget-cli/issues/2711, this affects all portable packages that include multiple files if installed using elevated privileges.
