### ISSUE TITLE
Mailbird is upgraded to version 3 even if current license is not valid for mailbird 3

### ISSUE THREAD

**Issue by tygore587** [microsoft/winget-cli#3907]
### Brief description of your issue

I had mailbird 3 installed and winget upgraded it to mailbird 3, which needs a new license.

### Steps to reproduce

1. Install mailbird 2.X with active license
2. Run `winget upgrade --all` (or just mailbird)
3. Start mailbird

### Expected behavior

Do not upgrade it to a version where the license is not working anymore.

### Actual behavior

Upgrades the version, so I only runs in free mode.

### Environment

```shell
Windows-Package-Manager v1.6.3133

Windows: Windows.Desktop v10.0.22631.2715
Systemarchitecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3133.0
```

**Comment by Masamune3210** [comment]
Not a issue with winget. It's doing its job correctly. You told it to upgrade everything that had a package match and a newer version that what you have installed, so it did. If you want to keep a package from being updated, you need to pin it at that version so that winget doesnt touch it

**Comment by tygore587** [comment]
I thought about it over night and your are right. But was a little bit suprised none the less, because mailbird itself doesn't offered the update if I don't also buy a license.

**Comment by Masamune3210** [comment]
The problem is winget has absolutely no idea about the state of the program, so it doesnt have the information needed to know the license isnt applicable to the new version. In reality, its likely the same issue would happen with any other package manager as well.

**Comment by tygore587** [comment]
Yeah the installer should implement that check and fail. So this is not a concern of winget, you are right.
