### ISSUE TITLE
WinGetUI not displaying updates or installed packages but winget cli works

### ISSUE THREAD

**Issue by stephenhilton** [microsoft/winget-cli#3908]
### Brief description of your issue

When I first installed WinGetUI it was working.
However, now it does not display installed packages or software updates.
I can discover packages successfully though.
I don't know what has changed for it to stop working.

### Steps to reproduce

Start WinGetUI and click on Software Updates and Installed Packages

### Expected behavior

I expect to see a list of upgradeable packages, and a list of installed packages.

### Actual behavior

I see zero software updates and zero installed packages
(but winget CLI works)

wingetui log:
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
🔵 It took 0.0030019283294677734 to load all language files
🟢 checkQueue Thread started!
🟡 Chocolatey was not found on the default location, perhaps a portable WingetUI installation?
🔵 Language file up-to-date
🔵 Starting main application...
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
 * Serving Flask app 'WingetUI backend'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:7058
Press CTRL+C to quit
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E}\WingetUI\winge...
🔵 Adding chocolatey to path...
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop is disabled', 'PipFound': False, 'PipVersion': 'Pip is disabled', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', '.NET ToolFound': False, '.NET ToolVersion': '.NET Tool is disabled', 'ChocolateyFound': True, 'ChocolateyVersion': '', 'WingetFound': True, 'WingetVersion': ''}
🔵 Reached main ui load milestone
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🔵 Reloading Scoop sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Starting winget source search...
🟢 Starting winget source search...
🟢 Settings tab loaded!
🟢 winget source search finished
🟢 winget source search finished
🟢 About tab loaded!
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🔵 Starting Chocolatey search for updates
🔵 Starting Winget search for updates
🟢 Winget search for updates finished with 0 result(s)
🟢 Main application loaded...
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🟢 Starting winget source search...
🟢 winget source search finished
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/translate.png
🟢 Found reactivation lock file...
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🟢 Starting winget source search...
🟢 winget source search finished
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/translate.png
🔵 Loading WingetUI log...
🔵 Reloading Package Manager logs...
🔵 Loading WingetUI log...
🔵 Loading WingetUI log...
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...

Package manager logs
Outputs from package managers on the current session:
 ---------Winget---------Winget---------Chocolatey
Chocolatey v2.2.2
0 packages installed.

---------Winget

---------Chocolatey
Chocolatey v2.2.2
0 packages installed.

---------Chocolatey
Chocolatey v2.2.2
Outdated Packages
Output is package name | current version | available version | pinned?Chocolatey has determined 0 package(s) are outdated.---------Winget

---------Winget---------Chocolatey
Chocolatey v2.2.2
0 packages installed.

---------Chocolatey
Chocolatey v2.2.2
0 packages installed.

CLI output:
C:\Users\Stephen>winget list
Name                                          Id                                            Version                    Source
------------------------------------------------------------------------------------------------------------------------------
Windows Driver Package - Google, Inc. (WinUS… 092555911492C6959D2596D612F52DCA71881CA2      08/28/2014 11.0.0000.00000
The Witcher Enhanced Edition Director's Cut   1207658924_is1                                2.1.0.15
The Witcher 2 - Assassins of Kings Enhanced … 1207658930_is1                                3.5.0.26g
Cyberpunk 2077: Phantom Liberty               1256837418_is1                                2.02
<<snipped>>

C:\Users\Stephen>winget update
Name                                                           Id                           Version       Available     Source
------------------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.30501   Microsoft.VCRedist.2013.x64  12.0.30501.0  12.0.40664.0  winget
Microsoft Visual C++ 2005 Redistributable (x64)                Microsoft.VCRedist.2005.x64  8.0.56336     8.0.61000     winget
Microsoft Visual C++ 2005 Redistributable                      Microsoft.VCRedist.2005.x86  8.0.56336     8.0.61001     winget
Microsoft Visual C++ 2005 Redistributable                      Microsoft.VCRedist.2005.x86  8.0.59193     8.0.61001     winget
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.36.… Microsoft.VCRedist.2015+.x86 14.36.32532.0 14.38.33130.0 winget
Python Launcher                                                Python.Launcher              < 3.12.0      3.12.0        winget
<<snipped>>

### Environment

```shell
C:\Users\Stephen>winget --info
Windows Package Manager v1.6.3133
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2715
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3133.0

Winget Directories
------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputD…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.js…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by mdanish-kh** [comment]
https://github.com/marticliment/WingetUI/ would be the correct place to file this issue.
