### ISSUE TITLE
[Idea] Support official download mirrors when the official download site is down.

### ISSUE THREAD

**Issue by tranquilcarbon** [microsoft/winget-cli#3912]
### Description of the new feature / enhancement

Currently, the blender download site is down from what appears to be a denial of service attack, the symptoms include extremely slow download speeds to download failures, If this occurs, winget will slow to a crawl, appearing to not support the ability to stop a download if it times out and move on.

Being a open source program, Blender has several alternative downloads, hosted by third parties. The blender foundation has posted a few mirrors that it trusts, including:

https://mirror.clarkson.edu/blender/release/

and

https://ftp.nluug.nl/pub/graphics/blender/release/

other open source programs also have alternative download mirrors including:

WiresharkFoundation.Wireshark - https://www.wireshark.org/mirror.html

### Proposed technical implementation details

If the download either times out or fails in some way, it will move to one of these mirrors and try those. If all of the mirrors fail, then the package update should be skipped.

In addition, there is the concern of hashes, my suggestion is to connect to each server and reserve the hashes in memory and check against the most common hash.

**Comment by Trenly** [comment]
* Duplicate of #1589 
* Related to #3074
