### ISSUE TITLE
Microsoft Terminal installation fails because of UI.Xaml higher version

### ISSUE THREAD

**Issue by dirrgang** [microsoft/winget-cli#3918]
### Brief description of your issue

I installed WingetUI the other day, and today I noticed it kept trying to install Windows Terminal but kept failing. Checking the logs revealed that the installation failed with this error:

```
PS C:\Users\d> winget install Microsoft.WindowsTerminal
Gefunden Windows Terminal [Microsoft.WindowsTerminal] Version 1.18.3181.0
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Dieses Paket erfordert folgende Abhängigkeiten:
  - Pakete
      Microsoft.UI.Xaml.2.8 [>= 8.2306.22001.0]
Abhängigkeiten werden installiert:
(1/1) Gefunden Microsoft.UI.Xaml [Microsoft.UI.Xaml.2.8] Version 8.2306.22001.0
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
  ████████████████████████████▌   95%
Installation fehlgeschlagen mit Exitcode: 0x80073d06 : Das Paket konnte nicht installiert werden, da bereits eine h�here Version des Pakets installiert ist.
Eine höhere Version dieser Anwendung ist bereits installiert.
```

The same error happens when trying to install the Microsoft.UI.Xaml.2.8 package directly. I figured reinstalling the package might work, but that didn't work either:

```
PS C:\Users\d> winget uninstall Microsoft.UI.Xaml.2.8
Es wurde kein installiertes Paket gefunden, das den Eingabekriterien entspricht.
PS C:\Users\d> winget uninstall Microsoft.UI.Xaml
Es wurde kein installiertes Paket gefunden, das den Eingabekriterien entspricht.
```

No package found. It's also not in appwiz.cpl or the installed apps section - so I'm not really sure if it really is installed or not.

I stupidly uninstalled Windows Terminal in hopes that this fixes something, but it just refused to install it with the same error. Interestingly, installing it via the Microsoft Store UI worked without a hitch.

### Steps to reproduce

Not sure what caused this issue to happen in the first place.

### Expected behavior

Package is updated/installed as expected.

### Actual behavior

Installation/update is cancelled because of a dependency that is (supposedly) already installed with a higher version.

### Environment

```shell
Windows-Paket-Manager v1.6.3133
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22631.2715
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.21.3133.0

WinGet-Verzeichnisse
-----------------------------------------------------------------------------------------------------------------------
Protokolle                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Benutzereinstellungen                        %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Verzeichnis für portierbare Links (Benutzer) %LOCALAPPDATA%\Microsoft\WinGet\Links
Portables Linkverzeichnis (Computer)         C:\Program Files\WinGet\Links
Portierbarer Paketstamm (Benutzer)           %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portierbarer Paketstamm                      C:\Program Files\WinGet\Packages
Portierbares Paketstamm (x86)                C:\Program Files (x86)\WinGet\Packages
Installationsprogrammdownloads               %USERPROFILE%\Downloads

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale

Administratoreinstellung                  Status
-----------------------------------------------------
LocalManifestFiles                        Deaktiviert
BypassCertificatePinningForMicrosoftStore Deaktiviert
InstallerHashOverride                     Deaktiviert
LocalArchiveMalwareScanOverride           Deaktiviert


WingetUI 2.1.1
```

**Comment by Chasapple4** [comment]
When I tried I get the prompt tho it looks like it downloads a version that is older than what is installed.

A workaround might be to manually grab the updated version

**Comment by dirrgang** [comment]
> When I tried I get the prompt tho it looks like it downloads a version that is older than what is installed.
> 
> A workaround might be to manually grab the updated version

How do I install the updated version? (And which is it?) If I'm not mistaken, it is trying to install the recent version:

```
PS C:\Users\d> winget install Microsoft.UI.Xaml.2.8
Gefunden Microsoft.UI.Xaml [Microsoft.UI.Xaml.2.8] Version 8.2306.22001.0
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
  ████████████████████████████▌   95%
Installation fehlgeschlagen mit Exitcode: 0x80073d06 : Das Paket konnte nicht installiert werden, da bereits eine h�here Version des Pakets installiert ist.
Eine höhere Version dieser Anwendung ist bereits installiert.

PS C:\Users\d> winget search Microsoft.UI.Xaml
Name              ID                    Version        Quelle
--------------------------------------------------------------
Microsoft.UI.Xaml Microsoft.UI.Xaml.2.8 8.2306.22001.0 winget
Microsoft.UI.Xaml Microsoft.UI.Xaml.2.7 7.2208.15002.0 winget
```

**Comment by elisimpson** [comment]
Me too. The version I already have is Microsoft.UI.Xaml.2.8_8.2310.30001.0_x64__8wekyb3d8bbwe

For some reason the WindowsTerminal installer keeps trying to install an older version UI.Xaml (8.2306.22001.0) and failing

**Comment by Chasapple4** [comment]
The version it is grabbing is older (you can see the url it is grabbing the file from in the terminal window during the download)
https://github.com/microsoft/terminal/releases/tag/v1.18.3181.0 has the newer one that is listed (that is based on where it was trying to grab the file from but it grabs a version that is older than 1.18.3181.0 )

**Comment by Auto72** [comment]
If you install it from here it works.

https://github.com/microsoft/terminal/releases/tag/v1.18.3181.0

https://github.com/microsoft/terminal/releases/download/v1.18.3181.0/Microsoft.WindowsTerminal_1.18.3181.0_8wekyb3d8bbwe.msixbundle

**Comment by mdanish-kh** [comment]
A workaround until this dependency issue gets resolved is to try installing without the dependency by passing `--skip-dependencies`

```
winget install Microsoft.WindowsTerminal --skip-dependencies
```

**Comment by abionescu** [comment]
optionally you can skip dependency resolution
`winget update Microsoft.WindowsTerminal --skip-dependencies`

**Comment by Chasapple4** [comment]
> A workaround until this dependency issue gets resolved is to try installing without the dependency by passing `--skip-dependencies`
> 
> ```
> winget install Microsoft.WindowsTerminal --skip-dependencies
> ```

That will downgrade it to an older version than is already installed, WinGet is grabbing an older version as of when the issue was first opened

**Comment by yooakim** [comment]
I also have the reported issue, the dependency Microsoft.UI.Xaml fails to install.

This likely is not an issue with Windows Terminal but with the Microsoft.UI.Xaml winget package.

Using the `winget install Microsoft.WindowsTerminal --skip-dependencies` as suggested by many works.

**Comment by sinsukehlab** [comment]
> > A workaround until this dependency issue gets resolved is to try installing without the dependency by passing `--skip-dependencies`
> > ```
> > winget install Microsoft.WindowsTerminal --skip-dependencies
> > ```
> 
> That will downgrade it to an older version than is already installed, WinGet is grabbing an older version as of when the issue was first opened

Try `winget upgrade --id Microsoft.WindowsTerminal --skip-dependencies` if `winget install` fails to grab the latest version.

**Comment by burhankoylu** [comment]
> If you install it from here it works.
> 
> https://github.com/microsoft/terminal/releases/tag/v1.18.3181.0
> 
> https://github.com/microsoft/terminal/releases/download/v1.18.3181.0/Microsoft.WindowsTerminal_1.18.3181.0_8wekyb3d8bbwe.msixbundle

thanks for help. it works.

**Comment by giuseppebin** [comment]
> > If you install it from here it works.
> > https://github.com/microsoft/terminal/releases/tag/v1.18.3181.0
> > https://github.com/microsoft/terminal/releases/download/v1.18.3181.0/Microsoft.WindowsTerminal_1.18.3181.0_8wekyb3d8bbwe.msixbundle
> 
> thanks for help. it works.

Thanks. It works.

**Comment by rumplin** [comment]
I already have Windows.Terminal install, doing an update I get an unknown error:

```
winget update Microsoft.WindowsTerminal
Found Windows Terminal [Microsoft.WindowsTerminal] Version 1.18.3181.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Microsoft.UI.Xaml.2.8 [>= 8.2306.22001.0]
Installing dependencies:
(1/1) Found Microsoft.UI.Xaml [Microsoft.UI.Xaml.2.8] Version 8.2306.22001.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
  ████████████████████████████▌   95%
Installer failed with exit code: 0x80070002 : unknown error
```

**Comment by chriss-bauer** [comment]
winget update Microsoft.WindowsTerminal
....
Starting package install...
  ████████████████████████████▌   95%
Installer failed with exit code: 0x80070002 : unknown error

Same here - 0x80070002 : says "File not found"

Problably some dependency issues since https://www.nuget.org/packages/Microsoft.UI.Xaml/2.8.0 also cannot be installed.
Tried via download and direct install through package manager.
Seems ther is one unfullfilled dependency to Microsoft.Web.WebView2

Please check the dependencies so they work for all.

**Comment by giuseppebin** [comment]
> same problem here

install from https://github.com/microsoft/terminal/releases/tag/v1.18.3181.0 
without using winget. It works for me.

**Comment by gadzhikuliev** [comment]
> > same problem here
> 
> install from https://github.com/microsoft/terminal/releases/tag/v1.18.3181.0 without using winget. It works for me.

Mee too! Thank you!

**Comment by jessey-git** [comment]
3 weeks later and a Microsoft tool still cannot install a Microsoft package due to a problem inside a Microsoft dependency.

**Comment by vayinapurapu** [comment]
I am getting the same issue when installing Windows Terminal Preview. The below steps worked for me
winget install Microsoft.UI.XAML.2.8 
winget install Microsoft.WindowsTerminal.Preview.
![iScreen Shoter - 20240129100540953](https://github.com/microsoft/winget-cli/assets/22406785/fbfa0e77-131c-4321-a4e7-ab86092ca92e)

**Comment by hueldoeu** [comment]
> same problem here

somehow it got solved in it own.
