### ISSUE TITLE
[Request] Add Fonts Support

### ISSUE THREAD

**Issue by garmede** [microsoft/winget-cli#392]
At least i wish Cascadia.

**Comment by TylerLeonhardt** [comment]
Need this to resolve https://github.com/tonsky/FiraCode/issues/1177

**Comment by shalva97** [comment]
any updates on this?

**Comment by ChungZH** [comment]
good idea

**Comment by glen-84** [comment]
Duplicate of #166.

**Comment by Trenly** [comment]
> Duplicate of #166.

cc @denelon

**Comment by denelon** [comment]
Duplicate of #166
