### ISSUE TITLE
App different versions, same ID, unable to uninstall

### ISSUE THREAD

**Issue by GustavoAlmeidaAboud** [microsoft/winget-cli#3934]
### Brief description of your issue

Two different versions of the software installed with the same ID

### Steps to reproduce

I believe this was due a winget upgrade

### Expected behavior

Be able to uninstall winget app with the same ids

### Actual behavior

Unable to uninstall winget with the same id

Winget list keepass
-----------------------------------------------------------------------------
KeePass Password Safe 1.40.1 DominikReichl.KeePass   1.40.1  2.55.0    winget
KeePass Password Safe 2.55   DominikReichl.KeePass   2.55              winget
KeePass 2.53                 DominikReichl.KeePass   2.53.0  2.55.0    winget

### Environment

```shell
Windows Package Manager v1.6.3133
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2715
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3133.0
```

**Comment by mdanish-kh** [comment]
This is a known issue with side-by-side installations and unfortunately WinGet does not handle this scenario all that well in its current implementation.

You'll have to manually uninstall the older version from `appwiz.cpl`. After that the uninstall command will work as expected with a single installed version of the package.

- Related to https://github.com/microsoft/winget-cli/issues/2129

**Comment by denelon** [comment]
We've been working on the side-by-side scenarios. You could try the latest release and enable the experimental feature on:
* https://github.com/microsoft/winget-cli/releases/tag/v1.8.924-preview

Please provide feedback at:
* https://github.com/microsoft/winget-cli/discussions/4281

**Comment by denelon** [comment]
You should now be able to uninstall a specific version of a package using WinGet 1.8.
