### ISSUE TITLE
`winget source update` doesn't properly update manifest information

### ISSUE THREAD

**Issue by mjr4077au** [microsoft/winget-cli#3938]
### Brief description of your issue

Currently it can be seen that TeamViewer 15.48.4 was reverted out, however the client is still trying to deploy it.

Link to revert: https://github.com/microsoft/winget-pkgs/pull/128578

Results from `winget search --id TeamViewer.TeamViewer`:
```
Name            Id                         Version Source
----------------------------------------------------------
TeamViewer      TeamViewer.TeamViewer      15.48.4 winget
TeamViewer Host TeamViewer.TeamViewer.Host 15.48.4 winget
```

### Steps to reproduce

1. Execute `winget search --id TeamViewer.TeamViewer`.
2. Observe incorrect package version.
3. Execute `winget source update`.
4. Execute `winget search --id TeamViewer.TeamViewer`.
5. Observe incorrect package version.

### Expected behavior

```
PS C:\Users\mjr40> winget search --id TeamViewer.TeamViewer
Name            Id                         Version Source
----------------------------------------------------------
TeamViewer      TeamViewer.TeamViewer      15.48.4 winget
TeamViewer Host TeamViewer.TeamViewer.Host 15.48.4 winget
PS C:\Users\mjr40> winget source update
Updating all sources...
Updating source: msstore...
Done
Updating source: winget...
Done
PS C:\Users\mjr40> winget search --id TeamViewer.TeamViewer
Name            Id                         Version Source
----------------------------------------------------------
TeamViewer      TeamViewer.TeamViewer      15.47.3 winget
TeamViewer Host TeamViewer.TeamViewer.Host 15.47.3 winget
PS C:\Users\mjr40>
```

### Actual behavior

```
PS C:\Users\mjr40> winget search --id TeamViewer.TeamViewer
Name            Id                         Version Source
----------------------------------------------------------
TeamViewer      TeamViewer.TeamViewer      15.48.4 winget
TeamViewer Host TeamViewer.TeamViewer.Host 15.48.4 winget
PS C:\Users\mjr40> winget source update
Updating all sources...
Updating source: msstore...
Done
Updating source: winget...
Done
PS C:\Users\mjr40> winget search --id TeamViewer.TeamViewer
Name            Id                         Version Source
----------------------------------------------------------
TeamViewer      TeamViewer.TeamViewer      15.48.4 winget
TeamViewer Host TeamViewer.TeamViewer.Host 15.48.4 winget
PS C:\Users\mjr40>
```

### Environment

```shell
Windows Package Manager v1.6.3133
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2715
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3133.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                D:\User Redirected Folders\mjr40\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by mjr4077au** [comment]
I also tried `winget source reset --force` to give it the sledgehammer, same outcome.

**Comment by mdanish-kh** [comment]
The PR was merged but did not pass the publish pipeline (that's why you don't see `Publish-Pipeline-Succeeded` label attached to the PR)

Looks like there have been a number of PRs recently that did not pass the publish stage

https://github.com/microsoft/winget-pkgs/pulls?q=is%3Amerged+is%3Apr+label%3A%22Validation-Completed%22+-label%3A%22Publish-Pipeline-Succeeded%22+

cc @denelon

**Comment by mdanish-kh** [comment]
Looking more into some older PRs (more than a day old), it seems that those PRs did get their changes published but the label was not successfully attached to the PR.

Usually the publish process takes less than an hour, but anomalies may occur. This could be a transient error that resolves itself over time.

**Comment by mjr4077au** [comment]
The problem is that the PR was reverted over 4 hours ago and nearly 2 hours later, that's still reflected on the client. We're frequently doing device builds using Autopilot and this huge delay between a reversion and manifest update causes all our workstation builds to fail. This may not be a problem for end users, but it is for businesses trying to leverage the technology in Intune or SCCM.

Is there any documentation that highlights how frequently the database is updated to reflect the committed manifest changes?

**Comment by denelon** [comment]
The publishing [pipeline](https://dev.azure.com/ms/winget-pkgs/_build?definitionId=338) (linked on the [winget-pkgs](https://github.com/microsoft/winget-pkgs) README.md) runs when a PR is merged for a package. If any other PRs are merged during the time it is running, it will begin again. Any PRs that have been merged before the pipeline starts will be included.

**Comment by denelon** [comment]
@mjr4077au no, an instance of a publishing run will complete (assuming it doesn't fail). Any PRs that are merged while the publishing pipeline is running get queued for inclusion into the next pipeline run.

**Comment by denelon** [comment]
For the sake of transparency, the worst-case scenario is some merged manifest causes the publishing pipeline to fail. More PRs were merged while it was running. Then the next pipeline run has the previous and any new PRs merged to publish. The original "bad" manifest will continue to cause the pipeline to fail until we intervene. 

Unfortunately, this has happened a few times over the last 3+ years, but it is certainly an exception to the typical behavior.

**Comment by mjr4077au** [comment]
Thanks for clarifying, that makes a lot more sense. With those pipelines only taking about 15 minutes each to run, what would cause the client to believe a reverted manifest was still current some 4 or more hours later?

**Comment by mjr4077au** [comment]
There's certainly a lot of moving parts from PR merging to the client becoming aware of the update. Do you think the time this TeamViewer revert took is an anomaly, therefore this issue should be closed; or is it something that should remain open for review/further discussion?

**Comment by denelon** [comment]
I think it was an anomaly. The GitHub APIs seem to have been running a bit slower than normal during this time as well which certainly affects when we get the notifications for the tooling to take the next steps.
