### ISSUE TITLE
Add shortcut in powershell to lunch app

### ISSUE THREAD

**Issue by khoshroomahdi** [microsoft/winget-cli#394]
# Description of the new feature/enhancement
In scoop, packages should have shortcut to run easily lunch app from powershell. For example:after install chrome by scoop, i could type chrome in powershell to lunch chrome. 

# Proposed technical implementation details (optional)

**Comment by megamorf** [comment]
@khoshroomahdi Hey, thanks for creating this issue. However, this seems to be a duplicate of #222 so I'd recommend you close this issue and subscribe to the one I linked.

PS: you probably mean launch instead of lunch ;-)

**Comment by khoshroomahdi** [comment]
#361
