### ISSUE TITLE
Support Qt installer type

### ISSUE THREAD

**Issue by BrandonWanHuanSheng** [microsoft/winget-cli#3945]
It look like https://github.com/microsoft/winget-pkgs/pull/129021 and https://github.com/microsoft/winget-pkgs/pull/129015 failed with Validation-Unattended-Failed which must required NestedInstallerType: Qt and it will support in the future

**Comment by Trenly** [comment]
Why can't you just use the unattended switches?
```
InstallerSwitches:
  Silent: in --am --al -c
  SilentWithProgress: in --am --al -c
```
