### ISSUE TITLE
Beta versions of apps

### ISSUE THREAD

**Issue by filiptronicek** [microsoft/winget-cli#395]
# Description of the new feature/enhancement

I think it would be nice to let people decide if they want to install the alpha or beta releases of the apps with winget. For example, the [Microsoft VS Code Insiders Build](https://code.visualstudio.com/insiders/) or [Mozilla Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/), just to let winget be more flexible

# Proposed technical implementation details (optional)
Perhaps a `--beta` or `@insider/@beta` or some flags like that in the CLI.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/147

**Comment by denelon** [comment]
Duplicate of #147
