### ISSUE TITLE
Winget stuck loading

### ISSUE THREAD

**Issue by jackra1n** [microsoft/winget-cli#3962]
### Brief description of your issue

When executing any winget command `winget search ...`, `winget install ...` the output will look like its loading for 1-2 seconds and then stop but in the terminal taskbar it will still be infinitely loading. 
Video example:
[Peek_2023-12-05_17-15.webm](https://github.com/microsoft/winget-cli/assets/45038833/fe958aa5-db68-48ed-bdfa-479c24b0a237)

### Steps to reproduce

Open Terminal
use any winget command

### Expected behavior

a search result showing up, or a installation process starting...

### Actual behavior

stick loading 

### Environment

```shell
Windows Package Manager v1.2.10691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2792
Package: Microsoft.DesktopAppInstaller v1.17.10691.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by denelon** [comment]
This is a very old version of WinGet.

You can either update App Installer in the Microsoft Store or install it using https://aka.ms/getwinget.

**Comment by jackra1n** [comment]
Thanks for the information @denelon
I tried to update the App Installer on Microsoft Store but I don't see where I can do that,
![image](https://github.com/microsoft/winget-cli/assets/45038833/8f66f7b0-5198-4b1f-94a9-9fb96026e9ac)

I also tried to execute the installation file you linked me but it says the app is already installed.
![image](https://github.com/microsoft/winget-cli/assets/45038833/040e7b11-1e62-47df-b0a4-73ccdbaabec4)

**Comment by jackra1n** [comment]
Does anyone know what I should try next? How can I fix this issue? Why is Microsoft shipping outdated and broken version of winget with Windows11_23H2 iso ??

**Comment by nathanpovo** [comment]
Ran into this same issue and found this issue from searching how to fix the problem.

Screenshot of the issue:

![image](https://github.com/microsoft/winget-cli/assets/17831160/d978e424-e333-41de-aa07-e197b355f840)

I was setting up a fresh install of Windows 11 (Enterprise, Version 23H2, OS build 22631.2861), found `winget` already installed (version 1.2.10691), and simply assumed that Windows would include the latest version of `winget` for me by default.

I found the store link from the page of documentation https://learn.microsoft.com/en-us/windows/package-manager/winget/ and could update it from there

![image](https://github.com/microsoft/winget-cli/assets/17831160/19e513f3-3833-4203-bab5-8468a57a7ad7)

Once updated (to version 1.6.3482), it worked as expected

![image](https://github.com/microsoft/winget-cli/assets/17831160/40176fa9-6a4f-4cd5-84a8-aab718ce393c)
