### ISSUE TITLE
Broken aka.ms link aka.ms/winget-command-configure

### ISSUE THREAD

**Issue by me-and** [microsoft/winget-cli#3967]
### Brief description of your issue

When running `winget configure --help`, the output includes the following:

    More help can be found at: https://aka.ms/winget-command-configure

This link is broken; it looks like the redirect it's supposed to use hasn't been set up or has expired. I expect it's supposed to point to https://learn.microsoft.com/en-gb/windows/package-manager/winget/configure

I've not checked, but I wouldn't be surprised if there are a whole class of similar links that are broken in the same way.

I'm running a preview build but I can see the commit that added the links – https://github.com/microsoft/winget-cli/commit/73f05cdf9b72eed991ccc5609f459f385cb9ec2f – had a "TODO" to create the URL which is still in place: https://github.com/microsoft/winget-cli/blob/master/src/AppInstallerCLICore/Commands/ConfigureCommand.cpp#L54

I'm a Microsoft FTE, but I'm reporting this as a winget user; I have no other involvement in winget as part of my job. That said, it does mean that if there isn't a more appropriate set of owners for this aka.ms link, I can be one of them…

**Comment by denelon** [comment]
Thanks for finding this one!  I just created the aka.ms link and tested it.

**Comment by denelon** [comment]
@JohnMcPMS you should be good to remove the "TODO".
