### ISSUE TITLE
[enhancment] Enable non-silent install

### ISSUE THREAD

**Issue by Yavor-aaa** [microsoft/winget-cli#398]
When you install something with `winget`, `winget` downloads the installer and runs it **silently**. But I think it will  be good if there was an option to run it **non-silently** (like you would just execute the exe,msi,etc... from file explorer). It can be a flag, for example `winget install Microsoft.dotnet --non-silent`.

**Comment by cderv** [comment]
I believe this would be `winget install —interactive` that is a current existing flag. 
But it is seems not yet supported from the spec 

https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv0.1.md

Relates to #365 too.

**Comment by denelon** [comment]
@Yavor-aaa there is a bug as @cderv points out. We have been looking at either `Silent` or `SilentWithProgress` as the default install mode selected by the client. This feature could represent the ability to change the default client configuration if you like.

**Comment by megamorf** [comment]
To me this issue is really just a copy of #365 and should be closed to avoid more duplication.

**Comment by Yavor-aaa** [comment]
> To me this issue is really just a copy of #365 and should be closed to avoid more duplication.

Okay, closing.
