### ISSUE TITLE
0x8a15005e : The server certificate did not match any of the expected values.

### ISSUE THREAD

**Issue by webertmartinsfreitas** [microsoft/winget-cli#3984]
### Brief description of your issue

Ao executar o comando `winget upgrade --all` como Administrador no Terminal é retornada uma mensagem de erro e o comando não é processado.

### Steps to reproduce

1. Acesse o menu iniciar;
2. Pesquise pelo programa Terminal;
3. Clique com o botão direito do mouse;
4. Execute o programa como administrador do sistema;
5. Dentro do terminal, execute o comando 'winget upgrade --all';

### Expected behavior

É esperado que seja realizada uma varredura do sistema em busca de atualizações disponíveis para os programas instalados. Caso seja localizado alguma atualização disponível a mesma é baixada e aplicada pela aplicação.

### Actual behavior

PS C:\Users\webert.freitas> winget upgrade --all
Falha na pesquisa da origem: msstore
Ocorreu um erro inesperado ao executar o comando:
0x8a15005e : The server certificate did not match any of the expected values.

### Environment

```shell
PS C:\Users\webert.freitas> winget --info
Gerenciador de Pacotes do Windows v1.6.3421
Copyright (c) Microsoft Corporation. Todos os direitos reservados.

Windows: Windows.Desktop v10.0.22631.2861
Arquitetura do Sistema: X64
Pacote: Microsoft.DesktopAppInstaller v1.21.3421.0

Diretórios Winget
-----------------------------------------------------------------------------------------------------------------------
Registros                                 %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalSta…
Configurações do Usuário                  %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalSta…
Diretório de Links Portáteis (Usuário)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Diretório de Links Portáteis (Computador) C:\Program Files\WinGet\Links
Raiz do Pacote Portátil (Usuário)         %LOCALAPPDATA%\Microsoft\WinGet\Packages
Raiz do Pacote Portátil                   C:\Program Files\WinGet\Packages
Raiz do Pacote Portátil (x86)             C:\Program Files (x86)\WinGet\Packages
Downloads do Instalador                   F:\OneDrive\Pessoal\OneDrive\Downloads

Links
-------------------------------------------------------------------------------
Política de Privacidade https://aka.ms/winget-privacy
Contrato de Licença     https://aka.ms/winget-license
Avisos de Terceiros     https://aka.ms/winget-3rdPartyNotice
Home page               https://aka.ms/winget
Termos da Windows Store https://www.microsoft.com/en-us/storedocs/terms-of-sale

Configuração do Administrador             Estado
------------------------------------------------------
LocalManifestFiles                        Desabilitado
BypassCertificatePinningForMicrosoftStore Desabilitado
InstallerHashOverride                     Desabilitado
LocalArchiveMalwareScanOverride           Desabilitado
```

**Comment by webertmartinsfreitas** [comment]
Adicionei os logs de erro do WinGet com Verbose ativados.

[WinGet-2023-12-16-00-48-35.886.log](https://github.com/microsoft/winget-cli/files/13691246/WinGet-2023-12-16-00-48-35.886.log)
[WinGet-2023-12-16-00-48-48.691.log](https://github.com/microsoft/winget-cli/files/13691247/WinGet-2023-12-16-00-48-48.691.log)
[WinGet-2023-12-16-00-49-01.150.log](https://github.com/microsoft/winget-cli/files/13691248/WinGet-2023-12-16-00-49-01.150.log)
[WinGet-2023-12-16-00-49-13.766.log](https://github.com/microsoft/winget-cli/files/13691249/WinGet-2023-12-16-00-49-13.766.log)

**Comment by denelon** [comment]
This issue has been resolved in WinGet 1.7.

**Comment by webertmartinsfreitas** [comment]
> This issue has been resolved in WinGet 1.7.

Thank you for the good work.
