### ISSUE TITLE
running `winget` shows nothing and waits indefinitely

### ISSUE THREAD

**Issue by Ciki** [microsoft/winget-cli#3995]
### Brief description of your issue

running `winget` or `winget --info` in powershell does nothing, just an empty line with flickering cursor

Please help me what to do.. I've tried multiple commands to reinstall winget to no avail. 

### Steps to reproduce

I don't know, 

### Expected behavior

`winget` command works

### Actual behavior

an empty line with flickering cursor is shown

### Environment

```shell
Windows: Win 11 Pro, build 22631.2861
```

**Comment by mdanish-kh** [comment]
What version of winget are you using? (`winget -v` to find out)

This looks related to https://github.com/microsoft/winget-cli/issues/3652 where some older versions had their CDN retired.

Can you upgrade to the latest version of winget from `https://aka.ms/getwinget`  or upgrade the "App Installer" package from Microsoft Store and try again?

**Comment by Ciki** [comment]
@mdanish-kh thanks for your reply and sorry for my late response, I haven't noticed earlier. As I wrote originally, running `winget <anything>` just stalls my console and does not render/do anything (for 10 minutes at least). Several things stopped working on my windows, unfortunately, so I will have to reinstall it probably (I cannot run any windows app, Store app is missing, etc.)
