### ISSUE TITLE
python launcher 3.12 not getting installed

### ISSUE THREAD

**Issue by pleabargain** [microsoft/winget-cli#4007]
### Brief description of your issue

Not installing

![image](https://github.com/microsoft/winget-cli/assets/640846/1672e3d2-f6ba-464f-a54d-7ce6b9fdf7d0)

### Steps to reproduce

 winget upgrade --all

### Expected behavior

python launcher 3.12 should get installed

### Actual behavior

python launcher 3.12 is not being installed

### Environment

```shell
PS C:\Users\denni> winget --info
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3803
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Ashcora** [comment]
I have the same issue with

`Python Launcher Python.Launcher < 3.12.0 3.12.0    winget`

when running

`winget upgrade --all --accept-source-agreements --accept-package-agreements --include-unknown --silent`

as Administrator.

**Comment by mdanish-kh** [comment]
Can you share the output of `winget list python`?

**Comment by Ashcora** [comment]
Please find the output within the screenshot below.

<img width="675" alt="image" src="https://github.com/microsoft/winget-cli/assets/58374721/5acc0dd6-0aa3-450f-854a-cad5bcde6cf9">

**Comment by mdanish-kh** [comment]
> Update: I found in the package manager another (old) Python Launcher 11 entry.
When uninstalling this package, it works now for me.

That's what I suspected was going on. This is a case where side-by-side installations are not handled properly. Currently one needs to manually remove the old version to unblock the upgrade behavior.

 Related to
- https://github.com/microsoft/winget-cli/issues/2129

**Comment by Ashcora** [comment]
Thanks for confirming and the link, @mdanish-kh.

But I am not sure if this also fits to @pleabargain's issue.
Did you already check your installed apps? Is your issue having the same roots?

**Comment by pleabargain** [comment]
Am I in the right place?
winget list shows 2 python.launchers but winget won't let me uninstall

![image](https://github.com/microsoft/winget-cli/assets/640846/5006a47a-229e-410b-9ad7-fca5de7adcbe)

**Comment by mdanish-kh** [comment]
> Am I in the right place? winget list shows 2 python.launchers but winget won't let me uninstall
> 

This is a case where side-by-side installations are not handled properly (see above linked issue for more details). You will have to manually remove the older version from `appwiz.cpl` (Control Panel) or Apps&Features

**Comment by soredake** [comment]
Related https://github.com/microsoft/winget-cli/issues/3656

**Comment by denelon** [comment]
We've been working on the side-by-side scenarios. You could try the latest release and enable the experimental feature on:
* https://github.com/microsoft/winget-cli/releases/tag/v1.8.924-preview

Please provide feedback at:
* https://github.com/microsoft/winget-cli/discussions/4281

**Comment by denelon** [comment]
You should now be able to uninstall a specific version using WinGet 1.8.
