### ISSUE TITLE
winget does not create a links for portable packages in user scope

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-cli#4009]
### Brief description of your issue

`winget install -h --accept-package-agreements --accept-source-agreements Rclone.Rclone yt-dlp.yt-dlp Gyan.FFmpeg lycheeverse.lychee Haali.WinUtils.lswitch`

After doing this my Links folder are still empty:
![image](https://github.com/microsoft/winget-cli/assets/5204968/5924eff1-2e24-4a1e-8b8a-2bd5c987d83c)

Installing packages with sudo and scope=machine makes links appear in global directory (`C:\Program Files\WinGet\Links`)

### Steps to reproduce

1) Install latest stable/preview build of winget.
2) Do `winget install -h --accept-package-agreements --accept-source-agreements Rclone.Rclone yt-dlp.yt-dlp Gyan.FFmpeg lycheeverse.lychee Haali.WinUtils.lswitch`
3) Go to `%LOCALAPPDATA%\Microsoft\WinGet\Links`
4) No links, PATH is also not updated.

### Expected behavior

Links should be created.

### Actual behavior

Links are not created.

### Environment

```shell
❯ winget --info
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2861
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0
```

**Comment by Trenly** [comment]
Symlinks can only be created if you are running the install as admin or if Developer Mode is enabled. When neither of these are true, the folder to the executable should be added to the path

**Comment by soredake** [comment]
Yeah, i forgot that symlinks need admin rights, anyway, most packages are not added to PATH, even after removing them and installing again.
