### ISSUE TITLE
Publish WinGet as an MSIX with dependencies included

### ISSUE THREAD

**Issue by felipecrs** [microsoft/winget-cli#401]
# Description of the new feature/enhancement

Publish the WinGet installer as an MSIX with the dependencies included, just like Windows Terminal.

# Motivation

Currently, the WinGet `.appxbundle` has two required dependencies from `VCLibs`. This prevents people to install in environments where there is no Microsoft Store available, such as the Windows Sandbox. This would help https://github.com/microsoft/winget-pkgs/pull/827.

# Proposed technical implementation details

Follow the same approach of Windows Terminal, tracked on https://github.com/microsoft/terminal/issues/3097 and https://github.com/microsoft/terminal/pull/5661.

This can also help -> https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net

**Comment by driver1998** [comment]
I guess the better way would be asking MS to release those dependency package outside the store, in a support document or something.

They provide direct appx downloads for WSL distros in WSL docs after all.

**Comment by grzegor** [comment]
> [...] release those dependency package outside the store

They're available to download from the [Microsoft docs site over here](https://docs.microsoft.com/en-us/troubleshoot/cpp/c-runtime-packages-desktop-bridge).

**Comment by felipecrs** [comment]
Not all of the needed deps seems to be there, as per my comments in the TestSandbox PR

**Comment by grzegor** [comment]
Oh, right - just read about VCLibs in your original post. I didn't realize there's also a separate VCLibsUWP package.

**Comment by denelon** [comment]
@felipecrs we're not likely to pull the dependencies into WinGet and include them in our bundle. We've created the Repair-WinGetPackageManger cmdlet in the Microsoft.WinGet.Client powershell module to make it easier to bootstrap/upgrade WinGet when the Microsoft Store isn't available. We've also added the App Installer (with "winget" moniker) to the community repository along with the dependencies. 

I've also got a sample WinGet configuration over at https://aka.ms/dsc.yaml for launching the Windows Sandbox and bootstrapping WinGet inside the sandbox. 

>Note: I've refactored it to match our guidance over at Microsoft Learn rather than using the Repair-WinGetPackageManager and that PR hasn't been merged as of today.

**Comment by abyrd-phx** [comment]
@denelon Are there instructions available for bootstrapping winget from a terminal in an environment like Windows Sandbox? Packaging a program into a single file with all it's dependencies is a standard software practice. Currently with winget I have to jump through hoops to manually download and install dependencies from a script and that fails every time the dependency set changes.

```
function Install-WinGet
{
	# Using github instead of the store since it's not guaranteed to be installed (Windows Sandbox,
	# corporate environments, etc).
	# https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget-on-windows-sandbox

	# We have to manually grab dependencies. This is fragile and will hopefully be fixed one day.
	# https://github.com/microsoft/winget-cli/issues/401
	$wingetUrls = @(
		"https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx",
		"https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.8.6/Microsoft.UI.Xaml.2.8.x64.appx",
		"https://aka.ms/getwinget"
	)

	# Disable progress because it slows downloads to a crawl
	$progressPreference = "silentlyContinue"
	$tempDir = "dotfiles-temp"
	Write-Information "Downloading WinGet and its dependencies..."
	New-Item $tempDir -ItemType Directory -Force | Out-Null
	for ($i = 0; $i -lt $wingetUrls.Length; $i++)
	{
		$url = $wingetUrls[$i]
		$filename = "$tempDir\WingetFile_$i.msixbundle";

		Invoke-WebRequest -Uri $url -OutFile $filename
		Add-AppxPackage $filename
		Remove-Item $filename
	}
	Remove-Item $tempDir
	$progressPreference = "Continue"
}
```

**Comment by akbyrd** [comment]
@denelon Are there instructions available for bootstrapping winget from a terminal in an environment like Windows Sandbox? Packaging a program into a single file with all it's dependencies is a standard software practice. Currently with winget I have to jump through hoops to manually download and install dependencies from a script and that fails every time the dependency set changes.

```
function Install-WinGet
{
	# Using github instead of the store since it's not guaranteed to be installed (Windows Sandbox,
	# corporate environments, etc).
	# https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget-on-windows-sandbox

	# We have to manually grab dependencies. This is fragile and will hopefully be fixed one day.
	# https://github.com/microsoft/winget-cli/issues/401
	$wingetUrls = @(
		"https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx",
		"https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.8.6/Microsoft.UI.Xaml.2.8.x64.appx",
		"https://aka.ms/getwinget"
	)

	# Disable progress because it slows downloads to a crawl
	$progressPreference = "silentlyContinue"
	$tempDir = "dotfiles-temp"
	Write-Information "Downloading WinGet and its dependencies..."
	New-Item $tempDir -ItemType Directory -Force | Out-Null
	for ($i = 0; $i -lt $wingetUrls.Length; $i++)
	{
		$url = $wingetUrls[$i]
		$filename = "$tempDir\WingetFile_$i.msixbundle";

		Invoke-WebRequest -Uri $url -OutFile $filename
		Add-AppxPackage $filename
		Remove-Item $filename
	}
	Remove-Item $tempDir
	$progressPreference = "Continue"
}
```

**Comment by felipecrs** [comment]
At this point, I think there's no good reason for Windows Sandbox not to come with WinGet preinstalled btw. 😄

**Comment by Trenly** [comment]
> @denelon Are there instructions available for bootstrapping winget from a terminal in an environment like Windows Sandbox? Packaging a program into a single file with all it's dependencies is a standard software practice. Currently with winget I have to jump through hoops to manually download and install dependencies from a script and that fails every time the dependency set changes.

This is what I use inside a PowerShell script

```
Install-PackageProvider -Name NuGet -Force
Install-Module -Name Microsoft.WinGet.Client -Force -Repository PSGallery
Repair-WinGetPackageManager
```

**Comment by denelon** [comment]
> At this point, I think there's no good reason for Windows Sandbox not to come with WinGet preinstalled btw. 😄

I'm working with the Windows Sandbox team on doing this 😊

**Comment by denelon** [comment]
@akbyrd: https://learn.microsoft.com/windows/package-manager/winget/#install-winget-on-windows-sandbox
