### ISSUE TITLE
Detecting current versions for self-updating software

### ISSUE THREAD

**Issue by MarkSFrancis** [microsoft/winget-cli#4013]
### Description of the new feature / enhancement

When viewing currently installed versions in `winget`, it uses the version of the app that was last installed / updated with the CLI. 
Because most apps over time have been built for Windows with self-updating mechanisms included (such as Google Chrome, Discord, etc.), often the version number reported by `winget` does not agree with the version number provided by the application. This causes incorrect information to be displayed by `winget`, which leads to bad update behavior (such as unnecessary updates being ran). 

### Proposed technical implementation details

I recognize that any package may invent its own way of handling updates, and I'm not very familiar with how versions are handled on Windows. I could see several possible solutions:
1. Allow packages to update the version number listed by `winget`, so that standard updating mechanisms (like [`update-electron-app`](https://github.com/electron/update-electron-app) and `msi`) can also be updated to support reporting updates to `winget` (such as making their own registry changes as per `winget`'s documentation). This solution should be done such that they can still function even if `winget` is not (yet) installed on the machine
2. Add a feature to the `winget-pkgs` manifests that specifies how `winget` can get version information from a package. This may cause performance issues however, especially if it requires mechanisms like spawning the process and running `-version` to find the version number

These solutions are not mutually exclusive, so perhaps the 1st could be the default, and then the 2nd allows the package to overwrite it if it needs to (such as for legacy reasons). 

Please note that I have no idea if there is _already_ a recognized standard for how to manage version numbers built into Windows (such as how the version number is shown in Apps & Features). If this mechanism is already available, perhaps `winget` should simply interop with this mechanism and treat it as the source of truth. Then if packages don't set this version number properly, perhaps the `winget` team might make contributions to the community themselves, in order to help leading software to update those values as they should. Obviously some packages do not manage their own version numbers at all (such as lightweight portable apps), and in those cases, `winget` might need to manage these version numbers instead.

**Comment by mdanish-kh** [comment]
> Please note that I have no idea if there is already a recognized standard for how to manage version numbers built into Windows (such as how the version number is shown in Apps & Features).

That's exactly what `winget` uses currently. It takes the `DisplayVersion` string from the registry, that's visible as the version field in Control Panel / Apps&Features, as the source of truth for an app's version.

What's likely happening here is that the application is not updating this version in the registry in the self-update scenario.

> Obviously some packages do not manage their own version numbers at all (such as lightweight portable apps), and in those cases, winget might need to manage these version numbers instead.

winget treats portables as first-class packages and takes it upon itself to write the Registry entries for them and make them visible in Control Panel / Apps&Features. By doing this, winget can leverage the existing approach of having Registry / Control Panel / Apps&Features as the source of truth for a package.

For non-portable installer types, winget lets the installer provided by the publisher handle what is written to registry. If an installer does not write a version to the Registry, `winget` shows a sentinel value "Unknown"

See - [Why does a package have the version "Unknown"?](https://github.com/microsoft/winget-pkgs/blob/master/FAQ.md#why-does-a-package-have-the-version-unknown)

**Comment by MarkSFrancis** [comment]
Thanks for the explanation - sounds like the feature is already present, just not working in the apps I used. I'll close this issue
