### ISSUE TITLE
Failed when opening source(s)

### ISSUE THREAD

**Issue by Pixel556** [microsoft/winget-cli#4018]
### Brief description of your issue

![image](https://github.com/microsoft/winget-cli/assets/95143545/5038b0e2-6a97-4c1c-9c41-2163ecc1079e)
Winget gives me an error every time I try to use `winget show` or `winget install`, saying that "Failed when opening source(s); try the source reset command if the problem persists.

I tried to do `winget source reset --force` and `winget source reset`, it was successful but the problem persisted. I also tried `winget source update` which outputs this:

`PowerShell 7.4.0`
`PS C:\Windows>winget source update`
`Updating all sources...`
`Updating source: msstore...`
`Done`
`Updating source: winget...`
`Cancelled`
`PS C:\Windows>_`

I don't interrupt the process while winget is updating its sources, but for some reason it automatically cancels at `Updating source: winget...`.

Can anybody help me this? I'm new to Winget, so I don't really know much.

### Steps to reproduce

Only thing needed to do is: `winget show Insert.AnyPackageHere` or `winget install Insert.AnyPackageHere`

### Environment

```shell
Windows: Windows.Desktop v10.0.22631.2861
System Architecture: Arm64
Package: Microsoft.DesktopAppInstaller v1.20.441.0
```

**Comment by Trenly** [comment]
What is the full output of `winget --info`

**Comment by Pixel556** [comment]
`Windows Package Manager (Preview) v1.5.441-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2861
System Architecture: Arm64
Package: Microsoft.DesktopAppInstaller v1.20.441.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled`

**Comment by Pixel556** [comment]
`Windows Package Manager (Preview) `v1.5.441-preview`
`Copyright (c) Microsoft Corporation. All rights reserved.`

`Windows: Windows.Desktop v10.0.22631.2861`
`System Architecture: Arm64`
`Package: Microsoft.DesktopAppInstaller v1.20.441.0`

`Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir`

`User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json`

`Links`
`---------------------------------------------------------------------------`
`Privacy Statement   https://aka.ms/winget-privacy`
`License Agreement   https://aka.ms/winget-license`
`Third Party Notices https://aka.ms/winget-3rdPartyNotice`
`Homepage            https://aka.ms/winget`
`Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale`

`Admin Setting                             State`
`--------------------------------------------------`
`LocalManifestFiles                        Disabled`
`BypassCertificatePinningForMicrosoftStore Disabled`
`InstallerHashOverride                     Disabled`
`LocalArchiveMalwareScanOverride           Disabled`

**Comment by Trenly** [comment]
> `Windows Package Manager (Preview) v1.5.441-preview`


You will need to update your version of WinGet, since the original CDN which was hardcoded into version 1.5 has been retired.

* https://github.com/microsoft/winget-cli/issues/3652

**Comment by Pixel556** [comment]
> You will need to update your version of WinGet
And how am I supposed to do that? Running `winget source update` doesn't do anything. It just updates the source for the Microsoft Store but not Winget itself.

**Comment by Trenly** [comment]
> And how am I supposed to do that? Running `winget source update` doesn't do anything. It just updates the source for the Microsoft Store but not Winget itself.

As mentioned in the issue, you can use the installer from https://aka.ms/getwinget. Or, since you’re currently using a preview version, you can download the latest preview version from the GitHub releases pge

**Comment by denelon** [comment]
Just for others who might also want to stay on prerelease versions we have https://aka.ms/getwingetpreview available.
