### ISSUE TITLE
[JetBrains.DataGrip] it reports an update version even if installed the latest one

### ISSUE THREAD

**Issue by ali50m** [microsoft/winget-cli#4019]
### Brief description of your issue

winget will report update for `JetBrains.DataGrip` even I have installed the latest one with winget.

### Steps to reproduce

```
winget install JetBrains.DataGrip
```
then check update
```
winget update
```

### Expected behavior

won`t see update for `JetBrains.DataGrip`.

### Actual behavior

when excute `winget update` in cli, it will promps there is an **update** for `JetBrains.DataGrip`.

### Environment

```shell
win10-64bit 21h2
winget v1.6.3482
JetBrains.DataGrip 2023.3.2
```

**Comment by Trenly** [comment]
What is the output of `winget list DataGrip`

**Comment by Trenly** [comment]
> Just check with "winget update", I can`t see the update for DataGrip now. Is it already fixed?

It's possible. I did see that there was a mistake in the manifest which was fixed yesterday, which could have resolved the issue
