### ISSUE TITLE
Not all strings are localized

### ISSUE THREAD

**Issue by JohnMcPMS** [microsoft/winget-cli#403]
# Brief description of your issue

Not all strings have been moved to localized resources.

# Steps to reproduce

1. Write the code
2. File an Issue to track unfinished work

# Expected behavior

All strings being output to the console are in localized resources.

# Actual behavior

Some strings are not.

# Environment

You can trust me on this one :wink:

**Comment by JohnMcPMS** [comment]
I put this in the backlog as the default, but I think it needs to be fixed sooner rather than later.

**Comment by megamorf** [comment]
I'd be really happy if you added an environment variable that would enable me to override the winget locale (like `LANG=en_US.UTF-8 <command>` in Linux). This would also help you as developers to get output for bug reports in a language that you can understand.

**Comment by denelon** [comment]
At this point, I believe all of the strings have been localized. As we run into them, we fix them on a case by case basis.
