### ISSUE TITLE
Updating apps that where already updated

### ISSUE THREAD

**Issue by Alecerzea** [microsoft/winget-cli#4031]
### Brief description of your issue

Its only happening with two apps in my pc for the moment

### Steps to reproduce

winget upgrade --all --include-unknown

### Expected behavior

It only should say, "No found criteria packages"

### Actual behavior

![image](https://github.com/microsoft/winget-cli/assets/85199063/5036191e-fb62-470e-b5fb-abbf82e6cf87)

### Environment

```shell
Windows Package Manager v1.6.3482

Windows: Windows.Desktop v10.0.22631.2861
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0
```

**Comment by Trenly** [comment]
It looks like someone made a mistake in the manifest; Should be fixed by the above PR

**Comment by Alecerzea** [comment]
It once again reocurring with same driver easy and now yt-dlp 
![image](https://github.com/user-attachments/assets/a8f36fc0-3c5c-4c72-90a2-abd0be58ab30)
