### ISSUE TITLE
SSL cert is invalid for cdn.winget.microsoft.com

### ISSUE THREAD

**Issue by LawrenceHwang** [microsoft/winget-cli#4091]
### Brief description of your issue

Hello,

It seems to me the SSL cert is invalid for `cdn.winget.microsoft.com`. As a side effect, this causes `winget upgrade` to return error such as `Failed in attempting to update the source: winget`.

- winget version: v1.6.3482

### Steps to reproduce

Access `https://cdn.winget.microsoft.com/cache` from browser or cli.

*cli - powershell*

```powershell
> invoke-webrequest -UseBasicParsing -Uri https://cdn.winget.microsoft.com -verbose pwsh
VERBOSE: Requested HTTP/1.1 GET with 0-byte payload
Invoke-WebRequest: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors
```

### Expected behavior

The url is accessible without error.

### Actual behavior

Getting certificate error. Screenshot shows the error:

<img width="478" alt="Screenshot 2024-01-20 114556" src="https://github.com/microsoft/winget-cli/assets/16510876/b075de60-bec1-419b-b63f-e7a84ff591e2">

### Environment

```shell
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3007
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads
```
```

**Comment by LawrenceHwang** [comment]
From a different computer, the SSL cert was returned correctly. So this may be an issue with CDN not fully refreshed. To help with troubleshooting, here is the browser request id (to [https://cdn.winget.microsoft.com/cache](https://cdn.winget.microsoft.com/cache)) that returned invalid the SSL cert in earlier screenshot.

`RequestId:10307c21-f01e-002a-46db-4bdc22000000`

**Comment by JohnMcPMS** [comment]
Are you sure that there is no HTTP intercept (ex. Fiddler), DNS redirect (hosts file), or other MITM, intentional or otherwise?  This seems like an issue specific to the one machine at this time.

**Comment by LawrenceHwang** [comment]
Thank you @JohnMcPMS, it does look like machine specific. I'll check on my side.
