### ISSUE TITLE
Validation should also check folder name

### ISSUE THREAD

**Issue by mrlacey** [microsoft/winget-cli#411]
# Brief description of your issue

If the YAML file is in a folder structure that does not match the publisher and application name the CLI validation test (`winget validate <manifest>`) will pass but when submitting to the repository it will fail if the naming isn't the same. 
This can lead to unexpected failures in the PR which could have been caught locally/earlier.

# Steps to reproduce

* Create a YAML file for `Publisher.AppName` v1.0
* put it in the folder '/Publisher/ApName' (Note that there is only one 'p')
* Run the validation command on the file

# Expected behavior

The process should validate that the folder structure does not match the expected values based on the contents of the YAML file and so may fail ingestion into the manifest repository.
_(This could just be a warning, not a full-on failure._)

# Actual behavior

Validation passes fine and the typo is only noticed when the PR is validated.

# Environment

```none
[winget --info]
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18363.836
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

```

**Comment by denelon** [comment]
@mrlacey the client validation is only looking at file contents.  The filename and path conventions are primarily used for submitting manifests to the GitHub community repository, and the structure may need to change in the future. I am wondering if you think just having a hint or note about the filename and path structure would be sufficient?

`winget validate <manifest>`
`Manifest validation succeeded.`
`Please use "/manifests/<publisher>/<package>/<version>.yaml" for community submission`

**Comment by mrlacey** [comment]
@denelon yes a hint would be fine.
The issue was that because I built a package that passed validation I was surprised when submitting to the package repo failed. Especially as it was a typo that broke a convention I wasn't totally clear about. 
Having this extra check (and hint) could save others (and maybe myself again in the future) when possible mistakes are caught earlier.

**Comment by denelon** [comment]
@mrlacey, we've made substantial changes to the schema and the validation process. I'm going to go ahead and close this Issue as I believe it has been resolved. Thank you for submitting the Issue.
