### ISSUE TITLE
Exclude option

### ISSUE THREAD

**Issue by TheNetMasterA** [microsoft/winget-cli#4114]
### Description of the new feature / enhancement

In certain situations, when carrying out massive updates, it is possible that one of the packages may have an error in its latest version. 

Despite this, it might still be necessary to continue using the 'upgrade --all' option to update the other components. 

It would be extremely useful to have an exception that supports wildcard characters. 

For example, in my current situation, a function like '`-except *java*`' would be beneficial.

**Comment by mdanish-kh** [comment]
This can be achieved using [winget pin](https://learn.microsoft.com/en-us/windows/package-manager/winget/pinning) command. It doesn't support wildcard characters at the moment, but that request could be raised as a separate issue (or you could edit this one)
