### ISSUE TITLE
CLI and PowerShell module for the same package show different versions

### ISSUE THREAD

**Issue by denis-komarov** [microsoft/winget-cli#4115]
### Brief description of your issue

CLI and PowerShell module for the same package show different versions.

### Steps to reproduce

```
winget search --id QuestSoft.QTranslate --source winget
```
```
Name       Id                   Version
---------------------------------------
QTranslate QuestSoft.QTranslate 6.10.0
```
```powershell
Find-WinGetPackage -Id QuestSoft.QTranslate -Source winget
```
```
Name       Id                   Version Source
----       --                   ------- ------
QTranslate QuestSoft.QTranslate 6.9.0   winget
```

### Expected behavior

CLI and PowerShell module for the same package show the same versions

### Actual behavior

CLI and PowerShell module for the same package show different versions

### Environment

```shell
Windows Package Manager v1.6.3482
Windows: Windows.Desktop v10.0.19045.2604
System Architecture: X64
```

**Comment by denelon** [comment]
Could you reproduce this?

What version of WinGet and what version of Microsoft.WinGet.Client is on the device?

 I just tested and I got the same version for both:

```
 denelon  winget search --id QuestSoft.QTranslate --source winget
Name       Id                   Version
---------------------------------------
QTranslate QuestSoft.QTranslate 6.10.0
 denelon 
 denelon  Find-WinGetPackage -Id QuestSoft.QTranslate -Source winget

Name       Id                   Version Source
----       --                   ------- ------
QTranslate QuestSoft.QTranslate 6.10.0  winget
```

**Comment by Trenly** [comment]
@denis-kmarov - There has been a new release of both the client and the PowerShell module. Can you please check if this issue still occurs after updating both?
