### ISSUE TITLE
Broken winget, yet again

### ISSUE THREAD

**Issue by IntNinja** [microsoft/winget-cli#4117]
### Brief description of your issue

When i run `winget install something` the text of terminal turns blue and then nothing happens

### Steps to reproduce

1) Open admin powershell
2) run `winget install something` or any command
3) outputs a / and text turns blue and nothing happens

### Expected behavior

it should work like normal without just outputting color change?

### Actual behavior

outputting blue color

![image](https://github.com/microsoft/winget-cli/assets/116146426/28991a0b-2d79-4dcb-a4b3-7e221e714bad)

### Environment

```shell
Windows Package Manager v1.2.10691
Copyright (c) Microsoft Corporation. All rights reserved.
Windows: Windows.Desktop v10.0.22631.3085
Package: Microsoft.DesktopAppInstaller v1.17.10691.0  

and Nope
```

**Comment by Trenly** [comment]
@intninja - You need to update your version of WinGet to 1.6 or the 1.7-preview. The CDN serving the 1.2 version has been retired

* #3652

**Comment by IntNinja** [comment]
Okay i had to check microsoft store to update the app installer, closing.
