### ISSUE TITLE
Version mismatch with grepWin

### ISSUE THREAD

**Issue by dl1mx** [microsoft/winget-cli#4126]
### Brief description of your issue

I'm updating my Windows 10 programs regulary with the winget tool. After I installed grepWin version 2.0.15, I always get an update recommendation from winget, although version 2.0.15 is the only installed version. Installation with grepWin-2.0.15-x64.msi for all users.

### Steps to reproduce

If I look into "Programs & Feature" I get the following version:
![installed](https://github.com/stefankueng/grepWin/assets/3036287/3d8bda00-bbd0-4945-8541-c92aa8c41059)

And winget show the following dialog:
![winget](https://github.com/stefankueng/grepWin/assets/3036287/a7125aad-2dd9-419b-b721-42bf22e0f45a)

But grepWin has version 
![version](https://github.com/stefankueng/grepWin/assets/3036287/f17691d6-30a1-4596-8ac3-e54614574b95)

### Expected behavior

Why is the old version of 2.0.1232 listed in Windows programs? Maybe it has to do with version.txt from git, which shows 2.0.15.1232.

### Actual behavior

grepWin version 2.0.15 is always recommended to update, but this version is already installed

### Environment

```shell
Windows-Paket-Manager v1.6.3482
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19045.3930
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.21.3482.0
```

**Comment by Trenly** [comment]
> Why is the old version of 2.0.1232 listed in Windows programs? Maybe it has to do with version.txt from git, which shows 2.0.15.1232.

It's because this is what the GrepWin installer writes to the registry. At its core, WinGet simply downloads and runs the installer that GrepWin provides.

**Comment by stephengillie** [comment]
This should be moved to the [winget-pkgs](https://github.com/microsoft/winget-pkgs) repo.
