### ISSUE TITLE
Per User / Per Machine installation selection

### ISSUE THREAD

**Issue by Annihilator** [microsoft/winget-cli#413]
Currently, winget defaults to (and seems to encourage), the use of per-user installers, and provides no method of selecting at installation time a per-machine installation for software that originally provides that choice. I propose implementing a switch/commandline parameter which would enable the end user to choose whether the installation performed would be per-user or per-machine. Some software offers this choice within their own installer (example: WinSCP), so a commandline parameter for the installer would be appropriate for such cases, and other software has completely separate per-mahine installers available; those would have to point to two different download URLs in the manifest, and select one depending on the choice (example: MS VS Code).

Also, the following logic would possibly be useful:
- if running in an elevated command prompt: default to per-machine
- if running in user context: default to per-user

**Comment by doctordns** [comment]
I would like to see this issue resolved via a winget installation manifest. A manifest could tell winget HOW to use the installer (run it as an exe, copy as a zip, etc).

**Comment by megamorf** [comment]
@doctordns Please don't comment on duplicate issues (this one has been closed already days ago as well). Use the original issues instead.
