### ISSUE TITLE
Can't upgrade a package whose newest version number is shorter than the installed number

### ISSUE THREAD

**Issue by github4jojo** [microsoft/winget-cli#4141]
Something like

C:\Windows\System32>winget upgrade
Name                                             ID                                Version   Verfügbar  Quelle
--------------------------------------------------------------------------------------------------------------
Advanced SystemCare                         IObit.AdvancedSystemCare          17.2.0    17.2.0.191 winget
Driver Booster 11                                IObit.DriverBooster               11.2.0    11.2.0.46  winget

can not be updated.
In most common case, the newest version is installed.
But winget believe, 17.2.0 is newer than 17.2.0.191!

How to solve it?
What is the solution?

Thanks!

**Comment by denelon** [comment]
Can you share the output from `winget list` showing the installed version and the suggested version?

It looks like one of our moderators added PRs for the versions mentioned.

**Comment by denelon** [comment]
It looks like the output from `winget upgrade` is showing the newer versions available in the "Available" column.

**Comment by github4jojo** [comment]
> Can you share the output from `winget list` showing the installed version and the suggested version?
> 
> It looks like one of our moderators added PRs for the versions mentioned.

How to share this 'winget list'?
Maybe like an attached file?
Here we are...

![Screenshot 2024-02-06 015151](https://github.com/microsoft/winget-cli/assets/138662017/3f77c43b-20c1-4fd1-ba16-c9c050210367)

**Comment by denelon** [comment]
That's from WinGet UI which is a different project.

This GitHub project is for WinGet, the CLI (Command Line Experience) running behind WinGetUI.

**Comment by github4jojo** [comment]
> That's from WinGet UI which is a different project.
> 
> This GitHub project is for WinGet, the CLI (Command Line Experience) running behind WinGetUI.

Ok!
Here we are...

C:\Windows\System32>winget list | more
Name                                     ID                                        Version            Verf├╝gbar  Quelle
-----------------------------------------------------------------------------------------------------------------------
Upscayl 2.5.1                            2239ca62-47a7-52bf-bffa-6c900931774b      2.5.1
...
WhatsApp                                 5319275A.WhatsAppDesktop_cv1g1gvanyjgm    2.2401.5.0
...
7-Zip 23.01 (x64)                        7zip.7zip                                 23.01                         winget
Advanced SystemCare                      IObit.AdvancedSystemCare                  17.2.0             17.2.0.191 winget
...
CPUID CPU-Z 2.09                         CPUID.CPU-Z                               2.09                          winget
...
Creative Sound Blaster USB Audio DriverÔÇª CtKsUSBDrvInst_is1                        1.0.03.02
Creative USB Native ASIO                 CtUsAsio_is1                              1.0.00.00
...
Driver Booster 11                        IObit.DriverBooster                       11.2.0             11.2.0.46  winget
...
GIMP 2.10.36                             GIMP.GIMP                                 2.10.36                       winget
.....

**Comment by denelon** [comment]
OK, it looks like newer versions are being offered. Are the upgrades failing?

**Comment by denelon** [comment]
I'm guessing the installer isn't updating the version in the registry after the upgrade. WinGet is looking at registry data to determine the version. What is displayed in Windows Apps & Features after installing the latest version?

**Comment by github4jojo** [comment]
> I'm guessing the installer isn't updating the version in the registry after the upgrade. WinGet is looking at registry data to determine the version. What is displayed in Windows Apps & Features after installing the latest version?

How to show it?
Like this...?
![3_winget](https://github.com/microsoft/winget-cli/assets/138662017/a97eb072-1016-4573-8570-02f19b7a30a6)

**Comment by Trenly** [comment]
@denelon - this is an issue with the manifests. The manifests were submitted with an incorrect PackageVersion which is higher than the version the application writes to registry. The two linked PRs should close this issue

**Comment by denelon** [comment]
@Stuntman58 I'm not sure if it's a bug in GitHub or if you are following something on GitHub leading to the e-mail notifications.
