### ISSUE TITLE
Installing TortoiseHg.TortoiseHg results in a InternetOpenUrl() failed error

### ISSUE THREAD

**Issue by PissedCapslock** [microsoft/winget-cli#417]
# Brief description of your issue

Trying to install Mercurial correctly downloads the TortoiseHg installer, but fails when executing it with the following error

````
An unexpected error occurred while executing the command:
InternetOpenUrl() failed.
0x80072ee2 : unknown error
````
# Steps to reproduce

Run `winget install mercurial`

# Expected behavior

I expect that mercurial/TortoiseHg gets installed

# Actual behavior

````
An unexpected error occurred while executing the command:
InternetOpenUrl() failed.
0x80072ee2 : unknown error
````

# Environment

```none
[winget --info]
Windows Package Manager v0.1.41331 Preview
Windows: Windows.Desktop v10.0.18363.836
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

Any other software?
```

**Comment by FireMasterK** [comment]
I'm facing this issue too.

```
C:\Users\kavin>winget install Git.Git
Found Git [Git.Git]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://github.com/git-for-windows/git/releases/download/v2.29.0.windows.1/Git-2.29.0-64-bit.exe
An unexpected error occurred while executing the command:
InternetReadFile() failed.
0x80072ee2 : unknown error
```
```
C:\Users\kavin>winget install github.cli
Found GitHub CLI [GitHub.cli]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://github.com/cli/cli/releases/download/v1.2.0/gh_1.2.0_windows_amd64.msi
An unexpected error occurred while executing the command:
InternetOpenUrl() failed.
0x80072efd : unknown error
```

**Comment by FireMasterK** [comment]
It started occouring when
```
C:\Users\kavin>winget install Git.Git
Found Git [Git.Git]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://github.com/git-for-windows/git/releases/download/v2.29.0.windows.1/Git-2.29.0-64-bit.exe
  ██████████████████████████████  10.0 MB / 46.1 MB
```
just exited without throwing any errors.

**Comment by huangsijun17** [comment]
I'm facing this issue too. How did you fix it?

https://github.com/microsoft/winget-cli/issues/638#issue-739737353

**Comment by FireMasterK** [comment]
It fixed itself for me when I tried it 20-30 minutes later.

**Comment by mUsman3** [comment]
This issue usually happens when your internet is slower. Check you internet connectivity and try again running above mentioned command.

**Comment by mUsman3** [comment]
> 
> 
> I'm facing this issue too. How did you fix it?
> 
> [#638 (comment)](https://github.com/microsoft/winget-cli/issues/638#issue-739737353)

Did you check later, after some time? This happen due to internet connection.

**Comment by FireMasterK** [comment]
I don't think this is a network issue, I was able to perform other internet activities on my browser just fine.

**Comment by G0rocks** [comment]
I am facing this issue as well and my internet is okay. Mentioned this issue in a PR

**Comment by G0rocks** [comment]
I have managed to resolve the issue on my end.
I read what the PR bot was saying in the conversation and it turned out that I needed to add the publisher name to the ID in the YAML manifest file.

**Comment by FireMasterK** [comment]
> I have managed to resolve the issue on my end.
> I read what the PR bot was saying in the conversation and it turned out that I needed to add the publisher name to the ID in the YAML manifest file.

Your issue is unrelated as this happens with working packages/manifests. This issue occurs randomly and works if you try later.

**Comment by G0rocks** [comment]
Okay, sorry, my mistake. I just saw 2 almost identical error messages and assumed they were cause by the same error 😅 Good luck with this one

**Comment by denelon** [comment]
This error is related to the Windows Package Manager client not being able to download the installer due to issues with Internet connectivity. I believe the error message has been improved, and we have added additional retry logic.
