### ISSUE TITLE
Add a way to unpin packages that are not installed

### ISSUE THREAD

**Issue by CanePlayz** [microsoft/winget-cli#4194]
### Description of the new feature / enhancement

If you have pinned a package and then uninstalled it, you cannot unpin it as winget tells you that it cannot find the package. But there needs to be a way to unpin those packages.

### Proposed technical implementation details

This could be either fixed by letting us unpin packages regardless of the question whether they can be found or by adding a flag such as `--force` to forcefully unpin packages.

**Comment by mdanish-kh** [comment]
You can use `winget pin list` to list all pins and remove the pins you don't want with the `--id` flag

This duplicates #4163

**Comment by CanePlayz** [comment]
> You can use `winget pin list` to list all pins and remove the pins you don't want with the `--id` flag
> 
> This duplicates #4163

Thanks, couldn't find your issue when I looked for existing ones, sorry.

**Comment by CanePlayz** [comment]
Yup 👍
