### ISSUE TITLE
InstallerType MSI with Switches seems to fail.

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/winget-cli#421]
# Brief description of your issue
When processing PR 1653  https://github.com/microsoft/winget-pkgs/pull/1653
It failed because it was MSI and the Switches were specified.

If I remove the Switches, it works.  But Switches should override, right?  It should have used the switches provided  instead of defaults.  

# Steps to reproduce

Try to install PR 1653.  At least the version available on 6/13.

# Expected behavior

Switches should override default MSI settings

# Actual behavior

Fails to install with error 1603.

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
```

**Comment by yao-msft** [comment]
Somehow I cannot repro the issue. With or without explicit Switches declaration in the PR(iteration 1 and iteration 2), the installation succeeded.

**Comment by KevinLaMS** [comment]
Ugh.  Just repro'd again.  See PR  https://github.com/microsoft/winget-pkgs/pull/2905

**Comment by KevinLaMS** [comment]
Ugh, ugh. Just repro'd again. See PR microsoft/winget-pkgs#2906
