### ISSUE TITLE
Unable to Add Pin; Trying to upgrade the installed package...

### ISSUE THREAD

**Issue by dgulik** [microsoft/winget-cli#4249]
### Brief description of your issue

Unable to pin a package. The package was previously pinned. After having some other issues with winget, I reset it and then ran upgrade all and it started to upgrade a previously pinned package, and I closed the CLI  while this upgrade was in progress. Now I am unable to pin this package. Please, refer to screenshot.
![Screenshot 2024-03-06 201649](https://github.com/microsoft/winget-cli/assets/48869777/a6e00ff7-0e01-48e8-8f89-53586ec33594)
![image](https://github.com/microsoft/winget-cli/assets/48869777/3288a444-1ec8-44a6-bf40-971f1cfff354)

### Steps to reproduce

 winget add pin OBSProject.OBSStudio
 winget add pin WavesAudio.WavesCentral

both of these were previously pinned.

### Expected behavior

packages to be pinned so I can run upgrade --all

### Actual behavior

packages are not pinning due to error; "Trying to upgrade the installed package..."

### Environment

```shell
Windows Package Manager v1.7.10582
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3235
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10582.0
```

**Comment by Trenly** [comment]
@dgulik - Have you tried `winget pin add` instead of `winget add pin`?

https://learn.microsoft.com/en-us/windows/package-manager/winget/pinning#usage

**Comment by dgulik** [comment]
Oh well, my mistake. I was using the wrong command. winget pin add produces
the correct result.
