### ISSUE TITLE
Export reports Installed package is not available from any source even for winget installed apps

### ISSUE THREAD

**Issue by craftzneko** [microsoft/winget-cli#4269]
### Brief description of your issue

I believe this is the same issue logged and closed here https://github.com/microsoft/winget-cli/issues/1274 

### Steps to reproduce

Winget export -o=file.json

### Expected behavior

Export with sources

### Actual behavior

Example Github desktop was installed through winget as shown when doing list

![image](https://github.com/microsoft/winget-cli/assets/662108/ee2ab663-1ef7-4b4a-b56c-e0d3a9d25467)

Yet my export shows all applications as having no source and as you can see github desktop now source

![image](https://github.com/microsoft/winget-cli/assets/662108/b3fc49e6-31e5-47a3-8cc7-d0d782077ba8)

### Environment

```shell
Windows: Windows.Desktop v10.0.19045.4046
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10582.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by craftzneko** [comment]
Ahh i see so its defining packages and then the source beneath. Fair enough that makes sense was just thrown by the messages appearing. Is there a way to supress them?

**Comment by Trenly** [comment]
> Ahh i see so its defining packages and then the source beneath. Fair enough that makes sense was just thrown by the messages appearing. Is there a way to supress them?

Not yet, but it is being tracked by 
* #4213 
And should be resolved by
* https://github.com/microsoft/winget-cli/pull/4221
