### ISSUE TITLE
Windows Package Manager 1.7.10661

### ISSUE THREAD

**Issue by bmacnair** [microsoft/winget-cli#4280]
### Discussed in https://github.com/microsoft/winget-cli/discussions/4255

<div type='discussions-op-text'>

<sup>Originally posted by **ryfu-msft** March  9, 2024</sup>
This release is the second release candidate of Windows Package Manager 1.7 for Windows 10 (1809+), and Windows 11.
Experimental features have been disabled in this release.

This release fixes issues related to `winget upgrade --all` (https://github.com/microsoft/winget-cli/issues/4219) and addresses problems with the PowerShell cmdlet `Repair-WinGetPackageManager` which was caused by our dependency on the latest Microsoft.UI.Xaml version 2.8 (https://github.com/microsoft/winget-cli/issues/4208).

## What's Changed
* Update Repair-WinGetPackageManager with UiXaml 2.8 by @ryfu-msft in https://github.com/microsoft/winget-cli/pull/4218
* Allow all packages to check for a version by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/4227
* Copy semver.dll to direct dependencies by @ryfu-msft in https://github.com/microsoft/winget-cli/pull/4226
* Fix PowerShellCmdlet by @msftrubengu in https://github.com/microsoft/winget-cli/pull/4247
* Fix xamlAsset value (powershell module) by @vedantmgoyal9 in https://github.com/microsoft/winget-cli/pull/4247

**Full Changelog**: https://github.com/microsoft/winget-cli/compare/v1.7.10582...v1.7.10661

<hr /><em>This discussion was created from the release <a href='https://github.com/microsoft/winget-cli/releases/tag/v1.7.10661'>Windows Package Manager 1.7.10661</a>.</em></div>

**Comment by mdanish-kh** [comment]
> I just downloaded the latest version, but when I run it, it looks like it's an older version. I downloaded the Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle but when I double click on this it is showing version 1.22.10661.0.

That's the version of App Installer package that WinGet is shipped as part of. Both softwares have a different version. App Installer `v1.22.10661.0` contains the current latest WinGet version `v1.7.10661`. If you install the package, and then run `winget -v`, you'll see the WinGet version to be in fact `1.7.10661`. If you're curious about why these two have different versions and the relation between them, you can check out:

- [WinGet community repository frequently asked questions (FAQs) (at 0:47 timestamp)](https://youtu.be/b976Vdv2VAs?si=PWhPh6zn1U6d_de-&t=47)

If you have other questions, check out the [FAQ](https://github.com/microsoft/winget-pkgs/blob/master/FAQ.md#why-do-winget-and-appinstaller-have-different-versions) or [open a discussion](https://github.com/microsoft/winget-cli/discussions/new/choose) if you have a question that's not answered there.
