### ISSUE TITLE
Winget upgrade allows updating the same package twice

### ISSUE THREAD

**Issue by ewanm89** [microsoft/winget-cli#4284]
### Brief description of your issue

If you list the same package twice on winget upgrade, it attempts to install the package twice.

### Steps to reproduce

Have a package in need of updating then run winget upgrade <packageid> <packageid> with the same packageid twice.
![image](https://github.com/microsoft/winget-cli/assets/135458/7886b115-2e25-488d-b20e-e0136bf18e2f)

### Expected behavior

Ignore the accidental repeat and automatically not download and run the installer twice.

### Actual behavior

Runs the installer for the package twice.

### Environment

```shell
Windows Package Manager v1.7.10661

Windows: Windows.Desktop v10.0.19045.4123
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10661.0
```

**Comment by Trenly** [comment]
Can you share the output of `winget list "ShareX"`?
