### ISSUE TITLE
winget list filters missing items

### ISSUE THREAD

**Issue by zhangzih4n** [microsoft/winget-cli#4334]
### Brief description of your issue

`winget list Microsoft.DotNet.DesktopRuntime.8` command result is empty when both `x64` and `x86` of `Microsoft.DotNet.DesktopRuntime.8` are installed

This problem also exists in DotNet6, DotNet7

### Steps to reproduce

1. run `winget install -a x64 Microsoft.DotNet.DesktopRuntime.8`
2. run `winget list Microsoft.DotNet.DesktopRuntime`. Results exists
3. run `winget install --force -a x86 Microsoft.DotNet.DesktopRuntime.8`
4. run `winget list`. Both `x64` and `x86` for `Microsoft.DotNet.DesktopRuntime.8` are among the results
5. run `winget list Microsoft.DotNet.DesktopRuntime.8`. Result is empty

### Expected behavior

Both `x64` and `x86` for Microsoft.DotNet.DesktopRuntime.8 are among the results

### Actual behavior

Result is empty

### Environment

```shell
Windows Package Manager v1.7.10861
Windows: Windows.Desktop v10.0.22631.3374
Package: Microsoft.DesktopAppInstaller v1.22.10861.0
```

**Comment by denelon** [comment]
We've been working on the side-by-side scenarios. You could try the latest release and enable the experimental feature on:
* https://github.com/microsoft/winget-cli/releases/tag/v1.8.924-preview

Please provide feedback at:
* https://github.com/microsoft/winget-cli/discussions/4281
