### ISSUE TITLE
WINGET UPGRADE - Package contracts have not been agreed. Operation cancelled.

### ISSUE THREAD

**Issue by Novogumiguel** [microsoft/winget-cli#4350]
### Brief description of your issue

Estou tentando fazer uma atualização pelo winget em um notebook, mas fica dando esse aviso "Os contratos de pacote não foram concordados. Operação cancelada." e não encontro nada sobre na internet...

![image](https://github.com/microsoft/winget-cli/assets/98752670/ad3c20fc-b931-47b7-a151-31fcad70d6ff)

![image](https://github.com/microsoft/winget-cli/assets/98752670/dc66f72b-7fd3-4bed-9a20-75c933a5e85c)

### Steps to reproduce

winget update

### Expected behavior

esperava atualizar o que tem disponivel

### Actual behavior

da um erro com o aviso mencionado acima e cancela

### Environment

```shell
Gerenciador de Pacotes do Windows v1.7.10861
Copyright (c) Microsoft Corporation. Todos os direitos reservados.

Windows: Windows.Desktop v10.0.22621.3374
Arquitetura do Sistema: X64
Pacote: Microsoft.DesktopAppInstaller v1.22.10861.0
```

**Comment by Trenly** [comment]
@Novogumiguel - Some packages require acceptance of their terms and conditions. When using `--all` winget runs without interaction, so the prompts are not shown. To avoid this error, use `--accept-package-agreements` which will automatically accept the agreements.

**Comment by Novogumiguel** [comment]
Deu erro de comando desconhecido primo :c

**Comment by Trenly** [comment]
> It gave an unknown command error cousin :c

Can you provide the log file?

**Comment by Novogumiguel** [comment]
tentei novamente agora, devo ter digitado errado.. agora deu certo.. muito obrigado

![image](https://github.com/microsoft/winget-cli/assets/98752670/bfa37b82-2bb8-4e90-85b9-94d2a1b0cdda)

![image](https://github.com/microsoft/winget-cli/assets/98752670/9a9d896b-7d59-413e-b5d7-864f82e8c404)

**Comment by Trenly** [comment]
Glad it's working!

**Comment by Novogumiguel** [comment]
Tenho outra questão que me incomoda, nao sei se posso usar nesse tópico,....

quando tento formatar um pc com a versão Home single language, mesmo usando uma imagem multi-iso do windows, ele não deixa eu escolher qual verão quero instalar, e sempre fica em Single Language.

![image](https://github.com/microsoft/winget-cli/assets/98752670/8205dcb1-61ed-4f0f-a8f6-3489058bc017)


em outro notebook, o suporte do windows usou um comando que destravou esse sistema, mas não consegui identificar
