### ISSUE TITLE
Installing PowerShell results in error

### ISSUE THREAD

**Issue by Luedtkejk** [microsoft/winget-cli#4357]
### Brief description of your issue

```
2024-04-06 16:16:16.926 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerSharedLib\Public\AppInstallerLanguageUtilities.h(135)\WindowsPackageManager.dll!00007FFBEE892E19: (caller: 00007FFBEE8E8F38) Exception(1) tid(3dbc) 80070490 Element not found.

    Msg:[GetVariant(14)] 

2024-04-06 16:16:16.928 [CLI ] Caught wil::ResultException: C:\__w\1\s\external\pkg\src\AppInstallerSharedLib\Public\AppInstallerLanguageUtilities.h(135)\WindowsPackageManager.dll!00007FFBEE892E19: (caller: 00007FFBEE8E8F38) Exception(1) tid(3dbc) 80070490 Element not found.

    Msg:[GetVariant(14)] 
```

[WinGet-2024-04-06-16-16-16.338.log](https://github.com/microsoft/winget-cli/files/14895017/WinGet-2024-04-06-16-16-16.338.log)
[WinGet-2024-04-06-16-17-55.131.log](https://github.com/microsoft/winget-cli/files/14895018/WinGet-2024-04-06-16-17-55.131.log)
[WinGet-2024-04-06-16-17-43.499.log](https://github.com/microsoft/winget-cli/files/14895019/WinGet-2024-04-06-16-17-43.499.log)

### Steps to reproduce

`winget install Microsoft.PowerShell -s winget`

### Expected behavior

PowerShell 7 to be installed

### Actual behavior

```
An unexpected error occurred while executing the command:
GetVariant(14)
0x80070490 : Element not found.
```

### Environment

```shell
Windows Package Manager (Preview) v1.8.924-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4170
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.924.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
PS C:\WINDOWS\system32>
```

**Comment by Luedtkejk** [comment]
@johnmcpms / @denelon - `sideBySide` was enabled and causing this error. Disabling `sideBySide` experimental feature resolved the issue

cc @Trenly

**Comment by Trenly** [comment]
[Policy] Experimental
[Policy] Issue Bug
[Policy] Command Install

**Comment by mdanish-kh** [comment]
Same error seen in #4354

**Comment by soredake** [comment]
Same with `ETXSoftwareInc.DuckDns` and `REALiX.HWiNFO`

**Comment by aaronliu0130** [comment]
Could someone change the title to something like "GetVariant(14) 0x80070490 : Element not found when sideBySide is enabled"? I get this when trying to install `LastFM.LastFMDesktopScrobbler` and a few other packages as well

**Comment by davidldennison** [comment]
@aaronliu0130 I updated #4425 as well to be more clear - thanks for the heads up!

@mdanish-kh did you get this error when actually trying to use the sBS functionality? I tried installing apps that had no other versions, no head ever been installed, and was getting this error. I don't have any apps pinned, and just like you when disabling - installed just fine.

**Comment by mdanish-kh** [comment]
@Luedtkejk There have been updates to the client to fix similar issues to this one. Can you try installing the [v1.9.1551-preview release](https://github.com/microsoft/winget-cli/releases/tag/v1.9.1551-preview) and check if the issue's resolved for you?

[comment]: <[Policy] Needs-Author-Feedback>

**Comment by MagicAndre1981** [comment]
> Can you try installing the [v1.9.1551-preview release](https://github.com/microsoft/winget-cli/releases/tag/v1.9.1551-preview) and check if the issue's resolved for you?

works for me for Perfview. Before I got this error:

```
C:\>winget install --id Microsoft.PerfView -e --source winget --verbose-logs
Unerwarteter Fehler beim Ausführen des Befehls:
GetVariant(14)
0x80070490 : Element nicht gefunden.
```

with 1.9 preview it works 🥳

```
C:\>winget install --id Microsoft.PerfView -e --source winget --verbose-logs
Gefunden PerfView [Microsoft.PerfView] Version 3.1.11
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Download läuft https://github.com/microsoft/perfview/releases/download/v3.1.11/PerfView.exe
  ██████████████████████████████  21.4 MB / 21.4 MB
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Befehlszeilenalias hinzugefügt: "perfview"
Erfolgreich installiert
```

**Comment by aaronliu0130** [comment]
Since updating to the newest download, I have been unable to run `winget update`—it just keeps on spinning until I exorcize it from my realm.

**Comment by aaronliu0130** [comment]
Works after latest preview

**Comment by denelon** [comment]
@Luedtkejk are you still having this problem with the stable 1.8 release of WinGet, or the current 1.9-preview release?
