### ISSUE TITLE
add an abbreviation for "--accept-configuration-agreements" option. For example --aca.

### ISSUE THREAD

**Issue by acangialosi** [microsoft/winget-cli#4399]
### Description of the new feature / enhancement

When you authoring dsc configurations you often experiment with different configuration files, retyping the long command "winget configure --accept-configuration-agreements <myfile>.yaml". Long options and commands are constant sources of typos. Please provide an abbreviated option like --aca to simplify rapid development and reduce mistakes and retypes.

**Comment by denelon** [comment]
Shortened agreements aren't allowed for explicit arguments like terms, configuration agreements, source agreements, or package agreements.
