### ISSUE TITLE
Release artifacts 1.7.11132 incorrect linking

### ISSUE THREAD

**Issue by tonnesen-ncqa** [microsoft/winget-cli#4416]
### Brief description of your issue

The artifacts available for download in this latest release are incorrectly linked to the actual packages.

![image](https://github.com/microsoft/winget-cli/assets/104849311/5316605d-2b03-4b29-a939-5a54de59af84)

### Steps to reproduce

Visit: https://github.com/microsoft/winget-cli/releases/tag/v1.7.11132 and download any of the first 4 artifacts by clicking on them, or invoke unattended:

```powershell
$dc = New-Object net.webclient
$dc.UseDefaultCredentials = $true
$dc.Headers.Add("user-agent", "Inter Explorer")
$dc.Headers.Add("X-FORMS_BASED_AUTH_ACCEPTED", "f")
$WinGetURL = "https://aka.ms/getwinget"
$dc.DownloadFile($WinGetURL, "$InstallerFolder\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle")
		
```

- 'ccfd1d114c9641fc8491f3c7c179829e_License1.xml' -> downloads 'DesktopAppInstallerPolicies.zip.xml'
- 'DesktopAppInstallerPolicies.zip' -> downloads 'ccfd1d114c9641fc8491f3c7c179829e_License1.xml.zip'
- 'Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -> downloads 'Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.txt.msixbundle'
- 'Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.txt' -> downloads 'Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle.txt'

### Expected behavior

Download the listed files with the correct file extensions.

### Actual behavior

Incorrect and seemingly corrupted packages are being downloaded. Even after renaming the .txt.msixbundle, the bundle was still corrupted when used with Add-AppxProvisionedPackage.

### Environment

```shell
Windows Package Manager v1.7.10861
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4355
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10861.0

Winget Directories                 
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by denelon** [comment]
@tonnesen-ncqa I just tested, and the correct files were downloaded. I don't know if this was some kind of transient issue or not. Are you still getting the incorrect artifacts?

**Comment by tonnesen-ncqa** [comment]
> @tonnesen-ncqa I just tested, and the correct files were downloaded. I don't know if this was some kind of transient issue or not. Are you still getting the incorrect artifacts?

I am still seeing the same issue. This is happening in a Firefox and Edge.

https://ncqa-my.sharepoint.com/:v:/g/personal/tonnesen_ncqa_org/EfyvDyUHmL1LpLJIa6h-v7gBaTd82jz_PiDfmeqwQoWxwQ?e=SNhNWW

**Comment by Trenly** [comment]
The assets appear incorrect for me also, when selecting them using iOS

**Comment by ryfu-msft** [comment]
@tonnesen-ncqa,

 To be completely honest, I made a mistake when I renamed the files before publishing them to the GitHub releases. Editing the artifact name in the releases did not change the underlying filename. 

I have removed the files and reuploaded them. Please verify and let me know if you still encounter issues.

**Comment by tonnesen-ncqa** [comment]
@ryfu-msft - that fixed it! I appreciate all the work you do on this project.
