### ISSUE TITLE
sideBySide Experimental Feature Causing GetVariant(14) 0x80070490 Error - Winget v1.8.1133-preview

### ISSUE THREAD

**Issue by davidldennison** [microsoft/winget-cli#4425]
### Brief description of your issue

The sideBySide Experimental Features causes variant issue when trying to install an application Winget as the source and setting "sideBySide: true" under experimental features.

I also submitted to the Feedback Hub with all of my Winget logs and diagnostic data recorded. Find it here:

[https://aka.ms/AAq7fke](https://aka.ms/AAq7fkel)

The video attached is a side-by-side recording of my Terminal and Winget "settings.json" so you can see exactly how sideBySide was enabled, install failed, sideBySide disabled, install succeeds.

https://github.com/microsoft/winget-cli/assets/67825086/ddb77b54-d21b-4011-a39b-54ad311a70f9

### Steps to reproduce

Steps:
1. Enable sideBySide
2. ```winget install Google.Chrome.Beta -s winget```
3. ```Unexpected Error - GetVariant(14) 0x80070490 : Element not found.```
4. Disable sideBySide
5. Open new shell
6. ```winget install Google.Chrome.Beta -s winget```
7. Google Chrome Beta installs as expected

Also tried with ```winget install Google.Chrome.Dev -s winget```

### Expected behavior

C:\>```winget install Google.Chrome.Beta -s winget```
Found Google Chrome Beta [Google.Chrome.Beta] Version 125.0.6422.14
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.google.com/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  ██████████████████████████████   116 MB /  116 MB
Successfully verified installer hash
Starting package install...
Successfully installed

C:\>

### Actual behavior

C:\>```winget install Google.Chrome.Beta -s winget```
An unexpected error occurred while executing the command:
GetVariant(14)
0x80070490 : Element not found.

C:\>

### Environment

```shell
My current Winget settings.json:
{
    "$schema": "https://aka.ms/winget-settings.schema.json",
    "experimentalFeatures": {
        "experimentalCmd": true,
        "experimentalArg": true,
	    "dependencies": true,
	    "directMSI": true,
        "resume": true,
        "configuration03": true,
        "configureSelfElevate": true,
        "sideBySide": false
    },
    "visual": {
        "progressBar": "rainbow",
        "anonymizeDisplayedPaths": false
    },
    "source": {
        "autoUpdateIntervalInMinutes": 60
    },
    "installBehavior": {
        "disableInstallNotes": false,
        "skipDependencies": false,
        "includePreviewVersions": true,
        "portablePackageUserRoot": "C:\\Portable-Apps",
        "portablePackageMachineRoot": "C:\\Portable-Apps",
        "allowPrerelease": true,
        "allowExperimental": true,
        "preferences": {
            "locale": ["en-US"],
            "architectures": ["x64"],
            "installerTypes": ["msix", "msi", "exe", "msstore", "wix", "nullsoft", "zip", "inno", "burn",  "portable"]
        }
    },
    "uninstallBehavior": {
        "purgePortablePackage": true
    },
    "network": {
       "downloader": "wininet"
    },
    "telemetry": {
        "disable": false    
    },
    "logging": {
        "level": "verbose",
        "channels": ["all"]
    },
    "interactivity": {
        "disable": false
    }
}

Winget --info --verbose:
Windows Package Manager (Preview) v1.8.1133-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26200.5001
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1133.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------------------------
Logs                               C:\Users\david\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutp…
User Settings                      C:\Users\david\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings…
Portable Links Directory (User)    C:\Users\david\AppData\Local\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       C:\Portable-Apps
Portable Package Root              C:\Portable-Apps
Portable Package Root (x86)        C:\Portable-Apps
Installer Downloads                C:\Users\david\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled

C:\>
```

**Comment by mdanish-kh** [comment]
Related to:
- https://github.com/microsoft/winget-cli/issues/4354
- https://github.com/microsoft/winget-cli/issues/4357

[comment]: <[Policy] Experimental>
[comment]: <[Policy] Command-Install>

**Comment by denelon** [comment]
Thanks for reporting this with logs!

We were just discussing this bug and trying to get a reliable reproduction.
