### ISSUE TITLE
winget recommends spurious onenote update

### ISSUE THREAD

**Issue by fehrin1** [microsoft/winget-cli#4443]
### Brief description of your issue

With winget update (upgrade) i get the following upgrade recommendation:
Microsoft OneNote - de-de XPFFZHVGQWWLHB 16.0.16731.20636 16.0.17231.20236 msstore
Looking at
https://learn.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date
this is not a sensible suggestion:
- 16731.20636 is the latest update from the half year enterprise channel, so there is nothing to update here.
- 16.0.17231.20236 is not the latest update from the monthly enterprise channel, why is it that exactly this version is recommended?

### Steps to reproduce

winget update
or
winget upgrade

### Expected behavior

No onenote upgrade should be suggested.

### Actual behavior

A spurious upgrade is suggested.

### Environment

```shell
C:\Users\FEH01589>winget --info
Windows-Paket-Manager v1.7.11132
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19045.4355
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.22.11132.0

WinGet-Verzeichnisse
-----------------------------------------------------------------------------------------------------------------------------------------
Protokolle                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
Benutzereinstellungen                        %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Verzeichnis für portierbare Links (Benutzer) %LOCALAPPDATA%\Microsoft\WinGet\Links
Portables Linkverzeichnis (Computer)         C:\Program Files\WinGet\Links
Portierbarer Paketstamm (Benutzer)           %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portierbarer Paketstamm                      C:\Program Files\WinGet\Packages
Portierbares Paketstamm (x86)                C:\Program Files (x86)\WinGet\Packages
Installationsprogrammdownloads               %USERPROFILE%\Downloads

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale

Administratoreinstellung                  Status
-----------------------------------------------------
LocalManifestFiles                        Deaktiviert
BypassCertificatePinningForMicrosoftStore Deaktiviert
InstallerHashOverride                     Deaktiviert
LocalArchiveMalwareScanOverride           Deaktiviert
```

**Comment by stephengillie** [comment]
I couldn't find identical output (no version, and no "Microsoft"), but it does appear that the MSStore has a package named `OneNote`:

```PowerShell
PS C:\ManVal> find-WinGetPackage OneNote

Name                              Id                         Version          Source
----                              --                         -------          ------
OneNote                           XPFFZHVGQWWLHB             Unknown          msstore
OneNote Tagging Kit               wethat.onenotetaggingkit   5.1.8514         winget
OneMoreAddIn                      stevencohn.OneMore         5.9.0            winget
OneMark                           Neux.OneMark               1.0.2            winget
Microsoft 365 Apps for enterprise Microsoft.Office           16.0.17425.20176 winget
NoteHighlight2016                 elvirbrk.notehighlight2016 3.7              winget
```

Installing into a VM, it appears to download and install Office 365:

![image](https://github.com/microsoft/winget-cli/assets/114952565/92bc2aa6-0101-47ae-8b77-c53591310110)

**Comment by denelon** [comment]
Can you share logs for this incident?

If it's reproduceable you can append "--verbose-logs --logs" to get verbose logs and open the directory containing the files. I would just need the latest one with the error.

**Comment by fehrin1** [comment]
> I couldn't find identical output (no version, and no "Microsoft"), but it does appear that the MSStore has a package named `OneNote`:
> 
> ```powershell
> PS C:\ManVal> find-WinGetPackage OneNote
> 
> Name                              Id                         Version          Source
> ----                              --                         -------          ------
> OneNote                           XPFFZHVGQWWLHB             Unknown          msstore
> OneNote Tagging Kit               wethat.onenotetaggingkit   5.1.8514         winget
> OneMoreAddIn                      stevencohn.OneMore         5.9.0            winget
> OneMark                           Neux.OneMark               1.0.2            winget
> Microsoft 365 Apps for enterprise Microsoft.Office           16.0.17425.20176 winget
> NoteHighlight2016                 elvirbrk.notehighlight2016 3.7              winget
> ```
> 
> Installing into a VM, it appears to download and install Office 365:
> 
> ![image](https://private-user-images.githubusercontent.com/114952565/327811449-92bc2aa6-0101-47ae-8b77-c53591310110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MTUzMjEsIm5iZiI6MTcxNDgxNTAyMSwicGF0aCI6Ii8xMTQ5NTI1NjUvMzI3ODExNDQ5LTkyYmMyYWE2LTAxMDEtNDdhZS04Yjc3LWM1MzU5MTMxMDExMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQwOTMwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjhjZTQzM2Y5M2QwYzhlOGU4ZGQyYmJhZGZlY2E2OWUyNGY5MDgzZTRhMDk4NzYxYWM4YWZkZjFkNDE5MWMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aDPVgP_CwqOUeQkKs_ffbNlZyEKsctyERMnEtHx6GS0)

@stephengillie There is a onneote installed via Office 365 Enterprise. The update suggested by winget on top of this installation is spurious.

**Comment by fehrin1** [comment]
> Can you share logs for this incident?
> 
> If it's reproduceable you can append "--verbose-logs --logs" to get verbose logs and open the directory containing the files. I would just need the latest one with the error.

winget update --verbose-logs --logs
[WinGet-2024-05-04-11-33-01.458.log](https://github.com/microsoft/winget-cli/files/15209207/WinGet-2024-05-04-11-33-01.458.log)
[WinGet-2024-05-04-11-32-51.462.log](https://github.com/microsoft/winget-cli/files/15209208/WinGet-2024-05-04-11-32-51.462.log)
[WinGet-2024-05-04-11-33-36.222.log](https://github.com/microsoft/winget-cli/files/15209209/WinGet-2024-05-04-11-33-36.222.log)

**Comment by fehrin1** [comment]
@denelon I added the log file(s) requested.

**Comment by fehrin1** [comment]
Hi @denelon any idea on this, it is for me the last remaining problem, apart from this, winget is "clean" for me?

**Comment by fehrin1** [comment]
If an update were to be suggested at all, it should be the 16731.20674 in the meantime (but interestingly the "builtin" onenote/office update also does not detect this update).

**Comment by fehrin1** [comment]
With winget 1.8 it is still
C:\Users\FEH01589>winget update
Name                      ID             Version          Verfügbar        Quelle
----------------------------------------------------------------------------------
Microsoft OneNote - de-de XPFFZHVGQWWLHB 16.0.16731.20716 16.0.17231.20236 msstore
1 Aktualisierungen verfügbar.
My guess is that there is some information base for software versions which needs an update too.
Personally i would exclude OneNote from winget updates, it is only a placeholder for a full blown Office 365 installation.

**Comment by fehrin1** [comment]
As of today no OneNote update is suggested anymore. If it stays this way the issue can be closed.
winget update
Es wurde kein installiertes Paket gefunden, das den Eingabekriterien entspricht.

**Comment by fehrin1** [comment]
This issue reappeared, now the offered update is
Name                          ID                        Version          Verfügbar        Quelle
Microsoft OneNote - de-de     XPFFZHVGQWWLHB            16.0.19127.20570 16.0.19328.20178 msstore
which does not make sense for the same reasons as before.

**Comment by fehrin1** [comment]
winget --version
v1.28.220
btw

**Comment by fehrin1** [comment]
The spurious update is offered by Microsoft Store too.
