### ISSUE TITLE
winget cannot upgrade Teams Machine wide Installer

### ISSUE THREAD

**Issue by Robertblazor** [microsoft/winget-cli#4467]
### Brief description of your issue

<img width="908" alt="image" src="https://github.com/microsoft/winget-cli/assets/96743273/8bcb5af9-cb61-4072-944a-0f80067be508">

### Steps to reproduce

Type
'''winget upgrade'''

and 

'''winget upgrade --all''

### Expected behavior

I would expect the Teams Machine wide installer to be upgraded as well, but it just stepped away from that specific line.

### Actual behavior

No behavior upon the teams machine wide installer package

### Environment

```shell
Terminal Preview
Powershell 7.5 -- preview 2
```

**Comment by denelon** [comment]
This is a matching issue where the Teams Machine Wide installer is matching with the Teams manifest. For a workaround, you can pin the Teams Machine Wide installer.

**Comment by Robertblazor** [comment]
Will this issue be resolved?

**Comment by SpecterShell** [comment]
Should have been fixed. Could you try again?

**Comment by Robertblazor** [comment]
Yes I did and it worked.
