### ISSUE TITLE
Microsoft Store - allow downloading old versions

### ISSUE THREAD

**Issue by upintheairsheep** [microsoft/winget-cli#4472]
### Description of the new feature / enhancement

Hello, please add the ability to list and install old versions of Microsoft Store packages, there are many reasons on one may need to use an older version of an MS Store package, to combat a bug in a newer version, to use removed features, or a business wanting to only use certified versions of software. This is a Microsoft Store API problem, meaning Microsoft Store APIs only allow you to download the latest version, and a few other for some packages, but both WinGet and Microsoft Store API needs to support downloading any old version of an app. The only way to access old versions of an app as of now is to get in contact with someone with the version you want of the app dumping it, and manually installing it, or downloading the package from an open source release if it is open source. Other than that there is NO way to obtain the older versions of MS Store packaged, which is really inconvenient. WinGet would be the perfect place to have older versions of apps downloadable, as opposed to the Microsoft Store GUI.

### Proposed technical implementation details

N/A

**Comment by stephengillie** [comment]
This generally seems like a good idea. I do not know if this team has the contacts necessary to reach this goal. I'm not entirely sure, but I believe the WinGet package manager only uses the MSStore as an additional REST Source for package lookup and install, and that otherwise the teams don't have a formal relationship within the company.

**Comment by denelon** [comment]
@upintheairsheep

The Microsoft Store is designed to only distribute the latest versions of Apps across the matrix of supported OS and locale. If this changes, WinGet would have the ability to retrieve earlier versions, but this is completely driven by the Microsoft Store policies.

**Comment by upintheairsheep** [comment]
> @upintheairsheep
> 
> The Microsoft Store is designed to only distribute the latest versions of Apps across the matrix of supported OS and locale. If this changes, WinGet would have the ability to retrieve earlier versions, but this is completely driven by the Microsoft Store policies.

Reopen this, I know this is related to the MS Store API and requires collaboration between the WinGet and MS Store teams, and this would be a great feature as there is no other way to do this.
