### ISSUE TITLE
Winget Download Merged Yaml broken

### ISSUE THREAD

**Issue by futu9** [microsoft/winget-cli#4497]
### Brief description of your issue

Hello,
when i download a Package with more than 2 PackageLocale i get broken yamls merged in my download folder.

### Steps to reproduce

Download a Package with more than 1 addional PackageLocale 
winget download TeamViewer.TeamViewer -e

ExamplePkgs 
TeamViewer.TeamViewer
Microsoft.Terminal)

### Expected behavior

A Yaml with working Syntax
![image](https://github.com/microsoft/winget-cli/assets/170299601/e306106d-c901-42cb-a5c3-b6ba2b16a631)

### Actual behavior

A Yaml with broken Syntax 
![broken_yaml](https://github.com/microsoft/winget-cli/assets/170299601/f75bc93c-c968-48cc-9527-6ff568b83f91)

### Environment

```shell
Windows: Windows.Desktop v10.0.22631.3593
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.22.11261.0
```

**Comment by eabase** [comment]
Could be a line ending problem, as the files looks identical.

**Comment by yao-msft** [comment]
I think it's missing the '-' before the package locale.
