### ISSUE TITLE
Add `--exclude` option to `upgrade` command to exclude a specific app when upgrading packages using `--all`

### ISSUE THREAD

**Issue by AvogatoWizardWhisker** [microsoft/winget-cli#4498]
### Description of the new feature / enhancement

I want to upgrade packages but i don't want to update a specific app. It will be extremely helpful to have `--exclude` following the name, ID package to exclude when using the `winget upgrade --all` 

![image](https://github.com/microsoft/winget-cli/assets/89489853/fd0b65bc-7d9c-4704-b231-7562a906efce)

**Comment by Trenly** [comment]
Use `winget pin add <ID>` to exclude a package from `winget upgrade --all`
