### ISSUE TITLE
Add an option to "hide" or not download when "upgrade --all" is run.

### ISSUE THREAD

**Issue by DavidAdrian8ag** [microsoft/winget-cli#4505]
### Description of the new feature / enhancement

Sometimes when we purchased a license or something like that, the license only works for a particular version. And if we update we loose the license, so a way to "upgrade --all" but not including some apps will be great

### Proposed technical implementation details

Create a "not show" in the upgrade list, may be to hide any program we dont want to upgrade, so we can add it into a list, and not shown and download when "winget upgrade --all" is run.

Thank you!

**Comment by Trenly** [comment]
Use `winget pin add <ID>` to exclude a package from `winget upgrade --all`
https://learn.microsoft.com/en-us/windows/package-manager/winget/pinning
