### ISSUE TITLE
WinGet fails in Windows PowerShell but runs via PowerShell in Windows Terminal

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#4519]
As can be seen here.

https://github.com/microsoft/winget-cli/assets/9511158/6bb893f2-1fc0-4dc6-a896-2755fb5f3a9b

_Originally posted by @Battler624 in https://github.com/microsoft/winget-cli/discussions/4427_

**Comment by Battler624** [comment]
Winget-info does not work on either powershell or powershell via terminal
```
winget-info : The term 'winget-info' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ winget-info
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (winget-info:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by denelon** [comment]
Can you install the Microsoft.WinGet.Client PowerShell module and try running `Repair-WinGetPackageManager -Latest -Force` and let me know if that resolves the issue?

**Comment by Battler624** [comment]
> Can you install the Microsoft.WinGet.Client PowerShell module and try running `Repair-WinGetPackageManager -Latest -Force` and let me know if that resolves the issue?

Winget now works in both, winget-info still doesn't work.

**Comment by JordyEGNL** [comment]
> Can you install the Microsoft.WinGet.Client PowerShell module and try running `Repair-WinGetPackageManager -Latest -Force` and let me know if that resolves the issue?

Thanks this worked for me! Difference was that ``winget`` itself was not working in any terminal window, but now it is again, thank you
