### ISSUE TITLE
Microsoft Teams classic [Microsoft.Teams.Classic] Version 1.7.00.13456 - already installed error

### ISSUE THREAD

**Issue by nolme** [microsoft/winget-cli#4529]
Hello,

I can't upgrade Teams too  : 
```
C:\Windows\System32>winget upgrade --all
Nom                                           ID                                  Version        Disponible     Source
----------------------------------------------------------------------------------------------------------------------
Driver Easy 6.0.0                             Easeware.DriverEasy                 6.0.0          6.0.0.25691    winget
Foxit PDF Reader                              Foxit.FoxitReader                   2024.1.0.23997 2024.2.2.25170 winget
Microsoft SQL Server Management Studio - 19.2 Microsoft.SQLServerManagementStudio 19.2           20.1           winget
Teams Machine-Wide Installer                  Microsoft.Teams.Classic             1.6.0.4472     1.7.00.13456   winget
Microsoft .NET Runtime - 6.0.30 (x64)         Microsoft.DotNet.Runtime.6          6.0.30         6.0.31         winget
6 mises à niveau disponibles.

Les packages suivants ont une mise à niveau disponible, mais nécessitent un ciblage explicite pour la mise à niveau :
Nom     ID              Version  Disponible Source
--------------------------------------------------
Discord Discord.Discord 1.0.9013 1.0.9144   winget
```

Here is the log :  
[WinGet-Microsoft.Teams.Classic.1.7.00.13456-2024-06-03-14-35-28.149.log](https://github.com/user-attachments/files/15533906/WinGet-Microsoft.Teams.Classic.1.7.00.13456-2024-06-03-14-35-28.149.log)

Thanks,
Vincent

**Comment by stephengillie** [comment]
This appears to only impact 1 package, so should be moved to the [winget-pkgs](https://github.com/microsoft/winget-pkgs/issues) repo.

**Comment by stephengillie** [comment]
Is this the "upgrade always available" situation? Do you perform the upgrade, then check again to see the same version numbers, and the upgrade is still there?

**Comment by nolme** [comment]
> Is this the "upgrade always available" situation? Do you perform the upgrade, then check again to see the same version numbers, and the upgrade is still there?

oh yes, you're right, in the control panel I see to correct version.
I uninstall Teams Classic and kept Teams new.
Thanks for help.
