### ISSUE TITLE
`winget` doesn't match 7-zip, by substring or even by id

### ISSUE THREAD

**Issue by sba923** [microsoft/winget-cli#4540]
### Brief description of your issue

Listing or updating 7-zip using `winget` doesn't work:

![image](https://github.com/microsoft/winget-cli/assets/12860484/7f5b2fb8-a8f4-4064-8ee5-2ae80625f118)

Here are the logs:
[wingetlogs202406050938.zip](https://github.com/user-attachments/files/15577308/wingetlogs202406050938.zip)

### Steps to reproduce

Run `winget list 7z` or `winget list --id 7zip.7zip` or `winget update --id 7zip.7zip` on a system with 7-zip 24.05 and 24.06 (in my case, both are reported in the registry) installed.

All commands fail with `No installed package found matching input criteria.`

### Expected behavior

`winget` should find the package, the same way `Get-WinGetPackage` does.

### Actual behavior

`winget` considers the package is not installed (except when running `winget upgrade`)

### Environment

```shell
Windows Package Manager v1.7.11261
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4412
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11261.0

Winget Directories                 
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagΓÇª
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settΓÇª
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by denelon** [comment]
Hey, thanks for sharing this. I believe the issue is related to packages that are installed "side-by-side". We do have an experimental feature you can test with to see if it addresses the issue.

"Side-by-side improvements" is the name of the feature, and the property is "sideBySide". You can see if it's enabled with `winget features` and you can enable it using `winget settings`.
