### ISSUE TITLE
Add option to stop updating windows inbox apps / store apps

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-cli#4546]
### Description of the new feature / enhancement

Right now winget will list updates even for inbox apps (that will be updated by Windows Update or in case of edge by its updater) and store apps (which will be updated by Microsoft Store), I think it's better to add option to make winget ignore these packages.

Example of such packages:
Microsoft.DevHome (updated by microsoft store)
Microsoft.Edge (updated by edge updater)
Microsoft.EdgeWebView2Runtime (updated by edge updater)
Microsoft.Office (updated by windows update)
Microsoft.PowerShell (updated by microsoft store or windows update)
Microsoft.WindowsTerminal (updated by microsoft store)

**Comment by Trenly** [comment]
You can use the command `winget pin add <id>` to skip these applications when using `winget upgrade --all`

https://learn.microsoft.com/en-us/windows/package-manager/winget/pinning

**Comment by soredake** [comment]
@Trenly I know that I can do it, but I think having such option would be nice, winget should not do unnecessary updating when there is already windows update/edge updater/etc doing this by default.
