### ISSUE TITLE
Winget doesn't return an output after installing Visual Studio 2019

### ISSUE THREAD

**Issue by jusefn** [microsoft/winget-cli#458]
# Brief description of your issue

When using winget after installing Visual Studio, no actions will be done and no output will be given
# Steps to reproduce

Install Visual Studio 2019 via Winget
# Expected behavior

A list of commands that can be used with the application
# Actual behavior

No output is given when running from CMD or PowerShell

# Environment

```none
[winget --info] (reported via winver and Settings)
Windows Package Manager version
Windows: Windows.Desktop version v10.0.19041.329
Package: Microsoft.DesktopAppInstaller version 1.0.41331.0

Any other software?
Visual Studio 2019 Enterprise (Version 16.6.2) installed via winget
```

**Comment by denelon** [comment]
Were you looking for some kind of output that would tell you about "devenv"? Or were you looking for something else?

**Comment by jusefn** [comment]
I noticed that winget seems to stop working after an installation of VS, as in the command “winget” is recognized and winget.exe does exist but it won’t do anything.

**Comment by dansanduleac** [comment]
Same here. 
Note, I've just tried to reinstall Windows Package Manager https://github.com/microsoft/winget-cli/releases/tag/v.0.2.2521-preview, and the behaviour is the same.

Looking at where the app was installed, it seems all the files are empty, unless I'm missing something!

```
    Directory: C:\Users\Dan\AppData\Local\Microsoft\WindowsApps\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---l        10/10/2020     14:01              0 python.exe
-a---l        10/10/2020     14:01              0 python3.exe
-a---l        10/10/2020     14:01              0 winget.exe
```

Same goes for the executable in WindowsApps:

```
    Directory: C:\Users\Dan\AppData\Local\Microsoft\WindowsApps


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---l        10/10/2020     14:01              0 winget.exe
```

**Comment by Zelgadis87** [comment]
Same issue here. Winget.exe is a 0kb file located in C:\Users\gabri\AppData\Local\Microsoft\WindowsApps.  
It worked fine until a few days ago, but I have not installed Visual Studio in the mean time..

**Comment by denelon** [comment]
@jusefn has this happened recently? It looks like this might be an external issue related to app execution aliases.

**Comment by denelon** [comment]
@jusefn we've updated our [troubleshooting guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting). This should help resolve the issue. Let us know if the steps don't work.
