### ISSUE TITLE
COM API "upgrade" not working when MinimumOSVersion is set in App Manifest! 

### ISSUE THREAD

**Issue by PatrickSchmidtSE** [microsoft/winget-cli#4589]
### Brief description of your issue

When using the COM-API ( based on this project https://github.com/marticliment/WinGet-API-from-CSharp/tree/main/WindowsPackageManager%20Interop/WindowsPackageManager)  
installation etc is working fine. Binaries coming from the project. 

But "upgrading" via **UpgradePackageAsync** has been a very poor experience so far. 
Most of the upgrades fail with "NoApplicableInstaller" error code, while winget.exe upgrade does upgrade successfully. 

I tested it with many packages, some work (Docker.DockerDesktop) , but many does lead to the above error ( like Java8 etc )

### Steps to reproduce

Install a package like "snakefoot.snaketail" in an older version "1.9.7.0" 

Then use the COM API to run the UpgradePackageAsync mechanic. 

![image](https://github.com/microsoft/winget-cli/assets/9859622/cf75a552-4b2b-416d-9990-0ed46b81ee04)

### Expected behavior

Successfully upgrade to application with InstallResultStatus.OK

### Actual behavior

InstallResultStatus.NoApplicableInstaller 
![image](https://github.com/microsoft/winget-cli/assets/9859622/cf75a552-4b2b-416d-9990-0ed46b81ee04)
By the documentation this means, that means that the Upgrade function could not find an available installer given the "options". i tried every options combination, architecture stuff, used all the switches to ignore stuff. Everyhing leads to the same result. 
I looked up via the installedVersion property which "Installer" is used and what characteristiks but they are all normal and even setting stuff to the settings the installedVersion has.. It all ends the same.

If i just put "winget upgrade --id snakefoot.snaketail --silent --force" it instantly downloads the msi and installs it successfully. 

Proposed problem and solution
**So i think i got finally an idea what is happening:**

Snakefoot has a MinimumOSVersion included

ManifestVersion: 1.6.0
MinimumOSVersion: 10.0.0.0
PackageIdentifier: snakefoot.snaketail

If you go to this check ---> (sadly OSFilter is NOT publicly changable )

![image](https://github.com/microsoft/winget-cli/assets/9859622/5db409ed-070a-422e-b0ff-58f7113f746c)

**You will see that the relevant function is using verifyversioninfow , which delivers a wrong comparism under WIndows10 if the manifest is not changed** 
![image](https://github.com/microsoft/winget-cli/assets/9859622/eb5d03ba-9abc-45ae-879a-261f93e25297)

If i change that in my app manifest it works for my code, but not for the COM or detection from winCLI via COM. 
![image](https://github.com/microsoft/winget-cli/assets/9859622/9b9fe310-85cf-4497-8744-b480359f7dea)

https://learn.microsoft.com/de-de/windows/win32/api/winbase/nf-winbase-verifyversioninfow

This must be fixed OR at least adressed via an OSFIlter ignore option :) 

### Environment

```shell
Windows Package Manager (Preview) v1.9.1763-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4529
System Architecture: X64

Winget Directories
------------------------------------------------------------------------------------------------------
Logs                               %TEMP%\WinGet\defaultState
User Settings                      %LOCALAPPDATA%\Microsoft\WinGet\Settings\defaultState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**Comment by PatrickSchmidtSE** [comment]
@JohnMcPMS thats the issue for my comment yesterday :)

**Comment by PatrickSchmidtSE** [comment]
I have new log information.

Example of the SAME code for an itunes upgrade

`2024-06-27 14:57:17.056 [CORE] Passed in Correlation Vector Json is invalid: ; Error: * Line 1, Column 1
  Syntax error: value, object or array expected.

2024-06-27 14:57:17.056 [CORE] WinGet, version [1.9.1763-preview], activity [{6DA45197-FD27-47A9-A06B-FBFE196FAE86}]
2024-06-27 14:57:17.057 [CORE] OS: Windows.Desktop v10.0.19045.4529
2024-06-27 14:57:17.057 [CORE] Command line Args: C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\WindowsPackageManagerServer.exe --manualActivation
2024-06-27 14:57:17.057 [CORE] IsCOMCall:1; Caller: C:\Users\patrick.schmidt\Downloads\smartdeploy-comapi\WingetManagementService\bin\Debug\net6.0-windows10.0.22621.0\publish\WingetManagementService.exe
2024-06-27 14:57:17.579 [CLI ] Executing command: download
2024-06-27 14:57:17.595 [CLI ] Generated temp download path: C:\WINDOWS\TEMP\WinGet\defaultState\Apple.iTunes.12.13.2.3\9cbaef01a8e2be6f4aa68768484268def7ca71491b71e56b435d4878da3232fd
2024-06-27 14:57:17.596 [CORE] Downloading to path: C:\WINDOWS\TEMP\WinGet\defaultState\Apple.iTunes.12.13.2.3\9cbaef01a8e2be6f4aa68768484268def7ca71491b71e56b435d4878da3232fd
2024-06-27 14:57:17.596 [CORE] DeliveryOptimization downloading from url: https://secure-appldnld.apple.com/itunes12/052-51516-20240506-351B8BFB-C5A7-4FD8-8262-60CD9FAA1464/iTunes64Setup.exe
2024-06-27 14:58:22.027 [CORE] Download completed.
2024-06-27 14:58:25.064 [CORE] Started applying motw to C:\WINDOWS\TEMP\WinGet\defaultState\Apple.iTunes.12.13.2.3\9cbaef01a8e2be6f4aa68768484268def7ca71491b71e56b435d4878da3232fd with zone: 3
2024-06-27 14:58:25.067 [CORE] Finished applying motw
2024-06-27 14:58:25.067 [CLI ] Installer hash verified
2024-06-27 14:58:25.067 [CORE] Started applying motw to C:\WINDOWS\TEMP\WinGet\defaultState\Apple.iTunes.12.13.2.3\9cbaef01a8e2be6f4aa68768484268def7ca71491b71e56b435d4878da3232fd with zone: 2
2024-06-27 14:58:25.069 [CORE] Finished applying motw
2024-06-27 14:58:25.069 [CLI ] Successfully renamed downloaded installer. Path: C:\WINDOWS\TEMP\WinGet\defaultState\Apple.iTunes.12.13.2.3\iTunes64Setup.exe
2024-06-27 14:58:25.071 [CLI ] Executing command: install
2024-06-27 14:58:25.301 [CLI ] Installer hash verified
2024-06-27 14:58:25.301 [REPO] Creating new SQLite Index with version [Latest] at ':memory:'
2024-06-27 14:58:25.304 [REPO] Reading MSI UpgradeCodes
2024-06-27 14:58:25.438 [REPO] Reading MSI UpgradeCodes
2024-06-27 14:58:25.471 [CLI ] Installer args: /quiet /norestart /log "C:\dev\winget_upgrade.log"
2024-06-27 14:58:25.471 [CLI ] Starting: 'C:\WINDOWS\TEMP\WinGet\defaultState\Apple.iTunes.12.13.2.3\iTunes64Setup.exe' with arguments '/quiet /norestart /log "C:\dev\winget_upgrade.log"'
2024-06-27 15:00:02.127 [REPO] Creating new SQLite Index with version [Latest] at ':memory:'
2024-06-27 15:00:02.130 [REPO] Reading MSI UpgradeCodes
2024-06-27 15:00:02.272 [REPO] Reading MSI UpgradeCodes
2024-06-27 15:00:02.304 [CLI ] During package install, 1 changes to ARP were observed, 1 matches were found for the package, and 1 packages were in both
2024-06-27 15:00:02.304 [CLI ] The entry determined to be associated with the package is 'iTunes', with publisher 'Apple Inc.'
2024-06-27 15:00:02.306 [REPO] Opening database for ReadWrite at 'C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft/WinGet\State\defaultState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db'
2024-06-27 15:00:02.307 [REPO] Opened SQLite Index with version [1.7], last write [2024-06-27 09:22:21.000]
2024-06-27 15:00:02.331 [CLI ] Removing installer: C:\WINDOWS\TEMP\WinGet\defaultState\Apple.iTunes.12.13.2.3\iTunes64Setup.exe`


vs the code of the failed SnakeTail Upgrade ( delivering noapplicableinstallers )

`2024-06-27 15:01:58.512 [CORE] Passed in Correlation Vector Json is invalid: ; Error: * Line 1, Column 1
  Syntax error: value, object or array expected.

2024-06-27 15:01:58.512 [CORE] WinGet, version [1.9.1763-preview], activity [{5D755540-829E-4055-8AB7-FB0BB9F509DA}]
2024-06-27 15:01:58.512 [CORE] OS: Windows.Desktop v10.0.19045.4529
2024-06-27 15:01:58.512 [CORE] Command line Args: C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\WindowsPackageManagerServer.exe --manualActivation
2024-06-27 15:01:58.513 [CORE] IsCOMCall:1; Caller: C:\Users\patrick.schmidt\Downloads\smartdeploy-comapi\WingetManagementService\bin\Debug\net6.0-windows10.0.22621.0\publish\WingetManagementService.exe
2024-06-27 15:01:58.516 [CLI ] Executing command: download
2024-06-27 15:01:58.517 [CLI ] Terminating context: 0x8a150010 at C:\__w\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:12b
`

Like you can see there is an exception happening resulting in an error message that is not true. But the question is, why is this failing within COM , while the CLI can do it.

**Comment by PatrickSchmidtSE** [comment]
This would also help for analyzing 🗡️ 


 /// a lot of fields and no one requesting it. <<< I DOES NOW :D 

/// DESIGN NOTE:
        /// GetManifest from IPackageVersion in AppInstallerRepositorySearch is not implemented in V1. That class has
        /// a lot of fields andc
        /// Gets the manifest of this package version.
        /// virtual Manifest::Manifest GetManifest() = 0;

**Comment by PatrickSchmidtSE** [comment]
**So i think i got finally an idea what is happening:**

Snakefoot has a MinimumOSVersion included

ManifestVersion: 1.6.0
MinimumOSVersion: 10.0.0.0
PackageIdentifier: snakefoot.snaketail

If you go to this check ---> (sadly OSFilter is NOT publicly changable )

![image](https://github.com/microsoft/winget-cli/assets/9859622/5db409ed-070a-422e-b0ff-58f7113f746c)

You will see that the relevant function is using verifyversioninfow , which delivers a wrong comparism under WIndows10 if the manifest is not changed 
![image](https://github.com/microsoft/winget-cli/assets/9859622/eb5d03ba-9abc-45ae-879a-261f93e25297)

If i change that in my app manifest it works for my code, but not for the COM or detection from winCLI via COM. 
![image](https://github.com/microsoft/winget-cli/assets/9859622/9b9fe310-85cf-4497-8744-b480359f7dea)


https://learn.microsoft.com/de-de/windows/win32/api/winbase/nf-winbase-verifyversioninfow

This must be fixed OR at least adressed via an OSFIlter ignore option :)

**Comment by JohnMcPMS** [comment]
I'm not sure exactly what is happening in your setup, but based on the data provided I'm guessing that you are using `WindowsPackageManagerElevatedFactory`, which is surprisingly working from `SYSTEM`.  It is running `WindowsPackageManagerServer.exe` in an unsupported way, which causes the fact that it does not have the manifested OS support to negatively impact you.

I can add the manifest, but I also recently changed the way that the code underlying that factory works.  I would be very surprised if it continues to work from `SYSTEM`.

The supported way to use winget COM from `SYSTEM` is with the [in-process DLL](https://www.nuget.org/packages/Microsoft.WindowsPackageManager.InProcCom).  Using that, you would have control over the behavior of the version API via the manifest in your own executable.

**Comment by PatrickSchmidtSE** [comment]
@JohnMcPMS 
yes i do :) It works due to several workarounds implemented :)  i know its unsupported, we all wait for official support of winget for SYSTEM context ( and so the COM ) .

"I can add the manifest, but I also recently changed the way that the code underlying that factory works. I would be very surprised if it continues to work from SYSTEM."

That would be really downer :( adding the manifest would be cool or simply make the OS check "optional". 
What changes have you done? Are they already in winget 1.9.preview included? I am using the latest "preview" build 
Windows Package Manager (Preview) v1.9.1763-preview

The supported way to use winget COM from SYSTEM is with the [in-process DLL](https://www.nuget.org/packages/Microsoft.WindowsPackageManager.InProcCom)
I will look into the in-process DLL. is there any example / documentation of this?

**Comment by JohnMcPMS** [comment]
> That would be really downer :( adding the manifest would be cool or simply make the OS check "optional".
What changes have you done? Are they already in winget 1.9.preview included?

They would be coming to you via nuget (winrtact.dll), so technically you could avoid them by not updating (or not updating the interop you are using).

The change is to use the registered package location to find the executable, which will not work from `SYSTEM` since the package is not registered for that user.

> in-process DLL. is there any example / documentation of this?

Unfortunately I don't have any shipped solution here.  The closest thing would be to look at https://github.com/microsoft/winget-cli/tree/7ea9bca4deebf50f1b4d8c7092e61e1339d2830f/src/Microsoft.Management.Deployment.Projection and specifically https://github.com/microsoft/winget-cli/blob/7ea9bca4deebf50f1b4d8c7092e61e1339d2830f/src/Microsoft.Management.Deployment.Projection/Initializers/ActivationFactoryInstanceInitializer.cs

**Comment by JohnMcPMS** [comment]
I've also created that PR for the manifest since it was very easy and shouldn't hurt anything.  That is not an endorsement of support, just that it is the correct thing to do.  You should still try to move to in-proc.

**Comment by PatrickSchmidtSE** [comment]
> They would be coming to you via nuget (winrtact.dll), so technically you could avoid them by not updating (or not updating the interop you are using).
> 
> The change is to use the registered package location to find the executable, which will not work from `SYSTEM` since the package is not registered for that user.

I see, my current workaround already is based on the detection mechanic within the ManualServerActivation and "giving" the method what it wants. It would be interesting to see if there is some possibility to also make it seem "registered" for the USER and locate to the "correct" working executables. 

"[cli/tree/7ea9bca4deebf50f1b4d8c7092e61e1339d2830f/src/Microsoft.Management.Deployment.Projection](https://github.com/microsoft/winget-cli/tree/7ea9bca4deebf50f1b4d8c7092e61e1339d2830f/src/Microsoft.Management.Deployment.Projection) and specifically https://github.com/microsoft/winget-cli/blob/7ea9bca4deebf50f1b4d8c7092e61e1339d2830f/src/Microsoft.Management.Deployment.Projection/Initializers/ActivationFactoryInstanceInitializer.cs"

I did look into the given stuff you posted yesterday already before, since like you said its the closest to anything. And i tried to make it work and i understand in-proc is the way. 

I created the WIngetFactory exactly like that and filled it with the ActivationFactoryInstanceInstaller. I updated the ClassesDefinition with the "inproc" ones. 

**BUT i always get "REGDB_E_CLASSNOTREG" wenn calling "CreateInstance within ActivationFactoryInstanceInstaller" and the CLSID (for example 2DDE4456-64D9-4673-8F7E-A4F19A2E6CC3 ) is not found in my registry either so the error is correct, where as the outproc CLSID are there in my registry(C53A4F16-787E-42A4-B304-29EFFB4BF597) and are loaded correctly via the ManualActivation way**


1) Updates CLSIDs
![image](https://github.com/microsoft/winget-cli/assets/9859622/d2a3c5da-8f67-4c4a-97d4-97d1aafcb180)

2)Implementation like found Microsoft.Management.Deployment.Projection/Initializers/ActivationFactoryInstanceInitializer.cs, error is happening then within CreatePackageManager
![image](https://github.com/microsoft/winget-cli/assets/9859622/76db7915-6f40-4d3a-8860-ee1aa8e3d519)
![image](https://github.com/microsoft/winget-cli/assets/9859622/5ea23ee3-b5d6-4e5a-a80a-9b01c64eb38a)

3) The Exception error within WinRt.cs
![image](https://github.com/microsoft/winget-cli/assets/9859622/92fd3a68-f6b4-46ce-a8ee-349beee6bbf7)

So the question is, if In-proc is the solution, why are the CLSIDs not registered on my system?  How can i use CreateInstance with the ActivationFactoryInstanceInstaller. 
Especially if the Tests found within GIT seem to simply use it that way...
https://github.com/microsoft/winget-cli/blob/7ea9bca4deebf50f1b4d8c7092e61e1339d2830f/src/AppInstallerCLIE2ETests/Interop/InstallInterop.cs

It would be really great if you by any chance could update a short sample ( or someone from your team), if the other COM way is unsupported  . This would be a great benefit to the community using winget and promoting this great tool :)

**Comment by JohnMcPMS** [comment]
For the in-proc case, did you have `Microsoft.Management.Deployment.dll` (which is the output of the `Microsoft.Management.Deployment.InProc` project, renamed) placed next to your .exe?  I believe that it is also in the nuget I linked before.

Registering for SYSTEM is not supported as far as I know, other than a few select frameworks.  I can ask about it again though in case things have changed.

**Comment by PatrickSchmidtSE** [comment]
That would be great , like you said, for this check this would stop my workaround / approach. It would be therefore good to make this packagePath "skippable" ?. I know the solution is unsupported , but it works that way in SYSTEM context and would help in this case ( perhaps together with the manifest issue ). 

Regarding the "Microsoft.Management.Deployment.dll" , No it seems only the .winmd file is deployed there. Also no such .dll is in the package, only the .winmdb  file 
![image](https://github.com/microsoft/winget-cli/assets/9859622/08110be7-f5ea-46cf-b3f1-36bc836f29c9)
![image](https://github.com/microsoft/winget-cli/assets/9859622/1f221a3b-a101-4b15-8e15-0f42ced43020)

Will make sure the all the .dll are also placed where the .exe path is and will report.

**Comment by JohnMcPMS** [comment]
Renaming `Microsoft.Management.Deployment.InProc.dll` to `Microsoft.Management.Deployment.dll` is that I was suggesting as the option.

**Comment by PatrickSchmidtSE** [comment]
**That is very interesting. Never came to that idea. It actually "works" as it loads finally the PackageManager**, but it crashes on the async operation ( not immediatly, after a few seconds). 
![image](https://github.com/microsoft/winget-cli/assets/9859622/91d38909-75eb-463c-acc7-2b35aa48a5eb)

It loads the InstallerOptions, then when calling UpgradePackageAsync the following AppCrash Event is thrown:

.NET Runtime, Event ID 1026
Application: WingetManagementService.exe
CoreCLR Version: 6.0.3124.26714
.NET Version: 6.0.31
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFFB7072CE8
Name of the failed module: combase.dll, Version: 10.0.19041.4355, Zeitstempel: 0xc16ed6b5
**Exceptioncode: 0xc0000005  << This stands for Access Violation**
ErrorOffset: 0x00000000000c2ce8

**Comment by denelon** [comment]
I'm going to go ahead and close this issue since it looks like there is a solution.
