### ISSUE TITLE
winget repeatedly updates same package

### ISSUE THREAD

**Issue by MurraySobol** [microsoft/winget-cli#4634]
### Brief description of your issue

When I run Winget from a Command Prompt I get this window: 
![image](https://github.com/user-attachments/assets/c432c7f5-c713-477b-b226-65b7175e7da9)
The update completes, showing both modules have been updated.
If, however, I run the update a second time, the SAME 2 products are shown as requiring updating again.

### Steps to reproduce

See description above.

### Expected behavior

IMO, once the update has been run successfully the FIRST time, a second update should NOT ask for those same two products to be updated again.

### Actual behavior

The same two products are repeatedly asking to be updated.

### Environment

```shell
C:\>winget -v
v1.9.1792-preview

My environment: Windows 11 Professional 64-bit
Version: 23H2 OS Build 22631.3880
```

**Comment by MurraySobol** [comment]
None of the listed below problems addresses my problem.

Please investigate further.

Murray
________________________________

**Comment by MurraySobol** [comment]
Thanks Stephen, I moved it to the winget-pkgs<https://github.com/microsoft/winget-pkgs/issues/> repo.

I concur with your assessment of the problem, now let's see if we can get someone to FIX the problem!!

Thanks
Murray
________________________________

**Comment by MagicAndre1981** [comment]
you need to enable [SideBySide ](https://github.com/microsoft/winget-cli/issues/2129)experimental setting until this gets stable with 1.9 client. 

the 3rd number is called feature band level and the 4th the patchlevel. So the 4xx installer doesn't remove the old 300 level version.

**Comment by MurraySobol** [comment]
Hi MagicAndre1981:

I tried to install side-by-side but ran into a few issues.

My winget version is:
 C:\>winget
Windows Package Manager (Preview) v1.9.1792-preview
I ran this command: winget settings and added this to settings.json file:
    "experimentalFeatures": {
        "sideBySide": true
    }

I then ran winget features to see if the option has been enabled:
C:\>winget features
The following experimental features are in progress.
They can be configured through the settings file 'winget settings'.

Feature                  Status   Property             Link
-------------------------------------------------------------------------------------
Direct MSI Installation  Disabled directMSI            https://aka.ms/winget-settings
Resume                   Disabled resume               https://aka.ms/winget-settings
Configuration Schema 0.3 Disabled configuration03      https://aka.ms/winget-settings
Configure Self Elevation Disabled configureSelfElevate https://aka.ms/winget-settings
Configure Export         Disabled configureExport      https://aka.ms/winget-settings
Index V2                 Enabled  indexV2              https://aka.ms/winget-settings

I didn't see the option listed.

Any comments or issues with my actions??

BTW: I found this link: We've been working on the side-by-side scenarios. You could try the latest release and enable the experimental feature on:

  *   https://github.com/microsoft/winget-cli/releases/tag/v1.8.924-preview

I was unable to find that download.

Thanks
Murray

________________________________

**Comment by MagicAndre1981** [comment]
go to control panel and remove the older 6.0 and 7.0 SDKs and only keep the one with the higher 3rd number

**Comment by MurraySobol** [comment]
Thanks MagicAndre1981, that worked!!
 I guess I will have to wait until October 2024 for the OFFICIAL, not preview, release of winget to see how / if side-by-side is implemented.

BTW: should I leave those changes in place that I made to my settings.json file (these ones):
    "experimentalFeatures": {
        "sideBySide": true
    }

Or, remove them??

Thanks
Murray
________________________________

**Comment by MagicAndre1981** [comment]
leave it as it is.

**Comment by denelon** [comment]
The side-by-side feature is stable in WinGet 1.8 and WinGet 1.9 previews now.

**Comment by denelon** [comment]
Since this was moved to winget-pkgs, I'm going to go ahead and close this issue.
