### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by skanda890** [microsoft/winget-cli#4635]
### Brief description of your issue

Update README.md, and PULL_REQUEST_TEMPLATE.md to remove mistakes.

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-cli/pull/4619#pullrequestreview-2176688314

**Comment by skanda890** [comment]
https://github.com/microsoft/winget-cli/pull/4619#issuecomment-2229004163
