### ISSUE TITLE
how to enable side-by-side in V1.9.1792-preview

### ISSUE THREAD

**Issue by MurraySobol** [microsoft/winget-cli#4641]
I tried to add the side-by-side features by following these steps: https://www.tenforums.com/windows-10-news/212277-windows-package-manager-winget-1-8-924-preview-windows-10-11-a.html
I noticed that these instructions were for an older version of winget, does this matter, have the steps changed?/

I was unable to find the winget version download listed above.

After following those steps I ran winget features, this is the output:
C:\>winget features
The following experimental features are in progress.
They can be configured through the settings file 'winget settings'.

Feature                  Status   Property             Link
-------------------------------------------------------------------------------------
Direct MSI Installation  Disabled directMSI            https://aka.ms/winget-settings
Resume                   Disabled resume               https://aka.ms/winget-settings
Configuration Schema 0.3 Disabled configuration03      https://aka.ms/winget-settings
Configure Self Elevation Disabled configureSelfElevate https://aka.ms/winget-settings
Configure Export         Disabled configureExport      https://aka.ms/winget-settings
Index V2                 Enabled  indexV2              https://aka.ms/winget-settings

I don't see the side-by-side feature enabled,

Any assistance would be appreciated.

Murray

**Comment by Trenly** [comment]
Side by side is no longer experimental and has been made stable (enabled). There is no longer a setting to enable or disable it

* #4563

###### Close with reason: Feature is no longer experimental;

**Comment by MurraySobol** [comment]
Thanks Kaleb:

      Should I remove the entries I put in the settings.json file (these settings):

    "experimentalFeatures": {
        "sideBySide": true
    }

Murray

________________________________
