### ISSUE TITLE
WinGet Download presents error when it should be a warning.

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/winget-cli#4643]
### Brief description of your issue

When downloading a store app, the user is presented with the following if they do not have admin access to the license.

Failed to retrieve Microsoft Store package license
An unexpected error occurred while executing the command:
0x80190193 : Forbidden (403).

Given this is targeting a user or ITPro.  For the user, they can run the app and the license will come down from the store. Therefore not an error.
For the ITPro, they can pass in the --skip-license to avoid this case.

### Steps to reproduce

winget download 9WZDNCRFJ3PZ -d c:\temp\deleteme\9WZDNCRFJ3PZ

### Expected behavior

To be told the package was successfully installed and not error.

### Actual behavior

Failed to retrieve Microsoft Store package license
An unexpected error occurred while executing the command:
0x80190193 : Forbidden (403).

### Environment

```shell
Windows Package Manager (Preview) v1.9.1792-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26255.5000
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.1792.0
```

**Comment by CyrilShi** [comment]
I have the same issue , but it seems not affect to download completed.

**Comment by denelon** [comment]
You can use "--skip-license" to avoid downloading the license file. It's only necessary if the intended use is for "offline" installation on another host that isn't able to connect to the licensing server.
