### ISSUE TITLE
WinGet download has unhelpful error text when download not supported.

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/winget-cli#4645]
### Brief description of your issue

Not all apps in the store support download. When you download an app that does not support download you get the following error

Failed to retrieve Microsoft Store package download information
An unexpected error occurred while executing the command:
Failed to call SfsClient GetLatestAppDownloadInfo. ErrorCode: 2147492868 Message: 404 Not Found
0x8a150081 : Failed to get Microsoft Store package download information.

### Steps to reproduce

winget download  9PJN3DBXFP9M

### Expected behavior

I expect the client to offer a more useful message. 

The package you requested does not support the download command.

The current error makes me think access to the store is broken and I may spend unneccesary cycles trying to figure out what is wrong.

[It should be noted that filtering store apps in search that do not support download might improve the experience]

### Actual behavior

Failed to retrieve Microsoft Store package download information
An unexpected error occurred while executing the command:
Failed to call SfsClient GetLatestAppDownloadInfo. ErrorCode: 2147492868 Message: 404 Not Found
0x8a150081 : Failed to get Microsoft Store package download information.

### Environment

```shell
Windows Package Manager (Preview) v1.9.1792-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26255.5000
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.1792.0
```

**Comment by JimMoyle** [comment]
i'd like to see a proper reason here, and make it actionable, who should the admin contact to make this downloadable.  is it microsoft, is it the vendor, etc.
