### ISSUE TITLE
Delivery Optimization service download timeout

### ISSUE THREAD

**Issue by Gregor1996** [microsoft/winget-cli#4648]
### Brief description of your issue

When downloading large files with the Delivery Optimization downloader the download randomly stops, probably because it times out.
When the download stops it must be interrupted using Cntrl + C.

### Steps to reproduce

Download a large package like KiCad.KiCad using the default network downloader.
It will happen most of the times with a network that has only a 50 Mb/s actual throughput (this should be not so important since the download caps at 30 Mb/s anyways).
Tested even on different networks and machines.

### Expected behavior

The download completes correctly.

### Actual behavior

The download freezes, and nothing happens.
Using Cntrl + C is required to stop the download.

### Environment

```shell
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3880
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**Comment by Gregor1996** [comment]
Changing the downloader to the WinINet APIs required a full reboot. This was visible from the reduced download speed (aproxx. 17.1 Mb/s) after the switch.
But on this second machine, a Surface Laptop 6 for Business, does not help while it completely fixed the problem on my Dell Inspiron 5505

**Comment by Gregor1996** [comment]
> I'm not understanding why it would need a full reboot; Can you share how you changed the downloader?

It was probably my fault, I moved the documentation link comment at the beginning of the file, before the braces.
Anyways, on this device even the WinINet APIs downloader does not work, on the Dell it did not require a full reboot to start working after I changed to the WinINet APIs downloader.

Anyways I will attach the settings file.

[settings.json](https://github.com/user-attachments/files/16267132/settings.json)

**Comment by Gregor1996** [comment]
This is a screenshot clearly displaying the timeout problem, this is on the above mentioned Surface with WinINet APIs as a downloader
<img width="1248" alt="image" src="https://github.com/user-attachments/assets/ab1e997b-a5e0-4e9c-a66b-e65f42f45406">
The Delivery Optimization downloader works with my Hotspot Mobile connection
<img width="867" alt="image" src="https://github.com/user-attachments/assets/caff4fd6-38a4-47f3-ad77-2e6d72558b87">

**Comment by Gregor1996** [comment]
I have an update.
It is now not working even on my Dell with WinINet APIs downloader.

**Comment by denelon** [comment]
In general, we're not getting many reports of slow downloads since the download is coming from the publisher's URL for the package there isn't much we can do about that. 

From the WinGet side of things, do you see the same kind of download performance issues if you use the "Download" command?

`winget download <package id>` - The installer and manifest would land in the Downloads directory by default.

**Comment by Gregor1996** [comment]
> In general, we're not getting many reports of slow downloads since the download is coming from the publisher's URL for the package, and there isn't much we can do about that.
> 
> From the WinGet side of things, do you see the same kind of download performance issues if you use the "Download" command?
> 
> `winget download <package id>` - The installer and manifest would land in the Downloads directory by default.

I never talked about a performance issue, I would be okay if the download took 1 hour.
The issue I talked about is the download freezing before completion, consistently, 100 % of the time, with large downloads.

In fact I get exactly the same behaviour from the "Download" command, the download freezes and does not recover, the only thing that can be done is cancel the download.

Additionally the package I'm experiencing the issue with is hosted on GitHub, and have the same download speed of all the Microsoft packages hosted on there.

At last I've searched the web for this issue and did not find any other post talking about this. For this reason I've held from reporting it a year ago when I've first experienced it on my Dell, and I'm reporting this issue now that I've verified it on a second device, and now that the fix I've found for my Dell, using the WInINet's API instead of the standard Delivery Optimization, stopped working

**Comment by Gregor1996** [comment]
I have additional findings.

The download timeout is set exactly at 5 minutes, even if I partially disconnect my device from the network it still times out after 5 minutes.

Can you guys look into that? Is this a Winget timeout or is it a GitHub timeout?
If it is a GitHub timeout where should I report the issue?

Can someone look at this??

**Comment by chuhyeonjin** [comment]
I think it is a DO timeout issue because when I used the WinINet downloader, I was able to download it normally. The reason why the solution to use the WinINet downloader doesn't work is probably because of the issue that occurred after the proxy support update (#4695, already resolved, but not released).
