### ISSUE TITLE
PowerShell module still prerelease or stable?

### ISSUE THREAD

**Issue by ThomasNieto** [microsoft/winget-cli#4651]
### Brief description of your issue

Is the powerShell module still prerelease or stable? The module manifest says that its still prerelease but the module version is past 1.0 without a prerelease label.

> PowerShell Module for the Windows Package Manager Client. Due to https://github.com/PowerShell/PSResourceGet/issues/85 this module is not marked as prerelease but should be treated as such.

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Environment

```shell
N/A
```

**Comment by denelon** [comment]
We're going through the process to get the comment updated as well as add the WinGet Icon to the Microsoft.WinGet.* modules.
