### ISSUE TITLE
PowerShell module manifest PSEdition does not include Desktop

### ISSUE THREAD

**Issue by ThomasNieto** [microsoft/winget-cli#4652]
### Brief description of your issue

Currently the `CompatiblePSEditions` value in the module manifest lists `Core`. The `PowerShellVersion` is 5.1 so `CompatiblePSEditions` should be `@('Desktop', 'Core')`

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Environment

```shell
PowerShell Module version: 1.8.1133
```

**Comment by stephengillie** [comment]
[Policy] Powershell
