### ISSUE TITLE
PowerShell module manifest includes Crescensdo keys

### ISSUE THREAD

**Issue by ThomasNieto** [microsoft/winget-cli#4653]
### Brief description of your issue

The PowerShell module does not leverage Crescendo anymore so the following keys should be removed.

https://github.com/microsoft/winget-cli/blob/b41093b15a4a12c7abeff4e1aa7b92a728f99a40/src/PowerShell/Microsoft.WinGet.Client/ModuleFiles/Microsoft.WinGet.Client.psd1#L155-L159

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Environment

```shell
1.8.1133
```

**Comment by stephengillie** [comment]
[Policy] Powershell
