### ISSUE TITLE
Resizable Column Headers

### ISSUE THREAD

**Issue by JAK1047** [microsoft/winget-cli#4684]
### Description of the new feature / enhancement

A lot of package names can be fairly long and on a 4K monitor the text DPI resizing makes it so these often are longer than the column header lengths and get cut off

![image](https://github.com/user-attachments/assets/c9336fe1-a14e-46e9-af45-372c05037d41)

Would be handy to be able to click between the column header bars to drag and resize similar to other data tables.

### Proposed technical implementation details

Either the ability to resize the column headers or maybe just zoom controls on the app itself. Although I think the former would be easier to implement.

**Comment by denelon** [comment]
This looks like a request that should be made over at https://github.com/marticliment/UnigetUI

**Comment by JAK1047** [comment]
I apologize I clicked the wrong board you're 100% correct
