### ISSUE TITLE
Winget should support a "Privacy Policy" URL

### ISSUE THREAD

**Issue by JohnMcPMS** [microsoft/winget-cli#471]
# Description of the new feature/enhancement

Winget should support a "Privacy Policy" URL feature (optional, for now) so that you can check the policy before installing.

[Originally submitted by @ptorr-msft]

# Proposed technical implementation details (optional)

Much like the License field, the manifest should include a privacy policy field with a URL to allow the user to see and inspect before proceeding.  I'm not personally familiar enough with policies to know if they have already landed on a small subset of well known / used values such that they can simply be referenced by name, but it might be worth investigating to see if there should be both a PrivacyPolicy and PrivacyPolicyUrl field.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/blob/cf85374d37cc9391e22bff62aac9b62b524d4398/schemas/JSON/manifests/v1.1.0/manifest.defaultLocale.1.1.0.json#L75-L78
