### ISSUE TITLE
Can't search for a specific version of yt-dlp

### ISSUE THREAD

**Issue by Mujtaba0150** [microsoft/winget-cli#4721]
### Brief description of your issue

I can't search for other versions of yt-dlp because its ID matches the ID of its nightly version, the only difference is that in the the nightly version has ".nightly" at the end, which winget fails to identify and differentiate and instead tells me that there are multiple packages found matching input criteria but there's no other differentiating factor but the ID.

```
C:\Users\user>winget search --name yt-dlp --versions
Multiple packages found matching input criteria. Please refine the input.
Name           Id                    Source
-------------------------------------------
yt-dlp         yt-dlp.yt-dlp         winget
yt-dlp-nightly yt-dlp.yt-dlp.nightly winget

C:\Users\user>winget search --id yt-dlp.yt-dlp --versions
Multiple packages found matching input criteria. Please refine the input.
Name           Id                    Source
-------------------------------------------
yt-dlp         yt-dlp.yt-dlp         winget
yt-dlp-nightly yt-dlp.yt-dlp.nightly winget

C:\Users\user>winget search --name yt-dlp --id yt-dlp.yt-dlp --versions
Multiple packages found matching input criteria. Please refine the input.
Name           Id                    Source
-------------------------------------------
yt-dlp         yt-dlp.yt-dlp         winget
yt-dlp-nightly yt-dlp.yt-dlp.nightly winget
```

### Steps to reproduce

Search for available versions of yt-dlp using "winget search --id yt-dlp.yt-dlp --versions"

### Expected behavior

I expect it to give me a list of all previous version numbers of yt-dlp.

### Actual behavior

It says "Multiple packages found matching input criteria. Please refine the input." whereas there's no other factor except the ID and the name that can be used to differentiate the yt-dlp package from the nightly package 

### Environment

```shell
C:\Users\mujta>winget --info
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4717
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                D:\User\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**Comment by Trenly** [comment]
Can you try `winget search -e yt-dlp.yt-dlp --versions` ?

**Comment by stephengillie** [comment]
Even with the `--exact` flag, multiple results are returned:

```
PS C:\ManVal> winget search yt-dlp --exact
Name           Id                    Version           Match           Source
-----------------------------------------------------------------------------
yt-dlp         yt-dlp.yt-dlp         2024.08.06                        winget
yt-dlp-nightly yt-dlp.yt-dlp.nightly 2024.08.01.232808 Command: yt-dlp winget
```

My workaround is to use PowerShell, and manually perform the filtering:
```PowerShell
$WinGetOutput = Find-WinGetPackage $PackageIdentifier | where {$_.id -eq $PackageIdentifier}
```

**Comment by Mujtaba0150** [comment]
> Can you try `winget search -e yt-dlp.yt-dlp --versions` and `winget search -e yt-dlp --versions` ?

Using 'winget search -e yt-dlp.yt-dlp --versions' works absolutely fine but with `winget search -e yt-dlp --versions`, I specifically had to add the --name tag as well for it to work. Anyhow, thanks for replying, I guess I'll be marking this as closed seeing as the issue was resolved for this particular case at least, though I would prefer it worked the same way the command 'winget install --id yt-dlp.yt-dlp' works.

**Comment by Mujtaba0150** [comment]
> Even with the `--exact` flag, multiple results are returned:
> 
> ```
> PS C:\ManVal> winget search yt-dlp --exact
> Name           Id                    Version           Match           Source
> -----------------------------------------------------------------------------
> yt-dlp         yt-dlp.yt-dlp         2024.08.06                        winget
> yt-dlp-nightly yt-dlp.yt-dlp.nightly 2024.08.01.232808 Command: yt-dlp winget
> ```
> 
> My workaround is to use PowerShell, and manually perform the filtering:
> 
> ```powershell
> $WinGetOutput = Find-WinGetPackage $PackageIdentifier | where {$_.id -eq $PackageIdentifier}
> ```

I would recommend using the --name flag. Apparently that seems to fix the issue, as in 'winget search --name yt-dlp --exact'
