### ISSUE TITLE
Winget shows wrong package id for Java 8

### ISSUE THREAD

**Issue by Maccamh** [microsoft/winget-cli#4776]
### Brief description of your issue

winget id for java 8 changes after installation causing issues with uninstall as id then changes.

### Steps to reproduce

when running winget search "java 8" I get the below results

Name   Id                            Version    Source
-------------------------------------------------------
Java 8 Oracle.JavaRuntimeEnvironment 8.0.4210.9 winget

when attempting to uninstall using the above id it wont remove this is because the id is changing upon install

so if i run winget list 

it outputs the result like this
Name                                              Id
Java 8 Update 421 (64-bit)             ARP\Machine\X64\{77924AE4-039E-4CA4-87… 8.0.4210.9

Because of this I am unable to automate its uninstall via Intune which this did work previously as the id did not change,

### Expected behavior

expected behavior is to output the same ID after installation so it can used as an identifier for uninstall

### Actual behavior

the uninstall command fails and i have to manually look up the application, but this is not feasible in an environment with over 2000 laptops.

### Environment

```shell
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.4037
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0
```

**Comment by denelon** [comment]
@Trenly or @mdanish-kh do you think this is this a manifest issue, an installer issue or a WinGet issue?

**Comment by mdanish-kh** [comment]
@Maccamh Can you share the full output of `winget list java`?


> the uninstall command fails and i have to manually look up the application

As a workaround, you can use a command like `winget uninstall --name "Java 8 Update 421 (64-bit)"`, but I understand if all machines have a different java version, then this command may not be applicable

**Comment by mdanish-kh** [comment]
> @ Trenly or @ mdanish-kh do you think this is this a manifest issue, an installer issue or a WinGet issue?

I couldn't repro the issue on my VM. Looks to me that the installed package for user isn't getting correlated back to a source, hence the `ARP/Machine/...` package id being displayed.

**Comment by Maccamh** [comment]
Hi,

I'm out of the office til Tuesday but I'll test soon as I get in

**Comment by Maccamh** [comment]
I have attached the output log
[WinGet-2024-09-03-14-06-13.810.log](https://github.com/user-attachments/files/16849628/WinGet-2024-09-03-14-06-13.810.log)

**Comment by mdanish-kh** [comment]
Looks like some manifest fields had incorrect values, which would definitely have an effect on correlation and the issue you're seeing. @ItzLevvie pushed PRs to update these. Once those have been published (within an hour or so), I'll drop a comment and ask you to try again

**Comment by mdanish-kh** [comment]
@Maccamh All PRs should now be published. Can you check again if you're still able to repro the issue?

**Comment by Maccamh** [comment]
Hi Mdanish-kh,

That's now resolved the issue. Thanks for the quick support on this!
![Screenshot 2024-09-04 091944](https://github.com/user-attachments/assets/8ed1a782-874d-4b13-b9f6-1beeefd69044)

**Comment by mdanish-kh** [comment]
Credit to @ItzLevvie for the PRs

Close with reason: Resolved;
