### ISSUE TITLE
Class not registered when running winget from a C# program.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/winget-cli#4797]
### Brief description of your issue

This repros only on the internal self-host build.

I get a class not registered exception when using a C# console app to make a new admin process with shell execute.

I did make a feedback hub item, but the item is not appearing in my "My Feedback"  I can send the dumps and traces to someone instead.

### Steps to reproduce

1. Make a console app.
2.  Add this to main

            var processStartInfo = new ProcessStartInfo();
            processStartInfo.UseShellExecute = true;
            processStartInfo.FileName = "winget";
            processStartInfo.ArgumentList.Add("configure");
            processStartInfo.Verb = "RunAs";

            Process process = Process.Start(processStartInfo);

3. run the program.

### Expected behavior

winget launches in a cmd window as admin.

### Actual behavior

an exception.

### Environment

```shell
Windows Package Manager (Preview) v1.9.2411-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26286.5002
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.2411.0
```

**Comment by stephengillie** [comment]
I've had success with a slightly different way - starting PowerShell with `new ProcessStartInfo("PowerShell.exe");` and using `.WriteLine` to write the search string to it, then reading out the output with `.ReadToEnd()`. It's how I get package manager data into my C# application: https://github.com/stephengillie/winget-pkgs/blob/587e5ba43b7c79cc561d0bfcbbf17ff80c5aba25/Tools/ManualValidationPipeline.cs#L2459

What was the exception - did it involve creating a window? I'm not sure that the package manager would know to call cmd.exe, nor know its specific location on a given system, and might need some help with the window generation.

**Comment by dhoehna** [comment]
> What was the exception
    Class not registered

> involve a window?
    No

>  location on a given system
Windows shell.  Same how windows knows where cmd.exe and wt.exe is.  In my repro if "winget" is replaced with wt.exe windows terminal opens.

**Comment by dhoehna** [comment]
After talking to internal Microsoft people, this issue is a SelfHost issue on the selfhost build.  It is not a winget issue.
