### ISSUE TITLE
Missing `Available` column when use `winget list` command

### ISSUE THREAD

**Issue by KamilKandzia** [microsoft/winget-cli#4802]
### Brief description of your issue

Until a week ago, the Available column was normally visible, whereas today it is not. Has something changed in the configuration of the list command? 
![Screenshot 2024-09-10 173524](https://github.com/user-attachments/assets/34942b5a-2efc-4068-8b8e-aeb2e248dd44)

### Steps to reproduce

Use `winget list` command

### Expected behavior

Show `Available` column

### Actual behavior

Missing `Available` column

### Environment

```shell
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.4037
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**Comment by denelon** [comment]
@KamilKandzia the available column is only displayed when one or more packages have updates available via a configured source. Otherwise, the space is "saved" to provide a few more columns to display the package name or the package identifier.

**Comment by KamilKandzia** [comment]
> @KamilKandzia the available column is only displayed when one or more packages have updates available via a configured source. Otherwise, the space is "saved" to provide a few more columns to display the package name or the package identifier.

Hi @denelon , thank you for your reply. I did a test with downgrading the 7-zip version and indeed the column appeared. However, I was surprised that after upgrading 7-zip to the latest version, the column disappeared again, even though, for example, the telegram app needs to be upgraded and it is available via winget. Is this correct behaviour?
[after downgrade and upgrade.txt](https://github.com/user-attachments/files/16947772/after.downgrade.and.upgrade.txt)

**Comment by denelon** [comment]
I'm not sure if all the other apps function as "side-by-side". You'd need to run `winget list` to see if multiple versions are installed. In the case of side-by-side, it's possible an earlier and the latest version are both installed. The intent is to not show an upgrade available in those cases where the latest and one or more earlier versions are present on the system.
