### ISSUE TITLE
why can't  support custom  cache path and  package   installer path ,    so   bold ?   or slack ? 

### ISSUE THREAD

**Issue by Super1Windcloud** [microsoft/winget-cli#4818]
### Description of the new feature / enhancement

why can't  support custom  cache path and  package   installer path ,    so   bold ?   or slack ? 

### Proposed technical implementation details

why can't  support custom  cache path and  package   installer path ,    so   bold ?   or slack ?

**Comment by stephengillie** [comment]
I'm guessing that this might be 2 feature requests:
1. Have the package manager able to operate from arbitrary locations in the filesystem.
2. Have the package manager able to download and [cache](https://github.com/microsoft/winget-cli/discussions/2911) a package in an arbitrary location in the filesystem. 

To work from the first suggestion, I would also like to add a feature request for a portable version of the package manager.

**Comment by denelon** [comment]
I'm not sure I understand the request here.

Can you share the scenario with a bit more detail?

WinGet Download allows you to download installers to a specified location, and it includes their dependencies.

When installers support a non-default location the "--location" argument can be passed to the install command.

**Comment by Super1Windcloud** [comment]
OK ,  And  I  think    scoop or  choco  better
