### ISSUE TITLE
PowerShell module v1.9.2505 broken on PowerShell v7.4.5

### ISSUE THREAD

**Issue by o-l-a-v** [microsoft/winget-cli#4829]
### Brief description of your issue

[1.9.2411](https://www.powershellgallery.com/packages/Microsoft.WinGet.Client/1.9.2411) worked just fine, but with the recently released [1.9.2505](https://www.powershellgallery.com/packages/Microsoft.WinGet.Client/1.9.2505) I can't even do the following:

```pwsh
PS > Microsoft.WinGet.Client\Get-WinGetPackage -Source 'Winget'

Get-WinGetPackage: Operation is not supported on this platform. (0x80131539)

PS >
```

### Steps to reproduce

* Run PowerShell v7.4.5 x64 on Windows 11 23H2
  * If you want to make sure your profile does not mess with anything, WIN + R `pwsh -noprofile`
* Run `Microsoft.WinGet.Client\Get-WinGetPackage -Source 'WinGet'`

### Expected behavior

Should work as previous version of said module (`Microsoft.WinGet.Client`).

### Actual behavior

Crashes

### Environment

* Not using the WinGet client.
* `winget --version` = v1.8.1911

**Comment by wmmc88** [comment]
I am also running into this issue. It also seems that the installers at https://github.com/microsoft/winget-cli/releases will also always install the latest powershell module on the system, rather than a specific pinned version for that release. This is problematic when one needs a reproducible environment

**Comment by denelon** [comment]
@o-l-a-v thanks for reporting this!

We're working to get a fix out ASAP.

**Comment by JohnMcPMS** [comment]
The new version has been delisted to prevent further impact.
