### ISSUE TITLE
Is it possible to hide the disclaimer for packages from Microsoft?

### ISSUE THREAD

**Issue by LiCaoZ** [microsoft/winget-cli#4835]
### Description of the new feature / enhancement

![](https://github.com/user-attachments/assets/4b96f943-8413-4bae-a299-9442aab36e13)

Currently, when a user installs a package from the winget source, winget will prompt something like this:

> This application is licensed to you by its owner.  
> Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.

It makes sense when the user installs an application from a third-party developer. But if the target application is from Microsoft, things get a little confusing.

So, in my opinion, it will be better if winget hides the prompt or replaces it with the link pointing to https://www.microsoft.com/legal/terms-of-use when installing a Microsoft application.

**Comment by mdanish-kh** [comment]
Duplicate of #288
