### ISSUE TITLE
Sixel implementation not working in WinGet 1.9.2507

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#4869]
### Brief description of your issue

Sixel images not rendered.

### Steps to reproduce

Add the following to WinGet settings:

```JSON
    "visual": {
        "progressBar": "sixel", 
        "enableSixels": true
    }
```

### Expected behavior

Sixel images are rendered in `winget --info` and in the output from help.
Icons rendered for packages using `winget show <package>`
Sixel style progress output.

### Actual behavior

Default WinGet progress output.

### Environment

Windows Package Manager v1.9.2507
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26100.2023
System Architecture: Arm64
Package: Microsoft.DesktopAppInstaller v1.24.2507.0

**Comment by Va992** [comment]
> ### Brief description of your issue
> 
> Sixel images not rendered.
> ### Steps to reproduce
> 
> Add the following to WinGet settings:
> 
>     "visual": {
>         "progressBar": "sixel", 
>         "enableSixels": true
>     }
> 
> ### Expected behavior
> 
> Sixel images are rendered in `winget --info` and in the output from help. Icons rendered for packages using `winget show <package>` Sixel style progress output.
> ### Actual behavior
> 
> Default WinGet progress output.
> ### Environment
> 
> Windows Package Manager v1.9.2507 Copyright (c) Microsoft Corporation. All rights reserved.
> 
> Windows: Windows.Desktop v10.0.26100.2023 System Architecture: Arm64 Package: Microsoft.DesktopAppInstaller v1.24.2507.0
