### ISSUE TITLE
[Package Issue]: Hashicorp.Terraform upgrade/uninstall issue with zip/portable application

### ISSUE THREAD

**Issue by kdpuvvadi** [microsoft/winget-cli#4879]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

upgrading, uninstalling issue with the zip/portable apps.
also found with `TerraformLinters.tflint`

### Steps to reproduce

- Install `winget install Hashicorp.Terraform -v 1.3.8` 
- upgrade `winget upgrade Hashicorp.Terraform`
    - `No installed package found matching input criteria.` 
- uninstall `winget uninstall Hashicorp.Terraform` 
    - `No installed package found matching input criteria.`

### Actual behavior

`No installed package found matching input criteria.` 

### Expected behavior

either upgrade or uninstall proprly

### Environment

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2604
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by Hekter** [comment]
[WinGet-2024-10-14-18-38-17.233.log](https://github.com/user-attachments/files/17369973/WinGet-2024-10-14-18-38-17.233.log)

Had this same issue today as well! Log attached above.

PS C:\Users\nvdxs14> winget list --id Hashicorp.Terraform
Name                Id                  Version Available Source
----------------------------------------------------------------
Hashicorp Terraform Hashicorp.Terraform 1.9.6   1.9.7     winget

**Comment by mdanish-kh** [comment]
There were some improvements made to the manifests that _should_ have resolved this issue. @kdpuvvadi @Hekter Can you check if you are still able to reproduce the issue?

[comment]: <Needs-Author-Feedback>

---

<details>

<summary>Explanation for the interested folks</summary>



```
2024-10-15 20:47:28.885 [REPO]  ... installed package [ARP\User\X64\Hashicorp.Terraform_Microsoft.Winget.Source_8wekyb3d8bbwe] had multiple correlations and is being ignored as a match for [Hashicorp.Terraform]
2024-10-15 20:47:28.885 [CLI ] Search result size: 0
2024-10-15 20:47:28.885 [CLI ] No app found matching input criteria
```

The problem appears to be that CLI is seeing multiple correlations for the same package. I looked at the manifests and saw that multiple flavors of terraform (`HashiCorp.Terraform`, `HashiCorp.Terraform.Alpha`, `HashiCorp.Terraform.Beta`, `HashiCorp.Terraform.RC`) shared the same package matching metadata (Publisher, PackageName etc). This made it difficult for CLI to disambiguate the installed package and try to find a unique match from the source. Went through the manifests and changed the PackageNames of [non-stable releases of terraform](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+author%3Amdanish-kh++is%3Aclosed+Use+different+PackageName+for+non-stable+releases+of+terraform)

</details>

**Comment by kdpuvvadi** [comment]
Seems like it's working now. Upgrade/Uninstall both are working. If it needs to be tested thoroughly, i'll test it this wekend.

**Comment by mdanish-kh** [comment]
Close with reason: Resolved by updating manifests to use unique PackageName across different channel packages;
