### ISSUE TITLE
Can't install both x86 and x64 architecture Microsoft.DotNet.SDK.8

### ISSUE THREAD

**Issue by rkeithhill-keysight** [microsoft/winget-cli#4883]
### Brief description of your issue

Once I have installed one architecture of the .NET 8.0 SDK (say x64), winget refuses to install the other architecture:
```
> winget install Microsoft.DotNet.SDK.8 --architecture x86
Found an existing package already installed. Trying to upgrade the installed package...
No available upgrade found.
No newer package versions are available from the configured sources
```
Yet if I go to https://dot.net and download both the x64 & x86 SDKs, I can install them side-by-side no problem.

### Steps to reproduce

Run `winget install Microsoft.DotNet.SDK.8`.  This install the x64 SDK. Now try `winget install Microsoft.DotNet.SDK.8 --architecture x86`. That fails when it shouldn't. 

Now try the direct link to the x86 SDK: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.403-windows-x86-installer  That installs just fine.

### Expected behavior

I expect to be able to install both the x64 and x86 .NET 8.0 SDKs using winget.

### Actual behavior

I can install one but not both because winget thinks the package is already installed. Apparently it's not distinguishing between x64 and x86 being different packages.

### Environment

Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.5011
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled

**Comment by stephengillie** [comment]
This sounds like a problem with the `x86` version of the package. This Issue should probably be moved to the [winget-pkgs](https://github.com/microsoft/winget-pkgs/issues/) repo, since only one package is impacted. It might be a manifest issue that can be corrected with a PR.

**Comment by rkeithhill-keysight** [comment]
Issue seems to be with the Microsoft.DotNet.SDK.8 package.
