### ISSUE TITLE
Can the software installation path be set?

### ISSUE THREAD

**Issue by AirBashX** [microsoft/winget-cli#489]
How to set the installation path of the software, for example, I want to install the 7Z software on the D drive, can it be done? If this function is not available, will this function be added in the future?

**Comment by denelon** [comment]
This issue could be associated with #140 and #194 default path settings as well.

**Comment by OfficialEsco** [comment]
There is already a function in Winget, use `winget install Software.Name --location "C:\Folder\Software.Name"`

However the support is limited right now.

BUT, we also just got support for Interactive mode `winget install Software.Name -i`, which is a safer option then --location right now

**Comment by G0rocks** [comment]
These issues are similar: #201 , #337

**Comment by denelon** [comment]
As @OfficialEsco mentioned, this has been implemented in the client, but it does depend on the installer having support for the install location.

**Comment by Michaelzhouisnotwhite** [comment]
So dis nei
