### ISSUE TITLE
Add an option to exclude apps from major/minor updates

### ISSUE THREAD

**Issue by FaserF** [microsoft/winget-cli#4894]
### Description of the new feature / enhancement

We have some applications where we cannot update the applications without validating them first. But we would like to get patch updates (1.0.2 : 1=Major, 0=Minor, 2=Patch) for security reasons f.e.

I would love to see an option for this, similar to `winget pin add`
Tried implementing this in another way, but having it directly at winget would be great. https://github.com/Romanitho/Winget-AutoUpdate/pull/711

### Proposed technical implementation details

Extend for example the current pin option with these parameters: 

`winget pin add Company.AppName --PatchOnly `

for example

**Comment by mdanish-kh** [comment]
Have you tried setting a [gating pin](https://learn.microsoft.com/en-us/windows/package-manager/winget/pinning#pin-types)? For your use case, I believe the following command will do

```
winget pin add Company.AppName --version 1.0.*
```

**Comment by mdanish-kh** [comment]
[Policy] Needs-Author-Feedback

**Comment by FaserF** [comment]
Thats a great input, let me check that. I think this will solve it :) Thanks!
