### ISSUE TITLE
Change winget 'verbs' to be namewise compatible with PowerShell

### ISSUE THREAD

**Issue by doctordns** [microsoft/winget-cli#491]
# Description of the new feature/enhancement

At present, winget.exe has several 'verbs' which are not compatible with PowerShell. I now that Winget, in its current form, is probably never going to be targeted at IT pros or at enterprise management, but please don't make things INCONSISTENT where you can avoid it. You  can change the verb names today with little impact. Please honour PowerShell's (and Microsoft's) sacred vow. 

# Proposed technical implementation details (optional)

1. Instead of WInget Show, ake the verb 
2. Rethink the Source - it;'s not a verb - how about SET
3. Instead of validate, use Test
4. Instead of hash - use get (WInget Get Hash ...)

Even if you never create PowerShell cmdlets, at least honour the sacred vow.

**Comment by megamorf** [comment]
I don't see a relation between winget's subcommands and PowerShell conventions. Winget as C++ program is just like any other C#, Golang or Python application and can implement whatever is useful to the developer or its users. There are certain platform specific conventions such as short and long forms of parameters on Linux/Unix and the ability to specify parameters starting with a dash or slash on Windows. But PowerShell terminology is not a standard for regular command line applications.
The issue that requests native PowerShell support contains some useful implementation ideas and I fully expect that to adhere to conventions that originated from the monad manifesto.

**Comment by denelon** [comment]
I assume you are referencing the "[Approved Verbs](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7)" in your comment regarding the vow. If not, please cite the source.

Unfortunately, English is a complex language where many words can be both a verb or a noun. We do have plenty of time to rename commands, but I'm not aware of a precedent for many of the things the package manager is doing. The native PowerShell implementation is on the backlog, so I agree we should try to arrive at the right set of verbs.

"Search" and "Show" are both on the verbs page referenced above. 

"Test" may be better than "Validate".

"Set" is likely to be highly overloaded, but we've had some feature discussion around "settings" and the feature toggle.

"Hash" may also move away from it's position as a top level action and be replaced with a manifest creation capability.

As I was writing this, I saw @megamorf post. I'll have to look at the [Monad Manifesto](http://www.jsnover.com/Docs/MonadManifesto.pdf).

I am reminded of the [two hard things](https://www.martinfowler.com/bliki/TwoHardThings.html), and we have both here in the Windows Package Manager.

**Comment by megamorf** [comment]
@denelon I believe you should definitely read the manifesto. Almost 20 years have passed since then and the resulting PowerShell ecosystem has grown tremendously. That's because it offers a real business value to companies and that's the reason why people are demanding native PowerShell support. 

In the past I've provisioned Windows terminal servers (Citrix XenApp) and the installation of software packages and windows updates required multiple restarts and took 4 hours. The entire process was orchestrated by PowerShell, i.e. VM provisioning, package installations, updates and integration testing with Pester. If everything is written in PowerShell the code is a lot more readable and less prone to errors since error handling and logging is seamless.

**Comment by doctordns** [comment]
I thought I had responded to this, but I must have forgotten to send. :-)

At the end of the day, every project team has options. And as Sonver says: to ship is to choose.  Every product gets to decide cool things like naming and so on but many of those decisions have already been made - for better or worse. Reading the manifesto is, in my view, required of anyone running a software project at MSFT. 

If the team want to get IT Pro buyin and broad corporate adoption, a good PowerShell story is essential, in my view. We have had the better part of 17 years of getting IT Pros used to and enthusiastic about PowerShell. With a good PowerShell module you can both satisfy the individual developer and ensure the IT pro has control over corporate resources.

On the assumption that you DO want to have PowerShell cmdlets, and have a good winget module, you really really need to learn the lessons of history. Look at the Hyper-V team. - with 2008 there was no module. Early community efforts (which were sub-optimal) were very quickly improved to the point where there is a great module that is more than fit for purpose.  I would hope to see the same with winget and am very happy to participate/test when you get your module developed. 

The important lesson here, I feel, is to NOT re-invent wheels just because you can or because you feel you know your customers so well. Yes, you may have verbs that feel better, but those decisions were already made. Use Get, and IT Pros know what to do - and you have a better approach towards eventual cmdlets. 

Since there is no sizeable investment, yet, in winget automation, establishing as much parity with PowerShell as possible NOW, means minimal change. And with a bit of prodding, developers won't really notice or care - give them great cmdlerts and they will say thank you.

Please listen to the IT Pro input and at least provide a good roadmap towards an eventual module.

**Comment by denelon** [comment]
As we've released the first version of the PowerShell Module and cmdlets for WinGet, we're going to focus on that effort in terms of being consistent with PowerShell idioms.

We also recently added aliases for several commands to help with muscle memory. The idioms with the CLI are not the same as PowerShell, so I'm going to close this issue as "not planned".

**Comment by doctordns** [comment]
Another mistake, imho. You could have done this at the get-go but you chose not to. I get to ship is to choose Dadly, you ahce chosen to be deliberately incompatible and have shipped. that, 

For thus reason my advice, for this reason, continue to be to avoid this power toy. Wish I could be more positive.

**Comment by Masamune3210** [comment]
I'm confused why you thought this would be something worth adding. They are fixing what you didn't like, but it wasn't immediately from the start so you still complained?
