### ISSUE TITLE
winget list upgrade-available shows packages already upgraded

### ISSUE THREAD

**Issue by eabase** [microsoft/winget-cli#4912]
### Brief description of your issue

I installed the latest [HDSDR](https://www.hdsdr.de/wnew.html) package/drivers and now winget still reports updates available for the same package. 

```powersehll
# winget list --upgrade-available

Name                     Id          Version  Available Source
--------------------------------------------------------------
HDSDR 2.81               DG0JBJ.HDSDR Unknown 2.81-b9   winget

3 upgrades available.
```

### Steps to reproduce

Install old version, unless you already have one. 
Then install the latest version.

### Expected behavior

That the package is reported as up-to-date / latest, and not shown when using the `--upgrade-available` 

### Actual behavior

Showing multiple available versions for the same package id, even if already at latest.

### Environment

**`winget --info`**

```shell
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.4317
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**`How can I manually set the package version of what I have installed?`**

**Comment by eabase** [comment]
:arrow_up: Not true.
(I was copy pasting and editing a previous issue for quick post.)

**Comment by Trenly** [comment]
This is an expected behavior when using `winget list --upgrade-available` because the installer doesn’t write any version information to the registry, as seen by the version being `Unknown`. If you use just `winget upgrade` to list the upgrades, you won’t see the package in the list unless you use `--include-unknown`.

The only workaround would be to edit the registry entry for the package manually to add `DisplayVersion`, but you would need to do that for every update.

The publisher of the software needs to update their installer to write the version to the registry.

**Comment by eabase** [comment]
@Trenly 

> The only workaround would be to edit the registry entry for the package manually to add `DisplayVersion`..

That's fine, but are you sure it's a Registry entry and not in one of the package SQLite3 databases? 
Where would I find that registry entry?

**Comment by eabase** [comment]
I manged to rid the message by adding the missing `DisplayVersion` to the follwing key:
```
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{DB200CBD-9E3E-4C72-B711-B46D6817BC51}_is1
```

Thank you.
