### ISSUE TITLE
V 1.9 Breaks Winget PowerShell Module (Microsoft.VCLibs.140.00.UWPDesktop Issue)

### ISSUE THREAD

**Issue by PckgrTom** [microsoft/winget-cli#4916]
Add-AppxPackage: Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict validation.  Windows cannot
install package Microsoft.DesktopAppInstaller_1.24.25180.0_x64__8wekyb3d8bbwe because this package depends on a
framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by
"CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor
architecture and minimum version 14.0.33728.0, along with this package to install. The frameworks with name
"Microsoft.VCLibs.140.00.UWPDesktop" currently installed Windows cannot install package
Microsoft.DesktopAppInstaller_1.24.25180.0_x64__8wekyb3d8bbwe because this package depends on a framework that could
not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation,
O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version
14.0.33728.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop"
currently installed are: {Microsoft.VCLibs.140.00.UWPDesktop_14.0.33321.0_x64__8wekyb3d8bbwe}  NOTE: For additional
information, look for [ActivityId] 821[9](https://github.com/Pckgr-Pty-Ltd/Pckgr/actions/runs/11559986811/job/32175872357#step:3:10)baaf-8b1d-0001-d2cd-3bce6329db01 in the Event Log or use the command line
Get-AppPackageLog -ActivityID 8219baaf-8b1d-0001-d2cd-3bce6329db01
Error: Process completed with exit code 1.`

### Steps to reproduce

Attempt to install the Winget PowerShell module

### Expected behavior

Module install successfully

### Actual behavior

Module is failing to install winget due to out of date dependency for Microsoft.VCLibs.140.00.UWPDesktop.

### Environment

N/A

**Comment by Trenly** [comment]
This has the same root cause as:
* https://github.com/microsoft/winget-cli/issues/4903

**Comment by denelon** [comment]
We've marked the latest stable release as "Pre-Release" here at GitHub so the Repair-WinGetPackageManager cmdlet will still install a stable release. It will install WinGet 1.8 in that case.

The version delivered by the Microsoft Store is still the latest stable 1.9 version. This change is temporary until we've addressed the dependency for Repair-WinGetPackageManager to function properly installing the dependencies necessary for WinGet 1.9.

**Comment by juwens** [comment]
@denelon please consider adding the two dependency appx files into the github releases.
That would simplify the bootstrap.

You would be independent of what version is linked to `https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx`, especially in the long run.

Bootstrap-Installation can be simplified to two simple steps.

1. downloading 1 zip file with AppInstaller msixbundle and the dependencies appx.
2. Install with `Add-AppxPackagage AppInstallerDesktop.msixbundle -DependencyPath Depencencies/*`

AFAIK this structure is the default, when you run `msbuild -t:publish ...`

**Comment by denelon** [comment]
The updated module was just published: https://www.powershellgallery.com/packages/Microsoft.WinGet.Client/1.9.25190

Please let us know if this works or is still broken for you?
