### ISSUE TITLE
Impossible to download WinGet from link provided in readme

### ISSUE THREAD

**Issue by Stephanevg** [microsoft/winget-cli#4924]
### Brief description of your issue

Hi all,

I was trying to get winget on my machine (Windows 11), and it happens that when I click the link on the read of this project (https://www.microsoft.com/p/app-installer/9nblggh4nns1) I get an error message saying `Not found`.

Additionally, when I open the Microsoft store on my machine, and search for `winget` or `app installer` it cannot seem to find it (I switched to Apps too - no luck).

![Image](https://github.com/user-attachments/assets/85ec80c6-901a-46d8-ba0c-677b1be78429)

Can you please fix as like this, I cannot install it anywhere :(

Thanks in advance!

### Steps to reproduce

open the microsoft store and search for winget.

### Expected behavior

Winget should be easy to find in the microsoft store and install.
Additionally to this, it is not clear if the release available on github can be installed directly. In the [docs](https://github.com/microsoft/winget-cli?tab=readme-ov-file#manually-update), it mentions we can 'manually update' it.
It doens't talk about manually installing it.

### Actual behavior

Winget cannot be found, thus it cannot be installed.

### Environment

Windows 11

**Comment by mdanish-kh** [comment]
You can try one of these URLs:

Microsoft Store: https://apps.microsoft.com/detail/9nblggh4nns1
Latest stable release: https://aka.ms/getwinget
Latest preview release: https://aka.ms/getwingetpreview
