### ISSUE TITLE
Add Release Asset for SHA256 of DesktopAppInstaller_Dependencies.zip

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#4938]
### Description of the new feature / enhancement

With the new file `DesktopAppInstaller_Dependencies.zip` being included in the release, there should be a way to verify the hash matches what is expected. This is required for `SandboxTest.ps1` over at winget-pkgs to function without major modifications

### Proposed technical implementation details

Add `DesktopAppInstaller_Dependencies.txt` to the release as a text file containing the SHA256 of the zip file
Alternatively, add the hashes to the .json file

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/releases/download/v1.9.25180/DesktopAppInstaller_Dependencies.txt

**Comment by Trenly** [comment]
> https://github.com/microsoft/winget-cli/releases/download/v1.9.25180/DesktopAppInstaller_Dependencies.txt

Will this continue to be part of the releases moving forward?

**Comment by denelon** [comment]
Yes, we're going to update the pipelines so the dependencies get included in the artifacts built so we can easily add them to the releases. @ryfu-msft to confirm here.
