### ISSUE TITLE
Color contamination to the console if the program was terminated by Ctrl+C

### ISSUE THREAD

**Issue by yfdyh000** [microsoft/winget-cli#494]
# Color contamination to the console if the program was terminated by Ctrl+C

# Steps to reproduce

Run `winget source list update`, or `winget search [name]` (while cache is not ready) in cmd window.
While like "/" status, press Ctrl+C hotkey to terminate it, probably due to slowness.

# Expected behavior

Reset the character color to normal when the program is terminated.

# Actual behavior

The new characters remain blue.

# Environment

```Windows: Windows.Desktop v10.0.19041.329
程序包: Microsoft.DesktopAppInstaller v1.0.41821.0
```

In China, I see the `winget source update` often takes tens of seconds or minutes to complete. Only the `https://winget.azureedge.net/cache` configured and it is accessible from browser.

**Comment by denelon** [comment]
@yfdyh000 thanks for pointing this out. By the way, you can configure the TTL on the cache refresh with this version of the client in settings. We've been looking at bandwidth issues recently.

**Comment by denelon** [comment]
@yfdyh000 is this still happening. We believe this may have been fixed in an earlier release.
