### ISSUE TITLE
'Access is denied' when installing CPU-Z

### ISSUE THREAD

**Issue by nitishvijai** [microsoft/winget-cli#495]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?assignees=&labels=&template=Bug_Report.md&title=}

# Brief description of your issue
Whenever I try to install CPU-Z using winget, the exe has successfully downloaded and hash verified, but I get an 'Access is denied' error.

# Steps to reproduce

1. Open Command Prompt or PowerShell in Windows Terminal.
2. Type "winget install CPU-Z"

# Expected behavior

CPU-Z will successfully install.

# Actual behavior

The installer returns an 'Access is denied' error, and the terminal reports "Installer failed with exit code: 1".

# Environment

```none
[winget --info]
Windows Package Manager version 0.1.41821 Preview
Windows: Windows.Desktop version 10.0.20161.1000
Package: Microsoft.DesktopAppInstaller version 1.0.41821.0

Any other software? Windows Subsystem for Linux, Windows Terminal, WinGet, PowerToys, etc.
```

**Comment by denelon** [comment]
Duplicate of #218
