### ISSUE TITLE
Add a `winget list --json`

### ISSUE THREAD

**Issue by georgettica** [microsoft/winget-cli#4965]
I might be the only one here, but I want to extract all of the data I have in winget to json so I can quickly retrieve a substet of apps from the list

Is that already available?

**Comment by mdanish-kh** [comment]
Have you tried using the [WinGet PowerShell module](https://www.powershellgallery.com/packages/Microsoft.WinGet.Client/)?

You can use `Get-WinGetPackage` cmdlet (equivalent to `winget list`). Use `Get-Help Get-WinGetPackage -Full` to see all available capabilities of the cmdlet (there are examples available at the end of help text)

**Comment by mdanish-kh** [comment]
There is also a [`winget export`](https://learn.microsoft.com/en-us/windows/package-manager/winget/export) command that can export all installed files to a json file

`winget export -o file.json`

Conversely, there's a [`winget import`](https://learn.microsoft.com/en-us/windows/package-manager/winget/import) command too that lets you install all exported applications from the exported json files with one command

**Comment by stephengillie** [comment]
The output is modest:

```JSON
PS C:\ManVal> Get-WinGetPackage | ConvertTo-Json
[
  {
    "InstalledVersion": "2.47.0.2",
    "Name": "Git",
    "Id": "Git.Git",
    "IsUpdateAvailable": false,
    "Source": "winget",
    "AvailableVersions": [
      "2.47.0.2",
      "2.47.0",
      "2.46.2",
      "2.46.1",
      "2.46.0",
      "2.45.2",
      "2.45.1",
      "2.45.0",
      "2.44.0",
      "2.43.0",
      "2.42.0.2",
      "2.42.0",
      "2.41.0.3",
      "2.41.0.2",
      "2.41.0",
      "2.40.1",
      "2.40.0",
      "2.39.2",
      "2.39.1",
      "2.39.0.2",
      "2.39.0",
      "2.38.1",
      "2.38.0",
      "2.37.3",
      "2.37.2.2",
      "2.37.1",
      "2.37.0",
      "2.36.1",
      "2.36.0",
      "2.35.3",
      "2.35.2",
      "2.35.1.2",
      "2.35.1",
      "2.35.0",
      "2.34.1",
      "2.34.0",
      "2.33.1",
      "2.33.0.2",
      "2.33.0",
      "2.32.0.2",
      "2.32.0",
      "2.31.1",
      "2.31.0",
      "2.30.2",
      "2.30.1",
      "2.30.0.2",
      "2.29.2.3",
      "2.29.2.2",
      "2.29.0",
      "2.28.0",
      "2.27.0",
      "2.26.2",
      "2.25.1",
      "2.24.1.2"
    ]
  },
. . .
```

**Comment by denelon** [comment]
We've released the [Microsoft.WinGet.Client](https://www.powershellgallery.com/packages/Microsoft.WinGet.Client) PowerShell module to address customers wanting JSON output.
