### ISSUE TITLE
Hard to install more than one package.

### ISSUE THREAD

**Issue by huangsijun17** [microsoft/winget-cli#497]
`winget install Microsoft.VC++2017Redist-x86 Microsoft.VC++2017Redist-x64`

在未预期的情况下找到位置参数 : 'Microsoft.VC++2017Redist-x64'

I can't install more than one package by listing all the packages I want to install.

**Comment by dardrai** [comment]
I support that feature request - problem atm is that you'll have to run 
winget install Microsoft.VC++2017Redist-x86
Wait Until install is finished and only then you can start the next installer (terminal is blocked in the install process)
winget install Microsoft.VC++2017Redist-x64

a function like linux/unix would be nice: "apt-get install bind9 postfix"

**Comment by denelon** [comment]
Duplicate of #156
