### ISSUE TITLE
Winget does not see the application in the ms store repository

### ISSUE THREAD

**Issue by NoNameAvailableUsers** [microsoft/winget-cli#4977]
### Brief description of your issue

I can't find the new version of the "messenger" app in list of winget
https://apps.microsoft.com/detail/9wzdncrf0083

CMD
winget search Messenger
# "NO MESSENGER APP"

#Low priority

### Steps to reproduce

"winget search Messenger"   dont show Messenger app in list
 "winget search 9WZDNCRFJ2WL" show Messenger app

"winget search Messenger"   Does the search method have a limit?
What am I doing wrong?

### Expected behavior

Verification of search operation methods to find any apps.

"winget search Messenger"  <--> "winget search 9WZDNCRFJ2WL" 

---
winget search -q Messenger -s msstore
Name                       Id             Version
-------------------------------------------------
**Messenger               9WZDNCRF0083 Unknown** 
One Messenger              9NBLGGH5PBWT   Unknown
Chipper Messenger          XPFFTX5NCMM73C Unknown
Grape Messenger            9P28KPMR8L2Z   Unknown
Zenith Messenger           9N738K5MLZCP   Unknown
Softros LAN Messenger      XPFFZBJC8C4HJK Unknown
ChatS Encrypted Messenger  9WZDNCRDCMQH   Unknown
OfficeChat Messenger       9P5G8NMJ365L   Unknown
MangoApps Messenger        9NZ8CCCJ798N   Unknown
Sikur Messenger            9N6J4MJPGTZB   Unknown
twinme - Private Messenger 9MX5M684NHG4   Unknown
Gap Messenger              9PJL9FTF9NXD   Unknown
Arattai Messenger          9NFSL94JN89M   Unknown
TamTam Messenger           9PK1T23XZ106   Unknown
AnyTalk Messenger          9NCVBFXV0DJH   Unknown
Officetree Messenger       9PKCW303TNGC   Unknown
Skred Messenger Desktop    9N7NVZMW8GQB   Unknown
New Sikur Messenger        9NNWGJ83C101   Unknown

### Actual behavior

winget search Messenger
Name                             Id                                   Version                              Match          Source
---------------------------------------------------------------------------------------------------------------------------------
One Messenger                    9NBLGGH5PBWT                         Unknown                                             msstore
Chipper Messenger                XPFFTX5NCMM73C                       Unknown                                             msstore
Grape Messenger                  9P28KPMR8L2Z                         Unknown                                             msstore
Zenith Messenger                 9N738K5MLZCP                         Unknown                                             msstore
Softros LAN Messenger            XPFFZBJC8C4HJK                       Unknown                                             msstore
ChatS Encrypted Messenger        9WZDNCRDCMQH                         Unknown                                             msstore
OfficeChat Messenger             9P5G8NMJ365L                         Unknown                                             msstore
MangoApps Messenger              9NZ8CCCJ798N                         Unknown                                             msstore
Sikur Messenger                  9N6J4MJPGTZB                         Unknown                                             msstore
twinme - Private Messenger       9MX5M684NHG4                         Unknown                                             msstore
Gap Messenger                    9PJL9FTF9NXD                         Unknown                                             msstore
Arattai Messenger                9NFSL94JN89M                         Unknown                                             msstore
TamTam Messenger                 9PK1T23XZ106                         Unknown                                             msstore
AnyTalk Messenger                9NCVBFXV0DJH                         Unknown                                             msstore
Officetree Messenger             9PKCW303TNGC                         Unknown                                             msstore
Skred Messenger Desktop          9N7NVZMW8GQB                         Unknown                                             msstore
New Sikur Messenger              9NNWGJ83C101                         Unknown                                             msstore
ADAMANT Messenger                Adamant.Messenger                    4.6.2                                Tag: messenger winget
BeeBEEP                          BeeBEEP.BeeBEEP                      5.8.6                                Tag: messenger winget
Beeper                           Beeper.Beeper                        3.110.1                              Tag: messenger winget
Caprine                          Caprine.Caprine                      2.60.1                               Tag: messenger winget
Trillian                         CeruleanStudios.Trillian             6.5.0.45                             Tag: messenger winget
KakaoTalk                        Kakao.KakaoTalk                      4.2.5.4185                           Tag: messenger winget
Kakao Work                       KakaoEnterprise.KakaoWork            2.17.1.4960                          Tag: messenger winget
Kotatogram Desktop               Kotatogram.Kotatogram                1.4.8                                Tag: messenger winget
Dooray! Messenger                NHNCorporation.Dooray!Messenger      11.00.19041.1 (WinBuild.160101.0800) Tag: messenger winget
Nheko                            NhekoReborn.Nheko                    0.11.3                               Tag: messenger winget
Session                          Oxen.Session                         1.12.2                               Tag: messenger winget
Pidgin                           Pidgin.Pidgin                        2.14.13                              Tag: messenger winget
Rambox                           Rambox.Rambox.Community              0.8.0                                Tag: messenger winget
네이트온                         SKCommunications.NateOn              7.0.25.1                             Tag: messenger winget
Status-Desktop                   Status.Status                        2.28.0                               Tag: messenger winget
Telegram Desktop                 Telegram.TelegramDesktop             5.7.2                                Tag: messenger winget
Telegram Desktop Beta            Telegram.TelegramDesktop.Beta        4.6.4                                Tag: messenger winget
zg-ipchat Peer-to-peer chat tool Zheguisoft.zg-ipchat                 1.00.05                              Tag: messenger winget
DeltaChat                        deltachat.deltachat                  201.42.2                             Tag: messenger winget
Daou Messenger                   DaouTech.DaouMessenger               3.5.42                                              winget
Hiworks Messenger                Gabia.HiworksMessenger               3                                                   winget
U+Works Messenger                LGUplus.UplusWorksMessenger          1.0.34                                              winget
MAILPLUG Messenger Desktop       MAILPLUGInc.MAILPLUGMessengerDesktop 1.4.2                                               winget
Brity Messenger                  SamsungSDS.BrityMessenger            2.1.41.48                                           winget
Tigris Messenger                 TigerCompany.TigrisMessenger         1.1.7                                               winget
VK Messenger                     VKontakte.VKMessenger                5.3.2                                               winget
Yandex Messenger                 Yandex.Messenger                     2.222.0                                             winget
IP Messenger for Win             FastCopy.IPMsg                       5.6.2                                               winget
Dooray! Messenger                NHNCorporation.Dooray!Drive          1.0.3                                               winget

C:\Windows\System32>winget search -q 9WZDNCRF0083
Name      Id           Version Source
---------------------------------------
Messenger 9WZDNCRF0083 Unknown msstore

C:\Windows\System32>winget search -q Messenger -s msstore
Name                       Id             Version
-------------------------------------------------
One Messenger              9NBLGGH5PBWT   Unknown
Chipper Messenger          XPFFTX5NCMM73C Unknown
Grape Messenger            9P28KPMR8L2Z   Unknown
Zenith Messenger           9N738K5MLZCP   Unknown
Softros LAN Messenger      XPFFZBJC8C4HJK Unknown
ChatS Encrypted Messenger  9WZDNCRDCMQH   Unknown
OfficeChat Messenger       9P5G8NMJ365L   Unknown
MangoApps Messenger        9NZ8CCCJ798N   Unknown
Sikur Messenger            9N6J4MJPGTZB   Unknown
twinme - Private Messenger 9MX5M684NHG4   Unknown
Gap Messenger              9PJL9FTF9NXD   Unknown
Arattai Messenger          9NFSL94JN89M   Unknown
TamTam Messenger           9PK1T23XZ106   Unknown
AnyTalk Messenger          9NCVBFXV0DJH   Unknown
Officetree Messenger       9PKCW303TNGC   Unknown
Skred Messenger Desktop    9N7NVZMW8GQB   Unknown
New Sikur Messenger        9NNWGJ83C101   Unknown

(WITHOUT -> Messenger 9WZDNCRF0083 Unknown msstore)

### Environment

```shell
CMD (user with admin privileges) / (admin mode)
winget -v --info
Windows Package Manager v1.9.25200
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.4460
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.25200.0

...

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled /(BypassCertificatePinningForMicrosoftStore Enable -> same result)
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**Comment by denelon** [comment]
It looks like the top result for me:

![Image](https://github.com/user-attachments/assets/18aa4605-e92f-4992-881c-d4bde511b476)
