### ISSUE TITLE
Microsoft Store Destroy Microsoft.DesktopAppInstaller

### ISSUE THREAD

**Issue by Ramshu** [microsoft/winget-cli#4979]
### Brief description of your issue

We come from here: https://github.com/microsoft/winget-cli/issues/4794#issue-2508271379

It seemed that the problems had already been solved, but new ones have arrived...
Windows Store has been updating the same 4 looping apps, every 2-3 days, for several weeks now, including the Desktop Installer. At some point this has burst and the desktop installer application has become unusable and with it winget as well.

I have put all the knowledge learned during the solution of the previous problem plus some new ones that I have acquired, but I cannot solve it. I think the problem may have something to do with temporary files, but I can't find out more.

![Image](https://github.com/user-attachments/assets/3e42ac6d-85af-4789-aef9-02af9e6e8a8e)
![Image](https://github.com/user-attachments/assets/9c051b12-565b-43c0-8502-b1e5d270c954)
![Image](https://github.com/user-attachments/assets/b5d10208-4fd9-46a1-be8d-733e4f236983)
![Image](https://github.com/user-attachments/assets/1638700f-a6dd-4576-b57e-e656ec179c84)
![Image](https://github.com/user-attachments/assets/7f577988-a8d4-4ba0-8a25-ebf882b78216)

### Steps to reproduce

Anything that has to do with the package installer fails

### Expected behavior

Normal functions

### Actual behavior

Fail

### Environment

```shell
Winget info: No Info
Windows 10 x64 22h2
DesktopAppInstaller 1.24.25200.0
```

**Comment by mariusmg** [comment]
I have the same problem (can't update from MS Store and any winget operation fails ) : 


![Image](https://github.com/user-attachments/assets/3c449a3a-be30-47b2-8f2b-4d87e486a725)


![Image](https://github.com/user-attachments/assets/6a938057-6804-4fdf-b00e-cbc5a95931f3)


Windows version details : 

Edition	Windows 10 Pro
Version	22H2
Installed on	‎3/‎3/‎2022
OS build	19045.5131
Experience	Windows Feature Experience Pack 1000.19060.1000.0

**Comment by denelon** [comment]
Could you try using the Repair-WinGetPackageManager cmdlet from the Microsoft.WinGet.Client PowerShell module?

1. `Import-Module Microsoft.WinGet.Client`
2. `Repair-WinGetPackageManager -Force -Latest`

**Comment by mariusmg** [comment]
For me it didn't worked, it fails with an error message about......license ?!

![Image](https://github.com/user-attachments/assets/7de21a96-63a7-499a-89f8-dc20d1d45ebe)

**Comment by Ramshu** [comment]
> Could you try using the Repair-WinGetPackageManager cmdlet from the Microsoft.WinGet.Client PowerShell module?
> 
> 1. `Import-Module Microsoft.WinGet.Client`
> 2. `Repair-WinGetPackageManager -Force -Latest`

I've tried it before...
"Add-AppxProvisionedPackage: Error in the remote procedure call."

![Image](https://github.com/user-attachments/assets/4724aa54-e520-4c93-b0ef-6f0f6a90d577)
![Image](https://github.com/user-attachments/assets/c9cab8db-401e-4f7c-8a23-2a9fafd4f7cf)

**Comment by ronhowe** [comment]
I am in this same boat with the same errors after the November 2024 Patch Tuesday.

Will watch for wisdom and/or answers.

**Comment by brempusz** [comment]
same here
```
PS C:\WINDOWS\system32> winget
Program 'winget.exe' failed to run: The file cannot be accessed by the systemAt line:1 char:1
+ winget
+ ~~~~~~.
At line:1 char:1
+ winget
+ ~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

repair fails:
```
PS C:\WINDOWS\system32> Repair-WinGetPackageManager -Force -Latest -AllUsers -Verbose
VERBOSE: Creating MTA thread
VERBOSE: Running winget.exe with --version
VERBOSE: 'winget.exe' Win32Exception The file cannot be accessed by the system
VERBOSE: Program 'winget.exe' failed to run: The file cannot be accessed by the system.
VERBOSE: Integrity category type: AppInstallerNoLicense
VERBOSE: Downloading https://github.com/microsoft/winget-cli/releases/download/v1.9.25200/DesktopAppInstaller_Dependencies.json
VERBOSE: Size 264 bytes
VERBOSE: Executing Appx cmdlet Get-AppxPackage -Name Microsoft.VCLibs.140.00.UWPDesktop
VERBOSE: Microsoft.VCLibs.140.00.UWPDesktop is lower than minimum required version [14.0.33728.0]: Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe
VERBOSE: Executing Appx cmdlet Get-AppxPackage -Name Microsoft.UI.Xaml.2.8
VERBOSE: Microsoft.VCLibs.140.00.UWPDesktop is lower than minimum required version [14.0.33728.0]: Microsoft.VCLibs.140.00.UWPDesktop_14.0.30704.0_x64__8wekyb3d8bbwe
VERBOSE: Microsoft.VCLibs.140.00.UWPDesktop is lower than minimum required version [14.0.33728.0]: Microsoft.VCLibs.140.00.UWPDesktop_14.0.32530.0_x64__8wekyb3d8bbwe
VERBOSE: Microsoft.VCLibs.140.00.UWPDesktop is lower than minimum required version [14.0.33728.0]: Microsoft.VCLibs.140.00.UWPDesktop_14.0.33321.0_x64__8wekyb3d8bbwe
VERBOSE: Microsoft.VCLibs.140.00.UWPDesktop is lower than minimum required version [14.0.33728.0]: Microsoft.VCLibs.140.00.UWPDesktop_14.0.33519.0_x64__8wekyb3d8bbwe
VERBOSE: Microsoft.VCLibs.140.00.UWPDesktop x64 dependency satisfied by: Microsoft.VCLibs.140.00.UWPDesktop_14.0.33728.0_x64__8wekyb3d8bbwe
VERBOSE: Microsoft.UI.Xaml.2.8 x64 dependency satisfied by: Microsoft.UI.Xaml.2.8_8.2310.30001.0_x64__8wekyb3d8bbwe
VERBOSE: Downloading https://github.com/microsoft/winget-cli/releases/download/v1.9.25200/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
VERBOSE: Size 236859576 bytes
VERBOSE: Downloading https://github.com/microsoft/winget-cli/releases/download/v1.9.25200/7fdfd40ea2dc40deab85b69983e1d873_License1.xml
VERBOSE: Size 2688 bytes
VERBOSE: Failed installing bundle via Add-AppxProvisionedPackage System.Management.Automation.CmdletInvocationException: The remote procedure call failed.
 ---> System.Runtime.InteropServices.COMException: The remote procedure call failed.

   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.WinGet.Client.Engine.Helpers.AppxModuleHelper.<>c__DisplayClass51_0.<AddProvisionPackageAsync>b__0()
   at Microsoft.WinGet.Common.Command.PowerShellCmdlet.Wait(Task runningTask, PowerShellCmdlet writeCmdlet)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.WinGet.Common.Command.PowerShellCmdlet.WaitMainThreadActionCompletion()
   at Microsoft.WinGet.Common.Command.PowerShellCmdlet.ExecuteInPowerShellThread(Action action)
   at Microsoft.WinGet.Client.Engine.Helpers.AppxModuleHelper.<AddProvisionPackageAsync>d__51.MoveNext()
Add-AppxProvisionedPackage : The remote procedure call failed.
At line:1 char:1
+ Repair-WinGetPackageManager -Force -Latest -AllUsers -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AppxProvisionedPackage], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddAppxProvisionedPackageCommand

```

**Comment by mariusmg** [comment]
I'm adding the full output from my Repair-WinGetPackageManager , interesting is different from @brempusz  output : 


Repair-WinGetPackageManager -Force -Latest -Verbose -AllUsers
```
VERBOSE: Creating MTA thread
VERBOSE: Running winget.exe with --version
VERBOSE: 'winget.exe' Win32Exception An error occurred trying to start process 'winget.exe' with working directory 'c:\shared\utilities\ahk'. The file cannot be accessed by the system.
VERBOSE: Program 'winget.exe' failed to run: StandardOutputEncoding is only supported when standard output is redirected..
VERBOSE: Integrity category type: AppInstallerNoLicense
VERBOSE: Downloading https://github.com/microsoft/winget-cli/releases/download/v1.9.25200/DesktopAppInstaller_Dependencies.json
VERBOSE: Size 264 bytes
VERBOSE: Executing Appx cmdlet Get-AppxPackage -Name Microsoft.VCLibs.140.00.UWPDesktop
VERBOSE: Microsoft.VCLibs.140.00.UWPDesktop is lower than minimum required version [14.0.33728.0]: Microsoft.VCLibs.140.00.UWPDesktop_14.0.33519.0_x64__8wekyb3d8bbwe
VERBOSE: Microsoft.VCLibs.140.00.UWPDesktop x64 dependency satisfied by: Microsoft.VCLibs.140.00.UWPDesktop_14.0.33728.0_x64__8wekyb3d8bbwe
VERBOSE: Executing Appx cmdlet Get-AppxPackage -Name Microsoft.UI.Xaml.2.8
VERBOSE: Microsoft.UI.Xaml.2.8 is lower than minimum required version [8.2310.30001.0]: Microsoft.UI.Xaml.2.8_8.2306.22001.0_x64__8wekyb3d8bbwe
VERBOSE: Microsoft.UI.Xaml.2.8 x64 dependency satisfied by: Microsoft.UI.Xaml.2.8_8.2310.30001.0_x64__8wekyb3d8bbwe
VERBOSE: Downloading https://github.com/microsoft/winget-cli/releases/download/v1.9.25200/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
VERBOSE: Size 236859576 bytes
VERBOSE: Downloading https://github.com/microsoft/winget-cli/releases/download/v1.9.25200/7fdfd40ea2dc40deab85b69983e1d873_License1.xml
VERBOSE: Size 2688 bytes
VERBOSE: Running winget.exe with --version
VERBOSE: 'winget.exe' Win32Exception An error occurred trying to start process 'winget.exe' with working directory 'c:\shared\utilities\ahk'. The file cannot be accessed by the system.
VERBOSE: Program 'winget.exe' failed to run: StandardOutputEncoding is only supported when standard output is redirected..
VERBOSE: AppInstallerNoLicense encountered previously
Repair-WinGetPackageManager: No applicable license found.
```

**Comment by Ramshu** [comment]
In my case it has been solved.
This morning, when booting the PC has taken much longer than normal, looking at the task manager I could see that Windows telemetry compatibility was very busy.

After starting the Windows Store, "app installer" and WindowsAppRuntime.Singleton have been updated, after that, everything worked normally.
Then it has updated the 4 usual applications, but it is strange because in the history it only shows WindowsAppRuntime.Singleton

I leave the thread open in case any of those who had the same problem want to update the information.

![Image](https://github.com/user-attachments/assets/7c7281d1-6042-4685-90bc-0cfa81645a50)
![Image](https://github.com/user-attachments/assets/ce291be2-5450-4108-9869-0b5bce2b6976)

**Comment by ronhowe** [comment]
This fixed itself for me this morning.

After Microsoft Store updated WinAppRuntime.Singleton, it was able to update other applications.

**Comment by brempusz** [comment]
> This fixed itself for me this morning.
Same here.

**Comment by LeoPR** [comment]
My Micrtosoft.DesktopAppInstaller are broken... now im in a loop.
I cant install DesktopAppInstaller with Appx

```powershell
PS C:\Windows\system32> whereis winget
whereis : The term 'whereis' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that 
the path is correct and try again.
At line:1 char:1
+ whereis winget
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (whereis:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

PS C:\Windows\system32> where winget

PS C:\Windows\system32> Get-AppPackage Microsoft.DesktopAppInstaller

PS C:\Windows\system32> Import-Module Microsoft.WinGet
Import-Module : The specified module 'Microsoft.WinGet' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module Microsoft.WinGet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Microsoft.WinGet:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

Add-AppxPackage -Path "C:\Users\Admin\Downloads\Microsoft.DesktopAppInstaller_2024.1108.1842.0_neutral_~_8wekyb3d8bbwe.Msixbundle" -ForceApplicationShutdown

Get-AppPackageLog -ActivityID 035f3451-3ac7-0021-e25e-5f03c73adb01

PS C:\Users\Admin\Downloads> Get-AppPackageLog -ActivityID 035f3451-3ac7-0021-e25e-5f03c73adb01
.....
19/11/2024 18:44:25       802          Deletion of registry key: Software\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\S-1-5-21-1250557391-2919243731-1904298097-1004\Microsoft.DesktopAppInstaller_2024.1108.2107.0_neutral_~_8wekyb3d8bbwe failed with error: 0x0.
19/11/2024 18:44:25       802          Deletion of registry key: Software\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\S-1-5-21-1250557391-2919243731-1904298097-1005\Microsoft.DesktopAppInstaller_2024.1108.2107.0_neutral_~_8wekyb3d8bbwe failed with error: 0x0.
19/11/2024 18:44:25       325          error 0x8007139F: While preparing to process the request, the system failed to register the windows.applicationData.undocked extension due to the following error: The group or resource is not in the correct state to perform the
                                       requested operation.
                                       .
19/11/2024 18:44:25       8761         AppExecutionAlias directory missing, error code is 0x8007010B.
19/11/2024 18:44:25       8761         AppExecutionAlias directory missing, error code is 0x8007010B.
19/11/2024 18:44:25       8761         AppExecutionAlias directory missing, error code is 0x8007010B.
19/11/2024 18:44:25       8761         AppExecutionAlias directory missing, error code is 0x8007010B.
19/11/2024 18:44:25       6803         error 0x8007139F: The following error occured while preparing the windows.appExecutionAlias extension in the Microsoft.DesktopAppInstaller_1.24.25180.0_x64__8wekyb3d8bbwe package for update or removal: The group or resource is not
                                       in the correct state to perform the requested operation.
                                       .
19/11/2024 18:44:25       605          The last successful state reached was MachineRegisterRemove. Failure occurred before reaching the next state De-Indexed. hr: 0x8007139F
19/11/2024 18:44:25       751          Windows failed to undo changes with error code 0x8007139F to package Microsoft.DesktopAppInstaller_1.24.25200.0_neutral_split.scale-100_8wekyb3d8bbwe. The package needs to be reinstalled.
19/11/2024 18:44:25       300          error 0x8007139F: Cannot register the Microsoft.DesktopAppInstaller_8wekyb3d8bbwe package due to the following error: The group or resource is not in the correct state to perform the requested operation.
                                       .
19/11/2024 18:44:25       472          Moving package folder \\?\C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_2024.1108.2107.0_neutral_~_8wekyb3d8bbwe to \\?\C:\Program
                                       Files\WindowsApps\Deleted\Microsoft.DesktopAppInstaller_2024.1108.2107.0_neutral_~_8wekyb3d8bbwebd4caa04-c34f-489c-ac90-bbc697b3a1f9. Result: 0x0.
19/11/2024 18:44:25       472          Moving package folder \\?\C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.25.40.0_x64__8wekyb3d8bbwe to \\?\C:\Program
                                       Files\WindowsApps\Deleted\Microsoft.DesktopAppInstaller_1.25.40.0_x64__8wekyb3d8bbweb0efb80c-0729-43a0-8c97-6a32bef4a144. Result: 0x0.
19/11/2024 18:44:25       472          Moving package folder \\?\C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.25.40.0_neutral_split.language-ru_8wekyb3d8bbwe to \\?\C:\Program
                                       Files\WindowsApps\Deleted\Microsoft.DesktopAppInstaller_1.25.40.0_neutral_split.language-ru_8wekyb3d8bbwe82ea8171-caa7-47c6-8a6b-7bd92ce94249. Result: 0x0.
19/11/2024 18:44:25       472          Moving package folder \\?\C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.25.40.0_neutral_split.scale-100_8wekyb3d8bbwe to \\?\C:\Program
                                       Files\WindowsApps\Deleted\Microsoft.DesktopAppInstaller_1.25.40.0_neutral_split.scale-100_8wekyb3d8bbwedc9e1197-5371-4fe5-94ce-57ec3d749f7e. Result: 0x0.
19/11/2024 18:44:25       472          Moving package folder \\?\C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.25.40.0_neutral_split.language-pt_8wekyb3d8bbwe to \\?\C:\Program
                                       Files\WindowsApps\Deleted\Microsoft.DesktopAppInstaller_1.25.40.0_neutral_split.language-pt_8wekyb3d8bbwe0fea33b5-82ff-487f-8638-f6d6853e7f3a. Result: 0x0.
19/11/2024 18:44:25       10001        Finished servicing package Microsoft.DesktopAppInstaller_1.25.40.0_x64__8wekyb3d8bbwe. Setting the package state to enabled returned with 0x8007139F.
19/11/2024 18:44:25       10001        Finished servicing package Microsoft.DesktopAppInstaller_1.24.25200.0_x64__8wekyb3d8bbwe. Setting the package state to enabled returned with 0x8007139F.



```

**Comment by Ramshu** [comment]
> My Micrtosoft.DesktopAppInstaller are broken... now im in a loop. I cant install DesktopAppInstaller with Appx
> 
> PS C:\Windows\system32> whereis winget
> whereis : The term 'whereis' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that 
> the path is correct and try again.
> At line:1 char:1
> + whereis winget
> + ~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (whereis:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>  
> 
> PS C:\Windows\system32> where winget
> 
> PS C:\Windows\system32> Get-AppPackage Microsoft.DesktopAppInstaller
> 
> PS C:\Windows\system32> Import-Module Microsoft.WinGet
> Import-Module : The specified module 'Microsoft.WinGet' was not loaded because no valid module file was found in any module directory.
> At line:1 char:1
> + Import-Module Microsoft.WinGet
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ResourceUnavailable: (Microsoft.WinGet:String) [Import-Module], FileNotFoundException
>     + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
> 
> Add-AppxPackage -Path "C:\Users\Admin\Downloads\Microsoft.DesktopAppInstaller_2024.1108.1842.0_neutral_~_8wekyb3d8bbwe.Msixbundle" -ForceApplicationShutdown
> 
> Get-AppPackageLog -ActivityID 035f3451-3ac7-0021-e25e-5f03c73adb01
> 
> PS C:\Users\Admin\Downloads> Get-AppPackageLog -ActivityID 035f3451-3ac7-0021-e25e-5f03c73adb01
> .....
> 19/11/2024 18:44:25       802          Deletion of registry key: Software\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\S-1-5-21-1250557391-2919243731-1904298097-1004\Microsoft.DesktopAppInstaller_2024.1108.2107.0_neutral_~_8wekyb3d8bbwe failed with error: 0x0.
> 19/11/2024 18:44:25       802          Deletion of registry key: Software\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\S-1-5-21-1250557391-2919243731-1904298097-1005\Microsoft.DesktopAppInstaller_2024.1108.2107.0_neutral_~_8wekyb3d8bbwe failed with error: 0x0.
> 19/11/2024 18:44:25       325          error 0x8007139F: While preparing to process the request, the system failed to register the windows.applicationData.undocked extension due to the following error: The group or resource is not in the correct state to perform the
>                                        requested operation.
>                                        .
> 19/11/2024 18:44:25       8761         AppExecutionAlias directory missing, error code is 0x8007010B.
> 19/11/2024 18:44:25       8761         AppExecutionAlias directory missing, error code is 0x8007010B.
> 19/11/2024 18:44:25       8761         AppExecutionAlias directory missing, error code is 0x8007010B.
> 19/11/2024 18:44:25       8761         AppExecutionAlias directory missing, error code is 0x8007010B.
> 19/11/2024 18:44:25       6803         error 0x8007139F: The following error occured while preparing the windows.appExecutionAlias extension in the Microsoft.DesktopAppInstaller_1.24.25180.0_x64__8wekyb3d8bbwe package for update or removal: The group or resource is not
>                                        in the correct state to perform the requested operation.
>                                        .
> 19/11/2024 18:44:25       605          The last successful state reached was MachineRegisterRemove. Failure occurred before reaching the next state De-Indexed. hr: 0x8007139F
> 19/11/2024 18:44:25       751          Windows failed to undo changes with error code 0x8007139F to package Microsoft.DesktopAppInstaller_1.24.25200.0_neutral_split.scale-100_8wekyb3d8bbwe. The package needs to be reinstalled.
> 19/11/2024 18:44:25       300          error 0x8007139F: Cannot register the Microsoft.DesktopAppInstaller_8wekyb3d8bbwe package due to the following error: The group or resource is not in the correct state to perform the requested operation.
>                                        .
> 19/11/2024 18:44:25       472          Moving package folder \\?\C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_2024.1108.2107.0_neutral_~_8wekyb3d8bbwe to \\?\C:\Program
>                                        Files\WindowsApps\Deleted\Microsoft.DesktopAppInstaller_2024.1108.2107.0_neutral_~_8wekyb3d8bbwebd4caa04-c34f-489c-ac90-bbc697b3a1f9. Result: 0x0.
> 19/11/2024 18:44:25       472          Moving package folder \\?\C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.25.40.0_x64__8wekyb3d8bbwe to \\?\C:\Program
>                                        Files\WindowsApps\Deleted\Microsoft.DesktopAppInstaller_1.25.40.0_x64__8wekyb3d8bbweb0efb80c-0729-43a0-8c97-6a32bef4a144. Result: 0x0.
> 19/11/2024 18:44:25       472          Moving package folder \\?\C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.25.40.0_neutral_split.language-ru_8wekyb3d8bbwe to \\?\C:\Program
>                                        Files\WindowsApps\Deleted\Microsoft.DesktopAppInstaller_1.25.40.0_neutral_split.language-ru_8wekyb3d8bbwe82ea8171-caa7-47c6-8a6b-7bd92ce94249. Result: 0x0.
> 19/11/2024 18:44:25       472          Moving package folder \\?\C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.25.40.0_neutral_split.scale-100_8wekyb3d8bbwe to \\?\C:\Program
>                                        Files\WindowsApps\Deleted\Microsoft.DesktopAppInstaller_1.25.40.0_neutral_split.scale-100_8wekyb3d8bbwedc9e1197-5371-4fe5-94ce-57ec3d749f7e. Result: 0x0.
> 19/11/2024 18:44:25       472          Moving package folder \\?\C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.25.40.0_neutral_split.language-pt_8wekyb3d8bbwe to \\?\C:\Program
>                                        Files\WindowsApps\Deleted\Microsoft.DesktopAppInstaller_1.25.40.0_neutral_split.language-pt_8wekyb3d8bbwe0fea33b5-82ff-487f-8638-f6d6853e7f3a. Result: 0x0.
> 19/11/2024 18:44:25       10001        Finished servicing package Microsoft.DesktopAppInstaller_1.25.40.0_x64__8wekyb3d8bbwe. Setting the package state to enabled returned with 0x8007139F.
> 19/11/2024 18:44:25       10001        Finished servicing package Microsoft.DesktopAppInstaller_1.24.25200.0_x64__8wekyb3d8bbwe. Setting the package state to enabled returned with 0x8007139F.

Have you tried restarting your computer and updating everything from the Windows store

**Comment by mariusmg** [comment]
For me is also fixed now after "WinAppRuntime.Singleton" was successfully updated in MS Store.

**Comment by mdanish-kh** [comment]
Does this [recommendation](https://github.com/microsoft/WindowsAppSDK/issues/4881#issuecomment-2489961411) (from winapp sdk repo) unblock your issue?

[comment]: <[Policy] Needs-Author-Feedback>

**Comment by kumaresan-cgvak** [comment]
Microsoft released a patch OS update for Windows 10 with the fix for the install / uninstall issue.

[Users might be unable to update or uninstall packaged apps on Windows 10](https://learn.microsoft.com/en-us/windows/release-health/resolved-issues-windows-10-22h2#3447msgdesc)

Updating the OS to the Below optional update will allow the user to uninstall in case if the corrupted version of the app is there. in certain cases, it automatically removes the corrupted app. allowing us to do a fresh install of the app again.

![Image](https://github.com/user-attachments/assets/cfe95495-4c27-472a-8151-eeca651fcea6)
