### ISSUE TITLE
On-Premise winget

### ISSUE THREAD

**Issue by secana** [microsoft/winget-cli#498]
# Description of the new feature/enhancement

Idea for the (far?) future: An easy to install and use on-premise winget that companies can install in their networks for internal tools or preview versions.

Why: At the moment internal binaries are distributed based on the language they are written in e.g. "dotnet tool" or "cargo install". This is very inconvenient as you need to install the tooling for every possible used language. 
Instead I would like to push all binary artifacts to a internal winget instance and allow everyone to install the tools with ease. 

# Proposed technical implementation details (optional)

Provide a Docker container image or RPM/Deb package to set-up a local winget and the possibility in the winget-cli to add an additional source for packages.

**Comment by denelon** [comment]
@secana this is planned. There will likely be a few parts. The first prerequisite is the REST API #118 work. Once the client can work with a RESTful source, you should be able to stand one up. We are also considering building an Azure Marketplace offering that would make it trivial to stand one up on Azure. I'll also keep this in the backlog for the specific Docker request.

**Comment by WSLUser** [comment]
This needs to be expanded to more than just Azure. You have to support other cloud vendors for one and you also need to accept that some companies and gov agencies will want actual on-prem private repository stored locally on a server (even if that server is technically in the cloud or a VM using Xen for example).

**Comment by denelon** [comment]
@WSLUser the REST API could run on any HTTP server. My Azure Marketplace comment was just related to building a reference implementation. It could be implemented in a Docker container, on any other cloud provider, or even hosted on a machine inside of an enterprise.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli-restsource

**Comment by denelon** [comment]
@secana This specific implementation runs on Azure. It's possible to use https://azure.microsoft.com/en-us/services/azure-arc/ on premesis.

**Comment by WSLUser** [comment]
So Azure is the only accepted solution? I disagree.  That is a workaround. It should work with any cloud vendor and independent of any cloud provider.

**Comment by denelon** [comment]
No, Azure is not the only accepted solution. Azure is one possible solution. Many other cloud providers have the ability to host a REST API. We've just provided a reference implementation that runs on Azure. Feel free to take a look at the Swagger specification and build a private source on any technology stack you choose 😊. Feel free to host it on any infrastructure you chose 😊.
