### ISSUE TITLE
add `--list` option to `winget list`

### ISSUE THREAD

**Issue by GuoJikun** [microsoft/winget-cli#5051]
### Description of the new feature / enhancement

Mainly in order to facilitate the call of the tripartite program.

**Comment by Trenly** [comment]
I’m not sure I understand exatly what you want this new option to do. What would it do differently than the current behavior? Is there a reason the WinGet PowerShell module won’t work?

Please add some more detail to your request

**Comment by GuoJikun** [comment]
This is my usage scenario.
```rs
pub fn installed_list() -> Result<String, String> {
    let output = std::process::Command::new("winget")
        .args(&["list"])
        .output()
        .map_err(|e| format!("Failed to run winget: {}", e))?;
    
    let installed_software = String::from_utf8_lossy(&output.stdout).to_string();
    if installed_software.is_empty() {
        return Err("没有找到已安装的软件。".to_string());
    }

    Ok(installed_software)
}
```
The output of the 'winget list' command is a string that is difficult to parse.

**Comment by Trenly** [comment]
> This is my usage scenario.
> 
> pub fn installed_list() -> Result<String, String> {
>     let output = std::process::Command::new("winget")
>         .args(&["list"])
>         .output()
>         .map_err(|e| format!("Failed to run winget: {}", e))?;
>     
>     let installed_software = String::from_utf8_lossy(&output.stdout).to_string();
>     if installed_software.is_empty() {
>         return Err("没有找到已安装的软件。".to_string());
>     }
> 
>     Ok(installed_software)
> }
> The output of the 'winget list' command is a string that is difficult to parse.

Instead of using rhe WinGet binary, any application interfaces to WinGet are recommended to use the PowerShell module (Microsoft.WinGet.Client), which returns the information as PowerShell objecfs that can be interfaced with directy or converted to JSON;  or the COM API

**Comment by GuoJikun** [comment]
> Instead of using rhe WinGet binary, any application interfaces to WinGet are recommended to use the PowerShell module (Microsoft.WinGet.Client), which returns the information as PowerShell objecfs that can be interfaced with directy or converted to JSON; or the COM API

Thank you for your answer.
