### ISSUE TITLE
Locale not respected in `winget display`

### ISSUE THREAD

**Issue by Gijsreyn** [microsoft/winget-cli#5065]
### Brief description of your issue

Maybe this is expected behavior; perhaps it is not. When specifying locale in the settings file as such:

```json
{
    "$schema": "https://aka.ms/winget-settings.schema.json",
    "installBehavior": {
        "preferences": {
            "locale": ["zh-CN"]
        }
    }
}
```

I'm expecting the description for the package `k3d.k3d` to be returned properly for the language because it has a `zh-CN`, even thought we _prefer_ it.

### Steps to reproduce

Configure the settings in the `settings.json` file as such:

```json
{
    "$schema": "https://aka.ms/winget-settings.schema.json",
    "installBehavior": {
        "preferences": {
            "locale": ["zh-CN"]
        }
    }
}
```

Use `winget install k3d.k3d

### Expected behavior

Expected the following description to be returned when calling `winget show k3d.k3d`:

```plaintext
  k3d 是用于在 docker 中运行 k3s（Rancher Lab 的最小 Kubernetes 发行版）的轻量级封装。
  k3d 可以让你在 docker 中轻松创建单节点或多节点的 k3s 集群，例如在 Kubernetes 上进行本地开发。
```

### Actual behavior

Actually returns:

```plaintext
k3d is a lightweight wrapper to run k3s (Rancher Lab’s minimal Kubernetes distribution) in docker.
  k3d makes it very easy to create single- and multi-node k3s clusters in docker, e.g. for local development on Kubernet
```

### Environment

```shell
Windows Package Manager v1.9.25200
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.4602
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.25200.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

> [!NOTE]
> Even when the settings are switched to `requirements`, it fails to install the package, so it probably falls back to en-US. Am I missing something here?

**Comment by mdanish-kh** [comment]
The `locale` preference is being set for the `installBehavior` here which means that it affects the installer which WinGet is going to select for installation. You can verify that the preference / requirement is being honored correctly by testing on a package that offers different installers for different locales e.g., [CPUID.CPU-Z](https://github.com/microsoft/winget-pkgs/blob/6bdc7353b9da0e7f48415dc9c8afc03dcb1f06a5/manifests/c/CPUID/CPU-Z/2.12/CPUID.CPU-Z.installer.yaml#L22-L29). You can see it working in the screenshot below

<details>
<summary>Screenshot</summary>

![Image](https://github.com/user-attachments/assets/2d1e72ec-5ede-4b74-b328-9a92e68bc661)

</details>

As for `winget show`, _I believe_ (don't quote me on this tho as I didn't check the source code :D) the output defaults to your OS locale. There doesn't appear to be a WinGet setting to set a preference for something like `showBehavior`. Though you can pass `--locale` argument as `winget show CPUID.CPU-Z --locale zh-CN`

**Comment by Gijsreyn** [comment]
Thanks for the detailed explanation @mdanish-kh . Then, the package I was choosing might be invalid. I'll close the issue.
