### ISSUE TITLE
Vanity URL winget pin doesn't redirect to correct page

### ISSUE THREAD

**Issue by Gijsreyn** [microsoft/winget-cli#5088]
### Brief description of your issue

When looking through the help documentation of `winget pin`, I noticed the URL being used: https://aka.ms/winget-command-pin, doesn't redirect to: https://learn.microsoft.com/en-us/windows/package-manager/winget/pinning. Instead, it lands on the general overview page. This is a minor issue.

**Comment by mdanish-kh** [comment]
Can you check again? Someone may have fixed the URL, it appears to be opening the right page for me now

[comment]: <[Policy] Needs-Author-Feedback>

**Comment by florelis** [comment]
I just fixed it :)

**Comment by Gijsreyn** [comment]
Yippie! Thanks @florelis
