### ISSUE TITLE
Add JSON Schema to settings.json

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/winget-cli#509]
# Description of the new feature/enhancement
Now that there's a settings.json file, it'd be nice to have a [json schema](https://json-schema.org/). It allows users to make sure their edits are in spec and editors to provide smarter autocomplete options.

# Proposed technical implementation details (optional)

If you want an example/inspiration, Windows Terminal does it like this:

![description example](https://user-images.githubusercontent.com/11050425/88292266-731c1580-ccc7-11ea-945f-3bf23442c440.png)

![autocomplete example](https://user-images.githubusercontent.com/11050425/88292328-8202c800-ccc7-11ea-8c05-a9e197fb2e5b.png)

[schema.json](https://github.com/microsoft/terminal/blob/master/doc/cascadia/profiles.schema.json)

**Comment by megamorf** [comment]
I just worked on creating a schema for a Cloud Foundry application today. You can take a shortcut by pasting a complete json config here <https://www.jsonschema.net/home> (click on **continue as a Guest** below the log in buttons). Once you have that basic schema skeleton you have to fine tune it. This video should help you get started: https://www.youtube.com/watch?v=ZXOKPDmSYEw (don't forget to watch part 2 as well).

I spent this evening and got a working solution so it shouldn't take long for you either. I used [ajv](https://github.com/ajv-validator/ajv/) as validator with [better-ajv-errors](https://github.com/atlassian/better-ajv-errors) which gives me pretty error messages (that's both written in Javascript though).

Here's an example error from my schema generated by better-ajv-errors:
![image](https://user-images.githubusercontent.com/1732128/88351120-98576500-cd55-11ea-9d78-5f3173c6df47.png)

**Comment by denelon** [comment]
Related to #165

**Comment by denelon** [comment]
"$schema": "https://aka.ms/winget-settings.schema.json",

**Comment by alannt777** [comment]
Close this issue then?

**Comment by denelon** [comment]
@ghost, thanks for the comment. I missed this one :)
