### ISSUE TITLE
Add Option to choose file easily

### ISSUE THREAD

**Issue by Agent24015** [microsoft/winget-cli#511]
Hi , can you make a feature which allows easy selection of an App when there is more than on app to be downloaded
Something Like This,

```
Microsoft Windows [Version 10.0.19041.388]
(c) 2020 Microsoft Corporation. All rights reserved

Multiple apps found matching input criteria. Please refine the input
Name                     	                   Id                    Version       
---------------------------------------------------------------------------------------
[1] Windows Terminal     	  Microsoft.WindowsTerminal              1.1.2021.0    
[2] Terminus                      Eugeny.Terminus                        1.0.112        
[3] Windows Terminal Preview      Microsoft.WindowsTerminalPreview       1.2.2022.0   

Please choose a Number to install it :  
```

**Comment by megamorf** [comment]
@Agent24015 Thanks for reporting this. However, I'd recommend closing this issue since the solution to your problem can be found by checking the [docs](https://docs.microsoft.com/windows/package-manager/winget/install#options) or the command line help (`winget install --help`). What you're looking for is the `--exact` (`-e`) parameter. See:
* #133 
* #282
* #301

**Comment by Agent24015** [comment]
Yes, I have read the docs and know about the -e parameter, but I think that
it will be more easy if it is with numbers.

**Comment by suhailmalik07** [comment]
Package are not things where you have choice. If I asked for `windows terminal`. It should install windows terminal and didn't give me options to choose which I didn't asked. 

Your idea is good but not for this situation.

**Comment by denelon** [comment]
We're testing a version with the changes for #292 and it's close to being released.
The search command would behave essentially as it does today. The query parameter (the string you typed in) is checked as a substring of several fields "Name", "Id", "moniker", etc. 
The install and show command use the "exact" type behavior so if there is only one exact match you will get that program installed (with install) or it's manifest displayed with show.

This feature or something very similar might work well when you provide a search string and there isn't an exact match. We could still provide the list of similar results and in that specific case, we could provide the option to select one of the "close" matches in the event what the user wants is displayed. 

@Agent24015 would that work for the use case you are describing here?

**Comment by Agent24015** [comment]
Yup, that will be ok, but I have a small suggestion, could you make it
like it will provide the most similar result and will ask the user if they
want to install it or not, If yes, it will continue, else the user will be
asked to choose.

**Comment by denelon** [comment]
@Agent24015 have you had a chance to check the "current" version of the behavior for the client? `search` is still a more broad command that will pull multiple results back even when there is an exact match (as in the case of `winget search power`. The `show` and `install` command will use an exact match if one exists.
