### ISSUE TITLE
Do something about AppGet, which is now defunct

### ISSUE THREAD

**Issue by StewAlexander-com** [microsoft/winget-cli#518]
Just a comment to do something about AppGet which is now defunct; we and plenty of others used AppGet, and with it down, and WinGet not up, we are left with Chocolatey which doesn't work for us due to how it does things...  we can get it to work, and we have, but AppGet was a much smoother easier alternative.

Thanks ...

**Comment by denelon** [comment]
I've just enabled GitHub Discussions. I'm converting this Issue to a Discussion.
