### ISSUE TITLE
Installing GNU Arm Embedded Toolchain package somehow messed up my PATH

### ISSUE THREAD

**Issue by RedstonekPL** [microsoft/winget-cli#519]
# Brief description of your issue

Yesterday, I've downloaded GNU Arm Embedded Toolchain through winget. Everything was working. So, I turned off my computer and went to sleep. Today, the only path in user PATH is the one to the package. 

# Steps to reproduce

1. Install GNU Arm Embedded Toolchain
2. Restart the computer

# Expected behavior

Add some ARM compilers. Not mess up my local PATH variable.

# Actual behavior

It does this with my local PATH:
![](https://user-images.githubusercontent.com/29150618/88919585-a46a8780-d26b-11ea-8fb3-eb00cf05fb8c.png)
Even winget doesn't work!
![](https://user-images.githubusercontent.com/29150618/88919699-ded42480-d26b-11ea-9043-a5af295c2287.png)

# Environment

```none
[Yesterday's log file]
Windows Package Manager version 0.1.41821
Windows: Windows.Desktop version 10.0.18363.959
Package: Microsoft.DesktopAppInstaller version 1.0.41821.0

Any other software?
```

**Comment by denelon** [comment]
@RedstonekPL can you see if there is an update to the App Installer in the Store? The current version of winget should be v0.1.42101.

**Comment by fedot** [comment]
This is not related to the win-get but the ARM installer, it is replaces the PATH during the installation (removing any previous values) 💩

**Comment by denelon** [comment]
Is there a bug reported on the ARM toolchain installer somewhere we can reference here?

**Comment by fedot** [comment]
I can't really find one. I'm pretty sure it's related to the nsis script of toolchain installer. I'll try and see if I can dig a bit deeper once I have some spare time

**Comment by juxuanu** [comment]
I just had this with the v14 on Windows... All my Path env var was reset, now I don't know how to get it back. Updated with winget.

**Comment by doinkythederp** [comment]
I had the same issue! I don't think should be closed as completed.

**Comment by ThatDogGuy** [comment]
Same issue here too! Should be reopened because it's quite frustrating to lose all my path.

**Comment by NicoPowers** [comment]
Just happened to me too... wtf how they could let this happen for so long, how incompetent are these "engineers" to let this happen? All you have to do is append not replace...

**Comment by X1nto** [comment]
Happened to me too, except I used their own installer. None of my 3rd party commands resolve. Incompetent fucks.
