### ISSUE TITLE
tedious to list available versions of a package..

### ISSUE THREAD

**Issue by darbotron** [microsoft/winget-cli#520]
It would be nice if getting hold of the available versions of a package was less involved.
If you don't know the package path in advance, you have to search for the package with `winget search xxx` then again with `winget show xxx.yyy.zzz -versions`, then `winget install xxx.yyy.zzz -v a.b.c`.
I'd like to be able to use `-versions` with `search` as this would cut out an unnecessary step,

**Comment by megamorf** [comment]
I think the separation of concern between searching across all latest versions of packages (`winget search`) and listing available versions of a specific packages (`winget search`) is good as it is. Mixing both just makes the code base needlessly complex and harder to maintain.

**Comment by denelon** [comment]
I think I have some good news coming. @JohnMcPMS did a hackathon project and has a PR out #521. If you're using PowerShell, you will have the ability to tab through the versions.

**Comment by vedantmgoyal2009** [comment]
* https://github.com/microsoft/winget-cli/pull/521

Auto-completion is now available. This can be marked as completed.

**Comment by denelon** [comment]
@vedantmgoyal2009 I was looking at a YouTube video someone created for the Windows Package Manager. I noticed that they used "winget search" to try and find versions. I think this is a feature we want to implement. It's essentially adding "--versions" to the search command, and would produce the same output as "winget show --versions".

**Comment by denelon** [comment]
This is resolved with:
* #2847

The feature is available in WinGet [v1.5.441-preview](https://github.com/microsoft/winget-cli/releases/tag/v1.5.441-preview).
