### ISSUE TITLE
Can't install "Gnu Arm Embedded Toolchain"

### ISSUE THREAD

**Issue by LK4D4** [microsoft/winget-cli#523]
# Brief description of your issue
Trying to install Gnu Arm Embedded Toolchain and it either doesn't work or I can't figure out proper commands (which could be some kind of UX issue).
It is present in [winget-pkgs](https://github.com/microsoft/winget-pkgs/blob/master/manifests/Arm/GnuArmEmbeddedToolchain/9-2020-q2-update.yaml) and searchable by `winget search`.

# Steps to reproduce
```
C:\> winget search Arm.GnuArm
Name                       Id                          Version
-----------------------------------------------------------------------
Gnu Arm Embedded Toolchain Arm.GnuArmEmbeddedToolchain 9-2020-q2-update

C:\> winget install -e --id="Arm.GnuArmEmbeddedToolchain"
No package found matching input criteria.

C:\> winget install -e --name="Gnu Arm Embedded Toolchain"
No package found matching input criteria.
```

# Expected behavior
Gnu Arm Toolchain installed

# Actual behavior
Error `No package found matching input criteria.`

# Environment

```C:\> winget --info
Windows Package Manager v0.1.42101 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.421
Package: Microsoft.DesktopAppInstaller v1.10.42101.0
...
```

**Comment by denelon** [comment]
@LK4D4  Arm.GnuArmEmbeddedToolchain is the package Id.
Try `winget install Arm.GnuArmEmbeddedToolchain`

**Comment by LK4D4** [comment]
@denelon Thanks! That works, but why `--id=` doesn't? It worked for powershell for example.

**Comment by denelon** [comment]
@LK4D4 the syntax would be:

`winget install -e --id Arm.GnuArmEmbeddedToolchain`

The "=" sign is not part of the syntax for an argument.

I'm going to close the Issue since I believe your problem has been addressed. Feel free to open any new Issues you encounter.
