### ISSUE TITLE
Log does not include actual command used to install app.

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/winget-cli#525]
When processing PR 2904 it failed with 1603.
When looking at the LOG
C:\Users\kevinla\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet\LibreOffice.LibreOffice.7.0.0.log

It has lots of details, but not the actual command that the winget executes to install the app.

I would have expected to see:
MSIExec <file.msi>   /qn /norestart
 
But it just states 1603 error which is you need to be an admin.

EXAMPLE LOG and Manifest

:\Users\kevinla\winget-pkgs>type C:\Users\kevinla\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet\LibreOffice.LibreOffice.7.0.0.log
=== Logging started: 8/5/2020  10:21:19 ===
Action start 10:21:19: INSTALL.
Action start 10:21:19: AppSearch.
Action ended 10:21:19: AppSearch. Return value 1.
Action start 10:21:19: LaunchConditions.
MSI (s) (28:C0) [10:21:19:797]: Product: LibreOffice 7.0.0.3 -- The Installation Wizard cannot be run properly because you are logged in as a user without sufficient administrator rights for this system.

The Installation Wizard cannot be run properly because you are logged in as a user without sufficient administrator rights for this system.
Action ended 10:21:19: LaunchConditions. Return value 3.
Action ended 10:21:19: INSTALL. Return value 3.
Property(S): DiskPrompt = [1]
Property(S): UpgradeCode = {4B17E523-5D91-4E69-BD96-7FD81CFA81BB}
Property(S): WIN81S14 = C:\Windows\system32\kernel32.dll
Property(S): WINMAJORVER = #10
Property(S): CREATEDESKTOPLINK = 1
Property(S): FontsFolder = C:\Windows\Fonts\
Property(S): ApplicationUsers = AllUsers
Property(S): SELECT_WORD = 0
Property(S): SELECT_EXCEL = 0
Property(S): SELECT_POWERPOINT = 0
Property(S): SELECT_VISIO = 0
Property(S): AgreeToLicense = No
Property(S): _IsMaintenance = Change
Property(S): MsiUIRMOption = DontUseRM
Property(S): SetupType = Typical
Property(S): _IsSetupTypeMin = Typical
Property(S): Display_IsBitmapDlg = 1
Property(S): ALLUSERS = 1
Property(S): DesktopFolder = C:\Users\Public\Desktop\
Property(S): WindowsFolder = C:\Windows\
Property(S): ProgramFiles64Folder = C:\Program Files\
Property(S): TemplateFolder = C:\ProgramData\Microsoft\Windows\Templates\
Property(S): LocalAppDataFolder = C:\Users\kevinla\AppData\Local\
Property(S): CommonFilesFolder = C:\Program Files (x86)\Common Files\
Property(S): StartMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\
Property(S): ProgramMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\
Property(S): CommonAppDataFolder = C:\ProgramData\
Property(S): StartupFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\
Property(S): FINDPRODUCT = Software\LibreOffice\Layers\LibreOffice\7.0
Property(S): ARPCOMMENTS = LibreOffice 7.0 (multilanguage)
Property(S): ARPCONTACT = LibreOffice Community
Property(S): ARPHELPLINK = https://www.libreoffice.org/get-help
Property(S): ARPURLINFOABOUT = https://www.libreoffice.org/
Property(S): ARPURLUPDATEINFO = https://www.libreoffice.org/download
Property(S): DefaultUIFont = DialogDefault
Property(S): DialogCaption = Windows Installer
Property(S): DisplayNameCustom = IDPROP_SETUPTYPE_CUSTOM
Property(S): DisplayNameMinimal = IDPROP_SETUPTYPE_COMPACT
Property(S): DisplayNameTypical = IDPROP_SETUPTYPE_TYPICAL
Property(S): DWUSINTERVAL = 30
Property(S): ErrorDialog = SetupError
Property(S): FILETYPEDIALOGUSED = 0
Property(S): InstallChoice = AR
Property(S): INSTALLLEVEL = 100
Property(S): ISCHECKFORPRODUCTUPDATES = 1
Property(S): ISSCRIPT_VERSION_MISSING = IDS_ISSCRIPT_VERSION_MISSING
Property(S): ISSCRIPT_VERSION_OLD = IDS_ISSCRIPT_VERSION_OLD
Property(S): ISVROOT_PORT_NO = 0
Property(S): Manufacturer = The Document Foundation
Property(S): MSIFASTINSTALL = 1
Property(S): MSIRESTARTMANAGERCONTROL = 0
Property(S): PIDTemplate = 12345<###-%%%%%%%>@@@@@
Property(S): ProductCode = {7C7F19DA-6107-4284-9263-EC5C4792C8C7}
Property(S): ProductID = none
Property(S): ProductLanguage = 1033
Property(S): ProductName = LibreOffice 7.0.0.3
Property(S): ProductVersion = 7.0.0.3
Property(S): ProgressType0 = install
Property(S): ProgressType1 = Installing
Property(S): ProgressType2 = installed
Property(S): ProgressType3 = installs
Property(S): Quickstarterlinkname = LibreOffice 7.0
Property(S): RebootYesNo = Yes
Property(S): ReinstallModeText = omus
Property(S): SecureCustomProperties = NEWPRODUCTS;OLDPRODUCTS;WIN81S14;WINMAJORVER
Property(S): STR_NEW_DISPLAY_NAME = ~New
Property(S): STR_EDIT = ~Edit
Property(S): STR_MS_WORD_DOCUMENT = Microsoft Word Document
Property(S): STR_MS_WORD_TEMPLATE = Microsoft Word Template
Property(S): STR_MS_EXCEL_WORKSHEET = Microsoft Excel Worksheet
Property(S): STR_MS_EXCEL_TEMPLATE = Microsoft Excel Template
Property(S): STR_MS_POWERPOINT_PRESENTATION = Microsoft PowerPoint Presentation
Property(S): STR_MS_POWERPOINT_TEMPLATE = Microsoft PowerPoint Template
Property(S): STR_MS_POWERPOINT_SHOW = Microsoft PowerPoint Show
Property(S): STR_INSTALLATION_WIZARD = Installation Wizard
Property(S): VC_REDIST = 1
Property(S): WindowsMinVersionText = Windows 7 SP1
Property(S): WindowsMinVersionNumber = 601
Property(S): WindowsMinSPNumber = 1
Property(S): DEFINEDPRODUCT = LibreOffice
Property(S): DEFINEDVERSION = 7.0
Property(S): PRODUCTMAJOR = 00
Property(S): PRODUCTBUILDID = 3
Property(S): URELAYERVERSION = 1
Property(S): BRANDPACKAGEVERSION = 7.0
Property(S): IGNOREPREREQUIREDPATCH = 1
Property(S): DONTOPTIMIZELIBS = 0
Property(S): OFFICEDIRHOSTNAME = LibreOffice
Property(S): OFFICEDIRHOSTNAME_ = LibreOffice
Property(S): DESKTOPLINKEXISTS = 1
Property(S): PRODUCTALLLANGUAGES = en-US_af_am_ar_as_ast_be_bg_bn_bn-IN_bo_br_brx_bs_ca_ca-valencia_ckb_cs_cy_da_de_dgo_dsb_dz_el_en-GB_en-ZA_eo_es_et_eu_fa_fi_fr_fur_fy_ga_gd_gl_gu_gug_he_hsb_hi_hr_hu_id_is_it_ja_ka_kab_kk_km_kmr-Latn_kn_ko_kok_ks_lb_lo_lt_lv_mai_mk_ml_mn_mni_mr_my_nb_ne_nl_nn_nr_nso_oc_om_or_pa-IN_pl_pt_pt-BR_ro_ru_rw_sa-IN_sat_sd_sr-Latn_si_sid_sk_sl_sq_sr_ss_st_sv_sw-TZ_szl_ta_te_tg_th_tn_tr_ts_tt_ug_uk_uz_ve_vec_vi_xh_zh-CN_zh-TW_zu
Property(S): WRITE_REGISTRY = 1
Property(S): HIDEEULA = 1
Property(S): REGISTER_PPS = 0
Property(S): REGISTER_PPSX = 0
Property(S): REGISTER_PPT = 0
Property(S): REGISTER_PPTX = 0
Property(S): REGISTER_PPTM = 0
Property(S): REGISTER_POT = 0
Property(S): REGISTER_POTX = 0
Property(S): REGISTER_POTM = 0
Property(S): REGISTER_DOC = 0
Property(S): REGISTER_DOCX = 0
Property(S): REGISTER_DOCM = 0
Property(S): REGISTER_DOT = 0
Property(S): REGISTER_DOTX = 0
Property(S): REGISTER_DOTM = 0
Property(S): REGISTER_RTF = 0
Property(S): REGISTER_XLS = 0
Property(S): REGISTER_XLSX = 0
Property(S): REGISTER_XLSM = 0
Property(S): REGISTER_XLSB = 0
Property(S): REGISTER_XLT = 0
Property(S): REGISTER_XLTX = 0
Property(S): REGISTER_XLTM = 0
Property(S): REGISTER_IQY = 0
Property(S): REGISTER_NO_MSO_TYPES = 0
Property(S): REGISTER_ALL_MSO_TYPES = 0
Property(S): isMulti = 1
Property(S): ARPPRODUCTICON = soffice.ico
Property(S): DirectoryTable100_x86.F1670FCA_6780_3657_9C04_AF8005AC8143 = DirectoryTable
Property(S): DirectoryTable100_amd64.DFEFC2FE_EEE6_424C_841B_D4E66F0C84A3 = DirectoryTable
Property(S): MsiLogFileLocation = C:\Users\kevinla\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet\LibreOffice.LibreOffice.7.0.0.log
Property(S): PackageCode = {6A526651-6E3C-4CCD-A03A-5CE0CC09EA8D}
Property(S): ProductState = -1
Property(S): PackagecodeChanging = 1
Property(S): REBOOT = ReallySuppress
Property(S): CURRENTDIRECTORY = C:\Users\kevinla\winget-pkgs
Property(S): CLIENTUILEVEL = 3
Property(S): CLIENTPROCESSID = 7968
Property(S): MsiRestartManagerSessionKey = 6cd0777dd7aa9340bd9006b84e221eeb
Property(S): MsiSystemRebootPending = 1
Property(S): VersionDatabase = 200
Property(S): VersionMsi = 5.00
Property(S): VersionNT = 603
Property(S): ACTION = INSTALL
Property(S): VersionNT64 = 603
Property(S): WindowsBuild = 9600
Property(S): ServicePackLevel = 0
Property(S): ServicePackLevelMinor = 0
Property(S): MsiNTProductType = 1
Property(S): WindowsVolume = C:\
Property(S): System64Folder = C:\Windows\system32\
Property(S): SystemFolder = C:\Windows\SysWOW64\
Property(S): RemoteAdminTS = 1
Property(S): TempFolder = C:\Users\kevinla\AppData\Local\Temp\
Property(S): ProgramFilesFolder = C:\Program Files (x86)\
Property(S): CommonFiles64Folder = C:\Program Files\Common Files\
Property(S): AppDataFolder = C:\Users\kevinla\AppData\Roaming\
Property(S): FavoritesFolder = C:\Users\kevinla\Favorites\
Property(S): NetHoodFolder = C:\Users\kevinla\AppData\Roaming\Microsoft\Windows\Network Shortcuts\
Property(S): PersonalFolder = C:\Users\kevinla\Documents\
Property(S): PrintHoodFolder = C:\Users\kevinla\AppData\Roaming\Microsoft\Windows\Printer Shortcuts\
Property(S): RecentFolder = C:\Users\kevinla\AppData\Roaming\Microsoft\Windows\Recent\
Property(S): SendToFolder = C:\Users\kevinla\AppData\Roaming\Microsoft\Windows\SendTo\
Property(S): MyPicturesFolder = C:\Users\kevinla\Pictures\
Property(S): AdminToolsFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\
Property(S): GPTSupport = 1
Property(S): OLEAdvtSupport = 1
Property(S): ShellAdvtSupport = 1
Property(S): MsiAMD64 = 6
Property(S): Msix64 = 6
Property(S): Intel = 6
Property(S): PhysicalMemory = 6141
Property(S): VirtualMemory = 4485
Property(S): LogonUser = kevinla
Property(S): UserSID = S-1-5-21-283550467-216719282-1724522227-1000
Property(S): UserLanguageID = 1033
Property(S): ComputerName = KEVINLA-D1P8
Property(S): SystemLanguageID = 1033
Property(S): ScreenX = 1024
Property(S): ScreenY = 768
Property(S): CaptionHeight = 19
Property(S): BorderTop = 1
Property(S): BorderSide = 1
Property(S): TextHeight = 16
Property(S): TextInternalLeading = 3
Property(S): ColorBits = 32
Property(S): TTCSupport = 1
Property(S): Time = 10:21:19
Property(S): Date = 8/5/2020
Property(S): MsiNetAssemblySupport = 4.8.4161.0
Property(S): MsiWin32AssemblySupport = 6.3.20185.1000
Property(S): RedirectedDllSupport = 2
Property(S): DATABASE = C:\Windows\Installer\2da9ada.msi
Property(S): OriginalDatabase = C:\Users\kevinla\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet\LibreOffice.LibreOffice.7.0.0.msi
Property(S): UILevel = 2
MSI (s) (28:C0) [10:21:19:867]: Product: LibreOffice 7.0.0.3 -- Installation operation failed.

MSI (s) (28:C0) [10:21:19:867]: Windows Installer installed the product. Product Name: LibreOffice 7.0.0.3. Product Version: 7.0.0.3. Product Language: 1033. Manufacturer: The Document Foundation. Installation success or error status: 1603.
=== Logging stopped: 8/5/2020  10:21:19 ===

C:\Users\kevinla\winget-pkgs>
C:\Users\kevinla\winget-pkgs>type manifests\LibreOffice\LibreOffice\7.0.0.yaml
# ================== General ==================
Id: LibreOffice.LibreOffice
Publisher: The Document Foundation
Name: LibreOffice
Description: LibreOffice is a free and powerful office suite, and a successor to OpenOffice.org (commonly known as OpenOffice). Its clean interface and feature-rich tools help you unleash your creativity and enhance your productivity.
AppMoniker: libreoffice
Tags: libreoffice, odf, openoffice

# ================= License ==================
Homepage: https://www.libreoffice.org/
License: Mozilla Public License Version 2.0
LicenseUrl: https://www.libreoffice.org/about-us/licenses

# ================= Installer =================
Version: 7.0.0

Switches:
    Silent: /qn /norestart
    SilentWithProgress: /qn /norestart

InstallerType: msi
Installers:
  - Arch: x64
    Url: https://download.documentfoundation.org/libreoffice/stable/7.0.0/win/x86_64/LibreOffice_7.0.0_Win_x64.msi
    Sha256: 7e779fc8e0ec162fc3c6bbd96779ea7c4578e4ae43c2591516a24043752b78f6

**Comment by denelon** [comment]
The command is included in the WinGet log, not the application's install log.
