### ISSUE TITLE
winget.exe does not display characters properly in cmd.exe and powershell if user's preferred language is Korean

### ISSUE THREAD

**Issue by chitturs** [microsoft/winget-cli#529]
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

I ACKNOWLEDGE THE FOLLOWING BEFORE PROCEEDING:
1. If I delete this entire template and go my own path, the core team may close my issue without further explanation or engagement.
2. If I list multiple bugs/concerns in this one issue, the core team may close my issue without further explanation or engagement.
3. If I write an issue that has many duplicates, the core team may close my issue without further explanation or engagement (and without necessarily spending time to find the exact duplicate ID number).
4. If I leave the title incomplete when filing the issue, the core team may close my issue without further explanation or engagement.
5. If I file something completely blank in the body, the core team may close my issue without further explanation or engagement.

All good? Then proceed!
-->

# Brief description of your issue
cmd.exe and powershell do not display winget.exe korean characters.

Please use this section to describe your issue.   This could be a repeat of the title, or maybe you have more to say.
winget.exe does not display characters properly in cmd.exe and powershell if user's preferred language is Korean

# Steps to reproduce

1. Go to settings and make Korean the user's preferred language. Run winget.exe from cmd.exe or powershell. (This works fine from Windows Terminal, so it might give a clue as to what is broken).

# Expected behavior

Expected to see characters in Korean.

# Actual behavior

Garbage characters displayed

# Environment

2007 version of winget.

Any other software?
```

**Comment by megamorf** [comment]
Please post the output of the following command:

    winget --info

**Comment by chitturs** [comment]
C:\Windows\system32>winget --info
Windows Package Manager v0.1.42101 미리 보기
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.388
패키지: Microsoft.DesktopAppInstaller v1.10.42101.0

링크
---------------------------------------------
개인정보처리방침 https://aka.ms/winget-privacy
라이선스 계약  https://aka.ms/winget-license
타사 통지 사항 https://aka.ms/winget-3rdPartyNotice
홈페이지     https://aka.ms/winget

**Comment by chitturs** [comment]
It copy/pastes fine in Edge but cmd.exe just displays a bunch of rectangles instead of Korean. John McPherson knows it.

**Comment by JohnMcPMS** [comment]
It turns out that this is expected; you have to have the correct font selected in order to display these characters because the standard connhost does not (and likely will never) have font fallback.  Terminal does have this feature, and thus it works there, regardless of the font selected.
