### ISSUE TITLE
应用安装失败

### ISSUE THREAD

**Issue by StephenWu5** [microsoft/winget-cli#540]
应用安装失败，错误消息: 从  (Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle)  使用程序包 Microsoft.DesktopAppInstaller_2020.728.2353.0_neutral_~_8wekyb3d8bbwe 中的目标卷 C: 执行的部署 Add 操作失败，错误为 0x8000FFFF。有关诊断应用部署问题的帮助，请参阅 http://go.microsoft.com/fwlink/?LinkId=235160。 (0x8000ffff)

![image](https://user-images.githubusercontent.com/32475322/90460863-6d371a00-e137-11ea-9026-ab59c65574f8.png)

请问如何解决？？

**Comment by JohnMcPMS** [comment]
If possible, using Feedback Hub via this link http://aka.ms/appdepuif will collect traces that we can use to determine what is happening.  Please post a link back to the issue that you file.

Translated with bing:
如果可能，通过此链接 http://aka.ms/appdepuif 反馈中心，收集可用于确定所发生情况的跟踪。 请发布指向您提交的问题的链接。

**Comment by StephenWu5** [comment]
ok，i see
