### ISSUE TITLE
Roadmap is outdated, please update

### ISSUE THREAD

**Issue by davlgd** [microsoft/winget-cli#541]
The [doc/windows-package-manager-v1-roadmap.md](https://github.com/microsoft/winget-cli/blob/master/doc/windows-package-manager-v1-roadmap.md) document states that v0.2, 0.3, 0.4 should have been published within the last three months. They weren't. Can you please update the roadmap and clarify when next major release will be available and what are the features we can expect short term ?

**Comment by denelon** [comment]
@davlgd the dates on the milestones were aspirational. I was using them mainly to try and have the releases render as a sequence in GitHub. I had put the comment "Due date is primarily used to sort milestones, and not an expectation of release date." in the description to provide clarity. 

The roadmap will be updated with revised sequencing of features over the next couple of weeks. In terms of "Major" releases, we're still in preview and anticipate the first major (v1.0) release to happen "March-May 2021".

Is there a specific feature (or set of features) you are interested in, or is the request more informational in nature?

**Comment by davlgd** [comment]
More informational, as v1.0 is 6-9 months away it could be interesting to know what is short term focus. We see things moving (store manifest, feature toggle), but not where its going for next releases. For features, I think it's like anybody else here : Store compatibility, multi-install (winget install 7zip vlc), update/remove, zip/exe portable apps manifest, etc.

**Comment by denelon** [comment]
I'm building out the milestones now, so you should see some things moving around. Top of mind right now is: store, list, upgrade, uninstall, export/import, and dependencies. 

I think the export/import will take precedence over multi-install for now, but one could certainly customize a file to "import". The other installer formats (.zip, .exe, PWA) are likely all included. Some stand alone self extracting .exe's might not make it depending on how they are constructed and what they do. It's one thing to put an .exe file on the disk and update the path, and something completely different to have an .exe file try to do things on it's own with respect to the path and where it lands on the file system.

**Comment by davlgd** [comment]
Thanks for you answers ;)

**Comment by denelon** [comment]
PowerShell is on the list. I'm still working through the backlog.

**Comment by victorhooi** [comment]
What's the PowerShell module? Is this for running arbitrary PowerShell to install apps? Or something else?

**Comment by doctordns** [comment]
> What's the PowerShell module? Is this for running arbitrary PowerShell to install apps? Or something else?

My understanding is that converting winget to PowerShell is something the team want to do. So far as I can see, there is nothing in the current roadmap document that corresponds to work on a PowerShell solution. I repeat my view that if WInget is to be adopted more widely an IT Pro-focused solution is required and the team has not released any details on the underlying object model or the proposed cmdlets. As time goes on, the team is just making it harder for themselves.

**Comment by denelon** [comment]
The roadmap has been updated. And #221 Add Native PowerShell Support is milestone [v0.24.x](https://github.com/microsoft/winget-cli/milestone/26).

**Comment by doctordns** [comment]
Thanks for adding PowerShell milestone. 

Are there any documents available that examine the approach to be taken by this support?
