### ISSUE TITLE
External package repos

### ISSUE THREAD

**Issue by jascodes** [microsoft/winget-cli#554]
# Description of the new feature/enhancement
Allow ability to update default package repo to my own fork of winget-pkgs. My change will be instantly available to as the pull request move through approval process.

Other way is to allow multiple package repos like external buckets where one can keep like of packages not suitable for public package repo such as tools built for private consumption only.

# Proposed technical implementation details (optional)

**Comment by megamorf** [comment]
That's not how this works. The winget-pkgs repo is just an intermediate step that kicks of an Azure CI process that when successful updates a SQLite index file. This file is what the winget-cli retrieves in regular intervals. That means that winget-cli as it is now does not use the manifest files stored in winget-pkgs.

**Comment by denelon** [comment]
@jascodes we are working on #118 a REST API that would simplify hosting your own repository of packages. @megamorf correctly described how the GitHub packages repository is used. We are looking at an open source and/or an Azure Marketplace offering that would simplify the process of standing up a private repository.

**Comment by denelon** [comment]
@jascodes you can now stand up your own repository :)
https://github.com/microsoft/winget-cli-restsource

We've still got some documentation to update, but a compliant HTTPS REST implementation is supported by the client.
