### ISSUE TITLE
Installing a set of packages from a config defination file

### ISSUE THREAD

**Issue by raisedadead** [microsoft/winget-cli#555]
# Description of the new feature/enhancement

Have a config defination of a set of packages to install at a go, useful when setting up devices. This is similar to the Brewfile on Homebrew.

Most users can keep such a defination in version control.

# Proposed technical implementation details (optional)

**Comment by blogcraft** [comment]
Just like npm's package.json? I love the idea.

**Comment by raisedadead** [comment]
Yes, very similar to that. 

On macOS (and Linux too), where Homebrew is the package manager of choice users have a file (called Brewfile) that is just a list of packages that you have installed.

This file can be moved around using version control. You just get the file in any machine that you want and run one command to install all the packages in the list.

Its kind of neat when you have ephemeral setups and want to take your config where you need.
