### ISSUE TITLE
Add SpellChecker to GH Action

### ISSUE THREAD

**Issue by WSLUser** [microsoft/winget-cli#559]
Adding the Spellchecker will help with docs and code with misspellings. You can find it here: https://github.com/jsoref/spelling and is available in the GH Action Marketplace. Windows Terminal is already using it for example: https://github.com/microsoft/terminal/pull/4799

**Comment by WSLUser** [comment]
Since this has been assigned, summoning @jsoref to help winget adopt this.

**Comment by alannt777** [comment]
PowerToys also recently adopted this: https://github.com/microsoft/PowerToys/issues/7700

**Comment by jsoref** [comment]
@wsluser, sorry for the delay, not sure how I missed this. I will watch the repo for a bit after it merges to ensure a smooth ride.

**Comment by denelon** [comment]
@jsoref, I've asked @JohnMcPMS to take a look at the PR.
