### ISSUE TITLE
Can't use winget in xonsh, a shell powered by python

### ISSUE THREAD

**Issue by oxygen-dioxide** [microsoft/winget-cli#565]
# Brief description of your issue
Can't use winget on xonsh

# Steps to reproduce
1. Download and install python
2. pip install xonsh (in cmd)
3. Run any winget command in xonsh. For example, "winget install deepvocal", or "winget search browser"

# Expected behavior
Winget commands work successfully.

# Actual behavior
Winget commands work successfully in cmd, but fail in xonsh
```
For full traceback set: $XONSH_SHOW_TRACEBACK = True
OSError: [Errno 22] Invalid argument: 'C:\\Users\\lin\\AppData\\Local\\Microsoft\\WindowsApps\\winget.exe'
```

xonsh (left) and cmd (right)
![image](https://user-images.githubusercontent.com/54425948/92865310-ba559580-f430-11ea-9f0a-f32411b6fb0b.png)

# Environment

```none
[winget --info]
Windows Package Manager v0.1.42241
Windows: Windows.Desktop v10.0.20206.1000
Package: Microsoft.DesktopAppInstaller v1.10.42241.0

python 3.7.6
xonsh 0.9.18
```

[I have created an issue in the xonsh repo](https://github.com/xonsh/xonsh/issues/3752)

**Comment by megamorf** [comment]
This could be related to #228.

**Comment by oxygen-dioxide** [comment]
Xonsh will fix this issue in the next version.

**Comment by anki-code** [comment]
Xonsh 0.23.0 will have winget - https://github.com/xonsh/xonsh-winget
There is pre-release version on Releses page.
