### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by yashomer1994** [microsoft/winget-cli#567]
# Brief description of your issue

# Steps to reproduce

# Expected behavior

# Actual behavior

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
```

**Comment by yashomer1994** [comment]
Windows Package Manager v0.1.42241 Preview
Build : Windows 10 Pro Insider Preview - 2011.rs_prerelease.200904-1619

There's an issue with command git .
After installing git using winget.

I tried to clone any git repo , I got an error as mentioned below once it is installed .
Error: git: The term 'git' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

NOTE: We need to restart Terminal to use git. makes it less productive to use

**Comment by megamorf** [comment]
Bad title and issue description is missing, please put more effort into creating new issues and use the search function next time because your issue is actually a duplicate of #222.

**Comment by yashomer1994** [comment]
Ok  will make it good next time. 
This was my first for microsoft

**Comment by denelon** [comment]
@yashomer1994 thank you for submitting the issue. @megamorf thank you for the help identifying #222.

**Comment by denelon** [comment]
Duplicate of #222
