### ISSUE TITLE
Include checksums in the GitHub releases

### ISSUE THREAD

**Issue by felipecrs** [microsoft/winget-cli#568]
It would be very useful if checksums, such as SHA256, was included in the GitHub Releases.

This would enable me to automatically download the latest version of WinGet in [SandboxTest script](https://github.com/microsoft/winget-pkgs/pull/827).

It would be also good to follow some kind of pattern, such as [the one from `goreleaser`](https://goreleaser.com/customization/checksum/).

```sh-session
$ curl -L https://github.com/goreleaser/goreleaser/releases/download/v0.143.0/goreleaser_checksums.txt
0920d8b6be4be09744e9263be755965dc8a1df2318d6e8f68805990eb64f404d  goreleaser_armv6.deb
0b713827a2c0e21238a211899e6eb81f23c2dc7c9b39ecb426b06ed6efbce568  goreleaser_Darwin_x86_64.tar.gz
```

**Comment by denelon** [comment]
Great idea!

**Comment by felipecrs** [comment]
If this [feature suggestion](https://github.com/cli/cli/issues/1711) gets implemented on the `gh` , this change would be extremely easy.

**Comment by quangkieu** [comment]
I think this should also need to github itself provide checksum on the release file blob as more solutions now using github, Microsoft store as central distribution channels. So each project wouldn't need to reimplement or manually provide it.

**Comment by felipecrs** [comment]
> I think this should also need to github itself provide checksum on the release file blob as more solutions now using github, Microsoft store as central distribution channels. So each project wouldn't need to reimplement or manually provide it.

Of course. This is a very old feature request that GitHub has, we can assume they won't implement.

**Comment by denelon** [comment]
We're now including the SHA256 in our releases.
