### ISSUE TITLE
Officially support downloading signed appx packages from the Store for distribution via own website

### ISSUE THREAD

**Issue by benstevens48** [microsoft/winget-cli#578]
# Description of the new feature/enhancement
Presumably, in order to install apps from the Store, winget uses a publicly accessible API to download the signed app packages. This proposal is that the API should be officially documented. The API should include the ability to download the latest signed packages from specified package flights (as well as the unlighted version), and possibly also specified package versions.

The use-case is for developers to be able to distribute the signed app packages via their own website. Crucially, this would allow developers to offer old versions of apps or different branches such as LTS, current and beta, by creating an AppInstaller file and uploading the packages to their own website. (Currently there is no way to do this with the Store, except by collecting a limited number of users email addresses to add to a package flight, which is impractical). This is especially useful for apps with addon purchases, since it is very difficult (currently) to think of a way of distributing an app outside the Store while maintaining access to addon purchases. The Store would still receive a cut of addon purchases as they would continue to work in the normal way.

Ideally there would be an even more friendly way to download the packages and create an AppInstaller file, but the API would be a first step.

For further discussion on this issue, please see <https://github.com/microsoft/ProjectReunion/issues/39>, and also let me know if anything in their warrants a new issue here. Also, if the idea of being able to install old versions of apps (in a user-friendly way) is being addressed via some other means, please let me know, and then maybe this issue is obsolete. 

# Proposed technical implementation details (optional)
This is actually already possible, it's just not officially supported - see the comment here <https://github.com/microsoft/ProjectReunion/issues/39#issuecomment-631687219>.

Ideally, an app installed via an AppInstaller file outside the Store would not be automatically upgraded via the Store. However, this can be worked around (somewhat hackishly) by ensuring versions intended to be installed outside the Store have a very large package version number, so the unflighted package version number will always be lower.

**Comment by sammiie** [comment]
1. Microsoft Store API Integration:

Implement an API that allows website owners to interact with the Microsoft Store to search for, retrieve information about, and request downloads of Appx packages. Ensure that this API is secure and well-documented.
2. User Authentication and Authorization:

Create a user authentication system that website owners can integrate into their websites. Users must sign in to their Microsoft accounts, and the API should support OAuth 2.0 or similar protocols for secure authorization.
3. Package Discovery:

Develop methods within the API that enable website owners to discover Appx packages available on the Microsoft Store. Implement search and filtering options to help users find the apps they need.
4. Package Details and Metadata:

Provide endpoints to access detailed information about Appx packages, including descriptions, screenshots, release notes, and digital signatures. This information is crucial for users to make informed decisions.
5. Download Request and Verification:

Enable website owners to initiate download requests for selected Appx packages through the API. Implement mechanisms to verify the digital signatures of downloaded packages to ensure integrity.
6. Secure Download Links:

Generate secure, time-limited download links for Appx packages. These links should only be accessible to authorized users who have signed in and obtained proper permissions.
7. Rate Limiting and Throttling:

Implement rate limiting and throttling mechanisms to prevent abuse and ensure fair usage of the API. Define usage quotas based on subscription tiers or access levels.
8. Licensing and Legal Compliance:

Incorporate license validation mechanisms to ensure that website owners comply with Microsoft Store licensing agreements when distributing Appx packages.
9. Developer Portal Updates:

Enhance the Microsoft Store developer portal to include sections for managing API access, generating API keys, configuring permissions, and monitoring usage.
10. Documentation and SDKs:
- Create comprehensive documentation that covers API endpoints, authentication flows, usage examples, and best practices for integrating the Microsoft Store API into websites. Provide SDKs and code samples for popular web development frameworks.

11. Security Measures:
- Implement security measures such as HTTPS for all API endpoints, data encryption, input validation, and strong authentication protocols to protect sensitive user data and package integrity.

12. Monitoring and Analytics:
- Integrate monitoring and analytics tools into the API to track usage, detect anomalies, and generate reports on download statistics, user engagement, and security incidents.

13. Testing Environments:
- Set up sandbox or testing environments where website owners can experiment with the API without affecting production systems. Provide clear instructions for testing procedures.

14. Support and Issue Tracking:
- Establish a support system for website owners, including ticketing systems and forums where they can seek assistance, report issues, and collaborate with other developers.

15. Compliance Checks:
- Regularly perform compliance checks and security audits to ensure that both the API and websites using it adhere to Microsoft Store policies and legal requirements.

16. Regular Updates:
- Commit to a regular update schedule for the API, addressing bug fixes, security patches, and feature enhancements. Maintain backward compatibility to minimize disruptions for website owners.

By following these technical implementation details, Microsoft can provide a robust and secure platform for website owners to officially support downloading signed Appx packages from the Microsoft Store, fostering a thriving ecosystem of Windows app distribution.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/winget-cli/issues/578#event-13383463152

@denelon, where is this documented?
