### ISSUE TITLE
No UnInstaller command available

### ISSUE THREAD

**Issue by evilprince2009** [microsoft/winget-cli#592]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

Till date winget provides `install` command for installing packages from repository. But I see no `uninstall` or `remove` command to remove installed packages. Isn't it a good idea to add a `uninstall` or `remove` command for removing packages from command line rather than doing it manually ?

**Comment by denelon** [comment]
Duplicate of #121

**Comment by keenbowl3009** [comment]
> Duplicate of #121

Is that the one issue where we're supposed to dump all the "sloppy winget uninstall is broken" types of bugs?

**Comment by EqualDust** [comment]
Close all dupes, pretend the feature is implemented = microsoft software product.
