### ISSUE TITLE
Installation method using Powershell Gallery or MSI package

### ISSUE THREAD

**Issue by thenecroscope** [microsoft/winget-cli#593]
I've read the template, before posting.
Could you please provide a method to be able to install this tool from Powershell either using the powershell gallery if possible or an MSI package?

The problem I have is I'm not able to install any of the nice new tooling as its all hooked up to the Windows Store. In the environment I'm in, Im not able to use MS store, which blocks me from installing these nice new shiny tools :)

Many thanks,

**Comment by denelon** [comment]
Are you not able to follow the "Manually Update" process on the main README.md?

**Comment by thenecroscope** [comment]
Hi, thanks for getting to me. I'm not able to install appxbundles either. 
Compiling route is not really good either. 
Anything else I can try?

thanks

**Comment by denelon** [comment]
Is the store blocked by policy or the version of Windows 10 you're on? Can you share a bit more detail about your environment?

**Comment by thenecroscope** [comment]
Thanks for getting back to me.

Its blocked by Group Policy as I'm working in quite a large enterprise environment and store is blocked unfortunately.
I'm working on a combination of Servers 2016 and Server 2019. I have admin rights to the servers

**Comment by denelon** [comment]
Can you download the package to the machine and install it with:
`add-appxpackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle`

**Comment by thenecroscope** [comment]
Thanks! No luck I'm afraid.

I tried to run this on Windows 2012 R2 machine and I got the following


Add-AppxPackage : Deployment failed with HRESULT: 0x80080204, The Appx package's manifest is invalid.
error 0xC00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 518, Column 15, Reason: '125' violates enumeration constraint of '100 120 140 150 160 180
The attribute 'Scale' with value '125' failed to parse.
NOTE: For additional information, look for [ActivityId] 77336212-87eb-0006-6d41-7377eb87d601 in the Event Log or use the command line Get-AppxLog -ActivityID 77336212-87eb-0006-6d41-7377eb8
At line:1 char:1
+ Add-AppxPackage .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbun ...

**Comment by sharpninja** [comment]
Windows 2012-R2 is Windows 8.1 on steroids, it's not compatible.

**Comment by JohnMcPMS** [comment]
Our current release vehicle requires Windows 10.  If the ask is "Create a release that functions on older versions of Windows", we have tried to keep that as a possibility, but I don't believe we have any plans right now to move forward on it.

**Comment by denelon** [comment]
We've added the Repair-WinGetPackageManager to the Microsoft.WinGet.Client PowerShell module.
