### ISSUE TITLE
Installation stuck after "package found" stage with high cpu usage

### ISSUE THREAD

**Issue by OranShuster** [microsoft/winget-cli#599]
# Brief description of your issue
After successfully installing multiple programs using `winget`, it's now stuck when installing `Google.Chrome` after the `Found Google Chrome [Google.Chrome]`
Looking at task manager i can see that `Windows package manager client` is taking about 25% cpu (out of 6 logical cores)

# Steps to reproduce
1. run `winget install google.chrome` in terminal

# Expected behavior

Google chrome should be downloaded and installed

# Actual behavior
`winget` is completely stuck (let it run for 1+ hours)

# Environment

```none
Windows Package Manager v0.2.2521 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.508
Package: Microsoft.DesktopAppInstaller v1.11.2521.0
```

**Comment by peterlewis** [comment]
Yup, it appears that something ain't right with it, at the mo. [This has also been reported in the winget-pkgs repo](https://github.com/microsoft/winget-pkgs/issues/4021), just to let you know! 👍

**Comment by EddyBeaupre** [comment]
Same issue for me. Can't install anything.

**Comment by Bo-Fone** [comment]
Same issue. Completely stuck.

**Comment by ygorlazaro** [comment]
Seems I solved running `winget source update`.

**Comment by denelon** [comment]
The rebuild has finished. the problem appears to be resolved. You may need to manually refresh your cache `winget source update`. Let us know if you're still having trouble.

**Comment by dflo** [comment]
Was fixed last night, but seems to be broken again this morning even after manually refreshing cache with `winget source update`
![image](https://user-images.githubusercontent.com/5124106/95604412-2cfc6580-0a1d-11eb-88e2-6acb38661eda.png)
