### ISSUE TITLE
OpenSSL link doesn't work

### ISSUE THREAD

**Issue by legionaryu** [microsoft/winget-cli#603]
# Brief description of your issue
I was trying to install OpenSSH, but winget fails to download it. The reason is that the link that winget uses is broken ([https://slproweb.com/download/Win64OpenSSL_Light-1_1_1g.msi](https://slproweb.com/download/Win64OpenSSL_Light-1_1_1g.msi)) the right one is this [https://slproweb.com/download/Win64OpenSSL_Light-1_1_1h.msi](https://slproweb.com/download/Win64OpenSSL_Light-1_1_1h.msi)

# Steps to reproduce
winget install openssh

# Expected behavior
OpenSSH installed

# Actual behavior
```
Este aplicativo é licenciado para você pelo proprietário.
A Microsoft não é responsável por, nem concede licenças a pacotes de terceiros.
Downloading https://slproweb.com/download/Win64OpenSSL_Light-1_1_1g.msi
Ocorreu um erro inesperado ao executar o comando:
Download request status is not success.
0x80190194 : No encontrado (404).
```

# Environment
```none
[winget --info]
Windows Package Manager v0.2.2521 Visualização
Copyright (c) Microsoft Corporation. Todos os direitos reservados.

Windows: Windows.Desktop v10.0.19041.508
Pacote: Microsoft.DesktopAppInstaller v1.11.2521.0

Links
------------------------------------------------------------
Política de Privacidade https://aka.ms/winget-privacy
Contrato de Licença     https://aka.ms/winget-license
Avisos de Terceiros     https://aka.ms/winget-3rdPartyNotice
Home page               https://aka.ms/winget
```

**Comment by megamorf** [comment]
@egionaryu Thanks for reporting your issue. However, this repository is about the actual winget cli rather than its packages. To report problems with packages please file an issue here https://github.com/microsoft/winget-pkgs/issues.

PS: In your description you mentioned OpenSSH - I assume you meant to write OpenSSL (that matches the title and URLs).
