### ISSUE TITLE
Requesting to add package reposotories

### ISSUE THREAD

**Issue by Krrishdhaneja** [microsoft/winget-cli#605]
# Description of the new feature/enhancement
My feature request is that can the winget team add Arch user repo and debian repo to winget. If yes then please add it.

**Comment by 3rikk** [comment]
the arch user repo and the debian repo both have linux apps for the respective distrobutions, and they wont work on windows.
If you want to install them you will have to either install that linux distro or use wsl if it exists for the distro you want. IMO it wouldnt make sense to have winget be able to install stuff onto WSL installations either. You can already type "wsl sudo apt install *package*" (or "wsl sudo pacman -S *package* for if you have arch WSL)  and then "wsl *package*" to run it without entering the wsl prompt.
