### ISSUE TITLE
Is winget pre-installed in the latest windows 10 update now?

### ISSUE THREAD

**Issue by oxygen-dioxide** [microsoft/winget-cli#612]
My application depends on some third-party applications. I'm going to write a bat script to install the dependencies automatically. Users (using the latest version of windows 10) can install the dependencies with a simple double-click. However, if users don't have winget pre-installed, they will have to manually download winget, which reduces the user experience. So I want to know if winget is pre-installed in the latest windows 10 update now.

**Comment by jedieaston** [comment]
It is not available yet, as winget is still in pre-release. It's scheduled to be available in [Spring of 2021](https://github.com/microsoft/winget-cli/blob/master/doc/windows-package-manager-v1-roadmap.md), and will be presumably offered as a update to the App Installer in the Microsoft Store.

You may be able to write a PowerShell script to grab the manifests you want out of the repository and install them manually (I did this the other day), but it's a bit more work.

**Comment by oxygen-dioxide** [comment]
Thanks. I want to keep this issue open to track win10 updates until winget is installed in most computers.

**Comment by oxygen-dioxide** [comment]
Besides, I hope that we can find (winget （App Installer）)[https://www.microsoft.com/en-us/p/app-installer/9nblggh4nns1] on microsoft store by searching "winget", so that I can tell my users to download winget from microsoft store. Now I can only find some games, shirts and hats on microsoft store by searching "winget".

**Comment by denelon** [comment]
@oxygen-dioxide we plan on adding the "winget" keyword to the search terms for the store to land on the App Installer page. We will also need to update the documentation to reflect the inclusion of the Windows Package Manager at that time :smile:

**Comment by Burnsedia** [comment]
wow, windows finally has a basic OS feature that Linux and BSD have had since the 80s and 90s!!

**Comment by Masamune3210** [comment]
What is the point in coming in here just to bash on things.......

**Comment by Burnsedia** [comment]
I was generally impressed Microsoft doesn't have a good reputation among tech enthusiasts. I was just trying to be funny.

**Comment by Masamune3210** [comment]
I apologize if my idea was incorrect of your intentions. Unfortunately, people love to come in these issues just to whine a lot, so I assumed.

**Comment by Burnsedia** [comment]
I understand I am not a big Windows fan; I have not used Windows as my
Daily Driver since Windows 7, and I have Been an Arch Linux and MacOS in
VMs user since 2015. I have a Windows 10 and 11 VM for College and some
work. MacOS VM for IOS development is just my Arch Linux Setup.
