### ISSUE TITLE
Can't run winget as a admin

### ISSUE THREAD

**Issue by Jordan-Mesches** [microsoft/winget-cli#637]
# Brief description of your issue

I'm trying to avoid the UAC prompt whilst downloading a package, so I open a elevated terminal and run _winget_

However I get the following message _The system cannot execute the specified program._

But note that it works perfectly fine when it's just a normal terminal.
# Steps to reproduce

Open an elevated terminal and run winget?
# Expected behavior
Winget works normally, except I don't get any UAC prompts when installing

# Actual behavior
I get the following output _The system cannot execute the specified program._

# Environment

```none
[winget --info]
Windows Package Manager v0.2.2521 Preview
Windows: Windows.Desktop v10.0.19041.572
Package: Microsoft.DesktopAppInstaller v1.11.2521.0


```

**Comment by denelon** [comment]
Are you running this in CMD or Windows Terminal? I'm not able to reproduce. Incidentally, there is a newer version of the package manager available. (I don't think it would have any impact on this issue).

**Comment by Jordan-Mesches** [comment]
> Are you running this in CMD or Windows Terminal? I'm not able to reproduce. Incidentally, there is a newer version of the package manager available. (I don't think it would have any impact on this issue).

I'm running it in a elevated cmd, I do have a very rowdy antivirus installed, so it's very possible that could be the issue

**Comment by denelon** [comment]
@Jordan-Mesches, I don't have any other ideas. Can you temporarily disable the anti-virus and try the installer again? If you don't mind, which anti-virus and settings are you using? It might be good to add to our F.A.Q.s

**Comment by trollyanov** [comment]
Installed winget for a user without admin rights. 
I run cmd (run as admin) or powershell (run as admin). 
Winget was not found

**Comment by DrewNaylor** [comment]
Ran into this problem myself on some (but not all) installations of Windows 10 across various versions, including I think 2004 and 1909. This seems to affect APPX/MSIX packages in general so it's not just a winget thing and may in fact be a recent Windows bug, as it didn't start happening until a few months ago and I ran into the same issue with Windows Terminal. Not sure if the original poster is elevating from an account with Administrator permissions or not, but I'm not and winget only works when I elevate from that account.

**Comment by denelon** [comment]
I reopened the bug. This might be an external issue as suggested, but we'll keep this open to remind ourselves to take a look.

**Comment by ukedk** [comment]
on Win10 20H2 and winget v0.3.11201 same issue: on elevated cmd  "The system cannot execute the specified program."
It would be nice if there would be a self compiled exe  without the appxbundle but I am afraid that this is probably not technically possible. If I can provide someone with more information.....thx.

**Comment by ecovio1** [comment]
@ukedk 
winget has nothing to do here,  It is the same reason you can't run MSIX packages from SSH logins. all store apps/MSIX packages require `NT Authority\Interactive ` login. 

after several years, MSIX is still a no-op half backed thing for usecases like this.
you can tell MSIX devs to enable to not require `NT Authority\Interactive ` login. 

@denelon ,
since the issue is open and AFAIK winget team is not responsible for this, is winget team considering for a MSI release or MSIX is gonna mature up ?

**Comment by denelon** [comment]
I added the "Area-External" label.

**Comment by denelon** [comment]
@ecovio1 let's try to keep things constructive here. I understand the frustration regarding a highly desired feature. I just went and put my 👍 on both of those issues. Anyone else running into this challenge from the perspective of installing packages with the Windows Package Manager might stumble on this issue, and be motivated to show their support as well.

**Comment by ukedk** [comment]
@ecovio1 thanks for the explanation of the cause. Unfortunately, so much is half-baked (the youth will call it exciting ;)). Perhaps it would be useful to revise the readme, as this is misleading (...When running winget in an Administrator Command Prompt, you will not see elevation prompts) .  Due to lack of developer knowledge: probably it is too elaborate to leave the NT Authority\Interactive option out ? I have not seen any compilates outside the official repsiotry so far....

**Comment by jorgytim** [comment]
We have another "discussion" open that relates to what everyone is getting at here. Ultimately for this to be useful for anything outside of user-managed personal machines, it is an absolute requirement for winget to be deployable to the system context (i.e. msi or exe, binaries installed to a protected folder like \program files or \windows\system32). Right now we get that using the MSIX delivery mechanism is the newer method and it makes this manageable via the MS Store, but it makes it completely unusable for businesses entirely. 

My testing thus far with Winget has me hopeful on how useful this tool can be for installing and updating applications by simply updating manifests in our eventual private repository. Right now though, this tooling is entirely run in the user context, therefore completely unusable as it requires every user on a machine to have this installed, and then requires them be granted administrative permissions on the machine to execute the installers defined in the app manifests. Given today's security landscape and the various breaches in the past 6 months alone, I see many business partners locking things down and controlling administrative access much more tightly, so having this tooling available under the "system" context is going to be critical towards gaining adoption beyond home users and hobbyists.

Here is a link to our other discussion regarding this:
https://github.com/microsoft/winget-cli/discussions/962

**Comment by Simpuhl** [comment]
I can run winget as a user but not as admin for some reason

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/discussions/962#discussioncomment-736278

**Comment by rothgecw** [comment]
We have an automation tool where I work that I'd hoped to use WinGet to help manage our lab workstations. I encountered the same problem, but actually have a solution (at least for systems 20H2 and higher that have WinGet installed).

Windows Apps are actually stored under `C:\Program Files\WindowsApps`. In the case of WinGet, I am calling it using:

`"C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.16.12653.0_x64__8wekyb3d8bbwe\AppInstallerCLI.exe" upgrade --all -h --accept-package-agreements --accept-source-agreements`

Let me know if you have any questions or find this doesn't work for you. This is now a game changer for us!

**Comment by raShMan777** [comment]
Given you have access to the folder `C:\Program Files\WindowsApps` you can also create aliases as a workaround:

1. Look for the folder with the current version beginning with Microsoft.DesktopAppInstaller with your system architecture (e.g. x64): `C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.16.12701.0_x64__8wekyb3d8bbwe`
2. open an elevated PowerShell and open your profile: `notepad $PROFILE`
3. insert these two aliases while correcting the path (or create whatever alias[es] you want):
`Set-Alias -Name winget.exe -Value "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.16.12701.0_x64__8wekyb3d8bbwe\AppInstallerCLI.exe" -Scope "Local"
Set-Alias -Name winget -Value "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.16.12701.0_x64__8wekyb3d8bbwe\AppInstallerCLI.exe" -Scope "Local"`
4. open a new elevated PowerShell and voilá:
`❯ winget.exe
Windows Package Manager v1.1.0
Copyright (c) Microsoft Corporation. All rights reserved.

The winget command line utility enables installing applications and other packages from the command line.

usage: winget [<command>] [<options>]

…
…
…`

**Comment by haydenhartland** [comment]
As of 1.17 calling AppInstallerCLI directly doesn't do anything at least on Windows 11. Has anyone figured out how to call AppInstallerCLI directly or indirectly running 1.17 on Windows 11 from a System user/session?

**Comment by rothgecw** [comment]
> 

Is the AppInstallerCLI.exe binary simply not there, or is the path just changed? One thing I considered doing to avoid the versioning issue is to use the "pushd" command"

```
pushd "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe"
AppInstallerCLI.exe --version
```

Give this a try using PSExec. Might also get a directory listing just to see what's there:

`psexec -s -i cmd.exe
`
I'm interested to know if something significant changed - I'm still on 1.16 myself. Cheers!

**Comment by haydenhartland** [comment]
Does 1.16 work on Windows 11?

C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.3131.0_x64__8wekyb3d8bbwe\AppInstallerCLI.exe is where it is located. It is also strange that the old version directories and several files are on that machine in 1.0.42251.0 but the CLI is not in there. They should clean up that crapola... Any way if someone knows what changed or why it doesn't work with this new release or Windows 11 in general I appreciate your insights.

**Comment by rothgecw** [comment]
I'm on Windows 11, and 1.16 is working. What are the commands you're using? Are you getting any errors? When running as "nt authority\system", what do you get running `C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.3131.0_x64__8wekyb3d8bbwe\AppInstallerCLI.exe --version`? Just trying to make sense of the problem you're seeing. Cheers!

**Comment by haydenhartland** [comment]
I have tried several commands

C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.3131.0_x64__8wekyb3d8bbwe\AppInstallerCLI.exe --version

C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.3131.0_x64__8wekyb3d8bbwe\AppInstallerCLI.exe list --accept-source-agreements

All commands I run simply return to the command prompt. If I run it from the user context it is fine but if I run it from the system I get nothing at all - no feedback nothing

**Comment by rothgecw** [comment]
User context...? How did you manage to run C:\Program Files\...\ApInstallerCLI.exe as a user? The permissions on the WindowsApps directory do not permit it. How are you running your commands as system? Just trying to get context. Thanks!

**Comment by haydenhartland** [comment]
Sorry to be clear...

Running CMD as a Local Admin I can successfully use winget

Running a CMD from psexec -i -s cmd and using the full source path I get nothing

**Comment by rothgecw** [comment]
Are you using the full path when operating as local admin? If not, where is winget getting called from (`where winget`)?
I'm curious what is in the actual winget directory at that full source path. Have you tried calling dir on "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.3131.0_x64__8wekyb3d8bbwe"?

**Comment by haydenhartland** [comment]
"winget" is getting called from C:\User\...\AppData\Local\Microsoft\WindowsApps\ when I run it as a local user

And the only location of AppInstallerCLI.exe is in:
C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.3131.0_x64__8wekyb3d8bbwe\

There is another Microsoft.DesktopAppInstaller_*_8wekyb3d8bbwe\ directory but it does not contain the AppInstallerCLI.exe file in it

If I run dir on C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.3131.0_x64__8wekyb3d8bbwe\
 it has a bunch of stuff in it including the AppInstallerCLI.exe file although I have not run a diff against the two directories

**Comment by haydenhartland** [comment]
If I pushd C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.3131.0_x64__8wekyb3d8bbwe\ from a local Admin account and run AppInstallerCLI I get the same result as if I simply ran winget (All good there)

If I run pushd C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.3131.0_x64__8wekyb3d8bbwe\ from a system account (psexec -i -s cmd) then when I run AppInstallerCLI the output from the command is nothing just returns to command prompt

If I run powershell and then try to run the AppInstallerCLI as a system user I get AppInstallerCLI.exe is not a recognized blah blah blah

Keep in mind this is only happening when I try to run this 1.17 version so something had to have changed

**Comment by rothgecw** [comment]
Yeah, sounds like something changed. I'm on Win 11 and 1.16 of winget at work, but I'll check what I have at home and test it out too. Are you on a dev branch of Windows?

What I find really confusing is the versioning. If I run `winget -v` from any user account on my system, I get "v1.1.12986", which partly matches the versioning in the path "Microsoft.DesktopAppInstaller_1.16.12986.0_x64__8wekyb3d8bbwe". But where'd the "1.16." come from instead of the "1.1."? Further, if you're quick enough with Task Manager, you can find the process "AppInstallerCLI.exe" appear briefly (indeed in the full path), but getting properties for it shows both file and product versions "1.16.2110.25006", and yet if I run `AppInstallerCLI.exe -v` from system, I only get "v1.1.0". Huh?!

**Comment by haydenhartland** [comment]
I am running a Preview build of Windows...

If I run winget -v from a user account on that machine I get "v1.2.3131-preview"

I will look into attaching to the AppInstallerCLI.exe to see if I can grab the version info when I run winget as a user

Super frustrating...

**Comment by haydenhartland** [comment]
It is interesting that Local Service has Read&Execute rights and System has all permissions for C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.3131.0_x64__8wekyb3d8bbwe\ 

When I look at the process details I see the following:
![image](https://user-images.githubusercontent.com/74060258/145471814-60eafb0f-0345-481a-ab16-3cbb3dc7e8af.png)

Not sure what the problem is but seems like a defect to me...

**Comment by denelon** [comment]
The Windows Package Manager is delivered with the App Installer. Our build system typically uses the least significant digits for identifying builds. If you run `winget --info` you should see in the output which version of Windows Package Manager, App Installer, and Windows. There are cases where builds with changes targeted to App Installer also update the version of the Windows Package Manager. I know this is super confusing, but it's a necessary part of how we build the product today.

As the App Installer is delivered as an MSIX, there are boundaries for how the app is registered and used. This is why the remote calls and administrator calls behave differently than for other programs. This is an intentional part of the security boundaries for running MSIX packages. We are still evaluating remote execution and administrator execution scenarios.

**Comment by Simpuhl** [comment]
So what is the best way to run winget as system/admin using Intune?

**Comment by denelon** [comment]
To be honest, I'm not sure if an intentional change was made in this case. There are several teams working on different product areas. If I knew, I would share the information. We're looking at several scenarios for remote execution. Yes, we are working with the Intune team on a solution to replace the Store for Business. More information will be coming as we continue to work on that solution. I know how critical it is for administrators to be able to configure and manage their environments. I certainly see how powerful this tool can be in that space. I'm very excited about many of the problems we can help solve here.

**Comment by JulianGodd** [comment]
Without system execution access this product becomes largely useless for anyone but local admins and then it is a minor convenience where you wonder why you didn’t just install Linux

**Comment by gathulb** [comment]
This could be a great tool and game changer for Windows in so many ways. A unified deployment and package manager. Definitely needs an open way to remotely manage for admins and integrators. Otherwise someone will just branch it and at some point MSFT will buy them.

**Comment by chhetriabi** [comment]
> We have an automation tool where I work that I'd hoped to use WinGet to help manage our lab workstations. I encountered the same problem, but actually have a solution (at least for systems 20H2 and higher that have WinGet installed).
> 
> Windows Apps are actually stored under `C:\Program Files\WindowsApps`. In the case of WinGet, I am calling it using:
> 
> `"C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.16.12653.0_x64__8wekyb3d8bbwe\AppInstallerCLI.exe" upgrade --all -h --accept-package-agreements --accept-source-agreements`
> 
> Let me know if you have any questions or find this doesn't work for you. This is now a game changer for us!
> 
> Additional Clarifications:
> 
> As far as I know this only works under the System account. Windows Apps are something I don't quite understand, but as far as I can tell, standard user accounts can only access those directories as part of the Modern Apps framework, and administrators only browse that directory level. The permissions are... odd. I'm using the Windows File Manager since I can run it as admin and use it to pull up properties. I suppose you could do the same using the built-in Administrator account with File Explorer.
> 
> If you use the command where winget, you'll find it located under your `%localappdata%\Microsoft\WindowsApps\winget.exe`, but if you browse that WindowsApps directory, it's full of 0-byte files. These are some sort of link (hard links I think). Using junction.exe from SysInternals, it reports this file as `"UNKNOWN MICROSOFT REPARSE POINT"`. But my thought is that these point to provisioned APPX packages. As a user, I believe you can only get to the actual `C:\Program Files\WindowApps` by calling the link created under your profile's WindowsApps directory. But the System profile lacks the WindowsApps directory, hence the reason you can't simply call "winget". However, System does have full access to `C:\Program Files\WindowApps`, thus it works.

@rothgecw Thanks so much for the explanation and sharing your workaround for it.

However, When I run this under NT Authority\System I get `Unexpected token 'upgrade' in expression or statement`
Am I missing out something ?

**Comment by haydenhartland** [comment]
As indicated earlier if you are on 1.16 or below this solution works but if
you upgrade Winget to .17 or higher it no longer works to run winget in the
context of a System account.

As for your question the 'upgrade' token I can't help you there.

**Comment by chhetriabi** [comment]
> 

hmm interesting. I did check the version after your initial response and was on 1.16 and I am actually still on 1.16 and that actually does not work for me for some reason.

**Comment by Romanitho** [comment]
It seems that AppInstallerCLI.exe was replaced by winget.exe 😅

**Comment by haydenhartland** [comment]
Yes but any release after .16 will not support a direct call to
AppInstallerCLI.exe and any call to winget.exe as a system user will fail
to execute.

**Comment by Romanitho** [comment]
I mean "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.*_x64__8wekyb3d8bbwe\winget.exe"

**Comment by haydenhartland** [comment]
Are you able to run that as a system user cause I am not... Try running it
as a system user:

psexec -i -s cmd

Then try to run it

**Comment by Romanitho** [comment]
![image](https://user-images.githubusercontent.com/96626929/147365548-e7ee41f5-bffc-47c2-be96-15e4a62760e1.png)

**Comment by haydenhartland** [comment]
[image: image.png]

**Comment by Romanitho** [comment]
![image](https://user-images.githubusercontent.com/96626929/147366048-19c84933-2789-4268-9404-75f30d595c13.png)

**Comment by haydenhartland** [comment]
Mine simply returns with no output are you on a 32 or 64 bit machine?

**Comment by haydenhartland** [comment]
The directory list is the same output as yours

**Comment by Romanitho** [comment]
> Mine simply returns with no output are you on a 32 or 64 bit machine?

64

**Comment by haydenhartland** [comment]
Not sure why yours works and mine doesn't. It works fine for me on earlier version but not latest...

**Comment by 29039** [comment]
I ran into this issue today.

I think that the problem was that I was logged in as a Standard User, and I had run powershell.exe as an Admin user (different username) and that Admin user had not been logged into the Desktop before and therefore never had the opportunity to get winget from the Windows Store.

I think that overall having winget as part of the Microsoft Store & per-user installation is an absolutely horrible idea for a use-case like this, and it would be better to have it baked into Windows itself.

I usually use Chocolatey, which is awesome. But unfortunately there is a particular package which is only on winget (or manual download).

**Comment by Romanitho** [comment]
Run as system (if you use sccm or intune for example, or via a scheduled
task)

**Comment by Romanitho** [comment]
I have started to work on a process to run everyday to update apps as system and notify connected user
https://github.com/Romanitho/Winget-autoupdate
i'm not a dev, but it works 😅

**Comment by KrisAtKingston** [comment]
Winget would be such a usefull tool for system deployment IF it was able to run as system.

Having it Per user based seems such a missed opertunity.

**Comment by denelon** [comment]
We're working on an In Process COM API the work started with [this PR](https://github.com/microsoft/winget-cli/pull/2035).

It was mentioned in [this release](https://github.com/microsoft/winget-cli/releases/tag/v1.3.1251-preview).

**Comment by cgerke** [comment]
> We have another "discussion" open that relates to what everyone is getting at here. Ultimately for this to be useful for anything outside of user-managed personal machines, it is an absolute requirement for winget to be deployable to the system context (i.e. msi or exe, binaries installed to a protected folder like \program files or \windows\system32). Right now we get that using the MSIX delivery mechanism is the newer method and it makes this manageable via the MS Store, but it makes it completely unusable for businesses entirely.
> 
> My testing thus far with Winget has me hopeful on how useful this tool can be for installing and updating applications by simply updating manifests in our eventual private repository. Right now though, this tooling is entirely run in the user context, therefore completely unusable as it requires every user on a machine to have this installed, and then requires them be granted administrative permissions on the machine to execute the installers defined in the app manifests. Given today's security landscape and the various breaches in the past 6 months alone, I see many business partners locking things down and controlling administrative access much more tightly, so having this tooling available under the "system" context is going to be critical towards gaining adoption beyond home users and hobbyists.
> 
> Here is a link to our other discussion regarding this: #962

Some interesting stats on the manifests doing a search of InstallerType across the git repo.

11940 results in 11134 files InstallerType: nullsoft (exe)
6318 results in 4855 files InstallerType: wix (msi)
5931 results in 5387 files InstallerType: inno
5664 results in 3754 files InstallerType: exe
2713 results in 1974 files InstallerType: msi
1004 results in 637 files InstallerType: burn (exe)
811 results in 688 files InstallerType: portable
448 results in 290 files InstallerType: msix
225 results in 217 files InstallerType: zip

**Comment by aclondon** [comment]
Appreciate this is a slightly old topic, but if you are running winget using an elevated command prompt, such as:

**runas /user:localadmin cmd - this will not work.**

You need to use

**runas /noprofile /user:localadmin cmd**

A bit more details here https://superuser.com/questions/42537/is-there-any-sudo-command-for-windows
