### ISSUE TITLE
github​-​gh https:​//​github.com​/​cli​/​scoop​-​gh.git
scoop install gh

### ISSUE THREAD

**Issue by PuPe1408** [microsoft/winget-cli#642]
# Brief description of your issue

# Steps to reproduce

# Expected behavior

# Actual behavior

# Environment

```none
[winget --info]
Windows Package Manager version
Windows:

**Comment by denelon** [comment]
There isn't enough detail here for me to understand what the issue is.

**Comment by alannt777** [comment]
You can install GitHub CLI by `winget install gh`
