### ISSUE TITLE
Installed an app from Windows Store (source) but Winget Upgrade command downloads the update from Winget (source: Github)

### ISSUE THREAD

**Issue by hotcakex** [microsoft/winget-cli#643]
# Brief description of your issue

# Steps to reproduce

Installed Winget from Github (because I'm running Windows 10 20H2 Beta channel and it's not there by default).
I searched for Windows Terminal in Winget using (Winget Search) command.
installed Windows Terminal Preview using (Winget Install) command from Microsoft Store (source)
after 2 days there is a new update for Windows Terminal on Windows Store. I ran (Winget Upgrade) and it identified that there is a new version of Windows Terminal available, but on the source column it shows (Winget) instead of (Microsoft Store)

# Expected behavior

I was expecting (Winget Upgrade) command to correctly identify the source of the installed app and download the subsequent updates from the same source, not different source. If I download Windows Terminal from Microsoft Store using (Winget Install) command, (Winget Upgrade) command should update Windows Terminal from Microsoft Store.

# Actual behavior

(Winget upgrade) command downloads Windows Terminal from Github (Winget as source)

# Environment

```none
[winget --info]
Windows Package Manager v0.2.2941 Preview
Windows: Windows.Desktop v10.0.19042.630
Package: Microsoft.DesktopAppInstaller v1.11.2941.0

Any other software?
```
Nothing to be conflicting with Winget.

**Comment by hotcakex** [comment]
Did I have to use "Winget source update" before doing "Winget Upgrade" ?

**Comment by JohnMcPMS** [comment]
As `upgrade` is a work in progress, we don't yet have the local tracking for the source that a package was originally installed from.  This is coming sooner rather than later, but since it isn't there yet, the correlation is in source order.  So this isn't a bug, so much as a feature not yet implemented.

**Comment by hotcakex** [comment]
@JohnMcPMS Thanks for the explanation, I wasn't aware of that.
