### ISSUE TITLE
Cannot install AppxBundle!

### ISSUE THREAD

**Issue by pjhavariotis** [microsoft/winget-cli#647]
I'm trying to install `winget` via the AppxBundle and I'm getting the following error:

Add-AppxPackage -Path '.\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle'
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict validation.
Windows cannot install package Microsoft.DesktopAppInstaller_1.11.2941.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework
"Microsoft.VCLibs.140.00" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.27810.0,
along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs
Windows cannot install package Microsoft.DesktopAppInstaller_1.11.2941.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework
"Microsoft.VCLibs.140.00" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.27810.0,
along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs.140.00_14.0.23816.0_x86__8wekyb3d8bbwe
Microsoft.VCLibs.140.00_14.0.23816.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.24123.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.24123.0_x86__8wekyb3d8bbwe
Microsoft.VCLibs.140.00_14.0.26706.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.26706.0_x86__8wekyb3d8bbwe}
NOTE: For additional information, look for [ActivityId] 96e6a299-bf07-0002-ef60-e79607bfd601 in the Event Log or use the command line Get-AppPackageLog -ActivityID 96e6a299-bf07-0002-ef60-e79607bfd601
At line:1 char:1
+ Add-AppxPackage -Path '.\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\users\e36520... (1).appxbundle:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by JohnMcPMS** [comment]
You are missing some of the package dependencies necessary for installation of the package.  In this case you appear to have some older versions, but not the minimum required.  I'm not sure how you can acquire that one manually.  The next one you might have a problem with is the Desktop one, which you can find [here](https://docs.microsoft.com/en-us/troubleshoot/cpp/c-runtime-packages-desktop-bridge#how-to-install-and-update-desktop-framework-packages).

Depending on where you are trying to install it, you can also potentially just open the bundle (double click).  The version of the package that ships with Windows can then download those frameworks for you.

**Comment by denelon** [comment]
@pjhavariotis I hope this issue has been resolved for you. Feel free to re-open the issue if the suggestion above doesn't work.
