### ISSUE TITLE
ฉันกำลังแบ่งปัน 'last_log.doc' กับคุณจาก WPS Office

### ISSUE THREAD

**Issue by PuPe1408** [microsoft/winget-cli#651]
นี่คือลิงก์ไปยังไฟล์:

https://s.docworkspace.com/d/AM2ci0Xm551U-u-ajJunFA

แบ่งปันจาก WPS Office:
https://kso.page.link/wps

**Comment by denelon** [comment]
There isn't enough detail in the issue to help.
