### ISSUE TITLE
Task scheduler not working with WinGet

### ISSUE THREAD

**Issue by NBerlin** [microsoft/winget-cli#653]
# Brief description of your issue
When I try to set up a powershell script with WinGet in task scheduler it doesn't work and I get "Access denied". The script works if run normally. It also doesn't work if you skip the powershell script and try to run winget through task scheduler with cmd directly.

# Steps to reproduce

For example write a powershell script that just says "winget install vim" and try to run it through task scheduler. 
Or just try to run winget directly through task scheduler like this:
![image](https://user-images.githubusercontent.com/24526953/100336013-ee733800-2fd5-11eb-8a88-bebdfcb5f4ab.png)

# Expected behavior

For the program to download and install.

# Actual behavior

Installation fails with "Access denied" popup if using script or "Installer failed with exit code: 2" if run directly.

**Comment by megamorf** [comment]
The winget CLI is installed on a per-user basis. Is the account that you're running the scheduled job under the same as your regular user and is the job being run with the "Run with highest privileges" option?

**Comment by NBerlin** [comment]
> The winget CLI is installed on a per-user basis. Is the account that you're running the scheduled job under the same as your regular user and is the job being run with the "Run with highest privileges" option?
> 
> See #548.

Yes it's set to run as the same user account and with highest privileges. When I run the script normally it works without a problem, it seems to have something to do with how winget interacts with task scheduler.

**Comment by denelon** [comment]
I just noticed the error 2 from Vim is the same as #500 

Is this a duplicate?

Does the same thing happen with other packages when interacting with the task scheduler?

**Comment by yao-msft** [comment]
I just tried to create a new task for installing vim as described in repro steps. And it works fine. Does this issue still exist for you?
