### ISSUE TITLE
using install to update does not apear to be working

### ISSUE THREAD

**Issue by mikeysan** [microsoft/winget-cli#654]
# Brief description of your issue

According to the Github cli readme file, I should be able to run ``` winget install gh ``` in order to upgrade to a new version when available. This appears not to be the case. 

![image](https://user-images.githubusercontent.com/13338176/100358144-a3fdb580-2fed-11eb-94ff-8dd27d0989cd.png)

# Steps to reproduce

1. Open a Powershell terminal
2. type ``` winget install gh ```
3. type ``` gh --version ```
4. If you are notified that there is a new update, you may proceed to step 5
5. type ``` winget install gh ```
6. now type ``` gh --version ```

# Expected behavior

I expect that when i type gh --version in step 6, I will now have the latest version of the github cli tool

# Actual behavior
My current version remains the same and I get a message from gh telling me there is a new version available (which is annoying already but I believe an issue has been raise for that) 😄 

# Environment

```none
[winget --info]
Windows Package Manager v0.2.2941 Preview
Windows: Windows.Desktop v10.0.19042.630
Package: Microsoft.DesktopAppInstaller v1.11.2941.0

Any other software? None
```

**Comment by alannt777** [comment]
I was the one who added that to the GitHub CLI README

**Comment by alannt777** [comment]
@mikeysan  See https://github.com/cli/cli/pull/2272

**Comment by alannt777** [comment]
install command *is not* for upgrading. But the gh installer should have handled it itself

**Comment by LuanVSO** [comment]
i think is because there's a delay between when the gh cli says theres an update and the update actually being available on winget
check if winget got the newer version by:
```powershell
winget show gh
```

**Comment by alannt777** [comment]
@LuanVSO It was merged 15 hours ago microsoft/winget-pkgs#5037

**Comment by alannt777** [comment]
![Using install to update](https://user-images.githubusercontent.com/67918878/100529902-fcad9800-3211-11eb-932c-5fb02734855e.png)

---

![And it worked!](https://user-images.githubusercontent.com/67918878/100529916-0cc57780-3212-11eb-9f60-e5b05894db95.png)

**Comment by megamorf** [comment]
Hey @mikeysan, @alannt777 has provided a solution to your issue so please go ahead and close it. In addition, please note that package related issues don't belong to the winget-cli repo - instead they should be posted in [winget-pkgs](https://github.com/microsoft/winget-pkgs/issues).

**Comment by mikeysan** [comment]
Thanks for the info @megamorf I opened the issue here becasuse I didn't know where the problem stemmed from, but good to know. 
Thanks for resolving the issue @alannt777

**Comment by alannt777** [comment]
RESOLUTION: The README says to use `winget install gh` because the GitHub CLI installer will automatically remove the older version of the GitHub CLI.

Unfortunately when @mikeysan used `winget install gh`, the GitHub CLI manifest for v1.3.0 was not merged yet as pointed out by @LuanVSO
