### ISSUE TITLE
Examining ARP entries leads to winget crash

### ISSUE THREAD

**Issue by andrew-boyarshin** [microsoft/winget-cli#657]
# Brief description of your issue
Assertion fires at <https://github.com/microsoft/winget-cli/blob/92b3e73bb85a16e02a4c3044d6693a58ea9d6f5e/src/AppInstallerCommonCore/Registry.cpp#L15> when running `winget list` while iterating through entries in `Machine | x86`, registry hive attached to FH issue (reg file would probably not enough, given it's firing at REG_SZ read routine).

[Feedback Hub entry with logs and registry hive](https://aka.ms/AAago4t)

# Steps to reproduce
Run `winget list`.

# Expected behavior
Items fetched successfully.

# Actual behavior
```none
2020-12-2 14:17:49.625 [FAIL] C:\BA\237\s\external\pkg\src\AppInstallerCommonCore\Registry.cpp(15)\AppInstallerCLI.exe!00007FF78F575168: (caller: 00007FF78F574193) Exception(1) tid(f60)   8007139F The group or resource is not in the correct state to perform the requested operation.
```

# Environment
```none
WinGet, version [0.2.3162], activity [{47DA0524-D496-48FB-8800-1C7EAEF1FB22}]
OS: Windows.Desktop v10.0.20251.1
Command line Args: "C:\Users\Andrew\AppData\Local\Microsoft\WindowsApps\winget.exe" list
Package: Microsoft.DesktopAppInstaller v1.11.3162.0
```

**Comment by JohnMcPMS** [comment]
Thank you for the detailed bug report @andrew-boyarshin , it made it very easy to fix.
