### ISSUE TITLE
winget is not pre-installed on Windows App Installer.

### ISSUE THREAD

**Issue by leochoo** [microsoft/winget-cli#663]
`
The client is distributed within the App Installer package. While this package is pre-installed on Windows, the client will not be made generally available during the Preview period.`

Hmm.. No... I just downloaded Windows Terminal through Microsoft Store but it cannot run 'winget' command.
It says

    + CategoryInfo          : ObjectNotFound: (winget:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

What should I do?

**Comment by denelon** [comment]
You either need to be running a Windows Insider build, or join the Windows Package Managers insider program.

**Comment by wrosecrans** [comment]
Why is the App Store the encouraged installation method in the documentation if you can just install it without running a special OS build or seeking access to a special program by just installing it from the releases page here on GitHub?  Until it becomes a mainstream thing in the App Store, it's the least practical way for someone to use it.

At very least, the documentation currently has a link to the App Store _before_ the link to the prerequisite steps.  If you have to do those things first, it would be more obvious if the documentation started by talking about how to do the prerequisite steps before giving a link to the app store.

**Comment by lychichem** [comment]
> Why is the App Store the encouraged installation method in the documentation if you can just install it without running a special OS build or seeking access to a special program by just installing it from the releases page here on GitHub? Until it becomes a mainstream thing in the App Store, it's the least practical way for someone to use it.
> 
> At very least, the documentation currently has a link to the App Store _before_ the link to the prerequisite steps. If you have to do those things first, it would be more obvious if the documentation started by talking about how to do the prerequisite steps before giving a link to the app store.

![image](https://user-images.githubusercontent.com/9316590/103413639-70e2af00-4bb5-11eb-89be-5d2ced6cc4d8.png)
The MS team have written all you need to do in the readme. I wonder whether you really thoroughly read the readme, or English is not a language that you can fully understand.

**Comment by wintermute000** [comment]
Sorry but I signed up for the preview flight ring using the MSA I login as, over a week ago, and I'm still not getting winget via app store on two different PCs

**Comment by PushOrigin** [comment]
I am trying to get a future co-worker setup with winget. I signed him up for the Package Manager Insiders program on Monday. He got the email welcoming him but winget still isn't available. App Installer has not been updated via the store.

I used his work account, which is a Microsoft 365 account if that makes any difference. Please let me know how I can get winget through the store as recommended.

**Comment by limbusdev** [comment]
Same here. Default microsoft account. Signed up for the preview but nothing happending. Btw. - why isn't winget used to update winget?

**Comment by pvanberlo** [comment]
> Sorry but I signed up for the preview flight ring using the MSA I login as, over a week ago, and I'm still not getting winget via app store on two different PCs

Same - although it's been a few days for me. Got the confirmation e-mail I was added to the insider release, but the winget executable is nowhere to be found...

**Comment by denelon** [comment]
The "Windows Package Manager Insider" sign up form results in a request. We have to manually add your e-mail address to the flight group. That happens in batches. We generally try to get this done daily, but sometimes we may miss a day or two. After your address has truly been added to the flight group, the "App Installer" with the Windows Package Manager becomes available as an update from the Microsoft Store.

**Comment by Karl-WE** [comment]
@denelon I am seeing the following behaviour with the store based App Installer an suspect this is not intended.

App Installer is installed on a system. Searching for App Installer on the store, it shows up as if it is not already installed.
Basically a user could install it from store over and over again.
Affects all release builds if Windows 10, aka 20H2.

![image](https://user-images.githubusercontent.com/45657752/113140039-26aab180-9228-11eb-8fea-8bce1f5b251d.png)

**Comment by denelon** [comment]
@Karl-WE thanks for pointing this out. I'll see if I can get in touch with the right team to figure out what is causing this behavior.

**Comment by Karl-WE** [comment]
You're welcome.

**Comment by vietvudanh** [comment]
> 
> 
> The "Windows Package Manager Insider" sign up form results in a request. We have to manually add your e-mail address to the flight group. That happens in batches. We generally try to get this done daily, but sometimes we may miss a day or two. After your address has truly been added to the flight group, the "App Installer" with the Windows Package Manager becomes available as an update from the Microsoft Store.

I think this should be included in `readme` or the email? It is very confusing, since it did not stated anywhere in the guide, or the email about the this delayed time. I think everybody must think it's automatically.

**Comment by denelon** [comment]
@vietvudanh I'm not sure we're going to be able to change the template. I've been working through to see if that's possible. We're sorry for the confusion.

**Comment by vietvudanh** [comment]
@denelon yeah, the mail template might be hard to change. So what about in `readme.md`? Just a small note is enough.

**Comment by denelon** [comment]
@vietvudanh, I'll take a look and see if I can find a good place to put a small note 👍

**Comment by vietvudanh** [comment]
@denelon thank you for the quick change. I think it's much clearer now for new users.

**Comment by denelon** [comment]
@leochoo does the update to the README address your concern?

**Comment by Karl-WE** [comment]
> @denelon I am seeing the following behaviour with the store based App Installer and suspect this is not intended.
> 
> App Installer is installed on a system, listed in Settings > Apps Searching for App Installer on the Store, it shows up as if it is not installed.
> 
> Basically a user could install it from store over and over again.
> Affects all release builds of Windows 10, aka 20H2.
> 
> ![image](https://user-images.githubusercontent.com/45657752/113140039-26aab180-9228-11eb-8fea-8bce1f5b251d.png)

Hello @denelon I've noticed this has been closed. Do you have gain any insights about this related? issue. Thank you.

**Comment by denelon** [comment]
I hope the [troubleshooting guide](https://github.com/microsoft/winget-cli/blob/master/doc/troubleshooting/README.md) helps with this issue.

**Comment by Karl-WE** [comment]
Hello @denelon not exactly. Hhaving the App-Installer from the Store is a requirement. 

My point was that on some systems I have seen this app is reported to be installed as by Settings > Apps while on the Microsoft Store it displays itself as "download now."

If you would try to install winget in this state winget installation would fail to install. 

If a user downloads the application from the store again, even though it is installed, then 2 things might happen:
a. download and installation of App Installer is successful, winget could be installed on top.
b. download is fine and installation seems to be fine but in the Microsoft Store it is still available in the displayed state (screenshot above), winget would not install.

**Comment by denelon** [comment]
@Karl-WE thanks for the clarity here. Do you know if the experience is different based on the version of Windows? I'd like to be able to reproduce this so I can determine if there is a process to resolve this consistently. It may be an issue with the Microsoft Store, Windows 10 version, or the App Installer version.

**Comment by Karl-WE** [comment]
@denelon you're very welcome. No unfortunately not. While I have pushed winget on a lot of boxes with the 0.4 and later release 1.0.x version on 2004 / 20H2 and 21H1 boxes I have not found a way to reproduce it perfectly. 

But I estimate an error rate of 20% in a small sample of 14 completely different and unreleated devices.

What I can say though is that Insider Dev affected too. On my machine I have Windows Dual boot with 5 iterations of Win10 pro or Enterprise, 4 in Dev, 1 in release, not counted into the above figure, on my machine have seen this strange behaviour one time and flagged it here

Me also things this is a Store issue. I am currently working on a feedback hub repro that the store will not update any apps in the background. There are some other reports of this but Eddie requested a fresh one. 

examples of other people feedback: https://aka.ms/AAcojux, https://aka.ms/AAcv9hs, I have found more of these

I understand the Store isn't entirely your scope, yet if we look a bit beyond and assume that the broad distribution of winget in the future relies on this, it might be worth a talk with the PG. I think the first time I noticed this was in 1803. Here was my old feedback on this: https://aka.ms/AA6dyd3

Thanks to your troubleshooting guide, next time I will try to record it in a video and gather more information on the preinstalled app installer.

**Comment by denelon** [comment]
@Karl-WE Keep sending the feedback reports. Sometimes these things are tricky to diagnose and fix, but we want the best experience possible. I hope most of these challenges go away when we ship App Installer including the Windows Package Manager as the default. I'm counting the days.

**Comment by Karl-WE** [comment]
Good luck Den. The user ratings for App Installer on the Store are not representative :) I will try to catch it and open a new issue if I can repro it.
