### ISSUE TITLE
Resolving package with -i Microsoft.PowerShell -v 7.1.0?

### ISSUE THREAD

**Issue by BurtHarris** [microsoft/winget-cli#664]
Winget seems to treat my command line as ambiguous, even though I've specified the version to install.

# Steps to reproduce
```none
winget install -i Microsoft.PowerShell -v 7.1.0
```
# Expected behavior

I would expect specifying ID and version to be specific enough to install the version I want.

# Actual behavior
Unresolved ambiguity despite my using ID and Version:
```none
Multiple apps found matching input criteria. Please refine the input.
Name                      Id                                Version
---------------------------------------------------------------------------
PowerShell                Microsoft.PowerShell              7.1.0
PowerShell Preview (MSIX) Microsoft.PowerShell-Preview-MSIX 7.0.2
PowerShell-Preview        Microsoft.PowerShell-Preview      7.2.0-preview.1
```
Nothing installed.

# Environment

```none
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.662
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

Links:
  Privacy Statement: https://aka.ms/winget-privacy
  License agreement: https://aka.ms/winget-license
  3rd Party Notices: https://aka.ms/winget-3rdPartyNotice
  Homepage:          https://aka.ms/winget
```

**Comment by denelon** [comment]
It appears you need to update for the App Installer. You should be able to get the update from the Microsoft Store if you're not blocked by policy.

**Comment by denelon** [comment]
'winget --info'
Windows Package Manager v0.2.3162 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.20262.1010
Package: Microsoft.DesktopAppInstaller v1.11.3162.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget

**Comment by BurtHarris** [comment]
Thanks, that did it, once I figured out what store entry you were referring to.   

Is there some way to require an up-to-date version when installing winget?   A manifest?

**Comment by BurtHarris** [comment]
Possible duplicate root cause as #291.  Feel free to close if appropriate.

**Comment by denelon** [comment]
We're getting ready to do a pretty major update for the manifests. That will include work in the client to check and see what is supported, and when a newer version of a manifest shows up (than what the client currently supports), it will be an indicator that an upgrade is available. We're still discussing whether we just try to update the package manager automatically when that happens or not. There are several PROs and CONs to both approaches.
