### ISSUE TITLE
Revisit the logic in Architecture.cpp for X64 emulation of ARM64 devices.

### ISSUE THREAD

**Issue by zhzy0077** [microsoft/winget-cli#666]
# Description of the new feature/enhancement

Given the X64 emulation of ARM64 devices went publicly preview this week. We'd better add X64 to ApplicableArchitecturesVector for ARM64 devices. 

# Proposed technical implementation details (optional)
It should be a trivial change by adding an entry to ApplicableArchitecturesVector. However I don't know how to check if the system supports X64 emulation.

**Comment by denelon** [comment]
We will be looking at multi architecture support in #132

**Comment by JohnMcPMS** [comment]
Detection of x64 support on ARM64 requires a new API.
```C++
bool SupportsX64_OnlyCallOnARM64()
{
  // TODO: Dynamically load GetMachineTypeAttributes function pointer
  MACHINE_ATTRIBUTES ma = 0;
  GetMachineTypeAttributes(IMAGE_FILE_MACHINE_AMD64, &ma);
  return ma & UserEnabled;
}
```
`GetMachineTypeAttributes` is a brand new API, and thus we will have to load it from wherever it lives (we should be able to GetProcAddress from the onecore umbrella) to support older OS versions.
