### ISSUE TITLE


unstall

### ISSUE THREAD

**Issue by PuPe1408** [microsoft/winget-cli#668]
# Brief description of your issue

# Steps to reproduce

# Expected behavior

# Actual behavior

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
```

**Comment by megamorf** [comment]
This issue is unusable and therefore should be closed.

**Comment by denelon** [comment]
Duplicate of #121
