### ISSUE TITLE
How to switch from manual installation to Microsoft Store version?

### ISSUE THREAD

**Issue by gc435** [microsoft/winget-cli#671]
I installed WinGet v0.2.3162 around the time of the 2020 Build conference.  `Get-Command winget` shows it's installed in `$env:LOCALAPPDATA`.  I now want to use the version from the Microsoft Store.

How should I proceed?

* Do I uninstall v0.2.3162?  If so, how?
* Do I simply sign up for the Windows Package Manager Insiders Program and install WinGet from the Microsoft Store?  Will it figure out what to do with the old version?

I did not see this addressed in the documentation, and I imagine it might be a common scenario.

**Comment by denelon** [comment]
We will take a look at this when we return from holiday.

**Comment by Marc05** [comment]
I've been waiting for an answer to this as well. Specifically interested in uninstalling it.

**Comment by gc435** [comment]
@KevinLaMS Any thoughts on this?

**Comment by JohnMcPMS** [comment]
> * Do I simply sign up for the Windows Package Manager Insiders Program and install WinGet from the Microsoft Store?  Will it figure out what to do with the old version?

You don't even need to do the second step; just signing up will put you into the flight group and the Store will start delivering updates.  [Note that signing up has some latency, but if it takes more than a week then something may have gone wrong.]  The package that we post to Releases on GitHub is the same one that we send to the Store.
