### ISSUE TITLE
0x80072ee7 Error

### ISSUE THREAD

**Issue by ghost** [microsoft/winget-cli#675]
0x80072ee7 error after using ```winget show/install [anyApp]```

**Comment by megamorf** [comment]
An issue of such low quality cannot be answered and will be closed unless @hazard2020 updates it with more information - steps to reproduce, winget version, network topology, etc. As always, the more detailed you are in your issue description the easier it is to help you.

**Comment by denelon** [comment]
@hazard2020 can you share the `winget --info` output?

**Comment by zQueal** [comment]
If this is just after you installed, then sure that you update your sources before you try to install anything;

> winget source update

Why this isn't done automatically after installing is......super duper weird.
