### ISSUE TITLE
Give optional selection choices in applications while installing

### ISSUE THREAD

**Issue by vasudeveloper001** [microsoft/winget-cli#678]
# Description of the new feature/enhancement

When installing software like Git for Windows, we get the choices during installation. Those choices are currently selected as default while installing through winget. This feature request asks for provided those installation choices in the cmd/PowerShell interface.

**Comment by megamorf** [comment]
This is already possible. What you are asking for is an interactive installation whereas the default is an unattended (a.k.a silent) installation:

|Option|Description|
|---|---|
|-i, --interactive | Runs the installer in interactive mode. The default experience shows installer progress.|

So simply add `-i` or `--interactive` to your install command to get what you want. 
Please don't forget to close your issue if your matter has been resolved.

**Comment by denelon** [comment]
It is also possible to `winget install --override` if you know the command line parameters you wish to pass.

You can execute `winget install -?` to see help for the install command.
