### ISSUE TITLE
Winget create an folder with strange Owner 

### ISSUE THREAD

**Issue by long-nguyenxuan** [microsoft/winget-cli#679]
# Brief description of your issue

`winget` create an folder with stranger owner (`TrustedInstaller`) on my system and 

1. I can't  list that folder content.

[Imgur](https://imgur.com/qc3NSLW)

2. I can't delete files & subfolder in that folder 

[Imgur](https://imgur.com/5OXC8fH)

# Steps to reproduce

- Using `winget` to install `QuickLook`, 
- Search for quicklook folder in your PC. It will an folder be something like `C:\Program Files\WindowsApps\21090PaddyXu.QuickLook_3.6.10.0_neutral__egxr34yet59cg` 
- 

# Expected behavior

`winget` should create folder with owner = current-owner

# Actual behavior

`winget` should create folder with strange owner `TrustedInstaller`

# Environment

```none
C:\Users\long>winget --info
Windows Package Manager v0.2.3162 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18363.1256
Package: Microsoft.DesktopAppInstaller v1.11.3162.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

```

Related Software (The package which I want to uninstall by deleting): `QuickLook`

**Comment by megamorf** [comment]
This is to be expected:

> TrustedInstaller.exe is Windows Module Installer service which is part of Windows Resource Protection.
>
> Windows Resource Protection (WRP) is a technology that restricts access to certain core system files, folders, and registry keys that are part of the Windows installation. WRP prevents files with .dll, .exe, .ocx, and .sys file extensions from being modified or replaced.
>
> Protecting these key resources is important to overall system stability, and, as such, they can only be modified by the Windows Module Installer service (TrustedInstaller.exe). If someone with administrative rights attempts to modify or replace a file that is protected by WRP, he will be presented with the message "Access Denied".
>
> If you change TrustedInstaller settings, you put your system at risk and your system may not function properly. It’s not suggested to remove it.

`C:\Program Files\WindowsApps` is not related to winget. Instead it's the location where Microsoft Store apps are extracted to that are sandboxed and/or need to be protected by WRP.

**Comment by long-nguyenxuan** [comment]
> This is to be expected:

Thanks for reply and this is so sad :/
