### ISSUE TITLE
Add dependencies packages to the package list/sources

### ISSUE THREAD

**Issue by Kein** [microsoft/winget-cli#680]
# Description of the new feature/enhancement
Add numerous dependencies to the packages list for separate/direct installation. For example, search for:

`winget search --id xaml`

does not return any results that include `Microsoft.UI.Xaml` which is a dependency package for many UWP/Store apps. Same for `Microsoft.VCLibs`. It is a bit weird and greatly inconvenient you cant install them directly if you happed to need that.

# Proposed technical implementation details (optional)
Every single of them is a package, nothing special, just need to be added in the list.

**Comment by denelon** [comment]
#163 Support for package dependencies

**Comment by denelon** [comment]
WinGet now has support for dependencies. Any dependencies required by installers are now required to be available in the community repository.

**Comment by Kein** [comment]
I assume it is planned for 1.8?
