### ISSUE TITLE
Roadmap correction

### ISSUE THREAD

**Issue by nopeinomicon** [microsoft/winget-cli#682]
The roadmap to 1.0 laid out in the docs is pretty outdated as of now. Currently the app is a few months behind the target for 0.3,  so I think it would be best for the roadmap dates to be modified in order to more accurately reflect the current state of the project.

**Comment by doctordns** [comment]
Given the numerous comments here on GItHu8b, it would also be useful to see an updated scope/vision document (as per MSF). What, specifically, is winget and who is it targeted? What is the scope - and of course what will ship when. 

The reason I ask for this is I've seen all manner of requests - each of which feels like (if adopted) scope creep. That is of course inevitable and scope can and should be adjusted based on customer need. An update would be, as I say, useful.

**Comment by denelon** [comment]
I've just finished reviewing the open issues on the pkgs repository. I'm going to tackle the client next starting today. I'll be updating the roadmap accordingly. Many of the features we are currently building have dependencies on the `winget list` command. As such, they are behind experimental toggles. Once the list command is out of experimental mode, many of the features depending on it will also be updated as standard commands. These include upgrade, export/import, and uninstall to name a few. I'm expecting we'll jump up a few milestones when that version is released.

**Comment by doctordns** [comment]
Excellent news. Thanks

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/blob/master/doc/windows-package-manager-v1-roadmap.md

**Comment by doctordns** [comment]
A useful update

That being said,  I would suggest you split the Powershell milestone into two
a) An first draft of the object model (the objects used by the WInget PowerShell module (and the _list_ of proposed cmdlets with basic definitions
b) a first release of the module 

I would like to see what you are planning before you get things too baked. From experience, if you wait till all the prior milestones are done, the cmdlets not likely to happen - there will be too much baked in to make it easy. Just like, for example, docker.exe (which years later still has no PowerShell.  In my view, unless there is some early work that can be community reviewed and that you can iterate on, I am not convinced that April Date will be met (if it ever is).

I really want the PowerShell here - so here is my challenge to the team: If I am wrong, I'll put £100 behind the 'bar' for team beverages - or donate to a UK charity of my choosing (The Eplipsey Foundation as my daughter is severely disabled with epilepsy). 

So prove me wrong and I'll eat my words (on camera) and pay up! :-)

**Comment by denelon** [comment]
@doctordns I just put the PowerShell Issue into the Specification tracker. That will help serve as a forcing function to start documenting all of the commands and options in the package manager and their corresponding PowerShell equivalents.

**Comment by doctordns** [comment]
Excellent.

**Comment by denelon** [comment]
@doctordns I couldn't find a US 501(c)(3) equivalent charity. If you have a suggestion I'll make a matching donation in USD when we release the first version of the cmdlet. Beverages might have to be virtual due to travel restrictions.
