### ISSUE TITLE
The installation cannot continue as OpenVPN is currently running

### ISSUE THREAD

**Issue by pascx64** [microsoft/winget-cli#689]
I am unable to install OpenVPN since it gives me the following message : "The installation cannot continue as OpenVPN is currently running". OpenVPN is not installed on my computer. I can also take the same installer that `winget` is downloading and start it myself and it works.

![image](https://user-images.githubusercontent.com/39806655/82900365-6a5acd80-9f2a-11ea-88c2-daff68c81f4b.png)

**Comment by denelon** [comment]
@pascx64 several newer versions of OpenVPN have been added to the repository, and the one you are referencing has been removed. Can you confirm if this is still a problem?

**Comment by pascx64** [comment]
Sorry the OS containing this has been formatted since then!

**Comment by denelon** [comment]
OK, I'll close this issue then. Feel free to re-open or create a new issue if this happens again.
