### ISSUE TITLE
Uninstall feature not showing up

### ISSUE THREAD

**Issue by devmarcusf** [microsoft/winget-cli#704]
Running the most recent pre-release version 

⚡ marcusf@MARCUS-SURFACE  C:\src  winget --version
v0.2.3162 Preview

The first time I run winget features I see Uninstall available and disabled, so I enabled all the features of interest in the settings file below. 

Setting file
{
    "$schema": "https://aka.ms/winget-settings.schema.json",

    // For documentation on these settings, see: https://aka.ms/winget-settings
    "source": {
       "autoUpdateIntervalInMinutes": 5
    },
    "experimentalFeatures": {
        "experimentalMSStore": true,
        "list": true,
        "uninstall": true,
        "upgrade": true
    }
}

Come back and check features again and it seems Uninstall has disappeared from the list. 

⚡ marcusf@MARCUS-SURFACE  C:\src  winget features
The following experimental features are in progress.
They can be configured through the settings file 'winget settings'.

Feature                 Status   Property            Link
-----------------------------------------------------------------------------------
Command Sample          Disabled experimentalCmd     https://aka.ms/winget-settings
Argument Sample         Disabled experimentalArg     https://aka.ms/winget-settings
Microsoft Store Support Enabled  experimentalMSStore https://aka.ms/winget-settings
List Command            Enabled  list                https://aka.ms/winget-settings
Upgrade Command         Enabled  upgrade             https://aka.ms/winget-settings

**Comment by denelon** [comment]
@devmarcusf would you mind sharing the output for `winget --info`?

**Comment by MattBDev** [comment]
> @devmarcusf would you mind sharing the output for `winget --info`?

I can't access the uninstall feature either. I can add it to the settings file but the feature doesn't seem present at all in the currently available version. Here is my output:
```
Windows Package Manager v0.2.3162 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.746
Package: Microsoft.DesktopAppInstaller v1.11.3162.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
```

**Comment by denelon** [comment]
@MattBDev can you reproduce with Windows Package Manager v0.2.10191 Preview?

**Comment by denelon** [comment]
@MattBDev can you upgrade to https://github.com/microsoft/winget-cli/releases/tag/v-0.2.10191-preview
If you are on a Windows Insider build or the Windows Package Manager Insider Preview, you should be able to upgrade "App Installer" via the Microsoft Store.

**Comment by denelon** [comment]
The current client version is now 0.2.10771.

We have not been able to reproduce this issue.

If you are still having this problem on a current version, feel free to re-open this issue.
