### ISSUE TITLE
Winget list: No mapping for the Unicode character exists in the target multi-byte code page

### ISSUE THREAD

**Issue by Playwo** [microsoft/winget-cli#728]
# Brief description of your issue
I get an error every time I try to run `winget list` and all the commands that rely on it. 
`No mapping for the Unicode character exists in the target multi-byte code page.`

# Steps to reproduce
I have not found anyone else with this issue online and the error occurs every time since I have installed Winget.
So I cannot say how to reproduce it :/

# Expected behavior
`winget list` should run without any errors.

# Actual behavior

Trying to run `winget list` (It also affects the other commands requiring list) I get the following error
```
Failed to open the predefined source; please report to winget maintainers.
An unexpected error occurred while executing the command:
0x80070459 : No mapping for the Unicode character exists in the target multi-byte code page.
```

Looking at the log file I found this error (It's time same one every time)
```
...
2021-1-30 20:02:49.444 [REPO] Adding manifest for [IntelliJ IDEA Community Edition 2020.3.2, 203.7148.57] at relative path [IntelliJ IDEA Community Edition 2020.3.2]
2021-1-30 20:02:49.444 [REPO] Did not find an Id { IntelliJ IDEA Community Edition 2020.3.2 }
2021-1-30 20:02:49.445 [FAIL] C:\BA\246\s\external\pkg\src\AppInstallerCommonCore\AppInstallerStrings.cpp(281)\AppInstallerCLI.exe!00007FF74731484F: (caller: 00007FF747320E2B) Exception(1) tid(690) 80070459 No mapping for the Unicode character exists in the target multi-byte code page.

2021-1-30 20:02:49.517 [CLI ] Caught wil::ResultException: C:\BA\246\s\external\pkg\src\AppInstallerCommonCore\AppInstallerStrings.cpp(281)\AppInstallerCLI.exe!00007FF74731484F: (caller: 00007FF747320E2B) Exception(1) tid(690) 80070459 No mapping for the Unicode character exists in the target multi-byte code page.

```
# Environment

```none
Windows Package Manager v0.2.10191 Preview
Windows: Windows.Desktop v10.0.19041.746
Package: Microsoft.DesktopAppInstaller v1.11.10191.0
```

**Comment by denelon** [comment]
Have you changed any of the language or locale settings in Windows?

**Comment by Playwo** [comment]
My system was on german originally. I tried to change it to english (Mostly for the error message :P) but that did not change the error.

**Comment by JohnMcPMS** [comment]
This error seems to be originating from one of the registry entries on your system.  According to MSDN, the API in question will return this error if there is invalid Unicode present.  I don't think that the registry does any validation of that on write, so I think that the best we can do is probably to replace the invalid Unicode (somehow 🤷 ) with some other character to indicate the problem while still including an entry in the list.

If you want to provide us with a registry export of the locations in question, that might (depending on how regedit handles invalid Unicode) allow us to confirm a fix.  But I think that we need to ensure it for a broader range of data than your case, so it isn't necessary.  You could also use these locations to look for a string in regedit that doesn't look quite right and manually fix it.  All the usual caveats of editing the registry by hand apply; make a backup, don't do this unless you know what you are doing, etc.  The problematic entry would be right after `IntelliJ IDEA Community Edition 2020.3.2` (assuming that regedit doesn't sort subkeys differently than the normal enumeration).

```
HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall
HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
```

**Comment by Playwo** [comment]
I looked up IntelliJ under the given paths, the next one below is MEmu. 
The dump of that key is the following
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\MEmu]
"Contact"="support@microvirt.com"
"DisplayIcon"="\"P:\\Microvirt\\MEmu\\MEmu.ico\",0"
"DisplayName"="MEmu"
"DisplayVersion"="7.2.5.0"
"InstallLocation"="P:\\Microvirt"
"Publisher"="Microvirt Software Technology Co. Ltd."
"UninstallString"="\"P:\\Microvirt\\MEmu\\uninstall\\uninstall.exe\" -u"

```

I tried to do some modifications and found that `DisplayIcon` is causing the error. 
Removing the weird `,0` solved it.
I tried to install MEmu on the Sandbox to see if the key generated like that. And yeah it did include the `,0` after a fresh installation.

**Comment by JohnMcPMS** [comment]
The values that we might be reading from (and thus failing on here) are:
```
The key name itself (MEmu)
DisplayName
DisplayVersion
Publisher
UninstallString
```

If changing `DisplayIcon` caused `list` to start working then I don't know what is going on.

**Comment by Playwo** [comment]
OK that is indeed weird. The only value that I intentionally changed is the DisplayIcon. The only thing I could think of is that the Unicode char did not get exported and therefore got removed as I reimported my prior export. Idk how the registry handles Unicode so that's just an idea I had.

**Comment by JohnMcPMS** [comment]
It probably was that the export/import stomped the bad character.  We still need to fix our code to handle it better.

**Comment by denelon** [comment]
We've added code to mitigate this issue. There may still be invalid unicode characters in the registry, but the client should render them with the question mark in a box rather than the client crashing.
