### ISSUE TITLE
Chrome should be updated, but I did 

### ISSUE THREAD

**Issue by DennisPodbicanin** [microsoft/winget-cli#739]
Hello, I have activated the experimental features "list" and "upgrade". I updated Google Chrome via `winget upgrade`. When I called `winget upgrade` again, it still said that Google Chrome can be updated. I want this bug to be fixed. 

# Expected behavior

It should say that no more packages need to be updated (at least not Chrome) 

# Actual behavior

It says Chrome can be updated even though I did. 

# Environment

I wrote this issue on the phone, so there is no information about the environment. But I'll add them here as soon as possible.

**Comment by denelon** [comment]
Duplicate of #696

**Comment by DennisPodbicanin** [comment]
Oh I am sorry. I am still new here
