### ISSUE TITLE
Schema Json return 404

### ISSUE THREAD

**Issue by thibaultdelor** [microsoft/winget-cli#753]
# Brief description of your issue

Auto completing winget settings doesn't work on vscode.
The cause is that the schema url gives a 404.
My settings.json:
```json
{
    "$schema": "https://aka.ms/winget-settings.schema.json",
}
``` 
https://aka.ms/winget-settings.schema.json redirect to  https://raw.githubusercontent.com/microsoft/winget-cli/master/doc/settings.schema.json which doesn't exist

Workaround: Use https://raw.githubusercontent.com/microsoft/winget-cli/master/schemas/JSON/settings/settings.schema.0.2.json instead

# Steps to reproduce

Open my settings.json in VSCode, try to autocomplete. 

# Expected behavior

Typing something like `"exp` should suggest `"experimentalFeatures"`

# Actual behavior

Poor suggestions.

# Environment

```none
λ winget --info
Windows Package Manager v0.2.10191 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.746
Package: Microsoft.DesktopAppInstaller v1.11.10191.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by KevinLaMS** [comment]
This has been updated.  Thanks for the report.
