### ISSUE TITLE
Private repository hosting

### ISSUE THREAD

**Issue by ardenercelik** [microsoft/winget-cli#762]
I would like to host my personal repository with this tool. Is it possible to provide  packages folder which is not the one in the https://github.com/microsoft/winget-pkgs repository?

Should I build my own instance or is it possible to provide direct substitude for the winget-pkgs folder?

**Comment by megamorf** [comment]
Duplicate of:

* #160
* #203
* #213
* #226

/cc @denelon

**Comment by denelon** [comment]
Duplicate of #226
