### ISSUE TITLE
Output OSC 7 "File URI" sequence where appropriate

### ISSUE THREAD

**Issue by WSLUser** [microsoft/winget-cli#763]
# Description of the new feature/enhancement
In the hopefully not too far future, we'll see https://github.com/microsoft/terminal/pull/8921 and follow up PRs land. Additionally there are other terminals that support this sequence right now such as Mintty. Winget can take advantage of this sequence when displaying a list of installed applications including when an application is first installed for example. Users can click on that "link" and open `explorer.exe` at the path of the installed application. This can be useful when needing to troubleshoot installations of an application or uninstallation where winget may be having issues (or an underlying dependency within Windows such as the "Uninstall or Change a Program" in Programs and Features within the Control Panel.) The use of the sequence will be dependent on the ability to list installed applications including eventually the built-in features.

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
This is not what OSC 7 is for. You want OSC 8 to emit _hyperlinks_. OSC 7 communicates the working directory from a process to a terminal.
