### ISSUE TITLE
No results be loaded when using network-related functions 

### ISSUE THREAD

**Issue by CausingBrick** [microsoft/winget-cli#764]
# Brief description of your issue

No results be loaded when using network-related functions, its always loading and loading.
# Steps to reproduce

# Expected behavior
Such as `winget search poytoys`  can be executed normally

# Actual behavior

It's loading for a long time but noting appear.

# Environment

```none
[winget --info]
PS C:\Users\causingbrick> winget --info
Windows Package Manager v0.2.10191 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.804
Package: Microsoft.DesktopAppInstaller v1.11.10191.0
```

One of the log messages is as follow
```
[Log]
2021-2-21 15:53:54.464 [CORE] WinGet, version [0.2.10191], activity [{40A7C087-9C91-4FBB-8625-EA00F4ACC497}]
2021-2-21 15:53:54.464 [CORE] OS: Windows.Desktop v10.0.19042.804
2021-2-21 15:53:54.464 [CORE] Command line Args: "C:\Users\causingbrick\AppData\Local\Microsoft\WindowsApps\winget.exe" search powershell
2021-2-21 15:53:54.464 [CORE] Package: Microsoft.DesktopAppInstaller v1.11.10191.0
2021-2-21 15:53:54.485 [CLI ] WinGet invoked with arguments: 'search' 'powershell'
2021-2-21 15:53:54.485 [CLI ] Found subcommand: search
2021-2-21 15:53:54.485 [CLI ] Leaf command to execute: root:search
2021-2-21 15:53:54.485 [CORE] Setting action: Get, Type: UserFile, Name: settings.json
2021-2-21 15:53:54.501 [CORE] Setting action: Get, Type: UserFile, Name: settings.json.backup
2021-2-21 15:53:54.518 [CORE] Valid settings file not found. Using default values.
2021-2-21 15:53:54.518 [CLI ] Executing command: search
2021-2-21 15:53:54.518 [CORE] Setting action: Get, Type: Secure, Name: user_sources
2021-2-21 15:53:54.520 [CORE] Setting action: Get, Type: Standard, Name: sources_metadata
2021-2-21 15:53:54.520 [REPO] Default source requested, only 1 source available, using the only source: winget
2021-2-21 15:53:54.520 [CORE] Setting action: Get, Type: Secure, Name: user_sources
2021-2-21 15:53:54.521 [CORE] Setting action: Get, Type: Standard, Name: sources_metadata
2021-2-21 15:53:54.521 [REPO] Named source requested, found: winget
2021-2-21 15:53:54.521 [REPO] Source past auto update time [5 mins]; it has been at least 10462 mins
2021-2-21 15:53:54.537 [CORE] Examining extension: PFN = Microsoft.Winget.Source_8wekyb3d8bbwe, ID = IndexDB
2021-2-21 15:53:54.537 [CORE] Found matching extension.

```
This instruction has been executed for half an hour but still noting appear.

**Comment by denelon** [comment]
Are there any policies restricting the Microsoft store on this machine?
Is this machine behind a firewall or VPN?

**Comment by CausingBrick** [comment]
The firewall is turned off and there is no VPN

**Comment by denelon** [comment]
What happens if you execute `winget source update`?

**Comment by CausingBrick** [comment]
It's still loading
![image](https://user-images.githubusercontent.com/37139489/108816980-1f253680-75f2-11eb-9ae9-080647cf8cf3.png)
Logs are as bellow
```
2021-2-23 16:10:33.689 [CORE] WinGet, version [0.2.10191], activity [{36C67D0E-DE06-4364-A691-E9D54A2B3599}]
2021-2-23 16:10:33.690 [CORE] OS: Windows.Desktop v10.0.19042.804
2021-2-23 16:10:33.690 [CORE] Command line Args: "C:\Users\causingbrick\AppData\Local\Microsoft\WindowsApps\winget.exe" source update
2021-2-23 16:10:33.690 [CORE] Package: Microsoft.DesktopAppInstaller v1.11.10191.0
2021-2-23 16:10:33.707 [CLI ] WinGet invoked with arguments: 'source' 'update'
2021-2-23 16:10:33.708 [CLI ] Found subcommand: source
2021-2-23 16:10:33.708 [CLI ] Found subcommand: update
2021-2-23 16:10:33.708 [CLI ] Leaf command to execute: root:source:update
2021-2-23 16:10:33.708 [CORE] Setting action: Get, Type: UserFile, Name: settings.json
2021-2-23 16:10:33.723 [CORE] Setting action: Get, Type: UserFile, Name: settings.json.backup
2021-2-23 16:10:33.738 [CORE] Valid settings file not found. Using default values.
2021-2-23 16:10:33.738 [CLI ] Executing command: update
2021-2-23 16:10:33.738 [CORE] Setting action: Get, Type: Secure, Name: user_sources
2021-2-23 16:10:33.741 [CORE] Setting action: Get, Type: Standard, Name: sources_metadata
2021-2-23 16:10:33.756 [CORE] Setting action: Get, Type: Secure, Name: user_sources
2021-2-23 16:10:33.757 [CORE] Setting action: Get, Type: Standard, Name: sources_metadata
2021-2-23 16:10:33.757 [REPO] Named source to be updated, found: winget
2021-2-23 16:10:33.773 [CORE] Examining extension: PFN = Microsoft.Winget.Source_8wekyb3d8bbwe, ID = IndexDB
2021-2-23 16:10:33.773 [CORE] Found matching extension.

```
The firewall has been turned off, and ping source like bellow
![image](https://user-images.githubusercontent.com/37139489/108817240-89d67200-75f2-11eb-975c-bc9ee1427a87.png)

**Comment by denelon** [comment]
@CausingBrick this appears to be a network connectivity issue. I've seen one other issue that appeared similar to this one. I'm not sure about what to try next. I'll reach out to some of our other engineers to see if we can com up with other suggestions.

**Comment by denelon** [comment]
It may be possible to implement a work-around.

If you download the "source package" from https://winget.azureedge.net/cache/source.msix and install it (either by double clicking the file or using `PowerShell Add-AppxPackage`) you will have the package index.

You would also need to set your update interval in `winget settings` to "0" to prevent the tool from checking for new versions of the package.

From that point you should be able to execute "search" and "install". The network issues would potentially persist depending on the location of the installer.

Any time you wanted to get a current copy of the available packages, you would need to download and install the source again.

**Comment by megamorf** [comment]
Note that since you seem to be located in China that some installer downloads can fail due to slow download speeds and package loss caused by the Great Firewall of China. I've had my fair share of problems with projects in China and the only mitigation was to use Chinese mirrors. This is not possible here because winget essentially acts as a wrapper to install packages hosted all over the internet.

**Comment by CausingBrick** [comment]
@denelon It works as you said but this is not a convenient method. Although the network is not steady for accessing the source but eventually can reach it, so will have a better optimization logic in the program the feature? Anyway Thank you for your answer and help! 😆

**Comment by CausingBrick** [comment]
> Note that since you seem to be located in China that some installer downloads can fail due to slow download speeds and package loss caused by the Great Firewall of China. I've had my fair share of problems with projects in China and the only mitigation was to use Chinese mirrors. This is not possible here because winget essentially acts as a wrapper to install packages hosted all over the internet.

Yeah, quite a few projects cannot be accessed smoothly in China's network environment. But I hope I can install program which can access in China by using winget.😂

**Comment by denelon** [comment]
We are looking at adding a bit of additional "retry" logic, and some other enhancements with Delivery Optimization. I hope those help alleviate some of the networking issues. Hopefully we'll be able to get the peer to peer behavior working for the Windows Package Manager in the near future.

**Comment by denelon** [comment]
We have added retry logic, and the initial implementation of Delivery Optimization. We still have additional work to do on the service side to support peer to peer and parallel download.

**Comment by denelon** [comment]
This appears to be network related. We've done as many of the improvements as we could identify for retry logic. We will also look into the possibility of additional CDN endpoints to see if that will improve customer experiences.
