### ISSUE TITLE
install winget on Server SKU [No applicable app licenses found]

### ISSUE THREAD

**Issue by brwilkinson** [microsoft/winget-cli#776]
I would like to install winget on server sku.

windows server 2022

```powershell
# add pre-reqs
Add-AppxPackage -Path F:\source\tools\Microsoft.VCLibs.x64.14.00.Desktop.appx
# add winget
Add-AppxPackage -Path F:\source\tools\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle

get-command winget

CommandType Name       Version Source
----------- ----       ------- ------
Application winget.exe 0.0.0.0 C:\Users\brw\AppData\Local\Microsoft\WindowsApps\winget.exe

winget search p

Program 'winget.exe' failed to run: No applicable app licenses found   At line:1 char:1
```

**Comment by jedieaston** [comment]
I can replicate this on Server 2019 with GUI.

**Comment by brwilkinson** [comment]
@jedieaston 

I thought I get an unsupported pre-requisites on Server 2019 ? 

Did you install some other packages ? Other than the ones listed above ?

**Comment by jedieaston** [comment]
It’s possible my VM is missing updates, but I’ve gotten this error on 2019 when I have the prerequisites installed.

**Comment by matsmcp** [comment]
I replicated it on 2022 too. 
Both virtual and Physical servers

**Comment by denelon** [comment]
Duplicate of #700
