### ISSUE TITLE
Consistency :    Upgrade or Update ?

### ISSUE THREAD

**Issue by ecovio1** [microsoft/winget-cli#799]
# Description of the new feature/enhancement

![Screenshot 2021-03-16 202640](https://user-images.githubusercontent.com/74822870/111334911-27770b80-869e-11eb-87d8-bfa5948e375a.png)

**as**  `winget Source`  **has** `update` **sub-command  ,, for naming consistency among commands , is it possible to replace the**  `winget Upgrade` **with** `winget Update` ?   `Update` seems to be  much more common than `upgrade` in pckg mangers.

![Screenshot 2021-03-16 202602](https://user-images.githubusercontent.com/74822870/111335673-c4d23f80-869e-11eb-8007-8e5ffd183bd2.png)

**Comment by denelon** [comment]
This was an intentional decision. We didn't want users to become confused about getting the latest update from the source (index of packages) and upgrade packages.

**Comment by denelon** [comment]
I do see that we need to change the description for upgrade so I'll leave this issue open to track that request.

**Comment by ecovio1** [comment]
@denelon also for some reason these links 

https://aka.ms/winget-command-list
https://aka.ms/winget-command-upgrade
https://aka.ms/winget-command-uninstall

leads  to  nowhere, office home page , office home page.

**Comment by YsHaNgM** [comment]
I think the answer is simple, `upgrade` - Upgrades the given package. `update` should point to sources updating conventionally .
