### ISSUE TITLE
GUI for this

### ISSUE THREAD

**Issue by MXP2095onetechguy** [microsoft/winget-cli#820]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)
GUI for this, so it is easier(maybe as an API or officialy part of this)

**Comment by AmitKKhanchandani** [comment]
Rather than creating a completely new GUI app,  What about Integrate Winget with the Microsoft Store app. (this can be shown up in the respected category and it will make the existing app much more usable). (Suggestion)

In the background, the store app will call the Winget-CLI to install the respective software.

**Comment by MXP2095onetechguy** [comment]
yes
but can there be an api for this?

**Comment by denelon** [comment]
We do have a COM API. We will be updating docs in the coming weeks as a part of the pending WinGet 1.4 release.

**Comment by danielehrhardt** [comment]
@MXP2095onetechguy 
meanwhile, you can use:
https://github.com/codextde/winget-gui

**Comment by MXP2095onetechguy** [comment]
Thank you.

**Comment by denelon** [comment]
Hey everyone,

We're starting to look at the possibility of a GUI for WinGet. I'm looking to get a call together with some of the open-source implementation leads for WinGet related GUIs. 

https://github.com/MehediH/winstall - @MedhediH

https://github.com/winget-run/wingetdotrun - @MattheousDT

https://github.com/marticliment/WinGetUI - @marticliment

https://github.com/HandyOrg/HandyWinGet - @ghost1372

https://github.com/DrewNaylor/guinget - @DrewNaylor

https://github.com/Romanitho/Winget-AutoUpdate - @Romanitho 

https://github.com/Weatherlights/Winget-AutoUpdate-Intune - @Weatherlights 

This list may not be exhaustive. If you know of another open-source project related to WinGet with some UI experiences, feel free to mention them in the issue.

I'm in Pacific time and I'm open to finding a time that works for the majority of contributors. Friday the 27th is the date I'd like to aim for. Feel free to either respond here or e-mail me directly to coordinate.

**Comment by ghost1372** [comment]
It is very good news , If running on Windows 7 is important, WPF can be the best option, But if it doesn't matter, I think WinUI 3 (Ability to run on Windows 10 and above) is a very good option.

**Comment by denelon** [comment]
WinGet itself requires Windows 10 RS5 and above.

**Comment by ghost1372** [comment]
@denelon It looks good, my suggestion is WinUI 3/C# because it looks very attractive and flexible and consistent with Windows UI, it also doesn't have UWP limitations.

Can you give us more information?  Dos and don'ts.

**Comment by denelon** [comment]
I don't have much to share. It's very early. I wanted to reach out early to get community feedback. I think there have been some great ideas and examples with what I've come across. Depending on which direction we go with technology, look & feel, etc., I wanted to make sure we give proper recognition to the work that has already been done. I'm just trying to be a good open-source citizen.

**Comment by denelon** [comment]
I want to be respectful of people e-mail for those who are following this issue.

Feel free to mention other projects on this issue, but let's move the general discussion to:
* https://github.com/microsoft/winget-cli/discussions/733

**Comment by Stanzilla** [comment]
Having a (Microsoft) GUI for winget seems the wrong approach here. If anything, the GUI for it should be the Microsoft Store. It makes no sense making a new one.

**Comment by yoshiask** [comment]
I don't quite understand the goal of this issue, but I feel I should mention [Fluent Store](https://github.com/yoshiask/FluentStore) (disclaimer: my own project). It's already built on WinUI 3, and was designed to support multiple package managers and app stores at once, so it should easily handle more than just the WinGet community package repository.

**Comment by denelon** [comment]
Hey everyone. Quick update.

We announced [Dev Home](https://github.com/microsoft/devhome) at Microsft Build.
`winget install "Dev Home (Preview)"`

There is certainly more work to be done!

I also wanted to thank @marticliment for inspiring:
* https://github.com/microsoft/devhome/issues/20

We're still working on:
* #3026
