### ISSUE TITLE
Removed store apps still showing in Search command +  error code could not be found 

### ISSUE THREAD

**Issue by ecovio1** [microsoft/winget-cli#824]
# Brief description of your issue

![Screenshot 2021-03-26 210614](https://user-images.githubusercontent.com/74822870/112654067-39646580-8e79-11eb-8523-7ffd3eb302b5.jpg)

even after `winget source update` This particular unofficial Github Desktop app was removed from store like 7 months ago, still showing in `Search` command, installing it shows a vague error code
`An unexpected error occurred while executing the command: 
the text associated with this error code could not be found`

# Expected behavior
I expect removed apps to be not shown up in `Search` command, even if they show up , installing them should say `it was removed from store(in this case)/not available in my country or something like this`.

# Environment
```
Windows Package Manager v0.2.10771 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.870
Package: Microsoft.DesktopAppInstaller v1.11.10771.0
```

**Comment by denelon** [comment]
Thanks for reporting this @ecovio1. It's likely due to our manually curated list of packages for the experimental store source.

**Comment by yao-msft** [comment]
This app has been removed from our experimental store source. Thanks for the feedback. Please feel free to reopen if this app is still in the list after updating the msstore source. Thanks.
