### ISSUE TITLE
Improper versions being reported by "upgrade" - Sql Server Management Studio

### ISSUE THREAD

**Issue by eidylon** [microsoft/winget-cli#828]
# Brief description of your issue
When running `winget upgrade`, it is showing me the wrong versions for SSMS, and showing an upgrade when there isn't.

# Steps to reproduce
I have SSMS latest version installed
I run `winget upgrade` to list available upgrades

# Expected behavior
Would show updates available to apps I have that are not the latest version. Needs to compare the same version numbers (the same "source") for installed vs. available.

# Actual behavior
```CMD
C:\>winget upgrade
Name                         Id                                  Version      Available Source
-----------------------------------------------------------------------------------------------
Arduino IDE                  ArduinoLLC.ArduinoIDE               1.8.42.0     Latest    msstore
SQL Server Management Studio Microsoft.SQLServerManagementStudio 15.0.18369.0 18.8      winget

C:\>
```
You can see that it shows the installed version as 15.0.18369.0, and shows the latest version as 18.8. 

However, looking at the **About** screen in SSMS, you can see these actually are the same verion.
![image](https://user-images.githubusercontent.com/5951045/112899873-b3326400-90b0-11eb-9fef-5e508ce05541.png)

So it seems that for the current "Version" it is showing the build version, whereas for the latest "Available", it is showing the "friendly" version. As a result, it thinks there is an update when there isn't, because it is comparing limes to bananas.

Because of this, if I try to run the upgrade, it fails like so...
```CMD
C:\>winget upgrade Microsoft.SQLServerManagementStudio
Found SQL Server Management Studio [Microsoft.SQLServerManagementStudio]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://go.microsoft.com/fwlink/?LinkID=840946
  ██████████████████████████████   898 MB /  898 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 3221225477

C:\>
````

# Environment

```none
[winget --info]
Windows Package Manager version: v0.2.10191 Preview
Windows: Windows.Desktop version: v10.0.19042.870
Package: Microsoft.DesktopAppInstaller version: v1.11.10191.0

Any other software?
```

**Comment by jedieaston** [comment]
This can be fixed by putting the proper build number in the manifest as opposed to the "marketing" version number, which is how we've been doing it for Visual Studio.

**Comment by jedieaston** [comment]
Looks to be resolved now that all of the PRs have cleared. Is it behaving correctly on your end now too?

```
PS C:\Windows\system32> winget list --id Microsoft.SQLServerManagementStudio
Name                         Id                                  Version
-----------------------------------------------------------------------------
SQL Server Management Studio Microsoft.SQLServerManagementStudio 15.0.18369.0
PS C:\Windows\system32> winget upgrade --all
No applicable update found.
PS C:\Windows\system32>
```

**Comment by eidylon** [comment]
Yup, just checked, and it is now no longer erroneously listing SSMS as an available upgrade. 👍🏼
