### ISSUE TITLE
This file cannot be accessed from the system

### ISSUE THREAD

**Issue by NukeAOSP** [microsoft/winget-cli#833]
# Brief description of your issue

I have some strange problem with my program which was compiled with SAPIEN PowerShell Studio 2020. 

# Steps to reproduce

I cant run winget even with independent bat. My program just run .bat file with «winget» command and result «cant run program». If I run it from system/powershell/cmd – no problem. 
If I run winget from SAPIEN PowerShell Studio 2020 - ERROR: The winget.exe program has failed: This file cannot be accessed from the system. 
All another software, which I run from sapien (powershell modules, cmd, other system programs), works fine

# Expected behavior

# Actual behavior

# Environment

```none
[winget --info]
Can`t run winget --info
```

**Comment by NukeAOSP** [comment]
Here [https://www.sapien.com/software/powershell_studio](url)

But i call .bat (just with winget) file from tool. Can't even imagine why its didnt work

**Comment by NukeAOSP** [comment]
I can make video or many screenshots if it needed and provide any information as really want to use winget

**Comment by denelon** [comment]
Can you share the --info output from a terminal/shell that is working?

**Comment by NukeAOSP** [comment]
![1](https://user-images.githubusercontent.com/3286315/113106457-77f87800-920b-11eb-8d11-5446d9243e8e.jpg)

**Comment by denelon** [comment]
https://twitter.com/DenelonMs/status/1377286288504578048

**Comment by jedieaston** [comment]
I installed PowerShell Studio on a test box along with winget, and it executes fine for me:

![image](https://user-images.githubusercontent.com/21368066/113192209-7e4b1c00-922c-11eb-982d-ff840baa81a9.png)

Can you post the output of ` echo %PATH% ` if it runs from inside your bat file? I wonder if PowerShell Studio is modifying it somehow.

**Comment by NukeAOSP** [comment]
![123](https://user-images.githubusercontent.com/3286315/113311390-efb0ca80-9311-11eb-946b-005ba4b35644.jpg)

**Comment by NukeAOSP** [comment]
Sry, it seems to be a problem with my studio version. 2021 works fine, but cost extra 300$ =)
