### ISSUE TITLE
winget does not work against new manifest format

### ISSUE THREAD

**Issue by heaths** [microsoft/winget-cli#834]
# Brief description of your issue
Despite what [PSA: New Manifest Schema](https://github.com/microsoft/winget-pkgs/issues/8900) says:

> The Windows Package Manager client will continue to function normally during this transition.

...version v0.2.10191 Preview does not work with manifest version v1.0.0.0. This has blocked any use of winget.

# Steps to reproduce

Run any command that reads a manifest:
```powershell
winget show golang.go
winget install golang.go
```

# Expected behavior

I see manifest information for the selected package.

# Actual behavior

```none
Found Go [GoLang.Go]
An unexpected error occurred while executing the command:
Unsupported ManifestVersion: 1.0.0
0x8a150007 : Cannot process manifest. The manifest version is higher than supported. Please update the client.
```

# Environment

```none
Windows Package Manager v0.2.10191 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.867
Package: Microsoft.DesktopAppInstaller v1.11.10191.0
```

**Comment by denelon** [comment]
@heaths, thank you for reporting this. Can you upgrade to v0.2.10771?

We must have made some late changes that were breaking for v0.210191.

I'll update the PSA.

**Comment by heaths** [comment]
At the time of writing this, it was not available in Windows Store (I just checked again, too). Any idea when that's coming out?

**Comment by denelon** [comment]
> At the time of writing this, it was not available in Windows Store (I just checked again, too). Any idea when that's coming out?

We didn't have you in the correct flight ring. That should be corrected now.

**Comment by heaths** [comment]
Thanks. I'm getting the update now since I had originally installed from the Store on at least one of my machines. You or I could close this now, or if you want to keep it open to track the PSA update that's fine, too.

**Comment by denelon** [comment]
I added a comment with a link to this issue. https://github.com/microsoft/winget-pkgs/issues/8900

I'll go ahead and close this one.
