### ISSUE TITLE
Cannot install apps

### ISSUE THREAD

**Issue by avi12** [microsoft/winget-cli#839]
# Brief description of your issue

Installing an app results in an error:
```
Found GitHub CLI [GitHub.cli]
An unexpected error occurred while executing the command:
Unsupported ManifestVersion: 1.0.0
0x8a150007 : Cannot process manifest. The manifest version is higher than supported. Please update the client.
```
# Steps to reproduce

```powershell
winget install github.cli
```
# Expected behavior

Being able to install the app.
# Actual behavior

Getting the error above.

# Environment

```none
[winget --info]
Windows Package Manager v0.2.10191 Preview
Windows: Windows.Desktop v10.0.19042.870
Package: Microsoft.DesktopAppInstaller v1.11.10191.0

Additional software
PowerShell (admin): 5.1.19041.868
Windows Terminal: 1.6.10571.0
```

**Comment by ecovio1** [comment]
`Please update the client.`
this tells you what to do. install the latest .appxbundle from release or update through store.

**Comment by avi12** [comment]
@ecovio1 I did both. The bug sitll exists.

**Comment by aagz** [comment]
v0.1.41331 works fine.
v0.2.10191:

```
PS C:\soft> winget install -e --id 7zip.7zip
Найдено 7Zip [7zip.7zip]
При выполнении команды произошла непредвиденная ошибка:
Unsupported ManifestVersion: 1.0.0
0x8a150007 : Cannot process manifest. The manifest version is higher than supported. Please update the client.
PS C:\soft> winget show 7zip
Найдено 7Zip [7zip.7zip]
При выполнении команды произошла непредвиденная ошибка:
Unsupported ManifestVersion: 1.0.0
0x8a150007 : Cannot process manifest. The manifest version is higher than supported. Please update the client.
PS C:\soft>
```

**Comment by aagz** [comment]
v0.1.41331 works fine.

@ecovio1 Now I installed the latest version of .appxbundle.

v0.2.10191:

```Powershell
PS C:\soft> winget install -e --id 7zip.7zip
Найдено 7Zip [7zip.7zip]
При выполнении команды произошла непредвиденная ошибка:
Unsupported ManifestVersion: 1.0.0
0x8a150007 : Cannot process manifest. The manifest version is higher than supported. Please update the client.
PS C:\soft> winget show 7zip
Найдено 7Zip [7zip.7zip]
При выполнении команды произошла непредвиденная ошибка:
Unsupported ManifestVersion: 1.0.0
0x8a150007 : Cannot process manifest. The manifest version is higher than supported. Please update the client.
PS C:\soft>
```

**Comment by jedieaston** [comment]
The new version of the client (v0.2.10771) is still marked as "pre-release" in GitHub, so here is the direct link: https://github.com/microsoft/winget-cli/releases/tag/v-0.2.10771-preview. After installing this you should be able to use the new manifests.

**Comment by denelon** [comment]
@jedieaston thanks for pointing that out. Generally, I try to remove the "pre-release" label after the package is published to the store. I was thinking once we announce 1.0 I will only remove the "pre-release" mark from versions that have shipped to stable Windows 10. Are there any unintended consequences of doing that? Maybe I should just "edit" the release notes when a version is shipped in the future.

**Comment by jedieaston** [comment]
I can't think of any, editing the release notes when the build hits the store would be the best move so people can know there's a manual update available to fix bugs. 

What would be even better is if we could do ` winget upgrade --all ` and have winget upgraded, but I just tried that with a local manifest and since winget has to close to complete the upgrade, it just kind of stops (the upgrade completes successfully, but the progress bar stops at 21% since that's when the old version of winget is closed and there is never a message that install failed or succeeded). I don't know a great solution to that, other than having another copy of winget somewhere that is only used for bootstrapping winget, but it's a use case to think about.

**Comment by denelon** [comment]
We also get restarted if you upgrade PowerShell (the shell you are using) or Terminal (the terminal you are using).

**Comment by ltomuta** [comment]
Ok, so there is something fishy here.
I have the latest version of the client installed via the store but somehow it still reports itself to be v0.2.2941 instead of 1.whatever.

Why and how to fix this?

I tried uninstalling the app using 

Get-AppXPackage Microsoft.DesktopAppInstaller | Remove-AppXPackage 

and this seems to work. But after I install it again from the store, the problem remains the same.

**Comment by ltomuta** [comment]
C:\Users\lucian>winget --info
Windows Package Manager v0.2.2941 Previzualizare
(c) Microsoft Corporation. Toate drepturile rezervate.

Windows: Windows.Desktop v10.0.19043.1165
Pachet: Microsoft.DesktopAppInstaller v1.11.2941.0

**Comment by denelon** [comment]
@ltomuta your Microsoft Account(MSA) would need to be in the insider program to get an update from the store with Windows Package Manager unless you are on a Windows Insider build. Take a look at the README.md(https://github.com/microsoft/winget-cli#installing-the-client) if you want to join the insider program to receive dev builds. We're planning to release the stable Windows Package Manager to all Windows 10 (1809+) builds at the end of September 21'. You can also install directly from the releases page here at GitHub.

**Comment by ltomuta** [comment]
I am in the insider program, I got email with link to fetch the update via
store. Not on a insider build in that PC though.

And the package delivered by the store, before and after uninstall, is
supposedly 1.x not 0.2

Well, maybe some databases not synchronized yet.

joi, 2 sept. 2021, 17:32 denelon ***@***.***> a scris:

**Comment by avi12** [comment]
```powershell
PS C:\Users\avi12> winget install --exact "WhatsApp.WhatsApp"
Found WhatsApp [WhatsApp.WhatsApp] Version 2.2134.10
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://web.whatsapp.com/desktop/windows/release/x64/WhatsAppSetup.exe
An unexpected error occurred while executing the command:
InternetOpenUrl() failed.
0x80072ee7 : unknown error
```
WinGet version: v1.1.12653

**Comment by ImJoakim** [comment]
> ```powershell
> PS C:\Users\avi12> winget install --exact "WhatsApp.WhatsApp"
> Found WhatsApp [WhatsApp.WhatsApp] Version 2.2134.10
> This application is licensed to you by its owner.
> Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
> Downloading https://web.whatsapp.com/desktop/windows/release/x64/WhatsAppSetup.exe
> An unexpected error occurred while executing the command:
> InternetOpenUrl() failed.
> 0x80072ee7 : unknown error
> ```
> 
> WinGet version: v1.1.12653
> 
> Notice that I opened PowerShell as administrator

Facebook, Messenger, WhatsApp & Instagram are all currently down, that's why you are unable to download the installer from WhatsApp.

**Comment by avi12** [comment]
Yep, just found out about it
WinGet should provide a better error than "Unknown error"

**Comment by denelon** [comment]
#1546
