### ISSUE TITLE
How do you completely uninstall Winget?

### ISSUE THREAD

**Issue by VladPutinEu** [microsoft/winget-cli#842]
What is the procedure (what I must do) to completely uninstall Winget? I do not want to uninstall a Winget package, I want to uninstall the Winget package manager completely. I've decided to pass until is it completely released as I do not have much of a need for it.

**Comment by ecovio1** [comment]
IMO, completely uninstalling winget should never be an option. 
>I've decided to pass until is it completely released.
go to windows settings>apps>app execution aliases>toggle off winget.exe there
it won't show up in whatever command line you have.

**Comment by ecovio1** [comment]
IMO, completely uninstalling winget should never be an option. 
>I've decided to pass until is it completely released.

go to windows settings>apps>app execution aliases>toggle off winget.exe there
it won't show up in whatever command line you have.
