### ISSUE TITLE
0x80073cfc : The application cannot be started. Try reinstalling the application to fix the problem.

### ISSUE THREAD

**Issue by CausingBrick** [microsoft/winget-cli#858]
# Brief description of your issue

The winget-cli can't run while i using relative sub command.
# Steps to reproduce
Use winget with any sub command, such as search, list, etc

# Expected behavior

# Actual behavior

```
PS C:\Users\causingbrick> winget list
Failed to open the source; try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x80073cfc : The application cannot be started. Try reinstalling the application to fix the problem.
PS C:\Users\causingbrick> winget search qq
Failed to open the source; try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x80073cfc : The application cannot be started. Try reinstalling the application to fix the problem.
```

I had tried rest the source but no help.

# Environment

```none
[winget --info]

Windows: Windows.Desktop v10.0.21354.1
Package: Microsoft.DesktopAppInstaller v1.11.10771.0
Windows Package Manager v0.2.10771 Preview
```

**Comment by denelon** [comment]
@CausingBrick

What source(s) do you have configured?

`winget source list`

Is there a policy blocking the Microsoft Store?

What was the result of `winget source reset`?

Do you have any settings affecting the "autoUpdateIntervalInMinutes"?

**Comment by CausingBrick** [comment]
> @CausingBrick
> 
> What source(s) do you have configured?
> 
> `winget source list`
> 
> Is there a policy blocking the Microsoft Store?
> 
> What was the result of `winget source reset`?
> 
> Do you have any settings affecting the "autoUpdateIntervalInMinutes"?

Thanks for your reply!
1.  `winget source list` result:
```
PS C:\Users\causingbrick> winget source list
Name    Argument
--------------------------------------------
winget  https://winget.azureedge.net/cache
msstore https://winget.azureedge.net/msstore
```
2. There is no policy  blocking the Microsoft Store, I can install apps in it nomally.
3. `winget source reset` resulst :
```
PS C:\WINDOWS\system32> winget source reset
The following sources will be reset if the --force option is given:
Name    Argument
--------------------------------------------
winget  https://winget.azureedge.net/cache
msstore https://winget.azureedge.net/msstore
PS C:\WINDOWS\system32> winget source reset --force
Resetting all sources...Done
```
4. The value of "autoUpdateIntervalInMinutes" is 1 in settings.json.

**Comment by denelon** [comment]
@CausingBrick the "autoUpdateIntervalInMinutes" is a bit short. Our default is 5 minutes. That setting is what the client uses to determine if it should check for a newer source package and download it. If you have a great network connection to the Internet you should be able to download, install, run commands with the source. Can you try increasing that value and see if you get different results?

Did you install the Windows Package Manager via GitHub releases, or the Microsoft Store?

Would you mind using [Windows]+[f] to submit feedback for "Apps" / "Windows Package Manager"? That will result in logs being sent so we can try some additional troubleshooting.

**Comment by CausingBrick** [comment]
Today I ran the winget without modifying the settings with the settings.json, its perform normally. I don't know the reason, maybe my wi10 rebooted several times for windows update last night.

**Comment by denelon** [comment]
Feel free to re-open the Issue if this happens again.
