### ISSUE TITLE
Provide Taskbar progress indicator in Terminal

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#869]
# Description of the new feature/enhancement

Provide OSC 9;4 sequence to provide status in Terminals for status.

Windows Terminal added support in https://github.com/microsoft/terminal/pull/8055 for https://github.com/microsoft/terminal/issues/3004 Taskbar progress indicator.

**Comment by chausner** [comment]
This seems like a fun little feature I could potentially contribute, provided that @JohnMcPMS hasn't already started working on this. Does this need a spec written first?

**Comment by denelon** [comment]
@chausner I see this as a small work item. I'd be open to a PR against this issue :)

We would love to have your support!

**Comment by JohnMcPMS** [comment]
I have not, and I agree that it is both fun and should be a fairly small amount of work.

Watch out for how it handles cancellation with CTRL+C; a single signal should be able to end with the proper sequence but I don't know how the second one (where we just exit process) will be handled by Terminal.  Hopefully they track the source of this and end the progress when that process terminates.

I think we did want to get this in over the next two weeks, so please let us know if you've started it.

**Comment by JohnMcPMS** [comment]
And since neither of us explicitly answered the spec question; no, I don't see this as needing a spec.

**Comment by chausner** [comment]
Okay great, please assign me to this issue and I'll try to have a first implementation ready by next week.

> Watch out for how it handles cancellation with CTRL+C; a single signal should be able to end with the proper sequence but I don't know how the second one (where we just exit process) will be handled by Terminal. Hopefully they track the source of this and end the progress when that process terminates.

I did a quick test with
```
> python
print("\x1b]9;4;2;40\x1b\\")
quit()
```
and Terminal did not reset the progress on the task bar after the Python process exited. So when the winget process exits abnormally and if there is no event that would notify us before the process exit, there is probably no way to reset the progress. But normally, winget should not exit unexpectedly, right? And in the case of normal exit, we can always reset the progress.

**Comment by JohnMcPMS** [comment]
The only "expected" exit would be the second CTRL+C, where we terminate the process because cooperative cancellation didn't happen fast enough for the user.  We could probably even handle it in that case, but only of there is a clean "turn off progress" sequence.  I think it is fine to leave that as future work since most places where we are in a progress state should also be the best at cancellation.
