### ISSUE TITLE
Program 'winget.exe' failed to run: Access is denied.At line:1 char:1

### ISSUE THREAD

**Issue by bckelley** [microsoft/winget-cli#876]
anytime I run `winget install app`  or any command other then just `winget` i get this error

```
ResourceUnavailable: Program 'winget.exe' failed to run: Access is denied.At line:1 char:1
```
 and when I run just `winget` I actually see the help menu. Same results with admin and non-admin privileges.

**Comment by denelon** [comment]
@bckelley can you share the output of `winget --info`?

Are you running on a Windows Insider build?
Is this an enterprise managed machine?
Did you install the "App Installer" via the Microsoft Store, or did you install from the GitHub releases page?

**Comment by bckelley** [comment]
I have no idea.
no.
yes.

**Comment by denelon** [comment]
I'd like to help get this working for you.

I'll assume you're not running a [Windows Insider](https://insider.windows.com/) build as you would likely know if you were.
My last question was regarding the method you used to install the Windows Package Manager.

Can you give some additional detail about which version of Windows you are running and how you installed the Windows Package Manager?

Are you trying to run the tool in PowerShell or CMD?

**Comment by bckelley** [comment]
Windows Version 10.0.18362
As for 
>  and how you installed the Windows Package Manager?

I already answered  that when I said yes your 

> Did you install the "App Installer" via the Microsoft Store, or did you install from the GitHub releases page?

question

**Comment by denelon** [comment]
I'm trying to get clarity so I might be able to reproduce the issue. I've only seen this specific error one other time out of tens of thousands of installations. Users would usually do *one* of the two following things:

1) Install the "App Installer" via the store. 
2) Download and install the "App Installer" via the GitHub releases page and install it directly.

You may have done both which isn't necessary. That may be part of the problem. If you did both, which one was first and which one was second?

Did you fill out the form to join the Windows Package Manager Insider flight ring? If you did, you would need to be signed into the store with the Microsoft Account (MSA) to get the flighted build from the Microsoft Store.

We've seen what appears to be an OS problem with https://github.com/microsoft/winget-cli/issues/210

That issue may be able to help find the fix. In a few instances, a reboot seems to have corrected the problem, but not in all cases.

**Comment by bckelley** [comment]
I have only installed using the microsoft store!

**Comment by denelon** [comment]
@bckelley are you still having this issue? We've been working through several issues related to the Windows Package Manager not working. We've found at least one instance across more than one Issue related to a KB article associated with an update to App Installer. I'm not able to reproduce this without some assistance.

**Comment by denelon** [comment]
@bckelley we've updated our [troubleshooting](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting) guide. Let us know if none of these steps resolves the issue.

**Comment by chandanroksjsr** [comment]
had same issue went to app & features -> advanced options in app installer -> terminate repair & reset then it started working
