### ISSUE TITLE
winget installed but error when try

### ISSUE THREAD

**Issue by Owned67** [microsoft/winget-cli#897]
# Brief description of your issue

# Steps to reproduce

Download Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle, double click and install, open a prompt powershell => type winget and enter

# Expected behavior

`winget : Le terme «winget» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme
exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct
et réessayez.
Au caractère Ligne:1 : 1
+ winget
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (winget:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

# Actual behavior

# Environment

```none
[winget --info]
Windows Package Manager 1.11.11102.0
Windows: Windows.Desktop tell me how find this?
Package: Microsoft.DesktopAppInstaller tell me how find this?

Any other software?
```

**Comment by jedieaston** [comment]
Try searching for "App Execution Aliases" (or the equivalent in French) in the Windows search bar, should bring up some settings. Is winget in that menu, and is it checked?

**Comment by Owned67** [comment]
yes winget.exe is here and enabled.

I've search .exe and i've found in:
%LOCALAPPDATA%\Microsoft\WindowsApps
%LOCALAPPDATA%\Microsoft\WindowsApps\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe

for a temporary solution, i've added %LOCALAPPDATA%\Microsoft\WindowsApps in the path...

**Comment by denelon** [comment]
@Owned67 we've also updated our [troubleshooting](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting) guide. Let us know if none of those steps resolves this issue.
