### ISSUE TITLE
show-ing or install-ing anything returns an "unexpected error"

### ISSUE THREAD

**Issue by rotopenguin** [microsoft/winget-cli#900]
# Brief description of your issue

"Winget show" will list all the gettable applications, but doing "winget show APP" or "winget install APP" gets me something like this..
```
C:\Users\user\Documents>winget show cpod
Found CPod [z-------------.cpod]
An unexpected error occurred while executing the command:
yaml-cpp: error at line 8, column 1: bad conversion
0x8a150004 : Opening manifest failed
```

# Steps to reproduce

I have no idea how I got my PC into this state. Winget used to work on here. Now that it is broken, it seems insistent on staying broken. I have had little luck binging this error, or finding what cached state I could clear out from Winget.

# Expected behavior

Showing details of a named package, or installing one.

# Actual behavior

declaring it found package [developer.package], then erroring out.

# Environment

```[winget --info]
Windows Package Manager v0.1.42101 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.928
Package: Microsoft.DesktopAppInstaller v1.10.42101.0

C:\Users\user\Documents>winget source list
Name   Argument
-----------------------------------------
winget https://winget.azureedge.net/cache

C:\Users\user\Documents>winget features
The following experimental features are in progress.
They can be configured through the settings file 'winget settings'.

Feature                 Status   Property            Link
-----------------------------------------------------------------------------------
Command Sample          Disabled experimentalCmd     https://aka.ms/winget-settings
Argument Sample         Disabled experimentalArg     https://aka.ms/winget-settings
Microsoft Store Support Disabled experimentalMSStore https://aka.ms/winget-settings
```

**Comment by rotopenguin** [comment]
**Description of issue**
"Winget show" will list all the gettable applications, but doing "winget show APP" or "winget install APP" gets me something like this..
```
C:\Users\user\Documents>winget show cpod
Found CPod [z-------------.cpod]
An unexpected error occurred while executing the command:
yaml-cpp: error at line 8, column 1: bad conversion
0x8a150004 : Opening manifest failed
```
**Steps to reproduce**
I have no idea how I got my PC into this state. Winget used to work on here. Now that it is broken, it seems insistent on staying broken. I have had little luck binging this error, or finding what cached state I could clear out from Winget.

**Expected Behaviour**
Showing details of a named package, or installing one.

**Actual Behaviour**
declaring it found package [developer.package], then erroring out.

**Environment**
```
Windows Package Manager v0.1.42101 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.928
Package: Microsoft.DesktopAppInstaller v1.10.42101.0

C:\Users\user\Documents>winget source list
Name   Argument
-----------------------------------------
winget https://winget.azureedge.net/cache

C:\Users\user\Documents>winget features
The following experimental features are in progress.
They can be configured through the settings file 'winget settings'.

Feature                 Status   Property            Link
-----------------------------------------------------------------------------------
Command Sample          Disabled experimentalCmd     https://aka.ms/winget-settings
Argument Sample         Disabled experimentalArg     https://aka.ms/winget-settings
Microsoft Store Support Disabled experimentalMSStore https://aka.ms/winget-settings
```

**Comment by denelon** [comment]
@rotopenguin it appears you have an older version of the Windows Package Manager. 
Instructions for installing the client are in the README https://github.com/microsoft/winget-cli#installing-the-client

**Comment by denelon** [comment]
Can you upgrade the client to see if this resolves the issue?

**Comment by rotopenguin** [comment]
I finally have an upgraded client that works! I have no idea what sequence of flapping around fixed it. I uninstalled winget via Settings, updated the App Installer through the store, installed the latest .appxbundle from github, installed the one before the latest, and finally installed the latest one back.

For most of that journey, Winget went from the yaml-cpp error to 
```
C:\Users\user>winget show
Failed to open the source; try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x8a15000f : Data required by the source is missing
```
And doing a "winget source reset --force" (in an admin cmd) didn't seem to do the trick.

But somehow, re-installing the latest(11102) and resetting the source _again_ did the trick. Flailing around works 😎

```
C:\Users\user>winget --info
Windows Package Manager v0.3.11102 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.928
Package: Microsoft.DesktopAppInstaller v1.11.11102.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget

C:\Users\user>winget install shellexview
Found ShellExView [NirSoft.ShellExView]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.nirsoft.net/utils/shexview_setup.exe
  ██████████████████████████████   155 KB /  155 KB
Successfully verified installer hash
Starting package install...
Successfully installed
```

**Comment by denelon** [comment]
I'm happy you were able to use the brute force method to get it to conform to your will! We're going to have to do some more battle with the code to see if we can get this problem beat into submission.

**Comment by clovett** [comment]
See the solution I posted here https://github.com/microsoft/winget-cli/issues/998 solves the "0x8a15000f : Data required by the source is missing" problem

**Comment by ashpatil-msft** [comment]
We are not able to reproduce this error. The client has been updated, and this may have already been resolved. Feel free to reopen this bug if you encounter this issue again with the steps to reproduce the error.
