### ISSUE TITLE
Broken link to upgrade documentation

### ISSUE THREAD

**Issue by me-and** [microsoft/winget-cli#918]
When running `winget upgrade -?` after enabling the upgrade command in the settings Json file, the output finishes with the following line:

> More help can be found at: https://aka.ms/winget-command-upgrade

I'd expect this link to take me to a documentation page, but instead from my personal machine it just redirects to a Bing search page.

**Comment by ecovio1** [comment]
reported long ago here  : [#799](https://github.com/microsoft/winget-cli/issues/799#issuecomment-800389952)
