### ISSUE TITLE
"0x8a15002e : Download size does not match expected content length"

### ISSUE THREAD

**Issue by avi12** [microsoft/winget-cli#932]
# Brief description of your issue

I cannot download some packages, e.g. `nodejs`.

# Steps to reproduce
1. Install WinGet
2. Type to PowerShell running as admin: `winget install nodejs`

# Expected behavior
Install Node.js as expected.

# Actual behavior
```
0x8a15002e : Download size does not match expected content length
```

# Environment

```
Windows Package Manager version: 0.3.11102 Preview
Windows: Windows.Desktop version: 10.0.19041.572
Package: Microsoft.DesktopAppInstaller version: 1.11.11102.0
```

**Comment by ecovio1** [comment]
may be you should **delete the cache** or update windows.

works as expected here : 
![Screenshot 2021-05-06 192426](https://user-images.githubusercontent.com/74822870/117305897-02826600-aea1-11eb-8fd0-723c2312e67c.png)
![Screenshot 2021-05-06 192345](https://user-images.githubusercontent.com/74822870/117305908-057d5680-aea1-11eb-9b41-349cafda8b2f.png)

**Comment by avi12** [comment]
Windows is already updated (20H2).
How do I delete cache?

**Comment by ecovio1** [comment]
make sure all showing hidden folders enabled, clear the contents of %localappdata%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\AC\INetCache and try again.

**Comment by avi12** [comment]
Before your first post, I decided to install Node.js using its MSI
Next time I'll run into the same issue, I'll try to delete the cache and then retry

**Comment by ashpatil-msft** [comment]
We are not able to reproduce this error. The client has been updated, and this may have already been resolved. Feel free to reopen this bug if you encounter this issue again with the steps to reproduce the error.
