### ISSUE TITLE
Unistall error when id passed in powershell with out quotes is confusing

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/winget-cli#934]
When trying to uninstall orca.  it has an id that is a guid.
When I tried to pass in the guid.  with out quotes i get a strange message.

winget uninstall  --id {24559D0F-481C-F3BE-8DD0-D908923A38F8}
Windows Package Manager v0.3.11201 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Adjoined flag alias not found : '-inputFormat'

 it would be better to tell them to pass in a quoted string.

**Comment by denelon** [comment]
@KevinLaMS does this still happen in v1.1?

**Comment by ItzLevvie** [comment]
> @KevinLaMS does this still happen in v1.1?

This still happens on v1.2.3411-preview (1.17.3411.0) with Windows PowerShell version 5.1 and with PowerShell version 7.3.0-preview.1:
![image](https://user-images.githubusercontent.com/11600822/148385851-b563a9b7-1070-465f-ae1d-026ab1ecf723.png)

I am unable to reproduce this with Command Prompt.

**Comment by denelon** [comment]
@ItzLevvie, I believe what is happening is PowerShell is reacting to the curly brace "{".

**Comment by denelon** [comment]
This is indeed an issue specific to PowerShell interpreting the `{`.
This specific scenario will require using quotation marks around the GUID in curly braces.
