### ISSUE TITLE
Updates to packages.json schema.

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#940]
# Description of the new feature/enhancement

The packages.json schema shouldn't need the "WinGetVersion" as a required attribute since the schema itself is versioned.

The "CreationDate" should include an example for the proper format.

The "Id" field in the "Packages" node should be changed to "PackageIdentifier" so it conforms to the other schemas.

# Proposed technical implementation details (optional)

Update the packages.json schema and documentation.

Thanks @MehediH for the suggestions.

**Comment by MehediH** [comment]
Thanks @denelon!
