### ISSUE TITLE
Export only contains a few items

### ISSUE THREAD

**Issue by anoblet** [microsoft/winget-cli#941]
# Brief description of your issue

Even though I've installed 15+ of packages using `winget`, `winget export` only contains a few items.

# Steps to reproduce

1.  Install Steam using `winget`
2.  Run `winget export packages.json` 

# Expected behavior

Steam is listed as an installed package.

# Actual behavior

Steam is not present in the list.

# Environment

```
Windows Package Manager: 0.3.11102
Windows: 10.0.19042.964
Package: 1.11.11102.0
```

**Comment by denelon** [comment]
@anoblet export has a dependency on `winget list`. We also have quite a bit of work to improve the matching logic between what is recorded in Add / Remove Programs (ARP) and the metadata in a manifest. I've been making small adjustments to several of the manifests `PackageName` and `Publisher` to more closely match what is written to ARP when packages are installed.

**Comment by denelon** [comment]
@anoblet we've made several improvements to "list" and many manifests. Are you starting to see better results with export now?

**Comment by anoblet** [comment]
I am :) Thanks for all of the hard work!
