### ISSUE TITLE
Upgrade target are listed, but upgrade cannot be made.

### ISSUE THREAD

**Issue by noriakia** [microsoft/winget-cli#963]
# Brief description of your issue

Upgrade targets(Adobe Acrobat Reader) are listed, but upgrade cannot be made.

# Steps to reproduce

PS D:\Users\noria\Developments> winget upgrade
名前                        ID                         バージョン   利用可能       ソース

Adobe Acrobat Reader DC MUI Adobe.AdobeAcrobatReaderDC 21.001.20155 2021.001.20155 winget
PS D:\Users\noria\Developments> winget upgrade -e "Addobe Acrobat Reader DC MUI"
入力条件に一致するインストール済みのパッケージが見つかりませんでした。
PS D:\Users\noria\Developments> winget upgrade Adobe.AdobeAcrobatReaderDC
適用可能な更新は見つかりませんでした。

PS D:\Users\noria\Developments> winget upgrade
名前                        ID                         バージョン   利用可能       ソース

Adobe Acrobat Reader DC MUI Adobe.AdobeAcrobatReaderDC 21.001.20155 2021.001.20155 winget
PS D:\Users\noria\Developments>

# Expected behavior

Target software is upgraded

# Actual behavior

Target software is not upgraded

# Environment

```none
[winget --info]
Windows Package Manager v0.3.11201 プレビュー
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.21376.1
パッケージ: Microsoft.DesktopAppInstaller v1.11.11201.0

ログ: D:\Users\noria\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

リンク
----------------------------------------------------------------
プライバシーに関する声明    https://aka.ms/winget-privacy
使用許諾契約                https://aka.ms/winget-license
サード パーティに関する通知 https://aka.ms/winget-3rdPartyNotice
ホーム ページ               https://aka.ms/winget

Any other software?
```

**Comment by denelon** [comment]
@noriakia be sure to add your 👍 to #752. 

We're continuing to improve the `list` command where this matching logic (compare manifests against entries in Add / Remove Programs) lives.

Duplicate of 752#
