### ISSUE TITLE
Introduce new and completely optional term "AppName" for manifest. 

### ISSUE THREAD

**Issue by KaranKad** [microsoft/winget-cli#982]
# Description and explanation of the new feature/enhancement

 
winget uses `PackageName` to show name of the application when we use commands like `winget search` or `winget show`, it also uses it to relate to apps that we see in control panel/settings app, however some apps have different marketed/proper names vs the one that we see in control panel/settings app. This creates some issues.

For example, there is app called [XDM](https://xtremedownloadmanager.com/) (Xtreme Download Manager) whose `PackageName` was set to `Xtreme Download Manager` rightfully, but when I used its `Moniker` `xdm` to list the app using `winget list` it returns me with an error.
![image](https://user-images.githubusercontent.com/71691514/119262006-4c847f00-bbf7-11eb-87b8-47c7a41c941a.png)

But when I changed its `PackageName` to `Xtreme Download Manager 2020` according to control panel/settings app
![image](https://user-images.githubusercontent.com/71691514/119262124-c0bf2280-bbf7-11eb-8f67-7e70b870ae56.png)

Searching with `Moniker` returns proper result
![image](https://user-images.githubusercontent.com/71691514/119262223-0ed42600-bbf8-11eb-99aa-807794c3137d.png)

But now unnecessary information is in the app name when we use `winget search` or `winget show` command

# Proposed technical implementation details (optional)

We could use term `AppName` for proper name of the app, so when using `winget search` or `winget show` command, proper name of the app is shown. 

For Example, if manifest looks like this
```
PackageName: Xtreme Download Manager 2020
AppName: Xtreme Download Manager
```
and `winget show xdm` command is used the output should be
```
Found Xtreme Download Manager [subhra74.XtremeDownloadManager]
Version: 7.2.11
Publisher: subhra74
Author: subhra74
Moniker: xdm
```
instead of `Xtreme Download Manager 2020 [subhra74.XtremeDownloadManager]` which it currently shows.

The term `AppName` should only be used for describing/showning purpose and term `PackageName` should be used for relating or describing/showing purpose, because `AppName` is completely optional term and winget should just proceed with `PackageName` when term `AppName` is not given/detected in the manifest.

We could mention it in docs somewhere to enter data for `PackageName` according to the one in control panel/settings app name and enter data for `AppName` according to actual app name, only if the app has complicated case like this app.

**Comment by denelon** [comment]
This is part of the work we're doing with the new schema. We have added a section for data specifically matching what is reported via Apps & Features.

**Comment by denelon** [comment]
The package name will be the "Official name of the package", and the one found in Add / Remove Programs will be in the "Apps & Features" section of the manifest.

**Comment by denelon** [comment]
I believe this has been completed. Please let me know if this is not the case.
