### ISSUE TITLE
Import does not work when some packages names could correspond to multiple packages.

### ISSUE THREAD

**Issue by TechWatching** [microsoft/winget-cli#983]
# Brief description of your issue
winget import fail for some packages because of multiple entries that could match the name of the package.

# Steps to reproduce

Create a pacakge.json file with a package (Microsoft.Teams or Microsoft.Office) that has a name that match multple packages. 
```json
				{
					"PackageIdentifier": "Microsoft.Teams"
				}
			],
			"SourceDetails" : 
			{
				"Argument" : "https://winget.azureedge.net/cache",
				"Identifier" : "Microsoft.Winget.Source_8wekyb3d8bbwe",
				"Name" : "winget",
				"Type" : "Microsoft.PreIndexed.Package"
			}
```
Do a `winget import package.json`

# Expected behavior

Installation happen without error.

# Actual behavior

Logs can be found in this feedback: https://aka.ms/AAco2lu
![image](https://user-images.githubusercontent.com/15186176/119275660-9f216380-bc16-11eb-9383-8932fde3cdf9.png)
error is in french but it basically just says Microsoft.Teams name match multiple packages.

# Environment

```none
[winget --info]
Windows Package Manager v0.4.11391
Windows: Windows.Desktop v10.0.19042.985
Package: Microsoft.DesktopAppInstaller v1.11.11391.0

Any other software?
```

**Comment by denelon** [comment]
We haven't reproduced this issue yet. We're going to look into this further, and may add logging and see if we can reproduce. If not, we will likely ask for you to submit Feedback https://aka.ms/winget-feedback.

**Comment by TechWatching** [comment]
As indicated in the issue description, you can already find my feedback with the logs [here](https://aka.ms/AAco2lu).
![image](https://user-images.githubusercontent.com/15186176/119570630-ab412880-bdb0-11eb-9a85-b200c8fa35d7.png)
Tell me if you need more info.

**Comment by denelon** [comment]
@TechWatching I was mentioning that we may need to add "more" logging (in a newer version) and get feedback after that point. Sorry for the confusion.

**Comment by Nollknolle** [comment]
Same issue
