### ISSUE TITLE
Install winget without needing Microsoft Store

### ISSUE THREAD

**Issue by AlfonsoCampodonico** [microsoft/winget-cli#992]
# Description of the new feature/enhancement

Be able to download winget-cli and install it without using the microsoft store . Example as a .msixbundle like terminal

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/releases/tag/v1.0.11451 is the current release.

The "Assets" include the .appxbundle:
https://github.com/microsoft/winget-cli/releases/download/v1.0.11451/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle

Short URL: https://aka.ms/getwinget

Appx protocol activation: [ms-appinstaller:?source=https://aka.ms/getwinget](ms-appinstaller:?source=https://aka.ms/getwinget)

**Comment by AlfonsoCampodonico** [comment]
Just for anyone else that might have the same trouble as i , the way to install it is using Windows Powershell (not 7.1.3) and using:

`Add-AppxPackage -Path "C:\Users\user\Downloads\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle"`

This way it will install correctly

This was the error when i double clicked the appxbundle 
![image](https://user-images.githubusercontent.com/38387367/119744037-86f15480-be61-11eb-84f4-83e6f6dd2faf.png)

Thanks for such a wonderful app! Cheers!
