### ISSUE TITLE
Inform users a reboot is required after installation

### ISSUE THREAD

**Issue by lychichem** [microsoft/winget-cli#994]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue
When using winget to install Microsoft.VC++2015-2019Redist-x64, winget reports the installer failed with exit code: 3010
# Steps to reproduce
Install Microsoft.VC++2015-2019Redist-x64 with `winget install Microsoft.VC++2015-2019Redist-x64`

# Expected behavior
winget should report the installed successfully.

# Actual behavior
winget reports it exit with code 3010. But the package installed.
![image](https://user-images.githubusercontent.com/9316590/119604344-77521b80-be21-11eb-8832-ae7134f5f2da.png)
![image](https://user-images.githubusercontent.com/9316590/119604645-fd6e6200-be21-11eb-8486-970f43e5a5b4.png)

# Environment

```none
[winget --info]
Windows Package Manager version: v0.4.11391
Windows: Windows.Desktop version: 10.0.19043.1023 x64 pro zh-CN
Package: Microsoft.DesktopAppInstaller version: 1.11.11391.0

Any other software?
```
I don't konw which software is using vclibs when winget try to install it. But I strongly believe it means the installer need a system reboot to finish the install. So maybe winget should ask the user to reboot their system to finish the install and report 3010 as successfully.

**Comment by lychichem** [comment]
microsoft/winget-pkgs#14033 will treat 3010 as success. But we need to ask users to manually reboot their system.

**Comment by denelon** [comment]
@lychichem I don't recall another feature on the backlog addressing a generic reboot required. Would you mind a more generic title change? "Inform users a reboot is required after installation". I think we may need a manifest schema change "InstallerSuccessCodes" doesn't seem to capture this scenario well. 

I'm not sure if we want something specific just for this scenario, or something more generic or extensible. Testing and validation become much more complicated depending on the choice made. #229 "Suppress reboot on default" might be involved in the solution as well.

**Comment by lychichem** [comment]
> @lychichem I don't recall another feature on the backlog addressing a generic reboot required. Would you mind a more generic title change? "Inform users a reboot is required after installation". I think we may need a manifest schema change "InstallerSuccessCodes" doesn't seem to capture this scenario well. 
> 
> 
> 
> I'm not sure if we want something specific just for this scenario, or something more generic or extensible. Testing and validation become much more complicated depending on the choice made. #229 "Suppress reboot on default" might be involved in the solution as well.
> 
> 
> 
> 

Yes, you're right. This is a specific scene when the package installed is using by other program.

**Comment by denelon** [comment]
> However, if we really keep the last two types of virtual machine for every package, we will certainly cost a lot of storage space and make the system dirty at end.

That sounds like a fun engineering problem to solve. Fortunately, we are able to stand up "clean" virtual machines fairly easily. The interesting parts are figuring out which dependencies or other packages cause these conflicts while trying to install/upgrade/import.

**Comment by denelon** [comment]
@lychichem we've done some additional work with "Expected Return Codes". I believe 3010 should inform the user a reboot is required. Can you validate?

**Comment by OskarKlintrot** [comment]
It's not stale, we're just waiting :)

**Comment by denelon** [comment]
The 14.29.30139.0 Microsoft.VC++2015-2019Redist-x64 manifest currently treats the return code 3010 as success.

https://github.com/microsoft/winget-pkgs/blob/fc8bbeb8603e04e6d14584e04f5c8d7d7c0c1892/manifests/m/Microsoft/VC%2B%2B2015-2019Redist-x64/14.29.30139.0/Microsoft.VC%2B%2B2015-2019Redist-x64.installer.yaml#L13-L14

@ItzLevvie it looks like you were the last to work on the manifest. Would you mind changing the success code to an expected return code? I'd like to make sure this scenario is properly handled.

Ideally, the install would return 3010 if the runtime is in use, and the user would be informed of the need for a reboot via "rebootRequiredToFinish".

https://github.com/microsoft/winget-cli/blob/f14909aba2578b0b8b57cb700ffcdeddb196f878/schemas/JSON/manifests/v1.2.0/manifest.installer.1.2.0.json#L172-L201

**Comment by denelon** [comment]
I've been investigating this condition a bit more deeply. We're going to experiment with a couple of manifests, and if we can confirm the correct behavior, we're going to make this adjustment in the 1.4 client as a permanent solution.

Ideally, the MSI based installers will have 3010 errors are mapped to the correct expected return code, to address for earlier versions of winget, and going forward, the newer versions of the client will honor the mapping in the manifest and automatically map this error for MSI based installers to "rebootRequiredToFinish".

**Comment by denelon** [comment]
The client now informs the user that a reboot is required.
